### ISSUE TITLE
 --response-timeout option is not working

### ISSUE THREAD

**Issue by ArthurLapraye** [RasaHQ/rasa#10056]
### Rasa Open Source version

2.8.10

### Rasa SDK version

2.8.2

### Python version

3.7

### What operating system are you using?

Windows

### What happened?

In order to circumvent a recurring timeout error, I tried to use the `--response-timeout `command line parameter, [as explained in this forum post](https://forum.rasa.com/t/how-to-prevent-timeout-while-debugging-actions/27560/4).

However, this didn't appear to have any effect. 
I have checked (using print statements added after line 132 in the `rasa/core/channels/console.py ` that the timeout was effectively always set to 10 seconds, no matter the number sent as parameter to `--response-timeout`. 

In fact the relevant variable,  `DEFAULT_STREAM_READING_TIMEOUT_IN_SECONDS ` seems to be hardcoded at the top of the aforementioned file.

### Command / Request

```shell
python -m rasa shell --endpoints .\local_endpoints.yml --response-timeout 100
```

### Relevant log output

```shell
2021-11-02 12:03:03 ERROR    asyncio  - Task exception was never retrieved
future: <Task finished coro=<configure_app.<locals>.run_cmdline_io() done, defined at C:\Users\\progs\BOTFOLDER\.venv2\lib\site-packages\rasa\core\run.py:131> exception=TimeoutError()>
Traceback (most recent call last):
  File "C:\Users\HVFD4178\progs\BOTFOLDER\.venv2\lib\site-packages\rasa\core\run.py", line 137, in run_cmdline_io
    sender_id=conversation_id,
  File "C:\Users\\progs\BOTFOLDER\.venv2\lib\site-packages\rasa\core\channels\console.py", line 183, in record_messages
    async for response in bot_responses:
  File "C:\Users\\progs\BOTFOLDER\.venv2\lib\site-packages\rasa\core\channels\console.py", line 137, in _send_message_receive_stream
    async for line in resp.content:
  File "C:\Users\\progs\BOTFOLDER\.venv2\lib\site-packages\aiohttp\streams.py", line 39, in __anext__
    rv = await self.read_func()
  File "C:\Users\\progs\BOTFOLDER\.venv2\lib\site-packages\aiohttp\streams.py", line 338, in readline
    await self._wait("readline")
  File "C:\Users\\progs\BOTFOLDER\.venv2\lib\site-packages\aiohttp\streams.py", line 306, in _wait
    await waiter
  File "C:\Users\\progs\BOTFOLDER\.venv2\lib\site-packages\aiohttp\helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError
Transport closed @ ('127.0.0.1', 54130) and exception experienced during error handling
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @TyDunn will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗
