### ISSUE TITLE
Rasa sdk breaks on main branch on from validation. 

### ISSUE THREAD

**Issue by koaning** [RasaHQ/rasa#10054]
I am working on translating my forms for 3.x but it seems like there's a difference in what `rasa` sends and what `rasa-sdk` expects. I'm running off the main branch after installing `make install`. This is my `actions.py` file. 

```python
from typing import Text, List, Any, Dict

from rasa_sdk import Tracker, FormValidationAction, Action
from rasa_sdk.events import EventType
from rasa_sdk.executor import CollectingDispatcher
from rasa_sdk.types import DomainDict

ALLOWED_PIZZA_SIZES = ["small", "medium", "large", "extra-large", "extra large", "s", "m", "l", "xl"]
ALLOWED_PIZZA_TYPES = ["mozzarella", "fungi", "veggie", "pepperoni", "hawaii"]

class ValidateSimplePizzaForm(FormValidationAction):
    def name(self) -> Text:
        return "validate_simple_pizza_form"

    def validate_pizza_size(
        self,
        slot_value: Any,
        dispatcher: CollectingDispatcher,
        tracker: Tracker,
        domain: DomainDict,
    ) -> Dict[Text, Any]:
        """Validate `pizza_size` value."""

        if slot_value.lower() not in ALLOWED_PIZZA_SIZES:
            dispatcher.utter_message(text=f"We only accept pizza sizes: s/m/l/xl.")
            return {"pizza_size": None}
        dispatcher.utter_message(text=f"OK! You want to have a {slot_value} pizza.")
        return {"pizza_size": slot_value}

    def validate_pizza_type(
        self,
        slot_value: Any,
        dispatcher: CollectingDispatcher,
        tracker: Tracker,
        domain: DomainDict,
    ) -> Dict[Text, Any]:
        """Validate `pizza_type` value."""

        if slot_value not in ALLOWED_PIZZA_TYPES:
            dispatcher.utter_message(text=f"I don't recognize that pizza. We serve {'/'.join(ALLOWED_PIZZA_TYPES)}.")
            return {"pizza_type": None}
        dispatcher.utter_message(text=f"OK! You want to have a {slot_value} pizza.")
        return {"pizza_type": slot_value}
```

This validator used to work in Rasa 2.x, but now during `rasa interactive` I see this in the action server. 

```
> rasa run actions
2021-11-02 11:16:17 INFO     rasa_sdk.endpoint  - Starting action endpoint server...
2021-11-02 11:16:17 INFO     rasa_sdk.executor  - Registered function for 'validate_simple_pizza_form'.
2021-11-02 11:16:17 INFO     rasa_sdk.endpoint  - Action endpoint is up and running on http://0.0.0.0:5055
^C%               
(venv) ➜  rasa run actions
2021-11-02 11:39:13 INFO     rasa_sdk.endpoint  - Starting action endpoint server...
2021-11-02 11:39:13 INFO     rasa_sdk.executor  - Registered function for 'validate_simple_pizza_form'.
2021-11-02 11:39:13 INFO     rasa_sdk.endpoint  - Action endpoint is up and running on http://0.0.0.0:5055


Exception occurred while handling uri: 'http://localhost:5055/webhook'
Traceback (most recent call last):
  File "/Users/vincent/Development/rasa/venv/lib/python3.7/site-packages/sanic/app.py", line 939, in handle_request
    response = await response
  File "/Users/vincent/Development/rasa/venv/lib/python3.7/site-packages/rasa_sdk/endpoint.py", line 104, in webhook
    result = await executor.run(action_call)
  File "/Users/vincent/Development/rasa/venv/lib/python3.7/site-packages/rasa_sdk/executor.py", line 398, in run
    action(dispatcher, tracker, domain)
  File "/Users/vincent/Development/rasa/venv/lib/python3.7/site-packages/rasa_sdk/utils.py", line 230, in call_potential_coroutine
    return await coroutine_or_return_value
  File "/Users/vincent/Development/rasa/venv/lib/python3.7/site-packages/rasa_sdk/forms.py", line 695, in run
    extraction_events = await self.extract_custom_slots(dispatcher, tracker, domain)
  File "/Users/vincent/Development/rasa/venv/lib/python3.7/site-packages/rasa_sdk/forms.py", line 735, in extract_custom_slots
    self.slots_mapped_in_domain(domain), dispatcher, tracker, domain
  File "/Users/vincent/Development/rasa/venv/lib/python3.7/site-packages/rasa_sdk/forms.py", line 830, in slots_mapped_in_domain
    required_slots = form.get("required_slots", {}).keys()
AttributeError: 'list' object has no attribute 'keys'
Exception occurred while handling uri: 'http://localhost:5055/webhook'
Traceback (most recent call last):
  File "/Users/vincent/Development/rasa/venv/lib/python3.7/site-packages/sanic/app.py", line 939, in handle_request
    response = await response
  File "/Users/vincent/Development/rasa/venv/lib/python3.7/site-packages/rasa_sdk/endpoint.py", line 104, in webhook
    result = await executor.run(action_call)
  File "/Users/vincent/Development/rasa/venv/lib/python3.7/site-packages/rasa_sdk/executor.py", line 398, in run
    action(dispatcher, tracker, domain)
  File "/Users/vincent/Development/rasa/venv/lib/python3.7/site-packages/rasa_sdk/utils.py", line 230, in call_potential_coroutine
    return await coroutine_or_return_value
  File "/Users/vincent/Development/rasa/venv/lib/python3.7/site-packages/rasa_sdk/forms.py", line 695, in run
    extraction_events = await self.extract_custom_slots(dispatcher, tracker, domain)
  File "/Users/vincent/Development/rasa/venv/lib/python3.7/site-packages/rasa_sdk/forms.py", line 735, in extract_custom_slots
    self.slots_mapped_in_domain(domain), dispatcher, tracker, domain
  File "/Users/vincent/Development/rasa/venv/lib/python3.7/site-packages/rasa_sdk/forms.py", line 830, in slots_mapped_in_domain
    required_slots = form.get("required_slots", {}).keys()
AttributeError: 'list' object has no attribute 'keys'
```

Looking at the trace, it seems like this is unrelated to my `actions.py` file and it may be more related to something internal. I can provide more details is needed.

**Comment by koaning** [comment]
This is the error message from `rasa interactive`.

```
2021-11-02 11:44:39 ERROR    rasa.core.processor  - Encountered an exception while running action 'simple_pizza_form'.Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
Traceback (most recent call last):
  File "/Users/vincent/Development/rasa/rasa/core/actions/action.py", line 724, in run
    json=json_body, method="post", timeout=DEFAULT_REQUEST_TIMEOUT
  File "/Users/vincent/Development/rasa/rasa/utils/endpoints.py", line 174, in request
    response.status, response.reason, await response.content.read()
rasa.utils.endpoints.ClientResponseError: 500, Internal Server Error, body='b'<!DOCTYPE html><html lang=en><meta charset=UTF-8><title>\xe2\x9a\xa0\xef\xb8\x8f 500 \xe2\x80\x94 Internal Server Error</title>\n<style>\n        html { font-family: sans-serif }\n        h2 { color: #888; }\n        .tb-wrapper p { margin: 0 }\n        .frame-border { margin: 1rem }\n        .frame-line > * { padding: 0.3rem 0.6rem }\n        .frame-line { margin-bottom: 0.3rem }\n        .frame-code { font-size: 16px; padding-left: 4ch }\n        .tb-wrapper { border: 1px solid #eee }\n        .tb-header { background: #eee; padding: 0.3rem; font-weight: bold }\n        .frame-descriptor { background: #e2eafb; font-size: 14px }\n    </style>\n<h1>\xe2\x9a\xa0\xef\xb8\x8f 500 \xe2\x80\x94 Internal Server Error</h1><p>The server encountered an internal error and cannot complete your request.\n''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/vincent/Development/rasa/rasa/core/processor.py", line 846, in _run_action
    output_channel, nlg, temporary_tracker, self.domain
  File "/Users/vincent/Development/rasa/rasa/core/actions/loops.py", line 29, in run
    events += await self.do(output_channel, nlg, tracker, domain, events)
  File "/Users/vincent/Development/rasa/rasa/core/actions/forms.py", line 600, in do
    events = await self._validate_if_required(tracker, domain, output_channel, nlg)
  File "/Users/vincent/Development/rasa/rasa/core/actions/forms.py", line 540, in _validate_if_required
    return await self.validate(tracker, domain, output_channel, nlg)
  File "/Users/vincent/Development/rasa/rasa/core/actions/forms.py", line 393, in validate
    slot_values, tracker, domain, output_channel, nlg
  File "/Users/vincent/Development/rasa/rasa/core/actions/forms.py", line 262, in validate_slots
    validate_events = await _action.run(output_channel, nlg, _tracker, domain)
  File "/Users/vincent/Development/rasa/rasa/core/actions/action.py", line 747, in run
    raise RasaException("Failed to execute custom action.") from e
rasa.shared.exceptions.RasaException: Failed to execute custom action.
```

**Comment by ancalita** [comment]
@koaning I don't think you're running `rasa-sdk` in editable mode from `main` 🤔 . 

There were edits made in  rasa-sdk `forms.py`, my bad for not accurately pointing these out in my announcement last week (I only realised yesterday while looking through my docs PR that actually `FormValidationAction` doesn't have `slots_mapped_in_domain` method anymore and that was replaced with [`domain_slots()` ](https://github.com/RasaHQ/rasa-sdk/blob/2a2f08c59ae434232497643b6c7b40399a83adcf/rasa_sdk/forms.py#L285) which gets fed as parameter into `required_slots` which can still be overridden.)

**Comment by koaning** [comment]
Ah! Let's try that then. Just to check ... to run `rasa-sdk` in editable mode together with the rasa main branch ... would I need to clone both repositories and run `make install` from both? I'm worried this won't work since the `.lock` file on rasa main has: 

```
[[package]]
name = "rasa-sdk"
version = "2.8.2"
category = "main"
optional = false
python-versions = ">=3.6,<3.9"
```

The version seems pinned, no?

**Comment by ancalita** [comment]
> would I need to clone both repositories and run make install from both?

Yup exactly, first you'd need to clone `rasa` and run `make install`, then do the same for `rasa-sdk`, more details in the [Python Development Set-up](https://www.notion.so/rasa/Python-Development-Setup-6a7308797283415b9a66b4d5985437fd#cb351380268a4373b523293a378dc517).

**Comment by koaning** [comment]
This seems fixed in RC01. Closing.
