### ISSUE TITLE
`rasa init` saves model in wrong location

### ISSUE THREAD

**Issue by joejuzl** [RasaHQ/rasa#10105]
### Rasa Open Source version

3.0.0rc1

### Python version

3.8

### What operating system are you using?

OSX

### What happened?

When running `rasa init` and training an initial model it does this:
`Your Rasa model is trained and saved at 'models/20211108-141844.tar.gz/20211108-141847-mature-reflection.tar.gz'.`

Whereas it should be saving it to `models/20211108-141847-mature-reflection.tar.gz`.

### Command / Request

```shell
rasa init
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/Users/josephjuzl/.pyenv/versions/rasa3rc/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/Users/josephjuzl/.pyenv/versions/3.8.6/envs/rasa3rc/lib/python3.8/site-packages/rasa/__main__.py", line 121, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/Users/josephjuzl/.pyenv/versions/3.8.6/envs/rasa3rc/lib/python3.8/site-packages/rasa/cli/shell.py", line 112, in shell
    metadata = LocalModelStorage.metadata_from_archive(model)
  File "/Users/josephjuzl/.pyenv/versions/3.8.6/envs/rasa3rc/lib/python3.8/site-packages/rasa/engine/storage/local_model_storage.py", line 80, in metadata_from_archive
    cls._extract_archive_to_directory(model_archive_path, temporary_directory)
  File "/Users/josephjuzl/.pyenv/versions/3.8.6/envs/rasa3rc/lib/python3.8/site-packages/rasa/engine/storage/local_model_storage.py", line 89, in _extract_archive_to_directory
    with TarSafe.open(model_archive_path, mode="r:gz") as tar:
  File "/Users/josephjuzl/.pyenv/versions/3.8.6/envs/rasa3rc/lib/python3.8/site-packages/tarsafe/tarsafe.py", line 15, in open
    return super().open(name, mode, fileobj, bufsize, **kwargs)
  File "/Users/josephjuzl/.pyenv/versions/3.8.6/lib/python3.8/tarfile.py", line 1619, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/Users/josephjuzl/.pyenv/versions/3.8.6/lib/python3.8/tarfile.py", line 1665, in gzopen
    fileobj = GzipFile(name, mode + "b", compresslevel, fileobj)
  File "/Users/josephjuzl/.pyenv/versions/3.8.6/lib/python3.8/gzip.py", line 173, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
IsADirectoryError: [Errno 21] Is a directory: 'models/20211108-141947.tar.gz'
```

**Comment by tayfun** [comment]
Duplicate of https://github.com/RasaHQ/rasa/issues/10101 :)

**Comment by joejuzl** [comment]
👍 will close this one then
