### ISSUE TITLE
Global Slot Mappings: Dynamic slots not considered in `_get_slot_extractions`

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#10118]
### Rasa Open Source version

3.0.0rc1

### Rasa SDK version

3.0.0rc1

### Python version

3.9

### What operating system are you using?

OSX

### What happened?

When I try to fill a dynamically requested slot a `ActionExecutionRejection` is raised.

To reproduce:

1. Specify a form and a required slot
2. Add a `validate_<form_name>` action to your domain
3. Override `required_slots` in your `FormValidationAction` so that it requests a `slot2` if `slot1` as a certain value
4. When Rasa Open Source asks you to fill slot2 → fill it
5. Expected: Form is submitted since all values are filled
Actual: The form rejects it's execution as `_get_slot_extractions` returns an empty list. As this means we have a `slot_to_validate` and `some_slots_were_validated==False` the form rejects its execution

```python
version: "2.0"

intents:
  - greet
  - goodbye
  - affirm
  - deny
  - mood_great
  - mood_unhappy
  - bot_challenge
  - start_form

actions:
  - validate_tobi_form

entities:
  - entity1
  - entity2
  - entity3
  - entity4
  - entity5
  - entity6

slots:
  slot1:
    type: any
    influence_conversation: false
    mappings:
    - type: from_entity
      entity: entity1
      conditions:
      - active_loop: tobi_form
        requested_slot: slot1

  slot2:
    type: any
    influence_conversation: false
    mappings:
    - type: from_entity
      entity: entity1
      conditions:
      - active_loop: tobi_form
        requested_slot: slot2

responses:
  utter_greet:
  - text: "Hey! How are you?"

  utter_cheer_up:
  - text: "Here is something to cheer you up:"
    image: "https://i.imgur.com/nGF1K8f.jpg"

  utter_did_that_help:
  - text: "Did that help you?"

  utter_happy:
  - text: "Great, carry on!"

  utter_goodbye:
  - text: "Bye"

  utter_iamabot:
  - text: "I am a bot, powered by Rasa."

  utter_ask_slot1:
  - text: "Slot 1 please"

  utter_ask_slot2:
  - text: "Slot 2 please"

  utter_ask_slot3:
  - text: "Slot 3 please"

  utter_ask_slot4:
  - text: "Slot 4 please"

  utter_ask_slot5:
  - text: "Slot 5 please"

  utter_ask_slot6:
  - text: "Slot 6 please"

  utter_submit:
  - text: "Submitted"

session_config:
  session_expiration_time: 60
  carry_over_slots_to_new_session: true

forms:
  tobi_form:
    required_slots:
    - slot1
```

```python
from typing import Dict, Text, Any, List

from rasa_sdk import Tracker
from rasa_sdk.executor import CollectingDispatcher
from rasa_sdk.forms import FormValidationAction

class TobiFormValidation(FormValidationAction):
    def name(self) -> Text:
        return "validate_tobi_form"

    async def required_slots(
        self,
        domain_slots: List[Text],
        dispatcher: "CollectingDispatcher",
        tracker: "Tracker",
        domain: "DomainDict",
    ) -> List[Text]:
        """Returns slots which the validation action should fill.

        Args:
            domain_slots: Names of slots of this form which were mapped in
                the domain.
            dispatcher: the dispatcher which is used to
                send messages back to the user.
            tracker: the conversation tracker for the current user.
            domain: the bot's domain.

        Returns:
            A list of slot names.
        """
        if tracker.slots["slot1"] == "beer":
            return domain_slots + ["slot2"]

        return domain_slots
```

**Comment by ancalita** [comment]
@wochinge To double-check that I've replicated this correctly, after the 2nd slot gets requested and user message fills the slot, the bot crashes in a `rasa.engine.exceptions.GraphComponentException: Error running graph component for node select_prediction.` and in the debug log I see this: `DEBUG    rasa.core.policies.ensemble  - Execution of 'some_form' was rejected. Setting its confidence to 0.0 in all predictions.` Is that how you inferred the problem for this?

**Comment by wochinge** [comment]
exactly 👍🏻 Although the exception shouldn't happen 🙈 Do you have a stack trace?

**Comment by ancalita** [comment]
This is the traceback I got after I force exited `rasa shell` (via CTRL+C) - because I realised the bot crashed when I saw asyncio.TimeoutError:

```
Traceback (most recent call last):
  File "/Users/ancalita/rasa-projects/qa-rc1/lib/python3.8/site-packages/rasa/engine/graph.py", line 455, in __call__
    output = self._fn(self._component, **run_kwargs)
  File "/Users/ancalita/rasa-projects/qa-rc1/lib/python3.8/site-packages/rasa/core/policies/ensemble.py", line 102, in combine_predictions_from_kwargs
    return self.combine_predictions(
  File "/Users/ancalita/rasa-projects/qa-rc1/lib/python3.8/site-packages/rasa/core/policies/ensemble.py", line 310, in combine_predictions
    winning_prediction = self._best_policy_prediction(
  File "/Users/ancalita/rasa-projects/qa-rc1/lib/python3.8/site-packages/rasa/core/policies/ensemble.py", line 276, in _best_policy_prediction
    prediction.probabilities[index_of_rejected_action] = 0.0
IndexError: list assignment index out of range

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/ancalita/rasa-projects/qa-rc1/lib/python3.8/site-packages/rasa/core/channels/rest.py", line 47, in on_message_wrapper
    await on_new_message(message)
  File "/Users/ancalita/rasa-projects/qa-rc1/lib/python3.8/site-packages/rasa/core/channels/channel.py", line 89, in handler
    await app.agent.handle_message(message)
  File "/Users/ancalita/rasa-projects/qa-rc1/lib/python3.8/site-packages/rasa/core/agent.py", line 430, in handle_message
    return await self.processor.handle_message(message)
  File "/Users/ancalita/rasa-projects/qa-rc1/lib/python3.8/site-packages/rasa/core/processor.py", line 136, in handle_message
    await self._run_prediction_loop(message.output_channel, tracker)
  File "/Users/ancalita/rasa-projects/qa-rc1/lib/python3.8/site-packages/rasa/core/processor.py", line 734, in _run_prediction_loop
    action, prediction = self.predict_next_with_tracker_if_should(tracker)
  File "/Users/ancalita/rasa-projects/qa-rc1/lib/python3.8/site-packages/rasa/core/processor.py", line 436, in predict_next_with_tracker_if_should
    prediction = self._predict_next_with_tracker(tracker)
  File "/Users/ancalita/rasa-projects/qa-rc1/lib/python3.8/site-packages/rasa/core/processor.py", line 962, in _predict_next_with_tracker
    results = self.graph_runner.run(
  File "/Users/ancalita/rasa-projects/qa-rc1/lib/python3.8/site-packages/rasa/engine/runner/dask.py", line 106, in run
    dask_result = dask.get(run_graph, run_targets)
  File "/Users/ancalita/rasa-projects/qa-rc1/lib/python3.8/site-packages/dask/local.py", line 560, in get_sync
    return get_async(
  File "/Users/ancalita/rasa-projects/qa-rc1/lib/python3.8/site-packages/dask/local.py", line 503, in get_async
    for key, res_info, failed in queue_get(queue).result():
  File "/Users/ancalita/.pyenv/versions/3.8.6/lib/python3.8/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/Users/ancalita/.pyenv/versions/3.8.6/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/Users/ancalita/rasa-projects/qa-rc1/lib/python3.8/site-packages/dask/local.py", line 545, in submit
    fut.set_result(fn(*args, **kwargs))
  File "/Users/ancalita/rasa-projects/qa-rc1/lib/python3.8/site-packages/dask/local.py", line 237, in batch_execute_tasks
    return [execute_task(*a) for a in it]
  File "/Users/ancalita/rasa-projects/qa-rc1/lib/python3.8/site-packages/dask/local.py", line 237, in <listcomp>
    return [execute_task(*a) for a in it]
  File "/Users/ancalita/rasa-projects/qa-rc1/lib/python3.8/site-packages/dask/local.py", line 228, in execute_task
    result = pack_exception(e, dumps)
  File "/Users/ancalita/rasa-projects/qa-rc1/lib/python3.8/site-packages/dask/local.py", line 223, in execute_task
    result = _execute_task(task, data)
  File "/Users/ancalita/rasa-projects/qa-rc1/lib/python3.8/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/Users/ancalita/rasa-projects/qa-rc1/lib/python3.8/site-packages/rasa/engine/graph.py", line 461, in __call__
    raise GraphComponentException(
rasa.engine.exceptions.GraphComponentException: Error running graph component for node select_prediction.
```

**Comment by wochinge** [comment]
@ancalita I think the exception is related to something @joejuzl has discovered and is working on. Can you please try to delete the cache with `rm -r .rasa` and then retry validating this?

**Comment by ancalita** [comment]
@wochinge Ok, after removing the cache, I ran `rasa train` and then `rasa shell --debug` and the slots were filled, but the form was not deactivated but rejected, as you said, and a different bot response was predicted rather than `utter_submit`. No exception was raised this time.
