### ISSUE TITLE
none type object is not iterable error in test

### ISSUE THREAD

**Issue by simonm3** [RasaHQ/rasa#10438]
### Rasa Open Source version

2.8.15-full

### Python version

3.8

### What operating system are you using?

Linux

### What happened?

Ran the github actions script for train_test. Trains fine but raises exception on testing.

### Command / Request

```shell
jobs:
  train_test:
    name: train_test
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v2
      
      - name: train_test
        uses: RasaHQ/rasa-train-test-gha@main
        with:
          rasa_version: 2.8.15-full
```

### Relevant log output

```shell
2021-12-01 17:41:55 INFO     rasa.core.test  - Finished collecting predictions.
2021-12-01 17:41:55 INFO     rasa.core.test  - Evaluation Results on CONVERSATION level:
2021-12-01 17:41:55 INFO     rasa.core.test  - 	Correct:          12 / 12
2021-12-01 17:41:55 INFO     rasa.core.test  - 	Accuracy:         1.000
2021-12-01 17:41:55 INFO     rasa.core.test  - Stories report saved to results/story_report.json.
Traceback (most recent call last):
  File "/opt/venv/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/opt/venv/lib/python3.8/site-packages/rasa/__main__.py", line 118, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/opt/venv/lib/python3.8/site-packages/rasa/cli/test.py", line 133, in run_core_test
    test_core(
  File "/opt/venv/lib/python3.8/site-packages/rasa/model_testing.py", line 182, in test_core
    rasa.utils.common.run_in_loop(
  File "/opt/venv/lib/python3.8/site-packages/rasa/utils/common.py", line 296, in run_in_loop
    result = loop.run_until_complete(f)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/opt/venv/lib/python3.8/site-packages/rasa/core/test.py", line 1095, in test
    evaluate_entities(
  File "/opt/venv/lib/python3.8/site-packages/rasa/nlu/test.py", line 863, in evaluate_entities
    aligned_predictions = align_all_entity_predictions(entity_results, extractors)
  File "/opt/venv/lib/python3.8/site-packages/rasa/nlu/test.py", line 1223, in align_all_entity_predictions
    aligned_predictions.append(align_entity_predictions(result, extractors))
  File "/opt/venv/lib/python3.8/site-packages/rasa/nlu/test.py", line 1126, in align_entity_predictions
    for t in result.tokens:
TypeError: 'NoneType' object is not iterable
Error: Process completed with exit code 1.
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @joejuzl will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by joejuzl** [comment]
Hi @simonm3 could you give me a bit more context on why/how you are running the github actions?

**Comment by simonm3** [comment]
I was wanting to split the data train/test; train; run tests. I do not want crossvalidation as takes too long. Was expecting the traintest script would split the data; train; test. However it seems to fail. Does it expect the data to be already split train/test?

**Comment by HotThoughts** [comment]
@simonm3 The `rasa-train-test` action expects the data have split alreay. By default, `rasa train` will look for the Core and NLU data files in `data/` folder unless you set the path with the flag `--data <training data directory>`. 

`rasa test` will look for any files that start with `test_`. 

Note that if you have stories for testing, pass it to `rasa test core`, e.g.
```yaml
- name: train_test
  uses: RasaHQ/rasa-train-test-gha@main
  with:
    rasa_version: 2.8.15-full
    test_type: all
    test_core_args: >-
      --stories tests/test_conversations.yml
``` 

Read more about `rasa train` and `rasa test`: 
https://rasa.com/docs/rasa/command-line-interface/#rasa-train
https://rasa.com/docs/rasa/command-line-interface/#rasa-test
