### ISSUE TITLE
rasa train nlu   IndexError: list index out of range

### ISSUE THREAD

**Issue by yuxuan2015** [RasaHQ/rasa#10449]
### Rasa Open Source version

2.3.1

### Rasa SDK version

2.3.1

### Rasa X version

 _No response_ 

### Python version

3.6.13

### What operating system are you using?

ubuntu 16.04

### What happened?

IndexError: list index out of range

config.yml language: zh pipeline:

*   name: SpacyNLP model: "zh_core_web_sm"
*   name: SpacyTokenizer
*   name: SpacyFeaturizer pooling: mean
*   name: DIETClassifier epochs: 100 evaluate_every_num_epochs: 10

### Command / Request

<pre>rasa train nlu</pre>

### Relevant log output

<pre>If I use "zh_core_web_md" to train successfully, but if I use "zh_core_web_sm" or "zh_core_web_lg", the following error will appear 

Traceback (most recent call last):
 File "/home/bb5/anaconda3/envs/rasa231/bin/rasa", line 8, in 

 sys.exit(main())
 File "/home/bb5/anaconda3/envs/rasa231/lib/python3.6/site-packages/rasa/__main__.py", line 116, in main
 cmdline_arguments.func(cmdline_arguments)
 File "/home/bb5/anaconda3/envs/rasa231/lib/python3.6/site-packages/rasa/cli/train.py", line 207, in train_nlu
 finetuning_epoch_fraction=args.epoch_fraction,
 File "/home/bb5/anaconda3/envs/rasa231/lib/python3.6/site-packages/rasa/train.py", line 711, in train_nlu
 finetuning_epoch_fraction=finetuning_epoch_fraction,
 File "/home/bb5/anaconda3/envs/rasa231/lib/python3.6/site-packages/rasa/utils/common.py", line 308, in run_in_loop
 result = loop.run_until_complete(f)
 File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
 File "/home/bb5/anaconda3/envs/rasa231/lib/python3.6/site-packages/rasa/train.py", line 758, in train_nlu_async
 finetuning_epoch_fraction=finetuning_epoch_fraction,
 File "/home/bb5/anaconda3/envs/rasa231/lib/python3.6/site-packages/rasa/train.py", line 819, in _train_nlu_with_validated_data
 **additional_arguments,
 File "/home/bb5/anaconda3/envs/rasa231/lib/python3.6/site-packages/rasa/nlu/train.py", line 116, in train
 interpreter = trainer.train(training_data, **kwargs)
 File "/home/bb5/anaconda3/envs/rasa231/lib/python3.6/site-packages/rasa/nlu/model.py", line 209, in train
 updates = component.train(working_data, self.config, **context)
 File "/home/bb5/anaconda3/envs/rasa231/lib/python3.6/site-packages/rasa/nlu/classifiers/diet_classifier.py", line 838, in train
 self.component_config<span class="error">[BATCH_STRATEGY]</span>,
 File "/home/bb5/anaconda3/envs/rasa231/lib/python3.6/site-packages/rasa/utils/tensorflow/models.py", line 222, in fit
 ) = self._get_tf_train_functions(eager, model_data, batch_strategy)
 File "/home/bb5/anaconda3/envs/rasa231/lib/python3.6/site-packages/rasa/utils/tensorflow/models.py", line 484, in _get_tf_train_functions
 train_dataset_function, self.train_on_batch, eager, "train"
 File "/home/bb5/anaconda3/envs/rasa231/lib/python3.6/site-packages/rasa/utils/tensorflow/models.py", line 466, in _get_tf_call_model_function
 tf_call_model_function(next(iter(init_dataset)))
 File "/home/bb5/anaconda3/envs/rasa231/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
 result = self._call(*args, **kwds)
 File "/home/bb5/anaconda3/envs/rasa231/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 823, in _call
 self._initialize(args, kwds, add_initializers_to=initializers)
 File "/home/bb5/anaconda3/envs/rasa231/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 697, in _initialize
 *args, **kwds))
 File "/home/bb5/anaconda3/envs/rasa231/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2855, in _get_concrete_function_internal_garbage_collected
 graph_function, _, _ = self._maybe_define_function(args, kwargs)
 File "/home/bb5/anaconda3/envs/rasa231/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3213, in _maybe_define_function
 graph_function = self._create_graph_function(args, kwargs)
 File "/home/bb5/anaconda3/envs/rasa231/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3075, in _create_graph_function
 capture_by_value=self._capture_by_value),
 File "/home/bb5/anaconda3/envs/rasa231/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 986, in func_graph_from_py_func
 func_outputs = python_func(*func_args, **func_kwargs)
 File "/home/bb5/anaconda3/envs/rasa231/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 600, in wrapped_fn
 return weak_wrapped_fn().__wrapped__(*args, **kwds)
 File "/home/bb5/anaconda3/envs/rasa231/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 973, in wrapper
 raise e.ag_error_metadata.to_exception(e)
 tensorflow.python.autograph.impl.api.StagingError: in user code:

 /home/bb5/anaconda3/envs/rasa231/lib/python3.6/site-packages/rasa/utils/tensorflow/models.py:295 train_on_batch *
 prediction_loss = self.batch_loss(batch_in)
 /home/bb5/anaconda3/envs/rasa231/lib/python3.6/site-packages/rasa/nlu/classifiers/diet_classifier.py:1441 batch_loss *
 batch_dim = self._get_batch_dim(tf_batch_data<span class="error">[TEXT]</span>)
 /home/bb5/anaconda3/envs/rasa231/lib/python3.6/site-packages/rasa/utils/tensorflow/models.py:1133 _get_batch_dim *
 return tf.shape(attribute_data<span class="error">[SENTENCE]</span><span class="error">[0]</span>)<span class="error">[0]</span>

 IndexError: list index out of range
 </pre>

**Comment by sara-tagger** [comment]
Thanks for the issue, @sebwarnke will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by sebwarnke** [comment]
hi @yuxuan2015, thanks for raising that issue. would it be possible to bump your Rasa version to either version `2.8.15` which is the last major version of Rasa 2 or even to the brand new version `3.0.1`? If so please check whether the issue still persists.

**Comment by yuxuan2015** [comment]
@sebwarnke  if I update rasa version to 2.8.15, the following error will appear
Error: TFLayerConfigException: The attribute signature must contain some sequence-level featuresignatures but none were found
but if I add CountVectorsFeaturizer into the config.yml, it successed

**Comment by koaning** [comment]
That's strange. I can imagine that `sm` models don't always carry vectors but the `md` and `lg` models should work. 

In general though; @yuxuan2015 is there a reason why you're not adding a countvectorizer in your pipeline? I don't speak Chinese so I cannot judge the best practice, but it may be worth a try to train a model without the spaCy features in the pipeline.

**Comment by yuxuan2015** [comment]
@koaning I tried countvectorizer, but the effect is not as good as spaCy features；I tried model zh_core_web_trf-3.2.0, it will appear error, but I haven't tried `lg` model

**Comment by koaning** [comment]
The spaCy transformer models aren't supported in Rasa at the moment. I've added an issue to start considering it since you're not the first person asking. 

Just to check; what part of the score is disappointing? The intent scores? The action predictions? The entity extractions?
