### ISSUE TITLE
Facebook connection not working

### ISSUE THREAD

**Issue by alijundi** [RasaHQ/rasa#10456]
### Rasa Open Source version

2.8.12

### Rasa SDK version

2.8.2

### Rasa X version

0.42.4

### Python version

3.8

### What operating system are you using?

Linux

### What happened?

I followed the steps to connect my messenger on facebook page. Everything is as expected I got the token and secret and tested it with the developer page using the verify and it all works well (through HTTPS)

I am receiveing the below when I get messages from my messenger:

[2021-12-05 15:16:13 +0000] [9428] [ERROR] Exception occurred while handling uri: 'http://XXXXXXXX/webhooks/facebook/webhook'
Traceback (most recent call last):
  File "/home/rasa/venv/lib/python3.8/site-packages/sanic/app.py", line 939, in handle_request
    response = await response
  File "/home/rasa/venv/lib/python3.8/site-packages/rasa/core/channels/facebook.py", line 395, in webhook
    await messenger.handle(request.json, metadata)
  File "/home/rasa/venv/lib/python3.8/site-packages/rasa/core/channels/facebook.py", line 97, in handle
    for message in entry["messaging"]:
KeyError: 'messaging'

where XXXXXXXX is my domain name fully https working fine. I can even go to RASA X using reverse proxy just fine.

I am not sure why this is happnening please keep in mind that I have successfully connected the following:
1- Telegram
2- Rocketchat

All successfully. Not sure why facebook messenger not working.

### Relevant log output

```shell
[2021-12-05 15:16:13 +0000] [9428] [ERROR] Exception occurred while handling uri: 'http://XXXXXXXX/webhooks/facebook/webhook'
Traceback (most recent call last):
  File "/home/rasa/venv/lib/python3.8/site-packages/sanic/app.py", line 939, in handle_request
    response = await response
  File "/home/rasa/venv/lib/python3.8/site-packages/rasa/core/channels/facebook.py", line 395, in webhook
    await messenger.handle(request.json, metadata)
  File "/home/rasa/venv/lib/python3.8/site-packages/rasa/core/channels/facebook.py", line 97, in handle
    for message in entry["messaging"]:
KeyError: 'messaging'
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @dakshvar22 will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by alijundi** [comment]
@sara-tagger and @dakshvar22. I am still stuck with the issue. I am not sure but I feel that it is a Facebook issue. Sending s test message we hook results in a weird error message in Facebook developer page. Can any body confirm this?

**Comment by rgstephens** [comment]
I recently used the Facebook channel following the docs without any problem. There's also been a group reviewing the Instragram on #9446. Are you sure you're following all of the install steps?

**Comment by alijundi** [comment]
@rgstephens I am pretty sure I followed the steps correctly. I am starting to think that Facebook is not sending the message via webhook. The test message webhook in the developer page is not working. There is also a recent case on that in the support forum and still open

**Comment by alijundi** [comment]
the test webhook for messages in facebook is now working and showing success. However RASA is still shown the error every time I send a test message from facebook messenger webhook.

```
Traceback (most recent call last):
  File "/home/rasa/venv/lib/python3.8/site-packages/sanic/app.py", line 939, in handle_request
    response = await response
  File "/home/rasa/venv/lib/python3.8/site-packages/rasa/core/channels/facebook.py", line 395, in webhook
    messenger = Messenger(self.fb_access_token, on_new_message)
  File "/home/rasa/venv/lib/python3.8/site-packages/rasa/core/channels/facebook.py", line 97, in handle
    print(payload["entry"])
KeyError: 'messaging'
```
