### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f916' in position 17: character maps to <undefined>

### ISSUE THREAD

**Issue by koaning** [RasaHQ/rasa#10581]
On Windows, it seems telemetry is causing issues when users try to run `rasa init`. This has been confirmed on Python 3.7/3.8 as well as Windows 2019 and Windows 2022.

    > python -m rasa init --no-prompt

    2021-12-23 11:03:06 ERROR    rasa.telemetry  - Failed to initialize telemetry reporting: 'charmap' codec can't encode characters in position 0-81: character maps to <undefined>.Telemetry reporting will be disabled.
    Traceback (most recent call last):
      File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\rasa\telemetry.py", line 155, in _is_telemetry_enabled_in_configuration
        stored_config = rasa_utils.read_global_config_value(
      File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\rasa\utils\common.py", line 289, in read_global_config_value
        return not_found()
      File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\rasa\utils\common.py", line 282, in not_found
        raise ValueError(f"Configuration '{name}' key not found.")
    ValueError: Configuration 'metrics' key not found.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\rasa\telemetry.py", line 199, in initialize_telemetry
        is_enabled_in_configuration = _is_telemetry_enabled_in_configuration()
      File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\rasa\telemetry.py", line 164, in _is_telemetry_enabled_in_configuration
        success = _write_default_telemetry_configuration()
      File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\rasa\telemetry.py", line 141, in _write_default_telemetry_configuration
        print_telemetry_reporting_info()
      File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\rasa\telemetry.py", line 118, in print_telemetry_reporting_info
        print(table.table)
      File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-81: character maps to <undefined>
    Traceback (most recent call last):
      File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\runpy.py", line 194, in _run_module_as_main
        return _run_code(code, main_globals, None,
      File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\runpy.py", line 87, in _run_code
        exec(code, run_globals)
      File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\rasa\__main__.py", line 139, in <module>
        main()
      File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\rasa\__main__.py", line 121, in main
        cmdline_arguments.func(cmdline_arguments)
      File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\rasa\cli\scaffold.py", line 188, in run
        print_success("Welcome to Rasa! \U0001f916\n")
      File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\rasa\shared\utils\cli.py", line 21, in print_success
        print_color(*args, color=rasa.shared.utils.io.bcolors.OKGREEN)
      File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\rasa\shared\utils\cli.py", line 15, in print_color
        print(output, file=stream)
      File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\colorama\ansitowin32.py", line 41, in write
        self.__convertor.write(text)
      File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\colorama\ansitowin32.py", line 162, in write
        self.write_and_convert(text)
      File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\colorama\ansitowin32.py", line 187, in write_and_convert
        self.write_plain_text(text, cursor, start)
      File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\site-packages\colorama\ansitowin32.py", line 195, in write_plain_text
        self.wrapped.write(text[start:end])
      File "C:\hostedtoolcache\windows\Python\3.8.10\x64\lib\encodings\cp1252.py", line 19, in encode
        return codecs.charmap_encode(input,self.errors,encoding_table)[0]
    UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f916' in position 17: character maps to <undefined>

You can confirm this issue from the Github Action logs [here| https://github.com/RasaHQ/rasa-install-cron/runs/4617161434?check_suite_focus=true]. In particular it seems part of the issue is caused by `\U0001f916` which is the 
 <g-emoji class="g-emoji" alias="robot" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f916.png">
  🤖 
</g-emoji> robot emoji.

**Comment by koaning** [comment]
The cronjob has since moved to the core Rasa repository. More recent logs can be found [here](https://github.com/RasaHQ/rasa/runs/4934904748?check_suite_focus=true).
