### ISSUE TITLE
Triggering intent externally results in error in Telegram set_webhook function

### ISSUE THREAD

**Issue by Ra0k** [RasaHQ/rasa#10666]
### Rasa Open Source version

2.8.3

### Rasa SDK version

 _No response_ 

### Rasa X version

 _No response_ 

### Python version

3.8

### What operating system are you using?

Linux

### What happened?

I use my chatbot with Telegram. Recently, I implemented a script to trigger an intent every day once. For the first time, it works, but after it fails. Based on the logs, after the message was sent, Rasa tries to set the webhook again, which is completely unnecessary and also fails.

### Command / Request

 _No response_ 

### Relevant log output

<pre>2022-01-11 14:08:50 DEBUG rasa.core.policies.ted_policy - TED predicted 'action_listen' based on user intent.
 2022-01-11 14:08:50 DEBUG rasa.core.policies.form_policy - There is an active form 'daily_fruit_form'
 2022-01-11 14:08:50 DEBUG rasa.core.policies.ensemble - Predicted next action using policy_1_RulePolicy.
 2022-01-11 14:08:50 DEBUG rasa.core.processor - Predicted next action 'action_listen' with confidence 1.00.
 2022-01-11 14:08:50 DEBUG rasa.core.processor - Policy prediction ended with events '[]'.
 2022-01-11 14:08:50 DEBUG rasa.core.processor - Action 'action_listen' ended with events '[]'.
 2022-01-11 14:08:50 DEBUG rasa.core.tracker_store - Tracker with sender_id '5014576014' stored to database
 2022-01-11 14:08:50 DEBUG rasa.core.lock_store - Deleted lock for conversation '5014576014'.
 2022-01-11 14:08:50 DEBUG rasa.core.lock_store - Issuing ticket for conversation '1229077416'.
 2022-01-11 14:08:50 DEBUG rasa.core.lock_store - Acquiring lock for conversation '1229077416'.
 2022-01-11 14:08:50 DEBUG rasa.core.lock_store - Acquired lock for conversation '1229077416'.
 2022-01-11 14:08:51 DEBUG rasa.core.tracker_store - Recreating tracker from sender id '1229077416'
 2022-01-11 14:08:51 DEBUG urllib3.connectionpool - [https://api.telegram.org:443](https://api.telegram.org:443)([https://api.telegram.org:443](https://api.telegram.org:443)) "GET /botxxxxxxxx:XXXXXXXXXXXXX/setWebhook?url=https%3A%2F%2FXXXXXXXXXXXX%2Fwebhooks%2Ftelegram%2Fwebhook HTTP/1.1" 429 109
 2022-01-11 14:08:51 DEBUG rasa.core.lock_store - Deleted lock for conversation '1229077416'.
 2022-01-11 14:08:51 DEBUG rasa.server - Traceback (most recent call last):
 File "/opt/venv/lib/python3.8/site-packages/rasa/core/channels/telegram.py", line 284, in get_output_channel
 channel.set_webhook(url=self.webhook_url)
 File "/opt/venv/lib/python3.8/site-packages/telebot/__init__.py", line 321, in set_webhook
 return apihelper.set_webhook(self.token, url, certificate, max_connections, allowed_updates, ip_address,
 File "/opt/venv/lib/python3.8/site-packages/telebot/apihelper.py", line 279, in set_webhook
 return _make_request(token, method_url, params=payload, files=files)
 File "/opt/venv/lib/python3.8/site-packages/telebot/apihelper.py", line 145, in _make_request
 json_result = _check_result(method_name, result)
 File "/opt/venv/lib/python3.8/site-packages/telebot/apihelper.py", line 172, in _check_result
 raise ApiTelegramException(method_name, result, result_json)
 telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 429\. Description: Too Many Requests: retry after 1
 The above exception was the direct cause of the following exception:
 Traceback (most recent call last):
 File "/opt/venv/lib/python3.8/site-packages/rasa/server.py", line 953, in trigger_intent
 output_channel = _get_output_channel(request, tracker)
 File "/opt/venv/lib/python3.8/site-packages/rasa/server.py", line 1444, in _get_output_channel
 return reduce(
 File "/opt/venv/lib/python3.8/site-packages/rasa/server.py", line 1446, in 

input_channel.get_output_channel() or output_channel_created_so_far
 File "/opt/venv/lib/python3.8/site-packages/rasa/core/channels/telegram.py", line 286, in get_output_channel
 raise RasaException(
 rasa.shared.exceptions.RasaException: Failed to set channel webhook: A request to the Telegram API was unsuccessful. Error code: 429\. Description: Too Many Requests: retry after 1
 2022-01-11 14:08:51 ERROR rasa.server - An unexpected error occurred. Error: Failed to set channel webhook: A request to the Telegram API was unsuccessful. Error code: 429\. Description: Too Many Requests: retry after 1
 </pre>

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @jupyterjazz will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
