### ISSUE TITLE
Error with SpacyTokenizer `token_pattern` causing mismatched Spacy vs. Rasa tokens

### ISSUE THREAD

**Issue by melindaloubser1** [RasaHQ/rasa#10744]
### Rasa Open Source version

2.8.17

### Python version

3.8

### What happened?

Given:

1.  A config with `SpacyTokenizer` with a `token_pattern`, SpacyFeaturizer, and at least one non-spacy token based featurizer (CountVectorsFeaturizer, LexicalSyntacticFeaturizer):

language: en pipeline:

*   name: SpacyNLP case_sensitive: false model: en_core_web_md
*   name: SpacyTokenizer token_pattern: "(\d+| D+)"
*   name: SpacyFeaturizer
*   name: CountVectorsFeaturizer
*   name: DIETClassifier epochs: 10 constrain_similarities: true

1.  Input with multiple digits adjoined to a word e.g.

it's 12euro

At inference time, inputting the example sentence above causes DIETClassifier to complain of mismatched input dimensions (stacktrace below). In the absence of a second featurizer i.e. given only SpacyFeaturizer, this does not happen, implying that the final tokens iterated over by SpacyFeaturizer differs from those iterated over by the non-Spacy featurizer. It could be because SpacyFeaturizer uses the _spacy_ tokens [here](https://github.com/RasaHQ/rasa/blob/main/rasa/nlu/featurizers/dense_featurizer/spacy_featurizer.py#L68) not necessarily the ones Rasa uses.

The goal is that if the amount and the currency are stuck together without white space like this:

it's 12euro

This would be split into tokens `it's`, `12`, `euro`.

At inference time, inputting the example sentence above causes DIETClassifier to complain of mismatched input dimensions (stacktrace below). In the absence of a second featurizer i.e. given only SpacyFeaturizer, this does not happen, implying that the final tokens iterated over by SpacyFeaturizer differs from those iterated over by the non-Spacy featurizer. It could be because SpacyFeaturizer uses the _spacy_ tokens [here](https://github.com/RasaHQ/rasa/blob/main/rasa/nlu/featurizers/dense_featurizer/spacy_featurizer.py#L68) not necessarily the ones Rasa uses.

### Command / Request

<pre>rasa train nlu
 rasa shell nlu
 > it's 12euro</pre>

### Relevant log output

<pre>Traceback (most recent call last):
 File "
 ", line 1, in 

 File "/Users/melinda/.pyenv/versions/rasa2/lib/python3.8/site-packages/rasa/nlu/model.py", line 470, in parse
 component.process(message, **self.context)
 File "/Users/melinda/.pyenv/versions/rasa2/lib/python3.8/site-packages/rasa/nlu/classifiers/diet_classifier.py", line 988, in process
 out = self._predict(message)
 File "/Users/melinda/.pyenv/versions/rasa2/lib/python3.8/site-packages/rasa/nlu/classifiers/diet_classifier.py", line 904, in _predict
 return self.model.run_inference(model_data)
 File "/Users/melinda/.pyenv/versions/rasa2/lib/python3.8/site-packages/rasa/utils/tensorflow/models.py", line 318, in run_inference
 ] = self._rasa_predict(batch_in)
 File "/Users/melinda/.pyenv/versions/rasa2/lib/python3.8/site-packages/rasa/utils/tensorflow/models.py", line 280, in _rasa_predict
 outputs = tf_utils.sync_to_numpy_or_python_type(self.predict_step(batch_in))
 File "/Users/melinda/.pyenv/versions/rasa2/lib/python3.8/site-packages/rasa/utils/tensorflow/models.py", line 228, in predict_step
 return self.batch_predict(batch_in)
 File "/Users/melinda/.pyenv/versions/rasa2/lib/python3.8/site-packages/rasa/nlu/classifiers/diet_classifier.py", line 1707, in batch_predict
 text_transformed, _, _, _, _, attention_weights = self._tf_layers[
 File "/Users/melinda/.pyenv/versions/rasa2/lib/python3.8/site-packages/keras/engine/base_layer.py", line 1037, in __call__
 outputs = call_fn(inputs, *args, **kwargs)
 File "/Users/melinda/.pyenv/versions/rasa2/lib/python3.8/site-packages/rasa/utils/tensorflow/rasa_layers.py", line 992, in call
 seq_sent_features, mask_combined_sequence_sentence = self._tf_layers[
 File "/Users/melinda/.pyenv/versions/rasa2/lib/python3.8/site-packages/keras/engine/base_layer.py", line 1037, in __call__
 outputs = call_fn(inputs, *args, **kwargs)
 File "/Users/melinda/.pyenv/versions/rasa2/lib/python3.8/site-packages/rasa/utils/tensorflow/rasa_layers.py", line 645, in call
 sequence_features_combined = self._combine_sequence_level_features(
 File "/Users/melinda/.pyenv/versions/rasa2/lib/python3.8/site-packages/rasa/utils/tensorflow/rasa_layers.py", line 570, in _combine_sequence_level_features
 sequence_features_combined = self._tf_layers[f"sparse_dense.

 {SEQUENCE} 

"](
 File "/Users/melinda/.pyenv/versions/rasa2/lib/python3.8/site-packages/keras/engine/base_layer.py", line 1037, in __call__
 outputs = call_fn(inputs, *args, **kwargs)
 File "/Users/melinda/.pyenv/versions/rasa2/lib/python3.8/site-packages/rasa/utils/tensorflow/rasa_layers.py", line 338, in call
 return tf.concat(dense_features, axis=-1)
 File "/Users/melinda/.pyenv/versions/rasa2/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 206, in wrapper
 return target(*args, **kwargs)
 File "/Users/melinda/.pyenv/versions/rasa2/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py", line 1769, in concat
 return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
 File "/Users/melinda/.pyenv/versions/rasa2/lib/python3.8/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1213, in concat_v2
 _ops.raise_from_not_ok_status(e, name)
 File "/Users/melinda/.pyenv/versions/rasa2/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 6941, in raise_from_not_ok_status
 six.raise_from(core._status_to_exception(e.code, message), None)
 File "

 ", line 3, in raise_from
 tensorflow.python.framework.errors_impl.InvalidArgumentError: ConcatOp : Dimensions of inputs should match: shape<span class="error">[0]</span> = <span class="error">[1,3,128]</span> vs. shape<span class="error">[1]</span> = <span class="error">[1,2,300]</span> <span class="error">[Op:ConcatV2]</span> name: concat

 </pre>

### Defintion of Done

*   [ ] Facilitate discussion to scope fix
*   [ ] Create new issue for refinement for fix

**Comment by melindaloubser1** [comment]
The same symptoms will be seen at training time if the token pattern causes the same situation at that time i.e. more Rasa tokens than spacy tokens. 
Given `token_pattern: "\\d"` and training data including the sentence `it's 12 euro`, running `rasa train` shows the following traceback:

```
Epochs:   0%|                                                                                                             | 0/10 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/Users/melinda/.pyenv/versions/rasa2/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/Users/melinda/.pyenv/versions/rasa2/lib/python3.8/site-packages/rasa/__main__.py", line 118, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/Users/melinda/.pyenv/versions/rasa2/lib/python3.8/site-packages/rasa/cli/train.py", line 59, in <lambda>
    train_parser.set_defaults(func=lambda args: run_training(args, can_exit=True))
  File "/Users/melinda/.pyenv/versions/rasa2/lib/python3.8/site-packages/rasa/cli/train.py", line 91, in run_training
    training_result = train_all(
  File "/Users/melinda/.pyenv/versions/rasa2/lib/python3.8/site-packages/rasa/api.py", line 109, in train
    return rasa.utils.common.run_in_loop(
  File "/Users/melinda/.pyenv/versions/rasa2/lib/python3.8/site-packages/rasa/utils/common.py", line 296, in run_in_loop
    result = loop.run_until_complete(f)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/Users/melinda/.pyenv/versions/rasa2/lib/python3.8/site-packages/rasa/model_training.py", line 103, in train_async
    nlu_model = await handle_domain_if_not_exists(
  File "/Users/melinda/.pyenv/versions/rasa2/lib/python3.8/site-packages/rasa/model_training.py", line 129, in handle_domain_if_not_exists
    nlu_model_only = await _train_nlu_with_validated_data(
  File "/Users/melinda/.pyenv/versions/rasa2/lib/python3.8/site-packages/rasa/model_training.py", line 758, in _train_nlu_with_validated_data
    await rasa.nlu.train.train(
  File "/Users/melinda/.pyenv/versions/rasa2/lib/python3.8/site-packages/rasa/nlu/train.py", line 111, in train
    interpreter = trainer.train(training_data, **kwargs)
  File "/Users/melinda/.pyenv/versions/rasa2/lib/python3.8/site-packages/rasa/nlu/model.py", line 221, in train
    component.train(working_data, self.config, **context)
  File "/Users/melinda/.pyenv/versions/rasa2/lib/python3.8/site-packages/rasa/nlu/classifiers/diet_classifier.py", line 880, in train
    self.model.fit(
  File "/Users/melinda/.pyenv/versions/rasa2/lib/python3.8/site-packages/rasa/utils/tensorflow/temp_keras_modules.py", line 190, in fit
    tmp_logs = train_function(iterator)
  File "/Users/melinda/.pyenv/versions/rasa2/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 885, in __call__
    result = self._call(*args, **kwds)
  File "/Users/melinda/.pyenv/versions/rasa2/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 950, in _call
    return self._stateless_fn(*args, **kwds)
  File "/Users/melinda/.pyenv/versions/rasa2/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3039, in __call__
    return graph_function._call_flat(
  File "/Users/melinda/.pyenv/versions/rasa2/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 1963, in _call_flat
    return self._build_call_outputs(self._inference_function.call(
  File "/Users/melinda/.pyenv/versions/rasa2/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 591, in call
    outputs = execute.execute(
  File "/Users/melinda/.pyenv/versions/rasa2/lib/python3.8/site-packages/tensorflow/python/eager/execute.py", line 59, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError:  ConcatOp : Dimensions of inputs should match: shape[0] = [5,9,128] vs. shape[1] = [5,4,300]
         [[node rasa_sequence_layer_text/rasa_feature_combining_layer_text/concatenate_sparse_dense_features_text_sequence/concat (defined at /lib/python3.8/site-packages/rasa/utils/tensorflow/rasa_layers.py:338) ]] [Op:__inference_train_function_8141]

Errors may have originated from an input operation.
Input Source operations connected to node rasa_sequence_layer_text/rasa_feature_combining_layer_text/concatenate_sparse_dense_features_text_sequence/concat:
 IteratorGetNext (defined at /lib/python3.8/site-packages/rasa/utils/tensorflow/temp_keras_modules.py:190)
 rasa_sequence_layer_text/rasa_feature_combining_layer_text/concatenate_sparse_dense_features_text_sequence/dropout/dropout/Mul_1 (defined at /lib/python3.8/site-packages/rasa/utils/tensorflow/rasa_layers.py:308)

Function call stack:
train_function
```

**Comment by ondrej-jelinek-kbc-be** [comment]
I have invented a workaround for this.
You have to create custom class which extends the SpacyNLP class, in which you set up the Spacy tokenizer to split the tokens according to your regex. You then use this custom class instead of the SpacyNLP in your config.yml.

Code:
config.yml
```
language: en
pipeline:
  - name: workaround_spacy_nlp.WorkaroundSpacyNLP
    case_sensitive: false
    model: en_core_web_md
    additional_prefix_regexes: "(\\d+|\\D+)"
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: CountVectorsFeaturizer
  - name: DIETClassifier
    epochs: 10
    constrain_similarities: true
```

workaround_spacy_nlp.py (substitue the language for your own or customize according to your needs):
```
import typing
from typing import Any, Dict, Text

import spacy
from rasa.nlu.utils.spacy_utils import SpacyNLP
from spacy.lang.cs import Czech

if typing.TYPE_CHECKING:
    from spacy.language import Language

PREFIX_REGEXES_ATTRIBUTE = "additional_prefix_regexes"


class WorkaroundSpacyNLP(SpacyNLP):
    """Custom component to add additional prefix regexes for the Spacy tokenizer (to better split some words).
    """

    defaults = {
        **SpacyNLP.defaults,
        # Additional prefix regexes for the Spacy tokenizer. Can be `List[str]` or just one `str`.
        # They will be added to the `Czech.Defaults.prefixes` and passed to (spacy) tokenizer (`nlp.tokenizer`).
        PREFIX_REGEXES_ATTRIBUTE: None,
    }

    def __init__(self, component_config: Dict[Text, Any] = None, nlp: "Language" = None) -> None:
        self._process_prefix_regexes(component_config, nlp)
        super().__init__(component_config, nlp)

    @staticmethod
    def _process_prefix_regexes(component_config: Dict[Text, Any], nlp: "Language"):
        prefix_regexes = component_config.get(PREFIX_REGEXES_ATTRIBUTE)
        if isinstance(prefix_regexes, str):
            prefix_regexes = [prefix_regexes]

        if prefix_regexes:
            prefixes = Czech.Defaults.prefixes + prefix_regexes
            prefix_regex = spacy.util.compile_prefix_regex(prefixes)
            nlp.tokenizer.prefix_search = prefix_regex.search

```

**Comment by melindaloubser1** [comment]
Thanks for the workaround @ondrej-jelinek-kbc-be !
@joejuzl The root issue here seems to be that `SpacyNLP` must already know all tokenizer settings in order for its `doc` (which includes the feature vectors fetched by `SpacyFeaturizer`) to match the tokens from `SpacyTokenizer`, which is 
 what other featurizers will see. 
 Could we move tokenizer settings to `SpacyNLP` and have `SpacyTokenizer` refer to them via it (since its a required component)?
