### ISSUE TITLE
ImportError: cannot import name 'CompositionView' from 'sanic.views'

### ISSUE THREAD

**Issue by koaning** [RasaHQ/rasa#10748]
### Rasa Open Source version

3.0.5

### Rasa SDK version

3.0.3

### Python version

3.8

### What operating system are you using?

Cloud (AWS / GCP / AZURE)

### What happened?

I tried installing Rasa on a fresh Digital Ocean VM and got a [familiar error]().

```
> python3 -m rasa --version
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/rasa/__main__.py", line 14, in <module>
    from rasa.cli import (
  File "/usr/local/lib/python3.8/dist-packages/rasa/cli/export.py", line 9, in <module>
    import rasa.core.utils
  File "/usr/local/lib/python3.8/dist-packages/rasa/core/utils.py", line 17, in <module>
    from sanic.views import CompositionView
ImportError: cannot import name 'CompositionView' from 'sanic.views' (/usr/local/lib/python3.8/dist-packages/sanic/views.py)
```

**Comment by koaning** [comment]
My impression was that this issue was fixed, per https://github.com/RasaHQ/rasa/pull/10590. I did see similar issues still open though:

- https://github.com/RasaHQ/rasa/issues/10632
-
