### ISSUE TITLE
ImportError: cannot import name 'abort' from 'sanic.exceptions'

### ISSUE THREAD

**Issue by watash1** [RasaHQ/rasa#10847]
### Rasa Open Source version

3.0.6

### Python version

3.8

### What operating system are you using?

OSX

### What happened?

cannot import name 'abort' from 'sanic.exceptions'

### Command / Request

```shell
rasa train
```

### Relevant log output

```shell
$ rasa train
/my_work_directory_with_venv/lib/python3.8/site-packages/tensorflow/python/autograph/impl/api.py:22: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/my_work_directory_with_venv/lib/python3.8/site-packages/sklearn/utils/multiclass.py:14: DeprecationWarning: Please use `spmatrix` from the `scipy.sparse` namespace, the `scipy.sparse.base` namespace is deprecated.
  from scipy.sparse.base import spmatrix
Traceback (most recent call last):
  File "/my_work_directory_with_venv/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/my_work_directory_with_venv/lib/python3.8/site-packages/rasa/__main__.py", line 121, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/my_work_directory_with_venv/lib/python3.8/site-packages/rasa/cli/train.py", line 59, in <lambda>
    train_parser.set_defaults(func=lambda args: run_training(args, can_exit=True))
  File "/my_work_directory_with_venv/lib/python3.8/site-packages/rasa/cli/train.py", line 91, in run_training
    training_result = train_all(
  File "/my_work_directory_with_venv/lib/python3.8/site-packages/rasa/api.py", line 103, in train
    from rasa.model_training import train
  File "/my_work_directory_with_venv/lib/python3.8/site-packages/rasa/model_training.py", line 8, in <module>
    import rasa.engine.validation
  File "/my_work_directory_with_venv/lib/python3.8/site-packages/rasa/engine/validation.py", line 33, in <module>
    from rasa.engine.constants import RESERVED_PLACEHOLDERS
  File "/my_work_directory_with_venv/lib/python3.8/site-packages/rasa/engine/constants.py", line 3, in <module>
    from rasa.core.channels import UserMessage
  File "/my_work_directory_with_venv/lib/python3.8/site-packages/rasa/core/channels/__init__.py", line 18, in <module>
    from rasa.core.channels.rasa_chat import RasaChatInput  # noqa: F401
  File "/my_work_directory_with_venv/lib/python3.8/site-packages/rasa/core/channels/rasa_chat.py", line 6, in <module>
    from sanic.exceptions import abort
ImportError: cannot import name 'abort' from 'sanic.exceptions' (/my_work_directory_with_venv/lib/python3.8/site-packages/sanic/exceptions.py)
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @kedz will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by badbadbatman** [comment]
I found the bug  was fixed in 85f6218c26b6.
