### ISSUE TITLE
ValueError: invalid width -1 (must be > 0)

### ISSUE THREAD

**Issue by X1AOX1A** [RasaHQ/rasa#10988]
### Rasa Open Source version

2.2.2

### Rasa SDK version

2.2.0

### Rasa X version

0.34.0

### Python version

3.7

### What operating system are you using?

OSX

### What happened?

**Issue:** ValueError: invalid width -1 (must be > 0)

**Description:** 
- The model language is Chinese, but the issue raised even I only input English
- The issue will raise after the second input
- The issue will raise even if I only type two English characters
- The issue will raise even with --skip-visualization parameter

**Error (including full traceback):**
```
Bot loaded. 
Type a message and press enter (press 'Ctr-c' to exit).
? Your input -> hi                                                                           
? Your NLU model classified 'hi' with intent 'welcome_greet' and there are no entities, is th
is correct?  Yes                                                                             
------
Chat History

 #    Bot                                You        
────────────────────────────────────────────────────
 1    action_listen                                 
────────────────────────────────────────────────────
 2                                               hi 
                         intent: welcome_greet 1.00 


Current slots: 
        client_name: None, room_num: None, food_type: None, food_amount: None, food_name: None, order_number: None, total_price: None, total_order: None, requested_slot: None

------
? The bot wants to run 'utter_welcome_greet', correct?  Yes                                  
------
Chat History

 #    Bot                                              You        
──────────────────────────────────────────────────────────────────
 1    action_listen                                               
──────────────────────────────────────────────────────────────────
 2                                                             hi 
                                       intent: welcome_greet 1.00 
──────────────────────────────────────────────────────────────────
 3    utter_welcome_greet 1.00                                    
      你好！歡迎來到SMART茶餐廳～                                 


Current slots: 
        client_name: None, room_num: None, food_type: None, food_amount: None, food_name: None, order_number: None, total_price: None, total_order: None, requested_slot: None

------
? The bot wants to run 'utter_introduction', correct?  Yes                                   
------
Chat History

 #    Bot                                                                                               You        
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 1    action_listen                                                                                                
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 2                                                                                                              hi 
                                                                                        intent: welcome_greet 1.00 
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 3    utter_welcome_greet 1.00                                                                                     
      你好！歡迎來到SMART茶餐廳～                                                                                  
      utter_introduction 1.00                                                                                      
      本餐廳現有漢堡、面類、飯類、肉類、靚湯、蔬菜、小吃和飲品等，請問你需要什麼？                                 


Current slots: 
        client_name: None, room_num: None, food_type: None, food_amount: None, food_name: None, order_number: None, total_price: None, total_order: None, requested_slot: None

------
? The bot wants to run 'action_listen', correct?  Yes                                        
? Your input -> hello                                                                        
? Your NLU model classified 'hello' with intent 'welcome_greet' and there are no entities, is
 this correct?  Yes                                                                          
2022-03-14 20:54:33 ERROR    rasa.core.training.interactive  - An exception occurred while recording messages.
Traceback (most recent call last):
  File "/Users/x1a/opt/anaconda3/envs/OrderBot/lib/python3.7/site-packages/rasa/core/training/interactive.py", line 1483, in record_messages
    plot_file,
  File "/Users/x1a/opt/anaconda3/envs/OrderBot/lib/python3.7/site-packages/rasa/core/training/interactive.py", line 964, in _predict_till_next_listen
    await _print_history(conversation_id, endpoint)
  File "/Users/x1a/opt/anaconda3/envs/OrderBot/lib/python3.7/site-packages/rasa/core/training/interactive.py", line 467, in _print_history
    table = _chat_history_table(events)
  File "/Users/x1a/opt/anaconda3/envs/OrderBot/lib/python3.7/site-packages/rasa/core/training/interactive.py", line 547, in _chat_history_table
    msg = format_user_msg(event, user_width(table))
  File "/Users/x1a/opt/anaconda3/envs/OrderBot/lib/python3.7/site-packages/rasa/core/training/interactive.py", line 500, in format_user_msg
    colored(wrap(_md, max_width), "hired"),
  File "/Users/x1a/opt/anaconda3/envs/OrderBot/lib/python3.7/site-packages/rasa/core/training/interactive.py", line 488, in wrap
    return "\n".join(textwrap.wrap(txt, max_width, replace_whitespace=False))
  File "/Users/x1a/opt/anaconda3/envs/OrderBot/lib/python3.7/textwrap.py", line 379, in wrap
    return w.wrap(text)
  File "/Users/x1a/opt/anaconda3/envs/OrderBot/lib/python3.7/textwrap.py", line 354, in wrap
    return self._wrap_chunks(chunks)
  File "/Users/x1a/opt/anaconda3/envs/OrderBot/lib/python3.7/textwrap.py", line 248, in _wrap_chunks
    raise ValueError("invalid width %r (must be > 0)" % self.width)
ValueError: invalid width -1 (must be > 0)
2022-03-14 20:54:33 ERROR    asyncio  - Task exception was never retrieved
future: <Task finished coro=<_serve_application.<locals>.run_interactive_io() done, defined at /Users/x1a/opt/anaconda3/envs/OrderBot/lib/python3.7/site-packages/rasa/core/training/interactive.py:1569> exception=ValueError('invalid width -1 (must be > 0)')>
Traceback (most recent call last):
  File "/Users/x1a/opt/anaconda3/envs/OrderBot/lib/python3.7/site-packages/rasa/core/training/interactive.py", line 1576, in run_interactive_io
    conversation_id=conversation_id,
  File "/Users/x1a/opt/anaconda3/envs/OrderBot/lib/python3.7/site-packages/rasa/core/training/interactive.py", line 1483, in record_messages
    plot_file,
  File "/Users/x1a/opt/anaconda3/envs/OrderBot/lib/python3.7/site-packages/rasa/core/training/interactive.py", line 964, in _predict_till_next_listen
    await _print_history(conversation_id, endpoint)
  File "/Users/x1a/opt/anaconda3/envs/OrderBot/lib/python3.7/site-packages/rasa/core/training/interactive.py", line 467, in _print_history
    table = _chat_history_table(events)
  File "/Users/x1a/opt/anaconda3/envs/OrderBot/lib/python3.7/site-packages/rasa/core/training/interactive.py", line 547, in _chat_history_table
    msg = format_user_msg(event, user_width(table))
  File "/Users/x1a/opt/anaconda3/envs/OrderBot/lib/python3.7/site-packages/rasa/core/training/interactive.py", line 500, in format_user_msg
    colored(wrap(_md, max_width), "hired"),
  File "/Users/x1a/opt/anaconda3/envs/OrderBot/lib/python3.7/site-packages/rasa/core/training/interactive.py", line 488, in wrap
    return "\n".join(textwrap.wrap(txt, max_width, replace_whitespace=False))
  File "/Users/x1a/opt/anaconda3/envs/OrderBot/lib/python3.7/textwrap.py", line 379, in wrap
    return w.wrap(text)
  File "/Users/x1a/opt/anaconda3/envs/OrderBot/lib/python3.7/textwrap.py", line 354, in wrap
    return self._wrap_chunks(chunks)
  File "/Users/x1a/opt/anaconda3/envs/OrderBot/lib/python3.7/textwrap.py", line 248, in _wrap_chunks
    raise ValueError("invalid width %r (must be > 0)" % self.width)
ValueError: invalid width -1 (must be > 0)
```

**Command or request that led to error:**
```
rasa interactive -m models --skip-visualization
```

**Content of configuration file (config.yml) (if relevant):**
```
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: zh

pipeline:
   - name: JiebaTokenizer
     dictionary_path: "data/dict"
   - name: RegexFeaturizer
   - name: LexicalSyntacticFeaturizer
   - name: CountVectorsFeaturizer
   - name: CountVectorsFeaturizer
     analyzer: char_wb
     min_ngram: 1
     max_ngram: 4
   - name: RegexEntityExtractor
     use_word_boundaries: False
     use_lookup_tables: True
     use_regexes: True
   - name: DIETClassifier
     epochs: 100
   - name: EntitySynonymMapper
   - name: ResponseSelector
     epochs: 100
   - name: FallbackClassifier
     threshold: 0.3
     ambiguity_threshold: 0.1


policies:
  - name: TEDPolicy
    max_history: 5
    epochs: 150
  - name: AugmentedMemoizationPolicy
    max_history: 0
  - name: MappingPolicy
  - name: FormPolicy
  - name: FallbackPolicy
    nlu_threshold: 0.3
    ambiguity_threshold: 0.1
    core_threshold: 0.3
    fallback_action_name: 'action_default_fallback'
```

**Content of domain file (domain.yml) (if relevant):**
```
session_config:
  session_expiration_time: 60
  carry_over_slots_to_new_session: true
intents:
- welcome_greet
- ask_submenu
- item_start_generic
- response_positive
- response_negative
- response_name_room
- pay_online
- pay_offline
entities:
- client_name
- room_num
- food_type
- food_amount
- food_name
slots:
  client_name:
    type: text
    influence_conversation: false
  room_num:
    type: text
    influence_conversation: false
  food_type:
    type: categorical
    influence_conversation: false
    values:
    - 包
    - 麵食
    - 飯
    - 肉類
    - 蔬菜
    - 湯
    - 小吃
    - 飲品
  food_amount:
    type: categorical
    influence_conversation: false
    values:
    - '0'
    - '1'
    - '2'
    - '3'
    - '4'
    - '5'
    - '6'
    - '7'
    - '8'
    - '9'
  food_name:
    type: categorical
    influence_conversation: false
    values: []
  order_number:
    type: text
    influence_conversation: false
  total_price:
    type: categorical
    influence_conversation: false
    values: []
  total_order:
    type: list
    influence_conversation: false
  requested_slot:
    type: text
    influence_conversation: false
responses:
  utter_welcome_greet:
  - text: 你好！歡迎來到SMART茶餐廳～
  utter_introduction:
  - text: 本餐廳現有漢堡、面類、飯類、肉類、靚湯、蔬菜、小吃和飲品等，請問你需要什麼？
  utter_order_confirm_negative:
  - text: 你想要改成什麼？
  utter_extra_order:
  - text: 好的，已將其加入購物車。請問您還需要其他嗎？我們有飲品和小吃～
  utter_name_room:
  - text: 請提供您的姓名和房間號，以方便工作人員送餐。
  utter_payment:
  - text: 您已成功下單！訂單編號為{order_number}，訂單內容為：\n{total_order}\n。總共{total_price}元，請問是線上支付還是線下支付？
  utter_pay_online:
  - text: 即將跳轉到支付平台...\n您的訂單已成功支付，餐食將會在15分鐘後送達您的房間，請您耐心等待～
  utter_pay_offline:
  - text: 稍後將會有工作人員向您收費，請您耐心等候～
  utter_default:
  - text: 抱歉，我不清楚您在說什麼，您可以再説一次嗎？
  utter_ask_food_name:
  - text: 請問你想要哪種{food_type}？
  utter_ask_food_amount:
  - text: 請問你要多少份{food_name}？
actions:
- action_show_submenu
- action_change_order
- action_order_add
- action_order_number
- action_reset_order_form
- utter_welcome_greet
- utter_introduction
- utter_order_confirm_negative
- utter_extra_order
- utter_name_room
- utter_payment
- utter_pay_online
- utter_pay_offline
- utter_default
- utter_ask_food_name
- utter_ask_food_amount
forms:
  order_form: {}
```

### Command / Request

```shell
rasa interactive -m models --skip-visualization
```

### Relevant log output

```shell
Bot loaded. 
Type a message and press enter (press 'Ctr-c' to exit).
? Your input -> hi                                                                           
? Your NLU model classified 'hi' with intent 'welcome_greet' and there are no entities, is th
is correct?  Yes                                                                             
------
Chat History

 #    Bot                                You        
────────────────────────────────────────────────────
 1    action_listen                                 
────────────────────────────────────────────────────
 2                                               hi 
                         intent: welcome_greet 1.00 


Current slots: 
        client_name: None, room_num: None, food_type: None, food_amount: None, food_name: None, order_number: None, total_price: None, total_order: None, requested_slot: None

------
? The bot wants to run 'utter_welcome_greet', correct?  Yes                                  
------
Chat History

 #    Bot                                              You        
──────────────────────────────────────────────────────────────────
 1    action_listen                                               
──────────────────────────────────────────────────────────────────
 2                                                             hi 
                                       intent: welcome_greet 1.00 
──────────────────────────────────────────────────────────────────
 3    utter_welcome_greet 1.00                                    
      你好！歡迎來到SMART茶餐廳～                                 


Current slots: 
        client_name: None, room_num: None, food_type: None, food_amount: None, food_name: None, order_number: None, total_price: None, total_order: None, requested_slot: None

------
? The bot wants to run 'utter_introduction', correct?  Yes                                   
------
Chat History

 #    Bot                                                                                               You        
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 1    action_listen                                                                                                
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 2                                                                                                              hi 
                                                                                        intent: welcome_greet 1.00 
───────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 3    utter_welcome_greet 1.00                                                                                     
      你好！歡迎來到SMART茶餐廳～                                                                                  
      utter_introduction 1.00                                                                                      
      本餐廳現有漢堡、面類、飯類、肉類、靚湯、蔬菜、小吃和飲品等，請問你需要什麼？                                 


Current slots: 
        client_name: None, room_num: None, food_type: None, food_amount: None, food_name: None, order_number: None, total_price: None, total_order: None, requested_slot: None

------
? The bot wants to run 'action_listen', correct?  Yes                                        
? Your input -> hello                                                                        
? Your NLU model classified 'hello' with intent 'welcome_greet' and there are no entities, is
 this correct?  Yes                                                                          
2022-03-14 20:54:33 ERROR    rasa.core.training.interactive  - An exception occurred while recording messages.
Traceback (most recent call last):
  File "/Users/x1a/opt/anaconda3/envs/OrderBot/lib/python3.7/site-packages/rasa/core/training/interactive.py", line 1483, in record_messages
    plot_file,
  File "/Users/x1a/opt/anaconda3/envs/OrderBot/lib/python3.7/site-packages/rasa/core/training/interactive.py", line 964, in _predict_till_next_listen
    await _print_history(conversation_id, endpoint)
  File "/Users/x1a/opt/anaconda3/envs/OrderBot/lib/python3.7/site-packages/rasa/core/training/interactive.py", line 467, in _print_history
    table = _chat_history_table(events)
  File "/Users/x1a/opt/anaconda3/envs/OrderBot/lib/python3.7/site-packages/rasa/core/training/interactive.py", line 547, in _chat_history_table
    msg = format_user_msg(event, user_width(table))
  File "/Users/x1a/opt/anaconda3/envs/OrderBot/lib/python3.7/site-packages/rasa/core/training/interactive.py", line 500, in format_user_msg
    colored(wrap(_md, max_width), "hired"),
  File "/Users/x1a/opt/anaconda3/envs/OrderBot/lib/python3.7/site-packages/rasa/core/training/interactive.py", line 488, in wrap
    return "\n".join(textwrap.wrap(txt, max_width, replace_whitespace=False))
  File "/Users/x1a/opt/anaconda3/envs/OrderBot/lib/python3.7/textwrap.py", line 379, in wrap
    return w.wrap(text)
  File "/Users/x1a/opt/anaconda3/envs/OrderBot/lib/python3.7/textwrap.py", line 354, in wrap
    return self._wrap_chunks(chunks)
  File "/Users/x1a/opt/anaconda3/envs/OrderBot/lib/python3.7/textwrap.py", line 248, in _wrap_chunks
    raise ValueError("invalid width %r (must be > 0)" % self.width)
ValueError: invalid width -1 (must be > 0)
2022-03-14 20:54:33 ERROR    asyncio  - Task exception was never retrieved
future: <Task finished coro=<_serve_application.<locals>.run_interactive_io() done, defined at /Users/x1a/opt/anaconda3/envs/OrderBot/lib/python3.7/site-packages/rasa/core/training/interactive.py:1569> exception=ValueError('invalid width -1 (must be > 0)')>
Traceback (most recent call last):
  File "/Users/x1a/opt/anaconda3/envs/OrderBot/lib/python3.7/site-packages/rasa/core/training/interactive.py", line 1576, in run_interactive_io
    conversation_id=conversation_id,
  File "/Users/x1a/opt/anaconda3/envs/OrderBot/lib/python3.7/site-packages/rasa/core/training/interactive.py", line 1483, in record_messages
    plot_file,
  File "/Users/x1a/opt/anaconda3/envs/OrderBot/lib/python3.7/site-packages/rasa/core/training/interactive.py", line 964, in _predict_till_next_listen
    await _print_history(conversation_id, endpoint)
  File "/Users/x1a/opt/anaconda3/envs/OrderBot/lib/python3.7/site-packages/rasa/core/training/interactive.py", line 467, in _print_history
    table = _chat_history_table(events)
  File "/Users/x1a/opt/anaconda3/envs/OrderBot/lib/python3.7/site-packages/rasa/core/training/interactive.py", line 547, in _chat_history_table
    msg = format_user_msg(event, user_width(table))
  File "/Users/x1a/opt/anaconda3/envs/OrderBot/lib/python3.7/site-packages/rasa/core/training/interactive.py", line 500, in format_user_msg
    colored(wrap(_md, max_width), "hired"),
  File "/Users/x1a/opt/anaconda3/envs/OrderBot/lib/python3.7/site-packages/rasa/core/training/interactive.py", line 488, in wrap
    return "\n".join(textwrap.wrap(txt, max_width, replace_whitespace=False))
  File "/Users/x1a/opt/anaconda3/envs/OrderBot/lib/python3.7/textwrap.py", line 379, in wrap
    return w.wrap(text)
  File "/Users/x1a/opt/anaconda3/envs/OrderBot/lib/python3.7/textwrap.py", line 354, in wrap
    return self._wrap_chunks(chunks)
  File "/Users/x1a/opt/anaconda3/envs/OrderBot/lib/python3.7/textwrap.py", line 248, in _wrap_chunks
    raise ValueError("invalid width %r (must be > 0)" % self.width)
ValueError: invalid width -1 (must be > 0)
```

**Comment by YueShiibo** [comment]
May I ask you how to solve this problem? Thanks so much for any reply.
