### ISSUE TITLE
Error in custom channel documentation

### ISSUE THREAD

**Issue by eric-bonfadini** [RasaHQ/rasa#11042]
### Rasa Open Source version

2.8.26

### Python version

3.8

### What operating system are you using?

Linux

### What happened?

While creating a custom channel as described in https://rasa.com/docs/rasa/connectors/custom-connectors , I got an error because name expects cls parameter.

Everything is working as expected if I add the cls parameter (there are 2 occurrences in `docs/docs/connectors/custom-connectors.mdx`).
It looks like docs for both Rasa v2 and v3 are affected by this.

### Command / Request

```shell
from rasa.core.channels.channel import InputChannel

class MyIO(InputChannel):
    def name() -> Text:
        """Name of your custom channel."""
        return "myio"
```

### Relevant log output

```shell
(env_rasa_3.8) user@592791d40880:/workspaces/rasa3/bot$ rasa run -v
Traceback (most recent call last):
  File "/home/user/env_rasa_3.8/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/home/user/env_rasa_3.8/lib/python3.8/site-packages/rasa/__main__.py", line 118, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/home/user/env_rasa_3.8/lib/python3.8/site-packages/rasa/cli/run.py", line 126, in run
    rasa.run(**vars(args))
  File "/home/user/env_rasa_3.8/lib/python3.8/site-packages/rasa/api.py", line 57, in run
    rasa.core.run.serve_application(
  File "/home/user/env_rasa_3.8/lib/python3.8/site-packages/rasa/core/run.py", line 175, in serve_application
    app = configure_app(
  File "/home/user/env_rasa_3.8/lib/python3.8/site-packages/rasa/core/run.py", line 116, in configure_app
    channels.channel.register(input_channels, app, route=route)
  File "/home/user/env_rasa_3.8/lib/python3.8/site-packages/rasa/core/channels/channel.py", line 93, in register
    p = urljoin(route, channel.url_prefix())
  File "/home/user/env_rasa_3.8/lib/python3.8/site-packages/rasa/core/channels/channel.py", line 114, in url_prefix
    return self.name()
TypeError: name() takes 0 positional arguments but 1 was given
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @joejuzl will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗
