### ISSUE TITLE
Bug report: Rasa X implicitly assumes any YAML with slot field is a domain.yml, even if domain.yml in root 

### ISSUE THREAD

**Issue by bml1g12** [RasaHQ/rasa#11041]
### Rasa Open Source version

2.8.25

### Rasa X version

1.0.1

### Python version

3.8

### What operating system are you using?

Linux

### What happened?

Just wanted to point out some unintuitive behaviour/bug in Rasa-X.

Rasa X seems to check all files in the repo which are YAML and has certain keywords like slots (as Rasa X calls [this function](https://github.com/RasaHQ/rasa/blob/d7c4374c4a6ee12f165515dbe12cf8c473d6d84c/rasa/shared/core/domain.py#L1779) and if it has them, it assumes it is a domain.yml (even when there is a file called domain.yml in the root)

In my Github repo which is linked to Rasa X, I had a YAML file that is not directly used by Rasa but contains the field “slots”. This causes Rasa X to crash out with a validation error and as a result, it actually doesn’t proceed to load NLU data from the repo, essentially breaking Rasa-X.

I think this constitutes a bug, given the only workaround I can think of is to hide files from Rasa X, and given that debugging what the problem is here is not entirely obvious without tracking through the source code.

### Command / Request

This issue occurs when using the Rasa X GUI to sync to a Github Repo which has a YAML file in it that contains domain.yml-like fields but is not a domain.yml. 

Even if a domain.yml is present, it will attempt to validate the wrong file as a domain file and crash out. 

### Relevant log output

```shell
[2022-03-29 10:10:00 +0000] - (sanic.access)[INFO][10.50.32.73:53158]: GET http://development-rasa.thri.ai/api/conversations/52b3aa558ff24f998726a5d0ff6ddfe1?format=full_conversation&history=false&since=1648545036.727824&environment=production  200 324
INFO:sanic.access:
/usr/local/lib/python3.8/dist-packages/rasa/shared/core/domain.py:1863: UserWarning: The file /app/git/1/action.yml could not be loaded as domain file. You can use https://yamlchecker.com/ to validate the YAML syntax of your file.                                                                                                                                                      
  rasa.shared.utils.io.raise_warning(                                                                                                                                                         
ERROR:asyncio:Task was destroyed but it is pending!
task: <Task pending name='Task-76' coro=<Connection.disconnect() running at /usr/local/lib/python3.8/dist-packages/aioredis/connection.py:762> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f542cc47970>()]>>
ERROR:rasax.community.utils.common:Could not complete the coroutine: 'Could not inject domain. Details:
Failed to validate YAML. Please make sure the file is correct and all mandatory parameters are specified. Here are the errors found during validation:
  in Line 33:
      Value '[ordereddict([('commitBehavior', ordereddict([('writeSessionParam', 'AccountLinkingSlot')])), ('config', ordereddict([('@type', 'type.googleapis.com/google.actions.conversation.v3.SignInSpec'), ('opt_context', 'To allow Scovilleロボット to know who you are')])), ('defaultValue', ordereddict([('sessionParam', 'AccountLinkingSlot')])), ('name', 'AccountLinkingSlot'), ('required', True), ('type', ordereddict([('name', 'actions.type.AccountLinking')]))])]' is not a dict. Value path: '/slots''.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/rasa/shared/utils/validation.py", line 170, in validate_yaml_schema
    c.validate(raise_exception=True)
  File "/usr/local/lib/python3.8/dist-packages/pykwalify/core.py", line 194, in validate
    raise SchemaError(u"Schema validation failed:\n - {error_msg}.".format(
pykwalify.errors.SchemaError: <SchemaError: error code 2: Schema validation failed:
 - Value '[ordereddict([('commitBehavior', ordereddict([('writeSessionParam', 'AccountLinkingSlot')])), ('config', ordereddict([('@type', 'type.googleapis.com/google.actions.conversation.v3.SignInSpec'), ('opt_context', 'To allow Scovilleロボット to know who you are')])), ('defaultValue', ordereddict([('sessionParam', 'AccountLinkingSlot')])), ('name', 'AccountLinkingSlot'), ('required', True), ('type', ordereddict([('name', 'actions.type.AccountLinking')]))])]' is not a dict. Value path: '/slots'.: Path: '/'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/rasax/initialise.py", line 336, in inject_domain
    domain_service.validate_and_store_domain_yaml(
  File "/usr/local/lib/python3.8/dist-packages/rasax/community/services/domain_service.py", line 278, in validate_and_store_domain_yaml
    domain = CoreDomain.from_yaml(domain_yaml)
  File "/usr/local/lib/python3.8/dist-packages/rasa/shared/core/domain.py", line 179, in from_yaml
    raise e
  File "/usr/local/lib/python3.8/dist-packages/rasa/shared/core/domain.py", line 169, in from_yaml
    rasa.shared.utils.validation.validate_yaml_schema(yaml, DOMAIN_SCHEMA_FILE)
  File "/usr/local/lib/python3.8/dist-packages/rasa/shared/utils/validation.py", line 172, in validate_yaml_schema
    raise YamlValidationException(
rasa.shared.utils.validation.YamlValidationException: Failed to validate YAML. Please make sure the file is correct and all mandatory parameters are specified. Here are the errors found during validation:
  in Line 33:
      Value '[ordereddict([('commitBehavior', ordereddict([('writeSessionParam', 'AccountLinkingSlot')])), ('config', ordereddict([('@type', 'type.googleapis.com/google.actions.conversation.v3.SignInSpec'), ('opt_context', 'To allow Scovilleロボット to know who you are')])), ('defaultValue', ordereddict([('sessionParam', 'AccountLinkingSlot')])), ('name', 'AccountLinkingSlot'), ('required', True), ('type', ordereddict([('name', 'actions.type.AccountLinking')]))])]' is not a dict. Value path: '/slots'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/rasax/community/utils/common.py", line 886, in run_in_loop
    return loop.run_until_complete(coro)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.8/dist-packages/rasax/community/services/integrated_version_control/git_service.py", line 1203, in synchronize_project
    return await self._force_inject_latest_remote_changes()
  File "/usr/local/lib/python3.8/dist-packages/rasax/community/services/integrated_version_control/git_service.py", line 1261, in _force_inject_latest_remote_changes
    await self._inject_data()
  File "/usr/local/lib/python3.8/dist-packages/rasax/community/services/integrated_version_control/git_service.py", line 1233, in _inject_data
    await rasax.initialise.inject_files_from_disk(
  File "/usr/local/lib/python3.8/dist-packages/rasax/initialise.py", line 437, in inject_files_from_disk
    inject_domain(
  File "/usr/local/lib/python3.8/dist-packages/rasax/initialise.py", line 347, in inject_domain
    raise InjectionError(f"Could not inject domain. Details:\n{e}")
rasax.initialise.InjectionError: Could not inject domain. Details:
Failed to validate YAML. Please make sure the file is correct and all mandatory parameters are specified. Here are the errors found during validation:
  in Line 33:
      Value '[ordereddict([('commitBehavior', ordereddict([('writeSessionParam', 'AccountLinkingSlot')])), ('config', ordereddict([('@type', 'type.googleapis.com/google.actions.conversation.v3.SignInSpec'), ('opt_context', 'To allow Scovilleロボット to know who you are')])), ('defaultValue', ordereddict([('sessionParam', 'AccountLinkingSlot')])), ('name', 'AccountLinkingSlot'), ('required', True), ('type', ordereddict([('name', 'actions.type.AccountLinking')]))])]' is not a dict. Value path: '/slots'
DEBUG:rasax.community.services.websocket_service:Broadcasting message: {'topic': 'ivc', 'name': 'project synchronization complete', 'data': {}, 'recipient_id': 'ALL', 'scopes': None}
DEBUG:rasax.community.services.websocket_service:Broadcasting message: {'topic': 'ivc', 'name': 'project synchronization complete', 'data': {}, 'recipient_id': 'ALL', 'scopes': None}
```
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @yennycheung will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by alexweidauer** [comment]
Thank you for raising this issue about Rasa X. We decided to stop supporting the Community Edition (free version) of ‘Rasa X’ (see more info here: https://rasa.com/blog/rasa-x-community-edition-changes/). That’s why we’ve closed your issue. We suggest that Rasa Enterprise customers raise the issue with our customer support team if they haven’t done so already.
