### ISSUE TITLE
CrossValidation: UnboundLocalError: local variable 'intent_evaluation' referenced before assignment

### ISSUE THREAD

**Issue by Mazyod** [RasaHQ/rasa#11083]
### Rasa Open Source version

3.1.0

### Python version

3.9

### What operating system are you using?

Windows

### What happened?

We call Rasa functions directly. Calling `await run_nlu_test_async(...)` lead to the following issue:

```
UnboundLocalError: local variable 'intent_evaluation' referenced before assignment
```

Looking at the code, the minimum suggested improvement is handling the cases where the if statement is not executed, and either passing an empty dictionary or raising a useful error to the user:

https://github.com/RasaHQ/rasa/blob/main/rasa/nlu/test.py#L1647

https://github.com/RasaHQ/rasa/blob/main/rasa/nlu/test.py#L1684
 

### Command / Request

```shell
from rasa.cli.test import run_nlu_test_async

# attempt to merge with test model function proved more trouble than it's worth
await run_nlu_test_async(
    config=str(workspace.input.config_file),
    data_path=str(workspace.input.nlu_file),
    models_path="",  # :(
    output_dir=str(workspace.output.results_dir),
    cross_validation=True,
    percentages=[],  # :(
    runs=0,  # :(
    no_errors=not config["errors"],
    domain_path=None,  # :(
    all_args={
        "folds": config["folds"],
        "disable_plotting": not config["plots"],
        "successes": config["successes"],
    },
)
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "...py", line 171, in run
    await worker_handle
ray.exceptions.RayTaskError(UnboundLocalError): ray::worker_process() (pid=26928, ip=127.0.0.1)
  File "python\ray\_raylet.pyx", line 640, in ray._raylet.execute_task
  File "python\ray\_raylet.pyx", line 644, in ray._raylet.execute_task
  File "D:\Users\03704u\Developer\rasa\nlu\util\task_supervisor.py", line 76, in worker_process
    return asyncio.get_event_loop().run_until_complete(result)
  File "...py", line 647, in run_until_complete
    return future.result()
  File "...py", line 298, in _cross_validate_model
    await run_nlu_test_async(
  File "...\venv\lib\site-packages\rasa\cli\test.py", line 232, in run_nlu_test_async
    await perform_nlu_cross_validation(config_dict, nlu_data, output, all_args)
  File "...\venv\lib\site-packages\rasa\model_testing.py", line 322, in perform_nlu_cross_validation
    results, entity_results, response_selection_results = await cross_validate(
  File "...\venv\lib\site-packages\rasa\nlu\test.py", line 1684, in cross_validate
    dict(intent_train_metrics), dict(intent_test_metrics), intent_evaluation
UnboundLocalError: local variable 'intent_evaluation' referenced before assignment
```

**Comment by Mazyod** [comment]
It seems clear now we should pass the domain file, but the error is misleading.

**Comment by sara-tagger** [comment]
Thanks for the issue, @amn41 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by amn41** [comment]
thanks - just to clarify, when you run `run_nlu_test_async` without providing a domain, the function tries to execute and runs into an error, correct? I'll change this to an enhancement request then, to either make this a required parameter or handle the absence of a domain file gracefully.

**Comment by Mazyod** [comment]
@amn41 We use the same function to cross validate an NLU only model, and calling the function as is above works fine. Recently, we started experimenting with e2e pipelines, and saw this issue with an e2e trained model.

**Comment by amn41** [comment]
would love to hear how your e2e results are going! my email is on my github profile - would love to chat.

**Comment by ronaldgevern** [comment]
An UnboundLocalError is raised when a local variable is referenced before it has been assigned. In most cases this will occur when trying to modify a local variable before it is actually assigned within the local scope. Python doesn't have variable declarations, so it has to figure out the scope of variables itself. It does so by a simple rule: If there is an assignment to a variable inside a function, that variable is considered local. 

Python has lexical scoping by default, which means that although an enclosed scope can access values in its enclosing scope, it cannot modify them (unless they're declared global with the global keyword). A closure binds values in the enclosing environment to names in the local environment. The local environment can then use the bound value, and even reassign that name to something else, but it can't modify the binding in the enclosing environment. UnboundLocalError happend because when python sees an assignment inside a function then it considers that variable as local variable and will not fetch its value from enclosing or global scope when we execute the function. However, to modify a [global variable](http://net-informations.com/python/iq/global.htm) inside a function, you must use the global keyword.
