### ISSUE TITLE
Telegram connection

### ISSUE THREAD

**Issue by franciellevp** [RasaHQ/rasa#11103]
### Rasa Open Source version

2.8.22

### Rasa SDK version

2.8.4

### Rasa X version

None

### Python version

3.8

### What operating system are you using?

Windows

### What happened?

**The following Exception is throw when send a message to bot via Telegram. Its connect with ngrok running locally in my computer.**

The message is interpreted and the correct answer is predicted, but in telegram theres no response because of the error.

TypeError: send_message() got an unexpected keyword argument 'action'

### Command / Request

```shell
rasa run --enable-api --cors "*" -vv
```

### Relevant log output

```shell
2022-04-27 17:12:10 ERROR    rasa.core.channels.telegram  - Exception when trying to handle message.send_message() got an unexpected keyword argument 'action'
2022-04-27 17:12:10 DEBUG    rasa.core.channels.telegram  - send_message() got an unexpected keyword argument 'action'
Traceback (most recent call last):
  File "C:\Users\francielle.pereira\.conda\envs\realize2\lib\site-packages\rasa\core\channels\telegram.py", line 259, in message
    await on_new_message(
  File "C:\Users\francielle.pereira\.conda\envs\realize2\lib\site-packages\rasa\core\channels\channel.py", line 89, in handler
    await app.agent.handle_message(message)
  File "C:\Users\francielle.pereira\.conda\envs\realize2\lib\site-packages\rasa\core\agent.py", line 577, in handle_message
    return await processor.handle_message(message)
  File "C:\Users\francielle.pereira\.conda\envs\realize2\lib\site-packages\rasa\core\processor.py", line 108, in handle_message
    await self._predict_and_execute_next_action(message.output_channel, tracker)
  File "C:\Users\francielle.pereira\.conda\envs\realize2\lib\site-packages\rasa\core\processor.py", line 659, in _predict_and_execute_next_action
    should_predict_another_action = await self._run_action(
  File "C:\Users\francielle.pereira\.conda\envs\realize2\lib\site-packages\rasa\core\processor.py", line 798, in _run_action
    await self.execute_side_effects(events, tracker, output_channel)
  File "C:\Users\francielle.pereira\.conda\envs\realize2\lib\site-packages\rasa\core\processor.py", line 699, in execute_side_effects
    await self._send_bot_messages(events, tracker, output_channel)
  File "C:\Users\francielle.pereira\.conda\envs\realize2\lib\site-packages\rasa\core\processor.py", line 715, in _send_bot_messages
    await output_channel.send_response(tracker.sender_id, e.message())
  File "C:\Users\francielle.pereira\.conda\envs\realize2\lib\site-packages\rasa\core\channels\channel.py", line 234, in send_response
    await self.send_custom_json(recipient_id, message.pop("custom"), **message)
  File "C:\Users\francielle.pereira\.conda\envs\realize2\lib\site-packages\rasa\core\channels\telegram.py", line 141, in send_custom_json
    api_call(recipient_id, *args, **json_message)
TypeError: send_message() got an unexpected keyword argument 'action'
[2022-04-27 17:12:10 -0300] [19204] [ERROR] Exception occurred while handling uri: 'http://81ba-131-161-1-157.ngrok.io/webhooks/telegram/webhook'
Traceback (most recent call last):
  File "C:\Users\francielle.pereira\.conda\envs\realize2\lib\site-packages\sanic\app.py", line 939, in handle_request
    response = await response
  File "C:\Users\francielle.pereira\.conda\envs\realize2\lib\site-packages\rasa\core\channels\telegram.py", line 259, in message
    await on_new_message(
  File "C:\Users\francielle.pereira\.conda\envs\realize2\lib\site-packages\rasa\core\channels\channel.py", line 89, in handler
    await app.agent.handle_message(message)
  File "C:\Users\francielle.pereira\.conda\envs\realize2\lib\site-packages\rasa\core\agent.py", line 577, in handle_message
    return await processor.handle_message(message)
  File "C:\Users\francielle.pereira\.conda\envs\realize2\lib\site-packages\rasa\core\processor.py", line 108, in handle_message
    await self._predict_and_execute_next_action(message.output_channel, tracker)
  File "C:\Users\francielle.pereira\.conda\envs\realize2\lib\site-packages\rasa\core\processor.py", line 659, in _predict_and_execute_next_action
    should_predict_another_action = await self._run_action(
  File "C:\Users\francielle.pereira\.conda\envs\realize2\lib\site-packages\rasa\core\processor.py", line 798, in _run_action
    await self.execute_side_effects(events, tracker, output_channel)
  File "C:\Users\francielle.pereira\.conda\envs\realize2\lib\site-packages\rasa\core\processor.py", line 699, in execute_side_effects
    await self._send_bot_messages(events, tracker, output_channel)
  File "C:\Users\francielle.pereira\.conda\envs\realize2\lib\site-packages\rasa\core\processor.py", line 715, in _send_bot_messages
    await output_channel.send_response(tracker.sender_id, e.message())
  File "C:\Users\francielle.pereira\.conda\envs\realize2\lib\site-packages\rasa\core\channels\channel.py", line 234, in send_response
    await self.send_custom_json(recipient_id, message.pop("custom"), **message)
  File "C:\Users\francielle.pereira\.conda\envs\realize2\lib\site-packages\rasa\core\channels\telegram.py", line 141, in send_custom_json
    api_call(recipient_id, *args, **json_message)
TypeError: send_message() got an unexpected keyword argument 'action'
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @JustinaPetr will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗
