### ISSUE TITLE
Traceback (most recent call last):   File "C:\Users\Isaac\horoscope_bot\train_initialize.py", line 7, in <module>     from rasa_core import utils ModuleNotFoundError: No module named 'rasa_core'

### ISSUE THREAD

**Issue by izikmartins** [RasaHQ/rasa#11105]
### Rasa Open Source version

3.1.0

### Rasa SDK version

3.1.1

### Python version

3.8

### What operating system are you using?

Windows

### What happened?

I have been getting this error for weeks and I have tried everything online.
I am trying to follow the example from the book "Building Chatbots with Python" by Sumit Raj. The error is below.

Traceback (most recent call last):
  File "C:\Users\Isaac\horoscope_bot\train_initialize.py", line 7, in <module>
    from rasa_core import utils
ModuleNotFoundError: No module named 'rasa_core'

### Command / Request

```shell
python3 train_initialize.py
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @hsm207 will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by hsm207** [comment]
> I am trying to follow the example from the book "Building Chatbots with Python" by Sumit Raj. The error is below.

What version of rasa did that book say to follow?

**Comment by ancalita** [comment]
It seems that the book might be using a different version of rasa (maybe 1.x), while you tried to run the example with an incompatible rasa version (3.x).
