### ISSUE TITLE
TED Policy Error for End to End stories

### ISSUE THREAD

**Issue by msamogh** [RasaHQ/rasa#11141]
### Rasa Open Source version

3.0 (but also replicated on 3.1)

### Python version

3.7

### What operating system are you using?

Linux

### What happened?

I get the below error during policy training when I have both regular and end-to-end stories in the training data. The error disappears when I remove the end-to-end stories.

### Command / Request

`rasa train  -d data/domain`

### Relevant log output

```shell
Processed trackers: 100%|███████████| 510/510 [00:00<00:00, 2522.40it/s, # intent=425]
Traceback (most recent call last):
  File "/home/msamogh/.cache/pypoetry/virtualenvs/prod-e5ftwSZV-py3.7/lib/python3.7/site-packages/rasa/engine/graph.py", line 461, in __call__
    output = self._fn(self._component, **run_kwargs)
  File "/home/msamogh/.cache/pypoetry/virtualenvs/prod-e5ftwSZV-py3.7/lib/python3.7/site-packages/rasa/core/policies/ted_policy.py", line 718, in train
    self.run_training(model_data, label_ids)
  File "/home/msamogh/.cache/pypoetry/virtualenvs/prod-e5ftwSZV-py3.7/lib/python3.7/site-packages/rasa/core/policies/unexpected_intent_policy.py", line 487, in run_training
    super().run_training(model_data, label_ids)
  File "/home/msamogh/.cache/pypoetry/virtualenvs/prod-e5ftwSZV-py3.7/lib/python3.7/site-packages/rasa/core/policies/ted_policy.py", line 651, in run_training
    self._entity_tag_specs,
  File "/home/msamogh/.cache/pypoetry/virtualenvs/prod-e5ftwSZV-py3.7/lib/python3.7/site-packages/rasa/core/policies/ted_policy.py", line 1200, in __init__
    self._prepare_layers()
  File "/home/msamogh/.cache/pypoetry/virtualenvs/prod-e5ftwSZV-py3.7/lib/python3.7/site-packages/rasa/core/policies/ted_policy.py", line 1227, in _prepare_layers
    name, self.data_signature[name], is_label_attribute=False
  File "/home/msamogh/.cache/pypoetry/virtualenvs/prod-e5ftwSZV-py3.7/lib/python3.7/site-packages/rasa/core/policies/ted_policy.py", line 1282, in _prepare_input_layers
    attribute_name, attribute_signature, config_to_use
  File "/home/msamogh/.cache/pypoetry/virtualenvs/prod-e5ftwSZV-py3.7/lib/python3.7/site-packages/rasa/utils/tensorflow/rasa_layers.py", line 768, in __init__
    attribute, attribute_signature, config
  File "/home/msamogh/.cache/pypoetry/virtualenvs/prod-e5ftwSZV-py3.7/lib/python3.7/site-packages/rasa/utils/tensorflow/rasa_layers.py", line 412, in __init__
    self._prepare_sparse_dense_concat_layers(attribute, attribute_signature, config)
  File "/home/msamogh/.cache/pypoetry/virtualenvs/prod-e5ftwSZV-py3.7/lib/python3.7/site-packages/rasa/utils/tensorflow/rasa_layers.py", line 453, in _prepare_sparse_dense_concat_layers
    config=config,
  File "/home/msamogh/.cache/pypoetry/virtualenvs/prod-e5ftwSZV-py3.7/lib/python3.7/site-packages/rasa/utils/tensorflow/rasa_layers.py", line 231, in __init__
    attribute, feature_type_signature, config
  File "/home/msamogh/.cache/pypoetry/virtualenvs/prod-e5ftwSZV-py3.7/lib/python3.7/site-packages/rasa/utils/tensorflow/rasa_layers.py", line 294, in _calculate_output_units
    for signature in feature_type_signature
  File "/home/msamogh/.cache/pypoetry/virtualenvs/prod-e5ftwSZV-py3.7/lib/python3.7/site-packages/rasa/utils/tensorflow/rasa_layers.py", line 294, in <listcomp>
    for signature in feature_type_signature
  File "/home/msamogh/.cache/pypoetry/virtualenvs/prod-e5ftwSZV-py3.7/lib/python3.7/site-packages/wrapt/wrappers.py", line 394, in __getitem__
    return self.__wrapped__[key]
KeyError: 'action_text'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/msamogh/.cache/pypoetry/virtualenvs/prod-e5ftwSZV-py3.7/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/home/msamogh/.cache/pypoetry/virtualenvs/prod-e5ftwSZV-py3.7/lib/python3.7/site-packages/rasa/__main__.py", line 121, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/home/msamogh/.cache/pypoetry/virtualenvs/prod-e5ftwSZV-py3.7/lib/python3.7/site-packages/rasa/cli/train.py", line 59, in <lambda>
    train_parser.set_defaults(func=lambda args: run_training(args, can_exit=True))
  File "/home/msamogh/.cache/pypoetry/virtualenvs/prod-e5ftwSZV-py3.7/lib/python3.7/site-packages/rasa/cli/train.py", line 103, in run_training
    finetuning_epoch_fraction=args.epoch_fraction,
  File "/home/msamogh/.cache/pypoetry/virtualenvs/prod-e5ftwSZV-py3.7/lib/python3.7/site-packages/rasa/api.py", line 117, in train
    finetuning_epoch_fraction=finetuning_epoch_fraction,
  File "/home/msamogh/.cache/pypoetry/virtualenvs/prod-e5ftwSZV-py3.7/lib/python3.7/site-packages/rasa/model_training.py", line 181, in train
    **(nlu_additional_arguments or {}),
  File "/home/msamogh/.cache/pypoetry/virtualenvs/prod-e5ftwSZV-py3.7/lib/python3.7/site-packages/rasa/model_training.py", line 242, in _train_graph
    is_finetuning=is_finetuning,
  File "/home/msamogh/.cache/pypoetry/virtualenvs/prod-e5ftwSZV-py3.7/lib/python3.7/site-packages/rasa/engine/training/graph_trainer.py", line 108, in train
    graph_runner.run(inputs={PLACEHOLDER_IMPORTER: importer})
  File "/home/msamogh/.cache/pypoetry/virtualenvs/prod-e5ftwSZV-py3.7/lib/python3.7/site-packages/rasa/engine/runner/dask.py", line 106, in run
    dask_result = dask.get(run_graph, run_targets)
  File "/home/msamogh/.cache/pypoetry/virtualenvs/prod-e5ftwSZV-py3.7/lib/python3.7/site-packages/dask/local.py", line 565, in get_sync
    **kwargs
  File "/home/msamogh/.cache/pypoetry/virtualenvs/prod-e5ftwSZV-py3.7/lib/python3.7/site-packages/dask/local.py", line 503, in get_async
    for key, res_info, failed in queue_get(queue).result():
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 428, in result
    return self.__get_result()
  File "/usr/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/home/msamogh/.cache/pypoetry/virtualenvs/prod-e5ftwSZV-py3.7/lib/python3.7/site-packages/dask/local.py", line 545, in submit
    fut.set_result(fn(*args, **kwargs))
  File "/home/msamogh/.cache/pypoetry/virtualenvs/prod-e5ftwSZV-py3.7/lib/python3.7/site-packages/dask/local.py", line 237, in batch_execute_tasks
    return [execute_task(*a) for a in it]
  File "/home/msamogh/.cache/pypoetry/virtualenvs/prod-e5ftwSZV-py3.7/lib/python3.7/site-packages/dask/local.py", line 237, in <listcomp>
    return [execute_task(*a) for a in it]
  File "/home/msamogh/.cache/pypoetry/virtualenvs/prod-e5ftwSZV-py3.7/lib/python3.7/site-packages/dask/local.py", line 228, in execute_task
    result = pack_exception(e, dumps)
  File "/home/msamogh/.cache/pypoetry/virtualenvs/prod-e5ftwSZV-py3.7/lib/python3.7/site-packages/dask/local.py", line 223, in execute_task
    result = _execute_task(task, data)
  File "/home/msamogh/.cache/pypoetry/virtualenvs/prod-e5ftwSZV-py3.7/lib/python3.7/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/msamogh/.cache/pypoetry/virtualenvs/prod-e5ftwSZV-py3.7/lib/python3.7/site-packages/rasa/engine/graph.py", line 470, in __call__
    ) from e
rasa.engine.exceptions.GraphComponentException: Error running graph component for node train_UnexpecTEDIntentPolicy2.
```

**Comment by Aymoelle** [comment]
can you please show us the config.yml file, and also if you generated multiple models try to put them in a temp dir and then generate a new model with `rasa train nlu` and `rasa train` and see if it work
