### ISSUE TITLE
Training with LanguageModelFeaturizer (BERT) results in "AttributeError: 'tuple' object has no attribute 'as_list'"

### ISSUE THREAD

**Issue by eitantorf** [RasaHQ/rasa#11154]
### Rasa Open Source version

3.0.8

### Rasa SDK version

3.0.4

### Python version

3.8

### What operating system are you using?

Windows

### What happened?

When adding to the config.yml the LanguageModelFeaturizer, and trying to train using "rasa train nlu", I get the following error.

Training works fine otherwise.

Rasa version is 3.0.8
TF version is 2.6.1
transformers version is 4.15.0

### Relevant log output

```shell
Traceback (most recent call last):
  File "c:\users\eitan\rasa_env\lib\site-packages\rasa\engine\graph.py", line 458, in __call__
    output = self._fn(self._component, **run_kwargs)
  File "c:\users\eitan\rasa_env\lib\site-packages\rasa\nlu\featurizers\dense_featurizer\lm_featurizer.py", line 728, in process_training_data
    batch_docs = self._get_docs_for_batch(batch_messages, attribute)
  File "c:\users\eitan\rasa_env\lib\site-packages\rasa\nlu\featurizers\dense_featurizer\lm_featurizer.py", line 685, in _get_docs_for_batch
    ) = self._get_model_features_for_batch(
  File "c:\users\eitan\rasa_env\lib\site-packages\rasa\nlu\featurizers\dense_featurizer\lm_featurizer.py", line 616, in _get_model_features_for_batch
    sequence_hidden_states = self._compute_batch_sequence_features(
  File "c:\users\eitan\rasa_env\lib\site-packages\rasa\nlu\featurizers\dense_featurizer\lm_featurizer.py", line 466, in _compute_batch_sequence_features
    model_outputs = self.model(
  File "c:\users\eitan\rasa_env\lib\site-packages\keras\engine\base_layer.py", line 1037, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "c:\users\eitan\rasa_env\lib\site-packages\transformers\models\bert\modeling_tf_bert.py", line 1126, in call
    outputs = self.bert(
  File "c:\users\eitan\rasa_env\lib\site-packages\keras\engine\base_layer.py", line 1037, in __call__
    outputs = call_fn(inputs, *args, **kwargs)
  File "c:\users\eitan\rasa_env\lib\site-packages\transformers\models\bert\modeling_tf_bert.py", line 801, in call
    attention_mask_shape = shape_list(inputs["attention_mask"])
  File "c:\users\eitan\rasa_env\lib\site-packages\transformers\modeling_tf_utils.py", line 1958, in shape_list
    static = tensor.shape.as_list()
AttributeError: 'tuple' object has no attribute 'as_list'
```

**Comment by aniket-2611** [comment]
I think I can fix this

**Comment by aniket-2611** [comment]
static = tensor.shape
        if type(static)==tuple:
            static=list(static)
        else:
            static=static.as_list()

**Comment by aniketkulye** [comment]
Please assign the access
