### ISSUE TITLE
Can't train an initial model while initing

### ISSUE THREAD

**Issue by Talented-Business** [RasaHQ/rasa#11307]
### Rasa Open Source version

3.2.2

### Rasa SDK version

3.2.0

### Python version

3.8

### What operating system are you using?

Windows

### What happened?

I am going to init new project with model.

### Command / Request

```shell
rasa init
```

### Relevant log output

```shell
Welcome to Rasa! 🤖

To get started quickly, an initial project will be created.
If you need some help, check out the documentation at https://rasa.com/docs/rasa.
Now let's start! 👇🏽

? Please enter a path where the project will be created [default: current directory]
Created project directory at 'F:\work\thomas\rasa\first'.
Finished creating project structure.
? Do you want to train an initial model? 💪🏽 Yes
Training an initial model...
Traceback (most recent call last):
  File "C:\Users\TALENT~1\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\TALENT~1\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "F:\work\thomas\rasa\venv\Scripts\rasa.exe\__main__.py", line 7, in <module>
  File "F:\work\thomas\rasa\venv\lib\site-packages\rasa\__main__.py", line 110, in main
    cmdline_arguments.func(cmdline_arguments)
  File "F:\work\thomas\rasa\venv\lib\site-packages\rasa\cli\scaffold.py", line 238, in run
    init_project(args, path)
  File "F:\work\thomas\rasa\venv\lib\site-packages\rasa\cli\scaffold.py", line 132, in init_project
    print_train_or_instructions(args)
  File "F:\work\thomas\rasa\venv\lib\site-packages\rasa\cli\scaffold.py", line 64, in print_train_or_instructions
    training_result = rasa.train(
  File "F:\work\thomas\rasa\venv\lib\site-packages\rasa\api.py", line 103, in train
    from rasa.model_training import train
  File "F:\work\thomas\rasa\venv\lib\site-packages\rasa\model_training.py", line 8, in <module>
    import rasa.engine.validation
  File "F:\work\thomas\rasa\venv\lib\site-packages\rasa\engine\validation.py", line 20, in <module>
    from rasa.core.policies.policy import PolicyPrediction
  File "F:\work\thomas\rasa\venv\lib\site-packages\rasa\core\policies\policy.py", line 26, in <module>
    from rasa.core.featurizers.tracker_featurizers import TrackerFeaturizer
  File "F:\work\thomas\rasa\venv\lib\site-packages\rasa\core\featurizers\tracker_featurizers.py", line 24, in <module>
    from rasa.core.featurizers.single_state_featurizer import SingleStateFeaturizer
  File "F:\work\thomas\rasa\venv\lib\site-packages\rasa\core\featurizers\single_state_featurizer.py", line 7, in <module>
    from rasa.nlu.extractors.extractor import EntityTagSpec
  File "F:\work\thomas\rasa\venv\lib\site-packages\rasa\nlu\extractors\extractor.py", line 30, in <module>
    import rasa.utils.train_utils
  File "F:\work\thomas\rasa\venv\lib\site-packages\rasa\utils\train_utils.py", line 32, in <module>
    from rasa.utils.tensorflow.data_generator import RasaBatchDataGenerator
  File "F:\work\thomas\rasa\venv\lib\site-packages\rasa\utils\tensorflow\data_generator.py", line 9, in <module>
    from rasa.utils.tensorflow.model_data import RasaModelData, Data, FeatureArray
  File "F:\work\thomas\rasa\venv\lib\site-packages\rasa\utils\tensorflow\model_data.py", line 19, in <module>
    from sklearn.model_selection import train_test_split
  File "F:\work\thomas\rasa\venv\lib\site-packages\sklearn\__init__.py", line 64, in <module>
    from .base import clone
  File "F:\work\thomas\rasa\venv\lib\site-packages\sklearn\base.py", line 14, in <module>
    from .utils.fixes import signature
  File "F:\work\thomas\rasa\venv\lib\site-packages\sklearn\utils\__init__.py", line 14, in <module>
    from . import _joblib
  File "F:\work\thomas\rasa\venv\lib\site-packages\sklearn\utils\_joblib.py", line 22, in <module>
    from ..externals import joblib
  File "F:\work\thomas\rasa\venv\lib\site-packages\sklearn\externals\joblib\__init__.py", line 119, in <module>
    from .parallel import Parallel
  File "F:\work\thomas\rasa\venv\lib\site-packages\sklearn\externals\joblib\parallel.py", line 28, in <module>
    from ._parallel_backends import (FallbackToBackend, MultiprocessingBackend,
  File "F:\work\thomas\rasa\venv\lib\site-packages\sklearn\externals\joblib\_parallel_backends.py", line 22, in <module>
    from .executor import get_memmapping_executor
  File "F:\work\thomas\rasa\venv\lib\site-packages\sklearn\externals\joblib\executor.py", line 14, in <module>
    from .externals.loky.reusable_executor import get_reusable_executor
  File "F:\work\thomas\rasa\venv\lib\site-packages\sklearn\externals\joblib\externals\loky\__init__.py", line 12, in <module>
    from .backend.reduction import set_loky_pickler
  File "F:\work\thomas\rasa\venv\lib\site-packages\sklearn\externals\joblib\externals\loky\backend\reduction.py", line 125, in <module>
    from sklearn.externals.joblib.externals import cloudpickle  # noqa: F401
  File "F:\work\thomas\rasa\venv\lib\site-packages\sklearn\externals\joblib\externals\cloudpickle\__init__.py", line 3, in <module>
    from .cloudpickle import *
  File "F:\work\thomas\rasa\venv\lib\site-packages\sklearn\externals\joblib\externals\cloudpickle\cloudpickle.py", line 152, in <module>
    _cell_set_template_code = _make_cell_set_template_code()
  File "F:\work\thomas\rasa\venv\lib\site-packages\sklearn\externals\joblib\externals\cloudpickle\cloudpickle.py", line 133, in _make_cell_set_template_code
    return types.CodeType(
TypeError: an integer is required (got type bytes)
```

**Comment by saswat0** [comment]
Try using Python 3.7.5

**Comment by Talented-Business** [comment]
No it is not related with python version.  It was related with python path
