### ISSUE TITLE
Rasa shell not getting connected to duckling

### ISSUE THREAD

**Issue by sahanashettigar** [RasaHQ/rasa#11310]
### Rasa Open Source version

3.2.2

### Rasa SDK version

3.2.0

### Python version

3.8

### What operating system are you using?

Windows

### What happened?

Rasa shell is giving the following error when trying to connect with duckling.
PS: Tried this without virtual environment and by installing duckling
this is the error message:
2022-07-08 20:41:50 ERROR    rasa.nlu.extractors.duckling_entity_extractor  - Failed to connect to duckling http server. Make sure the duckling server is running/healthy/not stale and the proper host and port are set in the configuration. More information on how to run the server can be found on github: https://github.com/facebook/duckling#quickstart Error: HTTPSConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /parse (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))

### Relevant log output

```shell
when provided with entity:
2022-07-08 20:43:54 ERROR    asyncio  - Exception in callback _ProactorBasePipeTransport._call_connection_lost(None)
handle: <Handle _ProactorBasePipeTransport._call_connection_lost(None)>
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\asyncio\proactor_events.py", line 162, in _call_connection_lost
    self._sock.shutdown(socket.SHUT_RDWR)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
2022-07-08 20:43:56 ERROR    rasa.nlu.extractors.duckling_entity_extractor  - Failed to connect to duckling http server. Make sure the duckling server is running/healthy/not stale and the proper host and port are set in the configuration. More information on how to run the server can be found on github: https://github.com/facebook/duckling#quickstart Error: HTTPSConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /parse (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1131)')))
Your input ->
```

**Comment by saswat0** [comment]
Try running duckling as a docker container. I was facing this issue but it went away when I ran it in docker

**Comment by rgstephens** [comment]
This isn't a Rasa issue. Please post on forum.rasa.com
