### ISSUE TITLE
Bot doesnt reply in Telegram

### ISSUE THREAD

**Issue by beliboba** [RasaHQ/rasa#11387]
### Rasa Open Source version

3.2.4

### Rasa SDK version

3.2.0

### Python version

3.7

### What operating system are you using?

Windows

### What happened?

I have invited Rasa telegram bot to group, but it replies only to messagges, starting with "/start". It works fine in the DM

### Relevant log output

```shell
Exception occurred while handling uri: 'http://56cf-5-3-214-172.eu.ngrok.io/webhooks/telegram/webhook'
Traceback (most recent call last):
  File "handle_request", line 83, in handle_request
    )
  File "C:\Users\Beliboba\AppData\Local\Programs\Python\Python37\lib\site-packages\rasa\core\channels\telegram.py", line 228, in message
    if self._is_user_message(msg):
  File "C:\Users\Beliboba\AppData\Local\Programs\Python\Python37\lib\site-packages\rasa\core\channels\telegram.py", line 180, in _is_user_message
    return message.text is not None
AttributeError: 'NoneType' object has no attribute 'text'
```

**Comment by brunoalfred** [comment]
- Experiencing same challenge

```sh
[2022-08-22 04:27:42 +0000] [1] [ERROR] Exception occurred while handling uri: 'http://rasa-demo.onrender.com/webhooks/telegram/webhook'
Aug 22 07:27:42 AM  Traceback (most recent call last):
Aug 22 07:27:42 AM    File "handle_request", line 83, in handle_request
Aug 22 07:27:42 AM      )
Aug 22 07:27:42 AM    File "/usr/local/lib/python3.8/site-packages/rasa/core/channels/telegram.py", line 228, in message
Aug 22 07:27:42 AM      if self._is_user_message(msg):
Aug 22 07:27:42 AM    File "/usr/local/lib/python3.8/site-packages/rasa/core/channels/telegram.py", line 180, in _is_user_message
Aug 22 07:27:42 AM      return message.text is not None
```

**Comment by xxxwarrior** [comment]
Hi everyone, any workaround on this one?
