### ISSUE TITLE
transformers already installed: MissingDependencyException: Not all required importable packages are installed to use the configured NLU pipeline. To use this pipeline, you need to install the missing modules: - transformers (needed for LanguageModelFeaturizer)

### ISSUE THREAD

**Issue by sataliulan** [RasaHQ/rasa#11464]
### Rasa Open Source version

2.8.31

### Rasa SDK version

2.8.8

### Python version

3.7

### What operating system are you using?

Linux

### What happened?

I've installed package transformers (version: 3.5.1), and use " LanguageModelFeaturizer" in pipeline.  But exception message shows no package transformers found. I dont kown why, any ideas?

### Command / Request

```shell
cmd that led to the bug: 
rasa train -c config/config_pretrained_embeddings_bert_zh.yml --data data/medical/M3-training_dataset_1564317234.md data/medical/stories.md data/medical/Diseases_converted.yml data/medical/Drugs_converted.yml data/medical/Departments_converted.yml data/medical/Foods_converted.yml data/medical/Symptoms_converted.yml --out models/medicalRasa2 --domain config/domains2.yml --num-threads 5 --augmentation 100 -vv
```

### Relevant log output

```shell
error logs:
2022-08-16 16:57:35 DEBUG    urllib3.connectionpool  - Starting new HTTPS connection (1): api.segment.io:443
2022-08-16 16:57:36 DEBUG    urllib3.connectionpool  - https://api.segment.io:443 "POST /v1/track HTTP/1.1" 200 21
2022-08-16 16:57:37 DEBUG    rasa.__main__  - Failed to run CLI command due to an exception.
Traceback (most recent call last):
  File "/home/hcl/miniconda3/envs/rasa2/lib/python3.7/site-packages/rasa/__main__.py", line 118, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/home/hcl/miniconda3/envs/rasa2/lib/python3.7/site-packages/rasa/cli/train.py", line 59, in <lambda>
    train_parser.set_defaults(func=lambda args: run_training(args, can_exit=True))
  File "/home/hcl/miniconda3/envs/rasa2/lib/python3.7/site-packages/rasa/cli/train.py", line 103, in run_training
    finetuning_epoch_fraction=args.epoch_fraction,
  File "/home/hcl/miniconda3/envs/rasa2/lib/python3.7/site-packages/rasa/api.py", line 124, in train
    loop,
  File "/home/hcl/miniconda3/envs/rasa2/lib/python3.7/site-packages/rasa/utils/common.py", line 296, in run_in_loop
    result = loop.run_until_complete(f)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/home/hcl/miniconda3/envs/rasa2/lib/python3.7/site-packages/rasa/model_training.py", line 104, in train_async
    file_importer, output, fixed_model_name
  File "/home/hcl/miniconda3/envs/rasa2/lib/python3.7/site-packages/rasa/model_training.py", line 130, in handle_domain_if_not_exists
    file_importer, output=output_path, fixed_model_name=fixed_model_name
  File "/home/hcl/miniconda3/envs/rasa2/lib/python3.7/site-packages/rasa/model_training.py", line 765, in _train_nlu_with_validated_data
    **additional_arguments,
  File "/home/hcl/miniconda3/envs/rasa2/lib/python3.7/site-packages/rasa/nlu/train.py", line 97, in train
    nlu_config, component_builder, model_to_finetune=model_to_finetune
  File "/home/hcl/miniconda3/envs/rasa2/lib/python3.7/site-packages/rasa/nlu/model.py", line 164, in __init__
    components.validate_requirements(cfg.component_names)
  File "/home/hcl/miniconda3/envs/rasa2/lib/python3.7/site-packages/rasa/nlu/components.py", line 88, in validate_requirements
    f"Not all required importable packages are installed to use "
rasa.exceptions.MissingDependencyException: Not all required importable packages are installed to use the configured NLU pipeline. To use this pipeline, you need to install the missing modules: 
  - transformers (needed for LanguageModelFeaturizer)
Please install the packages that contain the missing modules.
MissingDependencyException: Not all required importable packages are installed to use the configured NLU pipeline. To use this pipeline, you need to install the missing modules: 
  - transformers (needed for LanguageModelFeaturizer)
Please install the packages that contain the missing modules.
```

**Comment by ancalita** [comment]
Rasa `2.8.31` uses a different version of transformers `2.11.0` (see [here](https://github.com/RasaHQ/rasa/blob/243fa487cca3559ef4f3a7676ca972dfac28fc59/poetry.lock#L2955)). I would recommend creating a fresh venv and only installing rasa, this will ensure you will get all rasa's dependencies in the versions that the `2.8.x` version is compatible with.
