### ISSUE TITLE
Dependencies installation failure with conflict

### ISSUE THREAD

**Issue by VincentRoma** [RasaHQ/rasa#11483]
### Rasa Open Source version

3.2.6

### Rasa SDK version

3.2.0

### Python version

3.8

### What operating system are you using?

Linux

### What happened?

During a fresh install of Rasa:
```

ERROR: tensorflow-text 2.9.0 has requirement tensorflow<2.10,>=2.9.0; platform_machine != "arm64" or platform_system != "Darwin", but you'll have tensorflow 2.7.3 which is incompatible.
ERROR: sanic-cors 2.1.0 has requirement packaging>=21.3, but you'll have packaging 20.9 which is incompatible.
```

### Command / Request

```shell
pip3 install rasa
```

### Relevant log output

```shell
Rasa Version      :         3.2.6
Minimum Compatible Version: 3.0.0
Rasa SDK Version  :         3.2.0
Python Version    :         3.8.10
Operating System  :         Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.29
```

**Comment by ancalita** [comment]
@VincentRoma Which processor does your machine use? The failures might have to do with incompatibilities between the processor you're using and rasa dependencies.

**Comment by VincentRoma** [comment]
Hi @ancalita my computer is using a 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz

**Comment by ancalita** [comment]
To double-check you're installing rasa in a fresh venv that doesn't contain any other preinstalled libraries?

**Comment by VincentRoma** [comment]
Yes exactly

**Comment by tmbo** [comment]
Mhm I wonder why it is trying to install `tensorflow-text` version `2.9.0`. It should be installing `2.7.x` as the version for `tensorflow-text`.

Can you
* run `pip install rasa -vv` and provide us with the output
* run `pip install tensorlfow-text==2.7 -vv`, does this work?

**Comment by VincentRoma** [comment]
`pip install rasa -vv` output attached

`pip debug --verbose` is giving me error:

`ModuleNotFoundError: No module named 'pip._vendor.certifi'`

`pip install tensorlfow-text==2.7 -vv` is giving me:

```
Non-user install because user site-packages disabled
Created temporary directory: /tmp/pip-ephem-wheel-cache-j0kkfcsr
Created temporary directory: /tmp/pip-req-tracker-y0915w8y
Initialized build tracking at /tmp/pip-req-tracker-y0915w8y
Created build tracker: /tmp/pip-req-tracker-y0915w8y
[output.txt](https://github.com/RasaHQ/rasa/files/9416796/output.txt)

Entered build tracker: /tmp/pip-req-tracker-y0915w8y
Created temporary directory: /tmp/pip-install-fsucwq_u
1 location(s) to search for versions of tensorlfow-text:
* https://pypi.org/simple/tensorlfow-text/
Fetching project page and analyzing links: https://pypi.org/simple/tensorlfow-text/
Getting page https://pypi.org/simple/tensorlfow-text/
Found index url https://pypi.org/simple
Looking up "https://pypi.org/simple/tensorlfow-text/" in the cache
Request header has "max_age" as 0, cache bypassed
Starting new HTTPS connection (1): pypi.org:443
https://pypi.org:443 "GET /simple/tensorlfow-text/ HTTP/1.1" 404 13
Status code 404 not in (200, 203, 300, 301)
Could not fetch URL https://pypi.org/simple/tensorlfow-text/: 404 Client Error: Not Found for url: https://pypi.org/simple/tensorlfow-text/ - skipping
Given no hashes to check 0 links for project 'tensorlfow-text': discarding no candidates
ERROR: Could not find a version that satisfies the requirement tensorlfow-text==2.7 (from versions: none)
Cleaning up...
Removed build tracker: '/tmp/pip-req-tracker-y0915w8y'
ERROR: No matching distribution found for tensorlfow-text==2.7
Exception information:
Traceback (most recent call last):
  File "/home/vroma/code/CAE/HubbleRasa/venv/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/home/vroma/code/CAE/HubbleRasa/venv/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 357, in run
    resolver.resolve(requirement_set)
  File "/home/vroma/code/CAE/HubbleRasa/venv/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/home/vroma/code/CAE/HubbleRasa/venv/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/vroma/code/CAE/HubbleRasa/venv/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 281, in _get_abstract_dist_for
    req.populate_link(self.finder, upgrade_allowed, require_hashes)
  File "/home/vroma/code/CAE/HubbleRasa/venv/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 249, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/home/vroma/code/CAE/HubbleRasa/venv/lib/python3.8/site-packages/pip/_internal/index/package_finder.py", line 926, in find_requirement
    raise DistributionNotFound(
pip._internal.exceptions.DistributionNotFound: No matching distribution found for tensorlfow-text==2.7
```

**Comment by ancalita** [comment]
Oh there was a typo there, please try `pip install tensorflow-text==2.7 -vv`.
I also couldn't see the output for `pip install rasa -vv`.

**Comment by ancalita** [comment]
Additionally, I would also suggest upgrading pip just in case using `pip install -U pip`, that might resolve this error `ModuleNotFoundError: No module named 'pip._vendor.certifi'`.

**Comment by VincentRoma** [comment]
I updated my answer with the file it wasn't formatted correclty :)
Here it is again in case: 
[output.txt](https://github.com/RasaHQ/rasa/files/9417064/output.txt)

I upgrade pip from 20 to 22, resolved the debug 
[debug.txt](https://github.com/RasaHQ/rasa/files/9417040/debug.txt)

`pip install tensorflow-text==2.7 -vv`

[tensorflowtext.txt](https://github.com/RasaHQ/rasa/files/9417061/tensorflowtext.txt)

**Comment by ancalita** [comment]
I've submitted PR #11493 to fix the `tensorflow-text` constraint.

**Comment by ancalita** [comment]
Version `3.2.7` was just released, hopefully that resolves the problems you've encountered @VincentRoma
