### ISSUE TITLE
RasaX write a file with nothing encoding，but rasa read the file with utf-8 encoding

### ISSUE THREAD

**Issue by Gray430** [RasaHQ/rasa#11484]
### Rasa Open Source version

2.8.25

### Rasa SDK version

2.8.4

### Python version

3.8

### What operating system are you using?

Windows

### What happened?

my training data nlu.yml is chinese
when I typed rasa x, decoding error will occurred

it's exactly the same with issue #7765 created by [RumRaisins](https://github.com/RumRaisins)

traceback:
```
(rasa3) D:\1Python_Project\rasa_first_bot>rasa x
Preparing the local database...
Starting Rasa X in local mode... 🚀
Traceback (most recent call last):
  File "d:\1python\anaconda\anaconda\envs\rasa3\lib\site-packages\rasa\shared\utils\io.py", line 126, in read_file
    return f.read()
  File "d:\1python\anaconda\anaconda\envs\rasa3\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 2522: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\1python\anaconda\anaconda\envs\rasa3\lib\site-packages\rasa\cli\x.py", line 494, in run_locally
    local.main(
  File "d:\1python\anaconda\anaconda\envs\rasa3\lib\site-packages\rasax\community\local.py", line 213, in main
    _initialize_with_local_data(
  File "d:\1python\anaconda\anaconda\envs\rasa3\lib\site-packages\rasax\community\local.py", line 127, in _initialize_with_local_data
    loop.run_until_complete(
  File "d:\1python\anaconda\anaconda\envs\rasa3\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "d:\1python\anaconda\anaconda\envs\rasa3\lib\site-packages\rasax\initialise.py", line 454, in inject_files_from_disk
    await inject_stories(
  File "d:\1python\anaconda\anaconda\envs\rasa3\lib\site-packages\rasax\initialise.py", line 268, in inject_stories
    story_blocks = await story_service.save_stories_from_files(
  File "d:\1python\anaconda\anaconda\envs\rasa3\lib\site-packages\rasax\community\services\story_service.py", line 559, in save_stories_from_files 
    additional_blocks = await self.save_stories(
  File "d:\1python\anaconda\anaconda\envs\rasa3\lib\site-packages\rasax\community\services\story_service.py", line 452, in save_stories
    processed_stories = await self._extract_stories_yaml(
  File "d:\1python\anaconda\anaconda\envs\rasa3\lib\site-packages\rasax\community\services\story_service.py", line 375, in _extract_stories_yaml   
    steps_list = self.get_story_steps(
  File "d:\1python\anaconda\anaconda\envs\rasa3\lib\site-packages\rasax\community\services\story_service.py", line 217, in get_story_steps
    return StoryService._reader_read_from_string(
  File "d:\1python\anaconda\anaconda\envs\rasa3\lib\site-packages\rasax\community\services\story_service.py", line 135, in _reader_read_from_string
    return reader.read_from_file(temp_path, skip_validation=skip_validation)
  File "d:\1python\anaconda\anaconda\envs\rasa3\lib\site-packages\rasa\shared\core\training_data\story_reader\yaml_story_reader.py", line 100, in r
ead_from_file
    rasa.shared.utils.io.read_file(
  File "d:\1python\anaconda\anaconda\envs\rasa3\lib\site-packages\rasa\shared\utils\io.py", line 132, in read_file
    raise FileIOException(
rasa.shared.exceptions.FileIOException: Failed to read file 'C:\Users\19789\AppData\Local\Temp\tmp1he_7fzl', could not read the file using utf-8 to
 decode it. Please make sure the file is stored with this encoding.

Sorry, something went wrong (see error above). Make sure to start Rasa X with valid data and valid domain and config files. Please, also check any 
warnings that popped up.
If you need help fixing the issue visit our forum: https://forum.rasa.com/.

```

### Command / Request

```shell
rasa x
```

### Relevant log output

```shell
(rasa3) D:\1Python_Project\rasa_first_bot>rasa x
Preparing the local database...
Starting Rasa X in local mode... 🚀
Traceback (most recent call last):
  File "d:\1python\anaconda\anaconda\envs\rasa3\lib\site-packages\rasa\shared\utils\io.py", line 126, in read_file
    return f.read()
  File "d:\1python\anaconda\anaconda\envs\rasa3\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 2522: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\1python\anaconda\anaconda\envs\rasa3\lib\site-packages\rasa\cli\x.py", line 494, in run_locally
    local.main(
  File "d:\1python\anaconda\anaconda\envs\rasa3\lib\site-packages\rasax\community\local.py", line 213, in main
    _initialize_with_local_data(
  File "d:\1python\anaconda\anaconda\envs\rasa3\lib\site-packages\rasax\community\local.py", line 127, in _initialize_with_local_data
    loop.run_until_complete(
  File "d:\1python\anaconda\anaconda\envs\rasa3\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "d:\1python\anaconda\anaconda\envs\rasa3\lib\site-packages\rasax\initialise.py", line 454, in inject_files_from_disk
    await inject_stories(
  File "d:\1python\anaconda\anaconda\envs\rasa3\lib\site-packages\rasax\initialise.py", line 268, in inject_stories
    story_blocks = await story_service.save_stories_from_files(
  File "d:\1python\anaconda\anaconda\envs\rasa3\lib\site-packages\rasax\community\services\story_service.py", line 559, in save_stories_from_files 
    additional_blocks = await self.save_stories(
  File "d:\1python\anaconda\anaconda\envs\rasa3\lib\site-packages\rasax\community\services\story_service.py", line 452, in save_stories
    processed_stories = await self._extract_stories_yaml(
  File "d:\1python\anaconda\anaconda\envs\rasa3\lib\site-packages\rasax\community\services\story_service.py", line 375, in _extract_stories_yaml   
    steps_list = self.get_story_steps(
  File "d:\1python\anaconda\anaconda\envs\rasa3\lib\site-packages\rasax\community\services\story_service.py", line 217, in get_story_steps
    return StoryService._reader_read_from_string(
  File "d:\1python\anaconda\anaconda\envs\rasa3\lib\site-packages\rasax\community\services\story_service.py", line 135, in _reader_read_from_string
    return reader.read_from_file(temp_path, skip_validation=skip_validation)
  File "d:\1python\anaconda\anaconda\envs\rasa3\lib\site-packages\rasa\shared\core\training_data\story_reader\yaml_story_reader.py", line 100, in r
ead_from_file
    rasa.shared.utils.io.read_file(
  File "d:\1python\anaconda\anaconda\envs\rasa3\lib\site-packages\rasa\shared\utils\io.py", line 132, in read_file
    raise FileIOException(
rasa.shared.exceptions.FileIOException: Failed to read file 'C:\Users\19789\AppData\Local\Temp\tmp1he_7fzl', could not read the file using utf-8 to
 decode it. Please make sure the file is stored with this encoding.

Sorry, something went wrong (see error above). Make sure to start Rasa X with valid data and valid domain and config files. Please, also check any 
warnings that popped up.
If you need help fixing the issue visit our forum: https://forum.rasa.com/.
```

**Comment by Gray430** [comment]
well if the solution is simply adding the encoding parameter then this issue can be closed....

**Comment by ancalita** [comment]
@Gray430 Seems like your stories file is not using the correct encoding, please double-check that it's using utf-8.

**Comment by ancalita** [comment]
@Gray430 If you find any further issues, please reach out to the community on the [forum](https://forum.rasa.com/).
Please note that we're not supporting `2.8.x` any longer and neither `rasa x` local mode in version `3.x`.
