### ISSUE TITLE
Bug in rasa interactive 

### ISSUE THREAD

**Issue by Niebowziemii** [RasaHQ/rasa#11575]
### Rasa Open Source version

3.2.8

### Rasa SDK version

3.2.1

### Python version

3.9

### What operating system are you using?

OSX

### What happened?

After creating a new bot instance with `rasa init` and training the initial model with `rasa interactive`, the shell appears waiting for your user input. After three or four user intents this error appears: (ERROR 1 in the log form field)

This error however does not stop the `rasa interactive` command execution. If you ignore it after entering a few more intents the following is yield: (ERROR 2 in the log form field)

### Command / Request

```shell
rasa init 
rasa train
rasa interactive
```

### Relevant log output

```shell
========================================ERROR 1========================================
ERROR    asyncio  - Future exception was never retrieved
future: <Future finished exception=BlockingIOError(35, 'write could not complete without blocking', 0)>
Traceback (most recent call last):
  File "/Users/USERNAME/.pyenv/versions/3.9.11/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
BlockingIOError: [Errno 35] write could not complete without blocking


========================================ERROR 2========================================
Traceback (most recent call last):
  File "/Users/USERNAME/.pyenv/versions/3.9.11/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
BlockingIOError: [Errno 35] write could not complete without blocking
--- Logging error ---
2022-09-16 10:14:22 ERROR    rasa.core.training.interactive  - An exception occurred while recording messages.
Traceback (most recent call last):
  File "/Users/USERNAME/rasa_simple_bot_with_error/venv/lib/python3.9/site-packages/rasa/core/training/interactive.py", line 1505, in record_messages
    await _predict_till_next_listen(
  File "/Users/USERNAME/rasa_simple_bot_with_error/venv/lib/python3.9/site-packages/rasa/core/training/interactive.py", line 979, in _predict_till_next_listen
    await _print_history(conversation_id, endpoint)
  File "/Users/USERNAME/rasa_simple_bot_with_error/venv/lib/python3.9/site-packages/rasa/core/training/interactive.py", line 491, in _print_history
    print("------")
BlockingIOError: [Errno 35] write could not complete without blocking
--- Logging error ---
Traceback (most recent call last):
  File "/Users/USERNAME/rasa_simple_bot_with_error/venv/lib/python3.9/site-packages/rasa/core/training/interactive.py", line 1505, in record_messages
    await _predict_till_next_listen(
  File "/Users/USERNAME/rasa_simple_bot_with_error/venv/lib/python3.9/site-packages/rasa/core/training/interactive.py", line 979, in _predict_till_next_listen
    await _print_history(conversation_id, endpoint)
  File "/Users/USERNAME/rasa_simple_bot_with_error/venv/lib/python3.9/site-packages/rasa/core/training/interactive.py", line 491, in _print_history
    print("------")
BlockingIOError: [Errno 35] write could not complete without blocking

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/USERNAME/.pyenv/versions/3.9.11/lib/python3.9/logging/__init__.py", line 1086, in emit
    stream.write(msg + self.terminator)
BlockingIOError: [Errno 35] write could not complete without blocking
Call stack:
  File "/Users/USERNAME/rasa_simple_bot_with_error/venv/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/Users/USERNAME/rasa_simple_bot_with_error/venv/lib/python3.9/site-packages/rasa/__main__.py", line 110, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/Users/USERNAME/rasa_simple_bot_with_error/venv/lib/python3.9/site-packages/rasa/cli/interactive.py", line 94, in interactive
    perform_interactive_learning(args, zipped_model, file_importer)
  File "/Users/USERNAME/rasa_simple_bot_with_error/venv/lib/python3.9/site-packages/rasa/cli/interactive.py", line 129, in perform_interactive_learning
    do_interactive_learning(args, file_importer)
  File "/Users/USERNAME/rasa_simple_bot_with_error/venv/lib/python3.9/site-packages/rasa/core/train.py", line 102, in do_interactive_learning
    interactive.run_interactive_learning(
  File "/Users/USERNAME/rasa_simple_bot_with_error/venv/lib/python3.9/site-packages/rasa/core/training/interactive.py", line 1691, in run_interactive_learning
    _serve_application(app, file_importer, skip_visualization, conversation_id, port)
2022-09-16 10:14:22 ERROR    asyncio  - Task exception was never retrieved
future: <Task finished name='Task-6' coro=<SignalRouter._dispatch() done, defined at /Users/USERNAME/rasa_simple_bot_with_error/venv/lib/python3.9/site-packages/sanic/signals.py:121> exception=BlockingIOError(35, 'write could not complete without blocking', 0)>
Traceback (most recent call last):
  File "/Users/USERNAME/rasa_simple_bot_with_error/venv/lib/python3.9/site-packages/sanic/signals.py", line 161, in _dispatch
    retval = await maybe_coroutine
  File "/Users/USERNAME/rasa_simple_bot_with_error/venv/lib/python3.9/site-packages/sanic/app.py", line 1581, in run_delayed_task
    await prepped
  File "/Users/USERNAME/rasa_simple_bot_with_error/venv/lib/python3.9/site-packages/rasa/core/training/interactive.py", line 1597, in run_interactive_io
    await record_messages(
  File "/Users/USERNAME/rasa_simple_bot_with_error/venv/lib/python3.9/site-packages/rasa/core/training/interactive.py", line 1505, in record_messages
    await _predict_till_next_listen(
  File "/Users/USERNAME/rasa_simple_bot_with_error/venv/lib/python3.9/site-packages/rasa/core/training/interactive.py", line 979, in _predict_till_next_listen
    await _print_history(conversation_id, endpoint)
  File "/Users/USERNAME/rasa_simple_bot_with_error/venv/lib/python3.9/site-packages/rasa/core/training/interactive.py", line 491, in _print_history
    print("------")
BlockingIOError: [Errno 35] write could not complete without blocking
--- Logging error ---
2022-09-16 10:14:22 ERROR    asyncio  - Future exception was never retrieved
future: <Future finished exception=BlockingIOError(35, 'write could not complete without blocking', 0)>
Traceback (most recent call last):
  File "/Users/USERNAME/.pyenv/versions/3.9.11/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
BlockingIOError: [Errno 35] write could not complete without blocking
2022-09-16 10:14:22 ERROR    asyncio  - Future exception was never retrieved
future: <Future finished exception=BlockingIOError(35, 'write could not complete without blocking', 0)>
Traceback (most recent call last):
  File "/Users/USERNAME/.pyenv/versions/3.9.11/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
BlockingIOError: [Errno 35] write could not complete without blocking
```

**Comment by sanchariGr** [comment]
@Niebowziemii can you please confirm that you are also running the action server?

**Comment by labeebee** [comment]
I am getting similar error and I am running the action server.

**Comment by Niebowziemii** [comment]
Bot generated from rasa init does not have any custom actions, so running the action server is unnecessary. I have various rasa test bots created on my local machine and bots with custom actions and action server running gives the same error. What's more, I solved the bug by uninstalling the `uvloop==0.17.0` package. 

`pip uninstall uvloop`

I do not think this is the way it should be handled but maybe it will help somebody.

**Comment by ancalita** [comment]
Fix will be released next week in version `3.3.0`.

**Comment by BeppeMarnell** [comment]
This problem is still present in version 3.3.0!
I have: 
- rasa 3.3.1
- rasa sdk 3.3.0
- python3.8.15 
- MacOS Ventura

Removing the library solves the issue!

**Comment by visakhpr** [comment]
> Bot generated from rasa init does not have any custom actions, so running the action server is unnecessary. I have various rasa test bots created on my local machine and bots with custom actions and action server running gives the same error. What's more, I solved the bug by uninstalling the `uvloop==0.17.0` package.
> 
> `pip uninstall uvloop`
> 
> I do not think this is the way it should be handled but maybe it will help somebody.

it worked for me

**Comment by XardasDark** [comment]
Rasa Version      :         3.6.0
Minimum Compatible Version: 3.5.0
Rasa SDK Version  :         3.6.0
Python Version    :         3.9.17
Operating System  :         macOS-13.4-x86_64-i386-64bit

`pip3 uninstall uvloop `

works also for me

**Comment by lich0821** [comment]
Same issue.

Python: `3.9.16`
Rasa Version: `3.6.13`
Rasa SDK Version: `3.6.2`
Operating System: `Darwin Kernel Version 23.1.0: Mon Oct  9 21:27:27 PDT 2023; root:xnu-10002.41.9~6/RELEASE_X86_64 x86_64`

`pip uninstall uvloop` works for me as well.

**Comment by jneuendorf-i4h** [comment]
Uninstalling `uvloop` works for me, too. Just a little note for Poetry users:

The package cannot be uninstalled directly with `poetry remove uvloop` (because not specified in `pyproject.toml`).
A workaround is running the suggested command in the poetry shell:

```bash
poetry shell
> Spawning shell within /Users/jim/Library/Caches/pypoetry/virtualenvs/NAME-HASH-py3.11
> jim@mac rasa-assistant % emulate bash -c '. /Users/jim/Library/Caches/pypoetry/virtualenvs/NAME-HASH-py3.11/bin/activate'
> (NAME-HASH-py3.11) jim@mac rasa-project % pip uninstall uvloop
```
