### ISSUE TITLE
Bugs encountered when using external PostgreSQL and Redis

### ISSUE THREAD

**Issue by busyboy77** [RasaHQ/rasa#11878]
### Rasa Open Source version

1.1.2

### Rasa SDK version

3.4.0

### Python version

3.6

### What operating system are you using?

Linux

### What happened?

Helm Chart problems when using external PostgreSQL and Redis

1 -- when using External Redis, the document says to set 
```
postgresql:
  # Install should be `true` if the postgres subchart should be used
  install:  false
  # postgresqlPostgresPassword is the password when .Values.global.postgresql.postgresqlUsername    does not equal "postgres"
  postgresqlPostgresPassword: "Password123"
  # existingHost is the host which is used when an external postgresql instance is provided (`install: false`)
  existingHost: "postgresql.external.svc"
  # existingSecretKey is the key to get the password when an external postgresql instance is provided (`install: false`)
  existingSecretKey: "postgres-password"

```
and enter the external db host parameters like this
```
global:
  postgresql:
    # postgresqlUsername which should be used by Rasa to connect to Postgres
    postgresqlUsername: "sa"
    # postgresqlPassword is the password which is used when the postgresqlUsername equals "postgres"
    postgresqlPassword: "Password123"
    # existingSecret which should be used for the password instead of putting it in the values file
    existingSecret: "rasax-postgres"
    # postgresDatabase which should be used by Rasa Enterprise
    postgresqlDatabase: "rasa"
    # servicePort which is used to expose postgres to the other components
    servicePort: 5432
    # host: postgresql.hostedsomewhere.else
```

and when we create the secret using `kubectl -n rasa-x  create secret generic rasax-postgres --from-file=./postgres-password`

the db-migration fails with error like below:

```
# kubectl -n rasa-x logs -f rasa-x-db-migration-service-0
INFO:rasax.community.telemetry:Skipping request to external service: telemetry key not set.
INFO:__main__:Starting the database migration service.
/usr/local/lib/python3.8/dist-packages/rasax/community/database/utils.py:123: SADeprecationWarning: Calling URL() directly is deprecated and will be disabled in a future release.  The public constructor for URL is now the URL.create() method.
  return URL(
INFO:rasax.community.sql_migrations:Start running database migrations.
Process ForkProcess-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 3250, in _wrap_pool_connect
    return fn()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/impl.py", line 146, in _do_get
    self._dec_overflow()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 597, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.8/dist-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "postgresql.external.svc" (10.152.183.210), port 5432 failed: FATAL:  password authentication failed for user "sa"
```

and we check this inside the db-migration pod and do `printenv` and the `DB_PASSWORD=` is added with a newline added to it.
```
kubectl -n rasa-x exec -it  rasa-x-db-migration-service-0 -- printenv
RASA_X_RASA_PRODUCTION_SERVICE_HOST=10.152.183.224
KUBERNETES_SERVICE_PORT_HTTPS=443
DB_PASSWORD=Password123

KUBERNETES_SERVICE_HOST=10.152.183.1
```

FIX:

this must be added using `--from-literal ` rather than `--from-file` option to kubectl create secret command 

`kubectl -n rasa-x  create secret generic rasax-postgres --from-literal=postgres-password=Password123`

2 -- Redis Problem:

Same issue, when using external redis, the rasa-production, rasa-worker, and event-service start crying for absence of `rasa-x-redis` secret , however its is documented in the helm chart to use `rasax-redis`

as given below: snippet from the helm chart

```
  # In case you use an external hosted redis, fill these values
  # auth:
  #  # existingSecret which should be used for the password instead of putting it in the values file
  #  existingSecret: "rasax-redis"
  #  # existingSecretPasswordKey is the key to get the password when an external redis instance is provided
  #  existingSecretPasswordKey: "redis-password"
  # existingHost: "redis.extern.host"

  # existingHost is the host which is used when an external redis instance is provided (`install: false`)

  # create the namespace beforehand running the deployment and create the secret via the following commands
  # echo "<REDISPASSWORD>" > ./redis-password
  # kubectl -n rasa create secret generic rasax-redis --from-file=./redis-password

  auth:
    # existingSecret which should be used for the password instead of putting it in the values file
    existingSecret: "rasa-x-redis"
    # existingSecretPasswordKey is the key to get the password when an external redis instance is provided
    existingSecretPasswordKey: "redis-password"
  # existingHost is the host which is used when an external redis instance is provided (`install: false`)
  existingHost: "redis-master.external.svc"
```

I had to create the existingSecret with the name of "rasa-x-redis"  using `kubectl -n rasa-x  create secret generic rasax-redis --from-literal=redis-password=Password123`

and redploying the helm chart works perfectly fine now.

### Command / Request

```shell
Helm chart information is incomplete and incorrect.
```

**Comment by radovanZRasa** [comment]
@busyboy77 
Hi, we are not supporting Rasa 1.1.2.
Can you try with either Rasa 3.3.x or 3.4.0 and see if the issue persists?
