### ISSUE TITLE
"AttributeError: 'DataRouter' object has no attribute 'pool' " while running the HTTP server on a machine without multiprocessing support

### ISSUE THREAD

**Issue by parthsharma1996** [RasaHQ/rasa#1601]
**Rasa NLU version**: 0.13.8

**Operating system** (windows, osx, ...): Ubuntu 14.04

**Content of model configuration file**:
```yml
language: "en"

pipeline:
- name: "tokenizer_whitespace"
- name: "ner_crf"
- name: "ner_synonyms"
- name: "ner_duckling"
  dimensions: ["time"]
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
  intent_tokenization_flag: true
  intent_split_symbol: "+"

```

**Issue**:
On trying to start the `rasa_nlu` HTTP server, I am getting the following error.

``` python
(bot_env) [ps597689]$ python -m rasa_nlu.server --path nlu_models/
Traceback (most recent call last):
  File "/home/<username>/opt/python-3.6.2/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/<username>/opt/python-3.6.2/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/<username>/bot.<domain>/bot_env/lib/python3.6/site-packages/rasa_nlu/server.py", line 438, in <module>
    wait_time_between_pulls=cmdline_args.wait_time_between_pulls
  File "/home/<username>/bot.<domain>/bot_env/lib/python3.6/site-packages/rasa_nlu/data_router.py", line 119, in __init__
    self.pool = ProcessPool(self._training_processes)
  File "/home/<username>/opt/python-3.6.2/lib/python3.6/concurrent/futures/process.py", line 390, in __init__
    EXTRA_QUEUED_CALLS)
  File "/home/<username>/opt/python-3.6.2/lib/python3.6/multiprocessing/context.py", line 102, in Queue
    return Queue(maxsize, ctx=self.get_context())
  File "/home/<username>/opt/python-3.6.2/lib/python3.6/multiprocessing/queues.py", line 42, in __init__
    self._rlock = ctx.Lock()
  File "/home/<username>/opt/python-3.6.2/lib/python3.6/multiprocessing/context.py", line 67, in Lock
    return Lock(ctx=self.get_context())
  File "/home/<username>/opt/python-3.6.2/lib/python3.6/multiprocessing/synchronize.py", line 163, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1, ctx=ctx)
  File "/home/<username>/opt/python-3.6.2/lib/python3.6/multiprocessing/synchronize.py", line 60, in __init__
    unlink_now)
OSError: [Errno 38] Function not implemented
Exception ignored in: <bound method DataRouter.__del__ of <rasa_nlu.data_router.DataRouter object at 0x7f2a37903c18>>
Traceback (most recent call last):
  File "/home/<username>/bot.<domain>/bot_env/lib/python3.6/site-packages/rasa_nlu/data_router.py", line 123, in __del__
    self.pool.shutdown()
AttributeError: 'DataRouter' object has no attribute 'pool'
```

This error only occurs when I try to deploy the code on DreamHost VPS. The `OSError: [Errno 38] Function not implemented` is being thrown because DreamHost VPS doesn't allow multiprocessing apparently (I tried running a simple multiprocessing code and it throws the same error).

However imo, ideally `rasa_nlu` should catch this and either:-

- Revert to doing the same job without using multiprocessing OR
- Give the user a more informative error message

Although I am not very experienced at Multiprocessing, Thread synchronization etc. I can try and write a PR to fix it if I am given some outline on what to do.

**Comment by wochinge** [comment]
Thanks for raising this issue, @ricwo will get back to you about it soon.

**Comment by parthsharma1996** [comment]
Hi, is there any update on this? We are unable to deploy our Chatbot due to this issue.

**Comment by ricwo** [comment]
hey @parthsharma1996, since the multiprocessing features are restricted to training, adding the option to run in a single process sounds like a reasonable solution 👍this happens anyway on python 2 with tensorflow in the training pipeline, so the changes required are minimal.

I would suggest adding a `--single-process` argument to `rasa_nlu.server` which, when present, does not use the `ProcessPoolExecutor` in `data_router.py` during training. We should also catch the error you mentioned (`AttributeError: 'DataRouter' object has no attribute 'pool'`) and give instructions on how to fix it using the single-process flag

**Comment by parthsharma1996** [comment]
@ricwo I can try to implement the changes and submit a PR if you can elaborate a little bit more on the steps

**Comment by ricwo** [comment]
Sure, so add a keyword argument to `DataRouter` called `single_process`, which is `None` by default. If it is set to `True`, do not initialise `self.pool`. In `start_train_process()`. Add a check for this flag to `if six.PY2 and self._tf_in_pipeline(train_config)`, so that should become something like

```python
if self.single_process or six.PY2 and self._tf_in_pipeline(train_config):
```
and you would have to update the `logger.warning` method that follows it. Make the `single-process` kwarg in `DataRouter` flag accessible in `rasa_nlu.server` by adding `--single-process` to the argument parser. Does that make sense?

**Comment by parthsharma1996** [comment]
@ricwo I followed the instructions you gave me. However this lead to an error popping up on sending a query to the HTTP server:

```python
(rasa_env) ❯ python -m rasa_nlu.server --single_process --path nlu_models/ --verbose
2019-01-14 18:11:55 INFO     rasa_nlu.data_router - Logging of requests is disabled. (No 'request_log' directory configured)
2019-01-14 18:11:55 INFO     __main__ - Started http server on port 5000
2019-01-14 18:11:55+0530 [-] Log opened.
2019-01-14 18:11:55+0530 [-] Site starting on 5000
2019-01-14 18:11:55+0530 [-] Starting factory <twisted.web.server.Site object at 0x7fe3d2630d30>
2019-01-14 18:13:34+0530 [-] 2019-01-14 18:13:34 INFO     __main__ - value of self._testing False
2019-01-14 18:13:34+0530 [-] 2019-01-14 18:13:34 ERROR    __main__ - bad value(s) in fds_to_keep
2019-01-14 18:13:34+0530 [-] Traceback (most recent call last):
2019-01-14 18:13:34+0530 [-]   File "/home/parth/rasa_env/lib/python3.6/site-packages/rasa_nlu-0.14.0a1-py3.6.egg/rasa_nlu/server.py", line 261, in parse
2019-01-14 18:13:34+0530 [-]   File "/home/parth/rasa_env/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
2019-01-14 18:13:34+0530 [-]     result = inContext.theWork()
2019-01-14 18:13:34+0530 [-]   File "/home/parth/rasa_env/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
2019-01-14 18:13:34+0530 [-]     inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
2019-01-14 18:13:34+0530 [-]   File "/home/parth/rasa_env/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
2019-01-14 18:13:34+0530 [-]     return self.currentContext().callWithContext(ctx, func, *args, **kw)
2019-01-14 18:13:34+0530 [-]   File "/home/parth/rasa_env/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
2019-01-14 18:13:34+0530 [-]     return func(*args,**kw)
2019-01-14 18:13:34+0530 [-]   File "/home/parth/rasa_env/lib/python3.6/site-packages/rasa_nlu-0.14.0a1-py3.6.egg/rasa_nlu/data_router.py", line 275, in parse
2019-01-14 18:13:34+0530 [-]     model)
2019-01-14 18:13:34+0530 [-]   File "/home/parth/rasa_env/lib/python3.6/site-packages/rasa_nlu-0.14.0a1-py3.6.egg/rasa_nlu/project.py", line 265, in parse
2019-01-14 18:13:34+0530 [-]     interpreter = self._interpreter_for_model(model_name)
2019-01-14 18:13:34+0530 [-]   File "/home/parth/rasa_env/lib/python3.6/site-packages/rasa_nlu-0.14.0a1-py3.6.egg/rasa_nlu/project.py", line 371, in _interpreter_for_model
2019-01-14 18:13:34+0530 [-]     return Interpreter.create(metadata, self._component_builder)
2019-01-14 18:13:34+0530 [-]   File "/home/parth/rasa_env/lib/python3.6/site-packages/rasa_nlu-0.14.0a1-py3.6.egg/rasa_nlu/model.py", line 315, in create
2019-01-14 18:13:34+0530 [-]     components.validate_requirements(model_metadata.component_classes)
2019-01-14 18:13:34+0530 [-]   File "/home/parth/rasa_env/lib/python3.6/site-packages/rasa_nlu-0.14.0a1-py3.6.egg/rasa_nlu/components.py", line 49, in validate_requirements
2019-01-14 18:13:34+0530 [-]     from rasa_nlu import registry
2019-01-14 18:13:34+0530 [-]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
2019-01-14 18:13:34+0530 [-]   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
2019-01-14 18:13:34+0530 [-]   File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
2019-01-14 18:13:34+0530 [-]   File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
2019-01-14 18:13:34+0530 [-]   File "/home/parth/rasa_env/lib/python3.6/site-packages/rasa_nlu-0.14.0a1-py3.6.egg/rasa_nlu/registry.py", line 23, in <module>
2019-01-14 18:13:34+0530 [-]     from rasa_nlu.classifiers.embedding_intent_classifier import \
2019-01-14 18:13:34+0530 [-]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
2019-01-14 18:13:34+0530 [-]   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
2019-01-14 18:13:34+0530 [-]   File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
2019-01-14 18:13:34+0530 [-]   File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
2019-01-14 18:13:34+0530 [-]   File "/home/parth/rasa_env/lib/python3.6/site-packages/rasa_nlu-0.14.0a1-py3.6.egg/rasa_nlu/classifiers/embedding_intent_classifier.py", line 10, in <module>
2019-01-14 18:13:34+0530 [-]     from tqdm import tqdm
2019-01-14 18:13:34+0530 [-]   File "/home/parth/rasa_env/lib/python3.6/site-packages/tqdm/__init__.py", line 1, in <module>
2019-01-14 18:13:34+0530 [-]     from ._tqdm import tqdm
2019-01-14 18:13:34+0530 [-]   File "/home/parth/rasa_env/lib/python3.6/site-packages/tqdm/_tqdm.py", line 75, in <module>
2019-01-14 18:13:34+0530 [-]     mp_lock = mp.RLock()  # multiprocessing lock
2019-01-14 18:13:34+0530 [-]   File "/usr/lib64/python3.6/multiprocessing/context.py", line 72, in RLock
2019-01-14 18:13:34+0530 [-]     return RLock(ctx=self.get_context())
2019-01-14 18:13:34+0530 [-]   File "/usr/lib64/python3.6/multiprocessing/synchronize.py", line 188, in __init__
2019-01-14 18:13:34+0530 [-]     SemLock.__init__(self, RECURSIVE_MUTEX, 1, 1, ctx=ctx)
2019-01-14 18:13:34+0530 [-]   File "/usr/lib64/python3.6/multiprocessing/synchronize.py", line 81, in __init__
2019-01-14 18:13:34+0530 [-]     register(self._semlock.name)
2019-01-14 18:13:34+0530 [-]   File "/usr/lib64/python3.6/multiprocessing/semaphore_tracker.py", line 83, in register
2019-01-14 18:13:34+0530 [-]     self._send('REGISTER', name)
2019-01-14 18:13:34+0530 [-]   File "/usr/lib64/python3.6/multiprocessing/semaphore_tracker.py", line 90, in _send
2019-01-14 18:13:34+0530 [-]     self.ensure_running()
2019-01-14 18:13:34+0530 [-]   File "/usr/lib64/python3.6/multiprocessing/semaphore_tracker.py", line 71, in ensure_running
2019-01-14 18:13:34+0530 [-]     pid = util.spawnv_passfds(exe, args, fds_to_pass)
2019-01-14 18:13:34+0530 [-]   File "/usr/lib64/python3.6/multiprocessing/util.py", line 417, in spawnv_passfds
2019-01-14 18:13:34+0530 [-]     False, False, None)
2019-01-14 18:13:34+0530 [-] ValueError: bad value(s) in fds_to_keep
2019-01-14 18:13:34+0530 [-] "127.0.0.1" - - [14/Jan/2019:12:43:33 +0000] "POST /parse HTTP/1.1" 500 44 "-" "python-requests/2.19.1"

```

It seems to me that the `RasaNLU` object is trying to make use of multi-processing features/assuming multiprocessing in the rest of the code which is causing the error, although I am not sure.

It would be helpful if you could give me some pointers regarding what's going wrong and how to fix it. 

You can see the changes I made, here: https://github.com/parthsharma1996/rasa_nlu/tree/add_single_proc_opt

**Comment by parthsharma1996** [comment]
@ricwo I am using `sklearn 0.19.1`

**Comment by ricwo** [comment]
`embedding_intent_classifier` uses `tqdm`, which in turn uses `multiprocessing`. I haven't tested this approach, but you could probably try the following:

In `embedding_intent_classifier`, remove `from tqdm import tqdm`. At the definition of the progress bar, in `_tf_train()`, you would have
```python
try:
    from tqdm import tqdm
    pbar = tqdm(range(self.epochs), desc="Epochs")
except ImportError:
    logger.info("tqdm could not be imported. " 
                "This is likely due to missing multiprocessing "
                "capabilities of this system.")
    pbar = range(self.epochs)
```

**Comment by parthsharma1996** [comment]
@ricwo I made the above changes. I am getting a slightly different version of the same error. This time the error is in `sklearn_crfsuite`

```python
(rasa_env) ❯ python -m rasa_nlu.server --single_process --path nlu_models/ --verbose
2019-01-18 18:03:36 INFO     rasa_nlu.data_router - Logging of requests is disabled. (No 'request_log' directory configured)
2019-01-18 18:03:36 INFO     __main__ - Started http server on port 5000
2019-01-18 18:03:36+0530 [-] Log opened.
2019-01-18 18:03:36+0530 [-] Site starting on 5000
2019-01-18 18:03:36+0530 [-] Starting factory <twisted.web.server.Site object at 0x7fe331403f28>
2019-01-18 18:03:50+0530 [-] 2019-01-18 18:03:50 ERROR    __main__ - bad value(s) in fds_to_keep
2019-01-18 18:03:50+0530 [-] Traceback (most recent call last):
2019-01-18 18:03:50+0530 [-]   File "/home/parth/rasa_env/lib/python3.6/site-packages/rasa_nlu-0.14.0a1-py3.6.egg/rasa_nlu/server.py", line 261, in parse
2019-01-18 18:03:50+0530 [-]   File "/home/parth/rasa_env/lib/python3.6/site-packages/twisted/python/threadpool.py", line 250, in inContext
2019-01-18 18:03:50+0530 [-]     result = inContext.theWork()
2019-01-18 18:03:50+0530 [-]   File "/home/parth/rasa_env/lib/python3.6/site-packages/twisted/python/threadpool.py", line 266, in <lambda>
2019-01-18 18:03:50+0530 [-]     inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
2019-01-18 18:03:50+0530 [-]   File "/home/parth/rasa_env/lib/python3.6/site-packages/twisted/python/context.py", line 122, in callWithContext
2019-01-18 18:03:50+0530 [-]     return self.currentContext().callWithContext(ctx, func, *args, **kw)
2019-01-18 18:03:50+0530 [-]   File "/home/parth/rasa_env/lib/python3.6/site-packages/twisted/python/context.py", line 85, in callWithContext
2019-01-18 18:03:50+0530 [-]     return func(*args,**kw)
2019-01-18 18:03:50+0530 [-]   File "/home/parth/rasa_env/lib/python3.6/site-packages/rasa_nlu-0.14.0a1-py3.6.egg/rasa_nlu/data_router.py", line 276, in parse
2019-01-18 18:03:50+0530 [-]     model)
2019-01-18 18:03:50+0530 [-]   File "/home/parth/rasa_env/lib/python3.6/site-packages/rasa_nlu-0.14.0a1-py3.6.egg/rasa_nlu/project.py", line 265, in parse
2019-01-18 18:03:50+0530 [-]     interpreter = self._interpreter_for_model(model_name)
2019-01-18 18:03:50+0530 [-]   File "/home/parth/rasa_env/lib/python3.6/site-packages/rasa_nlu-0.14.0a1-py3.6.egg/rasa_nlu/project.py", line 371, in _interpreter_for_model
2019-01-18 18:03:50+0530 [-]     return Interpreter.create(metadata, self._component_builder)
2019-01-18 18:03:50+0530 [-]   File "/home/parth/rasa_env/lib/python3.6/site-packages/rasa_nlu-0.14.0a1-py3.6.egg/rasa_nlu/model.py", line 315, in create
2019-01-18 18:03:50+0530 [-]     components.validate_requirements(model_metadata.component_classes)
2019-01-18 18:03:50+0530 [-]   File "/home/parth/rasa_env/lib/python3.6/site-packages/rasa_nlu-0.14.0a1-py3.6.egg/rasa_nlu/components.py", line 56, in validate_requirements
2019-01-18 18:03:50+0530 [-]     component_class.required_packages()))
2019-01-18 18:03:50+0530 [-]   File "/home/parth/rasa_env/lib/python3.6/site-packages/rasa_nlu-0.14.0a1-py3.6.egg/rasa_nlu/components.py", line 39, in find_unavailable_packages
2019-01-18 18:03:50+0530 [-]     importlib.import_module(package)
2019-01-18 18:03:50+0530 [-]   File "/home/parth/rasa_env/lib/python3.6/importlib/__init__.py", line 126, in import_module
2019-01-18 18:03:50+0530 [-]     return _bootstrap._gcd_import(name[level:], package, level)
2019-01-18 18:03:50+0530 [-]   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
2019-01-18 18:03:50+0530 [-]   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
2019-01-18 18:03:50+0530 [-]   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
2019-01-18 18:03:50+0530 [-]   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
2019-01-18 18:03:50+0530 [-]   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
2019-01-18 18:03:50+0530 [-]   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2019-01-18 18:03:50+0530 [-]   File "/home/parth/rasa_env/lib/python3.6/site-packages/sklearn_crfsuite/__init__.py", line 2, in <module>
2019-01-18 18:03:50+0530 [-]     from .estimator import CRF
2019-01-18 18:03:50+0530 [-]   File "/home/parth/rasa_env/lib/python3.6/site-packages/sklearn_crfsuite/estimator.py", line 10, in <module>
2019-01-18 18:03:50+0530 [-]     from sklearn_crfsuite.compat import BaseEstimator
2019-01-18 18:03:50+0530 [-]   File "/home/parth/rasa_env/lib/python3.6/site-packages/sklearn_crfsuite/compat.py", line 3, in <module>
2019-01-18 18:03:50+0530 [-]     from sklearn.base import BaseEstimator
2019-01-18 18:03:50+0530 [-]   File "/home/parth/rasa_env/lib/python3.6/site-packages/sklearn/__init__.py", line 134, in <module>
2019-01-18 18:03:50+0530 [-]     from .base import clone
2019-01-18 18:03:50+0530 [-]   File "/home/parth/rasa_env/lib/python3.6/site-packages/sklearn/base.py", line 13, in <module>
2019-01-18 18:03:50+0530 [-]     from .utils.fixes import signature
2019-01-18 18:03:50+0530 [-]   File "/home/parth/rasa_env/lib/python3.6/site-packages/sklearn/utils/__init__.py", line 11, in <module>
2019-01-18 18:03:50+0530 [-]     from .validation import (as_float_array,
2019-01-18 18:03:50+0530 [-]   File "/home/parth/rasa_env/lib/python3.6/site-packages/sklearn/utils/validation.py", line 23, in <module>
2019-01-18 18:03:50+0530 [-]     from ..externals.joblib import Memory
2019-01-18 18:03:50+0530 [-]   File "/home/parth/rasa_env/lib/python3.6/site-packages/sklearn/externals/joblib/__init__.py", line 127, in <module>
2019-01-18 18:03:50+0530 [-]     from .parallel import Parallel
2019-01-18 18:03:50+0530 [-]   File "/home/parth/rasa_env/lib/python3.6/site-packages/sklearn/externals/joblib/parallel.py", line 25, in <module>
2019-01-18 18:03:50+0530 [-]     from ._multiprocessing_helpers import mp
2019-01-18 18:03:50+0530 [-]   File "/home/parth/rasa_env/lib/python3.6/site-packages/sklearn/externals/joblib/_multiprocessing_helpers.py", line 24, in <module>
2019-01-18 18:03:50+0530 [-]     _sem = mp.Semaphore()
2019-01-18 18:03:50+0530 [-]   File "/usr/lib64/python3.6/multiprocessing/context.py", line 82, in Semaphore
2019-01-18 18:03:50+0530 [-]     return Semaphore(value, ctx=self.get_context())
2019-01-18 18:03:50+0530 [-]   File "/usr/lib64/python3.6/multiprocessing/synchronize.py", line 127, in __init__
2019-01-18 18:03:50+0530 [-]     SemLock.__init__(self, SEMAPHORE, value, SEM_VALUE_MAX, ctx=ctx)
2019-01-18 18:03:50+0530 [-]   File "/usr/lib64/python3.6/multiprocessing/synchronize.py", line 81, in __init__
2019-01-18 18:03:50+0530 [-]     register(self._semlock.name)
2019-01-18 18:03:50+0530 [-]   File "/usr/lib64/python3.6/multiprocessing/semaphore_tracker.py", line 83, in register
2019-01-18 18:03:50+0530 [-]     self._send('REGISTER', name)
2019-01-18 18:03:50+0530 [-]   File "/usr/lib64/python3.6/multiprocessing/semaphore_tracker.py", line 90, in _send
2019-01-18 18:03:50+0530 [-]     self.ensure_running()
2019-01-18 18:03:50+0530 [-]   File "/usr/lib64/python3.6/multiprocessing/semaphore_tracker.py", line 71, in ensure_running
2019-01-18 18:03:50+0530 [-]     pid = util.spawnv_passfds(exe, args, fds_to_pass)
2019-01-18 18:03:50+0530 [-]   File "/usr/lib64/python3.6/multiprocessing/util.py", line 417, in spawnv_passfds
2019-01-18 18:03:50+0530 [-]     False, False, None)
2019-01-18 18:03:50+0530 [-] ValueError: bad value(s) in fds_to_keep
2019-01-18 18:03:50+0530 [-] "127.0.0.1" - - [18/Jan/2019:12:33:50 +0000] "POST /parse HTTP/1.1" 500 44 "-" "python-requests/2.19.1"
^C2019-01-18 18:05:08+0530 [-] Received SIGINT, shutting down.
2019-01-18 18:05:08+0530 [twisted.web.server.Site] (TCP Port 5000 Closed)
2019-01-18 18:05:08+0530 [-] Stopping factory <twisted.web.server.Site object at 0x7fe331403f28>
2019-01-18 18:05:08+0530 [-] Main loop terminated.
```
My package vesions are `scikit-learn==0.19.1` and `sklearn-crfsuite==0.3.6`

**Comment by ricwo** [comment]
Hi @parthsharma1996 , it seems that sklearn uses multiprocessing and there doesn't seem to be a way to switch that off. Feel free to have another look into sklearn, but if it doesn't work I'm afraid we can't switch off multiprocessing in Rasa NLU and sklearn-crf. Sorry!

**Comment by parthsharma1996** [comment]
@ricwo Hi, I realized that this problem with `sklearn` only occurs when I use it on a machine _with_ 
multiprocessing support. However, the solution is working on a machine _without_ multiprocessing support (on our dreamhost VPS) as expected ! 

When `sklearn` recognizes that the machine doesn't support multiprocessing it switches to serial mode automatically with the following message:
```python
2019-01-25 04:47:40-0800 [-] /home/<username>/<domain>/bot_env/lib/python3.6/site-packages/sklearn/externals/joblib/_multiprocessing_helpers.py:28: builtins.UserWarning: [Errno 38] Function not implemented.  joblib will operate in serial mode
```

I'll make the PR (although I think I'll need to make a few more commits since `0.14.1` seems to have dropped support for python 2)

**Comment by tmbo** [comment]
should be fixed https://github.com/RasaHQ/rasa/issues/4262
