### ISSUE TITLE
Runtime Warning due to functions named like modules

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#3070]
Errors like this
```
RuntimeWarning: 'rasa_nlu.test' found in sys.modules after import of package 'rasa_nlu', but prior to execution of 'rasa_nlu.test'; this may result in unpredictable behaviour
```
are apparently due to functions being named like modules. 

This has occured with:
 - `rasa_nlu.train`
 - `rasa_core.train`
 - `rasa_core.run`
 - `rasa_nlu.test`
 - `rasa_core.test`
 - `rasa_core.visualize`

**Comment by Nomiluks** [comment]
```
!python -m rasa_nlu.test \
    --data export_data_format_train.json \
    --model model/ner_model \
    --mode evaluation
```

When I run evaluation script I am also getting the same error is it fixed?

```
/home/user/anaconda2/envs/jd_matcher/lib/python3.6/runpy.py:125: RuntimeWarning: 'rasa_nlu.test' found in sys.modules after import of package 'rasa_nlu', but prior to execution of 'rasa_nlu.test'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
2019-04-30 11:55:12 INFO     rasa_nlu.components  - Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-04-30 11:55:12 INFO     rasa_nlu.training_data.loading  - Training data format of export_data_format_train.json is rasa_nlu
2019-04-30 11:55:12 INFO     rasa_nlu.training_data.training_data  - Training data stats: 
	- intent examples: 0 (0 distinct intents)
	- Found intents: 
	- entity examples: 3 (9 distinct entities)
	- found entities: 'soft_skills', 'technical_skills', 'degree', 'salary', 'job_position', 'degree_major', 'job_location', 'overall_work_experience', 'technology_work_experience'

Traceback (most recent call last):
  File "/home/user/anaconda2/envs/jd_matcher/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/user/anaconda2/envs/jd_matcher/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/anaconda2/envs/jd_matcher/lib/python3.6/site-packages/rasa_nlu/test.py", line 1001, in <module>
    main()
  File "/home/user/anaconda2/envs/jd_matcher/lib/python3.6/site-packages/rasa_nlu/test.py", line 995, in main
    cmdline_args.histogram)
  File "/home/user/anaconda2/envs/jd_matcher/lib/python3.6/site-packages/rasa_nlu/test.py", line 744, in run_evaluation
    intent_targets = [None] * test_data.training_examples
TypeError: can't multiply sequence by non-int of type 'list'
```

**Comment by erohmensing** [comment]
HI @Nomiluks, the runtime warning is just a warning and shouldn't have anything to do with your error. However you do seem to have run into a bug! I believe that line 744 should say
```
intent_targets = [None] * len(test_data.training_examples)
```
Thanks for catching -- we don't have many people running the test script without an intent classifier in their pipeline, so it was a pretty sneaky bug. I'll make sure to fix it.

**Comment by Nomiluks** [comment]
> HI @Nomiluks, the runtime warning is just a warning and shouldn't have anything to do with your error. However you do seem to have run into a bug! I believe that line 744 should say
> 
> ```
> intent_targets = [None] * len(test_data.training_examples)
> ```
> 
> Thanks for catching -- we don't have many people running the NLU test script without an intent classifier in their pipeline, so it was a pretty sneaky bug. I'll make sure to fix it.

thanks looking forward.

**Comment by Nomiluks** [comment]
> intent_targets = [None] * len(test_data.training_examples)

@erohmensing  I have added following changes in rasa_nlu/test.py code:

`        # intent_targets = [None] * test_data.training_examples
        intent_targets = [None] * len(test_data.training_examples)`

But getting another error can you help me to fix this one?

`/home/user/anaconda2/envs/jd_matcher/lib/python3.6/runpy.py:125: RuntimeWarning: 'rasa_nlu.test' found in sys.modules after import of package 'rasa_nlu', but prior to execution of 'rasa_nlu.test'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
2019-05-02 14:29:13 INFO     rasa_nlu.components  - Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-05-02 14:29:13 INFO     rasa_nlu.training_data.loading  - Training data format of export_data_format_test.json is rasa_nlu
2019-05-02 14:29:13 INFO     rasa_nlu.training_data.training_data  - Training data stats: 
	- intent examples: 0 (0 distinct intents)
	- Found intents: 
	- entity examples: 0 (0 distinct entities)
	- found entities: 

2019-05-02 14:29:13 INFO     __main__  - Running model for predictions:
0it [00:00, ?it/s]
2019-05-02 14:29:13 INFO     __main__  - Entity evaluation results:
2019-05-02 14:29:13 INFO     __main__  - Evaluation for entity extractor: CRFEntityExtractor 
Traceback (most recent call last):
  File "/home/user/anaconda2/envs/jd_matcher/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/user/anaconda2/envs/jd_matcher/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/user/anaconda2/envs/jd_matcher/lib/python3.6/site-packages/rasa_nlu/test.py", line 1002, in <module>
    main()
  File "/home/user/anaconda2/envs/jd_matcher/lib/python3.6/site-packages/rasa_nlu/test.py", line 996, in main
    cmdline_args.histogram)
  File "/home/user/anaconda2/envs/jd_matcher/lib/python3.6/site-packages/rasa_nlu/test.py", line 780, in run_evaluation
    report_folder)
  File "/home/user/anaconda2/envs/jd_matcher/lib/python3.6/site-packages/rasa_nlu/test.py", line 421, in evaluate_entities
    merged_targets, merged_predictions)
  File "/home/user/anaconda2/envs/jd_matcher/lib/python3.6/site-packages/rasa_nlu/test.py", line 181, in get_evaluation_metrics
    output_dict=output_dict)
  File "/home/user/.local/lib/python3.6/site-packages/sklearn/metrics/classification.py", line 1568, in classification_report
    name_width = max(len(cn) for cn in target_names)
ValueError: max() arg is an empty sequence`

**Comment by math77** [comment]
Hi @erohmensing 

When running the following command

`python3 -m rasa_nlu.train -c nlu_config.yml --data data/nlu.md -o model --fixed_model_name nlu --project current --verbose`

I'm getting the following errors at my prompt

`RuntimeWarning: 'rasa_nlu.train' found in sys.modules after import of package 'rasa_nlu', but prior to execution of 'rasa_nlu.train'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
2019-05-08 22:27:36.044846: F tensorflow/core/platform/cpu_feature_guard.cc:37] The TensorFlow library was compiled to use AVX instructions, but these aren't available on your machine.
`

**Comment by erohmensing** [comment]
Hey @math77 , these are just warnings that you can ignore. We haven't found any "unpredictable behaviour" as a result of that first warning so far. 🙂

**Comment by math77** [comment]
Hey @erohmensing 

When executing the command I believe that it is not creating the models directory.

**Comment by math77** [comment]
When you run the following code

`from rasa_nlu.model import Interpreter
import json
interpreter = Interpreter.load("./models/current/nlu")
message = "let's see some italian restaurants"
result = interpreter.parse(message)
print(json.dumps(result, indent=2))`

My prompt returns the following message: 

`  File "run.py", line 3, in <module>
    interpreter = Interpreter.load("./models/current/nlu")
  File "/home/matheus/anaconda3/envs/robot/lib/python3.6/site-packages/rasa_nlu/model.py", line 299, in load
    model_metadata = Metadata.load(model_dir)
  File "/home/matheus/anaconda3/envs/robot/lib/python3.6/site-packages/rasa_nlu/model.py", line 73, in load
    "from '{}'. {}".format(abspath, e))
rasa_nlu.model.InvalidProjectError: Failed to load model metadata from '/home/matheus/Documentos/projects/estudos/studies-rasa-lib/hall/models/current/nlu/metadata.json'. [Errno 2] No such file or directory: './models/current/nlu/metadata.json'
`

**Comment by erohmensing** [comment]
This is because you're using `-o model` , so it's outputting in the `model` directory, but you're looking for it in the `models` directory. 

Your usage problem is not relevant to this github issue, please ask usage questions like these in the [forum](https://forum.rasa.com). Also, in a case like this, it's best to take a look into your actual directories to see if it has created the directory if you don't believe it did -- this will show you that it created a directory by another name due to a typo.
