### ISSUE TITLE
Exception connection Facebook Messenger on a dockerized Rasa

### ISSUE THREAD

**Issue by ramsesdm** [RasaHQ/rasa#3147]
**Rasa version**:
docker-compose file

```
version: '3.0'

services:
  rasa_core:
    container_name: rasa_core
    restart: always
    image: rasa/rasa_core:stable
    ports:
      - 5002:5005
    volumes:
      - ./models/rasa_core:/app/models
      - ./config:/app/config
    command: start --core models -c facebook --endpoints config/endpoints.yml -u current/ --credentials config/messenger-credentials.yml

  rasa_nlu:
    container_name: rasa_nlu
    restart: always
    image: rasa/rasa_nlu:0.14.4-full
    volumes:
      - ./models/rasa_nlu:/app/models
      - ./config:/app/config
    command: start --path models -c config/nlu_config.yml

  action_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: action_server
    restart: always
    volumes:
      - ./actions:/app/actions

```

**Python version**: 
Python 3.6

**Operating system** (windows, osx, ...):
Ubuntu 18.04

**Issue**:

Stablishing connection from Facebook messenger I get this error.
I am running Rasa with Docker
```
[2019-03-25 19:50:58 +0000] [1] [ERROR] Exception occurred in one of response middleware handlers
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 791, in handle_request
    request, response
  File "/usr/local/lib/python3.6/site-packages/spf/framework.py", line 543, in _run_response_middleware
    _response = await _response
  File "/usr/local/lib/python3.6/site-packages/sanic_cors/extension.py", line 266, in unapplied_cors_response_middleware
    set_cors_headers(req, resp, context, res_options)
  File "/usr/local/lib/python3.6/site-packages/sanic_cors/core.py", line 248, in set_cors_headers
    if resp.headers is None:
AttributeError: 'str' object has no attribute 'headers'
2019-03-25 19:50:58 ERROR    sanic.error  - Exception occurred in one of response middleware handlers
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 791, in handle_request
    request, response
  File "/usr/local/lib/python3.6/site-packages/spf/framework.py", line 543, in _run_response_middleware
    _response = await _response
  File "/usr/local/lib/python3.6/site-packages/sanic_cors/extension.py", line 266, in unapplied_cors_response_middleware
    set_cors_headers(req, resp, context, res_options)
  File "/usr/local/lib/python3.6/site-packages/sanic_cors/core.py", line 248, in set_cors_headers
    if resp.headers is None:
AttributeError: 'str' object has no attribute 'headers'
2019-03-25 19:50:58 ERROR    sanic.root  - Invalid response object for url b'/webhooks/facebook/webhook?hub.mode=subscribe&hub.challenge=1456896537&hub.verify_token=rasa-bot', Expected Type: HTTPResponse, Actual Type: <class 'str'>
[2019-03-25 19:50:58 +0000] [1] [ERROR] Invalid response object for url b'/webhooks/facebook/webhook?hub.mode=subscribe&hub.challenge=1456896537&hub.verify_token=rasa-bot', Expected Type: HTTPResponse, Actual Type: <class 'str'>
[2019-03-25 19:50:58 +0000] [1] [ERROR] Exception occurred while handling uri: 'http://some-azure-url:443/webhooks/facebook/webhook?hub.mode=subscribe&hub.challenge=1456896537&hub.verify_token=rasa-bot'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sanic/server.py", line 374, in write_response
    response.output(
AttributeError: 'str' object has no attribute 'output'
2019-03-25 19:50:58 ERROR    sanic.root  - Exception occurred while handling uri: 'http://some-azure-url:443/webhooks/facebook/webhook?hub.mode=subscribe&hub.challenge=1456896537&hub.verify_token=rasa-bot'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sanic/server.py", line 374, in write_response
    response.output(
AttributeError: 'str' object has no attribute 'output'

```

**Content of configuration file (config.yml)**:
```
language: "en"
pipeline: "spacy_sklearn"
```

**Dockerfile**
```
FROM rasa/rasa_core_sdk:0.12.2

RUN apt-get update && apt-get install -y mc nano git

COPY requirements.txt /app/requirements.txt

RUN python -m pip install --upgrade pip && \
    python -m pip install --no-cache-dir requests && \
    python -m pip install --no-cache-dir elasticsearch && \
    python -m pip install -r /app/requirements.txt

RUN python -m spacy download en
```

I am able to connect FB Messenger running Rasa on my local (without docker)

**Comment by akelad** [comment]
Thanks for raising this issue, @wochinge  will get back to you about it soon.

**Comment by wochinge** [comment]
@ramsesdm Can you please try to drop the `-c facebook` parameter in your start command? I think this overwrite your configuration which you did in the credentials file.
