### ISSUE TITLE
Fallback action issue

### ISSUE THREAD

**Issue by Robertjbc** [RasaHQ/rasa#3217]
**rasa:_core:0.13.7**:
   rasa_nlu 0.16.4
**Python version**: 

**windows 10** (windows, osx, ...):

hello rasa friend i have a issue from the fallback actions i try to do in a custom action how appears in https://rasa.com/docs/core/fallbacks/#fallbacks 
but they give me this error:

`C:\Users\capitalminds\Desktop\oncloud365>py -m rasa_core_sdk.endpoint --actions actions
2019-04-06 13:11:17 INFO     __main__  - Starting action endpoint server...
2019-04-06 13:11:17 ERROR    rasa_core_sdk.executor  - Failed to register package 'actions'.
Traceback (most recent call last):
  File "C:\Users\capitalminds\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core_sdk\executor.py", line 144, in register_package
    self._import_submodules(package)
  File "C:\Users\capitalminds\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core_sdk\executor.py", line 131, in _import_submodules
    package = importlib.import_module(package)
  File "C:\Users\capitalminds\AppData\Local\Programs\Python\Python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\capitalminds\Desktop\oncloud365\actions.py", line 2, in <module>
    from rasa.core import events
ModuleNotFoundError: No module named 'rasa'
2019-04-06 13:11:17 INFO     __main__  - Action endpoint is up and running. on ('0.0.0.0', 5055)
`
 i need to do a default answer so if you can help me i´ll appreciate that

**Comment by erohmensing** [comment]
> rasa_nlu 0.16.4

Can you re-check that? This version of rasa_nlu doesn't exist yet. The most likely problem is that here:
```
File "C:\Users\capitalminds\Desktop\oncloud365\actions.py", line 2, in <module> from rasa.core import events ModuleNotFoundError: No module named 'rasa'
```
it looks like imports in your action files are incorrect -- this should look like `from rasa_core import events`, so long as you're not trying to get all of your code from the recently merged repo (which I assume you're not, since you're still using `rasa_core`). Try changing those imports and let me know if you have more luck :)

**Comment by Robertjbc** [comment]
hello erohemensing i think i´ll solve it,  i change the name of the default fallback action with a config.yml i retrained the bot and its work but i have other issue:

my answer by default always appears after the 2nd attempt not recognizable an example if I put: I'm not in an intent ...
always gives me another answer and I put it a second time and there if I get the default answer

so mi question is how i can do if the user put a not recognizable intent the bot say the first time the default answer

from the rasa nlu version es the 0.14.6

**Comment by erohmensing** [comment]
Hmm, are you using the `TwoStageFallbackPolicy`?
