### ISSUE TITLE
Failed to parse text error getting intent

### ISSUE THREAD

**Issue by ramsesdm** [RasaHQ/rasa#3277]
**Rasa version**:
**Running on Docker:**
rasa/rasa_core:stable
rasa/rasa_nlu:stable-full
rasa/rasa_core_sdk:latest

**Python version**: 
python-3.7

**Operating system** (windows, osx, ...):
Ubuntu 18.04
**Issue**:
I am running RASA on docker but trying to get an intent I got the following error

```
2019-04-17 20:13:59 DEBUG    rasa_core.tracker_store  - Creating a new tracker for id 'badb49a3a7924104bfc3dd24d6ce6ca6'.
2019-04-17 20:14:15 ERROR    rasa_core.interpreter  - Failed to parse text 'where is my order?' using rasa NLU over http. Error: {
  "error": "join() argument must be str or bytes, not 'NoneType'"
}
2019-04-17 20:14:15 DEBUG    rasa_core.processor  - Received user message 'where is my order?' with intent '{'name': '', 'confidence': 0.0}' and entities '[]'
2019-04-17 20:14:15 DEBUG    rasa_core.processor  - Logged UserUtterance - tracker now has 2 events
2019-04-17 20:14:15 DEBUG    rasa_core.processor  - Current slot values:
        order: None
        orders: None
        period: None
        requested_slot: None
2019-04-17 20:14:15 DEBUG    rasa_core.policies.memoization  - Current tracker state [None, None, None, {}, {'prev_action_listen': 1.0}]
2019-04-17 20:14:15 DEBUG    rasa_core.policies.memoization  - There is no memorised next action
2019-04-17 20:14:15 DEBUG    rasa_core.policies.form_policy  - There is no active form
2019-04-17 20:14:15 DEBUG    rasa_core.policies.fallback  - NLU confidence 0.0 is lower than NLU threshold 0.3.
2019-04-17 20:14:15 DEBUG    rasa_core.policies.ensemble  - Predicted next action using policy_3_FallbackPolicy
2019-04-17 20:14:15 DEBUG    rasa_core.processor  - Predicted next action 'action_default_fallback' with prob 1.00.
2019-04-17 20:14:15 DEBUG    rasa_core.actions.action  - Calling action endpoint to run action 'action_default_fallback'.
2019-04-17 20:14:15 ERROR    rasa_core.actions.action  - Failed to run custom action 'action_default_fallback'. Action server responded with a non 200 status code of 500. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: 500 Server Error: INTERNAL SERVER ERROR for url: http://action_server:5055/webhook
2019-04-17 20:14:15 ERROR    rasa_core.processor  - Encountered an exception while running action 'action_default_fallback'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
2019-04-17 20:14:15 DEBUG    rasa_core.processor  - Failed to execute custom action.
Traceback (most recent call last):
  File "/app/rasa_core/actions/action.py", line 342, in run
    response.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: INTERNAL SERVER ERROR for url: http://action_server:5055/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/rasa_core/processor.py", line 346, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/app/rasa_core/actions/action.py", line 362, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
2019-04-17 20:14:15 DEBUG    rasa_core.processor  - Action 'action_default_fallback' ended with events '[]'
2019-04-17 20:14:15 DEBUG    rasa_core.policies.memoization  - Current tracker state [None, None, {}, {'prev_action_listen': 1.0}, {'prev_action_default_fallback': 1.0}]
2019-04-17 20:14:15 DEBUG    rasa_core.policies.memoization  - There is no memorised next action
2019-04-17 20:14:15 DEBUG    rasa_core.policies.form_policy  - There is no active form
2019-04-17 20:14:15 DEBUG    rasa_core.policies.ensemble  - Predicted next action using policy_3_FallbackPolicy
2019-04-17 20:14:15 DEBUG    rasa_core.processor  - Predicted next action 'action_listen' with prob 1.00.
2019-04-17 20:14:15 DEBUG    rasa_core.processor  - Action 'action_listen' ended with events '[]'

```

Here my docker-compose.yml
```
version: '3.0'

networks:
  baseai_network:
    external: true

services:
  rasa_core:
    container_name: rasa_core
    restart: always
    image: rasa/rasa_core:stable
    ports:
      - 5002:5005
    volumes:
      - ./models:/app/models
      - ./config:/app/config
      - ./models/current/dialogue/policy_metadata.json:/app/models/policy_metadata.json
    command: start --core models -c socketio --endpoints config/endpoints.yml -u current/ --credentials config/credentials.yml --debug
    networks:
      - baseai_network

  rasa_nlu:
    container_name: rasa_nlu
    restart: always
    image: rasa/rasa_nlu:stable-full
    volumes:
      - ./models:/app/models
      - ./config:/app/config
    command: start --path models -c config/nlu_config.yml
    networks:
      - baseai_network

  action_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: action_server
    restart: always
    volumes:
      - ./actions:/app/actions
    networks:
      - baseai_network
```
Here my Dockerfile

```
FROM rasa/rasa_core_sdk:latest

RUN apt-get update && apt-get install -y mc nano git

COPY requirements.txt /app/requirements.txt

RUN python -m pip install --upgrade pip && \
    python -m pip install --no-cache-dir requests && \
    python -m pip install --no-cache-dir elasticsearch && \
    python -m pip install -r /app/requirements.txt

RUN python -m spacy download en

```

Running these before docker-compose up -d

```
docker run -v $(pwd):/app/project -v $(pwd)/models:/app/models rasa/rasa_core:latest train --domain project/domain.yml --stories project/data/stories.md --out models
```

and
```
docker run -v $(pwd):/app/project -v $(pwd)/models:/app/models rasa/rasa_nlu:latest-spacy run python -m rasa_nlu.train -c config.yml -d project/data/nlu_data.md -o models --project current
```

Am I missing something?

**Content of configuration file (config.yml)**:
```yml
language: "en"
pipeline: "spacy_sklearn"

```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml

```

**Comment by akelad** [comment]
Thanks for raising this issue, @wochinge  will get back to you about it soon.

**Comment by ramsesdm** [comment]
**More information**

```
root@1e14d1246b0c:/app# curl localhost:5000/status
{
  "max_training_processes": 1,
  "current_training_processes": 0,
  "available_projects": {
    "policy_metadata.json": {
      "status": "ready",
      "error_message": null,
      "current_training_processes": 0,
      "available_models": [
        "fallback"
      ],
      "loaded_models": [
        "fallback"
      ]
    },
    "policy_1_FallbackPolicy": {
      "status": "ready",
      "error_message": null,
      "current_training_processes": 0,
      "available_models": [
        "fallback"
      ],
      "loaded_models": [
        "fallback"
      ]
    },
    "policy_3_FormPolicy": {
      "status": "ready",
      "error_message": null,
      "current_training_processes": 0,
      "available_models": [
        "fallback"
      ],
      "loaded_models": [
        "fallback"
      ]
    },
    "policy_2_MemoizationPolicy": {
      "status": "ready",
      "error_message": null,
      "current_training_processes": 0,
      "available_models": [
        "fallback"
      ],
      "loaded_models": [
        "fallback"
      ]
    },
    "domain.json": {
      "status": "ready",
      "error_message": null,
      "current_training_processes": 0,
      "available_models": [
        "fallback"
      ],
      "loaded_models": [
        "fallback"
      ]
    },
    "current": {
      "status": "ready",
      "error_message": null,
      "current_training_processes": 0,
      "available_models": [
        "nlu",
        "model_20190416-155756",
        "dialogue"
      ],
      "loaded_models": []
    },
    "policy_0_KerasPolicy": {
      "status": "ready",
      "error_message": null,
      "current_training_processes": 0,
      "available_models": [
        "fallback"
      ],
      "loaded_models": [
        "fallback"
      ]
    },
    "domain.yml": {
      "status": "ready",
      "error_message": null,
      "current_training_processes": 0,
      "available_models": [
        "fallback"
      ],
      "loaded_models": [
        "fallback"
      ]
    },
    "metadata.json": {
      "status": "ready",
      "error_message": null,
      "current_training_processes": 0,
      "available_models": [
        "fallback"
      ],
      "loaded_models": [
        "fallback"
      ]
    }
  }
}
```

**Comment by akelad** [comment]
@wochinge ^

**Comment by wochinge** [comment]
@ramsesdm Seems to be an error in your action server. What do the logs of the custom action server say?
