### ISSUE TITLE
rasa test nlu does not load intent data from -u

### ISSUE THREAD

**Issue by MetcalfeTom** [RasaHQ/rasa#3282]
Passing a file instead of a directory leads to the following error:
```
2019-04-18 15:49:29 INFO     rasa.nlu.test  - Intent Evaluation: Only considering those 0 examples that have a defined intent out of 0 examples
Traceback (most recent call last):
  File "/Users/tom/.pyenv/versions/3.6.8/bin/rasa", line 11, in <module>
    load_entry_point('rasa', 'console_scripts', 'rasa')()
  File "/Users/tom/Documents/RASA/rasa_nlu/rasa/__main__.py", line 64, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/Users/tom/Documents/RASA/rasa_nlu/rasa/cli/test.py", line 195, in test_nlu
    test_nlu(nlu_data=nlu_data, **vars(args))
  File "/Users/tom/Documents/RASA/rasa_nlu/rasa/test.py", line 87, in test_nlu
    run_evaluation(nlu_data, nlu_model, **kwargs)
  File "/Users/tom/Documents/RASA/rasa_nlu/rasa/nlu/test.py", line 831, in run_evaluation
    intent_hist_filename,
  File "/Users/tom/Documents/RASA/rasa_nlu/rasa/nlu/test.py", line 364, in evaluate_intents
    targets, predictions = _targets_predictions_from(intent_results)
ValueError: not enough values to unpack (expected 2, got 0)
```

**Comment by Ghostvv** [comment]
also i think it doesn’t read the data form `-u` argument is it should based on help description:
```
rasa test nlu -u data/nlu/1000_persona.md --model models/nlu-20190418-153326.tar.gz

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

2019-04-18 15:36:32 INFO     tensorflow  - Entry Point [tensor2tensor.envs.tic_tac_toe_env:TicTacToeEnv] registered with id [T2TEnv-TicTacToeEnv-v0]
2019-04-18 15:36:33.068971: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-04-18 15:36:34 WARNING  tensorflow  - From /usr/local/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1266: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
2019-04-18 15:36:34 INFO     tensorflow  - Restoring parameters from /var/folders/k6/6hbz34d90fl1s5ywp6srmsg80000gn/T/tmpcjj56kbr/nlu/component_2_EmbeddingIntentClassifier.ckpt
2019-04-18 15:36:35 INFO     rasa.nlu.training_data.training_data  - Training data stats: 
    - intent examples: 0 (0 distinct intents)
    - Found intents: 
    - entity examples: 0 (0 distinct entities)
    - found entities: 

2019-04-18 15:36:35 INFO     rasa.nlu.test  - Running model for predictions:
0it [00:00, ?it/s]
2019-04-18 15:36:35 INFO     rasa.nlu.test  - Intent evaluation results:
2019-04-18 15:36:35 INFO     rasa.nlu.test  - Intent Evaluation: Only considering those 0 examples that have a defined intent out of 0 examples
Traceback (most recent call last):
  File "/usr/local/bin/rasa", line 11, in <module>
    load_entry_point('rasa', 'console_scripts', 'rasa')()
  File "/Users/ghost/Documents/rasa/rasa/rasa/__main__.py", line 64, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/Users/ghost/Documents/rasa/rasa/rasa/cli/test.py", line 195, in test_nlu
    test_nlu(nlu_data=nlu_data, **vars(args))
  File "/Users/ghost/Documents/rasa/rasa/rasa/test.py", line 87, in test_nlu
    run_evaluation(nlu_data, nlu_model, **kwargs)
  File "/Users/ghost/Documents/rasa/rasa/rasa/nlu/test.py", line 831, in run_evaluation
    intent_hist_filename,
  File "/Users/ghost/Documents/rasa/rasa/rasa/nlu/test.py", line 364, in evaluate_intents
    targets, predictions = _targets_predictions_from(intent_results)
ValueError: not enough values to unpack (expected 2, got 0)
```

**Comment by erohmensing** [comment]
btw, we're collecting CLI info here https://github.com/RasaHQ/rasa/issues/3272

**Comment by KarthikMgk** [comment]
I read both #3292 and #3282. Still, I'm not able to figure out the solution. I tried passing data using both --nlu and -u.

**Comment by erohmensing** [comment]
@KarthikMgk pretty sure this works now, can you create a post on our [forum](http://forum.rasa.com) to ask how to do it correctly? along with the commands you are running, the output, and the directory structure of your project
