### ISSUE TITLE
MappingPolicy throwing error

### ISSUE THREAD

**Issue by einarbmag** [RasaHQ/rasa#3328]
**Rasa version**:
rasa-core==0.14.0
rasa-core-sdk==0.13.1
rasa-nlu==0.15.0

**Python version**: 

Python 3.6.5 :: Anaconda, Inc.

**Operating system** (windows, osx, ...):
OSX 10.13.6
**Issue**:

Some of my mappings cause MappingPolicy to throw an error. Haven't been able to isolate the issue properly (this error happens for intents `greeting, goodbye, availableFunctions`, but not for `getBalance`, see yml files below):

```
Your input ->  what can you do                                                                                                                                                                              
Exception in thread Thread-39:
Traceback (most recent call last):
  File "/Users/44097208/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/44097208/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/44097208/Development/dtc_hssbot/venv/lib/python3.6/site-packages/rasa_core/channels/channel.py", line 324, in on_message_wrapper
    on_new_message(message)
  File "/Users/44097208/Development/dtc_hssbot/venv/lib/python3.6/site-packages/rasa_core/agent.py", line 322, in handle_message
    return processor.handle_message(message)
  File "/Users/44097208/Development/dtc_hssbot/venv/lib/python3.6/site-packages/rasa_core/processor.py", line 77, in handle_message
    self._predict_and_execute_next_action(message, tracker)
  File "/Users/44097208/Development/dtc_hssbot/venv/lib/python3.6/site-packages/rasa_core/processor.py", line 298, in _predict_and_execute_next_action
    action, policy, confidence = self.predict_next_action(tracker)
  File "/Users/44097208/Development/dtc_hssbot/venv/lib/python3.6/site-packages/rasa_core/processor.py", line 158, in predict_next_action
    probabilities, policy = self._get_next_action_probabilities(tracker)
  File "/Users/44097208/Development/dtc_hssbot/venv/lib/python3.6/site-packages/rasa_core/processor.py", line 471, in _get_next_action_probabilities
    tracker, self.domain)
  File "/Users/44097208/Development/dtc_hssbot/venv/lib/python3.6/site-packages/rasa_core/policies/ensemble.py", line 340, in probabilities_using_best_policy
    probabilities = p.predict_action_probabilities(tracker, domain)
  File "/Users/44097208/Development/dtc_hssbot/venv/lib/python3.6/site-packages/rasa_core/policies/mapping_policy.py", line 64, in predict_action_probabilities
    assert latest_action.name == action
AttributeError: 'ActionExecuted' object has no attribute 'name'
```

**Content of configuration file (config.yml)**:
```yml
policies:
  - name: KerasPolicy
    epochs: 100
    max_history: 5
  - name: FallbackPolicy
    fallback_action_name: 'action_default_fallback'
  - name: MemoizationPolicy
    max_history: 5
  - name: FormPolicy
  - name: MappingPolicy
```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml
intents:
  - greeting: {triggers: utter_greet}
  - goodbye: {triggers: utter_goodbye}
  - availableFunctions: {triggers: action_availableFunctions}
  - affirm
  - deny
  - getBalance: {triggers: action_getBalance}

actions:
  - utter_greet
  - utter_goodbye
  - action_availableFunctions
  - action_getBalance

etc...
```

**Comment by einarbmag** [comment]
PS. I tried changing line 64 in `mapping_policy.py` from
```
assert latest_action.name == action
to
assert latest_action.action_name == action
```
and it seems to work now.

**Comment by erohmensing** [comment]
Yes, i think you're right. Is it working for all of your intents now, including `getBalance`? I'm trying to figure out why it worked before. Are you sure it was the mapping policy that predicted the action when it worked?

**Comment by akelad** [comment]
@erohmensing are you opening a PR for this? please do so off of 0.14.x on the rasa_core repo

**Comment by einarbmag** [comment]
Yes, running core with --debug I see that the MappingPolicy determined `action_getBalance` and no error:
```
2019-04-26 15:01:50 DEBUG    rasa_core.policies.ensemble  - Predicted next action using policy_4_MappingPolicy
2019-04-26 15:01:50 DEBUG    rasa_core.processor  - Predicted next action 'action_getBalance' with prob 1.00.
2019-04-26 15:01:50 DEBUG    rasa_core.actions.action  - Calling action endpoint to run action 'action_getBalance'.
```
but the MappingPolicy fails on utter_greet.

**I've found a clue though:**
`action_getBalance` was returning a FollowupAction("..."), not the others. I tried returning an empty array in `action_getBalance` instead, and now it fails as well.

**Comment by erohmensing** [comment]
Hm okay so it looks like it is predicting the actions, just perhaps having trouble predicting the follow up? Can you show me what a broken one looks like on debug mode?

**Comment by einarbmag** [comment]
My last comment was perhaps confusing, it applies in the context of the un-modified core code with `assert latest_action.name == action`. With 'assert latest_action.action_name == action`, everything works fine. 

If you're still wanting to figure out why things worked in the first place for `action_getBalance`, here is the full debug printout (slightly redacted):

```
Your input ->  balance for R-111111-00-0                                                                                                                                                                    
2019-04-26 16:09:54 DEBUG    rasa_core.tracker_store  - Creating a new tracker for id 'default'.
2019-04-26 16:09:55 DEBUG    rasa_core.processor  - Received user message 'balance for R-111111-00-0' with intent '{'name': 'getBalance', **REDACTED**
2019-04-26 16:09:55 DEBUG    rasa_core.processor  - Logged UserUtterance - tracker now has 3 events
2019-04-26 16:09:55 DEBUG    rasa_core.processor  - Current slot values: 
	item: None
	requested_slot: None
	time: None
  **REDACTED**
2019-04-26 16:09:55 DEBUG    rasa_core.policies.memoization  - Current tracker state [None, None, None, {}, {'intent_getBalance': 1.0, 'entity_item_id': 1.0, 'prev_action_listen': 1.0, 'slot_item_id_0': 1.0}]
2019-04-26 16:09:55 DEBUG    rasa_core.policies.memoization  - There is no memorised next action
2019-04-26 16:09:55 DEBUG    rasa_core.policies.form_policy  - There is no active form
2019-04-26 16:09:55 DEBUG    rasa_core.policies.ensemble  - Predicted next action using policy_4_MappingPolicy
2019-04-26 16:09:55 DEBUG    rasa_core.processor  - Predicted next action 'action_getBalance' with prob 1.00.
2019-04-26 16:09:55 DEBUG    rasa_core.actions.action  - Calling action endpoint to run action 'action_getBalance'.
2019-04-26 16:09:55 DEBUG    rasa_core.processor  - Action 'action_getBalance' ended with events '['FollowupAction(action: utter_ask_followup)']'
2019-04-26 16:09:55 DEBUG    rasa_core.processor  - Bot utterance 'BotUttered(text: **REDACTED**, data: {
  "elements": null,
  "buttons": null,
  "attachment": null
})'
2019-04-26 16:09:55 DEBUG    rasa_core.processor  - Predicted next action 'utter_ask_followup' with prob 1.00.
**REDACTED**
2019-04-26 16:09:55 DEBUG    rasa_core.processor  - Action 'utter_ask_followup' ended with events '[]'
2019-04-26 16:09:55 DEBUG    rasa_core.processor  - Bot utterance 'BotUttered(text: **REDACTED**, data: {
  "elements": null,
  "buttons": null,
  "attachment": null
})'
**REDACTED**
2019-04-26 16:09:55 DEBUG    rasa_core.policies.memoization  - Current tracker state [None, {}, {'intent_getBalance': 1.0, 'entity_item_id': 1.0, 'prev_action_listen': 1.0, 'slot_item_id_0': 1.0}, {'prev_action_getBalance': 1.0, 'intent_getBalance': 1.0, 'entity_item_id': 1.0, 'slot_item_id_0': 1.0}, {'prev_utter_ask_followup': 1.0, 'intent_getBalance': 1.0, 'entity_item_id': 1.0, 'slot_item_id_0': 1.0}]
2019-04-26 16:09:55 DEBUG    rasa_core.policies.memoization  - There is no memorised next action
2019-04-26 16:09:55 DEBUG    rasa_core.policies.form_policy  - There is no active form
2019-04-26 16:09:55 DEBUG    rasa_core.policies.ensemble  - Predicted next action using policy_0_KerasPolicy
2019-04-26 16:09:55 DEBUG    rasa_core.processor  - Predicted next action 'action_listen' with prob 0.91.
2019-04-26 16:09:55 DEBUG    rasa_core.processor  - Action 'action_listen' ended with events '[]'

```

**Comment by erohmensing** [comment]
Yes that makes sense, I actually wanted to see what a broken version (i.e. one of the ones with no follow up action and no fix) looks like though please :)

**Comment by einarbmag** [comment]
Ah of course, here:

```
Your input ->  hi                                                                                                                                                                                           
2019-04-26 16:31:58 DEBUG    rasa_core.tracker_store  - Creating a new tracker for id 'default'.
2019-04-26 16:31:58 DEBUG    rasa_core.processor  - Received user message 'hi' with intent '{'name': 'greeting', 'confidence': 0.8262557571011788}' and entities '[]'
2019-04-26 16:31:58 DEBUG    rasa_core.processor  - Logged UserUtterance - tracker now has 2 events
2019-04-26 16:31:58 DEBUG    rasa_core.processor  - Current slot values: 
	item: None
	requested_slot: None
	time: None
	item_detail: None
	item_id: None
	item_output: None
	item_status: None
2019-04-26 16:31:59 DEBUG    rasa_core.policies.memoization  - Current tracker state [None, None, None, {}, {'intent_greeting': 1.0, 'prev_action_listen': 1.0}]
2019-04-26 16:31:59 DEBUG    rasa_core.policies.memoization  - There is a memorised next action '8'
2019-04-26 16:31:59 DEBUG    rasa_core.policies.form_policy  - There is no active form
2019-04-26 16:31:59 DEBUG    rasa_core.policies.ensemble  - Predicted next action using policy_4_MappingPolicy
2019-04-26 16:31:59 DEBUG    rasa_core.processor  - Predicted next action 'utter_greet' with prob 1.00.
2019-04-26 16:31:59 DEBUG    rasa_core.processor  - Action 'utter_greet' ended with events '[]'
2019-04-26 16:31:59 DEBUG    rasa_core.processor  - Bot utterance 'BotUttered(text: Hello!, data: {
  "elements": null,
  "buttons": null,
  "attachment": null
})'
Hello!
2019-04-26 16:31:59 DEBUG    rasa_core.policies.memoization  - Current tracker state [None, None, {}, {'intent_greeting': 1.0, 'prev_action_listen': 1.0}, {'prev_utter_greet': 1.0, 'intent_greeting': 1.0}]
2019-04-26 16:31:59 DEBUG    rasa_core.policies.memoization  - There is a memorised next action '0'
2019-04-26 16:31:59 DEBUG    rasa_core.policies.form_policy  - There is no active form
Exception in thread Thread-9:
Traceback (most recent call last):
  File "/Users/44097208/anaconda3/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/44097208/anaconda3/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/44097208/Development/dtc_hssbot/venv/lib/python3.6/site-packages/rasa_core/channels/channel.py", line 324, in on_message_wrapper
    on_new_message(message)
  File "/Users/44097208/Development/dtc_hssbot/venv/lib/python3.6/site-packages/rasa_core/agent.py", line 322, in handle_message
    return processor.handle_message(message)
  File "/Users/44097208/Development/dtc_hssbot/venv/lib/python3.6/site-packages/rasa_core/processor.py", line 77, in handle_message
    self._predict_and_execute_next_action(message, tracker)
  File "/Users/44097208/Development/dtc_hssbot/venv/lib/python3.6/site-packages/rasa_core/processor.py", line 298, in _predict_and_execute_next_action
    action, policy, confidence = self.predict_next_action(tracker)
  File "/Users/44097208/Development/dtc_hssbot/venv/lib/python3.6/site-packages/rasa_core/processor.py", line 158, in predict_next_action
    probabilities, policy = self._get_next_action_probabilities(tracker)
  File "/Users/44097208/Development/dtc_hssbot/venv/lib/python3.6/site-packages/rasa_core/processor.py", line 471, in _get_next_action_probabilities
    tracker, self.domain)
  File "/Users/44097208/Development/dtc_hssbot/venv/lib/python3.6/site-packages/rasa_core/policies/ensemble.py", line 340, in probabilities_using_best_policy
    probabilities = p.predict_action_probabilities(tracker, domain)
  File "/Users/44097208/Development/dtc_hssbot/venv/lib/python3.6/site-packages/rasa_core/policies/mapping_policy.py", line 64, in predict_action_probabilities
    assert latest_action.name == action
AttributeError: 'ActionExecuted' object has no attribute 'name'

```

**Comment by erohmensing** [comment]
Okay great, thank you! As predicted, it successfully predicts utter_greet, it just gets messed up when it tries to predict the next action after. I've checked it out locally and get the same stuff, so your fix should work. Thank you!
