### ISSUE TITLE
Interactive : AttributeError: 'Namespace' object has no attribute 'cors'

### ISSUE THREAD

**Issue by saideep-g** [RasaHQ/rasa#3352]
**Rasa version**:
Core: 0.15.0a1
**Python version**: 
3.6
**Operating system** (windows, osx, ...):
Mac 10.14
**Issue**:

When I train with interactive using below command, I get error:
```
docker run -it   \
-v $(pwd):/app/project   \
-v $(pwd)/models/rasa_core:/app/models   \
rasa/rasa_core:latest   \
run python -m rasa_core.train interactive -o /app/project/models/rasa_core/ -s/app/project/data/stories.md -d /app/project/domain.yml  
```
I get below error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/rasa/core/train.py", line 246, in <module>
    main()
  File "/app/rasa/core/train.py", line 237, in main
    additional_args)
  File "/app/rasa/core/train.py", line 199, in do_interactive_learning
    if cmdline_args.cors and cmdline_args.finetune:
AttributeError: 'Namespace' object has no attribute 'cors'
```
however without interactive it trains successfully. Command without interactive:
```
docker run -it   \
-v $(pwd):/app/project   \
-v $(pwd)/models/rasa_core:/app/models   \
rasa/rasa_core:latest   \
run python -m rasa_core.train -o /app/project/models/rasa_core/ -s/app/project/data/stories.md -d /app/project/domain.yml 
```

This seems to be typo error where cors was used instead of core

**Comment by akelad** [comment]
This should be fixed in the master version of the code, please update to that
