### ISSUE TITLE
Inconsistent intent = inform_number extraction between installs

### ISSUE THREAD

**Issue by Zylatis** [RasaHQ/rasa#3357]
*NOTE*: This is to do with the comparison of results between two machines, unless otherwise stated the versions/results are common for both. Machine 1 is accurate, Machine 2 gives incorrect results

**Rasa version** (_both_ machines):
rasa-core                     0.14.0                
rasa-core-sdk                 0.14.0                
rasa-nlu                      0.15.0 

**Python version**:  (should this make a big diff?)
**Machine:** 1: 3.6.8
**Machine 2:** 3.6.7

**Operating system** (windows, osx, ...):
**Machine 1:** Ubuntu 16
**Machine 2:** Ubuntu 18

**Issue**:
I am getting incorrect intent classification for a number on a remote machine. Both machines are drawing from my same git repo and so identical data/configs. Each machine trains their own model locally (in fact i find if i try to move model from Machine 1 to Machine 2 there is a tensor dimension mismatch which may indicate the issue: 

```
Traceback (most recent call last):
  File "verify_nlu.py", line 12, in <module>
    print(interpreter.parse("6062"))
  File "/home/rasa-root/.local/lib/python3.6/site-packages/rasa_nlu/model.py", line 370, in parse
    component.process(message, **self.context)
  File "/home/rasa-root/.local/lib/python3.6/site-packages/rasa_nlu/classifiers/embedding_intent_classifier.py", line 594, in process
    intent_ids, message_sim = self._calculate_message_sim(X, all_Y)
  File "/home/rasa-root/.local/lib/python3.6/site-packages/rasa_nlu/classifiers/embedding_intent_classifier.py", line 555, in _calculate_message_sim
    self.b_in: all_Y})
  File "/home/rasa-root/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/home/rasa-root/.local/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1128, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1, 710) for Tensor 'a:0', which has shape '(?, 666)'
```

In both cases I am running the rasa/duckling docker container for the duckling server (locally on each machine with same ports etc).

I also find that the top intent changes quite a bit with repeated retraining on Machine 2, whereas it is stable with Machine 1, for example one time if i retrain NLU on Machine 2 i get deny as top intent for this input with confidence = 0.8! I have also tried wiping and re-cloning the repo (which works locally), to no avail.

Machine 1:
```md
{'intent': 
{'name': 'inform_number', 'confidence': 0.9882717132568359}, 
'entities': [{'start': 0, 'end': 4, 'value': '6062', 'entity': 'number', 'confidence': 0.7012308597111402, 'extractor': 'CRFEntityExtractor'}, {'start': 0, 'end': 4, 'text': '6062', 'value': 6062, 'confidence': 1.0, 'additional_info': {'value': 6062, 'type': 'value'}, 'entity': 'number', 'extractor': 'DucklingHTTPExtractor'}], 'intent_ranking': [{'name': 'inform_number', 'confidence': 0.9882717132568359}, 
{'name': 'goodbye', 'confidence': 0.021181941032409668},
 {'name': 'get_human', 'confidence': 0.0},
 {'name': 'interrupt', 'confidence': 0.0}, 
{'name': 'deny', 'confidence': 0.0},
 {'name': 'greet', 'confidence': 0.0},
 {'name': 'thanks_and_goodbye', 'confidence': 0.0},
 {'name': 'affirm', 'confidence': 0.0},
 {'name': 'quote', 'confidence': 0.0}, 
{'name': 'thanks', 'confidence': 0.0}], 
'text': '6062'}
```

Machine 2:
```md
{'intent': 
{'name': 'thanks_and_goodbye', 'confidence': 0.5872691869735718},
 'entities': [{'start': 0, 'end': 4, 'value': '6062', 'entity': 'number', 'confidence': 0.7012308597111402, 'extractor': 'CRFEntityExtractor'}, {'start': 0, 'end': 4, 'text': '6062', 'value': 6062, 'confidence': 1.0, 'additional_info': {'value': 6062, 'type': 'value'}, 'entity': 'number', 'extractor': 'DucklingHTTPExtractor'}], 'intent_ranking': [{'name': 'thanks_and_goodbye', 'confidence': 0.5872691869735718}, 
{'name': 'deny', 'confidence': 0.552628219127655},
 {'name': 'interrupt', 'confidence': 0.33768343925476074}, 
{'name': 'get_human', 'confidence': 0.1882050782442093}, 
{'name': 'quote', 'confidence': 0.0}, 
{'name': 'goodbye', 'confidence': 0.0},
 {'name': 'thanks', 'confidence': 0.0},
 {'name': 'inform_number', 'confidence': 0.0},
 {'name': 'affirm', 'confidence': 0.0}
, {'name': 'greet', 'confidence': 0.0}],
 'text': '6062'}
```

**Config file**
```yml
language: "en"
pipeline:
- name: "SpacyNLP"
- name: "SpacyTokenizer"
- name: "RegexFeaturizer"
- name: "SpacyFeaturizer"
- name: "CRFEntityExtractor"
- name: "CountVectorsFeaturizer"
- name: "EmbeddingIntentClassifier"
  epochs: 600
- name: "DucklingHTTPExtractor"
  url:  "http://0.0.0.0:8000"
  dimensions: ["time", "number", "distance"]
```

**Extract from nlu.md**:
```md

## intent:inform_number
- weight is probably about [15](number)kg
- [12](number) kg
- it is [100](number) kg
- it weighs [10](number) kg
- [1](number) kg
- it is [100](number) kg
- it weighs [10](number) kg
- [10](number)
- [1](number)
- [5](number)
- [1000](number)
- [10358](number)kg
- [10](number)kg
- [1](number)m
- [5](number)kg
- [1000](number)kg
- [10358](number)kg
- [just one](number:1)
- [only one](number:1)
- [just two](number:2)
- [only two](number:2)
- [one](number:1)
- [two](number:2)
```

Output of training the NLU on *Machine 1*
```
python3.6 -m rasa_nlu.train -c rasa_bits/config.yml --fixed_model_name current --data rasa_bits/data/nlu.md -o models --verbose
/usr/lib/python3.6/runpy.py:125: RuntimeWarning: 'rasa_nlu.train' found in sys.modules after import of package 'rasa_nlu', but prior to execution of 'rasa_nlu.train'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
2019-05-02 12:15:03 INFO     rasa_nlu.utils.spacy_utils  - Trying to load spacy model with name 'en'
2019-05-02 12:15:03 INFO     rasa_nlu.components  - Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-05-02 12:15:03 INFO     rasa_nlu.training_data.loading  - Training data format of rasa_bits/data/nlu.md is md
2019-05-02 12:15:03 INFO     rasa_nlu.training_data.training_data  - Training data stats: 
	- intent examples: 225 (10 distinct intents)
	- Found intents: 'quote', 'affirm', 'deny', 'thanks', 'greet', 'thanks_and_goodbye', 'interrupt', 'inform_number', 'get_human', 'goodbye'
	- entity examples: 88 (13 distinct entities)
	- found entities: 'length', 'name', 'quantity', 'number', 'weight', 'pickup_suburb', 'dropoff_residential', 'dropoff_suburb', 'dropoff_postcode', 'depth', 'height', 'width', 'pickup_postcode'

/usr/local/lib/python3.6/dist-packages/rasa_nlu/training_data/training_data.py:184: UserWarning: Entity 'dropoff_residential' has only 1 training examples! minimum is 2, training may fail.
  self.MIN_EXAMPLES_PER_ENTITY))
/usr/local/lib/python3.6/dist-packages/rasa_nlu/training_data/training_data.py:184: UserWarning: Entity 'name' has only 1 training examples! minimum is 2, training may fail.
  self.MIN_EXAMPLES_PER_ENTITY))
2019-05-02 12:15:03 INFO     rasa_nlu.model  - Starting to train component SpacyNLP
2019-05-02 12:15:05 INFO     rasa_nlu.model  - Finished training component.
2019-05-02 12:15:05 INFO     rasa_nlu.model  - Starting to train component SpacyTokenizer
2019-05-02 12:15:05 INFO     rasa_nlu.model  - Finished training component.
2019-05-02 12:15:05 INFO     rasa_nlu.model  - Starting to train component RegexFeaturizer
2019-05-02 12:15:05 INFO     rasa_nlu.model  - Finished training component.
2019-05-02 12:15:05 INFO     rasa_nlu.model  - Starting to train component SpacyFeaturizer
2019-05-02 12:15:05 INFO     rasa_nlu.model  - Finished training component.
2019-05-02 12:15:05 INFO     rasa_nlu.model  - Starting to train component CRFEntityExtractor
2019-05-02 12:15:06 INFO     rasa_nlu.model  - Finished training component.
2019-05-02 12:15:06 INFO     rasa_nlu.model  - Starting to train component CountVectorsFeaturizer
2019-05-02 12:15:06 INFO     rasa_nlu.model  - Finished training component.
2019-05-02 12:15:06 INFO     rasa_nlu.model  - Starting to train component EmbeddingIntentClassifier

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

2019-05-02 12:15:06 WARNING  tensorflow  - From /usr/local/lib/python3.6/dist-packages/rasa_nlu/classifiers/embedding_intent_classifier.py:285: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.dense instead.
2019-05-02 12:15:06 WARNING  tensorflow  - From /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-05-02 12:15:06 WARNING  tensorflow  - From /usr/local/lib/python3.6/dist-packages/rasa_nlu/classifiers/embedding_intent_classifier.py:286: dropout (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.dropout instead.
2019-05-02 12:15:06 WARNING  tensorflow  - From /usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/layers/core.py:143: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
2019-05-02 12:15:07 WARNING  tensorflow  - From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
2019-05-02 12:15:07 WARNING  tensorflow  - From /usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/math_grad.py:102: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
2019-05-02 12:15:07.426142: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-05-02 12:15:07.429773: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2712000000 Hz
2019-05-02 12:15:07.430069: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0xa1f0e30 executing computations on platform Host. Devices:
2019-05-02 12:15:07.430095: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-05-02 12:15:07 INFO     rasa_nlu.classifiers.embedding_intent_classifier  - Accuracy is updated every 10 epochs
Epochs: 100%|██████████| 600/600 [00:09<00:00, 60.94it/s, loss=0.036, acc=1.000]
2019-05-02 12:15:17 INFO     rasa_nlu.classifiers.embedding_intent_classifier  - Finished training embedding classifier, loss=0.036, train accuracy=1.000
2019-05-02 12:15:17 INFO     rasa_nlu.model  - Finished training component.
2019-05-02 12:15:17 INFO     rasa_nlu.model  - Starting to train component DucklingHTTPExtractor
2019-05-02 12:15:17 INFO     rasa_nlu.model  - Finished training component.
2019-05-02 12:15:17 INFO     rasa_nlu.model  - Successfully saved model into '/home/graeme/coding_local/freight_exchange_codes/chatbot_code/models/default/current'
2019-05-02 12:15:17 INFO     __main__  - Finished training
```

NLU Training log from *Machine 2*
```
python3.6 -m rasa_nlu.train -c rasa_bits/config.yml --fixed_model_name current --data rasa_bits/data/nlu.md -o models --verbose
/usr/lib/python3.6/runpy.py:125: RuntimeWarning: 'rasa_nlu.train' found in sys.modules after import of package 'rasa_nlu', but prior to execution of 'rasa_nlu.train'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
2019-05-02 02:16:51 INFO     rasa_nlu.utils.spacy_utils  - Trying to load spacy model with name 'en'
2019-05-02 02:17:03 INFO     rasa_nlu.components  - Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2019-05-02 02:17:03 INFO     rasa_nlu.training_data.loading  - Training data format of rasa_bits/data/nlu.md is md
2019-05-02 02:17:03 INFO     rasa_nlu.training_data.training_data  - Training data stats: 
	- intent examples: 225 (10 distinct intents)
	- Found intents: 'quote', 'goodbye', 'thanks_and_goodbye', 'thanks', 'interrupt', 'get_human', 'inform_number', 'deny', 'affirm', 'greet'
	- entity examples: 88 (13 distinct entities)
	- found entities: 'length', 'pickup_postcode', 'dropoff_suburb', 'height', 'quantity', 'weight', 'depth', 'dropoff_postcode', 'number', 'dropoff_residential', 'width', 'name', 'pickup_suburb'

/home/rasa-root/.local/lib/python3.6/site-packages/rasa_nlu/training_data/training_data.py:184: UserWarning: Entity 'dropoff_residential' has only 1 training examples! minimum is 2, training may fail.
  self.MIN_EXAMPLES_PER_ENTITY))
/home/rasa-root/.local/lib/python3.6/site-packages/rasa_nlu/training_data/training_data.py:184: UserWarning: Entity 'name' has only 1 training examples! minimum is 2, training may fail.
  self.MIN_EXAMPLES_PER_ENTITY))
2019-05-02 02:17:03 INFO     rasa_nlu.model  - Starting to train component SpacyNLP
2019-05-02 02:17:05 INFO     rasa_nlu.model  - Finished training component.
2019-05-02 02:17:05 INFO     rasa_nlu.model  - Starting to train component SpacyTokenizer
2019-05-02 02:17:05 INFO     rasa_nlu.model  - Finished training component.
2019-05-02 02:17:05 INFO     rasa_nlu.model  - Starting to train component RegexFeaturizer
2019-05-02 02:17:05 INFO     rasa_nlu.model  - Finished training component.
2019-05-02 02:17:05 INFO     rasa_nlu.model  - Starting to train component SpacyFeaturizer
2019-05-02 02:17:05 INFO     rasa_nlu.model  - Finished training component.
2019-05-02 02:17:05 INFO     rasa_nlu.model  - Starting to train component CRFEntityExtractor
2019-05-02 02:17:05 INFO     rasa_nlu.model  - Finished training component.
2019-05-02 02:17:05 INFO     rasa_nlu.model  - Starting to train component CountVectorsFeaturizer
2019-05-02 02:17:05 INFO     rasa_nlu.model  - Finished training component.
2019-05-02 02:17:05 INFO     rasa_nlu.model  - Starting to train component EmbeddingIntentClassifier

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

2019-05-02 02:17:06 WARNING  tensorflow  - From /home/rasa-root/.local/lib/python3.6/site-packages/rasa_nlu/classifiers/embedding_intent_classifier.py:285: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.dense instead.
2019-05-02 02:17:06 WARNING  tensorflow  - From /home/rasa-root/.local/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
2019-05-02 02:17:06 WARNING  tensorflow  - From /home/rasa-root/.local/lib/python3.6/site-packages/rasa_nlu/classifiers/embedding_intent_classifier.py:286: dropout (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.dropout instead.
2019-05-02 02:17:06 WARNING  tensorflow  - From /home/rasa-root/.local/lib/python3.6/site-packages/tensorflow/python/keras/layers/core.py:143: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
2019-05-02 02:17:06 WARNING  tensorflow  - From /home/rasa-root/.local/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
2019-05-02 02:17:06 WARNING  tensorflow  - From /home/rasa-root/.local/lib/python3.6/site-packages/tensorflow/python/ops/math_grad.py:102: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
2019-05-02 02:17:07.016301: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-05-02 02:17:07.020197: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2294680000 Hz
2019-05-02 02:17:07.020935: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0xdb038d0 executing computations on platform Host. Devices:
2019-05-02 02:17:07.021052: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
2019-05-02 02:17:07 INFO     rasa_nlu.classifiers.embedding_intent_classifier  - Accuracy is updated every 10 epochs
Epochs: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 600/600 [00:14<00:00, 42.71it/s, loss=0.026, acc=1.000]
2019-05-02 02:17:21 INFO     rasa_nlu.classifiers.embedding_intent_classifier  - Finished training embedding classifier, loss=0.026, train accuracy=1.000
2019-05-02 02:17:21 INFO     rasa_nlu.model  - Finished training component.
2019-05-02 02:17:21 INFO     rasa_nlu.model  - Starting to train component DucklingHTTPExtractor
2019-05-02 02:17:21 INFO     rasa_nlu.model  - Finished training component.
2019-05-02 02:17:21 INFO     rasa_nlu.model  - Successfully saved model into '/home/rasa-root/rasa_bot/models/default/current'
2019-05-02 02:17:21 INFO     __main__  - Finished training
```

(I'm aware of the small number of examples for some entities but shouldn't matter if one of them gets it correct?)

Thanks!

**Comment by Zylatis** [comment]
Comment: Okay one different i didn't notice util now is **Machine 1** calls from dist-packages and **Machine 2** calls from site-packages

**Comment by akelad** [comment]
Thanks for raising this issue, @Ghostvv  will get back to you about it soon.

**Comment by Ghostvv** [comment]
it is entirely possible that intent classification give different result with each training.
The above mentioned shape mismatch error, suggest that you train with different set of features

**Comment by Zylatis** [comment]
I understand that, but surely they should not be so wildly different. Which sets of features? As indicated all of the config/data files are identical.

**Comment by Ghostvv** [comment]
it looks like `CountVectorsFeaturizer` uses different vocabulary on these machines. on the 1st it uses `666` words, while on the second `710`.

as a first step, I would check whether feature vectors passed to the classifier are the same on both machines

**Comment by Zylatis** [comment]
Okay, how do i check that? I see no reason why they should be different, and one should be very wrong, with identical training/config inputs. Are there specific package versions i should check?

Thanks
Z

**Comment by Ghostvv** [comment]
`does this mean I cannot import models from one system to another even if the setup is the same` - this should be possible.

First guess I have is different spacy models.
