### ISSUE TITLE
is_intent_classifier_present checks pipeline, not trained model

### ISSUE THREAD

**Issue by msamogh** [RasaHQ/rasa#3365]
**Rasa version**: Rasa NLU 0.14.6 (While I didn't do a code-dive into the latest version, I was able to replicate the same behavior in the latest version as well)

**Python version**: 3.7.3

**Operating system** (windows, osx, ...): Ubuntu 16.04

**Issue**:
My NLU training data has a single intent, and during training I get this warning:
`rasa_nlu.classifiers.sklearn_intent_classifier  - Can not train an intent classifier. Need at least 2 different classes. Skipping training of intent classifier.`, which is fine.

However, when I try to evaluate the model using:
`python -m rasa_nlu.evaluate --data data/nlu_data_test.md --model models/current/nlu/ --config nlu_config.yml`, it throws this error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/msamogh/rasa-1/lib/python3.7/site-packages/rasa_nlu-0.14.6-py3.7.egg/rasa_nlu/evaluate.py", line 978, in <module>
  File "/home/msamogh/rasa-1/lib/python3.7/site-packages/rasa_nlu-0.14.6-py3.7.egg/rasa_nlu/evaluate.py", line 972, in main
  File "/home/msamogh/rasa-1/lib/python3.7/site-packages/rasa_nlu-0.14.6-py3.7.egg/rasa_nlu/evaluate.py", line 749, in run_evaluation
  File "/home/msamogh/rasa-1/lib/python3.7/site-packages/rasa_nlu-0.14.6-py3.7.egg/rasa_nlu/evaluate.py", line 624, in get_intent_predictions
  File "/home/msamogh/rasa-1/lib/python3.7/site-packages/rasa_nlu-0.14.6-py3.7.egg/rasa_nlu/evaluate.py", line 596, in extract_intent
AttributeError: 'NoneType' object has no attribute 'get'
```

I tried checking the output of `is_intent_classifier_present`, for which it returned True, which is what I suspect is causing this issue. When I forcibly set it to False, it ran fine.

**Content of configuration file (config.yml)**:
```yml
language: "en"

pipeline: spacy_sklearn
```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml
intents:
- ask_budget

entities:
- low
- high


slots:
  low:
    type: float
  high:
    type: float
```

**Comment by msamogh** [comment]
I did a bit more looking around, and it seems like this would need a mechanism to override/modify the `provides` attribute attached to the `Component` classes from within individual `Component` instances.

**Comment by akelad** [comment]
Thanks for raising this issue, @erohmensing will get back to you about it soon.

**Comment by erohmensing** [comment]
I do agree that in this case the script should fail more gracefully. It's not incorrect that your pipeline has an intent classifer present, but rather the issue is that the model hasn't trained one. Can I ask, though, why you have an intent classifier in your pipeline (the `spacy_sklearn` pipeline contains one), but only one intent? Are you only trying to train and evaluate entity recognition with your model?

**Comment by msamogh** [comment]
Yeah, the absence of a model vs absence of a component seems to be the cause of confusion here. And yes, I was focusing on just the entity extraction part for the purposes of this bot.

**Comment by erohmensing** [comment]
Hm, in that case I think it would make more sense to remove intent classification from your pipeline

**Comment by msamogh** [comment]
I suppose that's the simplest solution here. 

This is me being pedantic, but given that most people new to Rasa start out with the `spacy_sklearn` pipeline, and a scenario like this (single intent + entity extraction evaluation) isn't too far-fetched for a beginner, perhaps it would be nice to have a more graceful failure?

**Comment by erohmensing** [comment]
That's fair, although single-intent definitely isn't' the recommended way of starting out. I agree it should be more graceful, just don't know if that's anything we'd get to very soon. Would be happy to take a PR for this.  

If you want to do so, don't go about it through changing the "provides" or "requires", as that's not where the problem lies. You'll have to check if the intent classifier is in the model itself. Can you show me what your NLU model directory looks like as well as the contents of metadata.json?

**Comment by msamogh** [comment]
Sorry for the late reply.

This is the contents of my model directory.
![nlu-models-dir](https://user-images.githubusercontent.com/1230386/57436643-ba9eb900-725d-11e9-8a09-6db6911c7cac.png)

This is the contents of `metadata.json`:
```json
{
    "language": "en",
    "pipeline": [
        {
            "name": "tokenizer_whitespace",
            "class": "rasa_nlu.tokenizers.whitespace_tokenizer.WhitespaceTokenizer"
        },
        {
            "BILOU_flag": true,
            "features": [
                [
                    "low",
                    "title",
                    "upper"
                ],
                [
                    "bias",
                    "low",
                    "prefix5",
                    "prefix2",
                    "suffix5",
                    "suffix3",
                    "suffix2",
                    "upper",
                    "title",
                    "digit",
                    "pattern"
                ],
                [
                    "low",
                    "title",
                    "upper"
                ]
            ],
            "max_iterations": 50,
            "L1_c": 0.1,
            "L2_c": 0.1,
            "name": "ner_crf",
            "classifier_file": "crf_model.pkl",
            "class": "rasa_nlu.extractors.crf_entity_extractor.CRFEntityExtractor"
        },
        {
            "name": "ner_synonyms",
            "synonyms_file": "entity_synonyms.json",
            "class": "rasa_nlu.extractors.entity_synonyms.EntitySynonymMapper"
        },
        {
            "batch_size": 64,
            "epochs": 10,
            "learning_rate": 2e-06,
            "max_seq_length": 128,
            "warmup_proportion": 0.1,
            "save_checkpoints_steps": 1000,
            "save_summary_steps": 500,
            "iterations_per_loop": 1000,
            "bert_model": "uncased_L-12_H-768_A-12",
            "bert_tfhub_module_handle": "https://tfhub.dev/google/bert_uncased_L-12_H-768_A-12/1",
            "checkpoint_dir": "./tmp/bert",
            "checkpoint_remove_before_training": true,
            "name": "intent_classifier_bert",
            "model_path": "/home/msamogh/rasa-1/rasa-currency/models/current/nlu/1556880871",
            "class": "innatis.classifiers.bert_intent_classifier.BertIntentClassifier"
        }
    ],
    "training_data": "training_data.json",
    "trained_at": "20190503-162435",
    "rasa_nlu_version": "0.14.3"
}
```

**Comment by erohmensing** [comment]
This doesn't look like the same pipeline you said you were using -- this has a custom component and for some reason two Sklearn intent classifiers? I'm confused -- I thought you weren't trying to do intent classification

**Comment by msamogh** [comment]
Okay, my bad, it looks like I made some updates since the time I posted the issue and this comment.

>  I'm confused -- I thought you weren't trying to do intent classification 

Yes, the issue arises when an intent classifier IS part of the pipeline, but gets ignored because the training file has only data for a single intent.

**Comment by erohmensing** [comment]
Right, was just wondering why you had a custom component for an intent classifier then. What pipeline is this metadata for?

**Comment by msamogh** [comment]
This is the correct metadata.json for the `spacy_sklearn` pipeline. I'm deleting the older metadata.json I'd sent.

```json
{
    "language": "en",
    "pipeline": [
        {
            "model": "en",
            "case_sensitive": false,
            "name": "SpacyNLP",
            "class": "rasa_nlu.utils.spacy_utils.SpacyNLP"
        },
        {
            "name": "SpacyTokenizer",
            "class": "rasa_nlu.tokenizers.spacy_tokenizer.SpacyTokenizer"
        },
        {
            "name": "SpacyFeaturizer",
            "class": "rasa_nlu.featurizers.spacy_featurizer.SpacyFeaturizer"
        },
        {
            "name": "RegexFeaturizer",
            "file": "component_3_RegexFeaturizer.pkl",
            "class": "rasa_nlu.featurizers.regex_featurizer.RegexFeaturizer"
        },
        {
            "BILOU_flag": true,
            "features": [
                [
                    "low",
                    "title",
                    "upper"
                ],
                [
                    "bias",
                    "low",
                    "prefix5",
                    "prefix2",
                    "suffix5",
                    "suffix3",
                    "suffix2",
                    "upper",
                    "title",
                    "digit",
                    "pattern"
                ],
                [
                    "low",
                    "title",
                    "upper"
                ]
            ],
            "max_iterations": 50,
            "L1_c": 0.1,
            "L2_c": 0.1,
            "name": "CRFEntityExtractor",
            "file": "component_4_CRFEntityExtractor.pkl",
            "class": "rasa_nlu.extractors.crf_entity_extractor.CRFEntityExtractor"
        },
        {
            "name": "EntitySynonymMapper",
            "file": "component_5_EntitySynonymMapper.json",
            "class": "rasa_nlu.extractors.entity_synonyms.EntitySynonymMapper"
        },
        {
            "C": [
                1,
                2,
                5,
                10,
                20,
                100
            ],
            "gamma": [
                0.1
            ],
            "kernels": [
                "linear"
            ],
            "max_cross_validation_folds": 5,
            "scoring_function": "f1_weighted",
            "name": "SklearnIntentClassifier",
            "file": "component_6_SklearnIntentClassifier.pkl",
            "class": "rasa_nlu.classifiers.sklearn_intent_classifier.SklearnIntentClassifier"
        }
    ],
    "training_data": "training_data.json",
    "trained_at": "20190509-181919",
    "rasa_nlu_version": "0.15.0"
}
```

And this is the contents of the model directory
```tsv
1556880871                          component_5_EntitySynonymMapper.json     crf_model.pkl                          intent_classifier_sklearn.pkl  training_data.json
component_3_RegexFeaturizer.pkl     component_5_SklearnIntentClassifier.pkl  entity_synonyms.json                   metadata.json
component_4_CRFEntityExtractor.pkl  component_6_SklearnIntentClassifier.pkl  intent_classifier_bert_label_list.pkl  regex_featurizer.json
```
