### ISSUE TITLE
from rasa_core.agent import Agent gives error

### ISSUE THREAD

**Issue by MoAbd** [RasaHQ/rasa#3378]
**Rasa version**:
0.13.8
**Python version**: 
3.7.0
**Operating system** (windows, osx, ...):
windows 10
**Issue**:
importing rasa_core gives an error, note that it was working two days ago. 
full error is 
```bash
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 1229, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 1275, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 1224, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 1016, in _send_output
    self.send(msg)
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 956, in send
    self.connect()
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 1384, in connect
    super().connect()
  File "C:\ProgramData\Anaconda3\lib\http\client.py", line 928, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 727, in create_connection
    raise err
  File "C:\ProgramData\Anaconda3\lib\socket.py", line 716, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dialogue_management_model.py", line 9, in <module>
    from rasa_core.agent import Agent
  File "C:\Users\m.elkasaby\AppData\Roaming\Python\Python37\site-packages\rasa_core\agent.py", line 17, in <module>
    from rasa_core.channels import UserMessage, OutputChannel, InputChannel
  File "C:\Users\m.elkasaby\AppData\Roaming\Python\Python37\site-packages\rasa_core\channels\__init__.py", line 23, in <module>
    from rasa_core.channels.telegram import TelegramInput  # nopep8
  File "C:\Users\m.elkasaby\AppData\Roaming\Python\Python37\site-packages\rasa_core\channels\telegram.py", line 4, in <module>
    from telegram import (
  File "C:\Users\m.elkasaby\AppData\Roaming\Python\Python37\site-packages\telegram\__init__.py", line 46, in <module>
    from .files.file import File
  File "C:\Users\m.elkasaby\AppData\Roaming\Python\Python37\site-packages\telegram\files\file.py", line 23, in <module>
    from future.backports.urllib import parse as urllib_parse
  File "C:\ProgramData\Anaconda3\lib\site-packages\future\backports\__init__.py", line 14, in <module>
    import_top_level_modules()
  File "C:\ProgramData\Anaconda3\lib\site-packages\future\standard_library\__init__.py", line 810, in import_top_level_modules
    with exclude_local_folder_imports(*TOP_LEVEL_MODULES):
  File "C:\ProgramData\Anaconda3\lib\site-packages\future\standard_library\__init__.py", line 781, in __enter__
    module = __import__(m, level=0)
  File "C:\Users\m.elkasaby\Desktop\chatbot\test.py", line 5, in <module>
    page=urllib.request.urlopen(quote_page).read()
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\ProgramData\Anaconda3\lib\urllib\request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
```

**Comment by akelad** [comment]
Thanks for raising this issue, @MetcalfeTom  will get back to you about it soon.

**Comment by MetcalfeTom** [comment]
Seems more like a proxy error than anything Rasa-specific.  Have you changed any proxy settings over the past couple of days?  Either directly through Windows Control Panel or indirectly through a browser?  Could you try [these](https://stackoverflow.com/questions/15820739/python-urlerror-urlopen-error-errno-10060) suggestions?

**Comment by MoAbd** [comment]
Thanks , for your reply .
The issue is resolved now
