### ISSUE TITLE
Core training Error: Device or resource busy

### ISSUE THREAD

**Issue by ties-s** [RasaHQ/rasa#3422]
**Rasa version**:
Docker rasa_core:latest

**Python version**: 
Docker rasa_core:latest

**Operating system** (windows, osx, ...):
Docker on macOS

**Issue**:
Training the core fails with the following error if there is already a model present:
```
2019-05-09 22:43:00 INFO     rasa.core.agent  - Model directory models exists and contains old model files. All files will be overwritten.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/rasa/core/train.py", line 246, in <module>
    main()
  File "/app/rasa/core/train.py", line 232, in main
    additional_args))
  File "uvloop/loop.pyx", line 1451, in uvloop.loop.Loop.run_until_complete
  File "/app/rasa/core/train.py", line 168, in do_default_training
    kwargs=additional_arguments)
  File "/app/rasa/core/train.py", line 91, in train
    agent.persist(output_path, dump_stories)
  File "/app/rasa/core/agent.py", line 652, in persist
    self._clear_model_directory(model_path)
  File "/app/rasa/core/agent.py", line 638, in _clear_model_directory
    shutil.rmtree(model_path)
  File "/usr/local/lib/python3.6/shutil.py", line 490, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/local/lib/python3.6/shutil.py", line 488, in rmtree
    os.rmdir(path)
OSError: [Errno 16] Device or resource busy: 'models'
```
Afterwards the directory is empty and running the same command again gives correct output.

**Content of configuration file (config.yml)**:
default used

**Content of domain file (domain.yml)** (if used & relevant):
example from the docs used

**Comment by akelad** [comment]
it's probably to do with how/where your models directory is mounted. In any case, I'd suggest you use a stable docker image, rather than the latest.

**Comment by ties-s** [comment]
I’ve tried with stable versions (0.13.x and 0.14.x). That gives the same error. 
I’ve mounted the volumes as indicated in the docs.

**Comment by ties-s** [comment]
I've tried on macOS and a freshly installed Ubuntu VM. The error pattern is always the same: No error when the folder is empty, Error when there are files in the folder already.
