### ISSUE TITLE
make cmdline

### ISSUE THREAD

**Issue by soundaraj** [RasaHQ/rasa#3461]
**Rasa version**: rasa nlu = 0.15.0
                             rasa core = 0.13.0a3

**Python version**: 3.6

**Operating system** (windows, osx, ...): ubuntu 18

**Issue**:
`make cmdline
python3 -m rasa_core.run -d models/current/dialogue -u models/current/nlu --endpoints endpoints.yml
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/aarbor03/Downloads/rasa_core-master/rasa_core/run.py", line 11, in <module>
    from rasa_core import utils, server
  File "/home/aarbor03/Downloads/rasa_core-master/rasa_core/server.py", line 15, in <module>
    from rasa_core.evaluate import run_story_evaluation
  File "/home/aarbor03/Downloads/rasa_core-master/rasa_core/evaluate.py", line 27, in <module>
    from rasa_nlu.evaluate import plot_confusion_matrix, get_evaluation_metrics
ImportError: cannot import name 'plot_confusion_matrix'
Makefile:42: recipe for target 'cmdline' failed
make: *** [cmdline] Error 1
`

**Comment by akelad** [comment]
I assume you're probably running an old core version with a new example. Can you try upgrading to Core 0.14.2?

**Comment by soundaraj** [comment]
no, in another system same versions worked, i downgrade the nlu version it worked, but i got new error,
`raceback (most recent call last):
  File "/home/aarbor03/.local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/aarbor03/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/aarbor03/.local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/aarbor03/zynobot/login/views.py", line 147, in train
    trainer = Trainer(config.load('config.yml'))
  File "/home/aarbor03/.local/lib/python3.6/site-packages/rasa_nlu/model.py", line 152, in __init__
    components.validate_requirements(cfg.component_names)
AttributeError: 'list' object has no attribute 'component_names'`

config.yml file:
`pipeline:
  - name: "nlp_spacy"
  - name: "tokenizer_whitespace"
  - name: "intent_entity_featurizer_regex"
  - name: "ner_crf"
  - name: "ner_synonyms"
  - name: "intent_featurizer_count_vectors"
  - name: "intent_classifier_tensorflow_embedding"
    intent_tokenization_flag: true
    intent_split_symbol: "+"
 `

**Comment by akelad** [comment]
what NLU version did you downgrade to? You need to make sure your nlu and core versions are compatible
