### ISSUE TITLE
Issue with training rasa core

### ISSUE THREAD

**Issue by itsanshul** [RasaHQ/rasa#3484]
**Command** - python -m rasa_core.train -d domain.yml -s stories.md -o models/dialogue

C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\runpy.py:125: RuntimeWarning: 'rasa_core.train' found in sys.modules after import of package 'rasa_core', but prior to execution of 'rasa_core.train'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
2019-05-16 13:42:00 INFO     apscheduler.scheduler  - Scheduler started

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

Processed Story Blocks: 100%|████████████████████████████████████████████| 6/6 [00:00<00:00, 1163.15it/s, # trackers=1]
Processed Story Blocks: 100%|█████████████████████████████████████████████| 6/6 [00:00<00:00, 367.96it/s, # trackers=6]
Processed Story Blocks: 100%|█████████████████████████████████████████████| 6/6 [00:00<00:00, 90.76it/s, # trackers=36]
Processed Story Blocks: 100%|█████████████████████████████████████████████| 6/6 [00:00<00:00, 65.39it/s, # trackers=42]
Traceback (most recent call last):
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\train.py", line 253, in <module>
    additional_args)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\train.py", line 164, in do_default_training
    kwargs=additional_arguments)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\train.py", line 89, in train
    agent.train(training_data, **kwargs)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\agent.py", line 539, in train
    **kwargs)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\policies\ensemble.py", line 82, in train
    policy.train(training_trackers, domain, **kwargs)
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\policies\keras_policy.py", line 171, in train
    shuffled_y.shape[1:])
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\rasa_core\policies\keras_policy.py", line 101, in model_architecture
    from tensorflow.keras.models import Sequential
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\keras\__init__.py", line 20, in <module>
    from tensorflow.keras import layers
  File "C:\Users\inhumane\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\keras\layers\__init__.py", line 8, in <module>
    from tensorflow.python.estimator.keras import Layer
ImportError: cannot import name 'Layer'

C:\Users\inhumane\cc>pip install -U future
Requirement already up-to-date: future in c:\users\inhumane\appdata\local\programs\python\python36\lib\site-packages (0.17.1)

**Comment by akelad** [comment]
please make sure you've installed the correct tensorflow version, listed in our requirements.txt (and compatible with your current version of rasa)

**Comment by itsanshul** [comment]
> please make sure you've installed the correct tensorflow version, listed in our requirements.txt (and compatible with your current version of rasa)

can you provide me with the latest requirements.txt. I am not able to find and also python or pip versions compatible

**Comment by akelad** [comment]
the `requirements.txt` lives in the github repo: https://github.com/RasaHQ/rasa/tree/0.15.x/alt_requirements
