### ISSUE TITLE
rasa init error - ModuleNotFoundError: No module named 'tensorflow.keras'

### ISSUE THREAD

**Issue by giorgobiani** [RasaHQ/rasa#3550]
Today I tried to install new Rasa to test it and got into an issue:

**Rasa version**: 1.0.1

**Python version**: 3.6.7

**Operating system** : Ubuntu 18.04.2 LTS (Running on Windows 10 Linux Subsystem)

**Issue**: 

After installing rasa and running "rasa init" I was getting: `F tensorflow/core/platform/cpu_feature_guard.cc:37] The TensorFlow library was compiled to use AVX instructions, but these aren't available on your machine.
Aborted (core dumped)`

I installed Tensorflow 1.5 and now when running "rasa init" I'm getting: 

`
Finished creating project structure.
Training an initial model...
Training Core model...
2019-05-22 13:22:45 INFO     root  - Generating grammar tables from /usr/lib/python3.6/lib2to3/Grammar.txt
2019-05-22 13:22:45 INFO     root  - Generating grammar tables from /usr/lib/python3.6/lib2to3/PatternGrammar.txt
Processed Story Blocks: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 1254.18it/s, # trackers=1]
Processed Story Blocks: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 722.78it/s, # trackers=4]
Processed Story Blocks: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 333.33it/s, # trackers=12]
Processed Story Blocks: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 432.04it/s, # trackers=7]
Processed trackers: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 473.89it/s, # actions=14]
Processed actions: 14it [00:00, 2246.46it/s, # examples=14]
Processed trackers: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 94/94 [00:00<00:00, 100.97it/s, # actions=62]
2019-05-22 13:22:48.579726: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2
Traceback (most recent call last):
  File "/usr/local/bin/rasa", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/rasa/__main__.py", line 70, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/usr/local/lib/python3.6/dist-packages/rasa/cli/scaffold.py", line 194, in run
    init_project(args, path)
  File "/usr/local/lib/python3.6/dist-packages/rasa/cli/scaffold.py", line 112, in init_project
    print_train_or_instructions(args, path)
  File "/usr/local/lib/python3.6/dist-packages/rasa/cli/scaffold.py", line 50, in print_train_or_instructions
    args.model = rasa.train(domain, config, training_files, output)
  File "/usr/local/lib/python3.6/dist-packages/rasa/train.py", line 48, in train
    kwargs=kwargs,
  File "uvloop/loop.pyx", line 1451, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.6/dist-packages/rasa/train.py", line 144, in train_async
    kwargs=kwargs,
  File "/usr/local/lib/python3.6/dist-packages/rasa/train.py", line 183, in _do_training
    kwargs=kwargs,
  File "/usr/local/lib/python3.6/dist-packages/rasa/train.py", line 312, in _train_core_with_validated_data
    kwargs=kwargs,
  File "/usr/local/lib/python3.6/dist-packages/rasa/core/train.py", line 59, in train
    agent.train(training_data, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/rasa/core/agent.py", line 668, in train
    self.policy_ensemble.train(training_trackers, self.domain, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/rasa/core/policies/ensemble.py", line 89, in train
    policy.train(training_trackers, domain, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/rasa/core/policies/keras_policy.py", line 185, in train
    shuffled_X.shape[1:], shuffled_y.shape[1:]
  File "/usr/local/lib/python3.6/dist-packages/rasa/core/policies/keras_policy.py", line 109, in model_architecture
    from tensorflow.keras.models import Sequential
ModuleNotFoundError: No module named 'tensorflow.keras'
`

I believe it's a version mismatch, so what is the correct version of Tensorflow that should be installed?

**Comment by akelad** [comment]
yeah this is the correct version: tensorflow~=1.13.0
It should get installed when you `pip install rasa`

**Comment by giorgobiani** [comment]
The problem is, after default install "rasa init" returns this: `F tensorflow/core/platform/cpu_feature_guard.cc:37] The TensorFlow library was compiled to use AVX instructions, but these aren't available on your machine. Aborted (core dumped)` (that's why I upgraded to 1.5)

So looks both versions have problem or do I miss something?

P.S. rasa_nlu also was showing this warning, but it didn't stop the process and here "rasa init" stops immediately

**Comment by akelad** [comment]
1.5 is a downgrade :D could you take a look at the docs for tensorflow about that error?

**Comment by giorgobiani** [comment]
Haha sometimes "upgrading" just downgrades the version :D :D my bad. I'll check it, thanks.
