### ISSUE TITLE
custom components cannot be found

### ISSUE THREAD

**Issue by HatuneMiku** [RasaHQ/rasa#3552]
**Rasa version**:
`rasa                    1.0.1`
**Python version**: 
`Python 3.6.8`
**Operating system** (windows, osx, ...):
Windows 10
**Issue**:
custom components cannot be found.

**Content of configuration file (config.yml)**:
```yml
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: "zh"
pipeline:
  # - name: "whitespace_tokenizer.WhitespaceTokenizer"
  - name: "components.ChatTokenizer"
  - name: "CRFEntityExtractor"
  - name: "EntitySynonymMapper"
  - name: "CountVectorsFeaturizer"
  - name: "EmbeddingIntentClassifier"
```
I build a custom component, that is the files in my folder:

```
__init__.py   components.py    domain.yml     readme.md
__pycache__/  config.yml       endpoints.yml  test.py
actions.py    credentials.yml  logs/          tokens.py
api.py        data/            models/        whitespace_tokenizer.py
```
my component is components.ChatTokenizer, but I get this error:

```
(rasa) D:\OneDrive\05Work\rasabot>rasa train nlu --config config.yml --out models/ --nlu data/nlu.md --fixed-model-name nlu --debug
2019-05-22 18:40:22 DEBUG    rasa.skill  - Selected skills: [].
Training NLU model...
Traceback (most recent call last):
  File "d:\programs\miniconda3\envs\rasa\lib\site-packages\rasa\nlu\registry.py", line 141, in get_component_class
    return utils.class_from_module_path(component_name)
  File "d:\programs\miniconda3\envs\rasa\lib\site-packages\rasa\nlu\utils\__init__.py", line 140, in class_from_module_path
    m = importlib.import_module(module_name)
  File "d:\programs\miniconda3\envs\rasa\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'components'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\programs\miniconda3\envs\rasa\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\programs\miniconda3\envs\rasa\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Programs\Miniconda3\envs\rasa\Scripts\rasa.exe\__main__.py", line 9, in <module>
  File "d:\programs\miniconda3\envs\rasa\lib\site-packages\rasa\__main__.py", line 70, in main
    cmdline_arguments.func(cmdline_arguments)
  File "d:\programs\miniconda3\envs\rasa\lib\site-packages\rasa\cli\train.py", line 132, in train_nlu
    fixed_model_name=args.fixed_model_name,
  File "d:\programs\miniconda3\envs\rasa\lib\site-packages\rasa\train.py", line 373, in train_nlu
    fixed_model_name=fixed_model_name,
  File "d:\programs\miniconda3\envs\rasa\lib\site-packages\rasa\train.py", line 392, in _train_nlu_with_validated_data
    config, nlu_data_directory, _train_path, fixed_model_name="nlu"
  File "d:\programs\miniconda3\envs\rasa\lib\site-packages\rasa\nlu\train.py", line 83, in train
    trainer = Trainer(nlu_config, component_builder)
  File "d:\programs\miniconda3\envs\rasa\lib\site-packages\rasa\nlu\model.py", line 148, in __init__
    components.validate_requirements(cfg.component_names)
  File "d:\programs\miniconda3\envs\rasa\lib\site-packages\rasa\nlu\components.py", line 36, in validate_requirements
    component_class = registry.get_component_class(component_name)
  File "d:\programs\miniconda3\envs\rasa\lib\site-packages\rasa\nlu\registry.py", line 150, in get_component_class
    "in a module.".format(component_name)
Exception: Failed to find component class for 'components.ChatTokenizer'. Unknown component name. Check your configured pipeline and make sure the mentioned component is not misspelled. If you are creating your own component, make sure it is either listed as part of the `component_classes` in `rasa.nlu.registry.py` or is a proper name of a class in a module.
```
but I try to copy whitespace_tokenizer.py as my custom component, and use :  
```
- name: "whitespace_tokenizer.WhitespaceTokenizer"
```
I get the same error:

```
(rasa) D:\OneDrive\05Work\rasabot>rasa train nlu --config config.yml --out models/ --nlu data/nlu.md --fixed-model-name nlu --debug
2019-05-22 18:43:53 DEBUG    rasa.skill  - Selected skills: [].
Training NLU model...
Traceback (most recent call last):
  File "d:\programs\miniconda3\envs\rasa\lib\site-packages\rasa\nlu\registry.py", line 141, in get_component_class
    return utils.class_from_module_path(component_name)
  File "d:\programs\miniconda3\envs\rasa\lib\site-packages\rasa\nlu\utils\__init__.py", line 140, in class_from_module_path
    m = importlib.import_module(module_name)
  File "d:\programs\miniconda3\envs\rasa\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'whitespace_tokenizer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\programs\miniconda3\envs\rasa\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\programs\miniconda3\envs\rasa\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Programs\Miniconda3\envs\rasa\Scripts\rasa.exe\__main__.py", line 9, in <module>
  File "d:\programs\miniconda3\envs\rasa\lib\site-packages\rasa\__main__.py", line 70, in main
    cmdline_arguments.func(cmdline_arguments)
  File "d:\programs\miniconda3\envs\rasa\lib\site-packages\rasa\cli\train.py", line 132, in train_nlu
    fixed_model_name=args.fixed_model_name,
  File "d:\programs\miniconda3\envs\rasa\lib\site-packages\rasa\train.py", line 373, in train_nlu
    fixed_model_name=fixed_model_name,
  File "d:\programs\miniconda3\envs\rasa\lib\site-packages\rasa\train.py", line 392, in _train_nlu_with_validated_data
    config, nlu_data_directory, _train_path, fixed_model_name="nlu"
  File "d:\programs\miniconda3\envs\rasa\lib\site-packages\rasa\nlu\train.py", line 83, in train
    trainer = Trainer(nlu_config, component_builder)
  File "d:\programs\miniconda3\envs\rasa\lib\site-packages\rasa\nlu\model.py", line 148, in __init__
    components.validate_requirements(cfg.component_names)
  File "d:\programs\miniconda3\envs\rasa\lib\site-packages\rasa\nlu\components.py", line 36, in validate_requirements
    component_class = registry.get_component_class(component_name)
  File "d:\programs\miniconda3\envs\rasa\lib\site-packages\rasa\nlu\registry.py", line 150, in get_component_class
    "in a module.".format(component_name)
Exception: Failed to find component class for 'whitespace_tokenizer.WhitespaceTokenizer'. Unknown component name. Check your configured pipeline and make sure the mentioned component is not misspelled. If you are creating your own component, make sure it is either listed as part of the `component_classes` in `rasa.nlu.registry.py` or is a proper name of a class in a module.
```

**Comment by BrunoRoth95** [comment]
i have the same problem. Any solutions yet?

**Comment by wochinge** [comment]
Can you make sure your python module is in the `PYTHONPATH`?
E.g. by doing `export PYTHONPATH=<path to the directory of the custom component>`

**Comment by BrunoRoth95** [comment]
It works when I erase the multiple intents in the pipeline

language: pt
pipeline:
- name: custom_components.tokenizer.DukaTokenizer
- name: CRFEntityExtractor
- name: CountVectorsFeaturizer
- name: EmbeddingIntentClassifier
- name: custom_components.synonym.DukaEntitySynonymMapper
# - intent_split_symbol: +
#   intent_tokenization_flag: true
- dimensions:
  - time
  - number
  - amount-of-money
  - distance
  - email
  locale: pt_BR
  name: DucklingHTTPExtractor
  timezone: "America/Bras\xEDlia"
  url: http://localhost:8000
policies:
  - name: KerasPolicy
    epochs: 150
    max_history: 5
  - name: FallbackPolicy
    nlu_threshold: 0.8
    core_threshold: 0.7
  - name: MemoizationPolicy
    max_history: 5
  - name: FormPolicy

**Comment by HatuneMiku** [comment]
> Can you make sure your python module is in the `PYTHONPATH`?
> E.g. by doing `export PYTHONPATH=<path to the directory of the custom component>`

My custom component is in the root directory of this project, and there is a `__init__.py`, so it should be found at this path without set the `PYTHONPATH`, and the custom component works at Rasa NLU 0.14.x and Rasa Core 0.13.x. but not rasa 1.0.1

**Comment by akelad** [comment]
hmm strange, @wochinge will look into it

**Comment by wochinge** [comment]
@HatuneMiku 

> My custom component is in the root directory of this project, and there is a __init__.py, so it should be found at this path without set the PYTHONPATH

Your project directory is not a registered python module (the `__init__.py` does not automatically add this directory to the pythonpath).

What is the exact error which your are getting when the module `custom_components.synonym.DukaEntitySynonymMapper` is loaded?

**Comment by HatuneMiku** [comment]
@wochinge Thanks. But I still don't understand.

This is my project files, the path is `/d/OneDrive/Work/rasabot/`:
```
__init__.py   components.py    domain.backup.yml  logs/            tokens.py
__pycache__/  config.yml       domain.yml         models/          words/
actions.py    credentials.yml  endpoints.yml      readme.md
api.py        data/            graph.html         story_graph.dot
```
in the custom components `components.py` I bulid a class :

```python
class ChatTokenizer(Tokenizer, Component):
    provides = ["tokens"]
    language_list = ["zh"]
    def __init__(self, component_config=None):
        super(ChatTokenizer, self).__init__(component_config)
    ...
```
and this is my config:
```yml
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: "zh"
pipeline:
  # - name: "JiebaTokenizer"
  - name: "components.ChatTokenizer"
  - name: "CRFEntityExtractor"
  - name: "EntitySynonymMapper"
  - name: "CountVectorsFeaturizer"
  - name: "EmbeddingIntentClassifier"
```
And I run this code at path `/d/OneDrive/Work/rasabot/`:
```
rasa train
```
core training fine:
```
2019-05-25 18:18:48 INFO     rasa.core.policies.keras_policy  - Done fitting keras policy model
Processed trackers: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 40/40 [00:00<00:00, 412.28it/s, # actions=172] 
Processed actions: 172it [00:00, 1865.99it/s, # examples=172]
Processed trackers: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 40/40 [00:00<00:00, 250.99it/s, # actions=134] 
2019-05-25 18:18:52 INFO     rasa.core.agent  - Persisted model to 'C:\Users\Miku\AppData\Local\Temp\tmpor8jxuaf\core'
Core model training completed.
```
but the nlu training failed:
```
Training NLU model...
Traceback (most recent call last):
  File "d:\programs\miniconda3\envs\rasa\lib\site-packages\rasa\nlu\registry.py", line 141, in get_component_class
    return utils.class_from_module_path(component_name)
  File "d:\programs\miniconda3\envs\rasa\lib\site-packages\rasa\nlu\utils\__init__.py", line 140, in class_from_module_path
    m = importlib.import_module(module_name)
  File "d:\programs\miniconda3\envs\rasa\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'components'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\programs\miniconda3\envs\rasa\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\programs\miniconda3\envs\rasa\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Programs\Miniconda3\envs\rasa\Scripts\rasa.exe\__main__.py", line 9, in <module>
  File "d:\programs\miniconda3\envs\rasa\lib\site-packages\rasa\__main__.py", line 70, in main
    cmdline_arguments.func(cmdline_arguments)
  File "d:\programs\miniconda3\envs\rasa\lib\site-packages\rasa\cli\train.py", line 69, in train
    kwargs=extract_additional_arguments(args),
  File "d:\programs\miniconda3\envs\rasa\lib\site-packages\rasa\train.py", line 48, in train
    kwargs=kwargs,
  File "d:\programs\miniconda3\envs\rasa\lib\asyncio\base_events.py", line 484, in run_until_complete
    return future.result()
  File "d:\programs\miniconda3\envs\rasa\lib\site-packages\rasa\train.py", line 144, in train_async
    kwargs=kwargs,
  File "d:\programs\miniconda3\envs\rasa\lib\site-packages\rasa\train.py", line 197, in _do_training
  File "d:\programs\miniconda3\envs\rasa\lib\site-packages\rasa\train.py", line 392, in _train_nlu_with_validated_data
  File "d:\programs\miniconda3\envs\rasa\lib\site-packages\rasa\nlu\train.py", line 83, in train
    trainer = Trainer(nlu_config, component_builder)
  File "d:\programs\miniconda3\envs\rasa\lib\site-packages\rasa\nlu\model.py", line 148, in __init__
t misspelled. If you are creating your own component, make sure it is either listed as part of the `component_classes` in `rasa.nlu.registry.py` or is a proper name of a class in a module.
```

I just want to know how to make the custom components work like at Rasa NLU 0.14.x and Rasa Core 0.13.x. What am I missing at rasa 1.0.1?

**Comment by HatuneMiku** [comment]
I mean, I run the rasa command at path `/d/OneDrive/Work/rasabot/`.  `components.py` in this path, local path model should can be importted as path `"."` for `PYTHONPATH`.

**Comment by wochinge** [comment]
@HatuneMiku 
Mhm, maybe it's not found anymore because you are not longer starting it with `python -m`. This probably added the directory implicitly to the search path. Since we know have the new CLI, I think you have to add the directory actively to the python search path.

So could you please add the path to your `PYTHONPATH`? You can also move create an extra directory and move the componenent there and then add this directory to the `PYTHONPATH`.

**Comment by HatuneMiku** [comment]
@wochinge 👍 **YES, THANKS!**   You are right, that is what I was missing!

But I use conda environment for rasa, my component use some relative path, so it is not good to use an extra directory.  It is complex to add python search path for conda evns, I have try times, I can import cumtom component in rasa env by import code, but raise error by run `rasa train`, allways get the same error like `can not find component`.

Now I use `python -m rasa train`, it works fine. 

I will close this issue, but still think if we can build custom component, maybe we need more friendly way to use it. 

Thank again!

**Comment by wochinge** [comment]
@HatuneMiku Glad you could solve it! Could you do sth like that https://stackoverflow.com/questions/32715261/how-to-add-folder-to-search-path-for-a-given-anaconda-environment with conda?

Cause I highly recommend you to use our new cli. It makes your life a lot easier: http://rasa.com/docs/rasa/user-guide/command-line-interface/

**Comment by HatuneMiku** [comment]
@wochinge I used the solution for the conda environment you provided, and it works very well now, thank you very much.👍
