### ISSUE TITLE
Change in variations specification (doc or Rasa X bug)

### ISSUE THREAD

**Issue by connorbrinton** [RasaHQ/rasa#3560]
**Rasa version**: 1.0.1

**Python version**: 3.6.7

**Operating system** (windows, osx, ...): OS X

**Issue**: Before Rasa 1.0, a `domain.yml` file could contain:
```
intents:
  - greet

actions:
  - utter_hi

templates:
  utter_hi:
    - "Hi"
    - "Hello"
    - "Greetings"
```

With the introduction of Rasa 1.0, the docs no longer include any example of this kind of usage of variations. Additionally, Rasa X raises the following error when this kind of `domain.yml` file is used:
```
Starting Rasa X in local mode... 🚀
Traceback (most recent call last):
  File "/.../.venv/bin/rasa", line 12, in <module>
    sys.exit(main())
  File "/.../.venv/lib/python3.6/site-packages/rasa/__main__.py", line 70, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/.../.venv/lib/python3.6/site-packages/rasa/cli/x.py", line 243, in rasa_x
    local.main(args, project_path, args.data, token=rasa_x_token)
  File "/.../.venv/lib/python3.6/site-packages/rasax/community/local.py", line 194, in main
    session)
  File "/.../.venv/lib/python3.6/site-packages/rasax/community/local.py", line 144, in _initialize_with_local_data
    LOCAL_PROJECT_NAME,
  File "/.../.venv/lib/python3.6/site-packages/rasax/community/api/initialise.py", line 170, in inject_domain
    username=username)
  File "/.../.venv/lib/python3.6/site-packages/rasax/community/services/projects_service.py", line 48, in store_domain
    templates = _templates(domain, username, project_id)
  File "/.../.venv/lib/python3.6/site-packages/rasax/community/services/projects_service.py", line 259, in _templates
    for template, responses in templates.items() for response in responses
  File "/.../.venv/lib/python3.6/site-packages/rasax/community/services/projects_service.py", line 259, in <listcomp>
    for template, responses in templates.items() for response in responses
AttributeError: 'str' object has no attribute 'get'
```

Changing the domain file to the following allows Rasa X to successfully start:
```
intents:
  - greet

actions:
  - utter_hi

templates:
  utter_hi:
    - text: "Hi"
    - text: "Hello"
    - text: "Greetings"
```

I believe that this is either:
* An omission from the changelog and migration guide or
* A bug in Rasa X

Since 1.0 has already been released, I don't think it's terribly important to update the changelog or migration guide, but if it is a bug in Rasa X, getting it fixed would be nice :)

Alternatively, an explanatory error message from starting Rasa X with this type of configuration file would be nice.

Thanks for all the hard work on Rasa!

**Comment by erohmensing** [comment]
Yep, you're totally right, currently Rasa allows this but Rasa X doesn't, we're already on top of getting it fixed! Thanks for pointing it out and showing a fix :)

**Comment by akelad** [comment]
@erohmensing can you reference the issue where this is being worked on?

**Comment by erohmensing** [comment]
It is actually a rasa x issue, but here is the related rasa issue:
https://github.com/RasaHQ/rasa/issues/3544
