### ISSUE TITLE
Cannot change RASA X port 

### ISSUE THREAD

**Issue by weiczhu** [RasaHQ/rasa#3597]
**Rasa version**:
1.0.1
**Python version**: 
3.7
**Operating system** (windows, osx, ...):
Ubuntu
**Issue**:
Starting Rasa X in local mode... 🚀
[2019-05-27 17:09:47 +0900] [16856] [ERROR] Unable to start server
Traceback (most recent call last):
  File "uvloop/loop.pyx", line 1112, in uvloop.loop.Loop._create_server
  File "uvloop/handles/streamserver.pyx", line 58, in uvloop.loop.UVStreamServer.listen
  File "uvloop/handles/streamserver.pyx", line 95, in uvloop.loop.UVStreamServer._fatal_error
OSError: [Errno 98] Address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/sanic/server.py", line 745, in serve
    http_server = loop.run_until_complete(server_coroutine)
  File "uvloop/loop.pyx", line 1451, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1684, in create_server
  File "uvloop/loop.pyx", line 1116, in uvloop.loop.Loop._create_server
OSError: [Errno 98] error while attempting to bind on address ('0.0.0.0', 5002): address already in use

Is there any way to configure the RASA X port number?
The following 
**rasa x --port PORT** 
does not work

**Content of configuration file (config.yml)**:
```yml

```

**Content of domain file (domain.yml)** (if used & relevant):
```yaml

```

**Comment by tmbo** [comment]
The thing is that we actually need two ports, one to run rasa-x (e.g. delivering the UI) and another one to run a normal rasa server. `--port` only changes the port of the rasa server, there is no argument to change the rasa-x port.

I think we should add a new argument to specify the rasa-x port and throw an error explaining the two ports thingy if binding to the address fails.

**Comment by zenhaust** [comment]
Same error in MacOS Sierra.
Rasa X not work.

2019-05-28 16:10:11 INFO     root  - Starting Rasa Core server on http://localhost:5005
[2019-05-28 16:10:12 +0200] [32965] [ERROR] Unable to start server
Traceback (most recent call last):
  File "uvloop/loop.pyx", line 1112, in uvloop.loop.Loop._create_server
  File "uvloop/handles/streamserver.pyx", line 58, in uvloop.loop.UVStreamServer.listen
  File "uvloop/handles/streamserver.pyx", line 95, in uvloop.loop.UVStreamServer._fatal_error
OSError: [Errno 48] Address already in use

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/sanic/server.py", line 745, in serve
    http_server = loop.run_until_complete(server_coroutine)
  File "uvloop/loop.pyx", line 1451, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1684, in create_server
  File "uvloop/loop.pyx", line 1116, in uvloop.loop.Loop._create_server
OSError: [Errno 48] error while attempting to bind on address ('0.0.0.0', 5002): address already in use

**Comment by tabergma** [comment]
Feature will be included in the next minor release.

**Comment by cyrilthank** [comment]
i give 
rasa x --debug --enable-api --cors "*" --port 5007 --rasa-x-port 5008

and  get 
Starting Rasa Core server on http://localhost:5007
Error: Cannot connect to host localhost:5008 ssl:None [Connect call failed ('127.0.0.1', 5008)]
 (http://localhost:5008/api/health is not responding)

The server is running at http://localhost:5002/login?

can you please share what i am breaking while changing the port from 5002?

**Comment by cyrilthank** [comment]
Rasa version:
1.1.4
Python version:
3.7
Operating system (windows, osx, ...):
Windows

**Comment by cyrilthank** [comment]
rasa-x : 0.19.0

**Comment by tabergma** [comment]
I guess, you need to use at least rasa-x version 0.19.1. Can you use that version and try again?

**Comment by cyrilthank** [comment]
indeed you are right

but now i am getting the below output on http://localhost:5008/api/version
after i installed from https://pypi.rasa.com/simple/rasa-x/

{
    "rasa": {
        "production": "1.1.4",
        "worker": "1.1.4"
    },
    "rasa-x": "UNDEFINED - this package is not installed"
}
