### ISSUE TITLE
ImportError: cannot import name 'Activation'

### ISSUE THREAD

**Issue by leonardocustodio** [RasaHQ/rasa#3628]
**Rasa version**: 1.0.1
**Python version**: 3.6 
**Operating system**: macOS Mojave 10.14.15

**Issue**:
I installed rasa using: "pip install rasa-x --extra-index-url https://pypi.rasa.com/simple" and used "rasa init" to start a default project. But when the project starts to train and also when using "rasa train" command. I'm getting the following error:
```
Training Core model...

WARNING: The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.

Processed Story Blocks: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 2932.57it/s, # trackers=1]
Processed Story Blocks: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 1001.74it/s, # trackers=4]
Processed Story Blocks: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 327.17it/s, # trackers=12]
Processed Story Blocks: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 212.01it/s, # trackers=12]
Processed trackers: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 1694.15it/s, # actions=14]
Processed actions: 14it [00:00, 6211.15it/s, # examples=14]
Processed trackers: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 125/125 [00:00<00:00, 542.45it/s, # actions=62]
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/rasa", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa/__main__.py", line 70, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa/cli/train.py", line 69, in train
    kwargs=extract_additional_arguments(args),
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa/train.py", line 48, in train
    kwargs=kwargs,
  File "uvloop/loop.pyx", line 1451, in uvloop.loop.Loop.run_until_complete
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa/train.py", line 144, in train_async
    kwargs=kwargs,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa/train.py", line 183, in _do_training
    kwargs=kwargs,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa/train.py", line 312, in _train_core_with_validated_data
    kwargs=kwargs,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa/core/train.py", line 59, in train
    agent.train(training_data, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa/core/agent.py", line 668, in train
    self.policy_ensemble.train(training_trackers, self.domain, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa/core/policies/ensemble.py", line 89, in train
    policy.train(training_trackers, domain, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa/core/policies/keras_policy.py", line 185, in train
    shuffled_X.shape[1:], shuffled_y.shape[1:]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa/core/policies/keras_policy.py", line 109, in model_architecture
    from tensorflow.keras.models import Sequential
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/keras/__init__.py", line 20, in <module>
    from tensorflow.keras import layers
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/tensorflow/keras/layers/__init__.py", line 9, in <module>
    from tensorflow.python.keras.applications.densenet import Activation
ImportError: cannot import name 'Activation'
```

**Content of configuration file (config.yml)**:
This is the default config.yml generated by "rasa init" in the current version
```yml
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline: supervised_embeddings

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
```

**Content of domain file (domain.yml)** (if used & relevant):
Also the default domain.yml generated by "rasa init" in the current version
```yaml
intents:
  - greet
  - goodbye
  - affirm
  - deny
  - mood_great
  - mood_unhappy

actions:
- utter_greet
- utter_cheer_up
- utter_did_that_help
- utter_happy
- utter_goodbye

templates:
  utter_greet:
  - text: "Hey! How are you?"

  utter_cheer_up:
  - text: "Here is something to cheer you up:"
    image: "https://i.imgur.com/nGF1K8f.jpg"

  utter_did_that_help:
  - text: "Did that help you?"

  utter_happy:
  - text: "Great carry on!"

  utter_goodbye:
  - text: "Bye"

```

**Comment by akelad** [comment]
Can you check which version of tensorflow you have installed by running `pip show tensorflow`? I believe you have the wrong version installed -- the correct one to use is `tensorflow==1.13.1`

**Comment by leonardocustodio** [comment]
Hi @akelad ,
In the beginning I thought the same thing but I'm using the correct one, it was installed on the "pip install rasa-x" this is my "pip list | grep tensorflow" output:

```
tensorflow                  1.13.1      
tensorflow-estimator        1.13.0    
```

**Comment by leonardocustodio** [comment]
Although as I said I had the right version installed of tensorflow. I was able to fix the issue right now by running:
```
pip uninstall tensorflow
pip install tensorflow=1.13.1
```
I think what happened is that maybe some file was not replaced/updated or was left behind when pip updated tensorflow from version 1.10.0 (that I was using before) to version 1.13.1

Regards,
