### ISSUE TITLE
Rasa init as well as model not running in centos with docker

### ISSUE THREAD

**Issue by karthikbalu** [RasaHQ/rasa#3668]
Please help

**Rasa version**:
using docker-full-latest

**Operating system** (windows, osx, ...):
CentOS Linux 7 (Core) 

**Issue**:
Im trying to deploy my locally trained model to remote server using docker to run the pretrained model from local machine

1) Not able to run with just loading the tar file
```
rasa run -m 20190531-122731.tar.gz --enable-api --log-file out.log
docker run -v $(pwd)/models:/app/models rasa/rasa:latest-full run
```

2) also tried creating new project using init and fails
```
docker run -v $(pwd):/app rasa/rasa init --no-prompt
```

**Error (including full traceback)**:
```
[root@clofus-careers rasa_test]# docker run -v $(pwd):/app rasa/rasa init --no-prompt
Welcome to Rasa! 🤖

To get started quickly, an initial project will be created.
If you need some help, check out the documentation at https://rasa.com/docs/rasa.

Warning: Output is not to a terminal (fd=1).
Warning: Input is not to a terminal (fd=0).
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/distutils/file_util.py", line 41, in _copy_file_contents
    fdst = open(dst, 'wb')
PermissionError: [Errno 13] Permission denied: './__init__.py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/rasa", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/rasa/__main__.py", line 70, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/usr/local/lib/python3.6/site-packages/rasa/cli/scaffold.py", line 194, in run
    init_project(args, path)
  File "/usr/local/lib/python3.6/site-packages/rasa/cli/scaffold.py", line 110, in init_project
    _create_initial_project(path)
  File "/usr/local/lib/python3.6/site-packages/rasa/cli/scaffold.py", line 118, in _create_initial_project
    copy_tree(scaffold_path(), path)
  File "/usr/local/lib/python3.6/distutils/dir_util.py", line 163, in copy_tree
    dry_run=dry_run)
  File "/usr/local/lib/python3.6/distutils/file_util.py", line 151, in copy_file
    _copy_file_contents(src, dst)
  File "/usr/local/lib/python3.6/distutils/file_util.py", line 44, in _copy_file_contents
    "could not create '%s': %s" % (dst, e.strerror))
distutils.errors.DistutilsFileError: could not create './__init__.py': Permission denied

```

**Command or request that led to error**:
```
docker run -v $(pwd):/app rasa/rasa init --no-prompt

```

** Content of docker-compose.yml
```
version: '3.0'
services:
  rasa:
    image: rasa/rasa:latest-full
    ports:
      - 8003:8003
    volumes:
      - ./:/app
    entrypoint: rasa
    command: ["run", "--enable-api", "-p", "8003"]
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml
actions:
  - utter_hi
  - utter_bye
intents:
  - greeting
  - bye
templates:
  utter_hi:
    - text: "hi how are you"
  utter_bye:
    - text: "see you soon"
```

**Comment by akelad** [comment]
Have you tried running those commands with sudo?

**Comment by gp187** [comment]
Open. It's still a problem

**Comment by xuanhaihust** [comment]
Please open it again. This problem drives me crazy

**Comment by xuanhaihust** [comment]
I have tried with sudo but things happened the same.

**Comment by akelad** [comment]
@erohmensing any ideas?

**Comment by erohmensing** [comment]
Looks like a duplicate of https://github.com/RasaHQ/rasa/issues/4797, I'd keep the discussion there. From another person's solution, looks like there may be a problem specifically with mounting the working directory?
