### ISSUE TITLE
Error on interactive learning on rasa version 1.0.6

### ISSUE THREAD

**Issue by anoop2503** [RasaHQ/rasa#3691]
**Rasa version**: rasa==1.0.6

**Python version**: Python 3.6.7

**Operating system** (windows, osx, ...):
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic

**Issue**:
Getting error on interactive learning. Please find the interactive learning logs below to see the error details.

**Error (including full traceback)**:
```
$ rasa interactive -m models/model.tar.gz --debug

2019-06-04 06:46:57 DEBUG    rasa.model  - Extracted model to '/tmp/tmp0z2zkdqp'.
2019-06-04 06:46:57 INFO     root  - Generating grammar tables from /usr/lib/python3.6/lib2to3/Grammar.txt
2019-06-04 06:46:57 INFO     root  - Generating grammar tables from /usr/lib/python3.6/lib2to3/PatternGrammar.txt
2019-06-04 06:46:59 DEBUG    rasa.core.utils  - Available web server routes:
/conversations/<conversation_id>/messages          POST                           add_message
/conversations/<conversation_id>/tracker/events    POST                           append_event
/model/test/intents                                POST                           evaluate_intents
/model/test/stories                                POST                           evaluate_stories
/conversations/<conversation_id>/execute           POST                           execute_action
/domain                                            GET                            get_domain
/                                                  GET                            hello
/model                                             PUT                            load_model
/model/parse                                       POST                           parse
/conversations/<conversation_id>/predict           POST                           predict
/conversations/<conversation_id>/tracker/events    PUT                            replace_events
/conversations/<conversation_id>/story             GET                            retrieve_story
/conversations/<conversation_id>/tracker           GET                            retrieve_tracker
/status                                            GET                            status
/model/predict                                     POST                           tracker_predict
/model/train                                       POST                           train
/model                                             DELETE                         unload_model
/version                                           GET                            version
2019-06-04 06:46:59 INFO     root  - Enabling coroutine debugging. Loop id 84201512.
2019-06-04 06:46:59 DEBUG    rasa.model  - Extracted model to '/tmp/tmpdzjtprop'.
2019-06-04 06:46:59 DEBUG    rasa.model  - Extracted model to '/tmp/tmpqh6lne59'.
Bot loaded. Visualisation at http://localhost:5006/visualization.html.
Type a message and press enter (press 'Ctr-c' to exit).
2019-06-04 06:47:01 DEBUG    rasa.core.training.generator  - Number of augmentation rounds is 0
2019-06-04 06:47:01 DEBUG    rasa.core.training.generator  - Starting data generation round 0 ... (with 1 trackers)
Processed Story Blocks: 100%|██████████████████████████████████████████████████████| 68/68 [00:00<00:00, 2950.47it/s, # trackers=2]
2019-06-04 06:47:01 DEBUG    rasa.core.training.generator  - Finished phase (39 training samples found).
2019-06-04 06:47:01 DEBUG    rasa.core.training.generator  - Data generation rounds finished.
2019-06-04 06:47:01 DEBUG    rasa.core.training.generator  - Found 0 unused checkpoints
2019-06-04 06:47:01 DEBUG    rasa.core.training.generator  - Found 39 training trackers.
2019-06-04 06:47:01 DEBUG    rasa.core.tracker_store  - Creating a new tracker for id 'ea63af27b3cd4e9a9d24c5526c85082d'.
2019-06-04 06:47:01 DEBUG    rasa.core.tracker_store  - Recreating tracker for id 'ea63af27b3cd4e9a9d24c5526c85082d'


? Your input -> Test intent


2019-06-04 06:47:26 DEBUG    rasa.core.tracker_store  - Recreating tracker for id 'ea63af27b3cd4e9a9d24c5526c85082d'
2019-06-04 06:47:26 DEBUG    rasa.core.processor  - Received user message 'Test intent' with intent '{'name': 'greet', 'confidence': 0.5926453471183777}' and entities '[]'
2019-06-04 06:47:26 DEBUG    rasa.core.processor  - Logged UserUtterance - tracker now has 2 events
2019-06-04 06:47:26 DEBUG    rasa.core.tracker_store  - Recreating tracker for id 'ea63af27b3cd4e9a9d24c5526c85082d'


? Your NLU model classified 'Test intent' with intent 'greet' and there are no entities, is this correct?  No
? What intent is it?  <create_new_intent>
? Please type the intent name: request_info_intent
? Please mark the entities using [value](type) notation Test intent


2019-06-04 06:48:12 DEBUG    rasa.core.tracker_store  - Recreating tracker for id 'ea63af27b3cd4e9a9d24c5526c85082d'
2019-06-04 06:48:12 DEBUG    rasa.core.processor  - Logged UserUtterance - tracker now has 2 events
2019-06-04 06:48:12 DEBUG    rasa.core.tracker_store  - Recreating tracker for id 'ea63af27b3cd4e9a9d24c5526c85082d'
2019-06-04 06:48:12 DEBUG    rasa.core.policies.memoization  - Current tracker state [None, None, None, {}, {'prev_action_listen': 1.0, 'intent_request_info_intent': 1.0}]
2019-06-04 06:48:12 DEBUG    rasa.core.policies.memoization  - Launch DeLorean...
2019-06-04 06:48:12 DEBUG    rasa.core.policies.memoization  - Current tracker state [None, None, None, {}, {'prev_action_listen': 1.0, 'intent_request_info_intent': 1.0}]
2019-06-04 06:48:12 DEBUG    rasa.core.policies.memoization  - There is no memorised next action
2019-06-04 06:48:12 DEBUG    rasa.core.featurizers  - Feature 'intent_request_info_intent' (value: '1.0') could not be found in feature map. Make sure you added all intents and entities to the domain
2019-06-04 06:48:12 DEBUG    rasa.core.policies.form_policy  - There is no active form
2019-06-04 06:48:12 DEBUG    rasa.core.policies.fallback  - NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-06-04 06:48:12 DEBUG    rasa.core.policies.ensemble  - Predicted next action using policy_1_KerasPolicy
2019-06-04 06:48:12 DEBUG    rasa.core.tracker_store  - Recreating tracker for id 'ea63af27b3cd4e9a9d24c5526c85082d'
------
Chat History

 #    Bot                                      You
──────────────────────────────────────────────────────────
 1    action_listen
──────────────────────────────────────────────────────────
 2                                            Test intent
                         intent: request_info_intent 1.00


Current slots:
        confirm_ticket_creation: None, environment: None, jira_application: None, jira_desc: None, jira_summary: None, requested_slot: None

------
2019-06-04 06:48:12 DEBUG    rasa.core.tracker_store  - Recreating tracker for id 'ea63af27b3cd4e9a9d24c5526c85082d'


? The bot wants to run 'utter_answer_ok', correct?  No


2019-06-04 06:48:52 DEBUG    rasa.core.tracker_store  - Recreating tracker for id 'ea63af27b3cd4e9a9d24c5526c85082d'
------
Chat History

 #    Bot                                      You
──────────────────────────────────────────────────────────
 1    action_listen
──────────────────────────────────────────────────────────
 2                                            Test intent
                         intent: request_info_intent 1.00


Current slots:
        confirm_ticket_creation: None, environment: None, jira_application: None, jira_desc: None, jira_summary: None, requested_slot: None

------
2019-06-04 06:48:52 DEBUG    rasa.core.tracker_store  - Recreating tracker for id 'ea63af27b3cd4e9a9d24c5526c85082d'

? What is the next action of the bot?  <create new action>
? Please type the action name: utter_info_test_intent
? Please type the message for your new utter_template 'utter_info_test_intent': This is a test intent response
Thanks! The bot will now run utter_info_test_intent.


2019-06-04 06:51:14 DEBUG    rasa.core.tracker_store  - Recreating tracker for id 'ea63af27b3cd4e9a9d24c5526c85082d'
2019-06-04 06:51:14 DEBUG    rasa.core.tracker_store  - Recreating tracker for id 'ea63af27b3cd4e9a9d24c5526c85082d'
2019-06-04 06:51:14 DEBUG    rasa.server  - Traceback (most recent call last):
  File "/home/ubuntu/rasa_ai/rasa/virtual_env/lib/python3.6/site-packages/rasa/server.py", line 489, in execute_action
    conversation_id, action_to_execute, out, policy, confidence
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/home/ubuntu/rasa_ai/rasa/virtual_env/lib/python3.6/site-packages/rasa/core/agent.py", line 483, in execute_action
    sender_id, action, output_channel, self.nlg, policy, confidence
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/home/ubuntu/rasa_ai/rasa/virtual_env/lib/python3.6/site-packages/rasa/core/processor.py", line 142, in execute_action
    action = self._get_action(action_name)
  File "/home/ubuntu/rasa_ai/rasa/virtual_env/lib/python3.6/site-packages/rasa/core/processor.py", line 258, in _get_action
    return self.domain.action_for_name(action_name, self.action_endpoint)
  File "/home/ubuntu/rasa_ai/rasa/virtual_env/lib/python3.6/site-packages/rasa/core/domain.py", line 371, in action_for_name
    self._raise_action_not_found_exception(action_name)
  File "/home/ubuntu/rasa_ai/rasa/virtual_env/lib/python3.6/site-packages/rasa/core/domain.py", line 413, in _raise_action_not_fou$d_exception
    "".format(action_name, action_names)
NameError: Cannot access action 'utter_info_test_intent', as that name is not a registered action for this domain. Available actio$s are:
         - action_listen
         - action_restart
         - action_default_fallback
         - action_deactivate_form
         - action_revert_fallback_events
         - action_default_ask_affirmation
         - action_default_ask_rephrase
         - action_back
         - action_support_jira_ticket
         - utter_answer_ok
         - utter_ask_environment
         - utter_ask_feedback
         - utter_ask_ticket_creation
         - utter_configure_app_splunk
         - utter_default_fallback
         - utter_goodbye
         - utter_greet
         - utter_info_access_apps_in_ccp
         - utter_info_artifactory_for_docker
         - utter_info_create_dns_in_ccp
         - utter_info_enable_https_ccp
         - utter_info_onboard_app_ccp
         - utter_marathon_label
         - utter_noworries
         - utter_splunk_url
         - action_create_jira_ticket
         - action_marathon_url
         - action_raise_feedback_jira_ticket

? WARNING: You have created a new action: 'utter_info_test_intent', with matching template: 'This is a test intent response'. This
action will not return its message in this session, but the new utterance will be saved to your domain file when you exit and save
this session. You do not need to do anything further.   (Yes
2019-06-04 06:52:51 DEBUG    rasa.core.tracker_store  - Recreating tracker for id 'ea63af27b3cd4e9a9d24c5526c85082d'
2019-06-04 06:52:51 DEBUG    rasa.core.tracker_store  - Recreating tracker for id 'ea63af27b3cd4e9a9d24c5526c85082d'
2019-06-04 06:52:51 DEBUG    rasa.core.tracker_store  - Recreating tracker for id 'ea63af27b3cd4e9a9d24c5526c85082d'
2019-06-04 06:52:51 WARNING  rasa.core.domain  - Failed to use action 'utter_info_test_intent' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while.
2019-06-04 06:52:51 DEBUG    rasa.core.policies.memoization  - Current tracker state [None, None, {}, {'prev_action_listen': 1.0, 'intent_request_info_intent': 1.0}, {'intent_request_info_intent': 1.0}]
2019-06-04 06:52:51 DEBUG    rasa.core.policies.memoization  - Launch DeLorean...
2019-06-04 06:52:51 WARNING  rasa.core.domain  - Failed to use action 'utter_info_test_intent' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while.
2019-06-04 06:52:51 DEBUG    rasa.core.policies.memoization  - Current tracker state [None, None, None, {}, {}]
2019-06-04 06:52:51 DEBUG    rasa.core.policies.memoization  - There is no memorised next action
2019-06-04 06:52:51 WARNING  rasa.core.domain  - Failed to use action 'utter_info_test_intent' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while.
2019-06-04 06:52:51 DEBUG    rasa.core.featurizers  - Feature 'intent_request_info_intent' (value: '1.0') could not be found in feature map. Make sure you added all intents and entities to the domain
2019-06-04 06:52:51 DEBUG    rasa.core.featurizers  - Feature 'intent_request_info_intent' (value: '1.0') could not be found in feature map. Make sure you added all intents and entities to the domain
2019-06-04 06:52:51 DEBUG    rasa.core.policies.mapping_policy  - There is no mapped action for the predicted intent, 'request_info_intent'.
2019-06-04 06:52:51 DEBUG    rasa.core.policies.form_policy  - There is no active form
2019-06-04 06:52:51 DEBUG    rasa.core.policies.fallback  - NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-06-04 06:52:51 DEBUG    rasa.core.policies.ensemble  - Predicted next action using policy_1_KerasPolicy
2019-06-04 06:52:51 DEBUG    rasa.core.tracker_store  - Recreating tracker for id 'ea63af27b3cd4e9a9d24c5526c85082d'
------
Chat History

 #    Bot                                               You
───────────────────────────────────────────────────────────────────
 1    action_listen
───────────────────────────────────────────────────────────────────
 2                                                     Test intent
                                  intent: request_info_intent 1.00
───────────────────────────────────────────────────────────────────
 3    utter_info_test_intent


Current slots:
        confirm_ticket_creation: None, environment: None, jira_application: None, jira_desc: None, jira_summary: None, requested_slot: None

------
2019-06-04 06:52:51 DEBUG    rasa.core.tracker_store  - Recreating tracker for id 'ea63af27b3cd4e9a9d24c5526c85082d'


? The bot wants to run 'action_restart', correct?  Yes
2019-06-04 06:53:21 DEBUG    rasa.core.tracker_store  - Recreating tracker for id 'ea63af27b3cd4e9a9d24c5526c85082d'
2019-06-04 06:53:21 DEBUG    rasa.core.tracker_store  - Recreating tracker for id 'ea63af27b3cd4e9a9d24c5526c85082d'
2019-06-04 06:53:21 DEBUG    rasa.core.processor  - Action 'action_restart' ended with events '['Restarted()']'
2019-06-04 06:53:21 DEBUG    rasa.core.processor  - Current slot values:
        confirm_ticket_creation: None
        environment: None
        jira_application: None
        jira_desc: None
        jira_summary: None
        requested_slot: None
2019-06-04 06:53:21 DEBUG    rasa.core.tracker_store  - Recreating tracker for id 'ea63af27b3cd4e9a9d24c5526c85082d'
2019-06-04 06:53:21 DEBUG    rasa.core.tracker_store  - Recreating tracker for id 'ea63af27b3cd4e9a9d24c5526c85082d'
2019-06-04 06:53:21 DEBUG    rasa.core.tracker_store  - Recreating tracker for id 'ea63af27b3cd4e9a9d24c5526c85082d'
2019-06-04 06:53:21 DEBUG    rasa.core.tracker_store  - Recreating tracker for id 'ea63af27b3cd4e9a9d24c5526c85082d'
------
Chat History

 #    Bot            You


Current slots:
        confirm_ticket_creation: None, environment: None, jira_application: None, jira_desc: None, jira_summary: None, requested_slot: None

------
2019-06-04 06:53:21 DEBUG    rasa.core.tracker_store  - Recreating tracker for id 'ea63af27b3cd4e9a9d24c5526c85082d'


? The bot wants to run 'action_listen', correct?  Yes
2019-06-04 06:53:51 DEBUG    rasa.core.tracker_store  - Recreating tracker for id 'ea63af27b3cd4e9a9d24c5526c85082d'
2019-06-04 06:53:51 DEBUG    rasa.core.tracker_store  - Recreating tracker for id 'ea63af27b3cd4e9a9d24c5526c85082d'
2019-06-04 06:53:51 DEBUG    rasa.core.processor  - Action 'action_listen' ended with events '[]'
2019-06-04 06:53:51 DEBUG    rasa.core.tracker_store  - Recreating tracker for id 'ea63af27b3cd4e9a9d24c5526c85082d'
2019-06-04 06:53:51 DEBUG    rasa.core.tracker_store  - Recreating tracker for id 'ea63af27b3cd4e9a9d24c5526c85082d'
2019-06-04 06:53:52 DEBUG    rasa.core.tracker_store  - Recreating tracker for id 'ea63af27b3cd4e9a9d24c5526c85082d'
2019-06-04 06:53:52 ERROR    rasa.core.training.interactive  - An exception occurred while recording messages.
Traceback (most recent call last):
  File "/home/ubuntu/rasa_ai/rasa/virtual_env/lib/python3.6/site-packages/rasa/core/training/interactive.py", line 1370, in record_messages
    endpoint, sender_id, finetune, sender_ids, plot_file
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/home/ubuntu/rasa_ai/rasa/virtual_env/lib/python3.6/site-packages/rasa/core/training/interactive.py", line 902, in _predic$_till_next_listen
    last_event = events[-2]  # last event before action_listen
IndexError: list index out of range
2019-06-04 06:53:52 ERROR    asyncio  - Task exception was never retrieved
future: <Task finished coro=<_serve_application.<locals>.run_interactive_io() done, defined at /home/ubuntu/rasa_ai/rasa/virtual_e$v/lib/python3.6/site-packages/rasa/core/training/interactive.py:1412> exception=IndexError('list index out of range',) created at $home/ubuntu/rasa_ai/rasa/virtual_env/lib/python3.6/site-packages/sanic/app.py:116>
source_traceback: Object created at (most recent call last):
  File "/home/ubuntu/rasa_ai/rasa/virtual_env/bin/rasa", line 10, in <module>
    sys.exit(main())
  File "/home/ubuntu/rasa_ai/rasa/virtual_env/lib/python3.6/site-packages/rasa/__main__.py", line 70, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/home/ubuntu/rasa_ai/rasa/virtual_env/lib/python3.6/site-packages/rasa/cli/interactive.py", line 57, in interactive
    perform_interactive_learning(args, zipped_model)
  File "/home/ubuntu/rasa_ai/rasa/virtual_env/lib/python3.6/site-packages/rasa/cli/interactive.py", line 82, in perform_interactiv$_learning
    do_interactive_learning(args, stories_directory)
  File "/home/ubuntu/rasa_ai/rasa/virtual_env/lib/python3.6/site-packages/rasa/core/train.py", line 165, in do_interactive_learnin$
    additional_arguments=additional_arguments,
  File "/home/ubuntu/rasa_ai/rasa/virtual_env/lib/python3.6/site-packages/rasa/core/training/interactive.py", line 1552, in run_in$eractive_learning
    _serve_application(app, stories, finetune, skip_visualization)
  File "/home/ubuntu/rasa_ai/rasa/virtual_env/lib/python3.6/site-packages/rasa/core/training/interactive.py", line 1431, in _serve$application
    app.run(host="0.0.0.0", port=DEFAULT_SERVER_PORT)
  File "/home/ubuntu/rasa_ai/rasa/virtual_env/lib/python3.6/site-packages/sanic/app.py", line 1096, in run
    serve(**server_settings)
  File "/home/ubuntu/rasa_ai/rasa/virtual_env/lib/python3.6/site-packages/sanic/server.py", line 742, in serve
    trigger_events(before_start, loop)
  File "/home/ubuntu/rasa_ai/rasa/virtual_env/lib/python3.6/site-packages/sanic/server.py", line 602, in trigger_events
    result = event(loop)
  File "/home/ubuntu/rasa_ai/rasa/virtual_env/lib/python3.6/site-packages/sanic/app.py", line 116, in run
    loop.create_task(task(self))
Traceback (most recent call last):
  File "/home/ubuntu/rasa_ai/rasa/virtual_env/lib/python3.6/site-packages/rasa/core/training/interactive.py", line 1420, in run_interactive_io
    sender_id=uuid.uuid4().hex,
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/home/ubuntu/rasa_ai/rasa/virtual_env/lib/python3.6/site-packages/rasa/core/training/interactive.py", line 1370, in record_messages
    endpoint, sender_id, finetune, sender_ids, plot_file
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/home/ubuntu/rasa_ai/rasa/virtual_env/lib/python3.6/site-packages/rasa/core/training/interactive.py", line 902, in _predict_till_next_listen
    last_event = events[-2]  # last event before action_listen
IndexError: list index out of range

```

**Command or request that led to error**:
```
 rasa interactive -m models/slackbot_model.tar.gz --debug
```

**Content of configuration file (config.yml)** (if relevant):
```yml

language: en
pipeline: supervised_embeddings

policies:
  - name: AugmentedMemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
  - name: FormPolicy
  - name: FallbackPolicy
    nlu_threshold: 0.4
    core_threshold: 0.3
    fallback_action_name: "utter_default_fallback"
```

**Comment by anoop2503** [comment]
Kindly note that the same model version is working fine on the previous version of rasa (rasa==1.0.1)

**Comment by akelad** [comment]
Thanks for raising this issue -- @tabergma this change seems to have come from Paulas PR (#3487) could you take a look?
