### ISSUE TITLE
Messages list in CollectingOutputChannel always empty

### ISSUE THREAD

**Issue by epiicme** [RasaHQ/rasa#3695]
**Rasa version**: 1.0.6

**Rasa X version** (if used & relevant): 0.19.0

**Python version**: 3.7.3

**Operating system** : Windows 10 1709 Build 16299.1146

**Issue**: Messages list in CollectingOutputChannel always empty.
I have attempted to modify the Google Assistant connector example from this [link](https://medium.com/rasa-blog/going-beyond-hey-google-building-a-rasa-powered-google-assistant-5ff916409a25) to work with Sanic in Rasa 1.0 (the Sanic server works). However, the above-mentioned output channel never returns any reply from Rasa. Please let me know what is the issue.

**Error (including full traceback)**:
```
Message handling no reply for user message 'Hello there'.
list index out of range
```

**Command or request that led to error**:
```
@google_webhook.route("/webhook", methods=["POST"])
async def receive(request):

    payload = request.json
    sender_id = payload["user"]['userId']
    intent = payload['inputs'][0]['intent'] 			
    text = payload['inputs'][0]['rawInputs'][0]['query']

    try:
        if intent == "actions.intent.MAIN":
            message = "<speak>Hello! <break time=\"1\"/> Welcome to the Rasa-powered Google Assistant skill. You can start by saying hi."
        else:
            out = CollectingOutputChannel()
            new_message = UserMessage(text,out,sender_id,input_channel=self.name())
            #NO EFFECT
            await on_new_message(new_message)
            responses = [m["text"] for m in out.messages]
            message = responses[0]
    except LookupError as e: 
            logger.error("Message handling no reply for user message '{}'.".format(text))
            logger.error(e)
            message = "RASA_NO_REPLY"
```

**Comment by akelad** [comment]
Thanks for raising this issue, @tmbo  will get back to you about it soon.

**Comment by DiegoProtec** [comment]
Did you solve the problem?

**Comment by epiicme** [comment]
@DiegoProtec, unfortunately, no, I'm still waiting to hear from @tmbo. Hopefully, he'll update us soon.

**Comment by tmbo** [comment]
Do you get a complete stacktrace @epiicme, that would help a lot (or at least the complete log)

**Comment by akelad** [comment]
@DiegoProtec could you link the issue you created here?

**Comment by DiegoProtec** [comment]
#3711

**Comment by DiegoProtec** [comment]
I do not know how Agent.load loads the interpreter. When using RasaNLUInterpreter class, occurs error: not found models / metadata.json. How to set interpreter if needed for Agent's lib: from rasa.core.interpreter.NaturalLanguageInterpreter?

```
import ga_connector as ga
from rasa.core.agent import Agent
from rasa.utils.endpoints import EndpointConfig

action_endpoint = EndpointConfig(url="http://localhost:5055/webhook")

agent = Agent.load(
unpacked_model_path='models/',
# error interpreter
action_endpoint=action_endpoint
)

input_channel = ga.CustomAction()
agent.handle_channels(channels=[input_channel], http_port=8877)

**Comment by DiegoProtec** [comment]
Did the test with Postman passing the body:

```
{
  "user": {
    "userId": "xpto",
    "locale": "pt-BR",
    "lastSeen": "2019-06-06T14:04:26Z"
  },
  "conversation": {
    "conversationId": "xpto",
    "type": "NEW"
  },
  "inputs": [
    {
      "intent": "actions.intent.TEXT",
      "rawInputs": [
        {
          "inputType": "KEYBOARD",
          "query": "oi"
        }
      ]
    }
  ],
  "surface": {
    "capabilities": [
      {
        "name": "actions.capability.AUDIO_OUTPUT"
      },
      {
        "name": "actions.capability.ACCOUNT_LINKING"
      },
      {
        "name": "actions.capability.SCREEN_OUTPUT"
      },
      {
        "name": "actions.capability.WEB_BROWSER"
      },
      {
        "name": "actions.capability.MEDIA_RESPONSE_AUDIO"
      }
    ]
  },
  "isInSandbox": true,
  "availableSurfaces": [
    {
      "capabilities": [
        {
          "name": "actions.capability.WEB_BROWSER"
        },
        {
          "name": "actions.capability.AUDIO_OUTPUT"
        },
        {
          "name": "actions.capability.SCREEN_OUTPUT"
        }
      ]
    }
  ],
  "requestType": "SIMULATOR"
}
```

But the stetament:

```
collector = CollectingOutputChannel()
    await on_new_message(
        UserMessage(
             text, collector, sender_id, input_channel=self.name()
        )
    )
message = [value["text"] for value in collector.messages][0]

```
**return error: list index out of range
The list is empty**

My service:
```
from rasa.core.agent import Agent
from rasa.utils.endpoints import EndpointConfig

import google_assistant.ga_connector as ga

action_endpoint = EndpointConfig(url="http://localhost:5055/webhook")
agent = Agent.load(
    unpacked_model_path='models/',
    action_endpoint=action_endpoint
)

actions_channel = ga.GoogleAssistantAction()

agent.handle_channels(channels=[actions_channel], http_port=8877)
```

**Comment by epiicme** [comment]
This is the extent of the log that I'm getting, @tmbo . Let me know if I can help you with more info.
```
Exception occurred while handling uri: 'http://abcdef.org/webhooks/google_assistant/webhook'
Traceback (most recent call last):
  File "C:\Users\john\AppData\Local\Continuum\anaconda3\envs\rasa_dev\lib\site-packages\sanic\app.py", line 917, in handle_request
    response = await response
  File "c:\GoogleAssistant\rasa-x\ga_connector_simple.py", line 73, in receive
    message = responses[0]
IndexError: list index out of range
```

**Comment by DiegoProtec** [comment]
I found the problem, but I don't know fixed it, here is the UserMessage's assinatur:

```
class UserMessage(object):
    """Represents an incoming message.

     Includes the channel the responses should be sent to."""

    DEFAULT_SENDER_ID = "default"

    def __init__(
        self,
        text: Optional[Text] = None,
        output_channel: Optional["OutputChannel"] = None,
        sender_id: Text = None,
        parse_data: Dict[Text, Any] = None,
        input_channel: Text = None,
        message_id: Text = None,
    ) -> None:

```
**`output_channel: Optional["OutputChannel"] = None,`**

Here is how I call it:

```
collector = CollectingOutputChannel()
await on_new_message(
       UserMessage(
               text, collector, sender_id, input_channel=self.name()
       )
)
```

**`collector = CollectingOutputChannel()`**

Incompative types

**Comment by DiegoProtec** [comment]
Got I help u?

**Comment by DiegoProtec** [comment]
Would that I need to implements the CollectingOutputChannel???

**Comment by tmbo** [comment]
What do you mean with `Incompatible types`, do you get an exception or an error that says that? Because from what I can see the types should be fine.

**Comment by nguyennhunai** [comment]
@DiegoProtec Did you fixed this bug ?

**Comment by DiegoProtec** [comment]
Not yet... but on this [issue](https://forum.rasa.com/t/google-assistant-rasa-1-0/10958/2), Juste promised that will update the tutorial.
