### ISSUE TITLE
rasa init error

### ISSUE THREAD

**Issue by Sonia2016** [RasaHQ/rasa#3700]
**Rasa version**:
rasa                               1.0.6    
rasa-core                          0.14.5    
rasa-core-sdk                      0.14.0    
rasa-nlu                           0.15.1    
rasa-sdk                           1.0.0  
**Python version**:
Python 3.6.5 :: Anaconda, Inc.
**Operating system** (windows, osx, ...):
osx
**Issue**:

Traceback (most recent call last):
  File "/Users/soniabaee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/Users/soniabaee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/soniabaee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (python-socketio 3.1.2 (/Users/soniabaee/anaconda3/lib/python3.6/site-packages), Requirement.parse('python-socketio~=4.0'), {'rasa'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/soniabaee/anaconda3/bin/rasa", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Users/soniabaee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/Users/soniabaee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/Users/soniabaee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/soniabaee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/Users/soniabaee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/Users/soniabaee/anaconda3/lib/python3.6/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'python-socketio~=4.0' distribution was not found and is required by rasa

**Command or request that led to error**:
```
rasa init
```

**Comment by imLew** [comment]
Hi Sonia,

Based on the trace it seems like you are missing the `python-socketio` package, try installing it with pip and see if this fixes your problem.

Also, it seems like you have `rasa-core` and `rasa-nlu` installed alongside `rasa`. This is not necessary, core and nlu were are our previous packages, they have now been merged into just `rasa` (i.e. it contains both nlu and core).

**Comment by Sonia2016** [comment]
Hi Lew,
Thanks for responding! I uninstall all my rasa component (rasa, nlu, core) and install rasa (`pip install rasa`). and it check my pip list and apperantly I have 
`python-socketio 4.1.0   `! and still I have the same error!

**Comment by imLew** [comment]
The `skip_if` method was added to the `questionary` module in April this year, so it seems as though you have an old version of `questionary` with which rasa is no longer compatible.
Please let me know which version you have and if it is `<1.1.1` try whether upgrading to the latest version fixes the issue.

**Comment by Sonia2016** [comment]
I upgraded `questionary` package and now is `1.1.1` after that I ran `rasa init` and it still gave me the same error so I created a virtual environment and activate the `.env`, ran `rasa init` and  is running! Thanks!
