### ISSUE TITLE
I am in the final phase of executing my weather chatbot but i am stuck with an issue. I am unable to run the  cod for dialogue_management_model.py.

### ISSUE THREAD

**Issue by gautamnair06** [RasaHQ/rasa#3713]

**Comment by gautamnair06** [comment]
Code in dialogue_management_model.py

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

import logging
import asyncio
import rasa.core
from rasa.core.agent import Agent
from rasa.core.policies.keras_policy import KerasPolicy
from rasa.core.policies.memoization import MemoizationPolicy
from rasa.core.interpreter import RasaNLUInterpreter
from rasa.core.run import serve_application
from rasa.core import config

logger = logging.getLogger(__name__)


async def train_dialogue(domain_file='weather_domain.yml',
                   model_path='./models/dialogue',
                   training_data_file='./data/stories.md'):
    agent = Agent(domain_file, policies=[MemoizationPolicy(),
                                         KerasPolicy(max_history=3, epochs=200,
                                                     batch_size=50)])

    loop = asyncio.get_event_loop()
    data = loop.run_until_complete(agent.load_data(training_data_file))

    agent.train(data)

    agent.persist(model_path)
    return agent


def run_weather_bot(serve_forever=True):
    interpreter = RasaNLUInterpreter('./models/nlu/default/weathernlu')
    agent = Agent.load('./models/dialogue', interpreter=interpreter)
    rasa.core.run.serve_application(agent, channel='cmdline')

    return agent


if __name__ == '__main__':
    train_dialogue()
    run_weather_bot()

**Comment by gautamnair06** [comment]
Error when running the code:

dialogue_management_model.py:44: RuntimeWarning: coroutine 'train_dialogue' was never awaited
  train_dialogue()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
2019-06-06 08:49:54.740803: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
WARNING:tensorflow:From C:\Users\Gautam\Anaconda3\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py:435: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
WARNING:tensorflow:From C:\Users\Gautam\Anaconda3\lib\site-packages\tensorflow\python\keras\backend.py:4010: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
WARNING:tensorflow:From C:\Users\Gautam\Anaconda3\lib\site-packages\tensorflow\python\ops\math_ops.py:3066: to_int32 (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.cast instead.
INFO:root:Starting Rasa Core server on http://localhost:5005
[2019-06-06 08:49:56 +0530] [1272] [ERROR] Experienced exception while trying to serve
Traceback (most recent call last):
  File "C:\Users\Gautam\Anaconda3\lib\site-packages\sanic\app.py", line 1096, in run
    serve(**server_settings)
  File "C:\Users\Gautam\Anaconda3\lib\site-packages\sanic\server.py", line 742, in serve
    trigger_events(before_start, loop)
  File "C:\Users\Gautam\Anaconda3\lib\site-packages\sanic\server.py", line 604, in trigger_events
    loop.run_until_complete(result)
  File "C:\Users\Gautam\Anaconda3\lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
  File "C:\Users\Gautam\Anaconda3\lib\site-packages\rasa\core\run.py", line 174, in load_agent_on_start
    _broker = broker.from_endpoint_config(endpoints.event_broker)
AttributeError: 'NoneType' object has no attribute 'event_broker'
Traceback (most recent call last):
  File "dialogue_management_model.py", line 45, in <module>
    run_weather_bot()
  File "dialogue_management_model.py", line 38, in run_weather_bot
    rasa.core.run.serve_application(agent, channel='cmdline')
  File "C:\Users\Gautam\Anaconda3\lib\site-packages\rasa\core\run.py", line 150, in serve_application
    app.run(host="0.0.0.0", port=port)
  File "C:\Users\Gautam\Anaconda3\lib\site-packages\sanic\app.py", line 1096, in run
    serve(**server_settings)
  File "C:\Users\Gautam\Anaconda3\lib\site-packages\sanic\server.py", line 742, in serve
    trigger_events(before_start, loop)
  File "C:\Users\Gautam\Anaconda3\lib\site-packages\sanic\server.py", line 604, in trigger_events
    loop.run_until_complete(result)
  File "C:\Users\Gautam\Anaconda3\lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
  File "C:\Users\Gautam\Anaconda3\lib\site-packages\rasa\core\run.py", line 174, in load_agent_on_start
    _broker = broker.from_endpoint_config(endpoints.event_broker)
AttributeError: 'NoneType' object has no attribute 'event_broker'

**Comment by akelad** [comment]
Please ask these kind of questions in our [forum](https://forum.rasa.com)
