### ISSUE TITLE
ERROR:rasa.core.channels.facebook:Exception when trying to handle webhook for facebook message.

### ISSUE THREAD

**Issue by majjihari** [RasaHQ/rasa#3727]
**Rasa version**:
1.0.7

**Rasa X version** (if used & relevant):
0.19.0

**Python version**:
3.6.8

**Operating system** (windows, osx, ...):
ubuntu 19.04

**Issue**:
Can able to receive messages from FB Messenger. But bot could not respond. In fact unable to find next action. There is no memorised next action (debug) and also facebook exception (error). 

**Error (including full traceback)**:
```
DEBUG:rasa.core.processor:Received user message 'Hi' with intent '{'name': 'greet', 'confidence': 0.9773842096328735}' and entities '[]'
DEBUG:rasa.core.processor:Logged UserUtterance - tracker now has 4 events
DEBUG:rasa.core.policies.memoization:Current tracker state [None, {}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}]
DEBUG:rasa.core.policies.memoization:There is no memorised next action
DEBUG:rasa.core.policies.memoization:Current tracker state [None, None, None, {}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}]
DEBUG:rasa.core.policies.memoization:Launch DeLorean...
DEBUG:rasa.core.policies.memoization:Current tracker state [None, None, None, {}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}]
DEBUG:rasa.core.policies.memoization:There is no memorised next action
DEBUG:rasa.core.agent:Deleted lock for conversation '2373945415998316' (unused)
ERROR:rasa.core.channels.facebook:Exception when trying to handle webhook for facebook message.
Traceback (most recent call last):
  File "/home/hari/environment_directory/rasa-tutorial/first/lib/python3.7/site-packages/rasa/core/channels/facebook.py", line 94, in _handle_user_message
    await self.on_new_message(user_msg)
  File "/home/hari/environment_directory/rasa-tutorial/first/lib/python3.7/site-packages/rasa/core/channels/channel.py", line 68, in handler
    await app.agent.handle_message(*args, **kwargs)
  File "/home/hari/environment_directory/rasa-tutorial/first/lib/python3.7/site-packages/rasa/core/agent.py", line 441, in handle_message
    return await processor.handle_message(message)
  File "/home/hari/environment_directory/rasa-tutorial/first/lib/python3.7/site-packages/rasa/core/processor.py", line 74, in handle_message
    await self._predict_and_execute_next_action(message, tracker)
  File "/home/hari/environment_directory/rasa-tutorial/first/lib/python3.7/site-packages/rasa/core/processor.py", line 337, in _predict_and_execute_next_action
    action, policy, confidence = self.predict_next_action(tracker)
  File "/home/hari/environment_directory/rasa-tutorial/first/lib/python3.7/site-packages/rasa/core/processor.py", line 164, in predict_next_action
    action_confidences, policy = self._get_next_action_probabilities(tracker)
  File "/home/hari/environment_directory/rasa-tutorial/first/lib/python3.7/site-packages/rasa/core/processor.py", line 550, in _get_next_action_probabilities
    tracker, self.domain
  File "/home/hari/environment_directory/rasa-tutorial/first/lib/python3.7/site-packages/rasa/core/policies/ensemble.py", line 342, in probabilities_using_best_policy
    probabilities = p.predict_action_probabilities(tracker, domain)
  File "/home/hari/environment_directory/rasa-tutorial/first/lib/python3.7/site-packages/rasa/core/policies/keras_policy.py", line 252, in predict_action_probabilities
    X = self.featurizer.create_X([tracker], domain)
  File "/home/hari/environment_directory/rasa-tutorial/first/lib/python3.7/site-packages/rasa/core/featurizers.py", line 408, in create_X
    X, _ = self._featurize_states(trackers_as_states)
  File "/home/hari/environment_directory/rasa-tutorial/first/lib/python3.7/site-packages/rasa/core/featurizers.py", line 335, in _featurize_states
    self.state_featurizer.encode(state) for state in tracker_states
  File "/home/hari/environment_directory/rasa-tutorial/first/lib/python3.7/site-packages/rasa/core/featurizers.py", line 335, in <listcomp>
    self.state_featurizer.encode(state) for state in tracker_states
  File "/home/hari/environment_directory/rasa-tutorial/first/lib/python3.7/site-packages/rasa/core/featurizers.py", line 102, in encode
    "BinarySingleStateFeaturizer was not prepared before encoding."
Exception: BinarySingleStateFeaturizer was not prepared before encoding.
WARNING:asyncio:Executing <Task finished coro=<SanicPluginsFramework._handle_request() done, defined at /home/hari/environment_directory/rasa-tutorial/first/lib/python3.7/site-packages/spf/framework.py:471> result=None created at /home/hari/environment_directory/rasa-tutorial/first/lib/python3.7/site-packages/sanic/server.py:365> took 0.006 seconds

```

**Command or request that led to error**:
```

def run(serve_forever=True, debug=False):
  logging.basicConfig(stream=sys.stdout, level=logging.DEBUG)
  logger = logging.getLogger(__name__)

  # load your trained agent
  interpreter = RasaNLUInterpreter("models/current/nlu")
  MODEL_PATH = "models/current/core"

  action_endpoint = EndpointConfig(url="https://ogmoneybot-actions.herokuapp.com/webhook")

  max_history = 3
  agent = Agent(MODEL_PATH, interpreter=interpreter, action_endpoint=action_endpoint, 
  policies=[
  MemoizationPolicy(max_history=max_history),
  AugmentedMemoizationPolicy(),
  KerasPolicy(MaxHistoryTrackerFeaturizer(BinarySingleStateFeaturizer(),
                                            max_history=max_history)),MappingPolicy(),FallbackPolicy(nlu_threshold=0.3, core_threshold=0.3)])

  #training_data_file='data/stories.md'
  #data = agent.load_data(training_data_file)
  #agent.train(data)

  #agent = agent.load(MODEL_PATH, interpreter=interpreter, action_endpoint=action_endpoint)

  input_channel = FacebookInput(
        fb_verify="some value",
        # you need tell facebook this token, to confirm your URL
        fb_secret="some value",  # your app secret
 fb_access_token="some value"
        # token for the page you subscribed to
  )
  # set serve_forever=False if you want to keep the server running
  if serve_forever:
    agent.handle_channels([input_channel], int(os.environ.get('PORT', 5004)))
    #agent.handle_channel(HttpInputChannel(5004, "/app", input_channel))
  return agent
```

**Content of configuration file (config.yml)** (if relevant):
```yml
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline: supervised_embeddings

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
  - name: "FallbackPolicy"
    nlu_threshold: 0.3
    core_threshold: 0.3
    fallback_action_name: "action_default_fallback"
```

**Content of domain file (domain.yml)** (if relevant):
```yml
entities:
- balance_type
- dob

intents:
  - help
  - greet
  - goodbye
  - balance_enquiry
  - report_issue
  - transaction_info
  - current_location
  - service_receipt
  - affirm
  - deny
  - mood_great
  - mood_unhappy
  - ask
  - ask_response

slots:
  balance_type:
    type: categorical
    values:
    - mobile
    - wallet
  mobile_balance:
    max_value: 1.0
    min_value: 0.0
    type: float
  service_category:
    type: categorical
    values:
    - mobile_bill_payment
    - topup
    - voucher
    - charity
  service_type:
    type: categorical
    values:
    - prepaid
    - postpaid
  telecom_operator:
    type: categorical
    values:
    - zain
    - ooredoo
    - viva
  wallet_balance:
    max_value: 1.0
    min_value: 0.0
    type: float

templates:
  utter_cheer_up:
    - text: 'Here is something to cheer you up:'
      image: https://i.imgur.com/nGF1K8f.jpg
  utter_default:
    - text: Sorry, I didn't understand that
  utter_did_that_help:
    - text: Did that help you?
  utter_goodbye:
    - text: Bye
  utter_greet:
    - text: Hey! How are you?
  utter_happy:
    - text: Great carry on!
  utter_help:
    - text: I can help you view your balances, transaction history, report issues if any.
  utter_mobile_balance:
    - text: 'Your mobile balance is: {mobile_balance}'
  utter_telecom_usage_info:
    - text: Bye
  utter_wallet_balance:
    - text: 'Your wallet balance is: {wallet_balance}'
  utter_which_balance:
    - text: Which balance?
      buttons:
      - title: Operator balance
        payload: /balance_enquiry{"balance_type":"mobile"}
      - title: Wallet balance
        payload: /balance_enquiry{"balance_type":"wallet"}

    

actions:
- action_fetch_mobile_balance
- action_fetch_wallet_balance
- utter_cheer_up
- utter_did_that_help
- utter_goodbye
- utter_greet
- utter_happy
- utter_help
- utter_mobile_balance
- utter_telecom_usage_info
- utter_wallet_balance
- utter_which_balance
```

**Comment by akelad** [comment]
I don't think this is related to facebook messenger, but rather how you're training/loading your bot. I assume you've trained your bot with `rasa train` and the config file you specified? Can I ask why you're not just starting it with `rasa run` instead of with the custom code?

**Comment by majjihari** [comment]
> I don't think this is related to facebook messenger, but rather how you're training/loading your bot. I assume you've trained your bot with `rasa train` and the config file you specified? Can I ask why you're not just starting it with `rasa run` instead of with the custom code?

Thank you akelad for your response. Yes trained with rasa train and also tested with "rasa run --credentials credentials.yml -c facebook" as well. Still the result is same. Credentials.yml contains the correct credentials of facebook as well.
