### ISSUE TITLE
oracle connection don´t work 

### ISSUE THREAD

**Issue by Robertjbc** [RasaHQ/rasa#3736]
hello rasa friend i need to connect my rasa bot to a oracle data for save the conversation, but when i write a message to my bot this send me a error..

`2019-06-07 15:51:36 ERROR    rasa.core.channels.channel  - An exception occured while handling user message 'hello'.
Traceback (most recent call last):
  File "c:\users\capitalminds\appdata\local\programs\python\python36\lib\site-packages\sqlalchemy\engine\base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "c:\users\capitalminds\appdata\local\programs\python\python36\lib\site-packages\sqlalchemy\engine\default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
cx_Oracle.IntegrityError: ORA-01400: cannot insert NULL into ("C##RASA"."EVENTS"."ID")`

i´ll check the connection and don´t have any error and i´ll check the tables and everythings is ok 
if you can help me i appreciate it

regards :wink:

**Comment by akelad** [comment]
If this is a potential bug, then please fill out the bug issue template. If it's not a bug from rasa, please post the question on our [forum](https://forum.rasa.com) instead
