### ISSUE TITLE
Rasa init error after successful installation

### ISSUE THREAD

**Issue by ArupMukherjee** [RasaHQ/rasa#3771]
**Rasa version**:
1.0.9
**Rasa X version** (if used & relevant):

**Python version**:
Anaconda Python 3.7

**Operating system** (windows, osx, ...):
Windows
**Issue**:
After successful installation of Rasa on trying to iniitialize using rasa init --no-prompt an error is thrown.

**Error (including full traceback)**:
```
Welcome to Rasa! 🤖

To get started quickly, an initial project will be created.
If you need some help, check out the documentation at https://rasa.com/docs/rasa.

Created project directory at 'C:\rasa'.
Finished creating project structure.
Training an initial model...
Training Core model...
Traceback (most recent call last):
  File "C:\Python_Anaconda\Scripts\rasa-script.py", line 11, in <module>
    load_entry_point('rasa', 'console_scripts', 'rasa')()
  File "c:\rasa\rasa\__main__.py", line 70, in main
    cmdline_arguments.func(cmdline_arguments)
  File "c:\rasa\rasa\cli\scaffold.py", line 194, in run
    init_project(args, path)
  File "c:\rasa\rasa\cli\scaffold.py", line 112, in init_project
    print_train_or_instructions(args, path)
  File "c:\rasa\rasa\cli\scaffold.py", line 50, in print_train_or_instructions
    args.model = rasa.train(domain, config, training_files, output)
  File "c:\rasa\rasa\train.py", line 48, in train
    kwargs=kwargs,
  File "C:\Python_Anaconda\lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
  File "c:\rasa\rasa\train.py", line 144, in train_async
    kwargs=kwargs,
  File "c:\rasa\rasa\train.py", line 183, in _do_training
    kwargs=kwargs,
  File "c:\rasa\rasa\train.py", line 313, in _train_core_with_validated_data
    kwargs=kwargs,
  File "c:\rasa\rasa\core\train.py", line 25, in train
    from rasa.core.agent import Agent
  File "c:\rasa\rasa\core\agent.py", line 27, in <module>
    from rasa.core.policies import FormPolicy, Policy
  File "c:\rasa\rasa\core\policies\__init__.py", line 11, in <module>
    from rasa.core.policies.sklearn_policy import SklearnPolicy
  File "c:\rasa\rasa\core\policies\sklearn_policy.py", line 8, in <module>
    from sklearn.base import clone
  File "C:\Python_Anaconda\lib\site-packages\sklearn\__init__.py", line 64, in <module>
    from .base import clone
  File "C:\Python_Anaconda\lib\site-packages\sklearn\base.py", line 13, in <module>
    from .utils.fixes import signature
  File "C:\Python_Anaconda\lib\site-packages\sklearn\utils\__init__.py", line 16, in <module>
    from .fixes import _Sequence as Sequence
  File "C:\Python_Anaconda\lib\site-packages\sklearn\utils\fixes.py", line 85, in <module>
    from scipy.special import boxcox  # noqa
  File "C:\Python_Anaconda\lib\site-packages\scipy\special\__init__.py", line 641, in <module>
    from ._ufuncs import *
ImportError: DLL load failed: The specified module could not be found.

```

**Command or request that led to error**:
```
rasa init --no-prompt
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by akelad** [comment]
Thanks for raising this issue, @erohmensing  will get back to you about it soon.

**Comment by erohmensing** [comment]
Hi @ArupMukherjee, do you have the [Windows requirements](https://rasa.com/docs/rasa/user-guide/installation/#windows-prerequisites) installed?

**Comment by ArupMukherjee** [comment]
Thanks @erohmensing , @akelad  for your responses. I was able to navigate past the errors by creating a virtual python environment using python = 3.6, My anaconda python = 3.7 was giving me issues.

**Comment by erohmensing** [comment]
Hm that's strange, 3.7 should be supported, but we can look into making sure it is supported as expected on windows. Glad you were able to get past the errors.

**Comment by wochinge** [comment]
@ArupMukherjee Could you please try uninstalling / installing `scipy` in your 3.7 environmet?

**Comment by narasivenkat** [comment]
For windows, visual studio 19 needs to be installed. Once done rasa init --no-prompt works fine for python 3.7. tensorflow 2.1 as well.
