### ISSUE TITLE
rasa train command error message

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa#3794]
**Rasa version**: 1.1.13

**Issue**:

If you run the `rasa train` command and don't provide a `--domain` option, a python stack trace results instead of an error message message that the domain file was a required option.

**Error (including full traceback)**:
```
docker run -v $(pwd)/data:/app/data rasa/rasa:latest-full train core --config /app/data/config.yml --stories /app/data/stories --out /app/data/models --augmentation 0 --quiet
2019-06-15 00:52:47 ERROR    rasa.core.training.dsl  - Error in line 2: 'NoneType' object has no attribute 'intents'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/rasa/core/training/dsl.py", line 301, in process_lines
    await self.add_user_messages(user_messages, line_num)
  File "/usr/local/lib/python3.6/site-packages/rasa/core/training/dsl.py", line 383, in add_user_messages
    *[self._parse_message(m, line_num) for m in messages]
  File "/usr/local/lib/python3.6/site-packages/rasa/core/training/dsl.py", line 367, in _parse_message
    if intent_name not in self.domain.intents:
AttributeError: 'NoneType' object has no attribute 'intents'
2019-06-15 00:52:47 ERROR    rasa.core.training.dsl  - Invalid story file format. Failed to parse '/tmp/tmpz84lkggv/c24e99a4b7ff480f80047ec55ce5b484_claimzen.md'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/rasa/core/training/dsl.py", line 301, in process_lines
    await self.add_user_messages(user_messages, line_num)
  File "/usr/local/lib/python3.6/site-packages/rasa/core/training/dsl.py", line 383, in add_user_messages
    *[self._parse_message(m, line_num) for m in messages]
  File "/usr/local/lib/python3.6/site-packages/rasa/core/training/dsl.py", line 367, in _parse_message
    if intent_name not in self.domain.intents:
AttributeError: 'NoneType' object has no attribute 'intents'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/rasa/core/training/dsl.py", line 214, in read_from_file
    return await reader.process_lines(lines)
  File "/usr/local/lib/python3.6/site-packages/rasa/core/training/dsl.py", line 313, in process_lines
    raise ValueError(msg)
ValueError: Error in line 2: 'NoneType' object has no attribute 'intents'
Training Core model...
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/rasa/core/training/dsl.py", line 301, in process_lines
    await self.add_user_messages(user_messages, line_num)
  File "/usr/local/lib/python3.6/site-packages/rasa/core/training/dsl.py", line 383, in add_user_messages
    *[self._parse_message(m, line_num) for m in messages]
  File "/usr/local/lib/python3.6/site-packages/rasa/core/training/dsl.py", line 367, in _parse_message
    if intent_name not in self.domain.intents:
AttributeError: 'NoneType' object has no attribute 'intents'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/rasa", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/rasa/__main__.py", line 70, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/usr/local/lib/python3.6/site-packages/rasa/cli/train.py", line 121, in train_core
    kwargs=extract_additional_arguments(args),
  File "/usr/local/lib/python3.6/site-packages/rasa/train.py", line 215, in train_core
    kwargs=kwargs,
  File "uvloop/loop.pyx", line 1451, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.6/site-packages/rasa/train.py", line 277, in train_core_async
    kwargs=kwargs,
  File "/usr/local/lib/python3.6/site-packages/rasa/train.py", line 303, in _train_core_with_validated_data
    kwargs=kwargs,
  File "/usr/local/lib/python3.6/site-packages/rasa/core/train.py", line 57, in train
    stories_file, exclusion_percentage=exclusion_percentage, **data_load_args
  File "/usr/local/lib/python3.6/site-packages/rasa/core/agent.py", line 616, in load_data
    exclusion_percentage=exclusion_percentage,
  File "/usr/local/lib/python3.6/site-packages/rasa/core/training/__init__.py", line 50, in load_data
    resource_name, domain, exclusion_percentage=exclusion_percentage
  File "/usr/local/lib/python3.6/site-packages/rasa/core/training/__init__.py", line 29, in extract_story_graph
    exclusion_percentage=exclusion_percentage,
  File "/usr/local/lib/python3.6/site-packages/rasa/core/training/dsl.py", line 186, in read_from_folder
    f, domain, interpreter, template_variables, use_e2e
  File "/usr/local/lib/python3.6/site-packages/rasa/core/training/dsl.py", line 214, in read_from_file
    return await reader.process_lines(lines)
  File "/usr/local/lib/python3.6/site-packages/rasa/core/training/dsl.py", line 313, in process_lines
    raise ValueError(msg)
```

**Command or request that led to error**:
```
docker run -v $(pwd)/data:/app/data rasa/rasa:latest-full train core --config /app/data/config.yml --stories /app/data/stories --out /app/data/models --augmentation 0 --quiet
```

**Comment by akelad** [comment]
Thanks for raising this issue, @ricwo  will get back to you about it soon.

**Comment by ricwo** [comment]
Hi @rgstephens, we should indeed throw a more useful warning and not just fail. Thanks for pointing this out!

**Comment by RanaMostafaAbdElMohsen** [comment]
Hello @ricwo ,
I am currently working on the issue. 
I just have one question :
- Should it fires just a warning and continues execution? or it should throw a warning and then terminates program ?

**Comment by ricwo** [comment]
Hi @RanaMostafaAbdElMohsen, thanks for working on this! Training can continue in that case, but only for NLU. The warning should explicitly state that Core training is skipped because no domain was found.

**Comment by akelad** [comment]
@RanaMostafaAbdElMohsen thanks a lot for taking this on, let us know if you have any questions in the process

**Comment by RanaMostafaAbdElMohsen** [comment]
@akelad @ricwo 
Would you please help me  in test coverage ?
I think a new test case should be added to `rasa/tests/cli/test_rasa_train.py` as below:
```python
def test_train_core_no_domain(run_in_default_project):
    run_in_default_project(
        "train",
        "core",
        "-c",
        "config.yml",
        "--stories",
        "data",
        "--out",
        "train_rasa_models",
        "--fixed-model-name",
        "rasa-model",
    )

    assert os.path.exists("train_rasa_models/rasa-model.tar.gz")
    assert os.path.isfile("train_rasa_models/rasa-model.tar.gz")
```
Am I on the right track ? Please advise

**Comment by ricwo** [comment]
@RanaMostafaAbdElMohsen, this test is indeed necessary! It would be great if we could also check for `domain.yml` is not present. To do this, we'll have to unpack the existing model first:


```python
from rasa import model

trained_model_path = "train_rasa_models/rasa-model.tar.gz"
unpacked = model.unpack_model(trained_model_path)

# finterprint.json is present
fingerprint_path = os.path.join(unpacked, "fingerprint.json")
assert os.path.exists(fingerprint_path)

# core/domain.yml is not present
domain_path = os.path.join(unpacked, "core", "domain.yml")
assert not os.path.exists(domain_path)
```

we should probably also check that NLU training worked, by checking for the presence of, for example, `nlu/metadata.json`.

**Comment by RanaMostafaAbdElMohsen** [comment]
@ricwo @akelad 
I have followed documentation steps so I can run tests locally using `make tests` command
and a large number of test cases fail locally. However, when test cases execute on Travis, they run successfully.

Can you please advise what am I missing here so tests execute correctly, so I can validate my own test cases.
Thanks a lot.

**Comment by ricwo** [comment]
@RanaMostafaAbdElMohsen did you install all requirements in `requirements-dev.txt`? If that doesn't help, you might have to try with a fresh python virtual / conda environment.

would running only your newly added tests instead of the whole suite be an option?
