### ISSUE TITLE
use_entities in domain raises TypeError Exception

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa#3796]
**Rasa version**: 1.1.13

If you use the now deprecated `use_entities` syntax in the `domain.yml` rasa command produces a stack trace. It should issue a Deprecation error message.

```
  - chitchat: null
    use_entities: false
```
Here's the stack trace you get when you use the now deprecated syntax.

```
Traceback (most recent call last):
  File "/usr/local/bin/rasa", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/site-packages/rasa/__main__.py", line 70, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/usr/local/lib/python3.6/site-packages/rasa/cli/train.py", line 121, in train_core
    kwargs=extract_additional_arguments(args),
  File "/usr/local/lib/python3.6/site-packages/rasa/train.py", line 215, in train_core
    kwargs=kwargs,
  File "uvloop/loop.pyx", line 1451, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.6/site-packages/rasa/train.py", line 252, in train_core_async
    domain = Domain.load(domain, skill_imports)
  File "/usr/local/lib/python3.6/site-packages/rasa/core/domain.py", line 77, in load
    other = cls.from_path(path, skill_imports)
  File "/usr/local/lib/python3.6/site-packages/rasa/core/domain.py", line 91, in from_path
    domain = cls.from_file(path)
  File "/usr/local/lib/python3.6/site-packages/rasa/core/domain.py", line 104, in from_file
    return cls.from_yaml(rasa.utils.io.read_file(path))
  File "/usr/local/lib/python3.6/site-packages/rasa/core/domain.py", line 114, in from_yaml
    return cls.from_dict(data)
  File "/usr/local/lib/python3.6/site-packages/rasa/core/domain.py", line 121, in from_dict
    intent_properties = cls.collect_intent_properties(data.get("intents", {}))
  File "/usr/local/lib/python3.6/site-packages/rasa/core/domain.py", line 217, in collect_intent_properties
    if "use_entities" not in properties:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by akelad** [comment]
Thanks for raising this issue, @erohmensing  will get back to you about it soon.

**Comment by erohmensing** [comment]
Hi @rgstephens, where did you find that syntax? Perhaps you just missed the yaml indentation?
```yaml
- chitchat: 
    use_entities: false 
```
Should work.

**Comment by rgstephens** [comment]
I can't find an example now with "null" added so I don't know where I got it.

However, the issue syntax as you display it does not work.

Take off the "null" and I still get the stack trace instead of a Depreciation error message.

**Comment by erohmensing** [comment]
Hm, I'm really not sure what you're talking about, I can't replicate it. With my domain file intents like so, Core training works perfectly for me. 
```
intents:
  - greet:
      use_entities: false
  - goodbye
  - affirm
  - deny
  - mood_great
  - mood_unhappy
```
As far as I know, we haven't deprecated this syntax.

**Comment by rgstephens** [comment]
You're right, if I indent `use_entities` it works.  Still wonder where I got that `null` syntax that had been working for me the past year.

Thanks for your help.
