### ISSUE TITLE
Compatibility with Windows and python 3.7

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#3801]
People on windows seem to have issues running spacy in python 3.7

https://github.com/RasaHQ/rasa/issues/3771#event-2415515719
We should go though and test the installation of both rasa and rasa x with 3.7 on windows

**Comment by akelad** [comment]
how 🤔

**Comment by erohmensing** [comment]
@akelad how do we test, or how is it happening? I think some of our new guys have windows computers no?

It might be a 64 vs 32 bit thing though https://stackoverflow.com/questions/39020361/python-scipy-module-import-error-due-to-missing-ufuncs-dll

**Comment by akelad** [comment]
i think they all have linux installed. But i'm not really sure this is an issue specific to rasa, but rather to spacy/tensorflow? 

Also the forum question you posted is someting different no? That's about running a docker image on windows (which is another problem...)

**Comment by wochinge** [comment]
We could test it using a windows server vm on gcloud?

**Comment by wochinge** [comment]
@JEM-Mosig Has Windows 🙂

**Comment by wochinge** [comment]
This forum post was not connected to the issue, they were just using the wrong image: https://forum.rasa.com/t/run-rasa-x-using-public-docker-image/11472

**Comment by erohmensing** [comment]
@wochinge I know, I let him know that. I was referring to his comment: 

> Context: I’m on Win10 with Python 3.7 installed. Can’t change that for other reasons. I can’t, therefore, install Rasa x natively (Tensorflow incompatible with Py 3.7).

His response was:

> Hi @erohmensing, thanks for your response. The TensorFlow/Py3.7 incompatibility dates back to Oct 18 (see related Q [here](https://forum.rasa.com/t/installation-failing-tensorflow-1-10-0-not-found/2129/4)). Looking again now at the TensorFlow installation instructions, it doesn’t explicitly mention 3.7 incompatibility. So it may have been resolved - my problem above might not be that.

So I guess you're right, seems like his issue was when we had the python 3.7, tensorflow 1.10.0 compatibility issue.

**Comment by wochinge** [comment]
@erohmensing Did you read of any more issues? Otherwise I think we can close it.

**Comment by erohmensing** [comment]
Yeah, I think that’s fine for now

**Comment by ValeriuOlar** [comment]
I got the same issue on Win 10 machine when run command: rasa init

Traceback (most recent call last):
  File "C:\Users\valeriu.olariu\AppData\Local\Programs\Python\Python36\Scripts\rasa-script.py", line 11, in <module>
    load_entry_point('rasa', 'console_scripts', 'rasa')()
  File "c:\users\valeriu.olariu\openjaw\rasa t\rasa\rasa\__main__.py", line 69, in main
    set_log_level(log_level)
  File "c:\users\valeriu.olariu\openjaw\rasa t\rasa\rasa\utils\common.py", line 68, in set_log_level
    update_tensorflow_log_level()
  File "c:\users\valeriu.olariu\openjaw\rasa t\rasa\rasa\utils\common.py", line 87, in update_tensorflow_log_level
    import tensorflow as tf
  File "c:\users\valeriu.olariu\appdata\local\programs\python\python36\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "c:\users\valeriu.olariu\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "c:\users\valeriu.olariu\appdata\local\programs\python\python36\lib\site-packages\tensorflow\core\framework\graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "c:\users\valeriu.olariu\appdata\local\programs\python\python36\lib\site-packages\google\protobuf\descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: DLL load failed: The specified procedure could not be found.
