### ISSUE TITLE
Config file error

### ISSUE THREAD

**Issue by OwaisRaza1** [RasaHQ/rasa#3821]
I am facing issue when I run rasa UI with nlu server, when I start rasa UI and it hits to the nlu server at port 5000 it throws following exception:

[5860] [ERROR] Exception occurred while handling uri: 'http://localhost:5000/config'
Traceback (most recent call last):
File "/usr/local/lib/python3.6/dist-packages/sanic/app.py", line 893, in handle_request
handler, args, kwargs, uri = self.router.get(request)
File "/usr/local/lib/python3.6/dist-packages/sanic/router.py", line 407, in get
return self._get(request.path, request.method, "")
File "/usr/local/lib/python3.6/dist-packages/sanic/router.py", line 469, in _get
raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /config not found

Unable to find its solution can you please help ???

**Comment by akelad** [comment]
@OwaisRaza1 if this is a potential bug, then please open an issue with the "Bug Report" template and fill out all the necessary information
