### ISSUE TITLE
RASA SDK ISSUE

### ISSUE THREAD

**Issue by Robertjbc** [RasaHQ/rasa#3834]
hello rasa friend i have a issue about the custom actions in rasa and  when i try to use the dispatcher for send the result of my code and send me that error

`C:\Users\capitalminds\Desktop\Empresa Risco>rasa run actions --cors "*"  --debug
2019-06-20 15:21:52 INFO     rasa_sdk.endpoint  - Starting action endpoint server...
2019-06-20 15:21:52 INFO     rasa_sdk.executor  - Registered function for 'action_prueba_de_datos'.
2019-06-20 15:21:52 INFO     rasa_sdk.endpoint  - Action endpoint is up and running. on ('0.0.0.0', 5055)
2019-06-20 15:22:09 DEBUG    rasa_sdk.executor  - Received request to run 'action_prueba_de_datos'
2019-06-20 15:22:09 ERROR    flask.app  - Exception on /webhook [POST]
Traceback (most recent call last):
  File "c:\users\capitalminds\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\capitalminds\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\capitalminds\appdata\local\programs\python\python36\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "c:\users\capitalminds\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\capitalminds\appdata\local\programs\python\python36\lib\site-packages\flask\_compat.py", line 36, in reraise
    raise value
  File "c:\users\capitalminds\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\capitalminds\appdata\local\programs\python\python36\lib\site-packages\flask\app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\capitalminds\appdata\local\programs\python\python36\lib\site-packages\flask_cors\decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "c:\users\capitalminds\appdata\local\programs\python\python36\lib\site-packages\rasa_sdk\endpoint.py", line 59, in webhook
    response = executor.run(action_call)
  File "c:\users\capitalminds\appdata\local\programs\python\python36\lib\site-packages\rasa_sdk\executor.py", line 245, in run
    events = action(dispatcher, tracker, domain)
  File "C:\Users\capitalminds\Desktop\Empresa Risco\actions.py", line 26, in run
    dispatcher.utter_message(respuesta)
AttributeError: 'action_prueba_de_datos' object has no attribute 'utter_message'
127.0.0.1 - - [2019-06-20 15:22:09] "POST /webhook HTTP/1.1" 500 443 0.251003

the code have attribute and i don't know how to do

regards :wink:

`

**Comment by erohmensing** [comment]
@Robertjbc as this is a usage question, you should post it on our [forum](forum.rasa.com). Post the error and the action `run.py` method there, are we will be able to help you.
