### ISSUE TITLE
How to fix "rasa' is not recognized as an internal or external command, operable program or batch file." Im trying to create a new project .

### ISSUE THREAD

**Issue by Vyshnavi-R** [RasaHQ/rasa#3852]

**Comment by Vyshnavi-R** [comment]
i have executed the following commands :

      *  pip install rasa[spacy]
      *  python -m spacy download en_core_web_md (linking successful)

and got an error : Failed building wheel for httptools

when i run "rasa init " to create a new project , i get 
""rasa' is not recognized as an internal or external command, operable program or batch file.""

**Comment by psds01** [comment]
Please try this and install rasa (x) again: https://askubuntu.com/questions/398489/how-to-install-build-essential

**Comment by wochinge** [comment]
Thanks for raising this issue, @erohmensing will get back to you about it soon.

**Comment by erohmensing** [comment]
@Vyshnavi-R Can you post the full error you get for ` Failed building wheel for httptools`?

**Comment by Vyshnavi-R** [comment]
Thanks! The issue is now resolved.
I ran the following command to resolve `Failed building wheel for httptools`.
`conda install -c conda-forge httptools `  in anaconda prompt.
resource : [https://anaconda.org/conda-forge/httptools](https://anaconda.org/conda-forge/httptools)

**Comment by erohmensing** [comment]
Awesome, glad you got it fixed 🚀

**Comment by sukgithub1** [comment]
you can try something like:
pip install rasa-x --extra-index-url https://pypi.rasa.com/simple

**Comment by discreterandomvariable** [comment]
I am facing the same issue where I am getting the error 'rasa' is not recognized as an internal or external command,operable program or batch file.
I have tried 'rasa init', 'rasa init --no-prompt', 'rasa init --from-remote url' on Anaconda prompt with the same error mentioned above.  
I am on Windows 7 and working on Anaconda Prompt with python 3.6.5. I was facing an issue with installation of httptools package earlier but I resolved it by installing it using wheel file generated on a Windows 10 system. Similarly I installed rasa-nlu package using a wheel file created on Windows 10 system. Can someone help resolve the issue?

**Comment by discreterandomvariable** [comment]
![image](https://user-images.githubusercontent.com/12828468/63595178-ea3bbc00-c5d5-11e9-8e8a-ffa6b5509e37.png)

This is what I get when I execute pip install rasa. And when I do pip list I don't find rasa-nlu or rasa-core installed.

**Comment by erohmensing** [comment]
It looks like it is not able to install rasa because of the greenlet error. Installing rasa doesn't install rasa-nlu and rasa-core, just rasa. Looks like you're trying to install into your base environment, which isn't recommended (because it will e.g. try to change versions of disutils projects). Can you create a new anaconda env and try to install it there?

**Comment by erohmensing** [comment]
Please create new posts on our [forum](forum.rasa.com) if you have trouble installing or executing Rasa

**Comment by kramitjha** [comment]
installed rasa but gettin this message
can anyone help


C:\Users\Sanjiw Jha>rasa
Traceback (most recent call last):
  File "c:\users\sanjiw jha\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "c:\users\sanjiw jha\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "c:\users\sanjiw jha\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "c:\users\sanjiw jha\appdata\local\programs\python\python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "c:\users\sanjiw jha\appdata\local\programs\python\python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\sanjiw jha\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\sanjiw jha\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Sanjiw Jha\AppData\Local\Programs\Python\Python37\Scripts\rasa.exe\__main__.py", line 7, in <module>
  File "c:\users\sanjiw jha\appdata\local\programs\python\python37\lib\site-packages\rasa\__main__.py", line 82, in main
    set_log_level(log_level)
  File "c:\users\sanjiw jha\appdata\local\programs\python\python37\lib\site-packages\rasa\utils\common.py", line 71, in set_log_level
    update_tensorflow_log_level()
  File "c:\users\sanjiw jha\appdata\local\programs\python\python37\lib\site-packages\rasa\utils\common.py", line 112, in update_tensorflow_log_level
    import tensorflow as tf
  File "c:\users\sanjiw jha\appdata\local\programs\python\python37\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "c:\users\sanjiw jha\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "c:\users\sanjiw jha\appdata\local\programs\python\python37\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "c:\users\sanjiw jha\appdata\local\programs\python\python37\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "c:\users\sanjiw jha\appdata\local\programs\python\python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "c:\users\sanjiw jha\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "c:\users\sanjiw jha\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "c:\users\sanjiw jha\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "c:\users\sanjiw jha\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "c:\users\sanjiw jha\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "c:\users\sanjiw jha\appdata\local\programs\python\python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "c:\users\sanjiw jha\appdata\local\programs\python\python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.


Failed to load the native TensorFlow runtime.

**Comment by sanjana-coder** [comment]
I've got the same issue...please help me sort this out 
Ive installed rasa..but when i check for the version or use rasa init it throws back an error

(base) D:\PYTHON>rasa --version
Traceback (most recent call last):
  File "d:\anaconda\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "d:\anaconda\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "d:\anaconda\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "d:\anaconda\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "d:\anaconda\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\anaconda\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\ANACONDA\Scripts\rasa.exe\__main__.py", line 7, in <module>
  File "d:\anaconda\lib\site-packages\rasa\__main__.py", line 82, in main
    set_log_level(log_level)
  File "d:\anaconda\lib\site-packages\rasa\utils\common.py", line 71, in set_log_level
    update_tensorflow_log_level()
  File "d:\anaconda\lib\site-packages\rasa\utils\common.py", line 112, in update_tensorflow_log_level
    import tensorflow as tf
  File "d:\anaconda\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "d:\anaconda\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "d:\anaconda\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "d:\anaconda\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "d:\anaconda\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "d:\anaconda\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "d:\anaconda\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "d:\anaconda\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "d:\anaconda\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "d:\anaconda\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "d:\anaconda\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "d:\anaconda\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by michaelbc** [comment]
Make sure you are using Python 3.6.x to 3.8.x, and NOT 3.9.

**Comment by mridulpandey123** [comment]
I'm still facing the same issue kindly help.

**Comment by wochinge** [comment]
@Aniruddha7 @mridulpandey123 Could you please create a new issue with 
- log of the installation
- rasa version
- OS 
- Python version

**Comment by satya319** [comment]
search rasa.exe file and add into your system environment as well as in user environment path. in my case `C:\Users\KUNU\AppData\Roaming\Python\Python38\Scripts`

**Comment by sweta-thakur112** [comment]
facing same issue !

**Comment by iliyas01** [comment]
other way to do it using docker so will be no issues. 
1.make new directory example rasadocker and open terminal or command prompt

2.run following command docker run --user 1000 -v $(pwd):/app rasa/rasa:3.1.0-full init --no-prompt here --user 1000 for no error of user permission ,-v is for volume, pwd is current directory, :/app is volume in docker image , rasa/rasa is rasa docker image with tag 3.1.0-full ,important thing here to create a project we use init
 3.you can see in current folder project required files are added 
4.to play with bot run following command
 `docker run --user 1000 -it -v $(pwd):/app rasa/rasa:3.1.0-full shell` opens shell where bot asks you input

works.glad i found a way other
