### ISSUE TITLE
mattermost connector ssl certificate failed

### ISSUE THREAD

**Issue by mihai-satmarean** [RasaHQ/rasa#3919]
**Rasa version**:
Rasa 1.1.4
**Rasa X version** (if used & relevant):

**Python version**:
3.6
**Operating system** (windows, osx, ...):
linux
**Issue**:
we are using it from a docker container and passing the root cacerts in the container

````
docker run  -p 5005:5005 -p 5055:5055 -v /etc/pki/ca-trust/source/anchors/:/etc/pki/ca-trust/source/anchors/ -v $(pwd):/app rasa:addcert run
````
when trying to use the mattermost connector with an ssl enable mattermost server we get an error about the certificate

**Error (including full traceback)**:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/rasa/core/channels/mattermost.py", line 98, in webhook
    self.url, self.team, self.user, self.pw, self.bot_channel
  File "/usr/local/lib/python3.6/site-packages/rasa/core/channels/mattermost.py", line 27, in __init__
    super(MattermostBot, self).login(user, pw)
  File "/usr/local/lib/python3.6/site-packages/mattermostwrapper/wrapper.py", line 38, in login
    p = requests.post(self.url + '/users/login', data=json.dumps(props))
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='redacted_matteromst_server.com', port=443): Max retries exceeded with url: /api/v4/users/login (Caused by SSLError(SSLError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)'),))
```

**Command or request that led to error**:
```
outgoing hook in mattermost
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```
some steps taken:
following the [answer here](https://stackoverflow.com/a/46241396)

I did 
````

cat Dockerfile
FROM rasa/rasa:latest-full
RUN pip install pyOpenSSL pyasn1 certifi
````

only to get to the next error:

````
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/rasa/core/channels/mattermost.py", line 98, in webhook
    self.url, self.team, self.user, self.pw, self.bot_channel
  File "/usr/local/lib/python3.6/site-packages/rasa/core/channels/mattermost.py", line 27, in __init__
    super(MattermostBot, self).login(user, pw)
  File "/usr/local/lib/python3.6/site-packages/mattermostwrapper/wrapper.py", line 38, in login
    p = requests.post(self.url + '/users/login', data=json.dumps(props))
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 116, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 668, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 668, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 247, in resolve_redirects
    **adapter_kwargs
  File "/usr/local/lib/python3.6/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host=redacted_mattermost_server.com', port=443): Max retries exceeded with url: /api/v4/users/login (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))



/usr/local/lib/python3.6/site-packages/rasa/core/channels/mattermost.py:109: ResourceWarning: unclosed <socket.socket fd=18, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.17.0.2', 43364), raddr=('redacted address', 443)>
  pass
2019-07-03 10:19:16 ERROR    rasa.core.channels.mattermost  - Exception when trying to handle message.HTTPSConnectionPool(host='redacted_mattermost_servers.com', port=443): Max retries exceeded with url: /api/v4/users/login (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
2019-07-03 10:19:16 DEBUG    rasa.core.channels.mattermost  - HTTPSConnectionPool(host='redacted_mattermost_server.com', port=443): Max retries exceeded with url: /api/v4/users/login (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),))
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/contrib/pyopenssl.py", line 472, in wrap_socket
    cnx.do_handshake()
  File "/usr/local/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1915, in do_handshake
    self._raise_ssl_error(self._ssl, result)
  File "/usr/local/lib/python3.6/site-packages/OpenSSL/SSL.py", line 1647, in _raise_ssl_error
    _raise_current_error()
  File "/usr/local/lib/python3.6/site-packages/OpenSSL/_util.py", line 54, in exception_from_error_queue
    raise exception_type(errors)
OpenSSL.SSL.Error: [('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')]

````

**Comment by mihai-satmarean** [comment]
I have to mention that running the container and executing openssl inside it results in correct SSL connection

**Comment by akelad** [comment]
Thanks for raising this issue, @erohmensing  will get back to you about it soon.

**Comment by erohmensing** [comment]
Hm, this is something I haven't seen before... to be clear, have you been able to connect to the mattermost connector from within docker without the ssl enabled? Perhaps it's a general issue with the connection that's stopping the request from being received?

**Comment by mihai-satmarean** [comment]
Hi, thanks for looking into it. 
Our mattermost instance is ssl only, so no possible to connect without ssl.
As stated, the openssl utility from within he container can read and match the certificate.

**Comment by erohmensing** [comment]
I’ve been looking into different places people have run into this error with no real insights. I understand the utility checks whether the certificate matches the private key, but does it also check whether the cert is valid yet? It may be a “dumb check”, but at least 2 people I’ve seen have run into the problem because the machine they’re running on (e.g. vm) has the clock or date wrong and the certificate isn’t valid yet. Anything there?

**Comment by mihai-satmarean** [comment]
Hi, no dumb check here, certificate valid until 2026. self signed certificate you can call it,
we have our own certificate authority running.

This we ran from inside the container
`echo | openssl s_client -servername redactedserver.com -connect redactedserver.com:443 2>/dev/null | openssl x509 -noout -dates


notBefore=Nov  8 14:47:51 2018 GMT
notAfter=Nov  7 14:47:51 2020 GMT`

**Comment by erohmensing** [comment]
Hm, then I'm not sure if its the connector or the CA that's making it not work. You could maybe try a Let's Encrypt certificate (that's what we usually use) and see if you have better luck with that...

**Comment by mihai-satmarean** [comment]
hi,
letsencrypt is not an option for us,
as seen here
http://blog.pengyifan.com/how-to-fix-python-ssl-certificate_verify_failed/ the
problem is the way you call the connection with python, so is the connector
that needs to learn about self signed certificates.
I can help testing
Thanks!

În mar., 9 iul. 2019 la 13:48, Ella Rohm-Ensing <notifications@github.com>
a scris:

**Comment by erohmensing** [comment]
Hm okay. You seem to know much more about this than I do -- would you be interested in looking into this and PRing a fix?

**Comment by mihai-satmarean** [comment]
Hi, the project is very interesting, if not a bit chaotic :), the skill level I might have. I lack the time. All I can offer now is testing.

**Comment by erohmensing** [comment]
Okay. I'll add it to our maintenance inbox we'll get around to this eventually. Let us know if you find more time in the meantime to work on it :)

**Comment by btotharye** [comment]
yea @wochinge agreed I'll take it and add it to my backlog

**Comment by mihai-satmarean** [comment]
some kind of workaround would be beneficial, I got inspired by the new videos masterclass but I cannot continue. thanks!

**Comment by alebeta90** [comment]
Hi friends,

I tested the connection to mattermost using Letsencrypt certificates and I'm facing the same problem.

Running Rasa Docker image 1.5.1-full 

Also tested connection from inside the container and everything seems to be fine using openssl command. Using other channels with letsencrypt for example rocketchat works properly.

If there is more info I could provide please, let me know

thanks

**Comment by btotharye** [comment]
ok thanks for the update, I have this on my radar to tackle soon.

**Comment by m-vdb** [comment]
@mihai-satmarean @alebeta90 I tried to understand what's going on here, and since these are self-signed certificated, we might need to tell the `requests` lib that these are valid. Did you try setting the `REQUESTS_CA_BUNDLE` environment variable like this?

```bash
$ export REQUESTS_CA_BUNDLE=/path/to.cert
```

**Comment by jk** [comment]
Thanks @m-vdb for the idea to set `REQUESTS_CA_BUNDLE`, it works.

> I tried to understand what's going on here, and since these are self-signed certificated, we might need to tell the `requests` lib that these are valid. Did you try setting the `REQUESTS_CA_BUNDLE` environment variable like this?
> 
> ```shell
> $ export REQUESTS_CA_BUNDLE=/path/to.cert
> ```

I've also stumbled here because of the following message in my RASA logfile:

```
Exception when trying to handle message.HTTPSConnectionPool(host='mattermost.[REDACTED]', port=443):
Max retries exceeded with url: /api/v4/posts (Caused by SSLError(SSLCertVerificationError(1, 
'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate 
 (_ssl.c:1131)')))
```

Since I'm starting rasa-core via a systemd unit file, it was easy to set `REQUESTS_CA_BUNDLE` and it did the trick. Now RASA replies to inqueries comming from our internal Mattermost, which is self-signed from our internal CA.

For everyone who wonders how our unit file looks like:
```systemd
[Unit]
Description=Chatbot API
After=multi-user.target
Wants=postgresql-14.service chatbot-actions-server.service

[Service]
Type=simple
Environment="PATH=/opt/rasa/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin"
Environment="PYTHONPATH=/opt/rasa/mycompanu_rasa_components_v3"
Environment="REQUESTS_CA_BUNDLE=/etc/pki/ca-trust/source/anchors/mycompany-root-ca.crt"
WorkingDirectory=/opt/rasa
ExecStart=/opt/rasa/venv/bin/rasa run --enable-api --cors '*' --log-file /var/log/chatbot/chatbot-api.log
User=chatbot
Group=daemon
```

The last remaining issue I've left with the mattermost connector/integration is, that every answer from RASA-core back to Mattermost emits an error about a perfectly fine 201 HTTP response - but that's a story for a seperate issue.
```
 [ERROR]  Failed to send message to mattermost channel [REDACTED]. Response: <Response [201]>
```
