### ISSUE TITLE
utter_attachement causing rasa interactive learning to crash

### ISSUE THREAD

**Issue by andrewrobertday** [RasaHQ/rasa#3945]
**Rasa version**:1.1.3

**Rasa X version** (if used & relevant):

**Python version**: 3.6.7

**Operating system** (windows, osx, ...): ubuntu 18.04

**Issue**: 
Whenever a utter_attachement is dispatched as the out put of an action, interactive learing crashes/.

**Error (including full traceback)**:
```
Traceback (most recent call last):
  File "/home/ubuntu/adam/environments/rasa_x_env/lib/python3.6/site-packages/rasa/core/training/interactive.py", line 1369, in record_messages
    endpoint, sender_id, sender_ids, plot_file
  File "/home/ubuntu/adam/environments/rasa_x_env/lib/python3.6/site-packages/rasa/core/training/interactive.py", line 881, in _predict_till_next_listen
    await _print_history(sender_id, endpoint)
  File "/home/ubuntu/adam/environments/rasa_x_env/lib/python3.6/site-packages/rasa/core/training/interactive.py", line 440, in _print_history
    table = _chat_history_table(events)
  File "/home/ubuntu/adam/environments/rasa_x_env/lib/python3.6/site-packages/rasa/core/training/interactive.py", line 526, in _chat_history_table
    wrapped = wrap(format_bot_output(event), bot_width(table))
  File "/home/ubuntu/adam/environments/rasa_x_env/lib/python3.6/site-packages/rasa/core/training/interactive.py", line 256, in format_bot_output
    output += "\nAttachment: " + data.get("attachment")
TypeError: must be str, not dict
2019-07-05 14:51:58 ERROR    asyncio  - Task exception was never retrieved
future: <Task finished coro=<_serve_application.<locals>.run_interactive_io() done, defined at /home/ubuntu/adam/environments/rasa_x_env/lib/python3.6/site-packages/rasa/core/training/interactive.py:1411> exception=TypeError('must be str, not dict',)>
Traceback (most recent call last):
  File "/home/ubuntu/adam/environments/rasa_x_env/lib/python3.6/site-packages/rasa/core/training/interactive.py", line 1418, in run_interactive_io
    sender_id=uuid.uuid4().hex,
  File "/home/ubuntu/adam/environments/rasa_x_env/lib/python3.6/site-packages/rasa/core/training/interactive.py", line 1369, in record_messages
    endpoint, sender_id, sender_ids, plot_file
  File "/home/ubuntu/adam/environments/rasa_x_env/lib/python3.6/site-packages/rasa/core/training/interactive.py", line 881, in _predict_till_next_listen
    await _print_history(sender_id, endpoint)
  File "/home/ubuntu/adam/environments/rasa_x_env/lib/python3.6/site-packages/rasa/core/training/interactive.py", line 440, in _print_history
    table = _chat_history_table(events)
  File "/home/ubuntu/adam/environments/rasa_x_env/lib/python3.6/site-packages/rasa/core/training/interactive.py", line 526, in _chat_history_table
    wrapped = wrap(format_bot_output(event), bot_width(table))
  File "/home/ubuntu/adam/environments/rasa_x_env/lib/python3.6/site-packages/rasa/core/training/interactive.py", line 256, in format_bot_output
    output += "\nAttachment: " + data.get("attachment")
TypeError: must be str, not dict
```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by akelad** [comment]
Could you please add the code of your action that's causing this?

**Comment by andrewrobertday** [comment]
class SearchProperty(BootstrapAction):

	def name(self):
		return "action_search_property"

	def execute(self, dispatcher, tracker, domain):
		
		# User credentials
		session_id = self.session.session_id
		client_id = self.session.client_id
		channel = self.session.channel

		try:

			# Search property 
			response = {
                        "text":get_response.get_response(channel,'prompt_for_bedrooms'),
                        "last_prompt_topic":"bedrooms"
			}

			dispatcher.utter_attachment(response)

			if response.get("last_prompt_topic") is not None:
				return [SlotSet("last_prompt_topic",response.get("last_prompt_topic"))]
			
			return [SlotSet("move_in_date",tracker.get_slot('time'))]
			
		except Exception as e:

			logger.info(e, exc_info=True) # exc_info will add traceback
			text = "I am unable to find that. Lets try again?"

			dispatcher.utter_message(text)

**Comment by akelad** [comment]
Thanks for raising this issue, @erohmensing  will get back to you about it soon.

**Comment by erohmensing** [comment]
Hey @andrewrobertday, thanks for pointing this out. Looks like we should probably json dump the attachment instead of assuming its a string here 
```
output += "\nAttachment: " + data.get("attachment")
```

Would you be interested in making a contribution to fix it?
