### ISSUE TITLE
Interactive learning fails when the intent name and entity type are the same

### ISSUE THREAD

**Issue by MetcalfeTom** [RasaHQ/rasa#3956]
When dumping NLU data at the end, if there is an entity type that is the same as an intent name, the following error is thrown up:

```bash
2019-07-08 12:51:09 ERROR    rasa.core.training.interactive  - An exception occurred while recording messages.
Traceback (most recent call last):
  File "/Users/tom/Documents/RASA/rasa/rasa/core/training/interactive.py", line 1363, in record_messages
    endpoint, sender_id, sender_ids, plot_file
  File "/Users/tom/Documents/RASA/rasa/rasa/core/training/interactive.py", line 881, in _predict_till_next_listen
    action_name, policy, confidence, predictions, endpoint, sender_id
  File "/Users/tom/Documents/RASA/rasa/rasa/core/training/interactive.py", line 1020, in _validate_action
    is_correct = await _ask_questions(question, sender_id, endpoint)
  File "/Users/tom/Documents/RASA/rasa/rasa/core/training/interactive.py", line 312, in _ask_questions
    should_retry = await _ask_if_quit(sender_id, endpoint)
  File "/Users/tom/Documents/RASA/rasa/rasa/core/training/interactive.py", line 589, in _ask_if_quit
    await _write_data_to_file(sender_id, endpoint)
  File "/Users/tom/Documents/RASA/rasa/rasa/core/training/interactive.py", line 565, in _write_data_to_file
    await _write_nlu_to_file(nlu_path, events)
  File "/Users/tom/Documents/RASA/rasa/rasa/core/training/interactive.py", line 807, in _write_nlu_to_file
    f.write(nlu_data.as_markdown())
  File "/Users/tom/Documents/RASA/rasa/rasa/nlu/training_data/training_data.py", line 134, in as_markdown
    return MarkdownWriter().dumps(self)
  File "/Users/tom/Documents/RASA/rasa/rasa/nlu/training_data/formats/markdown.py", line 206, in dumps
    md += self._generate_training_examples_md(training_data)
  File "/Users/tom/Documents/RASA/rasa/rasa/nlu/training_data/formats/markdown.py", line 219, in _generate_training_examples_md
    key=lambda k: k["intent"],
  File "/Users/tom/Documents/RASA/rasa/rasa/nlu/training_data/formats/markdown.py", line 219, in <lambda>
    key=lambda k: k["intent"],
KeyError: 'intent'
```

An example of what would cause this error:
```
------
Chat History

 #    Bot                            You        
────────────────────────────────────────────────
 1    action_listen                             
────────────────────────────────────────────────
 2                   i want to eat [pizza](food) 
                               intent: food 1.00 
------
```

**Comment by akelad** [comment]
@MetcalfeTom please always add issues to the maintenance board
