### ISSUE TITLE
Encountered an exception while running action 'action_hello_world'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.

### ISSUE THREAD

**Issue by arbazkhan971** [RasaHQ/rasa#3957]
**Rasa version*Rasa 1.1.4*:

**Rasa X version** (if used & relevant):0.19.2

**Python version**:3.7.3

**Operating system** (windows, osx, ...):UBUNTU 19.04

**Issue**:
Traceback (most recent call last):
  File "/home/arbaz/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/arbaz/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/arbaz/anaconda3/lib/python3.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/arbaz/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/arbaz/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/arbaz/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/arbaz/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/arbaz/anaconda3/lib/python3.7/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/home/arbaz/anaconda3/lib/python3.7/site-packages/rasa_sdk/endpoint.py", line 59, in webhook
    response = executor.run(action_call)
  File "/home/arbaz/anaconda3/lib/python3.7/site-packages/rasa_sdk/executor.py", line 237, in run
    "No registered Action found for name '{}'.".format(action_name)
Exception: No registered Action found for name 'action_hello_world'.

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```
action.py file

from typing import Any, Text, Dict, List

from rasa_sdk import Action, Tracker
from rasa_sdk.executor import CollectingDispatcher
from rasa_core_sdk.events import SlotSet

class ActionHelloWorld(Action):

    def name(self):
        return "action_hello_world"
        
    def run(self, dispatcher, tracker, domain):
        dispatcher.utter_message("Hello World!")
        return []

**Comment by psds01** [comment]
Weird, can you try renaming your file to `actions.py`?

**Comment by akelad** [comment]
yeah or specify the module when running the action server -- what command did you use to start it?
