### ISSUE TITLE
IL doesn't have a default endpoints path `endpoints.yml`

### ISSUE THREAD

**Issue by erohmensing** [RasaHQ/rasa#3959]
If I use `rasa shell` with my action server running and duckling server running, everything works as expected. If I use `rasa interactive`, the form action doesn't work .
```
? The bot wants to run 'restaurant_form', correct?  Yes
2019-07-08 16:18:42 ERROR    rasa.core.processor  - Encountered an exception while running action 'restaurant_form'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
------
Chat History
...
------
? The bot wants to run 'utter_slots_values', correct?  (Y/n)
```
There is no information in the action server on debug mode, no `received request to run restaurant_form`, so something is happening so the request doesn't hit the action server.

**Comment by erohmensing** [comment]
Update: from `rasa interactive debug`:
```
2019-07-08 16:22:51 DEBUG    rasa.core.processor  - The model predicted the custom action 'restaurant_form' but you didn't configure an endpoint to run this custom action. Please take a look at the docs and set an endpoint configuration. https://rasa.com/docs/rasa/core/actions
Traceback (most recent call last):
  File "/Users/ella/domain-pr/rasa/core/processor.py", line 439, in _run_action
    events = await action.run(output_channel, nlg, tracker, self.domain)
  File "/Users/ella/domain-pr/rasa/core/actions/action.py", line 389, in run
    "".format(self.name(), DOCS_BASE_URL)
Exception: The model predicted the custom action 'restaurant_form' but you didn't configure an endpoint to run this custom action. Please take a look at the docs and set an endpoint configuration. https://rasa.com/docs/rasa/core/actions
```

So maybe interactive doesn't have an auto-path for endpoints.yml?
