### ISSUE TITLE
ValueError: bad input shape (1, 89)

### ISSUE THREAD

**Issue by abhi2652254** [RasaHQ/rasa#3964]
Rasa NLU version: 0.13.0
Python version: 3.6.7

Operating system: Ubuntu:18.04.2 LTS

Content of model configuration file:

pipeline:
- name: "nlp_spacy"
#  case_sensitive: false
- name: "tokenizer_spacy"

- name: "ner_crf"
  BILOU_flag: true
  features:
    # features for word before token
    - ["low", "title", "upper", "pos", "pos2"]
    # features of token itself
    - ["bias", "low", "word3", "word2", "upper", "title", "digit", "pos", "pos2", "pattern"] 
  max_iterations: 50
  L1_c: 1
  L2_c: 1e-3

- name: "ner_synonyms"
#  language: "fr"

 # epochs: 10
 # batch_size: 4
  #dropout: 0.13

- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_sklearn"

- name: "intent_classifier_tensorflow_embedding"
  intent_tokenization_flag: true
  intent_split_symbol: "+"

"language": "fr"
"spacy_model_name" : "fr_core_news_md"

After I tested the RASA NLU model, I got the following error:

Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/abhi/.local/lib/python3.6/site-packages/rasa_nlu/run.py", line 52, in <module>
    run_cmdline(cmdline_args.model)
  File "/home/abhi/.local/lib/python3.6/site-packages/rasa_nlu/run.py", line 42, in run_cmdline
    r = interpreter.parse(text)
  File "/home/abhi/.local/lib/python3.6/site-packages/rasa_nlu/model.py", line 357, in parse
    component.process(message, **self.context)
  File "/home/abhi/.local/lib/python3.6/site-packages/rasa_nlu/classifiers/sklearn_intent_classifier.py", line 172, in process
    intents = self.transform_labels_num2str(intent_ids)
  File "/home/abhi/.local/lib/python3.6/site-packages/rasa_nlu/classifiers/sklearn_intent_classifier.py", line 108, in transform_labels_num2str
    return self.le.inverse_transform(y)
  File "/home/abhi/.local/lib/python3.6/site-packages/sklearn/preprocessing/label.py", line 273, in inverse_transform
    y = column_or_1d(y, warn=True)
  File "/home/abhi/.local/lib/python3.6/site-packages/sklearn/utils/validation.py", line 760, in column_or_1d
    raise ValueError("bad input shape {0}".format(shape))
ValueError: bad input shape (1, 89)

Although, with reference to issue "https://github.com/RasaHQ/rasa/issues/1436", I have the version of scikit-learn (0.21.2).

Can anyone please help me out to point out the mistake I am overlooking ? Thanks in advance.

**Comment by akelad** [comment]
Please ask these kind of questions in our [forum](https://forum.rasa.com)
