### ISSUE TITLE
"Expected string or bytes-like object" during interactive learning

### ISSUE THREAD

**Issue by msamogh** [RasaHQ/rasa#3970]
**Rasa version**: 1.0.2

**Rasa X version** (if used & relevant):

**Python version**: 3.7.2

**Operating system** (windows, osx, ...): OSX

**Issue**:
I created a bot using `rasa init`, and ran `rasa interactive`, during which I entered the following messages (all the while confirming the predictions).
- Hi
- I'm doing great
- I'm not doing great

**Error (including full traceback)**:
At this point, I get the following error:
```python
2019-07-09 22:20:10 ERROR    rasa.core.training.interactive  - An exception occurred while recording messages.
Traceback (most recent call last):
  File "/Users/amogh/rasa/hack/interactive-exc/lib/python3.7/site-packages/rasa/core/training/interactive.py", line 1370, in record_messages
    endpoint, sender_id, finetune, sender_ids, plot_file
  File "/Users/amogh/rasa/hack/interactive-exc/lib/python3.7/site-packages/rasa/core/training/interactive.py", line 883, in _predict_till_next_listen
    sender_ids, plot_file, endpoint, unconfirmed=[ActionExecuted(action_name)]
  File "/Users/amogh/rasa/hack/interactive-exc/lib/python3.7/site-packages/rasa/core/training/interactive.py", line 1295, in _plot_trackers
    event_sequences[-1], event_sequences, output_file=None, max_history=2
  File "/Users/amogh/rasa/hack/interactive-exc/lib/python3.7/site-packages/rasa/core/training/visualization.py", line 467, in visualize_neighborhood
    else sanitize(message.get("intent", {})).get("name", "  ?  "),
  File "/Users/amogh/rasa/hack/interactive-exc/lib/python3.7/site-packages/rasa/core/training/visualization.py", line 364, in sanitize
    return re.sub(r"""[&\\\<\>"'%();+]""", "", s)
  File "/Users/amogh/rasa/hack/interactive-exc/lib/python3.7/re.py", line 192, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
2019-07-09 22:20:10 ERROR    asyncio  - Task exception was never retrieved
future: <Task finished coro=<_serve_application.<locals>.run_interactive_io() done, defined at /Users/amogh/rasa/hack/interactive-exc/lib/python3.7/site-packages/rasa/core/training/interactive.py:1412> exception=TypeError('expected string or bytes-like object')>
Traceback (most recent call last):
  File "/Users/amogh/rasa/hack/interactive-exc/lib/python3.7/site-packages/rasa/core/training/interactive.py", line 1420, in run_interactive_io
    sender_id=uuid.uuid4().hex,
  File "/Users/amogh/rasa/hack/interactive-exc/lib/python3.7/site-packages/rasa/core/training/interactive.py", line 1370, in record_messages
    endpoint, sender_id, finetune, sender_ids, plot_file
  File "/Users/amogh/rasa/hack/interactive-exc/lib/python3.7/site-packages/rasa/core/training/interactive.py", line 883, in _predict_till_next_listen
    sender_ids, plot_file, endpoint, unconfirmed=[ActionExecuted(action_name)]
  File "/Users/amogh/rasa/hack/interactive-exc/lib/python3.7/site-packages/rasa/core/training/interactive.py", line 1295, in _plot_trackers
    event_sequences[-1], event_sequences, output_file=None, max_history=2
  File "/Users/amogh/rasa/hack/interactive-exc/lib/python3.7/site-packages/rasa/core/training/visualization.py", line 467, in visualize_neighborhood
    else sanitize(message.get("intent", {})).get("name", "  ?  "),
  File "/Users/amogh/rasa/hack/interactive-exc/lib/python3.7/site-packages/rasa/core/training/visualization.py", line 364, in sanitize
    return re.sub(r"""[&\\\<\>"'%();+]""", "", s)
  File "/Users/amogh/rasa/hack/interactive-exc/lib/python3.7/re.py", line 192, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
```

**Domain and Training Data**
The content of my domain and training data is the standard one from `rasa init`.

**Comment by psds01** [comment]
Can't reproduce the error, works normally for me for `rasa==1.1.4`.
![Screenshot from 2019-07-10 02-47-07](https://user-images.githubusercontent.com/49634935/60923800-4fa14b00-a2bd-11e9-81d2-bf35bc075e86.png)

**Comment by msamogh** [comment]
Yes, this seems to be specific to `1.0.2`.
