### ISSUE TITLE
Failed to run pip3 install -r requirements-docs.txt 

### ISSUE THREAD

**Issue by nisanth456** [RasaHQ/rasa#3986]
Running command git clone -q https://github.com/RasaHQ/sphinxcontrib-versioning.git /tmp/pip-install-ivtrfrus/sphinxcontrib-versioning
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/data/RasaChatBot/myenv/lib/python3.6/site-packages/setuptools/__init__.py", line 18, in <module>
        import setuptools.version
      File "/data/RasaChatBot/myenv/lib/python3.6/site-packages/setuptools/version.py", line 1, in <module>
        import pkg_resources
      File "/data/RasaChatBot/myenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2927, in <module>
        @_call_aside
      File "/data/RasaChatBot/myenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2913, in _call_aside
        f(*args, **kwargs)
      File "/data/RasaChatBot/myenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2952, in _initialize_master_working_set
        add_activation_listener(lambda dist: dist.activate())
      File "/data/RasaChatBot/myenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 956, in subscribe
        callback(dist)
      File "/data/RasaChatBot/myenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2952, in <lambda>
        add_activation_listener(lambda dist: dist.activate())
      File "/data/RasaChatBot/myenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2515, in activate
        declare_namespace(pkg)
      File "/data/RasaChatBot/myenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2097, in declare_namespace
        _handle_ns(packageName, path_item)
      File "/data/RasaChatBot/myenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2047, in _handle_ns
        _rebuild_mod_path(path, packageName, module)
      File "/data/RasaChatBot/myenv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2066, in _rebuild_mod_path
        orig_path.sort(key=position_in_sys_path)
    AttributeError: '_NamespacePath' object has no attribute 'sort'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-ivtrfrus/sphinxcontrib-versioning/

**Comment by federicotdn** [comment]
Hi @nisanth456, have you tried upgrading `setuptools` first?
```
pip3 install --upgrade setuptools
```

**Comment by akelad** [comment]
@nisanth456 please either open an issue with the correct template if you think this is a bug, otherwise please ask usage questions in the [forum](https://forum.rasa.com)
