### ISSUE TITLE
Cannot overwrite ActionRevertFallbackEvents 

### ISSUE THREAD

**Issue by MichaelMarien** [RasaHQ/rasa#4000]
**Rasa version**:  0.14.5
**Rasa SDK**:  0.14.0

**Python version**: 3.6

**Operating system**: RHEL7 (CentOs)

**Issue**: To overcome the issue described in https://forum.rasa.com/t/two-stage-fallback-policy-sms-voice/9880/2 we were considering to overwrite the ActionRevertFallbackEvents  action. However, due to incompatibility between the DialogueStateTracker and the Tracker class of the SDK this is not possible. 

It feels like all functionalities needed to run the default actions in rasa.core.actions should be also available in the sdk tracker? 

We are currently still using the older Rasa version in production due to migration issues. However after checking the relevant pieces of code in the latest release, this issue is still present.

**Error (including full traceback)**:
```
Traceback (most recent call last):
  File "/home/.conda/envs/rasa/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/.conda/envs/rasa/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/.conda/envs/rasa/lib/python3.6/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/.conda/envs/rasa/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/.conda/envs/rasa/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/.conda/envs/rasa/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/.conda/envs/rasa/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/.conda/envs/rasa/lib/python3.6/site-packages/flask_cors/decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "/home/.conda/envs/rasa/lib/python3.6/site-packages/rasa_core_sdk/endpoint.py", line 59, in webhook
    response = executor.run(action_call)
  File "/home/.conda/envs/rasa/lib/python3.6/site-packages/rasa_core_sdk/executor.py", line 185, in run
    events = action(dispatcher, tracker, domain)
  File "/data/cases/sada-chatbot-live/ya1-action-server/src/main/python/actions/policy_actions.py", line 98, in run
    if has_user_rephrased(tracker):
  File "/home/.conda/envs/rasa/lib/python3.6/site-packages/rasa_core/policies/two_stage_fallback.py", line 22, in has_user_rephrased
    return tracker.last_executed_action_has(ACTION_DEFAULT_ASK_REPHRASE_NAME)
AttributeError: 'Tracker' object has no attribute 'last_executed_action_has'
```

**Command or request that led to error**:
```
Executing the action ActionRevertFallbackEvents on the action server, even without making changes.
```

**Comment by akelad** [comment]
Thanks for raising this issue, @wochinge  will get back to you about it soon.

**Comment by wochinge** [comment]
@MichaelMarien I replied to you in the forum regarding the issue with the TwoStageFallbackPolicy. I think it's best if we continue the discussion about the usage of the policy there.

Regarding the different `Tracker` implementations in `rasa` and `rasa-sdk`:
1) I totally understand that this is confusing. We are currently discussing it in the team, how can make the difference more obvious. I will link this issue to the ongoing discussion. However, the current plan is not to keep these two classes synchronized, since `rasa` and `rasa-sdk` are two different packages in the end. This is also why I'd label this issue as `wontfix`
2) You can implement the same logic yourself, but I actually don't think you need this (see my answer in the forum).
