### ISSUE TITLE
Errors using `rasa test`

### ISSUE THREAD

**Issue by btburton42** [RasaHQ/rasa#4017]
**Rasa version**:
1.1.4

**Python version**:
3.7.3

**Operating system** (windows, osx, ...):
Mac OS 10.14.5

**Issue**:
Attempting to run e2e evaluation fails on stories that aren't explicitly replicated in the NLU.

**Error (including full traceback)**:
```
2019-07-09 10:56:21 INFO     rasa.nlu.test  - Confusion matrix, without normalization:
[[1 0]
 [1 0]]
Traceback (most recent call last):
  File "/Users/a1451195/anaconda3/bin/rasa", line 10, in <module>
    sys.exit(main())
  File "/Users/a1451195/anaconda3/lib/python3.7/site-packages/rasa/__main__.py", line 70, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/Users/a1451195/anaconda3/lib/python3.7/site-packages/rasa/cli/test.py", line 147, in test
    test_core(args)
  File "/Users/a1451195/anaconda3/lib/python3.7/site-packages/rasa/cli/test.py", line 85, in test_core
    kwargs=vars(args),
  File "/Users/a1451195/anaconda3/lib/python3.7/site-packages/rasa/test.py", line 102, in test_core
    rasa.core.test(stories, _agent, out_directory=output, **kwargs)
  File "uvloop/loop.pyx", line 1451, in uvloop.loop.Loop.run_until_complete
  File "/Users/a1451195/anaconda3/lib/python3.7/site-packages/rasa/core/test.py", line 514, in test
    log_failed_stories(story_evaluation.failed_stories, out_directory)
  File "/Users/a1451195/anaconda3/lib/python3.7/site-packages/rasa/core/test.py", line 470, in log_failed_stories
    f.write(failure.export_stories())
  File "/Users/a1451195/anaconda3/lib/python3.7/site-packages/rasa/core/trackers.py", line 434, in export_stories
    return story.as_story_string(flat=True, e2e=e2e)
  File "/Users/a1451195/anaconda3/lib/python3.7/site-packages/rasa/core/training/structures.py", line 376, in as_story_string
    story_content += step.as_story_string(flat, e2e)
  File "/Users/a1451195/anaconda3/lib/python3.7/site-packages/rasa/core/training/structures.py", line 183, in as_story_string
    result += self._user_string(s, e2e)
  File "/Users/a1451195/anaconda3/lib/python3.7/site-packages/rasa/core/training/structures.py", line 137, in _user_string
    return "* {}{}\n".format(prefix, story_step_element.as_story_string(e2e))
  File "/Users/a1451195/anaconda3/lib/python3.7/site-packages/rasa/core/test.py", line 171, in as_story_string
    correct_message = md_format_message(self.text, self.intent, self.entities)
  File "/Users/a1451195/anaconda3/lib/python3.7/site-packages/rasa/core/events/__init__.py", line 58, in md_format_message
    "entities": deserialised_entities,
  File "/Users/a1451195/anaconda3/lib/python3.7/site-packages/rasa/nlu/training_data/formats/markdown.py", line 293, in _generate_message_md
    entities = sorted(message.get("entities", []), key=lambda k: k["start"])
  File "/Users/a1451195/anaconda3/lib/python3.7/site-packages/rasa/nlu/training_data/formats/markdown.py", line 293, in <lambda>
    entities = sorted(message.get("entities", []), key=lambda k: k["start"])
KeyError: 'start'
```

**Command or request that led to error**:
```
rasa test --stories e2e_stories.md --e2e
```

**Content of configuration file (config.yml)** (if relevant):
```yml
language: en

pipeline: supervised_embeddings

policies:
- name: MemoizationPolicy
- name: KerasPolicy
- name: MappingPolicy
```

**Content of domain file (nlu.md)** (if relevant):
```md
## intent:TechSupportIssue

- [change](Issue) my [default](SubIssue) [browser](Product)

- My [computer](Product) is too [slow](Issue)

- My [printer](Product) [won't print](Issue)

- how to [fix](Issue) my [router](Product)

## synonym:internet

- browser
```

**Content of domain file (stories.md)** (if relevant):
```md
## quick path
* TechSupportIssue
    - utter_tech_support_issue

## Generated Story -4339791933908113526
* TechSupportIssue{"Product": "phone", "issue": "won't turn on"}
    - slot{"Product": "phone"}
    - utter_tech_support_issue
```

**Content of domain file (e2e_stories.md)** (if relevant):
```md
## e to e story 1
* TechSupportIssue: My [internet](Product) was working [yesterday](date) but then I unplugged it and now it is [slow](Issue)
    - utter_tech_support_issue
```

Reference to this issue can be found in the forums at:
https://forum.rasa.com/t/errors-using-rasa-test/12698/3
https://forum.rasa.com/t/problem-with-rasa-test/12448/3

**Comment by akelad** [comment]
Thanks for raising this issue, @MetcalfeTom  will get back to you about it soon.

**Comment by MetcalfeTom** [comment]
Thanks for bringing this to our attention, I've begun working on a fix [here](https://github.com/RasaHQ/rasa/pull/4033)
