### ISSUE TITLE
Training fails when story file has multi-line comment

### ISSUE THREAD

**Issue by msamogh** [RasaHQ/rasa#4053]
**Rasa version**:
1.1.6

**Rasa X version** (if used & relevant):

**Python version**:
3.7

**Operating system** (windows, osx, ...):
OSX

**Issue**:
Training (parsing) fails with 
```bash
(interactive-learning-3648) ➜  demo-bot-2 git:(master) ✗ rasa train
Training Core model...
2019-07-19 19:22:30 WARNING  rasa.core.training.dsl  - Skipping line 1. No valid command found. Line Content: '<!-- Without checkpoints'
2019-07-19 19:22:30 WARNING  rasa.core.training.dsl  - Skipping line 2. No valid command found. Line Content: 'several lines'
2019-07-19 19:22:30 ERROR    rasa.core.training.dsl  - Error in line 3: Failed to handle event '->'. There is no started story block available. 
Traceback (most recent call last):
  File "/Users/amogh/rasa/rasa/rasa/core/training/dsl.py", line 294, in process_lines
    self.add_event(event_name, parameters)
  File "/Users/amogh/rasa/rasa/rasa/core/training/dsl.py", line 424, in add_event
    "".format(event_name)
rasa.core.exceptions.StoryParseError: Failed to handle event '->'. There is no started story block available. 
2019-07-19 19:22:30 ERROR    rasa.core.training.dsl  - Invalid story file format. Failed to parse '/var/folders/87/pnn5hwg11cb8qkgp_q4dm8280000gp/T/tmplziahduf/9a00ac605da944e889d2c45513b64f7e_stories.md'
Traceback (most recent call last):
  File "/Users/amogh/rasa/rasa/rasa/core/training/dsl.py", line 294, in process_lines
    self.add_event(event_name, parameters)
  File "/Users/amogh/rasa/rasa/rasa/core/training/dsl.py", line 424, in add_event
    "".format(event_name)
rasa.core.exceptions.StoryParseError: Failed to handle event '->'. There is no started story block available. 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/amogh/rasa/rasa/rasa/core/training/dsl.py", line 214, in read_from_file
    return await reader.process_lines(lines)
  File "/Users/amogh/rasa/rasa/rasa/core/training/dsl.py", line 313, in process_lines
    raise ValueError(msg)
ValueError: Error in line 3: Failed to handle event '->'. There is no started story block available. 
Traceback (most recent call last):
  File "/Users/amogh/rasa/rasa/rasa/core/training/dsl.py", line 294, in process_lines
    self.add_event(event_name, parameters)
  File "/Users/amogh/rasa/rasa/rasa/core/training/dsl.py", line 424, in add_event
    "".format(event_name)
rasa.core.exceptions.StoryParseError: Failed to handle event '->'. There is no started story block available. 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/amogh/rasa/issues/github/interactive-learning-3648/bin/rasa", line 11, in <module>
    load_entry_point('rasa', 'console_scripts', 'rasa')()
  File "/Users/amogh/rasa/rasa/rasa/__main__.py", line 76, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/Users/amogh/rasa/rasa/rasa/cli/train.py", line 77, in train
    kwargs=extract_additional_arguments(args),
  File "/Users/amogh/rasa/rasa/rasa/train.py", line 42, in train
    kwargs=kwargs,
  File "uvloop/loop.pyx", line 1451, in uvloop.loop.Loop.run_until_complete
  File "/Users/amogh/rasa/rasa/rasa/train.py", line 100, in train_async
    kwargs,
  File "/Users/amogh/rasa/rasa/rasa/train.py", line 203, in _train_async_internal
    kwargs=kwargs,
  File "/Users/amogh/rasa/rasa/rasa/train.py", line 242, in _do_training
    kwargs=kwargs,
  File "/Users/amogh/rasa/rasa/rasa/train.py", line 377, in _train_core_with_validated_data
    kwargs=kwargs,
  File "/Users/amogh/rasa/rasa/rasa/core/train.py", line 58, in train
    stories_file, exclusion_percentage=exclusion_percentage, **data_load_args
  File "/Users/amogh/rasa/rasa/rasa/core/agent.py", line 623, in load_data
    exclusion_percentage=exclusion_percentage,
  File "/Users/amogh/rasa/rasa/rasa/core/training/__init__.py", line 49, in load_data
    resource_name, domain, exclusion_percentage=exclusion_percentage
  File "/Users/amogh/rasa/rasa/rasa/core/training/__init__.py", line 29, in extract_story_graph
    exclusion_percentage=exclusion_percentage,
  File "/Users/amogh/rasa/rasa/rasa/core/training/dsl.py", line 186, in read_from_folder
    f, domain, interpreter, template_variables, use_e2e
  File "/Users/amogh/rasa/rasa/rasa/core/training/dsl.py", line 214, in read_from_file
    return await reader.process_lines(lines)
  File "/Users/amogh/rasa/rasa/rasa/core/training/dsl.py", line 313, in process_lines
    raise ValueError(msg)
ValueError: ("Error in line 3: Failed to handle event '->'. There is no started story block available. ", "Invalid story file format. Failed to parse '/var/folders/87/pnn5hwg11cb8qkgp_q4dm8280000gp/T/tmplziahduf/9a00ac605da944e889d2c45513b64f7e_stories.md'")
```

My only story files is as follows:
```md
<!-- Without checkpoints
several lines
-->
## happy path
* greet
  - utter_greet
* mood_great
  - utter_happy

## sad path
* greet
  - utter_greet
* mood_unhappy
  - utter_cheer_up
  - utter_did_that_help

## sad path 2
* greet
  - utter_greet
* mood_unhappy
  - utter_cheer_up
  - utter_did_that_help
* deny
  - utter_goodbye
```

**Comment by erohmensing** [comment]
the most likely relevant method:
https://github.com/RasaHQ/rasa/blob/master/rasa/core/training/dsl.py#L294
