### ISSUE TITLE
Rasa X does not start (timeout fetching model)

### ISSUE THREAD

**Issue by seif-s3** [RasaHQ/rasa#4068]
**Rasa version**: 1.0.9

**Rasa X version** (if used & relevant): 1.0.9

**Python version**: 3.6

**Operating system** (windows, osx, ...): OSX 10.14.5

**Issue**:
I cannot start Rasa X in an already existing project. I tried also starting it in a new project but I get the same error. 

**Error (including full traceback)**:
```
rasa x --debug
2019-07-22 00:27:05 DEBUG    rasa.cli.utils  - Parameter 'endpoints' not set. Using default location 'endpoints.yml' instead.
Starting Rasa X in local mode... 🚀
2019-07-22 00:27:05 DEBUG    sanic_jwt.configuration  - validating provided secret
2019-07-22 00:27:05 DEBUG    sanic_jwt.configuration  - validating keys (if needed)
2019-07-22 00:27:05 DEBUG    sanic_jwt.configuration  - loading secret and/or keys (if needed)
2019-07-22 00:27:09 DEBUG    rasa.cli.utils  - Parameter 'credentials' not set. Using default location 'credentials.yml' instead.
2019-07-22 00:27:09 DEBUG    rasa.core.utils  - Available web server routes:
/conversations/<conversation_id>/messages          POST                           add_message
/conversations/<conversation_id>/tracker/events    POST                           append_event
/webhooks/rasa                                     GET                            custom_webhook_RasaChatInput.health
/webhooks/rasa/webhook                             POST                           custom_webhook_RasaChatInput.receive
/webhooks/rest                                     GET                            custom_webhook_RestInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_RestInput.receive
/model/test/intents                                POST                           evaluate_intents
/model/test/stories                                POST                           evaluate_stories
/conversations/<conversation_id>/execute           POST                           execute_action
/domain                                            GET                            get_domain
/                                                  GET                            hello
/model                                             PUT                            load_model
/model/parse                                       POST                           parse
/conversations/<conversation_id>/predict           POST                           predict
/conversations/<conversation_id>/tracker/events    PUT                            replace_events
/conversations/<conversation_id>/story             GET                            retrieve_story
/conversations/<conversation_id>/tracker           GET                            retrieve_tracker
/status                                            GET                            status
/model/predict                                     POST                           tracker_predict
/model/train                                       POST                           train
/model                                             DELETE                         unload_model
/version                                           GET                            version
2019-07-22 00:27:09 INFO     root  - Starting Rasa Core server on http://localhost:5005
2019-07-22 00:27:09 INFO     root  - Enabling coroutine debugging. Loop id 5170688024.
2019-07-22 00:27:09 DEBUG    root  - Could not load interpreter from 'None'
2019-07-22 00:27:09 DEBUG    rasa.core.tracker_store  - Attempting to connect to database via "sqlite:///tracker.db"
2019-07-22 00:27:09 DEBUG    rasa.core.tracker_store  - Connection to SQL database 'tracker.db' successful
2019-07-22 00:27:09 DEBUG    rasa.core.agent  - Requesting model from server http://localhost:5002/api/projects/default/models/tags/production...
Traceback (most recent call last):
  File "/Users/seif/anaconda2/envs/thesis/lib/python3.6/site-packages/rasa/cli/x.py", line 318, in run_locally
    local.main(args, project_path, args.data, token=rasa_x_token)
  File "/Users/seif/anaconda2/envs/thesis/lib/python3.6/site-packages/rasax/community/local.py", line 194, in main
    session)
  File "/Users/seif/anaconda2/envs/thesis/lib/python3.6/site-packages/rasax/community/local.py", line 153, in _initialize_with_local_data
    model_service.discover_models_on_init()
  File "/Users/seif/anaconda2/envs/thesis/lib/python3.6/site-packages/rasax/community/services/model_service.py", line 337, in discover_models_on_init
    loop.run_until_complete(self._discover_models())
  File "uvloop/loop.pyx", line 1451, in uvloop.loop.Loop.run_until_complete
  File "/Users/seif/anaconda2/envs/thesis/lib/python3.6/site-packages/rasax/community/services/model_service.py", line 355, in _discover_models
    minimum_version = await self.minimum_compatible_version()
  File "/Users/seif/anaconda2/envs/thesis/lib/python3.6/site-packages/rasax/community/services/model_service.py", line 348, in minimum_compatible_version
    info = await stack_service.status()
  File "/Users/seif/anaconda2/envs/thesis/lib/python3.6/site-packages/rasax/community/services/stack_service.py", line 147, in status
    subpath="/version", method="get")
  File "/Users/seif/anaconda2/envs/thesis/lib/python3.6/site-packages/rasax/community/services/stack_service.py", line 118, in request
    **kwargs) as resp:
  File "/Users/seif/anaconda2/envs/thesis/lib/python3.6/site-packages/aiohttp/client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "/Users/seif/anaconda2/envs/thesis/lib/python3.6/site-packages/aiohttp/client.py", line 575, in _request
    break
  File "/Users/seif/anaconda2/envs/thesis/lib/python3.6/site-packages/aiohttp/helpers.py", line 585, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError

Sorry, something went wrong (see error above). Make sure to start Rasa X with valid data and valid domain and config files. Please, also check any warnings that popped up.
If you need help fixing the issue visit our forum: https://forum.rasa.com/.
```

**Command or request that led to error**:
```
rasa init
rasa x --debug
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by akelad** [comment]
Thanks for raising this issue, @ricwo  will get back to you about it soon.

**Comment by ricwo** [comment]
Hi @seif-s3, which version of rasa X are you running?

**Comment by TatianaParshina** [comment]
I have the same error.
Rasa X version: 0.19.5
OS: Windows 8

**Comment by glitch-control** [comment]
hey @ricwo was the error solved ?

**Comment by rakib06** [comment]
I'm facing the same issue

**Comment by SmitTailor** [comment]
#4068

![image](https://user-images.githubusercontent.com/88365586/127965529-a98aaf77-56c1-4895-8857-0d31487daea3.png)

After installing Rasa. I run this command **rasa init**. It's working fine. But when I am trying to run this command **rasa x** it throws an error as shown in the above image(link).  One of the solutions I've heard that to remove **domain_path=domain_path** from **x.py** file which can be found in such a path: C:\Users\Admin\anaconda3\envs\Myenv\Lib\site-packages\rasa\cli\x,py. But still, I can't get rid of it. If anybody has a solution, please help.
