### ISSUE TITLE
rasa init not working 

### ISSUE THREAD

**Issue by ValeriuOlar** [RasaHQ/rasa#4124]
**Rasa version**:

**Rasa X version** (if used & relevant):
Last -v
**Python version 3.6.0

**Operating system** (windows, ):

**Issue**:

After installing RASA on my win10 machine, i have tried to start a new project, from cmd: rasa init

Is giving me the below error, if anyone can help it would be great. thanks 

**Error (including full traceback)**:
```
Traceback (most recent call last):
  File "C:\Users\valeriu.olariu\AppData\Local\Programs\Python\Python36\Scripts\rasa-script.py", line 11, in <module>
    load_entry_point('rasa', 'console_scripts', 'rasa')()
  File "c:\users\valeriu.olariu\openjaw\rasa t\rasa\rasa\__main__.py", line 69, in main
    set_log_level(log_level)
  File "c:\users\valeriu.olariu\openjaw\rasa t\rasa\rasa\utils\common.py", line 68, in set_log_level
    update_tensorflow_log_level()
  File "c:\users\valeriu.olariu\openjaw\rasa t\rasa\rasa\utils\common.py", line 87, in update_tensorflow_log_level
    import tensorflow as tf
  File "c:\users\valeriu.olariu\appdata\local\programs\python\python36\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "c:\users\valeriu.olariu\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "c:\users\valeriu.olariu\appdata\local\programs\python\python36\lib\site-packages\tensorflow\core\framework\graph_pb2.py", line 6, in <module>
    from google.protobuf import descriptor as _descriptor
  File "c:\users\valeriu.olariu\appdata\local\programs\python\python36\lib\site-packages\google\protobuf\descriptor.py", line 47, in <module>
    from google.protobuf.pyext import _message
ImportError: DLL load failed: The specified procedure could not be found.
```

**Command or request that led to error**:
```
rasa init
```

**Content of configuration file (config.yml)** (if relevant):
```yml
N/A
```

**Content of domain file (domain.yml)** (if relevant):
```yml
N/A
```

**Comment by AllBecomesGood** [comment]
What does 
rasa --version 
return?

**Comment by ValeriuOlar** [comment]
Is  rasa==1.1.8

**Comment by AllBecomesGood** [comment]
That means at least something's working! I don't know what the problem is, but while waiting for someone you should try Anaconda & make a virtual environment rather than using it in a system wide fashion, as this has the high chance of different versions of different things all messing with each other. That's what I do on win10 and it works like a charm, and I can have all different python versions and things per virtual environment without them messing with each other.

**Comment by msamogh** [comment]
Thanks for raising this issue, @tabergma will get back to you about it soon.

**Comment by ValeriuOlar** [comment]
Thanks @msamogh, would be great if you can point me in the right direction as i have seen that there were other users with this bug.

**Comment by tabergma** [comment]
@ValeriuOlar Sorry, for the late reply. Did you managed to get it working? Did you try to update to the latest rasa version?

**Comment by ValeriuOlar** [comment]
Hi @tabergma,

I have not manage to get it work on my local win10 env or on docker container, It was the latest version. I am now using an AWS vm is working. Thanks.

**Comment by TharushaKarunasinghe** [comment]
how did u manage it. same error occured
