### ISSUE TITLE
Checking for data files is prone to decoding errors

### ISSUE THREAD

**Issue by MetcalfeTom** [RasaHQ/rasa#4126]
Especially `True` in the case of the `SkillSelector`, where we check every file in `imports` for nlu/story data

```
Traceback (most recent call last):
 File "\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
   "__main__", mod_spec)
 File "\AppData\Local\Continuum\anaconda3\lib\runpy.py", line 85, in _run_code
   exec(code, run_globals)
 File "\Desktop\DS Projects\newRasa\Scripts\rasa.exe\__main__.py", line 9, in <module>
 File "\desktop\ds projects\newrasa\lib\site-packages\rasa\__main__.py", line 70, in main
   cmdline_arguments.func(cmdline_arguments)
 File "\desktop\ds projects\newrasa\lib\site-packages\rasa\cli\train.py", line 69, in train
   kwargs=extract_additional_arguments(args),
 File "\desktop\ds projects\newrasa\lib\site-packages\rasa\train.py", line 48, in train
   kwargs=kwargs,
 File "\AppData\Local\Continuum\anaconda3\lib\asyncio\base_events.py", line 468, in run_until_complete
   return future.result()
 File "\desktop\ds projects\newrasa\lib\site-packages\rasa\train.py", line 91, in train_async
   training_files, skill_imports
 File "\desktop\ds projects\newrasa\lib\site-packages\rasa\data.py", line 67, in get_core_nlu_directories
   story_files, nlu_data_files = get_core_nlu_files(paths, skill_imports)
 File "\desktop\ds projects\newrasa\lib\site-packages\rasa\data.py", line 114, in get_core_nlu_files
   path, skill_imports
 File "\desktop\ds projects\newrasa\lib\site-packages\rasa\data.py", line 139, in _find_core_nlu_files_in_directory
   if _is_nlu_file(full_path):
 File "\desktop\ds projects\newrasa\lib\site-packages\rasa\data.py", line 157, in _is_nlu_file
   content = io_utils.read_json_file(file_path)
 File "\desktop\ds projects\newrasa\lib\site-packages\rasa\utils\io.py", line 128, in read_json_file
   return json.load(f)
 File "\AppData\Local\Continuum\anaconda3\lib\json\__init__.py", line 296, in load
   return loads(fp.read(),
 File "\AppData\Local\Continuum\anaconda3\lib\encodings\cp1252.py", line 23, in decode
   return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 3984: character maps to <undefined>
```

**Comment by wochinge** [comment]
@MetcalfeTom I believe this is fixed now with  this approach https://github.com/RasaHQ/rasa/blob/3a60b930c4af46fe768c2ea495cadb0afa82a578/rasa/data.py#L137

**Comment by wochinge** [comment]
@MetcalfeTom
