### ISSUE TITLE
Telegram channel broken in latest update

### ISSUE THREAD

**Issue by selphe** [RasaHQ/rasa#4128]
**Rasa version**:
rasa/rasa:latest-full from docker-hub
https://hub.docker.com/r/rasa/rasa/builds
(https://github.com/RasaHQ/rasa/tree/f3480aa384740c58d4b98f6498938faecf39bbe1)

**Python version**:
3.6

**Operating system** (windows, osx, ...):
docker

**Issue**:
After latest update rasa can't start up with telegram connector.

**Error (including full traceback)**:
```
rasa_1  | 2019-07-30 03:32:07 DEBUG    telegram.vendor.ptb_urllib3.urllib3.connectionpool  - https://api.telegram.org:443 "POST /bot<cut>/setWebhook HTTP/1.1" 429 109
rasa_1  | Traceback (most recent call last):
rasa_1  |   File "/usr/local/bin/rasa", line 10, in <module>
rasa_1  |     sys.exit(main())
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/__main__.py", line 76, in main
rasa_1  |     cmdline_arguments.func(cmdline_arguments)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/cli/run.py", line 88, in run
rasa_1  |     rasa.run(**vars(args))
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/run.py", line 55, in run
rasa_1  |     **kwargs
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/run.py", line 165, in serve_application
rasa_1  |     log_file=log_file,
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/run.py", line 106, in configure_app
rasa_1  |     rasa.core.channels.channel.register(input_channels, app, route=route)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/channels/channel.py", line 72, in register
rasa_1  |     app.blueprint(channel.blueprint(handler), url_prefix=p)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/channels/telegram.py", line 242, in blueprint
rasa_1  |     out_channel.setWebhook(self.webhook_url)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/telegram/bot.py", line 65, in decorator
rasa_1  |     result = func(self, *args, **kwargs)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/telegram/bot.py", line 2070, in set_webhook
rasa_1  |     result = self._request.post(url_, data, timeout=timeout)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/telegram/utils/request.py", line 309, in post
rasa_1  |     headers={'Content-Type': 'application/json'})
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/telegram/utils/request.py", line 216, in _request_wrapper
rasa_1  |     message = self._parse(resp.data)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/telegram/utils/request.py", line 174, in _parse
rasa_1  |     raise RetryAfter(retry_after)
rasa_1  | telegram.error.RetryAfter: Flood control exceeded. Retry in 1 seconds
it-sd-bot_rasa_1 exited with code 1
```

I guess, problem ocurred because of duplicating `setWebhook`:
https://github.com/RasaHQ/rasa/blob/master/rasa/core/channels/telegram.py#L242
and
https://github.com/RasaHQ/rasa/blob/master/rasa/core/channels/telegram.py#L247

**Comment by selphe** [comment]
@wochinge could you please look at this issue?

**Comment by selphe** [comment]
1.2.0-latest - problem still exists

```
rasa_1  | Traceback (most recent call last):
rasa_1  |   File "/usr/local/bin/rasa", line 10, in <module>
rasa_1  |     sys.exit(main())
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/__main__.py", line 76, in main
rasa_1  |     cmdline_arguments.func(cmdline_arguments)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/cli/run.py", line 88, in run
rasa_1  |     rasa.run(**vars(args))
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/run.py", line 55, in run
rasa_1  |     **kwargs
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/run.py", line 165, in serve_application
rasa_1  |     log_file=log_file,
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/run.py", line 106, in configure_app
rasa_1  |     rasa.core.channels.channel.register(input_channels, app, route=route)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/channels/channel.py", line 87, in register
rasa_1  |     app.blueprint(channel.blueprint(handler), url_prefix=p)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/channels/telegram.py", line 242, in blueprint
rasa_1  |     out_channel.setWebhook(self.webhook_url)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/telegram/bot.py", line 65, in decorator
rasa_1  |     result = func(self, *args, **kwargs)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/telegram/bot.py", line 2070, in set_webhook
rasa_1  |     result = self._request.post(url_, data, timeout=timeout)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/telegram/utils/request.py", line 309, in post
rasa_1  |     headers={'Content-Type': 'application/json'})
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/telegram/utils/request.py", line 216, in _request_wrapper
rasa_1  |     message = self._parse(resp.data)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/telegram/utils/request.py", line 174, in _parse
rasa_1  |     raise RetryAfter(retry_after)
rasa_1  | telegram.error.RetryAfter: Flood control exceeded. Retry in 1 seconds
```

**Comment by selphe** [comment]
I've check locally to fix `setWebhook`, and it works for me.
I hope my PR is correct (i'm not a developer, sorry)

**Comment by wochinge** [comment]
@selphe Are you sure this is not caused by wrong credentials? So it actually sends messages correctly to Telegram if you comment line `247`?

**Comment by selphe** [comment]
Hi @wochinge
I didn't change the credentials.yml before update.
Yes, when this line commented, tg channel is up, messages is sent correctly.

**Comment by wochinge** [comment]
@selphe I am fixing this issue in https://github.com/RasaHQ/rasa/pull/4171 . Sorry for not using your pr, but I had to remove the `setWebhook` at another location (the one you removed is actually needed for another feature)
