### ISSUE TITLE
 Exception occurred while handling uri: 'http://localhost:5005/favicon.ico

### ISSUE THREAD

**Issue by pingyuan2016** [RasaHQ/rasa#4129]
hello, I install rasa X new version,run "rasa shell",It's error, I get this inspecting the core logs:
```
2019-07-30 13:23:09,608 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/'
Traceback (most recent call last):
  File "/home/duan/anaconda3/lib/python3.7/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/duan/anaconda3/lib/python3.7/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/duan/anaconda3/lib/python3.7/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL / not found
2019-07-30 13:23:17,398 [ERROR]  Exception occurred while handling uri: 'http://localhost:5005/favicon.ico'
Traceback (most recent call last):
  File "/home/duan/anaconda3/lib/python3.7/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/duan/anaconda3/lib/python3.7/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/duan/anaconda3/lib/python3.7/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /favicon.ico not found
```

**Comment by msamogh** [comment]
Thanks for raising this issue, @erohmensing will get back to you about it soon.

**Comment by erohmensing** [comment]
Hi there @pingyuan2016, sorry I seem to have missed this message. Can you post exactly what commands you're running and the full output (not just the error?)

**Comment by ngochuyenluu** [comment]
Hello, I just reinstalled update version of Rasa and Rasa X few days ago. I have same problem when run rasa run -m models --enable-api --log-file out.log -m my model, it raises: 

2019-08-21 14:51:58 INFO     root  - Generating grammar tables from /usr/lib/python3.6/lib2to3/Grammar.txt
2019-08-21 14:51:58 INFO     root  - Generating grammar tables from /usr/lib/python3.6/lib2to3/PatternGrammar.txt
2019-08-21 14:52:00 INFO     root  - Starting Rasa server on http://localhost:5005
[2019-08-21 14:52:09 +0200] [30698] [ERROR] Exception occurred while handling uri: 'http://localhost:5005/favicon.ico'
Traceback (most recent call last):
  File "/home/nluu/.virtualenvs/Chabot_hotline/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/nluu/.virtualenvs/Chabot_hotline/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/nluu/.virtualenvs/Chabot_hotline/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /favicon.ico not found
[2019-08-21 14:53:09 +0200] [30698] [ERROR] Exception occurred while handling uri: unknown

Is there any wrong with my command or sth else in the new version Rasa?

Thank in advance for any recommendations or responses.

**Comment by 123v** [comment]
hi, I'm facing same issue. is there any update?
![powershell](https://user-images.githubusercontent.com/18350670/64149853-b027b100-ce44-11e9-98d4-1bc6b8e64e59.PNG)

**Comment by erohmensing** [comment]
> Can you post exactly what commands you're running and the full output (not just the error?)

**Comment by jwheat** [comment]
I have this as well - [kind of fixed it]

Running Windows 10, fwiw.

When I initially execute `rasa run` there are no errors in the console. 

Simply hitting the url : http://localhost:5005/ correctly show this in the browser:
`Hello from Rasa: 1.2.5`

However hitting that url in the browser displays the following error dump in the console and in out.log

```
Exception occurred while handling uri: 'http://localhost:5005/favicon.ico'
Traceback (most recent call last):
    File "c:\users\jonathan\appdata\local\programs\python\python36\lib\site-packages\sanic\app.py", line 893, in handle_request
        handler, args, kwargs, uri = self.router.get(request)
    File "c:\users\jonathan\appdata\local\programs\python\python36\lib\site-packages\sanic\router.py", line 407, in get
        return self._get(request.path, request.method, "")
    File "c:\users\jonathan\appdata\local\programs\python\python36\lib\site-packages\sanic\router.py", line 469, in _get
        raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /favicon.ico not found
```

I don't think it's a big deal, it's simply not finding the favicon file when the Sanic server spins up.

I dropped a random one in the root of the project, restarted rasa and the error no longer appears.

However, the icon I placed there doesn't display in the browser as the favicon, and if I bookmark the url, there's a different favicon file next to the bookmark. :)

**Comment by ngochuyenluu** [comment]
Hello, I face the same error. The command that I used:
```
 rasa run -vv -m models/20190926-143232.tar.gz --enable-api
```
And all output with error:
```
/home/nluu/.virtualenvs/Chabot_hotline/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/home/nluu/.virtualenvs/Chabot_hotline/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:527: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/home/nluu/.virtualenvs/Chabot_hotline/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:528: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/home/nluu/.virtualenvs/Chabot_hotline/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:529: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
/home/nluu/.virtualenvs/Chabot_hotline/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:530: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
/home/nluu/.virtualenvs/Chabot_hotline/lib/python3.6/site-packages/tensorflow/python/framework/dtypes.py:535: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
/home/nluu/.virtualenvs/Chabot_hotline/lib/python3.6/site-packages/h5py/__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2019-09-27 10:56:48 DEBUG    rasa.cli.utils  - Parameter 'endpoints' not set. Using default location 'endpoints.yml' instead.
2019-09-27 10:56:48 DEBUG    rasa.cli.utils  - Parameter 'credentials' not set. Using default location 'credentials.yml' instead.
2019-09-27 10:56:48 INFO     root  - Generating grammar tables from /usr/lib/python3.6/lib2to3/Grammar.txt
2019-09-27 10:56:49 INFO     root  - Generating grammar tables from /usr/lib/python3.6/lib2to3/PatternGrammar.txt
2019-09-27 10:56:50 DEBUG    rasa.core.utils  - Available web server routes: 
/conversations/<conversation_id>/messages          POST                           add_message
/conversations/<conversation_id>/tracker/events    POST                           append_events
/webhooks/rasa                                     GET                            custom_webhook_RasaChatInput.health
/webhooks/rasa/webhook                             POST                           custom_webhook_RasaChatInput.receive
/model/test/intents                                POST                           evaluate_intents
/model/test/stories                                POST                           evaluate_stories
/conversations/<conversation_id>/execute           POST                           execute_action
/domain                                            GET                            get_domain
/                                                  GET                            hello
/model                                             PUT                            load_model
/model/parse                                       POST                           parse
/conversations/<conversation_id>/predict           POST                           predict
/conversations/<conversation_id>/tracker/events    PUT                            replace_events
/conversations/<conversation_id>/story             GET                            retrieve_story
/conversations/<conversation_id>/tracker           GET                            retrieve_tracker
/status                                            GET                            status
/model/predict                                     POST                           tracker_predict
/model/train                                       POST                           train
/model                                             DELETE                         unload_model
/version                                           GET                            version
2019-09-27 10:56:50 INFO     root  - Starting Rasa server on http://localhost:5005
2019-09-27 10:56:50 INFO     root  - Enabling coroutine debugging. Loop id 104305912.
2019-09-27 10:56:50 DEBUG    rasa.model  - Extracted model to '/tmp/tmpl8k9zlqb'.
2019-09-27 10:56:50 DEBUG    rasa.core.tracker_store  - Connected to InMemoryTrackerStore.
2019-09-27 10:56:50 DEBUG    rasa.model  - Extracted model to '/tmp/tmpzs5ou51c'.
2019-09-27 10:56:50 DEBUG    pykwalify.compat  - Using yaml library: /home/nluu/.virtualenvs/Chabot_hotline/lib/python3.6/site-packages/ruamel/yaml/__init__.py
[2019-09-27 10:56:55 +0200] [7665] [ERROR] Exception occurred while handling uri: 'http://localhost:5005/favicon.ico'
Traceback (most recent call last):
  File "/home/nluu/.virtualenvs/Chabot_hotline/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/nluu/.virtualenvs/Chabot_hotline/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/nluu/.virtualenvs/Chabot_hotline/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /favicon.ico not found
[2019-09-27 10:57:14 +0200] [7665] [ERROR] Exception occurred while handling uri: 'http://localhost:5005/favicon.ico'
Traceback (most recent call last):
  File "/home/nluu/.virtualenvs/Chabot_hotline/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/nluu/.virtualenvs/Chabot_hotline/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/nluu/.virtualenvs/Chabot_hotline/lib/python3.6/site-packages/sanic/router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /favicon.ico not found
```

Is there anyone have idea to fix this? Thank you

**Comment by erohmensing** [comment]
What are you sending when you receive the error?

**Comment by ngochuyenluu** [comment]
Hello, I tried to open it in a browser, with address http://localhost:5005, it returned 'hello from Rasa 1.2.5' but http://localhost:5005/favicon.ico, it returned the error above.
But if I don't open the browser, and test in another terminal, for example I sent:
```
curl -XPOST localhost:5005/webhooks/rest/webhook -d '{"sender":"Me","message":"how are you?"}'
```
It worked.

**Comment by erohmensing** [comment]
Right, it's not a browser application, so that'l be why

**Comment by mystic-cg** [comment]
I have the same problem. 
Python: 3.8.1
Sanic: 19.12.2
Here is the code.
`
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from sanic import Sanic
from sanic.response import json

app = Sanic("blog")


@app.route("/")
async def test(request):
    return json({"hello": "world"})


if __name__ == "__main__":
    app.run(host="0.0.0.0", port=8000)
`

**Comment by tanveerahmed668** [comment]
hi,when i am type this command,"rasa run actions" ,i am getting this error,

 C:\Users\mohammed tanveer\.javeriabot>rasa run actions
2020-03-26 13:27:33.378025: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2020-03-26 13:27:37 INFO     rasa_sdk.endpoint  - Starting action endpoint server...
2020-03-26 13:27:37 INFO     rasa_sdk.executor  - Registered function for 'find_facility_types'.
2020-03-26 13:27:37 INFO     rasa_sdk.executor  - Registered function for 'find_healthcare_address'.
2020-03-26 13:27:37 INFO     rasa_sdk.executor  - Registered function for 'facility_form'.
Exception occurred while handling uri: 'http://localhost:5055/webhook'
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\sanic\app.py", line 918, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "c:\programdata\anaconda3\lib\site-packages\sanic\router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "c:\programdata\anaconda3\lib\site-packages\sanic\router.py", line 447, in _get
    raise method_not_supported
sanic.exceptions.MethodNotSupported: Method GET not allowed for URL /webhook
Exception occurred while handling uri: 'http://localhost:5055/favicon.ico'
Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\site-packages\sanic\app.py", line 918, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "c:\programdata\anaconda3\lib\site-packages\sanic\router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "c:\programdata\anaconda3\lib\site-packages\sanic\router.py", line 470, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /favicon.ico not found

**Comment by erohmensing** [comment]
@tanveerahmed668 Please create a new issue and fill out the issue template with all of the relevant information

**Comment by tanveerahmed668** [comment]
sorry ,can you elaborate your answer

**Comment by erohmensing** [comment]
Please open a new issue instead of commenting on an old one if you think you have found a bug
