### ISSUE TITLE
i found it will crash when using interactive learning, if my input sequence too long to print the history.

### ISSUE THREAD

**Issue by jianjunchang** [RasaHQ/rasa#4130]
**Rasa version**:1.1.4

**Rasa X version** (if used & relevant):

**Python version**:3.6.9

**Operating system** (windows, osx, ...):osx

**Issue**:

i found it will crash when using interactive learning, if my input sequence too long to print the history. if the sequence is not too long ,the crash will not appear. 

**Error (including full traceback)**:
```
2019-07-30 15:13:34 ERROR    rasa.core.training.interactive  - An exception occurred while recording messages.
Traceback (most recent call last):
  File "/data/python36env/lib/python3.6/site-packages/rasa/core/training/interactive.py", line 1364, in record_messages
    endpoint, sender_id, sender_ids, plot_file
  File "/data/python36env/lib/python3.6/site-packages/rasa/core/training/interactive.py", line 875, in _predict_till_next_listen
    await _print_history(sender_id, endpoint)
  File "/data/python36env/lib/python3.6/site-packages/rasa/core/training/interactive.py", line 438, in _print_history
    table = _chat_history_table(events)
  File "/data/python36env/lib/python3.6/site-packages/rasa/core/training/interactive.py", line 520, in _chat_history_table
    msg = format_user_msg(event, user_width(table))
  File "/data/python36env/lib/python3.6/site-packages/rasa/core/training/interactive.py", line 471, in format_user_msg
    colored(wrap(_md, max_width), "hired"),
  File "/data/python36env/lib/python3.6/site-packages/rasa/core/training/interactive.py", line 459, in wrap
    return "\n".join(textwrap.wrap(txt, max_width, replace_whitespace=False))
  File "/opt/python3.6.9/lib/python3.6/textwrap.py", line 379, in wrap
    return w.wrap(text)
  File "/opt/python3.6.9/lib/python3.6/textwrap.py", line 354, in wrap
    return self._wrap_chunks(chunks)
  File "/opt/python3.6.9/lib/python3.6/textwrap.py", line 248, in _wrap_chunks
    raise ValueError("invalid width %r (must be > 0)" % self.width)
ValueError: invalid width -11 (must be > 0)
```

**Command or request that led to error**:
```
rasa run actions --actions actions&rasa interactive --skip-visualization -m models/20190730-145436.tar.gz --endpoints endpoints.yml
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by msamogh** [comment]
Can you paste your input here?

**Comment by jianjunchang** [comment]
@msamogh what's the content i input is not the matter, but the printing of the history table is the cause of the crash when the input sequence is too long. if the screen's resolution is high enough to display a long sequence, there will no crash again. so this is not a serious bug.

**Comment by msamogh** [comment]
By sequence, do you mean a single input line or the history length?

**Comment by jianjunchang** [comment]
i mean a single input line, i think the reason of crash is the input line can't be display properly.(sorry, my english is bad, i hope you can understand me)

**Comment by msamogh** [comment]
Sorry for the late reply. I tried using pretty long sequences, but couldn't reproduce it. Could you paste your input here?

**Comment by jianjunchang** [comment]
'''
------------------------------------------------------------------------------------
 10                                                                            是的 
                                                                intent: affirm 0.98 
------------------------------------------------------------------------------------
 11   action_restaurant_form 1.00                                                   
      还有哪些特别的要求吗？                                                        
      slot{"outdoor_seating": true}                                                 
      slot{"requested_slot": "preferences"}                                         
      action_listen 1.00                                                            
------------------------------------------------------------------------------------
 12                                                                            没了 
                                                                  intent: deny 0.97 


Current slots: 
        cuisine: 印度, feedback: None, num_people: 2, outdoor_seating: True, preferences: None, requested_slot: preferences

------
? The bot wants to run 'action_restaurant_form', correct?  Yes                                                                     
2019-08-21 09:39:45 DEBUG    rasa.core.actions.action  - Calling action endpoint to run action 'action_restaurant_form'.
2019-08-21 09:39:45 DEBUG    rasa.core.processor  - Action 'action_restaurant_form' ended with events '['BotUttered(text: 请您给出本次服务的评价！, data: {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, metadata: {"cuisine": "\\u5370\\u5ea6", "feedback": null, "num_people": "2", "outdoor_seating": true, "preferences": "\\u6ca1\\u6709\\u66f4\\u591a\\u8981\\u6c42\\u3002", "requested_slot": "preferences"})', 'SlotSet(key: preferences, value: 没有更多要求。)', 'SlotSet(key: requested_slot, value: feedback)']'
2019-08-21 09:39:45 DEBUG    rasa.core.processor  - Current slot values: 
        cuisine: 印度
        feedback: None
        num_people: 2
        outdoor_seating: True
        preferences: 没有更多要求。
        requested_slot: feedback
2019-08-21 09:39:45 DEBUG    rasa.core.policies.memoization  - Current tracker state [None, {}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_utter_greet': 1.0, 'intent_greet': 1.0}, {'intent_restaurant_search': 1.0, 'prev_action_listen': 1.0}]
2019-08-21 09:39:45 DEBUG    rasa.core.policies.memoization  - There is a memorised next action '25'
2019-08-21 09:39:45 DEBUG    rasa.core.policies.mapping_policy  - There is no mapped action for the predicted intent, 'deny'.
2019-08-21 09:39:45 DEBUG    rasa.core.policies.form_policy  - There is an active form 'action_restaurant_form'
2019-08-21 09:39:45 DEBUG    rasa.core.policies.fallback  - NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-21 09:39:45 DEBUG    rasa.core.policies.ensemble  - Predicted next action using policy_3_FormPolicy
------
Chat History

 #    Bot                                                                You        
------------------------------------------------------------------------------------
 1    action_listen                                                                 
------------------------------------------------------------------------------------
 2                                                                             你好 
                                                                 intent: greet 0.94 
------------------------------------------------------------------------------------
 3    utter_greet 1.00                                                              
      您好，我是订餐助手，请问您需要什么服务？                                      
      action_listen 1.00                                                            
------------------------------------------------------------------------------------
 4                                                                         预定桌位 
                                                     intent: restaurant_search 0.98 
------------------------------------------------------------------------------------
 5    action_restaurant_form 1.00                                                   
      您想要哪种风味的餐厅？                                                        
      form{"name": "action_restaurant_form"}                                        
      slot{"requested_slot": "cuisine"}                                             
      action_listen 1.00                                                            
------------------------------------------------------------------------------------
 6                                                              [印度](cuisine)风味 
                                                                intent: inform 0.97 
------------------------------------------------------------------------------------
 7    action_restaurant_form 1.00                                                   
      您准备多少人同时就餐？                                                        
      slot{"cuisine": "印度"}                                                       
      slot{"requested_slot": "num_people"}                                          
      action_listen                                                                 
------------------------------------------------------------------------------------
 8                                                             [两个](num_people:2) 
                                                                intent: inform 1.00 
------------------------------------------------------------------------------------
 9    action_restaurant_form 1.00                                                   
      您喜欢露天餐位吗？                                                            
      slot{"num_people": "2"}                                                       
      slot{"requested_slot": "outdoor_seating"}                                     
      action_listen 1.00                                                            
------------------------------------------------------------------------------------
 10                                                                            是的 
                                                                intent: affirm 0.98 
------------------------------------------------------------------------------------
 11   action_restaurant_form 1.00                                                   
      还有哪些特别的要求吗？                                                        
      slot{"outdoor_seating": true}                                                 
      slot{"requested_slot": "preferences"}                                         
      action_listen 1.00                                                            
------------------------------------------------------------------------------------
 12                                                                            没了 
                                                                  intent: deny 0.97 
------------------------------------------------------------------------------------
 13   action_restaurant_form 1.00                                                   
      请您给出本次服务的评价！                                                      
      slot{"preferences": "没有更多要求。"}                                         
      slot{"requested_slot": "feedback"}                                            


Current slots: 
        cuisine: 印度, feedback: None, num_people: 2, outdoor_seating: True, preferences: 没有更多要求。, requested_slot: feedback

------
? The bot wants to run 'action_listen', correct?  Yes                                                                              
2019-08-21 09:39:48 DEBUG    rasa.core.processor  - Action 'action_listen' ended with events '[]'
? Your input -> 满意                                                                                                               
2019-08-21 09:39:51 DEBUG    rasa.core.processor  - Received user message '满意' with intent '{'name': 'inform', 'confidence': 0.974751889705658}' and entities '[{'start': 0, 'end': 2, 'value': '好', 'entity': 'feedback', 'confidence': 0.8955358576338861, 'extractor': 'CRFEntityExtractor', 'processors': ['EntitySynonymMapper']}]'
2019-08-21 09:39:51 DEBUG    rasa.core.processor  - Current slot values: 
        cuisine: 印度
        feedback: None
        num_people: 2
        outdoor_seating: True
        preferences: 没有更多要求。
        requested_slot: feedback
2019-08-21 09:39:51 DEBUG    rasa.core.processor  - Logged UserUtterance - tracker now has 87 events
? Is the intent 'inform' correct for '[满意](feedback:好)' and are all entities labeled correctly?  Yes                            
2019-08-21 09:39:52 DEBUG    rasa.core.policies.memoization  - Current tracker state [None, {}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_utter_greet': 1.0, 'intent_greet': 1.0}, {'intent_restaurant_search': 1.0, 'prev_action_listen': 1.0}]
2019-08-21 09:39:52 DEBUG    rasa.core.policies.memoization  - There is a memorised next action '25'
2019-08-21 09:39:52 DEBUG    rasa.core.policies.form_policy  - There is an active form 'action_restaurant_form'
2019-08-21 09:39:52 DEBUG    rasa.core.policies.fallback  - NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-21 09:39:52 DEBUG    rasa.core.policies.ensemble  - Predicted next action using policy_3_FormPolicy
------
Chat History

 #    Bot                                                                You        
------------------------------------------------------------------------------------
 1    action_listen                                                                 
------------------------------------------------------------------------------------
 2                                                                             你好 
                                                                 intent: greet 0.94 
------------------------------------------------------------------------------------
 3    utter_greet 1.00                                                              
      您好，我是订餐助手，请问您需要什么服务？                                      
      action_listen 1.00                                                            
------------------------------------------------------------------------------------
 4                                                                         预定桌位 
                                                     intent: restaurant_search 0.98 
------------------------------------------------------------------------------------
 5    action_restaurant_form 1.00                                                   
      您想要哪种风味的餐厅？                                                        
      form{"name": "action_restaurant_form"}                                        
      slot{"requested_slot": "cuisine"}                                             
      action_listen 1.00                                                            
------------------------------------------------------------------------------------
 6                                                              [印度](cuisine)风味 
                                                                intent: inform 0.97 
------------------------------------------------------------------------------------
 7    action_restaurant_form 1.00                                                   
      您准备多少人同时就餐？                                                        
      slot{"cuisine": "印度"}                                                       
      slot{"requested_slot": "num_people"}                                          
      action_listen                                                                 
------------------------------------------------------------------------------------
 8                                                             [两个](num_people:2) 
                                                                intent: inform 1.00 
------------------------------------------------------------------------------------
 9    action_restaurant_form 1.00                                                   
      您喜欢露天餐位吗？                                                            
      slot{"num_people": "2"}                                                       
      slot{"requested_slot": "outdoor_seating"}                                     
      action_listen 1.00                                                            
------------------------------------------------------------------------------------
 10                                                                            是的 
                                                                intent: affirm 0.98 
------------------------------------------------------------------------------------
 11   action_restaurant_form 1.00                                                   
      还有哪些特别的要求吗？                                                        
      slot{"outdoor_seating": true}                                                 
      slot{"requested_slot": "preferences"}                                         
      action_listen 1.00                                                            
------------------------------------------------------------------------------------
 12                                                                            没了 
                                                                  intent: deny 0.97 
------------------------------------------------------------------------------------
 13   action_restaurant_form 1.00                                                   
      请您给出本次服务的评价！                                                      
      slot{"preferences": "没有更多要求。"}                                         
      slot{"requested_slot": "feedback"}                                            
      action_listen 1.00                                                            
------------------------------------------------------------------------------------
 14                                                             [满意](feedback:好) 
                                                                intent: inform 0.97 


Current slots: 
        cuisine: 印度, feedback: None, num_people: 2, outdoor_seating: True, preferences: 没有更多要求。, requested_slot: feedback

------
? The bot wants to run 'action_restaurant_form', correct?  Yes                                                                     
2019-08-21 09:39:55 DEBUG    rasa.core.actions.action  - Calling action endpoint to run action 'action_restaurant_form'.
2019-08-21 09:39:55 DEBUG    rasa.core.processor  - Action 'action_restaurant_form' ended with events '['BotUttered(text: 好了, data: {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, metadata: {})', 'SlotSet(key: feedback, value: 好)', 'Form(None)', 'SlotSet(key: requested_slot, value: None)']'
2019-08-21 09:39:55 DEBUG    rasa.core.processor  - Current slot values: 
        cuisine: 印度
        feedback: 好
        num_people: 2
        outdoor_seating: True
        preferences: 没有更多要求。
        requested_slot: None
2019-08-21 09:39:55 DEBUG    rasa.core.policies.memoization  - Current tracker state [{}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_utter_greet': 1.0, 'intent_greet': 1.0}, {'intent_restaurant_search': 1.0, 'prev_action_listen': 1.0}, {'intent_restaurant_search': 1.0, 'prev_action_restaurant_form': 1.0}]
2019-08-21 09:39:55 DEBUG    rasa.core.policies.memoization  - There is a memorised next action '18'
2019-08-21 09:39:55 DEBUG    rasa.core.policies.mapping_policy  - There is no mapped action for the predicted intent, 'inform'.
2019-08-21 09:39:55 DEBUG    rasa.core.policies.form_policy  - There is no active form
2019-08-21 09:39:55 DEBUG    rasa.core.policies.fallback  - NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-21 09:39:55 DEBUG    rasa.core.policies.ensemble  - Predicted next action using policy_0_MemoizationPolicy
------
Chat History

 #    Bot                                                                You        
------------------------------------------------------------------------------------
 1    action_listen                                                                 
------------------------------------------------------------------------------------
 2                                                                             你好 
                                                                 intent: greet 0.94 
------------------------------------------------------------------------------------
 3    utter_greet 1.00                                                              
      您好，我是订餐助手，请问您需要什么服务？                                      
      action_listen 1.00                                                            
------------------------------------------------------------------------------------
 4                                                                         预定桌位 
                                                     intent: restaurant_search 0.98 
------------------------------------------------------------------------------------
 5    action_restaurant_form 1.00                                                   
      您想要哪种风味的餐厅？                                                        
      form{"name": "action_restaurant_form"}                                        
      slot{"requested_slot": "cuisine"}                                             
      action_listen 1.00                                                            
------------------------------------------------------------------------------------
 6                                                              [印度](cuisine)风味 
                                                                intent: inform 0.97 
------------------------------------------------------------------------------------
 7    action_restaurant_form 1.00                                                   
      您准备多少人同时就餐？                                                        
      slot{"cuisine": "印度"}                                                       
      slot{"requested_slot": "num_people"}                                          
      action_listen                                                                 
------------------------------------------------------------------------------------
 8                                                             [两个](num_people:2) 
                                                                intent: inform 1.00 
------------------------------------------------------------------------------------
 9    action_restaurant_form 1.00                                                   
      您喜欢露天餐位吗？                                                            
      slot{"num_people": "2"}                                                       
      slot{"requested_slot": "outdoor_seating"}                                     
      action_listen 1.00                                                            
------------------------------------------------------------------------------------
 10                                                                            是的 
                                                                intent: affirm 0.98 
------------------------------------------------------------------------------------
 11   action_restaurant_form 1.00                                                   
      还有哪些特别的要求吗？                                                        
      slot{"outdoor_seating": true}                                                 
      slot{"requested_slot": "preferences"}                                         
      action_listen 1.00                                                            
------------------------------------------------------------------------------------
 12                                                                            没了 
                                                                  intent: deny 0.97 
------------------------------------------------------------------------------------
 13   action_restaurant_form 1.00                                                   
      请您给出本次服务的评价！                                                      
      slot{"preferences": "没有更多要求。"}                                         
      slot{"requested_slot": "feedback"}                                            
      action_listen 1.00                                                            
------------------------------------------------------------------------------------
 14                                                             [满意](feedback:好) 
                                                                intent: inform 0.97 
------------------------------------------------------------------------------------
 15   action_restaurant_form 1.00                                                   
      好了                                                                          
      slot{"feedback": "好"}                                                        
      form{"name": null}                                                            
      slot{"requested_slot": null}                                                  


Current slots: 
        cuisine: 印度, feedback: 好, num_people: 2, outdoor_seating: True, preferences: 没有更多要求。, requested_slot: None

------
? The bot wants to run 'utter_slots_values', correct?  Yes                                                                         
2019-08-21 09:39:59 DEBUG    rasa.core.processor  - Action 'utter_slots_values' ended with events '['BotUttered(text: 我将为您查询相关酒店，请您核对您的偏好：\\n 风味：印度\\n 人数：2\\n 露天餐位：True\\n 其它要求：没有更多要求。\\n 服务反馈：好, data: {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, metadata: {})']'
2019-08-21 09:39:59 DEBUG    rasa.core.policies.memoization  - Current tracker state [{'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_utter_greet': 1.0, 'intent_greet': 1.0}, {'intent_restaurant_search': 1.0, 'prev_action_listen': 1.0}, {'intent_restaurant_search': 1.0, 'prev_action_restaurant_form': 1.0}, {'intent_restaurant_search': 1.0, 'prev_utter_slots_values': 1.0}]
2019-08-21 09:39:59 DEBUG    rasa.core.policies.memoization  - There is a memorised next action '0'
2019-08-21 09:39:59 DEBUG    rasa.core.policies.mapping_policy  - There is no mapped action for the predicted intent, 'inform'.
2019-08-21 09:39:59 DEBUG    rasa.core.policies.form_policy  - There is no active form
2019-08-21 09:39:59 DEBUG    rasa.core.policies.fallback  - NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-21 09:39:59 DEBUG    rasa.core.policies.ensemble  - Predicted next action using policy_0_MemoizationPolicy
------
Chat History

 #    Bot                                                                                                                                                 You        
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
 1    action_listen                                                                                                                                                  
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
 2                                                                                                                                                              你好 
                                                                                                                                                  intent: greet 0.94 
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
 3    utter_greet 1.00                                                                                                                                               
      您好，我是订餐助手，请问您需要什么服务？                                                                                                                       
      action_listen 1.00                                                                                                                                             
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
 4                                                                                                                                                          预定桌位 
                                                                                                                                      intent: restaurant_search 0.98 
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
 5    action_restaurant_form 1.00                                                                                                                                    
      您想要哪种风味的餐厅？                                                                                                                                         
      form{"name": "action_restaurant_form"}                                                                                                                         
      slot{"requested_slot": "cuisine"}                                                                                                                              
      action_listen 1.00                                                                                                                                             
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
 6                                                                                                                                               [印度](cuisine)风味 
                                                                                                                                                 intent: inform 0.97 
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
 7    action_restaurant_form 1.00                                                                                                                                    
      您准备多少人同时就餐？                                                                                                                                         
      slot{"cuisine": "印度"}                                                                                                                                        
      slot{"requested_slot": "num_people"}                                                                                                                           
      action_listen                                                                                                                                                  
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
 8                                                                                                                                              [两个](num_people:2) 
                                                                                                                                                 intent: inform 1.00 
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
 9    action_restaurant_form 1.00                                                                                                                                    
      您喜欢露天餐位吗？                                                                                                                                             
      slot{"num_people": "2"}                                                                                                                                        
      slot{"requested_slot": "outdoor_seating"}                                                                                                                      
      action_listen 1.00                                                                                                                                             
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
 10                                                                                                                                                             是的 
                                                                                                                                                 intent: affirm 0.98 
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
 11   action_restaurant_form 1.00                                                                                                                                    
      还有哪些特别的要求吗？                                                                                                                                         
      slot{"outdoor_seating": true}                                                                                                                                  
      slot{"requested_slot": "preferences"}                                                                                                                          
      action_listen 1.00                                                                                                                                             
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
 12                                                                                                                                                             没了 
                                                                                                                                                   intent: deny 0.97 
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
 13   action_restaurant_form 1.00                                                                                                                                    
      请您给出本次服务的评价！                                                                                                                                       
      slot{"preferences": "没有更多要求。"}                                                                                                                          
      slot{"requested_slot": "feedback"}                                                                                                                             
      action_listen 1.00                                                                                                                                             
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
 14                                                                                                                                              [满意](feedback:好) 
                                                                                                                                                 intent: inform 0.97 
---------------------------------------------------------------------------------------------------------------------------------------------------------------------
 15   action_restaurant_form 1.00                                                                                                                                    
      好了                                                                                                                                                           
      slot{"feedback": "好"}                                                                                                                                         
      form{"name": null}                                                                                                                                             
      slot{"requested_slot": null}                                                                                                                                   
      utter_slots_values 1.00                                                                                                                                        
      我将为您查询相关酒店，请您核对您的偏好：\n 风味：印度\n 人数：2\n 露天餐位：True\n 其它要求：没有更多要求。\n 服务反馈：好                                     


Current slots: 
        cuisine: 印度, feedback: 好, num_people: 2, outdoor_seating: True, preferences: 没有更多要求。, requested_slot: None

------
? The bot wants to run 'action_listen', correct?  Yes                                                                              
2019-08-21 09:40:04 DEBUG    rasa.core.processor  - Action 'action_listen' ended with events '[]'
? Your input -> 谢谢                                                                                                               
2019-08-21 09:40:09 DEBUG    rasa.core.processor  - Received user message '谢谢' with intent '{'name': 'thankyou', 'confidence': 0.8500159978866577}' and entities '[]'
2019-08-21 09:40:09 DEBUG    rasa.core.processor  - Logged UserUtterance - tracker now has 96 events
? Your NLU model classified '谢谢' with intent 'thankyou' and there are no entities, is this correct?  Yes                         
2019-08-21 09:40:10 DEBUG    rasa.core.policies.memoization  - Current tracker state [{'prev_utter_greet': 1.0, 'intent_greet': 1.0}, {'intent_restaurant_search': 1.0, 'prev_action_listen': 1.0}, {'intent_restaurant_search': 1.0, 'prev_action_restaurant_form': 1.0}, {'intent_restaurant_search': 1.0, 'prev_utter_slots_values': 1.0}, {'prev_action_listen': 1.0, 'intent_thankyou': 1.0}]
2019-08-21 09:40:10 DEBUG    rasa.core.policies.memoization  - There is a memorised next action '17'
2019-08-21 09:40:10 DEBUG    rasa.core.policies.form_policy  - There is no active form
2019-08-21 09:40:10 DEBUG    rasa.core.policies.fallback  - NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2019-08-21 09:40:10 DEBUG    rasa.core.policies.ensemble  - Predicted next action using policy_0_MemoizationPolicy
2019-08-21 09:40:12 ERROR    rasa.core.training.interactive  - An exception occurred while recording messages.
Traceback (most recent call last):
  File "/data/python36env/lib/python3.6/site-packages/rasa/core/training/interactive.py", line 1388, in record_messages
    endpoint, sender_id, sender_ids, plot_file
  File "/opt/python3.6.9/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/data/python36env/lib/python3.6/site-packages/rasa/core/training/interactive.py", line 900, in _predict_till_next_listen
    await _print_history(sender_id, endpoint)
  File "/opt/python3.6.9/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/data/python36env/lib/python3.6/site-packages/rasa/core/training/interactive.py", line 449, in _print_history
    table = _chat_history_table(events)
  File "/data/python36env/lib/python3.6/site-packages/rasa/core/training/interactive.py", line 531, in _chat_history_table
    msg = format_user_msg(event, user_width(table))
  File "/data/python36env/lib/python3.6/site-packages/rasa/core/training/interactive.py", line 482, in format_user_msg
    colored(wrap(_md, max_width), "hired"),
  File "/data/python36env/lib/python3.6/site-packages/rasa/core/training/interactive.py", line 470, in wrap
    return "\n".join(textwrap.wrap(txt, max_width, replace_whitespace=False))
  File "/opt/python3.6.9/lib/python3.6/textwrap.py", line 379, in wrap
    return w.wrap(text)
  File "/opt/python3.6.9/lib/python3.6/textwrap.py", line 354, in wrap
    return self._wrap_chunks(chunks)
  File "/opt/python3.6.9/lib/python3.6/textwrap.py", line 248, in _wrap_chunks
    raise ValueError("invalid width %r (must be > 0)" % self.width)
ValueError: invalid width -9 (must be > 0)
2019-08-21 09:40:12 ERROR    asyncio  - Task exception was never retrieved
future: <Task finished coro=<_serve_application.<locals>.run_interactive_io() done, defined at /data/python36env/lib/python3.6/site-packages/rasa/core/training/interactive.py:1430> exception=ValueError('invalid width -9 (must be > 0)',) created at /data/python36env/lib/python3.6/site-packages/sanic/app.py:116>
source_traceback: Object created at (most recent call last):
  File "/data/python36env/bin/rasa", line 10, in <module>
    sys.exit(main())
  File "/data/python36env/lib/python3.6/site-packages/rasa/__main__.py", line 76, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/data/python36env/lib/python3.6/site-packages/rasa/cli/interactive.py", line 59, in interactive
    perform_interactive_learning(args, zipped_model)
  File "/data/python36env/lib/python3.6/site-packages/rasa/cli/interactive.py", line 88, in perform_interactive_learning
    do_interactive_learning(args, stories_directory)
  File "/data/python36env/lib/python3.6/site-packages/rasa/core/train.py", line 192, in do_interactive_learning
    additional_arguments=additional_arguments,
  File "/data/python36env/lib/python3.6/site-packages/rasa/core/training/interactive.py", line 1568, in run_interactive_learning
    _serve_application(app, stories, skip_visualization)
  File "/data/python36env/lib/python3.6/site-packages/rasa/core/training/interactive.py", line 1448, in _serve_application
    app.run(host="0.0.0.0", port=DEFAULT_SERVER_PORT)
  File "/data/python36env/lib/python3.6/site-packages/sanic/app.py", line 1096, in run
    serve(**server_settings)
  File "/data/python36env/lib/python3.6/site-packages/sanic/server.py", line 742, in serve
    trigger_events(before_start, loop)
  File "/data/python36env/lib/python3.6/site-packages/sanic/server.py", line 602, in trigger_events
    result = event(loop)
  File "/data/python36env/lib/python3.6/site-packages/sanic/app.py", line 116, in run
    loop.create_task(task(self))
Traceback (most recent call last):
  File "/data/python36env/lib/python3.6/site-packages/rasa/core/training/interactive.py", line 1437, in run_interactive_io
    sender_id=uuid.uuid4().hex,
  File "/opt/python3.6.9/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/data/python36env/lib/python3.6/site-packages/rasa/core/training/interactive.py", line 1388, in record_messages
    endpoint, sender_id, sender_ids, plot_file
  File "/opt/python3.6.9/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/data/python36env/lib/python3.6/site-packages/rasa/core/training/interactive.py", line 900, in _predict_till_next_listen
    await _print_history(sender_id, endpoint)
  File "/opt/python3.6.9/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/data/python36env/lib/python3.6/site-packages/rasa/core/training/interactive.py", line 449, in _print_history
    table = _chat_history_table(events)
  File "/data/python36env/lib/python3.6/site-packages/rasa/core/training/interactive.py", line 531, in _chat_history_table
    msg = format_user_msg(event, user_width(table))
  File "/data/python36env/lib/python3.6/site-packages/rasa/core/training/interactive.py", line 482, in format_user_msg
    colored(wrap(_md, max_width), "hired"),
  File "/data/python36env/lib/python3.6/site-packages/rasa/core/training/interactive.py", line 470, in wrap
    return "\n".join(textwrap.wrap(txt, max_width, replace_whitespace=False))
  File "/opt/python3.6.9/lib/python3.6/textwrap.py", line 379, in wrap
    return w.wrap(text)
  File "/opt/python3.6.9/lib/python3.6/textwrap.py", line 354, in wrap
    return self._wrap_chunks(chunks)
  File "/opt/python3.6.9/lib/python3.6/textwrap.py", line 248, in _wrap_chunks
    raise ValueError("invalid width %r (must be > 0)" % self.width)
ValueError: invalid width -9 (must be > 0)
'''
Here i pasted more logs when the exception is raised. if i adjust the fontsize to be smaller, then the screen can show more words in one line and the exception disappear. I think the cause of the exception is the calculation of the printing space.Hope it's helpful for your resolve.

**Comment by msamogh** [comment]
Thanks for pasting it here. I've formatted it so that it appears as code and not raw Markdown. Will look into it.

**Comment by jianjunchang** [comment]
Hi, thanks for your edit. I have try to format it yesterday using the "<>" button above, but failed.
