### ISSUE TITLE
utter_attachment throwing AttributeError: 'list' object has no attribute 'get'

### ISSUE THREAD

**Issue by vigneshp826** [RasaHQ/rasa#4145]
**Rasa version**: 1.1.8

**Rasa X version** (if used & relevant):

**Python version**: 3.6.8

**Operating system** (windows, osx, ...): osx - Ubuntu

**Issue**:

Recently migrated to Rasa 1.1.8. In my actions.py, am using utter_attachment to send html color bar along with string to Slack channel. In previous version it worked fine.  

**Error (including full traceback)**:
```
>rasa.core.processor - Received user message 'pls do health check for AbuseApp' with intent '{'name': 'health_check', 'confidence': 0.9436773061752319}' and entities '[{'start': 24, 'end': 32, 'value': 'AbuseApp', 'entity': 'application_name', 'confidence': 0.7173894464098511, 'extractor': 'CRFEntityExtractor'}]'
>DEBUG rasa.core.processor - Current slot values: application_name: AbuseApp

>DEBUG rasa.core.processor - Logged UserUtterance - tracker now has 4 events
>DEBUG rasa.core.policies.memoization - Current tracker state [None, None, None, {}, {'entity_application_name': 1.0, 'intent_health_check': 1.0, 'prev_action_listen': 1.0, 'slot_application_name_0': 1.0}]
>DEBUG rasa.core.policies.memoization - There is a memorised next action '13'
>DEBUG rasa.core.policies.form_policy - There is no active form
>DEBUG rasa.core.policies.ensemble - Predicted next action using policy_0_MemoizationPolicy
>DEBUG rasa.core.processor - Predicted next action 'action_health_notify' with confidence 1.00.
2019-07-31 12:32:12 DEBUG rasa.core.actions.action - Calling action endpoint to run action 'action_health_notify'.
>txt_msg: Sure, pls give me 2 minutes. Inspecting health of AbuseApp application
>127.0.0.1 - - [2019-07-31 12:32:12] "POST /webhook HTTP/1.1" 200 404 0.001306
>2019-07-31 12:32:12 DEBUG rasa.core.processor - Action 'action_health_notify' ended with events '['BotUttered(text: None, data: {"elements": null, "quick_replies": null, "buttons": null, "attachment": [{"attachment_type": "default", "color": "#5bc0de", "text": "Sure, pls give me 2 minutes. Inspecting health of AbuseApp application"}], "image": null, "custom": null}, metadata: {})', 'SlotSet(key: application_name, value: AbuseApp)']'
>2019-07-31 12:32:12 DEBUG rasa.core.processor - Current slot values:
>application_name: AbuseApp
>
>2019-07-31 12:32:12 DEBUG rasa.core.agent - Deleted lock for conversation 'W94SC8XU7' (unused)
>2019-07-31 12:32:12 ERROR rasa.core.channels.slack - Exception when trying to handle message.'list' object has no attribute 'get'
>2019-07-31 12:32:12 ERROR rasa.core.channels.slack - 'list' object has no attribute 'get'
>Traceback (most recent call last):
>
>File "/home/vcap/deps/0/python/lib/python3.6/site-packages/rasa/core/channels/slack.py", line 272, in process_message
>await on_new_message(user_msg)
>File "/home/vcap/deps/0/python/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
>return self.gen.send(None)
>File "/home/vcap/deps/0/python/lib/python3.6/site-packages/rasa/core/channels/channel.py", line 65, in handler
>await app.agent.handle_message(*args, **kwargs)
>File "/home/vcap/deps/0/python/lib/python3.6/site-packages/rasa/core/agent.py", line 488, in handle_message
>return await processor.handle_message(message)
>File "/home/vcap/deps/0/python/lib/python3.6/site-packages/rasa/core/processor.py", line 90, in handle_message
>await self._predict_and_execute_next_action(message, tracker)
>File "/home/vcap/deps/0/python/lib/python3.6/site-packages/rasa/core/processor.py", line 356, in _predict_and_execute_next_action
>action, tracker, message.output_channel, self.nlg, policy, confidence
>File "/home/vcap/deps/0/python/lib/python3.6/site-packages/rasa/core/processor.py", line 466, in _run_action
>await self._send_bot_messages(events, tracker, output_channel)
>File "/home/vcap/deps/0/python/lib/python3.6/site-packages/rasa/core/processor.py", line 388, in _send_bot_messages
>await output_channel.send_response(tracker.sender_id, e.message())
>File "/home/vcap/deps/0/python/lib/python3.6/site-packages/rasa/core/channels/channel.py", line 183, in send_response
>recipient_id, message.pop("attachment"), **message
>File "/home/vcap/deps/0/python/lib/python3.6/site-packages/rasa/core/channels/slack.py", line 61, in send_attachment
>text = attachment.get("text", "Attachment")
>AttributeError: 'list' object has no attribute 'get'
```

**Command or request that led to error**:
```
actions.py
------------

from rasa_sdk import Action
from rasa_sdk.events import SlotSet
from rasa_sdk.events import AllSlotsReset
from rasa_sdk.events import Restarted
from rasa.core.channels import CollectingOutputChannel
from rasa_sdk.forms import FormAction
from rasa_sdk import utils
from slackclient import SlackClient

class HealthNotify(Action):
    def name(self):
        return 'action_health_notify'

    def run(self, dispatcher, tracker, domain):
        appname = tracker.get_slot('application_name')
        response = format_text_color("Sure, pls give me 2 minutes. Inspecting health of {} application".format(appname), INFO)
        dispatcher.utter_attachment(response)		
        return [SlotSet('application_name',appname)]



```

Expected result which worked in previous version:

![image](https://user-images.githubusercontent.com/36441437/62213650-06767f80-b3c1-11e9-94ef-30775e79e003.png)

**Comment by msamogh** [comment]
Thanks for raising this issue, @ricwo will get back to you about it soon.

**Comment by ricwo** [comment]
Hi @vigneshp826, what exactly does your `response` look like in `run()` you posted above?

**Comment by vigneshp826** [comment]
HI @ricwo , response = format_text_color("Sure, pls give me 2 minutes. Inspecting health of {} application".format(appname), INFO)  ----> this line calls below function.

```
def format_text_color(txt_msg, col):
    GENERAL = '#428bca'         # Blue
    SUCCESS = '#5cb85c'         # Green
    INFO    = '#5bc0de'         # Light blue
    WARNING = '#f0ad4e'         # Orange
    ERROR  = '#d9534f'         # Red  
    print('txt_msg:', txt_msg)
    attachments_json = [{'color': col, 'attachment_type': 'default','text': txt_msg}]

    return attachments_json
```
So ``` response = [{'color': '#5bc0de', 'attachment_type': 'default', 'text': 'Sure, pls give me 2 minutes. Inspecting health of Abuseapp application'}]```

**Comment by ricwo** [comment]
Hi @vigneshp826, the response you're feeding into `utter_attachment` needs to be a dictionary. You're supplying  list instead. Please change your `format_text_color()` method to instead return

```python
response = {'color': '#5bc0de', 'attachment_type': 'default', 'text': 'Sure, pls give me 2 minutes. Inspecting health of Abuseapp application'}
```

**Comment by vigneshp826** [comment]
hi @ricwo , thanks 👍 . That works.
