### ISSUE TITLE
NLU test comparison mode doesn't accept a folder

### ISSUE THREAD

**Issue by MetcalfeTom** [RasaHQ/rasa#4169]
With `all_configs` as a folder:
```
rasa test nlu -u dataset/full.json --config all_configs
2019-08-05 01:58:51 INFO     rasa.cli.test  - Multiple configuration files specified, running nlu comparison mode.

Traceback (most recent call last):
  File "/Users/tom/Documents/RASA/rasa/rasa/utils/io.py", line 130, in read_file
    with open(filename, encoding=encoding) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/tom/Documents/RASA/wordpieces/pretrained_spacy.yml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/tom/miniconda3/bin/rasa", line 11, in <module>
    load_entry_point('rasa', 'console_scripts', 'rasa')()
  File "/Users/tom/Documents/RASA/rasa/rasa/__main__.py", line 76, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/Users/tom/Documents/RASA/rasa/rasa/cli/test.py", line 123, in test_nlu
    io_utils.read_file(file),
  File "/Users/tom/Documents/RASA/rasa/rasa/utils/io.py", line 133, in read_file
    raise ValueError("File '{}' does not exist.".format(filename))
ValueError: File '/Users/tom/Documents/RASA/wordpieces/pretrained_spacy.yml' does not exist.
```
Seems the config folder name is dropped somewhere (the path should be `/Users/tom/Documents/RASA/wordpieces/all_configs/pretrained_spacy.yml`)

**Comment by MetcalfeTom** [comment]
OK now it's completely broken:
```
rasa test nlu -u expressions.json --config default_supervised.yml --config super_supervised.yml
The path 'models' does not exist. Please make sure to use the default location ('models') or specify it with '--model'.
```

**Comment by wochinge** [comment]
@MetcalfeTom I can't reproduce it 🙈 Works fine for me. maybe some wrong permissions or so?

**Comment by wochinge** [comment]
@MetcalfeTom Now I can reproduce it. Thanks!
