### ISSUE TITLE
Rasa test config Folder Argument error

### ISSUE THREAD

**Issue by ismaeelBM** [RasaHQ/rasa#4211]
**Rasa version**: 1.2.2

**Python version**: 3.6.7

**Operating system**: ubuntu

**Issue**:
Unable to parse a folder as an argument when running rasa test. Below are the error and the command that I ran. The configFolder only consists of two files 'config2.yml' and 'config.yml'.

**Error**:
```
Traceback (most recent call last):
  File "/home/ismaeel/hungrynaki/zRasa_env/lib/python3.6/site-packages/rasa/utils/io.py", line 130, in read_file
    with open(filename, encoding=encoding) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/ismaeel/hungrynaki/rasa/config2.yml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ismaeel/hungrynaki/zRasa_env/bin/rasa", line 10, in <module>
    sys.exit(main())
  File "/home/ismaeel/hungrynaki/zRasa_env/lib/python3.6/site-packages/rasa/__main__.py", line 76, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/home/ismaeel/hungrynaki/zRasa_env/lib/python3.6/site-packages/rasa/cli/test.py", line 157, in test
    test_nlu(args)
  File "/home/ismaeel/hungrynaki/zRasa_env/lib/python3.6/site-packages/rasa/cli/test.py", line 123, in test_nlu
    io_utils.read_file(file),
  File "/home/ismaeel/hungrynaki/zRasa_env/lib/python3.6/site-packages/rasa/utils/io.py", line 133, in read_file
    raise ValueError("File '{}' does not exist.".format(filename))
ValueError: File '/home/ismaeel/hungrynaki/rasa/config2.yml' does not exist.
```

**Command that led to error**:
```
rasa test -c configFolder/
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @akelad will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by akelad** [comment]
Hi @ismaeelBM, sorry for getting back to you so late. Are you trying to do the model comparison mode? If yes, then please try passing the config like this `-c configFolder/config.yml configFolder/config2.yml`

**Comment by ismaeelBM** [comment]
@akelad Oh ok. Was it a change made in an update? Because I remember being able to use it by just passing in a folder in Rasa 1.0.9 I think.

**Comment by akelad** [comment]
@ismaeelBM i don't think so... although i think i saw a similar issue about this recently, @Ghostvv were you working on that?

**Comment by Ghostvv** [comment]
I'm not sure, I understand what do you want to do. You can pass several configs to `train` script or a folder with several trained models to `test`. Passing configs to test doesn't make sense

**Comment by ismaeelBM** [comment]
@Ghostvv, Oh I thought this was there to be able to do quick model comparisons instead of having to train them first and test them.
Also when I was working on an issue, I found that in the rasa/core/cli/test.py file, there is specific lines that checks on whether the argument passed is a directory or not, in order to handle them # 

From rasa/core/cli/test.py (lines 101 - 107):
```
if os.path.isdir(args.config):
            config_dir = args.config
            config_files = os.listdir(config_dir)
            args.config = [
                os.path.join(config_dir, os.path.abspath(config))
                for config in config_files
            ]
```

Which is why I thought this was something that was intended to be included as a feature. This is why i checked in an older version to see if it is something that was possible to do before. But if this is not a feature that was intended to implement, I guess I will close this as an issue.

**Comment by Ghostvv** [comment]
yes, you can pass a folder with trained models, but not configs.

**Comment by Akoparna24** [comment]
Training an initial model...
Traceback (most recent call last):
  File "c:\users\user\anaconda3\envs\rasa\lib\site-packages\rasa\utils\io.py", line 137, in read_file
    with open(filename, encoding=encoding) as f:
FileNotFoundError: [Errno 2] No such file or directory: '.\\config.yml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\user\anaconda3\envs\rasa\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\user\anaconda3\envs\rasa\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\USER\anaconda3\envs\rasa\Scripts\rasa.exe\__main__.py", line 7, in <module>
  File "c:\users\user\anaconda3\envs\rasa\lib\site-packages\rasa\__main__.py", line 91, in main
    cmdline_arguments.func(cmdline_arguments)
  File "c:\users\user\anaconda3\envs\rasa\lib\site-packages\rasa\cli\scaffold.py", line 209, in run
    init_project(args, path)
  File "c:\users\user\anaconda3\envs\rasa\lib\site-packages\rasa\cli\scaffold.py", line 121, in init_project
    print_train_or_instructions(args, path)
  File "c:\users\user\anaconda3\envs\rasa\lib\site-packages\rasa\cli\scaffold.py", line 58, in print_train_or_instructions
    args.model = rasa.train(domain, config, training_files, output)
  File "c:\users\user\anaconda3\envs\rasa\lib\site-packages\rasa\train.py", line 50, in train
    additional_arguments=additional_arguments,
  File "c:\users\user\anaconda3\envs\rasa\lib\asyncio\base_events.py", line 488, in run_until_complete
    return future.result()
  File "c:\users\user\anaconda3\envs\rasa\lib\site-packages\rasa\train.py", line 83, in train_async
    config, domain, training_files
  File "c:\users\user\anaconda3\envs\rasa\lib\site-packages\rasa\importers\importer.py", line 79, in load_from_config
    config = io_utils.read_config_file(config_path)
  File "c:\users\user\anaconda3\envs\rasa\lib\site-packages\rasa\utils\io.py", line 190, in read_config_file
    content = read_yaml(read_file(filename))
  File "c:\users\user\anaconda3\envs\rasa\lib\site-packages\rasa\utils\io.py", line 140, in read_file
    raise ValueError(f"File '{filename}' does not exist.")
ValueError: File '.\config.yml' does not exist.

I am facing this problem of config.yml. Please help
