### ISSUE TITLE
Provide custom Library path to RASA

### ISSUE THREAD

**Issue by rakesh4osdd** [RasaHQ/rasa#4219]
What to do, if "asa init --no-prompt" fails?
If the custom ld_library_path is provided then segment fault comes.
Please help.

(base) [rakesh@localhost rasax]$ rasa init --no-prompt
Traceback (most recent call last):
  File "/home/rakesh/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/rakesh/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/rakesh/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/rakesh/anaconda3/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/rakesh/anaconda3/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /lib64/libc.so.6: version `GLIBC_2.16' not found (required by /home/rakesh/anaconda3/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rakesh/anaconda3/bin/rasa", line 10, in <module>
    sys.exit(main())
  File "/home/rakesh/anaconda3/lib/python3.7/site-packages/rasa/__main__.py", line 69, in main
    set_log_level(log_level)
  File "/home/rakesh/anaconda3/lib/python3.7/site-packages/rasa/utils/common.py", line 68, in set_log_level
    update_tensorflow_log_level()
  File "/home/rakesh/anaconda3/lib/python3.7/site-packages/rasa/utils/common.py", line 87, in update_tensorflow_log_level
    import tensorflow as tf
  File "/home/rakesh/anaconda3/lib/python3.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/rakesh/anaconda3/lib/python3.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/rakesh/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/rakesh/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/rakesh/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/rakesh/anaconda3/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/rakesh/anaconda3/lib/python3.7/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/home/rakesh/anaconda3/lib/python3.7/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: /lib64/libc.so.6: version `GLIBC_2.16' not found (required by /home/rakesh/anaconda3/lib/python3.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template

**Comment by MetcalfeTom** [comment]
Try upgrading your 'libc6' package

```
sudo apt-get update
sudo apt-get install libc6
```
