### ISSUE TITLE
Interactive learning crashes when correcting the next action

### ISSUE THREAD

**Issue by nbeuchat** [RasaHQ/rasa#4237]
**Rasa version**: 1.1.8

**Rasa X version** (if used & relevant): Not used

**Python version**: 3.6

**Operating system** (windows, osx, ...): Ubuntu (Ubuntu subsystem for windows)

**Issue**: I am trying to create unhappy paths for a form using interactive learning. I have an active form `form_apartment_interest`. Interactive learning crashes when correcting the action that the bot chose when the user ask a question while in the form.

Here are the different steps of the interactive learning before the crash:
```
? The bot wants to run 'form_apartment_interest', correct?  Yes
? The bot wants to run 'action_listen', correct?  Yes

? Your input -> how long is the lease?
? Your NLU model classified 'how long is the lease?' with intent 'ask_lease_length' and there are no entities, is
 this correct?  Yes
? The bot wants to run 'form_apartment_interest', correct?  No
? What is the next action of the bot?  0.00 utter_answer_lease_length
Thanks! The bot will now run utter_answer_lease_length.

CRASH
```

I tried with other intents and it always crashes. Any idea what could be happening?

**Error (including full traceback)**:
When selecting the correct action that the bot should execute, it throws an internal server error. 

Stack trace:
```
? What is the next action of the bot?  0.00 utter_answer_lease_length
Thanks! The bot will now run utter_answer_lease_length.

2019-08-14 02:00:26 ERROR    rasa.core.training.interactive  - An exception occurred while recording messages.
Traceback (most recent call last):
  File "/home/nicolas/miniconda3/envs/chatbot/lib/python3.6/site-packages/rasa/core/training/interactive.py", line 1388, in record_messages
    endpoint, sender_id, sender_ids, plot_file
  File "/home/nicolas/miniconda3/envs/chatbot/lib/python3.6/site-packages/rasa/core/training/interactive.py", line 892, in _predict_till_next_listen
    result = await request_prediction(endpoint, sender_id)
  File "/home/nicolas/miniconda3/envs/chatbot/lib/python3.6/site-packages/rasa/core/training/interactive.py", line 147, in request_prediction
    method="post", subpath="/conversations/{}/predict".format(sender_id)
  File "/home/nicolas/miniconda3/envs/chatbot/lib/python3.6/site-packages/rasa/utils/endpoints.py", line 148, in request
    resp.status, resp.reason, await resp.content.read()
rasa.utils.endpoints.ClientResponseError: 500, Internal Server Error, body='b'{"version":"1.1.8","status":"failure","message":"An unexpected error occurred. Error: \'NoneType\' object has no attribute \'endswith\'","reason":"ConversationError","details":{},"help":null,"code":500}''
2019-08-14 02:00:26 ERROR    asyncio  - Task exception was never retrieved
future: <Task finished coro=<_serve_application.<locals>.run_interactive_io() done, defined at /home/nicolas/miniconda3/envs/chatbot/lib/python3.6/site-packages/rasa/core/training/interactive.py:1430> exception=ClientResponseError('500, Internal Server Error, body=\'b\'{"version":"1.1.8","status":"failure","message":"An unexpected error occurred. Error: \\\'NoneType\\\' object has no attribute \\\'endswith\\\'","reason":"ConversationError","details":{},"help":null,"code":500}\'\'',)>
Traceback (most recent call last):
  File "/home/nicolas/miniconda3/envs/chatbot/lib/python3.6/site-packages/rasa/core/training/interactive.py", line 1437, in run_interactive_io
    sender_id=uuid.uuid4().hex,
  File "/home/nicolas/miniconda3/envs/chatbot/lib/python3.6/site-packages/rasa/core/training/interactive.py", line 1388, in record_messages
    endpoint, sender_id, sender_ids, plot_file
  File "/home/nicolas/miniconda3/envs/chatbot/lib/python3.6/site-packages/rasa/core/training/interactive.py", line 892, in _predict_till_next_listen
    result = await request_prediction(endpoint, sender_id)
  File "/home/nicolas/miniconda3/envs/chatbot/lib/python3.6/site-packages/rasa/core/training/interactive.py", line 147, in request_prediction
    method="post", subpath="/conversations/{}/predict".format(sender_id)
  File "/home/nicolas/miniconda3/envs/chatbot/lib/python3.6/site-packages/rasa/utils/endpoints.py", line 148, in request
    resp.status, resp.reason, await resp.content.read()
rasa.utils.endpoints.ClientResponseError: 500, Internal Server Error, body='b'{"version":"1.1.8","status":"failure","message":"An unexpected error occurred. Error: \'NoneType\' object has no attribute \'endswith\'","reason":"ConversationError","details":{},"help":null,"code":500}''
```

**Command or request that led to error**:
```
? What is the next action of the bot?  0.00 utter_answer_lease_length
Thanks! The bot will now run utter_answer_lease_length.
```

**Comment by erohmensing** [comment]
Hi @nbeuchat, I think this bug is already fixed, can you update to 1.2.2 and try again?
