### ISSUE TITLE
Allow nlg to return channel specific utterances

### ISSUE THREAD

**Issue by jasonkuhrt** [RasaHQ/rasa#4260]
It is possible to setup [channel-specific utterances in the domain file](https://rasa.com/docs/rasa/core/domains/#channel-specific-utterances). But it is not possible to return channel specific utterances from an NLG server. For example, this error is logged when returning an array of utterances from our NLG server:

```
Failed to validate NLG response from API, make sure your response from the NLG endpoint is valid. For more information about the format visit https://nlu.rasa.com/...

Failed validating 'type' in schema:
    {'properties': {'attachment': {'type': ['object', 'null']},
                    'buttons': {'items': {'type': 'object'},
                                'type': ['array', 'null']},
                    'elements': {'items': {'type': 'object'},
                                 'type': ['array', 'null']},
                    'image': {'type': ['string', 'null']},
                    'text': {'type': 'string'}},
     'type': 'object'}

On instance:
    [{'custom': {'message': '{intake_first_name} {intake_last_name}, '
                            '{intake_date_of_birth}, {intake_consent}, '
                            '{intake_sex}, {intake_visit_id}, '
                            '{intake_visit_reason}',
                 'props': {'patient_visible': True,
                           'practitioner_visible': True,
                           'sender': 'rasa'}}}]
Traceback (most recent call last):
  File "/Users/jasonkuhrt/projects/dialoguemd/beautiful-mind/rasa-stack/.venv/lib/python3.7/site-packages/rasa/core/processor.py", line 439, in _run_action
    events = await action.run(output_channel, nlg, tracker, self.domain)
  File "/Users/jasonkuhrt/projects/dialoguemd/beautiful-mind/rasa-stack/.venv/lib/python3.7/site-packages/rasa/core/actions/action.py", line 184, in run
    message = await nlg.generate(self.template_name, tracker, output_channel.name())
  File "/Users/jasonkuhrt/projects/dialoguemd/beautiful-mind/rasa-stack/.venv/lib/python3.7/site-packages/rasa/core/nlg/callback.py", line 102, in generate
    if self.validate_response(response):
  File "/Users/jasonkuhrt/projects/dialoguemd/beautiful-mind/rasa-stack/.venv/lib/python3.7/site-packages/rasa/core/nlg/callback.py", line 128, in validate_response
    raise e
  File "/Users/jasonkuhrt/projects/dialoguemd/beautiful-mind/rasa-stack/.venv/lib/python3.7/site-packages/rasa/core/nlg/callback.py", line 119, in validate_response
    validate(content, nlg_response_format_spec())
  File "/Users/jasonkuhrt/projects/dialoguemd/beautiful-mind/rasa-stack/.venv/lib/python3.7/site-packages/jsonschema/validators.py", line 541, in validate
    cls(schema, *args, **kwargs).validate(instance)
  File "/Users/jasonkuhrt/projects/dialoguemd/beautiful-mind/rasa-stack/.venv/lib/python3.7/site-packages/jsonschema/validators.py", line 130, in validate
    raise error
```

The JSON schema enforced on data being returned from NLG makes clear that the list-style supported in domain file is not currently possible.

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀@tmbo will get back to you about it soon!✨

**Comment by tmbo** [comment]
Very good point, it might really just be adapting the jsonschema. Would be great if you can create a PR for that - let me know if you need any help

**Comment by erohmensing** [comment]
@tmbo here's the spec for rasa-x, which i just now realized although i added support for `custom:` also needs support for `channel:`
```
    "nlg/response": {
        "type": "object",
        "anyOf": [
            {"required": ["template", "text"]},
            {"required": ["template", "custom"]},
        ],
        "properties": {
            "template": {"type": "string"},
            "text": {"type": "string"},
            "buttons": {"type": "array", "items": {"type": "object"}},
            "elements": {"type": "array", "items": {"type": "object"}},
            "image": {"type": "string"},
            "attachment": {"type": "object"},
            "custom": {"type": ["object", "array"]},
            "id": {"type": ["string", "integer"]},
        },
    },
```

@jasonkuhrt would be great if you could test out a spec like this with your NLG server. adding `channel:` for channel-specific should just be adding` "text": {"channel": "string"},` to the properties, I believe

**Comment by tmbo** [comment]
@erohmensing can you create a PR on Rasa X to fix the schema?

**Comment by erohmensing** [comment]
of course @tmbo

**Comment by tmbo** [comment]
@erohmensing did you end up doing this?

**Comment by erohmensing** [comment]
@tmbo i'm trading this again (super late, lol) and IMO an NLG should always return _the_ response, not a list of responses. Doing channel-specific responses would be something you'd implement from the NLG server side, i.e. pick your response based on the `channel` parameter that is already provided in the request format. https://github.com/RasaHQ/rasa/blob/master/rasa/core/nlg/callback.py#L47

WDYT?

**Comment by tmbo** [comment]
yes that sounds right :+1:

**Comment by erohmensing** [comment]
cool, closing this then!
