### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get' in latest RASA Version

### ISSUE THREAD

**Issue by richie312** [RasaHQ/rasa#4263]
**Rasa version**: rasa_core==0.14.5

**Rasa X version** (if used & relevant):

**Python version**: 3.6.1

**Operating system** (windows, osx, ...): Windows 10

**Issue**:

Does not have the get module in slot class

**Error (including full traceback)**:
```
Traceback (most recent call last):
  File "train_init.py", line 18, in <module>
    agent = Agent('weather_domain.yml', policies = [MemoizationPolicy(), KerasPolicy()])
  File "C:\Users\aritra.chatterjee\AppData\Local\Programs\Python\Python36\envs\chatbot\lib\site-packages\rasa_core\agent.py", line 218, in __init__
    self.domain = self._create_domain(domain)
  File "C:\Users\aritra.chatterjee\AppData\Local\Programs\Python\Python36\envs\chatbot\lib\site-packages\rasa_core\agent.py", line 669, in _create_domain
    return Domain.load(domain)
  File "C:\Users\aritra.chatterjee\AppData\Local\Programs\Python\Python36\envs\chatbot\lib\site-packages\rasa_core\domain.py", line 122, in load
    return cls.from_yaml(read_file(filename))
  File "C:\Users\aritra.chatterjee\AppData\Local\Programs\Python\Python36\envs\chatbot\lib\site-packages\rasa_core\domain.py", line 128, in from_yaml
    return cls.from_dict(data)
  File "C:\Users\aritra.chatterjee\AppData\Local\Programs\Python\Python36\envs\chatbot\lib\site-packages\rasa_core\domain.py", line 133, in from_dict
    slots = cls.collect_slots(data.get("slots", {}))
  File "C:\Users\aritra.chatterjee\AppData\Local\Programs\Python\Python36\envs\chatbot\lib\site-packages\rasa_core\domain.py", line 221, in collect_slots
    slot_class = Slot.resolve_by_type(slot_dict[slot_name].get("type"))
AttributeError: 'NoneType' object has no attribute 'get'
```

**Command or request that led to error**:
```
python train_init.py
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by richie312** [comment]
I am following the tutorial on weatherbot. https://jpboost.com/2018/02/06/creating-a-chatbot-with-rasa-nlu-and-rasa-core/

Code: https://github.com/JustinaPetr/Weatherbot_Tutorial/tree/master/Full%20Code

this has train_init.py file and required yaml file.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @tabergma will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by richie312** [comment]
@sara-tagger : This error is initiating from the below command from train_init.py, (you can find the file in the repo; provided above.)

<code>agent = Agent('weather_domain.yml', policies = [MemoizationPolicy(), KerasPolicy()])</code>

**Comment by tabergma** [comment]
Hi @richie312! Did you consider updating to Rasa 1.0 and use the updated code here: https://github.com/JustinaPetr/Weatherbot_Tutorial/tree/master/Full_Code_Latest?

We are not maintaining the older Rasa versions anymore. So, we will not fix the issue. Feel free to fix it yourself. Otherwise, I would highly recommend to switch to Rasa 1.0.

**Comment by richie312** [comment]
@tabergma : <h4>Thank you for the update.</h4> 
<p>I was doing something wrong with the yml template and stories.md. As i corrected the yml format and used the appropriate stories.md. The issue resolved and now it is working.</p>
