### ISSUE TITLE
Rasa ignoring the username and password provided in endpoints.yml for MySQL

### ISSUE THREAD

**Issue by saideep-g** [RasaHQ/rasa#4270]
**Rasa version**:
version": "1.2.2
**Rasa X version** (if used & relevant):
NA
**Python version**:
python 3.6 (using the docker image: rasa/rasa:latest)

**Operating system** (windows, osx, ...):
Docker image: rasa/rasa:latest
host: windows 10

**Issue**:
When connecting to the MySQL tracker store, the user name and password provided in endpoints.yml is not used.

**Error (including full traceback)**:
```
rasa_1           | 2019-08-17 02:32:24 DEBUG    rasa.core.tracker_store  - Connection to SQL database 'rasa' successful
rasa_1           | 2019-08-17 02:32:24 DEBUG    rasa.core.tracker_store  - Connected to SQLTrackerStore.
rasa_1           | 2019-08-17 02:32:24 DEBUG    rasa.model  - Extracted model to '/tmp/tmpdydl3z2r'.
rasa_1           | 2019-08-17 02:32:24 DEBUG    pykwalify.compat  - Using yaml library: /usr/local/lib/python3.6/site-packages/ruamel/yaml/__init__.py
rasa_1           | 2019-08-17 02:32:44 DEBUG    rasa.core.agent  - Created a new lock for conversation 'default'
rasa_1           | 2019-08-17 02:32:44 DEBUG    rasa.core.agent  - Deleted lock for conversation 'default' (unused)
rasa_1           | 2019-08-17 02:32:44 ERROR    rasa.core.channels.channel  - An exception occured while handling user message '*******************intentionally masked***********'.
rasa_1           | Traceback (most recent call last):
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2265, in _wrap_pool_connect
rasa_1           |     return fn()
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 363, in connect
rasa_1           |     return _ConnectionFairy._checkout(self)
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
rasa_1           |     fairy = _ConnectionRecord.checkout(pool)
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
rasa_1           |     rec = pool._do_get()
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 139, in _do_get
rasa_1           |     self._dec_overflow()
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
rasa_1           |     compat.reraise(exc_type, exc_value, exc_tb)
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
rasa_1           |     raise value
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 136, in _do_get
rasa_1           |     return self._create_connection()
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
rasa_1           |     return _ConnectionRecord(self)
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
rasa_1           |     self.__connect(first_connect_check=True)
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
rasa_1           |     connection = pool._invoke_creator(self)
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
rasa_1           |     return dialect.connect(*cargs, **cparams)
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 453, in connect
rasa_1           |     return self.dbapi.connect(*cargs, **cparams)
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/MySQLdb/__init__.py", line 84, in Connect
rasa_1           |     return Connection(*args, **kwargs)
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 166, in __init__
rasa_1           |     super(Connection, self).__init__(*args, **kwargs2)
rasa_1           | MySQLdb._exceptions.OperationalError: (1045, "Access denied for user 'root'@'172.18.0.4' (using password: NO)")
rasa_1           |
rasa_1           | The above exception was the direct cause of the following exception:
rasa_1           |
rasa_1           | Traceback (most recent call last):
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/rasa/core/channels/channel.py", line 490, in receive
rasa_1           |     text, collector, sender_id, input_channel=input_channel
rasa_1           |   File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
rasa_1           |     return self.gen.send(None)
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/rasa/core/channels/channel.py", line 80, in handler
rasa_1           |     await app.agent.handle_message(*args, **kwargs)
rasa_1           |   File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
rasa_1           |     return self.gen.send(None)
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/rasa/core/agent.py", line 491, in handle_message
rasa_1           |     return await processor.handle_message(message)
rasa_1           |   File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
rasa_1           |     return self.gen.send(None)
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/rasa/core/processor.py", line 80, in handle_message
rasa_1           |     tracker = await self.log_message(message)
rasa_1           |   File "/usr/local/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
rasa_1           |     return self.gen.send(None)
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/rasa/core/processor.py", line 132, in log_message
rasa_1           |     tracker = self._get_tracker(message.sender_id)
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/rasa/core/processor.py", line 532, in _get_tracker
rasa_1           |     return self.tracker_store.get_or_create_tracker(sender_id)
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/rasa/core/tracker_store.py", line 73, in get_or_create_tracker
rasa_1           |     tracker = self.retrieve(sender_id)
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/rasa/core/tracker_store.py", line 450, in retrieve
rasa_1           |     result = query.filter_by(sender_id=sender_id).all()
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3174, in all
rasa_1           |     return list(self)
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3330, in __iter__
rasa_1           |     return self._execute_and_instances(context)
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3352, in _execute_and_instances
rasa_1           |     querycontext, self._connection_from_session, close_with_result=True
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3367, in _get_bind_args
rasa_1           |     mapper=self._bind_mapper(), clause=querycontext.statement, **kw
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3345, in _connection_from_session
rasa_1           |     conn = self.session.connection(**kw)
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1124, in connection
rasa_1           |     execution_options=execution_options,
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1130, in _connection_for_bind
rasa_1           |     engine, execution_options
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 431, in _connection_for_bind
rasa_1           |     conn = bind._contextual_connect()
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2229, in _contextual_connect
rasa_1           |     self._wrap_pool_connect(self.pool.connect, None),
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2269, in _wrap_pool_connect
rasa_1           |     e, dialect, self
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1536, in _handle_dbapi_exception_noconnection
rasa_1           |     util.raise_from_cause(sqlalchemy_exception, exc_info)
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
rasa_1           |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
rasa_1           |     raise value.with_traceback(tb)
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 2265, in _wrap_pool_connect
rasa_1           |     return fn()
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 363, in connect
rasa_1           |     return _ConnectionFairy._checkout(self)
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 760, in _checkout
rasa_1           |     fairy = _ConnectionRecord.checkout(pool)
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 492, in checkout
rasa_1           |     rec = pool._do_get()
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 139, in _do_get
rasa_1           |     self._dec_overflow()
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
rasa_1           |     compat.reraise(exc_type, exc_value, exc_tb)
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
rasa_1           |     raise value
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/impl.py", line 136, in _do_get
rasa_1           |     return self._create_connection()
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 308, in _create_connection
rasa_1           |     return _ConnectionRecord(self)
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 437, in __init__
rasa_1           |     self.__connect(first_connect_check=True)
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/pool/base.py", line 639, in __connect
rasa_1           |     connection = pool._invoke_creator(self)
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
rasa_1           |     return dialect.connect(*cargs, **cparams)
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 453, in connect
rasa_1           |     return self.dbapi.connect(*cargs, **cparams)
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/MySQLdb/__init__.py", line 84, in Connect
rasa_1           |     return Connection(*args, **kwargs)
rasa_1           |   File "/usr/local/lib/python3.6/site-packages/MySQLdb/connections.py", line 166, in __init__
rasa_1           |     super(Connection, self).__init__(*args, **kwargs2)
rasa_1           | sqlalchemy.exc.OperationalError: (MySQLdb._exceptions.OperationalError) (1045, "Access denied for user 'root'@'172.18.0.4' (using password: NO)")
rasa_1           | (Background on this error at: http://sqlalche.me/e/e3q8)

```

**Command or request that led to error**:
```
docker-compose up and then sending a API request to below URL with 'message' and 'sending' in json format:
localhost:5005/webhooks/rest/webhook
```

**Content of configuration file (config.yml)** (if relevant):
```yml
Not Relevant
```

**Content of domain file (domain.yml)** (if relevant):
```yml
not relevant
```
**docker-compose: (relevant portion)**
```
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - .data/mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_ALLOW_EMPTY_PASSWORD: "No"
      MYSQL_DATABASE: rasa
```
**tracker store: (relevant portion)**
```
tracker_store:
    type: SQL
    dialect: "mysql"  # the dialect used to interact with the db
    #url: "mysql://root:example@mysql:3306/rasa"  # (optional) host of the sql db
    url: "mysql://mysql:3306"
    db: rasa  # path to your db
    username:  root # username used for authentication
    password:  example # password used for authentication
```
see the below post to understand the alternative used to overcome this issue but to maintain consistency, rasa should be able to handle this.
https://forum.rasa.com/t/could-not-create-tables-mysqldb-exceptions-operationalerror-mysql-tracker-store/14419

**Comment by sara-tagger** [comment]
Thanks for the issue, @tmbo will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by tmbo** [comment]
Yes that is def a bug. We haven't tested mysql in depth (but I don't see why it wouldn't work). 

Can you provide a PR with a fix for this?
