### ISSUE TITLE
PermissionError: [Errno 1] Operation not permitted when run rasa shell in docker

### ISSUE THREAD

**Issue by ngochuyenluu** [RasaHQ/rasa#4317]
**Rasa version**: 1.2.3

**Rasa X version** (if used & relevant): 0.20.1

**Python version**: 3.6.8

**Operating system** (windows, osx, ...): Linux

**Issue**: PermissionError: [Errno 1] Operation not permitted when run rasa shell in docker

**Error (including full traceback)**:
```
 File "/usr/local/lib/python3.6/site-packages/rasa/core/run.py", line 126, in run_cmdline_io
    server_url=constants.DEFAULT_SERVER_FORMAT.format(port)
  File "/usr/local/lib/python3.6/site-packages/rasa/core/channels/console.py", line 129, in record_messages
    text = get_user_input(button_question)
  File "/usr/local/lib/python3.6/site-packages/rasa/core/channels/console.py", line 77, in get_user_input
    style=Style([("qmark", "#b373d6"), ("", "#b373d6")]),
  File "/usr/local/lib/python3.6/site-packages/questionary/question.py", line 45, in ask
    return self.unsafe_ask(patch_stdout)
  File "/usr/local/lib/python3.6/site-packages/questionary/question.py", line 59, in unsafe_ask
    return self.application.run()
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 709, in run
    return run()
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 683, in run
    return f.result()
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/eventloop/future.py", line 149, in result
    raise self._exception
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/eventloop/coroutine.py", line 90, in step_next
    new_f = coroutine.throw(exc)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 658, in _run_async2
    result = yield f
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/eventloop/coroutine.py", line 86, in step_next
    new_f = coroutine.send(None)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 598, in _run_async
    with self.input.attach(read_from_input):
  File "/usr/local/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/input/vt100.py", line 147, in _attached_input
    loop.add_reader(fd, callback)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/eventloop/posix.py", line 272, in add_reader
    self.selector.register(fd)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/eventloop/select.py", line 76, in register
    sel.register(fd)
  File "/usr/local/lib/python3.6/site-packages/prompt_toolkit/eventloop/select.py", line 131, in register
    self._sel.register(fd, selectors.EVENT_READ, None)
  File "/usr/local/lib/python3.6/selectors.py", line 412, in register
    self._epoll.register(key.fd, epoll_events)
PermissionError: [Errno 1] Operation not permitted

```

**Command or request that led to error**:
```
rasa shell
```

**Content of configuration file (config.yml)** (if relevant):
```yml
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline: supervised_embeddings

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @tmbo will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by tmbo** [comment]
Are you running in docker-compose or directly in docker? This sounds a lot like you are not in an interactive shell. How do you run the container?

**Comment by ngochuyenluu** [comment]
Hi, I runned directly in docker, just followed your user guide (running rasa with docker). After training my chatbot, I run the command: 
```
docker run -it -v $(pwd):/app rasa/rasa shell
```
And I had the problem above. Is there any suggestion? Thank you a lot.

**Comment by ngochuyenluu** [comment]
Hello @tmbo, as you suggested, I have tried to run with docker-compose, but I got another error from #4339. Just can figure out where is the problem. If you have any advice, it will be cool. Thank you.

**Comment by VinceD2049** [comment]
You can workaround this by running rasa shell is a docker in 2 steps :

1/ 
```
docker run -it  -v $(pwd):/app --entrypoint "/bin/bash" rasa/rasa
```

2/
```
rasa shell
2020-04-30 15:39:24 INFO     root  - Connecting to channel 'cmdline' which was specified by the '--connector' argument. Any other channels will be ignored. To connect to all given channels, omit the '--connector' argument.
2020-04-30 15:39:24 INFO     root  - Starting Rasa server on http://localhost:5005
2020-04-30 15:39:25.286654: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (303)
Bot loaded. Type a message and press enter (use '/stop' to exit): 
Your input ->                                                                                                                                                                                                      
```

**Comment by madanmeena** [comment]
> You can execute rasa shell is a docker like this :
> 
> ```
> docker run  --user $(id -u):$(id -g) -it -v $(pwd):/app --entrypoint rasa rasa/rasa shell  
> ```
Yes that works, thanks

If i run
docker run -v $(pwd):/app rasa/rasa:1.10.12-full shell 
i get the following error
2020-09-28 07:15:32 INFO     root  - Rasa server is up and running.
Warning: Output is not to a terminal (fd=1).
Warning: Input is not to a terminal (fd=0).
2020-09-28 07:15:33 ERROR    asyncio  - Task exception was never retrieved
future: <Task finished coro=<configure_app.<locals>.run_cmdline_io() done, defined at /opt/venv/lib/python3.7/site-packages/rasa/core/run.py:128> exception=PermissionError(1, 'Operation not permitted')>
Traceback (most recent call last):
  File "/opt/venv/lib/python3.7/site-packages/rasa/core/run.py", line 134, in run_cmdline_io
    sender_id=conversation_id,
  File "/opt/venv/lib/python3.7/site-packages/rasa/core/channels/console.py", line 142, in record_messages
    text = get_user_input(button_question)
  File "/opt/venv/lib/python3.7/site-packages/rasa/core/channels/console.py", line 78, in get_user_input
    style=Style([("qmark", "#b373d6"), ("", "#b373d6")]),
  File "/opt/venv/lib/python3.7/site-packages/questionary/question.py", line 45, in ask
    return self.unsafe_ask(patch_stdout)
  File "/opt/venv/lib/python3.7/site-packages/questionary/question.py", line 59, in unsafe_ask
    return self.application.run()
  File "/opt/venv/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 736, in run
    return run()
  File "/opt/venv/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 710, in run
    return f.result()
  File "/opt/venv/lib/python3.7/site-packages/prompt_toolkit/eventloop/future.py", line 151, in result
    raise self._exception
  File "/opt/venv/lib/python3.7/site-packages/prompt_toolkit/eventloop/coroutine.py", line 92, in step_next
    new_f = coroutine.throw(exc)
  File "/opt/venv/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 685, in _run_async2
    result = yield f
  File "/opt/venv/lib/python3.7/site-packages/prompt_toolkit/eventloop/coroutine.py", line 88, in step_next
    new_f = coroutine.send(None)
  File "/opt/venv/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 625, in _run_async
    with self.input.attach(read_from_input):
  File "/usr/local/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/opt/venv/lib/python3.7/site-packages/prompt_toolkit/input/vt100.py", line 150, in _attached_input
    loop.add_reader(fd, callback)
  File "/opt/venv/lib/python3.7/site-packages/prompt_toolkit/eventloop/posix.py", line 273, in add_reader
    self.selector.register(fd)
  File "/opt/venv/lib/python3.7/site-packages/prompt_toolkit/eventloop/select.py", line 78, in register
    sel.register(fd)
  File "/opt/venv/lib/python3.7/site-packages/prompt_toolkit/eventloop/select.py", line 133, in register
    self._sel.register(fd, selectors.EVENT_READ, None)
  File "/usr/local/lib/python3.7/selectors.py", line 359, in register
    self._selector.register(key.fd, poller_events)
PermissionError: [Errno 1] Operation not permitted

I have been able to run the above command successfully for training as follows
docker run -v $(pwd):/app rasa/rasa:1.10.12-full shell

Command shared by @VinceD2049 runs without an issue, I did specify the model as per my need
docker run  --user $(id -u):$(id -g) -it -v $(pwd):/app --entrypoint rasa rasa/rasa:1.10.12-full shell

**Comment by mkopinsky** [comment]
I got this error; it had nothing to do with file permissions and was because I forgot to pass `-it` to `docker run`
