### ISSUE TITLE
Docker-compose up [Errno 2] No such file or directory: '/tmp/tmpw67o33_3/nlu/component_6_EmbeddingIntentClassifier.tf_config.pkl'

### ISSUE THREAD

**Issue by ngochuyenluu** [RasaHQ/rasa#4339]
**Rasa version**:1.2.3

**Rasa X version** (if used & relevant):0.20.1

**Python version**:3.6.8

**Operating system** (windows, osx, ...): Linux

**Issue**: rasa.core.agent  - Could not load model due to [Errno 2] No such file or directory: '/tmp/tmpw67o33_3/nlu/component_6_EmbeddingIntentClassifier.tf_config.pkl'.

**Error (including full traceback)**:
```
Starting chabot_hotline_rasa_1 ... done
Attaching to chabot_hotline_rasa_1
rasa_1  | 2019-08-28 12:32:10 INFO     root  - Starting Rasa server on http://localhost:5005
rasa_1  | 2019-08-28 12:32:11 ERROR    rasa.core.agent  - Could not load model due to [Errno 2] No such file or directory: '/tmp/tmpw67o33_3/nlu/component_6_EmbeddingIntentClassifier.tf_config.pkl'.
rasa_1  | Experienced exception while trying to serve
rasa_1  | Traceback (most recent call last):
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 1096, in run
rasa_1  |     serve(**server_settings)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/sanic/server.py", line 742, in serve
rasa_1  |     trigger_events(before_start, loop)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/sanic/server.py", line 604, in trigger_events
rasa_1  |     loop.run_until_complete(result)
rasa_1  |   File "uvloop/loop.pyx", line 1417, in uvloop.loop.Loop.run_until_complete
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/run.py", line 233, in load_agent_on_start
rasa_1  |     action_endpoint=endpoints.action,
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/agent.py", line 258, in load_agent
rasa_1  |     remote_storage=remote_storage,
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/agent.py", line 921, in load_local_model
rasa_1  |     remote_storage=remote_storage,
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/agent.py", line 368, in load
rasa_1  |     interpreter = NaturalLanguageInterpreter.create(nlu_model)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/interpreter.py", line 57, in create
rasa_1  |     return RasaNLUInterpreter(model_directory=obj)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/interpreter.py", line 263, in __init__
rasa_1  |     self._load_interpreter()
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/interpreter.py", line 286, in _load_interpreter
rasa_1  |     self.interpreter = Interpreter.load(self.model_directory)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/nlu/model.py", line 301, in load
rasa_1  |     return Interpreter.create(model_metadata, component_builder, skip_validation)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/nlu/model.py", line 328, in create
rasa_1  |     component_meta, model_metadata.model_dir, model_metadata, **context
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/nlu/components.py", line 437, in load_component
rasa_1  |     component_meta, model_dir, model_metadata, cached_component, **context
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/nlu/registry.py", line 182, in load_component_by_meta
rasa_1  |     component_meta, model_dir, metadata, cached_component, **kwargs
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/nlu/classifiers/embedding_intent_classifier.py", line 580, in load
rasa_1  |     with open(os.path.join(model_dir, file_name + ".tf_config.pkl"), "rb") as f:
rasa_1  | FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpw67o33_3/nlu/component_6_EmbeddingIntentClassifier.tf_config.pkl'
rasa_1  | Traceback (most recent call last):
rasa_1  |   File "/usr/local/bin/rasa", line 10, in <module>
rasa_1  |     sys.exit(main())
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/__main__.py", line 76, in main
rasa_1  |     cmdline_arguments.func(cmdline_arguments)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/cli/run.py", line 119, in run
rasa_1  |     rasa.run(**vars(args))
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/run.py", line 55, in run
rasa_1  |     **kwargs
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/run.py", line 194, in serve_application
rasa_1  |     app.run(host="0.0.0.0", port=port, ssl=ssl_context)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 1096, in run
rasa_1  |     serve(**server_settings)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/sanic/server.py", line 742, in serve
rasa_1  |     trigger_events(before_start, loop)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/sanic/server.py", line 604, in trigger_events
rasa_1  |     loop.run_until_complete(result)
rasa_1  |   File "uvloop/loop.pyx", line 1417, in uvloop.loop.Loop.run_until_complete
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/run.py", line 233, in load_agent_on_start
rasa_1  |     action_endpoint=endpoints.action,
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/agent.py", line 258, in load_agent
rasa_1  |     remote_storage=remote_storage,
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/agent.py", line 921, in load_local_model
rasa_1  |     remote_storage=remote_storage,
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/agent.py", line 368, in load
rasa_1  |     interpreter = NaturalLanguageInterpreter.create(nlu_model)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/interpreter.py", line 57, in create
rasa_1  |     return RasaNLUInterpreter(model_directory=obj)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/interpreter.py", line 263, in __init__
rasa_1  |     self._load_interpreter()
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/interpreter.py", line 286, in _load_interpreter
rasa_1  |     self.interpreter = Interpreter.load(self.model_directory)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/nlu/model.py", line 301, in load
rasa_1  |     return Interpreter.create(model_metadata, component_builder, skip_validation)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/nlu/model.py", line 328, in create
rasa_1  |     component_meta, model_metadata.model_dir, model_metadata, **context
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/nlu/components.py", line 437, in load_component
rasa_1  |     component_meta, model_dir, model_metadata, cached_component, **context
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/nlu/registry.py", line 182, in load_component_by_meta
rasa_1  |     component_meta, model_dir, metadata, cached_component, **kwargs
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/nlu/classifiers/embedding_intent_classifier.py", line 580, in load
rasa_1  |     with open(os.path.join(model_dir, file_name + ".tf_config.pkl"), "rb") as f:
rasa_1  | FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpw67o33_3/nlu/component_6_EmbeddingIntentClassifier.tf_config.pkl'
```

**Command or request that led to error**:
```
docker-compose up
```

**Content of configuration file (config.yml)** (if relevant):
```yml
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline: supervised_embeddings

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
```

**Docker-compose.yml**
````
version: '3.0'
services:
  rasa:
    image: rasa/rasa:latest-full
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
````

Hello everyone, after having problem with running docker, I give a try with docker compose, just follow the tutorial to launch it. But it gives me other error that it could not find the file component_6_EmbeddingIntentClassifier.tf_config.pkl. In my models/nlu/nlu_model, there are some files which have names such as: component_1_RegexFeaturizer.pkl, component_2_CRFEntityExtractor.pkl, component_4_CountVectorsFeaturizer.pkl, component_5_EmbeddingIntentClassifier.ckpt.data-00000-of-00001 but I couldn't find the file component_6_EmbeddingIntentClassifier.tf_config.pk.

Is there any steps that I missed out or something wrong? If anyone can give me recommendations, it would be great. Thanks a lot!

**Comment by sara-tagger** [comment]
Thanks for the issue, @akelad will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by akelad** [comment]
@ngochuyenluu with which version was that model trained? It sounds to me like it's a version pre 1.x, meaning it's not supported. You can try deleting the models from that folder.

**Comment by ngochuyenluu** [comment]
Hello @akelad, thank you for your answer. I trained the model for 6months ago, and as you suggested, I removed all the files in folder models, retrained data with newest rasa version. After run ````docker-compose up````, it gave me the error:
````
Starting chabot_hotline_rasa_1 ... done
Attaching to chabot_hotline_rasa_1
rasa_1  | 2019-08-29 12:40:00 INFO     root  - Starting Rasa server on http://localhost:5005
rasa_1  | 2019-08-29 12:40:00 ERROR    rasa.core.agent  - Could not load model due to The model version is to old to be loaded by this Rasa NLU instance. Either retrain the model, or run withan older version. Model version: 1.2.3 Instance version: 1.3.0a1.
rasa_1  | Experienced exception while trying to serve
rasa_1  | Traceback (most recent call last):
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 1096, in run
rasa_1  |     serve(**server_settings)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/sanic/server.py", line 742, in serve
rasa_1  |     trigger_events(before_start, loop)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/sanic/server.py", line 604, in trigger_events
rasa_1  |     loop.run_until_complete(result)
rasa_1  |   File "uvloop/loop.pyx", line 1417, in uvloop.loop.Loop.run_until_complete
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/run.py", line 233, in load_agent_on_start
rasa_1  |     action_endpoint=endpoints.action,
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/agent.py", line 258, in load_agent
rasa_1  |     remote_storage=remote_storage,
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/agent.py", line 921, in load_local_model
rasa_1  |     remote_storage=remote_storage,
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/agent.py", line 368, in load
rasa_1  |     interpreter = NaturalLanguageInterpreter.create(nlu_model)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/interpreter.py", line 57, in create
rasa_1  |     return RasaNLUInterpreter(model_directory=obj)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/interpreter.py", line 263, in __init__
rasa_1  |     self._load_interpreter()
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/interpreter.py", line 286, in _load_interpreter
rasa_1  |     self.interpreter = Interpreter.load(self.model_directory)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/nlu/model.py", line 300, in load
rasa_1  |     Interpreter.ensure_model_compatibility(model_metadata)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/nlu/model.py", line 275, in ensure_model_compatibility
rasa_1  |     "".format(model_version, rasa.__version__)
rasa_1  | rasa.nlu.model.UnsupportedModelError: The model version is to old to be loaded by this Rasa NLU instance. Either retrain the model, or run withan older version. Model version: 1.2.3 Instance version: 1.3.0a1
rasa_1  | Traceback (most recent call last):
rasa_1  |   File "/usr/local/bin/rasa", line 10, in <module>
rasa_1  |     sys.exit(main())
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/__main__.py", line 76, in main
rasa_1  |     cmdline_arguments.func(cmdline_arguments)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/cli/run.py", line 119, in run
rasa_1  |     rasa.run(**vars(args))
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/run.py", line 55, in run
rasa_1  |     **kwargs
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/run.py", line 194, in serve_application
rasa_1  |     app.run(host="0.0.0.0", port=port, ssl=ssl_context)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 1096, in run
rasa_1  |     serve(**server_settings)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/sanic/server.py", line 742, in serve
rasa_1  |     trigger_events(before_start, loop)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/sanic/server.py", line 604, in trigger_events
rasa_1  |     loop.run_until_complete(result)
rasa_1  |   File "uvloop/loop.pyx", line 1417, in uvloop.loop.Loop.run_until_complete
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/run.py", line 233, in load_agent_on_start
rasa_1  |     action_endpoint=endpoints.action,
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/agent.py", line 258, in load_agent
rasa_1  |     remote_storage=remote_storage,
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/agent.py", line 921, in load_local_model
rasa_1  |     remote_storage=remote_storage,
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/agent.py", line 368, in load
rasa_1  |     interpreter = NaturalLanguageInterpreter.create(nlu_model)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/interpreter.py", line 57, in create
rasa_1  |     return RasaNLUInterpreter(model_directory=obj)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/interpreter.py", line 263, in __init__
rasa_1  |     self._load_interpreter()
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/interpreter.py", line 286, in _load_interpreter
rasa_1  |     self.interpreter = Interpreter.load(self.model_directory)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/nlu/model.py", line 300, in load
rasa_1  |     Interpreter.ensure_model_compatibility(model_metadata)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/nlu/model.py", line 275, in ensure_model_compatibility
rasa_1  |     "".format(model_version, rasa.__version__)
rasa_1  | rasa.nlu.model.UnsupportedModelError: The model version is to old to be loaded by this Rasa NLU instance. Either retrain the model, or run withan older version. Model version: 1.2.3 Instance version: 1.3.0a1
chabot_hotline_rasa_1 exited with code 1
(Chabot_hotline) (base) nluu@nluu-ThinkPad-T440:~/PycharmProjects/Chabot_hotline$ docker-compose up
Starting chabot_hotline_rasa_1 ... done
Attaching to chabot_hotline_rasa_1
rasa_1  | 2019-08-29 12:52:45 INFO     root  - Starting Rasa server on http://localhost:5005
rasa_1  | 2019-08-29 12:52:45 ERROR    rasa.core.agent  - Could not load model due to The model version is to old to be loaded by this Rasa NLU instance. Either retrain the model, or run withan older version. Model version: 1.2.3 Instance version: 1.3.0a1.
rasa_1  | Experienced exception while trying to serve
rasa_1  | Traceback (most recent call last):
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 1096, in run
rasa_1  |     serve(**server_settings)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/sanic/server.py", line 742, in serve
rasa_1  |     trigger_events(before_start, loop)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/sanic/server.py", line 604, in trigger_events
rasa_1  |     loop.run_until_complete(result)
rasa_1  |   File "uvloop/loop.pyx", line 1417, in uvloop.loop.Loop.run_until_complete
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/run.py", line 233, in load_agent_on_start
rasa_1  |     action_endpoint=endpoints.action,
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/agent.py", line 258, in load_agent
rasa_1  |     remote_storage=remote_storage,
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/agent.py", line 921, in load_local_model
rasa_1  |     remote_storage=remote_storage,
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/agent.py", line 368, in load
rasa_1  |     interpreter = NaturalLanguageInterpreter.create(nlu_model)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/interpreter.py", line 57, in create
rasa_1  |     return RasaNLUInterpreter(model_directory=obj)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/interpreter.py", line 263, in __init__
rasa_1  |     self._load_interpreter()
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/interpreter.py", line 286, in _load_interpreter
rasa_1  |     self.interpreter = Interpreter.load(self.model_directory)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/nlu/model.py", line 300, in load
rasa_1  |     Interpreter.ensure_model_compatibility(model_metadata)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/nlu/model.py", line 275, in ensure_model_compatibility
rasa_1  |     "".format(model_version, rasa.__version__)
rasa_1  | rasa.nlu.model.UnsupportedModelError: The model version is to old to be loaded by this Rasa NLU instance. Either retrain the model, or run withan older version. Model version: 1.2.3 Instance version: 1.3.0a1
rasa_1  | Traceback (most recent call last):
rasa_1  |   File "/usr/local/bin/rasa", line 10, in <module>
rasa_1  |     sys.exit(main())
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/__main__.py", line 76, in main
rasa_1  |     cmdline_arguments.func(cmdline_arguments)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/cli/run.py", line 119, in run
rasa_1  |     rasa.run(**vars(args))
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/run.py", line 55, in run
rasa_1  |     **kwargs
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/run.py", line 194, in serve_application
rasa_1  |     app.run(host="0.0.0.0", port=port, ssl=ssl_context)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 1096, in run
rasa_1  |     serve(**server_settings)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/sanic/server.py", line 742, in serve
rasa_1  |     trigger_events(before_start, loop)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/sanic/server.py", line 604, in trigger_events
rasa_1  |     loop.run_until_complete(result)
rasa_1  |   File "uvloop/loop.pyx", line 1417, in uvloop.loop.Loop.run_until_complete
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/run.py", line 233, in load_agent_on_start
rasa_1  |     action_endpoint=endpoints.action,
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/agent.py", line 258, in load_agent
rasa_1  |     remote_storage=remote_storage,
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/agent.py", line 921, in load_local_model
rasa_1  |     remote_storage=remote_storage,
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/agent.py", line 368, in load
rasa_1  |     interpreter = NaturalLanguageInterpreter.create(nlu_model)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/interpreter.py", line 57, in create
rasa_1  |     return RasaNLUInterpreter(model_directory=obj)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/interpreter.py", line 263, in __init__
rasa_1  |     self._load_interpreter()
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/core/interpreter.py", line 286, in _load_interpreter
rasa_1  |     self.interpreter = Interpreter.load(self.model_directory)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/nlu/model.py", line 300, in load
rasa_1  |     Interpreter.ensure_model_compatibility(model_metadata)
rasa_1  |   File "/usr/local/lib/python3.6/site-packages/rasa/nlu/model.py", line 275, in ensure_model_compatibility
rasa_1  |     "".format(model_version, rasa.__version__)
rasa_1  | rasa.nlu.model.UnsupportedModelError: The model version is to old to be loaded by this Rasa NLU instance. Either retrain the model, or run withan older version. Model version: 1.2.3 Instance version: 1.3.0a1
````
I know there is relevant with #2132 but I didn't found the answer because as I know, rasa_core and rasa_nlu are combined to become rasa. So why the model version that I used is too old with rasa_nlu?
Thank you for your answer. I can open a new issue if you want.
