### ISSUE TITLE
rasa-x 0.20

### ISSUE THREAD

**Issue by baudzhou** [RasaHQ/rasa#4395]
**Rasa version**: 1.2.7

**Rasa X version** (if used & relevant): 0.20.2

**Python version**: 3.6.8

**Operating system** (windows, osx, ...): ubuntu 1604

**Issue**: 
When using rasa-x interactive learning mode, itents can be recognized but next action never be proposed. When I click the "enter" button, rasa-x performes nothing.
But the normal conversation mode works fine.

![image](https://user-images.githubusercontent.com/26374579/64307861-ec384e80-cfc9-11e9-89f9-7b854f66457e.png)

**Error (including full traceback)**:

```
2019-09-05 10:56:34 DEBUG    rasa.core.tracker_store  - Recreating tracker for id '3d7851c2056a4e68b284ad5c53c9d27e'
2019-09-05 10:56:34 DEBUG    rasa.core.tracker_store  - Recreating tracker for id '3d7851c2056a4e68b284ad5c53c9d27e'
2019-09-05 10:56:34 DEBUG    rasax.community.services.data_service  - Dumping NLU data to file 'data/nlu.md'.
Exception occurred while handling uri: 'http://localhost:5002/api/conversations/a431229188b648feb7f557b948ed8899/events'
Traceback (most recent call last):
  File "/usr/local/miniconda3/lib/python3.6/site-packages/sanic/app.py", line 917, in handle_request
    response = await response
  File "/usr/local/miniconda3/lib/python3.6/site-packages/rasax/community/api/decorators.py", line 176, in decorated_function
    return await await_and_return_response(args, kwargs, request)
  File "/usr/local/miniconda3/lib/python3.6/site-packages/rasax/community/api/decorators.py", line 106, in await_and_return_response
    response = await response
  File "/usr/local/miniconda3/lib/python3.6/site-packages/rasax/community/api/decorators.py", line 46, in decorated_function
    return await response
  File "/usr/local/miniconda3/lib/python3.6/site-packages/rasax/community/api/blueprints/stack.py", line 255, in post_event
    user, config.project_name, _event
  File "/usr/local/miniconda3/lib/python3.6/site-packages/rasax/community/services/data_service.py", line 280, in save_user_event_as_example
    return self.save_example(user["username"], project_id, example)
  File "/usr/local/miniconda3/lib/python3.6/site-packages/rasax/community/services/data_service.py", line 243, in save_example
    {"username": username}, project_id, example, existing_id
  File "/usr/local/miniconda3/lib/python3.6/site-packages/rasax/community/services/data_service.py", line 304, in replac e_example
    self._dump_data_in_local_mode()
  File "/usr/local/miniconda3/lib/python3.6/site-packages/rasax/community/services/data_service.py", line 345, in _dump_data_in_local_mode
    self._dump_nlu_data(project_id)
  File "/usr/local/miniconda3/lib/python3.6/site-packages/rasax/community/services/data_service.py", line 353, in _dump_nlu_data
    training_data = self.get_nlu_training_data_object(file_name, project)
  File "/usr/local/miniconda3/lib/python3.6/site-packages/rasax/community/services/data_service.py", line 928, in get_nlu_training_data_object
    filename, project_id, should_include_lookup_table_entries
  File "/usr/local/miniconda3/lib/python3.6/site-packages/rasax/community/services/data_service.py", line 128, in create_formatted_training_data
    training_examples, regex_features, lookup_tables, entity_synonyms
  File "/usr/local/miniconda3/lib/python3.6/site-packages/rasax/community/services/data_service.py", line 989, in nlu_format
    formatted_entities = format_entities(e)
  File "/usr/local/miniconda3/lib/python3.6/site-packages/rasax/community/services/data_service.py", line 969, in format_entities
    "start": int(ent["start"]),
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

```

**Command or request that led to error**:
This is the brower console error.
```
2.fa55e2b7.chunk.js:1 POST http://47.107.243.166:5002/api/conversations/bf7acfc4bcb248dcbc631ca05f6b0a45/events 500 (Internal Server Error)
(anonymous) @ 2.fa55e2b7.chunk.js:1
t.exports @ 2.fa55e2b7.chunk.js:1
t.exports @ 2.fa55e2b7.chunk.js:1
Promise.then (async)
s.request @ 2.fa55e2b7.chunk.js:1
s.<computed> @ 2.fa55e2b7.chunk.js:1
(anonymous) @ 2.fa55e2b7.chunk.js:1
(anonymous) @ main.cbf6002c.chunk.js:1
c @ 2.fa55e2b7.chunk.js:1
(anonymous) @ 2.fa55e2b7.chunk.js:1
t.<computed> @ 2.fa55e2b7.chunk.js:1
r @ 2.fa55e2b7.chunk.js:1
u @ 2.fa55e2b7.chunk.js:1
(anonymous) @ 2.fa55e2b7.chunk.js:1
(anonymous) @ 2.fa55e2b7.chunk.js:1
(anonymous) @ main.cbf6002c.chunk.js:1
I.<computed> @ 2.fa55e2b7.chunk.js:1
(anonymous) @ 2.fa55e2b7.chunk.js:1
v @ 2.fa55e2b7.chunk.js:1
d @ 2.fa55e2b7.chunk.js:1
X @ 2.fa55e2b7.chunk.js:1
(anonymous) @ 2.fa55e2b7.chunk.js:1
v @ 2.fa55e2b7.chunk.js:1
I.<computed> @ 2.fa55e2b7.chunk.js:1
(anonymous) @ 2.fa55e2b7.chunk.js:1
v @ 2.fa55e2b7.chunk.js:1
d @ 2.fa55e2b7.chunk.js:1
s @ 2.fa55e2b7.chunk.js:1
c @ 2.fa55e2b7.chunk.js:1
t.put @ 2.fa55e2b7.chunk.js:1
(anonymous) @ 2.fa55e2b7.chunk.js:1
p @ 2.fa55e2b7.chunk.js:1
y @ 2.fa55e2b7.chunk.js:1
d @ 2.fa55e2b7.chunk.js:1
O.t.put @ 2.fa55e2b7.chunk.js:1
(anonymous) @ 2.fa55e2b7.chunk.js:1
(anonymous) @ 2.fa55e2b7.chunk.js:1
(anonymous) @ 2.fa55e2b7.chunk.js:1
(anonymous) @ main.cbf6002c.chunk.js:1
onClick @ main.cbf6002c.chunk.js:1
(anonymous) @ 2.fa55e2b7.chunk.js:1
h @ 2.fa55e2b7.chunk.js:1
(anonymous) @ 2.fa55e2b7.chunk.js:1
k @ 2.fa55e2b7.chunk.js:1
O @ 2.fa55e2b7.chunk.js:1
E @ 2.fa55e2b7.chunk.js:1
D @ 2.fa55e2b7.chunk.js:1
Sn @ 2.fa55e2b7.chunk.js:1
Pu @ 2.fa55e2b7.chunk.js:1
Ft @ 2.fa55e2b7.chunk.js:1
On @ 2.fa55e2b7.chunk.js:1
(anonymous) @ 2.fa55e2b7.chunk.js:1
e.unstable_runWithPriority @ 2.fa55e2b7.chunk.js:1
Nu @ 2.fa55e2b7.chunk.js:1
An @ 2.fa55e2b7.chunk.js:1
Show 24 more frames

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by baudzhou** [comment]
I found that this problem caused by intents with no entities which reconized by customized extractor.  When rasa-x tried to save nlu data, "start" and "end" keys could not be found.

**Comment by amn41** [comment]
hi @baudzhou - are you on the latest 0.20.2?

**Comment by amn41** [comment]
thanks @baudzhou - can you confirm what the output of your custom component is? if there are no entiities, rasa shouldn't be looking for a `"start"` or `"end"` key

**Comment by baudzhou** [comment]
@amn41 
We created a component to solve single word.
The output of custom component looks like this
```
      {
        "intent": "single_word",
        "entities": [
          {
            "start": None,
            "end": None,
            "entity": "xx",
            "value": "single_word"
          }
        ],
        "text": "single_word"
      }
```
"None" value caused the error. It should not be a bug. But if you fix this, rasa x will be more robust.
Thanks!
