### ISSUE TITLE
Missing dependency for running tests

### ISSUE THREAD

**Issue by icaropires** [RasaHQ/rasa#4401]
**Rasa version**: 1.3.0a2

**Python version**: 3.7.4

**Operating system** (windows, osx, ...): Fedora 30 Thirty

**Issue**: I followed the steps at [Development Internals](https://github.com/RasaHQ/rasa#development-internals) and unfortunately the Makefile doesn't have a `prepare-tests-fedora` so I installed the `graphviz`, `graphviz-devel` and runned manually the lines at `prepare-tests-files` on Makefile.

However, when running `make tests`, 6 tests failed. Some of the fails complained about the missing module tkinter, others seems to have failed by side effects.

After installing the `python3-tkinter` on my environment, the tests passed with no additional problems.

I'd like to add this missing dependency and create the `prepare-tests-fedora` command on Makefile if possible :smiley: 

**Error (including full traceback)**:
```
running: rasa test
     in: /tmp/pytest-of-icaro/pytest-7/test_test0
--------------------------------------------------------------- Captured stderr call ----------------------------------------------------------------

  0%|          | 0/4 [00:00<?, ?it/s]
 25%|██▌       | 1/4 [00:00<00:00,  5.99it/s]
100%|██████████| 4/4 [00:00<00:00, 16.36it/s]
Traceback (most recent call last):
  File "/home/icaro/Desktop/gces/rasa/env/bin/rasa", line 11, in <module>
    load_entry_point('rasa', 'console_scripts', 'rasa')()
  File "/home/icaro/Desktop/gces/rasa/rasa/__main__.py", line 76, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/home/icaro/Desktop/gces/rasa/rasa/cli/test.py", line 153, in test
    test_core(args)
  File "/home/icaro/Desktop/gces/rasa/rasa/cli/test.py", line 88, in test_core
    kwargs=vars(args),
  File "/home/icaro/Desktop/gces/rasa/rasa/test.py", line 108, in test_core
    rasa.core.test(stories, _agent, out_directory=output, **kwargs)
  File "uvloop/loop.pyx", line 1417, in uvloop.loop.Loop.run_until_complete
  File "/home/icaro/Desktop/gces/rasa/rasa/core/test.py", line 504, in test
    out_directory,
  File "/home/icaro/Desktop/gces/rasa/rasa/core/test.py", line 557, in plot_story_evaluation
    import matplotlib.pyplot as plt
  File "/home/icaro/Desktop/gces/rasa/env/lib/python3.7/site-packages/matplotlib/pyplot.py", line 2372, in <module>
    switch_backend(rcParams["backend"])
  File "/home/icaro/Desktop/gces/rasa/env/lib/python3.7/site-packages/matplotlib/pyplot.py", line 207, in switch_backend
    backend_mod = importlib.import_module(backend_name)
  File "/home/icaro/Desktop/gces/rasa/env/lib64/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/icaro/Desktop/gces/rasa/env/lib/python3.7/site-packages/matplotlib/backends/backend_tkagg.py", line 1, in <module>
    from . import _backend_tk
  File "/home/icaro/Desktop/gces/rasa/env/lib/python3.7/site-packages/matplotlib/backends/_backend_tk.py", line 5, in <module>
    import tkinter as Tk
ModuleNotFoundError: No module named 'tkinter'
```

**Command or request that led to error**:
```
make test
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @akelad will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by akelad** [comment]
@federicotdn i think you recently updated the requirements for running tests - thoughts on this?

**Comment by federicotdn** [comment]
I think it depends on whether we want to support testing on various GNU/Linux distributions or not. Fedora is one of the most popular ones so I guess it'd makes sense to add some setup instructions.

We should also add the `python3-tk` package for the Ubuntu installation, I forgot about that one.

**Comment by akelad** [comment]
i would say it's not a priority to test on various GNU/Linux distributions. but yeah let's add the `python3-tk` package for sure

**Comment by federicotdn** [comment]
@icaropires would you mind creating a PR to add `python3-tk` to the Ubuntu packages?

**Comment by icaropires** [comment]
@federicotdn, I can do it! Just add the package or I can create the `prepare-tests-fedora`? I could add a `prepare-tests-arch` as well. @akelad, even that it's not a priority to test on another distributions, it could help developers that use them.
