### ISSUE TITLE
AttributeError: type object 'FormPolicy' has no attribute 'priority'

### ISSUE THREAD

**Issue by RajaAsimFayyaz** [RasaHQ/rasa#4484]
**Rasa version**: 1.0.7

**Rasa X version** (if used & relevant):

**Python version**: 3.7.4

**Operating system** (windows, osx, ...): Ubuntu 18.04

**Issue**: **AttributeError: type object 'FormPolicy' has no attribute 'priority'**
I am using FormPolicy in my actions file and getting this error when executing the dialogue model. My form policy is simple, that asks for email and responds with "Got your email, we will contact you. Thanks" and if it is not given or invalid it says "Ok, thanks".

**Error (including full traceback)**:
```

Traceback (most recent call last):
  File "dialogue_model.py", line 43, in <module>
    train_dialogue('piri_domain.yml', './models/dialogue', './data/stories.md')
  File "dialogue_model.py", line 25, in train_dialogue
    agent = Agent(domain_file, policies = [MemoizationPolicy(max_history=0), KerasPolicy(epochs = 100, batch_size = 16), fallback_action, FormPolicy])
  File "/media/asim/MyData/Malik_Fiverr/Malik_Bots/piri-ai-main-ai_bot/env/lib/python3.7/site-packages/rasa_core/agent.py", line 221, in __init__
    self.policy_ensemble = self._create_ensemble(policies)
  File "/media/asim/MyData/Malik_Fiverr/Malik_Bots/piri-ai-main-ai_bot/env/lib/python3.7/site-packages/rasa_core/agent.py", line 694, in _create_ensemble
    return SimplePolicyEnsemble(policies)
  File "/media/asim/MyData/Malik_Fiverr/Malik_Bots/piri-ai-main-ai_bot/env/lib/python3.7/site-packages/rasa_core/policies/ensemble.py", line 45, in __init__
    self._check_priorities()
  File "/media/asim/MyData/Malik_Fiverr/Malik_Bots/piri-ai-main-ai_bot/env/lib/python3.7/site-packages/rasa_core/policies/ensemble.py", line 66, in _check_priorities
    priority_dict[p.priority].append(type(p).__name__)
AttributeError: type object 'FormPolicy' has no attribute 'priority'

```

**Command or request that led to error**:
```

python dialogue_model.py

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
The file is quite big but the relevant contents are given below:
```yml

entities:
    - human_name
    - human_gender
    - human_contact_information
    - human_designation
    - human_company
    - human_email

slots:
    human_name:
        type: text
    human_contact_information:
        type: text
    human_gender:
        type: text
    human_email:
        type: text
        
forms:
    - information_form

```

The story in stories.md relevant is:

```

## happy path
* greet
    - utter_greet
* human_operator
    - information_form
    - form{"name": "information_form"}
    - form{"name": null}
* auth_thanks
    - utter_bye


```

The relevant file I guess is dialogue_model.py and it's contents are as follows:

```

from __future__ import absolute_import
from __future__ import division
from __future__ import print_function
from __future__ import unicode_literals

import logging
import rasa_core
from rasa_core.agent import Agent
from rasa_core.policies import FallbackPolicy, FormPolicy
from rasa_core.policies.keras_policy import KerasPolicy
from rasa_core.policies.memoization import MemoizationPolicy
from rasa_core.interpreter import RasaNLUInterpreter
from rasa_nlu.model import Interpreter
from rasa_core.utils import EndpointConfig
from rasa_core.run import serve_application

logger = logging.getLogger(__name__)

def train_dialogue(domain_file, model_path, data_file):

    fallback_action = FallbackPolicy(fallback_action_name="fallback_action",
                              core_threshold=0.1,
                              nlu_threshold=0.1)

    agent = Agent(domain_file, policies = [MemoizationPolicy(max_history=0), KerasPolicy(epochs = 100, batch_size = 16), fallback_action, FormPolicy])
    data = agent.load_data(data_file)
    agent.train(data, validation_split = 0.01)
    agent.persist(model_path)

    return agent


def run_bot(serve_forever=True):
    interpreter = RasaNLUInterpreter('./models/nlu/default/piri')
    action_endpoint = EndpointConfig(url="http://localhost:6055/webhook")
    agent = Agent.load('./models/dialogue', 
                       interpreter=interpreter, 
                       action_endpoint=action_endpoint)
    
    rasa_core.run.serve_application(agent, channel='cmdline')

if __name__ == '__main__':
    train_dialogue('piri_domain.yml', './models/dialogue', './data/stories.md')
    # run_bot()

```

The contents of action.py file are given below, the fallback_action is working fine though:

```

from rasa_core_sdk import Action
from rasa_core_sdk.forms import FormAction
from Doc2vec import get_answer
from email.utils import parseaddr
from rasa_core_sdk import Tracker
from typing import Dict, Text, Any, List, Union, Optional
from rasa_core_sdk.executor import CollectingDispatcher

class fallback_action(Action):

    FAQ_THRESHOLD = 0.3

    #@antidote.inject
    def __init__(self):
        print("a")

    def name(self):
        return 'fallback_action'

    def run(self, dispatcher,
            tracker,
            domain):
        
        
        msg=tracker.latest_message['text']
        resp=get_answer.get_answer(msg)  #getting response from doc2vec
        dispatcher.utter_message(resp)
        return []

class InformationForm(FormAction):
    """Example of a custom form action"""

    def name(self):
        """Unique identifier of the form"""
        return "introduction_form"
    
    @staticmethod
    def required_slots(tracker: Tracker) -> List[Text]:
        """A list of required slots that the form has to fill"""

        return ["human_name", "human_email"]
    
    def validate(self,
                 dispatcher: CollectingDispatcher,
                 tracker: Tracker,
                 domain: Dict[Text, Any]) -> List[Dict]:
        """Validate extracted requested slot
                else reject the execution of the form action
        """

        # extract other slots that were not requested
        # but set by corresponding entity
        slot_values = self.extract_other_slots(dispatcher, tracker, domain)

        # extract requested slot
        slot_to_fill = tracker.get_slot("human_email")
        if '@' in parseaddr(slot_to_fill)[1]:
            flag=True
        else:
            flag=False
        if flag:
            dispatcher.utter_message("Got your email, we will contact you. Thanks")
        else:
            dispatcher.utter_message("Ok, thanks")
        return []

```

Any help will be greatly appreciated, thanks.

**Comment by RajaAsimFayyaz** [comment]
I can't delete this issue lol, I just had to use "FormPolicy()" instead of "FormPolicy" in the dialogue_model.py file.
