### ISSUE TITLE
TypeError :CIMultiDict  keys error when integrating Rasa with Slack

### ISSUE THREAD

**Issue by rjtmehta99** [RasaHQ/rasa#4503]
**Rasa version**: 1.2.2.

**Rasa X version** (if used & relevant): Not Used

**Python version**: 3.6.8

**Operating system** (windows, osx, ...): Ubuntu 18.04

**Issue**: 
I have integrated Slack with Rasa. It shows verified in the Events Subscription page on Slack. But on sending a message to the channel/app on Slack, the following error is encountered. 

**Error (including full traceback)**:
```
Exception occurred while handling uri: 'http://c23c2a14.ngrok.io/webhooks/slack/webhook'
Traceback (most recent call last):
  File "/home/rajat-mehta/.local/lib/python3.6/site-packages/sanic/app.py", line 917, in handle_request
    response = await response
  File "/home/rajat-mehta/.local/lib/python3.6/site-packages/rasa/core/channels/slack.py", line 329, in webhook
    sender_id=output.get("event").get("user"),
  File "/home/rajat-mehta/.local/lib/python3.6/site-packages/rasa/core/channels/slack.py", line 267, in process_message
    retry_reason = request.headers.get(self.retry_reason_header)
  File "multidict/_multidict.pyx", line 69, in multidict._multidict._Base.get
  File "multidict/_multidict.pyx", line 52, in multidict._multidict._Base._getone
TypeError: CIMultiDict keys should be either str or subclasses of str


```

**Command or request that led to error**:
```
Message Sent from Slack to Rasa connected via ngrok
```

**Content of credentials file (credentials.yml)** (if relevant):
```yml

slack:
  slack_token: "xxxxxxxxxxxxx"
  slack_channel: "@name"
  slack_retry_reason_header: "x-slack-retry-reason" #Slack HTTP header name indicating reason that slack send retry request. This configuration is optional.
  slack_retry_number_header: "x-slack-retry-num" #Slack HTTP header name indicating the attempt number. This configuration is optional.
  errors_ignore_retry: None #Any error codes given by Slack included in this list will be ignored. Error codes are listed `here <https://api.slack.com/events-api#errors>`_.

rasa:
  url: "http://localhost:5002/api"
```

**Content of domain file (domain.yml)** (if relevant):
```yml
Not Relevant
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @imLew will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by imLew** [comment]
Hi @rjtmehta99, I'm not sure this is a bug.
Based on your post you seem to have the credentials in `config.yml`, while they should be in `credentials.yml` https://rasa.com/docs/rasa/user-guide/connectors/slack/.

**Comment by rjtmehta99** [comment]
> Hi @rjtmehta99, I'm not sure this is a bug.
> Based on your post you seem to have the credentials in `config.yml`, while they should be in `credentials.yml` https://rasa.com/docs/rasa/user-guide/connectors/slack/.

Sorry, copied it by mistake. I have updated it above. Please have a look now.

**Comment by imLew** [comment]
Too bad it's not that easy 😅 
It is weird, looking at your credentials and the code it looks like it should be a string. Can you find out what type it thinks it is?

**Comment by rjtmehta99** [comment]
@imLew  
Actually I am new to this. How do I check it ? Also, it is running fine when I use rasa shell.

**Comment by imLew** [comment]
The simplest way would be to insert a print statement to check the variable above https://github.com/RasaHQ/rasa/blob/da370f4eb5be871d33ae42840e9bc7cf4b55b67d/rasa/core/channels/slack.py#L267
Also try running rasa with `--debug`, that won't tell us the type of the variable but might show other useful information.
When running `rasa shell` the slack channel is not used so there should be no problem.

**Comment by rjtmehta99** [comment]
@imLew  Here are the logs: 
The 'None' being printed at the top is the type(retry_reason).
As you can see it is showing - Action 'utter_ask_course' ended with events 
But no response is seen on Slack.  
```
None
2019-09-24 09:59:57 DEBUG    rasa.core.agent  - Created a new lock for conversation 'UNHKDL5CY'
2019-09-24 09:59:57 DEBUG    rasa.core.tracker_store  - Recreating tracker for id 'UNHKDL5CY'
2019-09-24 09:59:57 DEBUG    rasa.core.processor  - Received user message 'fees' with intent '{'name': 'fees_query', 'confidence': 0.8593208055101995}' and entities '[{'start': 0, 'end': 4, 'value': 'fees', 'entity': 'Fees', 'confidence': 0.7246493292904564, 'extractor': 'CRFEntityExtractor'}]'
2019-09-24 09:59:57 DEBUG    rasa.core.processor  - Logged UserUtterance - tracker now has 6 events
2019-09-24 09:59:57 DEBUG    rasa.core.featurizers  - Feature 'entity_Fees' (value: '1.0') could not be found in feature map. Make sure you added all intents and entities to the domain
2019-09-24 09:59:57 DEBUG    rasa.core.featurizers  - Feature 'entity_Fees' (value: '1.0') could not be found in feature map. Make sure you added all intents and entities to the domain
2019-09-24 09:59:57 DEBUG    rasa.core.featurizers  - Feature 'entity_Fees' (value: '1.0') could not be found in feature map. Make sure you added all intents and entities to the domain
2019-09-24 09:59:57 DEBUG    rasa.core.policies.fallback  - NLU confidence threshold met, confidence of fallback action set to core threshold (0.779).
2019-09-24 09:59:57 DEBUG    rasa.core.policies.ensemble  - Predicted next action using policy_0_KerasPolicy
2019-09-24 09:59:57 DEBUG    rasa.core.processor  - Predicted next action 'utter_ask_course' with confidence 1.00.
2019-09-24 09:59:57 DEBUG    rasa.core.processor  - Action 'utter_ask_course' ended with events '['BotUttered(text: \nWhich course are you interested in ?\n, data: {"elements": null, "quick_replies": null, "buttons": [{"payload": "/btech_fees", "title": "B.Tech"}, {"payload": "/mtech_fees", "title": "M.Tech"}, {"payload": "/bca_fees", "title": "BCA"}, {"payload": "/mca_fees", "title": "MCA"}, {"payload": "/ba_fees", "title": "BA"}, {"payload": "/bba_fees", "title": "BBA"}, {"payload": "/ballb_fees", "title": "BA LLB"}, {"payload": "/phd_fees", "title": "PhD."}, {"payload": "/bhm_fees", "title": "BHM (Hotel Management)"}, {"payload": "/mba_fees", "title": "MBA"}], "attachment": null, "image": null, "custom": null}, metadata: {})']'
2019-09-24 09:59:57 WARNING  rasa.core.channels.slack  - Slack API currently allows only up to 5 buttons. If you add more, all will be ignored.
2019-09-24 09:59:57 DEBUG    rasa.core.featurizers  - Feature 'entity_Fees' (value: '1.0') could not be found in feature map. Make sure you added all intents and entities to the domain
2019-09-24 09:59:57 DEBUG    rasa.core.featurizers  - Feature 'entity_Fees' (value: '1.0') could not be found in feature map. Make sure you added all intents and entities to the domain
2019-09-24 09:59:57 DEBUG    rasa.core.featurizers  - Feature 'entity_Fees' (value: '1.0') could not be found in feature map. Make sure you added all intents and entities to the domain
2019-09-24 09:59:57 DEBUG    rasa.core.featurizers  - Feature 'entity_Fees' (value: '1.0') could not be found in feature map. Make sure you added all intents and entities to the domain
2019-09-24 09:59:57 DEBUG    rasa.core.policies.fallback  - NLU confidence threshold met, confidence of fallback action set to core threshold (0.779).
2019-09-24 09:59:57 DEBUG    rasa.core.policies.ensemble  - Predicted next action using policy_0_KerasPolicy
2019-09-24 09:59:57 DEBUG    rasa.core.processor  - Predicted next action 'action_listen' with confidence 1.00.
2019-09-24 09:59:57 DEBUG    rasa.core.processor  - Action 'action_listen' ended with events '[]'
2019-09-24 09:59:57 DEBUG    rasa.core.agent  - Deleted lock for conversation 'UNHKDL5CY' (unused)

```

**Comment by rjtmehta99** [comment]
@imLew  
Got it working. 
Thank you for your help ! 
Cheers !

**Comment by imLew** [comment]
What was the fix?
