### ISSUE TITLE
Rasa X API Incomplete Error Response

### ISSUE THREAD

**Issue by rgstephens** [RasaHQ/rasa#4597]
**Rasa version**: 1.3.9

**Rasa X version**: 0.21.3

**Issue**:
I call the `POST /api/stories` endpoint to add a new story and it returns a status 500 with no other information. The server side log shows the trace shown below.

The API response should include the message `rasa.core.domain.InvalidDomain Duplicate actions in domain. These actions occur more than once in the domain: 'dynamic_form'`

Without that information, the user is in the dark about what happened.  This API change is also needed for the Rasa X UI. See discussion in #4231 [here](https://github.com/RasaHQ/rasa/issues/4231#issuecomment-540797775)

**Error (including full traceback)**:
```
rasa-x_1           | Exception occurred while handling uri: 'http://localhost/api/stories'
rasa-x_1           | Traceback (most recent call last):
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 917, in handle_request
rasa-x_1           |     response = await response
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/rasax/community/api/decorators.py", line 176, in decorated_function
rasa-x_1           |     return await await_and_return_response(args, kwargs, request)
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/rasax/community/api/decorators.py", line 106, in await_and_return_response
rasa-x_1           |     response = await response
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/rasax/community/api/decorators.py", line 46, in decorated_function
rasa-x_1           |     return await response
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/rasax/community/api/blueprints/stack.py", line 641, in add_stories
rasa-x_1           |     story_string, user["team"], username=user["username"]
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/rasax/community/services/story_service.py", line 110, in save_stories
rasa-x_1           |     steps = await self.get_story_steps(story)
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/rasax/community/services/story_service.py", line 52, in get_story_steps
rasa-x_1           |     domain = DomainService(self.session).get_parsed_domain()
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/rasax/community/services/domain_service.py", line 189, in get_parsed_domain
rasa-x_1           |     return self._get_or_create_domain(project_id).as_rasa_domain()
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/rasax/community/database/domain.py", line 91, in as_rasa_domain
rasa-x_1           |     return RasaDomain.from_dict(self.as_dict())
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/rasa/core/domain.py", line 119, in from_dict
rasa-x_1           |     **additional_arguments
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/rasa/core/domain.py", line 296, in __init__
rasa-x_1           |     self._check_domain_sanity()
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/rasa/core/domain.py", line 894, in _check_domain_sanity
rasa-x_1           |     incorrect_mappings,
rasa-x_1           | rasa.core.domain.InvalidDomain: Duplicate actions in domain. These actions occur more than once in the domain: 'dynamic_form'
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @wochinge will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by wochinge** [comment]
Hi @rgstephens 

> I call the POST /api/version endpoint to add a new story and it returns a status 500 with no other information. The server side log shows the trace shown below.

You mean `/api/stories` right? How does the uploaded story look and how does the domain look like?

**Comment by rgstephens** [comment]
Oops, yes.
