### ISSUE TITLE
 Encountered an exception while running action 'action_get_links'. Bot will continue, but the actions events are lost.

### ISSUE THREAD

**Issue by Hansagupta27** [RasaHQ/rasa#4604]
**I'm trying to implement custom actions and have added action_get_links to domain.yml. In this action, I want to read a csv file and fetch the details based upon the specific category.**
actions:
- utter_greet
- utter_reply
- utter_help
- utter_did_that_help
- utter_anything_else
- utter_ofc
- utter_happy
- utter_happy_happy
- utter_goodbye
- utter_default
- utter_iamabot
- action_restart
- action_get_links

**Added the actions in action.py**
from typing import Any, Text, Dict, List
from rasa_sdk import Action, Tracker
from rasa_sdk.executor import CollectingDispatcher
import pandas as pd

class ActionGetLinkDesc(Action):
    def name(self):
        return 'action_get_links'

    def run(self, 
            dispatcher: CollectingDispatcher,
            tracker: Tracker,
            domain: Dict[Text, Any]) -> List[Dict[Text, Any]]:
        category = tracker.get_slot('category')
        print(category)
           
        data = pd.read_csv("links.csv", index_col = "Category_List") 
        link_des = data.loc[category]
        dispatcher.utter_message(link_des)

        return []

**Ran the action server:**
python -m rasa_core_sdk.endpoint --actions actions

**Logs from action server:**
[2019-10-12 02:12:30,984] ERROR in app: Exception on /webhook [POST]
Traceback (most recent call last):
  File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask_cors\decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\rasa_core_sdk\endpoint.py", line 59, in webhook
    response = executor.run(action_call)
  File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\rasa_core_sdk\executor.py", line 177, in run
    "No registered Action found for name '{}'.".format(action_name)
Exception: No registered Action found for name 'action_get_links'.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @dakshvar22 will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by dakshvar22** [comment]
@Hansagupta27 Please mention what Rasa version are you trying?
Also, as the document mentions, please run your custom action server with `python -m rasa_sdk --actions action`
https://rasa.com/docs/rasa/core/actions/#custom-actions-written-in-python

**Comment by Hansagupta27** [comment]
Thanks @dakshvar22 for looking into it. I am using Rasa 1.3.8.
I used the command as suggested by you- python -m rasa_sdk --actions action and still I am getting the same issue.
Below are the error description:
[2019-10-14 16:55:14,860] ERROR in app: Exception on /webhook [POST]
Traceback (most recent call last):
  File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask_cors\decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\rasa_sdk\endpoint.py", line 74, in webhook
    response = executor.run(action_call)
  File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\rasa_sdk\executor.py", line 246, in run
    "No registered Action found for name '{}'.".format(action_name)
Exception: No registered Action found for name 'action_get_links'.
2019-10-14 16:55:14 ERROR    rasa_sdk.endpoint  - Exception on /webhook [POST]
Traceback (most recent call last):
  File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask_cors\decorator.py", line 128, in wrapped_function
    resp = make_response(f(*args, **kwargs))
  File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\rasa_sdk\endpoint.py", line 74, in webhook
    response = executor.run(action_call)
  File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\rasa_sdk\executor.py", line 246, in run
    "No registered Action found for name '{}'.".format(action_name)
Exception: No registered Action found for name 'action_get_links'.
127.0.0.1 - - [2019-10-14 16:55:14] "POST /webhook HTTP/1.1" 500 411 0.063016

**Comment by Hansagupta27** [comment]
> Thanks @dakshvar22 for looking into it. I am using Rasa 1.3.8.
> I used the command as suggested by you- python -m rasa_sdk --actions action and still I am getting the same issue.
> Below are the error description:
> [2019-10-14 16:55:14,860] ERROR in app: Exception on /webhook [POST]
> Traceback (most recent call last):
> File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
> response = self.full_dispatch_request()
> File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
> rv = self.handle_user_exception(e)
> File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
> return cors_after_request(app.make_response(f(*args, **kwargs)))
> File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
> reraise(exc_type, exc_value, tb)
> File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask_compat.py", line 39, in reraise
> raise value
> File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
> rv = self.dispatch_request()
> File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
> return self.view_functions[rule.endpoint](**req.view_args)
> File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask_cors\decorator.py", line 128, in wrapped_function
> resp = make_response(f(*args, **kwargs))
> File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\rasa_sdk\endpoint.py", line 74, in webhook
> response = executor.run(action_call)
> File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\rasa_sdk\executor.py", line 246, in run
> "No registered Action found for name '{}'.".format(action_name)
> Exception: No registered Action found for name 'action_get_links'.
> 2019-10-14 16:55:14 ERROR rasa_sdk.endpoint - Exception on /webhook [POST]
> Traceback (most recent call last):
> File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
> response = self.full_dispatch_request()
> File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
> rv = self.handle_user_exception(e)
> File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
> return cors_after_request(app.make_response(f(*args, **kwargs)))
> File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
> reraise(exc_type, exc_value, tb)
> File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask_compat.py", line 39, in reraise
> raise value
> File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
> rv = self.dispatch_request()
> File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
> return self.view_functions[rule.endpoint](**req.view_args)
> File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask_cors\decorator.py", line 128, in wrapped_function
> resp = make_response(f(*args, **kwargs))
> File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\rasa_sdk\endpoint.py", line 74, in webhook
> response = executor.run(action_call)
> File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\rasa_sdk\executor.py", line 246, in run
> "No registered Action found for name '{}'.".format(action_name)
> Exception: No registered Action found for name 'action_get_links'.
> 127.0.0.1 - - [2019-10-14 16:55:14] "POST /webhook HTTP/1.1" 500 411 0.063016

Thanks @dakshvar22 for looking into it. I am using Rasa 1.3.8.
I used the command as suggested by you- python -m rasa_sdk --actions action and still I am getting the same issue.
Below are the error description:
[2019-10-14 16:55:14,860] ERROR in app: Exception on /webhook [POST]
Traceback (most recent call last):
File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
response = self.full_dispatch_request()
File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
rv = self.handle_user_exception(e)
File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
return cors_after_request(app.make_response(f(*args, **kwargs)))
File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask_compat.py", line 39, in reraise
raise value
File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
rv = self.dispatch_request()
File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
return self.view_functionsrule.endpoint
File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask_cors\decorator.py", line 128, in wrapped_function
resp = make_response(f(*args, **kwargs))
File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\rasa_sdk\endpoint.py", line 74, in webhook
response = executor.run(action_call)
File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\rasa_sdk\executor.py", line 246, in run
"No registered Action found for name '{}'.".format(action_name)
Exception: No registered Action found for name 'action_get_links'.
2019-10-14 16:55:14 ERROR rasa_sdk.endpoint - Exception on /webhook [POST]
Traceback (most recent call last):
File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask\app.py", line 2446, in wsgi_app
response = self.full_dispatch_request()
File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
rv = self.handle_user_exception(e)
File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask_cors\extension.py", line 161, in wrapped_function
return cors_after_request(app.make_response(f(*args, **kwargs)))
File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask_compat.py", line 39, in reraise
raise value
File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
rv = self.dispatch_request()
File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask\app.py", line 1935, in dispatch_request
return self.view_functionsrule.endpoint
File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\flask_cors\decorator.py", line 128, in wrapped_function
resp = make_response(f(*args, **kwargs))
File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\rasa_sdk\endpoint.py", line 74, in webhook
response = executor.run(action_call)
File "C:\Users\hgupta22\AppData\Local\Continuum\anaconda3\envs\chatbotenv\lib\site-packages\rasa_sdk\executor.py", line 246, in run
"No registered Action found for name '{}'.".format(action_name)
Exception: No registered Action found for name 'action_get_links'.
127.0.0.1 - - [2019-10-14 16:55:14] "POST /webhook HTTP/1.1" 500 411 0.063016

**Comment by DeepakTiwari84** [comment]
@Hansagupta27  when you start your action server does it says started server with  action registered action? something like this with port 

![image](https://user-images.githubusercontent.com/42840642/67147038-a2bc6e00-f2ae-11e9-935c-053de1b7472c.png)

**Comment by Hansagupta27** [comment]
> @Hansagupta27 when you start your action server does it says started server with action registered action? something like this with port
> 
> ![image](https://user-images.githubusercontent.com/42840642/67147038-a2bc6e00-f2ae-11e9-935c-053de1b7472c.png)
> 
> i had the issue , you can run action server on docker and keep it running

Yes, I keep another terminal open and run the action server in that. I also keep it running. From there itself, I copied the logs details.
