### ISSUE TITLE
Exception occurred while handling uri: /api/projects/default/models/jobs

### ISSUE THREAD

**Issue by DeepakTiwari84** [RasaHQ/rasa#4623]
**Rasa version**: rasa/rasa:1.3.9-full 

**Rasa X version** (if used & relevant):  rasa/rasa-x:stable

**Python version**: 3.6

**Operating system** (windows, osx, ...): ubuntu 18.04

**Issue**:  Exception occurred while handling uri : /api/projects/default/models/jobs

**Error (including full traceback)**:
```
Exception occurred while handling uri: 'http://xxx.xxx.xxx.239/api/conversations/d796cffd51a64268a38ae84b001453b5/messages?environment=production'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 917, in handle_request
    response = await response
  File "/usr/local/lib/python3.6/site-packages/rasax/community/api/decorators.py", line 176, in decorated_function
    return await await_and_return_response(args, kwargs, request)
  File "/usr/local/lib/python3.6/site-packages/rasax/community/api/decorators.py", line 106, in await_and_return_response
    response = await response
  File "/usr/local/lib/python3.6/site-packages/rasax/community/api/blueprints/stack.py", line 357, in send_message
    return await chat_to_bot(request, conversation_id)
  File "/usr/local/lib/python3.6/site-packages/rasax/community/api/decorators.py", line 176, in decorated_function
    return await await_and_return_response(args, kwargs, request)
  File "/usr/local/lib/python3.6/site-packages/rasax/community/api/decorators.py", line 106, in await_and_return_response
    response = await response
  File "/usr/local/lib/python3.6/site-packages/rasax/community/api/decorators.py", line 196, in decorated_function
    return await f(request, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/rasax/community/api/blueprints/stack.py", line 733, in chat_to_bot
    message_object, token=request.headers.get("Authorization")
  File "/usr/local/lib/python3.6/site-packages/rasax/community/services/stack_service.py", line 172, in send_message
    subpath=url, method="post", json=message, headers={"Authorization": token}
  File "/usr/local/lib/python3.6/site-packages/rasa/utils/endpoints.py", line 144, in request
    **kwargs
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client.py", line 497, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.6/site-packages/aiohttp/client_reqrep.py", line 857, in start
    self._continue = None
  File "/usr/local/lib/python3.6/site-packages/aiohttp/helpers.py", line 585, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError
Exception occurred while handling uri: 'http://xxx.xxx.xxx.239/api/projects/default/models/jobs'
NoneType: None

Exception occurred while handling uri: 'http://xxx.xxx.xxx.239/api/projects/default/models/jobs'
NoneType: None

Transport closed @ ('172.18.0.9', 40872) and exception experienced during error handling

```

**Command or request that led to error**:
```
Clicked on train on Rasa X UI
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```
pipeline: supervised_embeddings
language: en
policies:
- name: MemoizationPolicy
- name: KerasPolicy
- name: MappingPolicy

```
Server Configuration
```
OS: Ubantu 18.04
RAM: 16 GB
```

**Comment by DeepakTiwari84** [comment]
Here is the response I got:
![image](https://user-images.githubusercontent.com/42840642/66959499-22b4bf00-f088-11e9-9ab4-b8caa7d0ad7a.png)

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @gausie will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by DeepakTiwari84** [comment]
I checked with large volume of training data and examples it fails to train the model. But with smaller data set there is no problem.

Is there a way we can just log in the server and train the data and use the UI to do the stories, NLU training , view conversation tracker etc?

**Comment by wochinge** [comment]
This will be fixed in the next release. I increased the Sanic response timeout.

**Comment by DeepakTiwari84** [comment]
Thanks!

**Comment by Wing-e7** [comment]
> This will be fixed in the next release. I increased the Sanic response timeout.

I have the same problem. Anyway i can do the same on my end ?

**Comment by Mazyod** [comment]
Same Issue here, with training examples of about 34,000

**Comment by wochinge** [comment]
@erohmensing that's the one just fixed, isn't it?

**Comment by erohmensing** [comment]
Original post with `concurrent.futures._base.TimeoutError` smells like it yea, usually that is the error that appears (we saw this in custom actions) 

as for the 504 that @DeepakTiwari84  saw I'm not sure -- I think it should be a 503
