### ISSUE TITLE
Rasa shell panics on CTRL + D

### ISSUE THREAD

**Issue by icaropires** [RasaHQ/rasa#4632]
**Rasa version**: 1.3.8

**Rasa X version** (if used & relevant):

**Python version**:  3.7.4

**Operating system** (windows, osx, ...): Fedora 30

**Issue**: The rasa shell panics and hangs forever when pressing CTRL+D, which is a default command for leaving shells sessions. I believe it has the same behaviour as `/stop`

**Error (including full traceback)**:
```
(env) ✔︎ tmp (master) ✗ rasa shell
2019-10-17 16:51:42 INFO     root  - Connecting to channel 'cmdline' which was specified by the '--connector' argument. Any other channels will be ignored. To connect to all given channels, omit the '--connector' argument.
2019-10-17 16:51:42 INFO     root  - Starting Rasa server on http://localhost:5005
Bot loaded. Type a message and press enter (use '/stop' to exit): 
Your input ->                                                                                                                                          
2019-10-17 16:51:52 ERROR    asyncio  - Task exception was never retrieved
future: <Task finished coro=<configure_app.<locals>.run_cmdline_io() done, defined at /home/icaro/Desktop/gces/rasa/rasa/core/run.py:123> exception=EOFError()>
Traceback (most recent call last):
  File "/home/icaro/Desktop/gces/rasa/rasa/core/run.py", line 127, in run_cmdline_io
    server_url=constants.DEFAULT_SERVER_FORMAT.format("http", port)
  File "/home/icaro/Desktop/gces/rasa/rasa/core/channels/console.py", line 125, in record_messages
    text = get_user_input(button_question)
  File "/home/icaro/Desktop/gces/rasa/rasa/core/channels/console.py", line 74, in get_user_input
    style=Style([("qmark", "#b373d6"), ("", "#b373d6")]),
  File "/home/icaro/Desktop/gces/rasa/env/lib/python3.7/site-packages/questionary/question.py", line 45, in ask
    return self.unsafe_ask(patch_stdout)
  File "/home/icaro/Desktop/gces/rasa/env/lib/python3.7/site-packages/questionary/question.py", line 59, in unsafe_ask
    return self.application.run()
  File "/home/icaro/Desktop/gces/rasa/env/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 709, in run
    return run()
  File "/home/icaro/Desktop/gces/rasa/env/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 683, in run
    return f.result()
  File "/home/icaro/Desktop/gces/rasa/env/lib/python3.7/site-packages/prompt_toolkit/eventloop/future.py", line 149, in result
    raise self._exception
  File "/home/icaro/Desktop/gces/rasa/env/lib/python3.7/site-packages/prompt_toolkit/eventloop/coroutine.py", line 90, in step_next
    new_f = coroutine.throw(exc)
  File "/home/icaro/Desktop/gces/rasa/env/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 658, in _run_async2
    result = yield f
  File "/home/icaro/Desktop/gces/rasa/env/lib/python3.7/site-packages/prompt_toolkit/eventloop/coroutine.py", line 92, in step_next
    new_f = coroutine.send(f.result())
  File "/home/icaro/Desktop/gces/rasa/env/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 610, in _run_async
    result = yield From(f)
EOFError
```

**Command or request that led to error**:
```
rasa shell
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

I'd like to contribute if possible :smiley:

**Comment by sara-tagger** [comment]
Thanks for the issue, @amn41 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by sunqiang25** [comment]
please check your actions.py, maybe it'll report error when you run "rasa run actions"

**Comment by icaropires** [comment]
> please check your actions.py, maybe it'll report error when you run "rasa run actions"

@sunqiang25 I had just run `rasa init` without changing any configuration files. CTRL + C work as expected, the problem is CTRL + D

**Comment by icaropires** [comment]
I believe the expected behaviour would be the same as CTRL + C:
```
(env) ✔︎ tmp rasa shell
2019-10-27 17:48:58 INFO     root  - Connecting to channel 'cmdline' which was specified by the '--connector' argument. Any other channels will be ignored. To connect to all given channels, omit the '--connector' argument.
2019-10-27 17:48:58 INFO     root  - Starting Rasa server on http://localhost:5005
Bot loaded. Type a message and press enter (use '/stop' to exit): 
Your input ->  hi                                                                                                                                                         
Hey! How are you?
Your input ->                                                                                                                                                             

Cancelled by user

2019-10-27 17:49:09 INFO     root  - Killing Sanic server now.
(env) ✔︎ tmp
```

With further investigation, I'm afraid that to gracefully exit on `SIGTERM` (CTRL + D) without big changes, the modifications should be done at [questionary](https://github.com/tmbo/questionary) which is handling only `SIGINT` through `KeyboardInterrupt` exception.
