### ISSUE TITLE
rasa visualize and interactive fail

### ISSUE THREAD

**Issue by vsraptor** [RasaHQ/rasa#4674]
**Rasa version**:
1.3.9
**Rasa X version** (if used & relevant):

**Python version**:
3.6
**Operating system** (windows, osx, ...):
linux
**Issue**:

rasa visualize and interactive fail

**Error (including full traceback)**:
```
2019-10-25 11:37:31 INFO     absl  - Entry Point [tensor2tensor.envs.tic_tac_toe_env:TicTacToeEnv] registered with id [T2TEnv-TicTacToeEnv-v0]
2019-10-25 11:37:31 INFO     rasa.core.visualize  - Starting to visualize stories...
Processed Story Blocks: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:00<00:00, 4190.11it/s, # trackers=1]
Traceback (most recent call last):
  File "/usr/local/bin/rasa", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/rasa/__main__.py", line 76, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/usr/local/lib/python3.6/dist-packages/rasa/cli/visualize.py", line 38, in visualize_stories
    args.config, args.domain, args.stories, args.nlu, args.out, args.max_history
  File "uvloop/loop.pyx", line 1417, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.6/dist-packages/rasa/core/visualize.py", line 53, in visualize
    stories_path, output_path, max_history, nlu_training_data=nlu_data_path
  File "/usr/local/lib/python3.6/dist-packages/rasa/core/agent.py", line 803, in visualize
    fontsize,
  File "/usr/local/lib/python3.6/dist-packages/rasa/core/training/visualization.py", line 582, in visualize_stories
    fontsize=fontsize,
  File "/usr/local/lib/python3.6/dist-packages/rasa/core/training/visualization.py", line 491, in visualize_neighborhood
    _merge_equivalent_nodes(graph, max_history)
  File "/usr/local/lib/python3.6/dist-packages/rasa/core/training/visualization.py", line 207, in _merge_equivalent_nodes
    graph, i, j, max_history
  File "/usr/local/lib/python3.6/dist-packages/rasa/core/training/visualization.py", line 147, in _nodes_are_equivalent
    return graph.node[node_a]["label"] == graph.node[node_b]["label"] and (
AttributeError: 'MultiDiGraph' object has no attribute 'node'

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by vsraptor** [comment]
I added this : 

```
def _nodes_are_equivalent(graph, node_a, node_b, max_history):
    """Decides if two nodes are equivalent based on their fingerprints."""
    if not hasattr(graph, 'node') : return False  # <<<<<<<<<<<<<<<<
    return graph.node[node_a]["label"] == graph.node[node_b]["label"] and (
        _outgoing_edges_are_similar(graph, node_a, node_b)
        or _incoming_edges(graph, node_a) == _incoming_edges(graph, node_b)
        or _fingerprint_node(graph, node_a, max_history)
        == _fingerprint_node(graph, node_b, max_history)
    )
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @federicotdn will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by erohmensing** [comment]
Hi there @vsraptor, thanks for the bug report. This has already been fixed on our dev branch (https://github.com/RasaHQ/rasa/pull/4665) and is awaiting release :) in the meantime, 
```
pip install networkx==2.3
```
should fix the issue. (though I believe there may be another IL bug fix that is awaiting release as well 😅)

**Comment by erohmensing** [comment]
Fixed in 1.4.2

**Comment by murtuzamdahod** [comment]
> ```
> pip install networkx==2.3
> ```

Thanks alot

**Comment by erohmensing** [comment]
@murtuzamdahod this was officially fixed as well, so instead of pinning it yourself, you can also
```
pip install -U rasa
``` 

:)
