### ISSUE TITLE
ModelNotFound Exception: No NLU or Core data for unpacked model

### ISSUE THREAD

**Issue by cintahofmann** [RasaHQ/rasa#4678]
**Rasa version:** 1.3.9

**Python version:** 3.7.4

**Operating system:** Windows 10 (VM)

**Issue:** ModelNotFound Exception: No NLU or Core data for unpacked model at: './models/

So I'm trying to update my model from pre-1.0 Rasa to the up-to-date package, and I'm finding myself utterly lacking in the competence to do this? Before, I had my model in a subfolder under /models/dialogue and now it's being exported from the train function as a tar.gz file. So I extracted the file and put it in the folder structure I had before, only now I keep getting the above error, and I don't know what's wrong with my setup. My models folder contains exactly what 'comes out' of the unzipped file, so what is it missing? 

Thanks so much in advance for any help!

**Comment by sara-tagger** [comment]
Thanks for the issue, @dakshvar22 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by erohmensing** [comment]
Hi @cintahofmann, in the latest version you don't need/want to extract the file, rather the models will live in the models/ directory as tar.gz files. Is that helpful? If not, can you please post the output of the commands you are running?

**Comment by cintahofmann** [comment]
Hi @erohmensing, thanks for your response! :) When I try to just leave the unzipped file in the folder structure, I get the same error. This is what my dialogue management model looks like with the subfolder structure:

```from __future__ import absolute_import
from __future__ import division  
from __future__ import print_function  
from __future__ import unicode_literals

import logging
import rasa.core
import asyncio
from rasa.core.agent import Agent
from rasa.core.policies.keras_policy import KerasPolicy
from rasa.core.policies.memoization import MemoizationPolicy
from rasa.core.interpreter import RasaNLUInterpreter
from rasa.core.run import serve_application
from rasa.core import config
from rasa.utils.endpoints import EndpointConfig

from rasa.core.policies.fallback import FallbackPolicy
from rasa.core.policies.form_policy import FormPolicy

logger = logging.getLogger(__name__)

async def train_dialogue(domain_file = 'domain.yml',
					model_path = './models/core',
					training_data_file = './data/stories.md'):
					
					
	fallback = FallbackPolicy(fallback_action_name="action_default_fallback",
                          core_threshold=0.2,
                          nlu_threshold=0.4)
						  
	agent = Agent(domain_file, policies = [FormPolicy(), MemoizationPolicy(), KerasPolicy(max_history=3, epochs=200, batch_size=50), fallback])
	data = await agent.load_data(training_data_file)	
	

	agent.train(data)
				
	agent.persist(model_path)
	return agent
	
def run_report_bot(serve_forever=True):
	interpreter = RasaNLUInterpreter('./models/nlu/')
	action_endpoint = EndpointConfig(url="http://localhost:5055/webhook")
	
						  	
	agent = Agent.load('./models/core', interpreter=interpreter, action_endpoint=action_endpoint)
	rasa_core.run.serve_application(agent ,channel='cmdline')
		
	return agent
	
if __name__ == '__main__':
	train_dialogue()
	run_report_bot()

**Comment by cintahofmann** [comment]
So, this is what happens when I delete the subfolder structure and just leave the unextracted tar.gz files (and take out the reference to the subfolders from the dialogue management model.py):

(aka it seems to be looking for the json that's inside the zipped model file)

```Traceback (most recent call last):
  File "C:\Users\Cinta\Anaconda3\lib\site-packages\rasa\nlu\model.py", line 68, in load
    data = rasa.utils.io.read_json_file(metadata_file)
  File "C:\Users\Cinta\Anaconda3\lib\site-packages\rasa\utils\io.py", line 141, in read_json_file
    content = read_file(filename)
  File "C:\Users\Cinta\Anaconda3\lib\site-packages\rasa\utils\io.py", line 136, in read_file
    raise ValueError("File '{}' does not exist.".format(filename))
ValueError: File './models/metadata.json' does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "dialogue_management_model.py", line 53, in <module>
    run_report_bot()
  File "dialogue_management_model.py", line 42, in run_report_bot
    interpreter = RasaNLUInterpreter('./models/')
  File "C:\Users\Cinta\Anaconda3\lib\site-packages\rasa\core\interpreter.py", line 263, in __init__
    self._load_interpreter()
  File "C:\Users\Cinta\Anaconda3\lib\site-packages\rasa\core\interpreter.py", line 286, in _load_interpreter
    self.interpreter = Interpreter.load(self.model_directory)
  File "C:\Users\Cinta\Anaconda3\lib\site-packages\rasa\nlu\model.py", line 302, in load
    model_metadata = Metadata.load(model_dir)
  File "C:\Users\Cinta\Anaconda3\lib\site-packages\rasa\nlu\model.py", line 73, in load
    "Failed to load model metadata from '{}'. {}".format(abspath, e)
rasa.nlu.model.InvalidModelError: Failed to load model metadata from 'C:\Users\Cinta\Documents\Chatbot\models\metadata.json'. File './models/metadata.json' does not exist.

**Comment by cintahofmann** [comment]
And then, if I just copy over the metadata.json from the previously extracted model file, this happens - which makes no sense, as I trained the model literally yesterday using Rasa 1.3.9 (which is reflected in the file name of course):

```(venv) (base) C:\Users\Cinta\Documents\Chatbot>python dialogue_management_model.py
dialogue_management_model.py:52: RuntimeWarning: coroutine 'train_dialogue' was never awaited
  train_dialogue()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "dialogue_management_model.py", line 53, in <module>
    run_report_bot()
  File "dialogue_management_model.py", line 42, in run_report_bot
    interpreter = RasaNLUInterpreter('./models/')
  File "C:\Users\Cinta\Anaconda3\lib\site-packages\rasa\core\interpreter.py", line 263, in __init__
    self._load_interpreter()
  File "C:\Users\Cinta\Anaconda3\lib\site-packages\rasa\core\interpreter.py", line 286, in _load_interpreter
    self.interpreter = Interpreter.load(self.model_directory)
  File "C:\Users\Cinta\Anaconda3\lib\site-packages\rasa\nlu\model.py", line 304, in load
    Interpreter.ensure_model_compatibility(model_metadata)
  File "C:\Users\Cinta\Anaconda3\lib\site-packages\rasa\nlu\model.py", line 279, in ensure_model_compatibility
    "".format(model_version, rasa.__version__)
rasa.nlu.model.UnsupportedModelError: The model version is too old to be loaded by this Rasa NLU instance. Either retrain the model, or run with an older version. Model version: 0.0.0 Instance version: 1.3.9

**Comment by aziz-raihan** [comment]
I am having the same issue. any solution?

**Comment by erohmensing** [comment]
@aziz-raihan this issue is old and about version 1.3, when we are now on 1.9. If you are still seeing issues on the later versions, please open a new bug report and we'll reinvestigate.

**Comment by shivam1702** [comment]
Still getting this issue. I am using `rasa.nlu.train.train` with params: `nlu_config, data, path, fixed_model_name` to create a model using syncio run_until_complete in python, but unable to load the model using the cli command `rasa run -m trained_model`

**Comment by erohmensing** [comment]
See my above comment!
