### ISSUE TITLE
Train command crashes

### ISSUE THREAD

**Issue by tahamr83** [RasaHQ/rasa#4684]
**Rasa version**:
1.4.1
**Rasa X version** (if used & relevant):

**Python version**:
3.7.3
**Operating system** (windows, osx, ...):
MacOs 10.14.6
**Issue**:
The train command crashes when trying to build the docker image for a bot. 

**Command or request that led to error**:
```
rasa train \
	--domain config/domain.yml \
	--config config/config.yml \
	--fixed-model-name models \
	--out models/
```
**Error (including full traceback)**:
```
[2019-10-28 11:29:41,094: INFO/ForkPoolWorker-2] [91mTraceback (most recent call last):
  File "/usr/local/bin/rasa", line 5, in <module>
    from rasa.__main__ import main
  File "/usr/local/lib/python3.7/site-packages/rasa/__init__.py", line 8, in <module>
    from rasa.run import run
  File "/usr/local/lib/python3.7/site-packages/rasa/run.py", line 7, in <module>
    from rasa.core.lock_store import LockStore
  File "/usr/local/lib/python3.7/site-packages/rasa/core/__init__.py", line 6, in <module>
    from rasa.core.test import test
  File "/usr/local/lib/python3.7/site-packages/rasa/core/test.py", line 21, in <module>
    matplotlib.use("TkAgg")
  File "/usr/local/lib/python3.7/site-packages/matplotlib/cbook/deprecation.py", line 295, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/cbook/deprecation.py", line 356, in wrapper

    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/__init__.py", line 1254, in use
    plt.switch_backend(name)
  File "/usr/local/lib/python3.7/site-packages/matplotlib/pyplot.py", line 237, in switch_backend
    newbackend, required_framework, current_framework))
ImportError: Cannot load backend 'TkAgg' which requires the 'tk' interactive framework, as 'headless' is currently running

```
The same kind of error also occurs when trying to run the command locally on my machine when I try online training

**Command or request that led to error**:
```

rasa interactive \
	--endpoints config/endpoints.yml \
	--domain config/domain.yml \
	--config config/config.yml \
	--no-plot \
	--verbose
```
**Error (including full traceback)**:
```
Traceback (most recent call last):
  File "/Users/muhammadtahazaidi/.virtualenvs/project_dev-QMe0BD3g/bin/rasa", line 5, in <module>
    from rasa.__main__ import main
  File "/Users/muhammadtahazaidi/.virtualenvs/project_dev-QMe0BD3g/lib/python3.7/site-packages/rasa/__init__.py", line 8, in <module>
    from rasa.run import run
  File "/Users/muhammadtahazaidi/.virtualenvs/project_dev-QMe0BD3g/lib/python3.7/site-packages/rasa/run.py", line 7, in <module>
    from rasa.core.lock_store import LockStore
  File "/Users/muhammadtahazaidi/.virtualenvs/project_dev-QMe0BD3g/lib/python3.7/site-packages/rasa/core/__init__.py", line 6, in <module>
    from rasa.core.test import test
  File "/Users/muhammadtahazaidi/.virtualenvs/project_dev-QMe0BD3g/lib/python3.7/site-packages/rasa/core/test.py", line 21, in <module>
    matplotlib.use("TkAgg")
  File "/Users/muhammadtahazaidi/.virtualenvs/project_dev-QMe0BD3g/lib/python3.7/site-packages/matplotlib/cbook/deprecation.py", line 295, in wrapper
    return func(*args, **kwargs)
  File "/Users/muhammadtahazaidi/.virtualenvs/project_dev-QMe0BD3g/lib/python3.7/site-packages/matplotlib/cbook/deprecation.py", line 356, in wrapper
    return func(*args, **kwargs)
  File "/Users/muhammadtahazaidi/.virtualenvs/project_dev-QMe0BD3g/lib/python3.7/site-packages/matplotlib/__init__.py", line 1253, in use
    from matplotlib import pyplot as plt
  File "/Users/muhammadtahazaidi/.virtualenvs/project_dev-QMe0BD3g/lib/python3.7/site-packages/matplotlib/pyplot.py", line 2310, in <module>
    switch_backend(rcParams["backend"])
  File "/Users/muhammadtahazaidi/.virtualenvs/project_dev-QMe0BD3g/lib/python3.7/site-packages/matplotlib/pyplot.py", line 221, in switch_backend
    backend_mod = importlib.import_module(backend_name)
  File "/Users/muhammadtahazaidi/.virtualenvs/project_dev-QMe0BD3g/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/muhammadtahazaidi/.virtualenvs/project_dev-QMe0BD3g/lib/python3.7/site-packages/matplotlib/backends/backend_tkagg.py", line 1, in <module>
    from . import _backend_tk
  File "/Users/muhammadtahazaidi/.virtualenvs/project_dev-QMe0BD3g/lib/python3.7/site-packages/matplotlib/backends/_backend_tk.py", line 6, in <module>
    import tkinter as tk
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @wochinge will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by wochinge** [comment]
I'm so sorry @tahamr83 . Totally overlooked this issue. Looking into it now!

**Comment by wochinge** [comment]
Hi @tahamr83, I fixed in this pr https://github.com/RasaHQ/rasa/pull/4791 🎉
