### ISSUE TITLE
Rasa docs are malformed

### ISSUE THREAD

**Issue by kschoenrock-iw** [RasaHQ/rasa#4736]
**Rasa version**: latest? (this is for the documentation)

**Rasa X version** (if used & relevant): none

**Python version**: none

**Operating system** (windows, osx, ...): Ubuntu

**Issue**: Rasa docs are malformed, instead of code output there are stacktraces. Example: https://rasa.com/docs/rasa/user-guide/command-line-interface/#train-a-model

**Error (including full traceback)**:
```
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (python-dateutil 2.8.1 (/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages), Requirement.parse('python-dateutil<2.8.1,>=2.1; python_version >= "2.7"'), {'botocore'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.6.7/bin/rasa", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (python-dateutil 2.8.1 (/home/travis/virtualenv/python3.6.7/lib/python3.6/site-packages), Requirement.parse('python-dateutil<2.8.1,>=2.1; python_version >= "2.7"'), {'botocore'})

```

**Command or request that led to error**:
```
-
```

**Content of configuration file (config.yml)** (if relevant):
```yml
-
```

**Content of domain file (domain.yml)** (if relevant):
```yml
-
```

The documentation on the Rasa website wasn't properly generated.

**Comment by erohmensing** [comment]
Thanks for pointing this out! There is a build happening that should (hopefully 🤞 ) fix this as we speak. :)

**Comment by erohmensing** [comment]
Fixed in https://github.com/RasaHQ/rasa/pull/4732 😃
