### ISSUE TITLE
Error: Requested URL /conversations/

### ISSUE THREAD

**Issue by sushilr007** [RasaHQ/rasa#4744]
**Rasa version**:1.2.7

**Rasa X version** (if used & relevant): 0.22.2

**Python version**: 3.6.5

**Operating system** (windows, osx, ...): windows 10 

**Issue**:  I am hitting "http://localhost:5005/conversations" API from postman to get conversations. but getting an error. 

**Error (including full traceback)**:
```
Traceback (most recent call last):
  File "c:\users\abc\appdata\local\programs\python\python36\lib\site-packages\sanic\app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "c:\users\abc\appdata\local\programs\python\python36\lib\site-packages\sanic\router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "c:\users\abc\appdata\local\programs\python\python36\lib\site-packages\sanic\router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /conversations not found
```

**Command or request that led to error**:
```
rasa run --cors "*" -m models --enable-api --log-file out.log --endpoints endpoints.yml --debug
```

**Content of configuration file (config.yml)** (if relevant):
```yml
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline: supervised_embeddings

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```
**Content of enpoints file (endpoints.yml)**
```
action_endpoint:
  url: "http://localhost:5055/webhook"

tracker_store:
    type: SQL
    dialect: "mysql+pymysql"  # the dialect used to interact with the db
    url: "localhost"  # (optional) host of the sql db, e.g. "localhost"
    db: "db"  # path to your db
    username: "username" # username used for authentication
    password:  "password" # password used for authentication
    query:
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @imLew will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by imLew** [comment]
Thanks for raising this issue @sushilr007, can you please post the logs from the `rasa run` command?

**Comment by sushilr007** [comment]
`rasa run --cors "*" -m models --enable-api --log-file out.log --endpoints endpoints.yml --debug
2019-11-19 18:30:29 DEBUG    rasa.cli.utils  - Parameter 'credentials' not set. Using default location 'credentials.yml' instead.
2019-11-19 18:30:56 INFO     engineio.server  - Server initialized for sanic.
2019-11-19 18:30:56 DEBUG    rasa.core.utils  - Available web server routes:
/conversations/<conversation_id>/messages          POST                           add_message
/conversations/<conversation_id>/tracker/events    POST                           append_events
/webhooks/rasa                                     GET                            custom_webhook_RasaChatInput.health
/webhooks/rasa/webhook                             POST                           custom_webhook_RasaChatInput.receive
/webhooks/rest                                     GET                            custom_webhook_RestInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_RestInput.receive
/model/test/intents                                POST                           evaluate_intents
/model/test/stories                                POST                           evaluate_stories
/conversations/<conversation_id>/execute           POST                           execute_action
/domain                                            GET                            get_domain
/socket.io                                         GET                            handle_request
/                                                  GET                            hello
/model                                             PUT                            load_model
/model/parse                                       POST                           parse
/conversations/<conversation_id>/predict           POST                           predict
/conversations/<conversation_id>/tracker/events    PUT                            replace_events
/conversations/<conversation_id>/story             GET                            retrieve_story
/conversations/<conversation_id>/tracker           GET                            retrieve_tracker
/webhooks/socketio                                 GET                            socketio_webhook.health
/status                                            GET                            status
/model/predict                                     POST                           tracker_predict
/model/train                                       POST                           train
/model                                             DELETE                         unload_model
/version                                           GET                            version
2019-11-19 18:30:56 INFO     root  - Starting Rasa server on http://localhost:5005
2019-11-19 18:30:56 INFO     root  - Enabling coroutine debugging. Loop id 2085291583920.
2019-11-19 18:30:57 DEBUG    rasa.model  - Extracted model to 'C:\Users\SUSHIL~1\AppData\Local\Temp\tmpnsg6acb7'.
2019-11-19 18:30:59 DEBUG    rasa.core.tracker_store  - Attempting to connect to database via 'sqlite:///events.db'.
2019-11-19 18:30:59 DEBUG    rasa.core.tracker_store  - Connection to SQL database 'events.db' successful.
2019-11-19 18:30:59 DEBUG    rasa.core.tracker_store  - Connected to SQLTrackerStore.
2019-11-19 18:30:59 DEBUG    rasa.model  - Extracted model to 'C:\Users\SUSHIL~1\AppData\Local\Temp\tmpwgr_0499'.
2019-11-19 18:31:00 DEBUG    pykwalify.compat  - Using yaml library: c:\users\sushil`s pc\appdata\local\programs\python\python36\lib\site-packages\ruamel\yaml\__init__.py
[2019-11-19 18:31:42 +0530] [21020] [ERROR] Exception occurred while handling uri: 'http://localhost:5005/conversations'
Traceback (most recent call last):
  File "c:\users\sushil`s pc\appdata\local\programs\python\python36\lib\site-packages\sanic\app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "c:\users\sushil`s pc\appdata\local\programs\python\python36\lib\site-packages\sanic\router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "c:\users\sushil`s pc\appdata\local\programs\python\python36\lib\site-packages\sanic\router.py", line 469, in _get
    raise NotFound("Requested URL {} not found".format(url))`

**Comment by imLew** [comment]
I cannot reproduce this error (on mac), so I think it's not rasa related. Try upgrading your dependencies and running it in another environment.
