### ISSUE TITLE
Rasa X start Timeout error

### ISSUE THREAD

**Issue by kapoorh** [RasaHQ/rasa#4752]
When I run rasa x then it gives an error but UI opens fine:

Rasa X version - 0.22.2
Rasa version - 1.4.3
```
**ERROR    asyncio  - Task exception was never retrieved
future: <Task finished coro=<_track_async() done, defined at /opt/chatbot/rasax_environment/rasax_env/lib/python3.6/site-packages/rasax/community/metrics.py:84> exception=TimeoutError()>
Traceback (most recent call last):
  File "/opt/chatbot/rasax_environment/rasax_env/lib/python3.6/site-packages/rasax/community/metrics.py", line 127, in _track_async
    timeout=METRICS_HTTP_TIMEOUT,
  File "/opt/chatbot/rasax_environment/rasax_env/lib/python3.6/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/opt/chatbot/rasax_environment/rasax_env/lib/python3.6/site-packages/aiohttp/client.py", line 582, in _request
    break
  File "/opt/chatbot/rasax_environment/rasax_env/lib/python3.6/site-packages/aiohttp/helpers.py", line 596, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError**
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue about Rasa X 🔧@tmbo will get back to you about it soon!

###### In the meantime, you may find some useful information in the [Rasa X docs](https://rasa.com/docs/rasa-x/) or by searching our [forum](https://forum.rasa.com/c/rasa-x) 😊

**Comment by tmbo** [comment]
@federicotdn When we schedule the task for the metrics, we need to attach a handler catching any exceptions (basically after `loop.create_task(coro)`), basically something along these lines https://github.com/python/asyncio/issues/397#issuecomment-269124841 (to sum it up: there needs to be someone receiving the exception even if it is ignored).
