### ISSUE TITLE
Rasa X, continues the oracle migration error

### ISSUE THREAD

**Issue by DiegoProtec** [RasaHQ/rasa#4754]
**Rasa version**: 1.4.3

**Rasa X version**: 0.22.2

**Python version**: 3.6

**Operating system**: WINDOWS

**Issue**: I keep getting the error when I run the services, the Rasa X can't finish the database migration, the tables does created but can't import the dataset.

**Error (including full traceback)**:
```
rasa-x_1           | Traceback (most recent call last):
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
rasa-x_1           |     cursor, statement, parameters, context
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
rasa-x_1           |     cursor.execute(statement, parameters)
rasa-x_1           | cx_Oracle.DatabaseError: ORA-00936: expression not found
rasa-x_1           |
rasa-x_1           | The above exception was the direct cause of the following exception:
rasa-x_1           |
rasa-x_1           | Traceback (most recent call last):
rasa-x_1           |   File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
rasa-x_1           |     "__main__", mod_spec)
rasa-x_1           |   File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
rasa-x_1           |     exec(code, run_globals)
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/rasax/community/server.py", line 105, in <module>
rasa-x_1           |     main()
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/rasax/community/server.py", line 27, in main
rasa-x_1           |     sql_migrations.run_migrations(session)
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/rasax/community/sql_migrations.py", line 25, in run_migrations
rasa-x_1           |     _run_schema_migrations(session)
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/rasax/community/sql_migrations.py", line 41, in _run_schema_migrations
rasa-x_1           |     _run_alembic_migration(alembic_config)
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/rasax/community/sql_migrations.py", line 65, in _run_alembic_migration
rasa-x_1           |     command.upgrade(alembic_config, target_revision)
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/alembic/command.py", line 276, in upgrade
rasa-x_1           |     script.run_env()
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/alembic/script/base.py", line 475, in run_env
rasa-x_1           |     util.load_python_file(self.dir, "env.py")
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/alembic/util/pyfiles.py", line 90, in load_python_file
rasa-x_1           |     module = load_module_py(module_id, path)
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/alembic/util/compat.py", line 156, in load_module_py
rasa-x_1           |     spec.loader.exec_module(module)
rasa-x_1           |   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
rasa-x_1           |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/rasax/community/database/schema_migrations/alembic/env.py", line 89, in <module>
rasa-x_1           |     run_migrations_online()
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/rasax/community/database/schema_migrations/alembic/env.py", line 79, in run_migrations_online
rasa-x_1           |     context.run_migrations()
rasa-x_1           |   File "<string>", line 8, in run_migrations
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/alembic/runtime/environment.py", line 839, in run_migrations
rasa-x_1           |     self.get_context().run_migrations(**kw)
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/alembic/runtime/migration.py", line 361, in run_migrations
rasa-x_1           |     step.migration_fn(**kw)
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/rasax/community/database/schema_migrations/alembic/versions/migration_2019_08_30_add_unique_id_to_entitysynonyms_d45a0bf21e89.py", line 78, in upgrade
rasa-x_1           |     for row in session.execute("select name, synonym from entity_synonym"):
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1268, in execute
rasa-x_1           |     clause, params or {}
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 988, in execute
rasa-x_1           |     return meth(self, multiparams, params)
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
rasa-x_1           |     return connection._execute_clauseelement(self, multiparams, params)
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
rasa-x_1           |     distilled_params,
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
rasa-x_1           |     e, statement, parameters, cursor, context
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
rasa-x_1           |     util.raise_from_cause(sqlalchemy_exception, exc_info)
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 383, in raise_from_cause
rasa-x_1           |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 128, in reraise
rasa-x_1           |     raise value.with_traceback(tb)
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
rasa-x_1           |     cursor, statement, parameters, context
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
rasa-x_1           |     cursor.execute(statement, parameters)
rasa-x_1           | sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-00936: expression not found
rasa-x_1           | [SQL: select name, synonym from entity_synonym]
rasa-x_1           | (Background on this error at: http://sqlalche.me/e/4xp6)
```

**Command or request that led to error**:
```
python -m rasax.community.server
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @federicotdn will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by federicotdn** [comment]
@wochinge Do you know what might be causing this? I've added this issue to my to-do list but there's also a change you've seen this error before.

**Comment by DiegoProtec** [comment]
I guess that it does create the table with fk, but the "synonym_id" fk still not exist.

**Comment by wochinge** [comment]
I think it's some syntax in the migration which is not supported by Oracle. In order to avoid more of this "breaking-fixing-breaking" cycles we will have to first set up integration tests. Sorry @DiegoProtec , we try to get this done soon!

**Comment by wochinge** [comment]
@federicotdn We probably should change the pure sql queries to sql-alchemy core. I think some quotes or whatever are missing.

**Comment by federicotdn** [comment]
Ok! Thanks for the tip.

**Comment by federicotdn** [comment]
Interesting, for me, another migration is failing with another error:
```
2019-11-18 15:00:19 INFO     alembic.runtime.migration  - Running upgrade b4a9bd47b6e0 -> 8b528d137850, Add single column id for domain objects such as actions, slots, etc.
Traceback (most recent call last):
  File "/Users/federico/Workspace/rasa/rasa/cli/x.py", line 384, in run_locally
    local.main(args, project_path, args.data, token=rasa_x_token)
  File "/Users/federico/Workspace/rasa-x/src/community/rasax/community/local.py", line 189, in main
    sql_migrations.run_migrations(session)
  File "/Users/federico/Workspace/rasa-x/src/community/rasax/community/sql_migrations.py", line 25, in run_migrations
    _run_schema_migrations(session)
  File "/Users/federico/Workspace/rasa-x/src/community/rasax/community/sql_migrations.py", line 41, in _run_schema_migrations
    _run_alembic_migration(alembic_config)
  File "/Users/federico/Workspace/rasa-x/src/community/rasax/community/sql_migrations.py", line 65, in _run_alembic_migration
    command.upgrade(alembic_config, target_revision)
  File "/Users/federico/Workspace/rasa-x/env/lib/python3.7/site-packages/alembic/command.py", line 276, in upgrade
    script.run_env()
  File "/Users/federico/Workspace/rasa-x/env/lib/python3.7/site-packages/alembic/script/base.py", line 475, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/Users/federico/Workspace/rasa-x/env/lib/python3.7/site-packages/alembic/util/pyfiles.py", line 90, in load_python_file
    module = load_module_py(module_id, path)
  File "/Users/federico/Workspace/rasa-x/env/lib/python3.7/site-packages/alembic/util/compat.py", line 156, in load_module_py
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/federico/Workspace/rasa-x/src/community/rasax/community/database/schema_migrations/alembic/env.py", line 89, in <module>
    run_migrations_online()
  File "/Users/federico/Workspace/rasa-x/src/community/rasax/community/database/schema_migrations/alembic/env.py", line 79, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/Users/federico/Workspace/rasa-x/env/lib/python3.7/site-packages/alembic/runtime/environment.py", line 839, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/Users/federico/Workspace/rasa-x/env/lib/python3.7/site-packages/alembic/runtime/migration.py", line 361, in run_migrations
    step.migration_fn(**kw)
  File "/Users/federico/Workspace/rasa-x/src/community/rasax/community/database/schema_migrations/alembic/versions/migration_2019_07_19_single_ids_for_domain_items_8b528d137850.py", line 33, in upgrade
    batch_op, "domain_action", ["action_id"], "domain_action_pk"
  File "/usr/local/Cellar/python/3.7.4/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 119, in __exit__
    next(self.gen)
  File "/Users/federico/Workspace/rasa-x/env/lib/python3.7/site-packages/alembic/operations/base.py", line 325, in batch_alter_table
    impl.flush()
  File "/Users/federico/Workspace/rasa-x/env/lib/python3.7/site-packages/alembic/operations/batch.py", line 73, in flush
    fn(*arg, **kw)
  File "/Users/federico/Workspace/rasa-x/env/lib/python3.7/site-packages/alembic/ddl/impl.py", line 240, in drop_constraint
    self._exec(schema.DropConstraint(const))
  File "/Users/federico/Workspace/rasa-x/env/lib/python3.7/site-packages/alembic/ddl/oracle.py", line 30, in _exec
    result = super(OracleImpl, self)._exec(construct, *args, **kw)
  File "/Users/federico/Workspace/rasa-x/env/lib/python3.7/site-packages/alembic/ddl/impl.py", line 134, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/Users/federico/Workspace/rasa-x/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/Users/federico/Workspace/rasa-x/env/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 72, in _execute_on_connection
    return connection._execute_ddl(self, multiparams, params)
  File "/Users/federico/Workspace/rasa-x/env/lib/python3.7/site-packages/sqlalchemy/engine/base.py", line 1043, in _execute_ddl
    else None,
  File "<string>", line 1, in <lambda>
  File "/Users/federico/Workspace/rasa-x/env/lib/python3.7/site-packages/sqlalchemy/sql/elements.py", line 462, in compile
    return self._compiler(dialect, bind=bind, **kw)
  File "/Users/federico/Workspace/rasa-x/env/lib/python3.7/site-packages/sqlalchemy/sql/ddl.py", line 29, in _compiler
    return dialect.ddl_compiler(dialect, self, **kw)
  File "/Users/federico/Workspace/rasa-x/env/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 319, in __init__
    self.string = self.process(self.statement, **compile_kwargs)
  File "/Users/federico/Workspace/rasa-x/env/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 350, in process
    return obj._compiler_dispatch(self, **kwargs)
  File "/Users/federico/Workspace/rasa-x/env/lib/python3.7/site-packages/sqlalchemy/ext/compiler.py", line 436, in <lambda>
    lambda *arg, **kw: existing(*arg, **kw),
  File "/Users/federico/Workspace/rasa-x/env/lib/python3.7/site-packages/sqlalchemy/ext/compiler.py", line 478, in __call__
    return fn(element, compiler, **kw)
  File "/Users/federico/Workspace/rasa-x/env/lib/python3.7/site-packages/sqlalchemy/ext/compiler.py", line 423, in _wrap_existing_dispatch
    return existing_dispatch(element, compiler, **kw)
  File "/Users/federico/Workspace/rasa-x/env/lib/python3.7/site-packages/sqlalchemy/sql/visitors.py", line 91, in _compiler_dispatch
    return meth(self, **kw)
  File "/Users/federico/Workspace/rasa-x/env/lib/python3.7/site-packages/sqlalchemy/sql/compiler.py", line 3055, in visit_drop_constraint
    "it has no name" % drop.element
sqlalchemy.exc.CompileError: Can't emit DROP CONSTRAINT for constraint Constraint(_create_rule=<sqlalchemy.util.langhelpers.portable_instancemethod object at 0x10d4fc0a0>); it has no name
```
This is with Oracle Database 12c Standard Edition.

**Comment by DiegoProtec** [comment]
Rasa X version: **0.23.0**
Rasa version: **1.5.1**

Still in error.
```
rasa-x_1           | sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-00936: expression not found
rasa-x_1           | [SQL: select name, synonym from entity_synonym]
rasa-x_1           | (Background on this error at: http://sqlalche.me/e/4xp6)
```

**Comment by wochinge** [comment]
@ricwo Can we close this?
