### ISSUE TITLE
Rasa X - Copy to interactive learning

### ISSUE THREAD

**Issue by DiegoProtec** [RasaHQ/rasa#4788]
**Rasa version**:1.4.3

**Rasa X version**:0.22.2

**Python version**:3.6

**Operating system** (windows, osx, ...):Windows

**Issue**:
I get this error message when I execute “copy to interactive learning”.

**Error (including full traceback)**:
```
rasa-x_1           | Exception occurred while handling uri: 'http://rasa-x:5002/api/conversations/0a858ab87e0a41bd8f264ea96bcc8f6e/events'
rasa-x_1           | Traceback (most recent call last):
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 944, in handle_request
rasa-x_1           |     response = await response
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/rasax/community/api/decorators.py", line 177, in decorated_function
rasa-x_1           |     return await await_and_return_response(args, kwargs, request)
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/rasax/community/api/decorators.py", line 107, in await_and_return_response
rasa-x_1           |     response = await response
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/rasax/community/api/blueprints/stack.py", line 294, in update_events
rasa-x_1           |     conversation_id, _events, _event_service(request)
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/rasax/community/services/stack_service.py", line 124, in update_events
rasa-x_1           |     conversation_id
rasa-x_1           |   File "/usr/local/lib/python3.6/site-packages/rasax/community/services/stack_service.py", line 99, in timestamp_of_first_action_listen
rasa-x_1           |     events = tracker["events"]
rasa-x_1           | TypeError: 'NoneType' object is not subscriptable
```

**Command or request that led to error**:
```
http://rasa-x:5002/conversations/<conversation_id>/messages
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue about Rasa X 🔧@wochinge will get back to you about it soon!

###### In the meantime, you may find some useful information in the [Rasa X docs](https://rasa.com/docs/rasa-x/) or by searching our [forum](https://forum.rasa.com/c/rasa-x) 😊

**Comment by wochinge** [comment]
hi @DiegoProtec ,

it seems to me that Rasa X somehow cannot connect to Rasa. Do you get any more errors in your logs? Can you please try a request to `http://localhost:5002/api/health` and share the output here?

**Comment by DiegoProtec** [comment]
Here it is:
`get: http://localhost:5002/api/health`
```
{
  "production": {
    "version": "1.4.3",
    "minimum_compatible_version": "1.3.0a2",
    "status": 200
  },
  "worker": {
    "version": "1.4.3",
    "minimum_compatible_version": "1.3.0a2",
    "status": 200
  }
}
```

**Comment by DiegoProtec** [comment]
Hello @wochinge, something new about this?

**Comment by wochinge** [comment]
@DiegoProtec Sorry, we haven't had time to tackle this yet.

**Comment by DiegoProtec** [comment]
I'm updating the version Rasa X to 0.23.2 and Rasa to 1.5.1, but the error still occurs.

**Comment by wochinge** [comment]
> @DiegoProtec Sorry, we haven't had time to tackle this yet.

Sorry, this comment was actually for the Oracle issue of yours 🙈 
Do you have any logs in rasa-x when you run rasa-x with `DEBUG_MODE=true` (env variable)?

**Comment by DiegoProtec** [comment]
Going forward, probably the error occurs by the rabbitmq service. I'll try run it as debug mode for show you, I right be back. Thx!

**Comment by DiegoProtec** [comment]
Hello @wochinge!
I'm recieving this:
```
logger_1           | Named volume "./models:/app/models" is used in service "rasa-x" but no declaration was found in the volumes section.
```
What should I do?

**Comment by wochinge** [comment]
This is super weird, the `logger` container should not use the `./models` volume. Can you please share some logs and (considering the last error) also your file structure? Are you running any custom docker images / docker-compose files?

**Comment by DiegoProtec** [comment]
stacktrace:
```
rasa-x_1           | [2019-12-12 19:05:52 +0000] [26] [DEBUG] CORS: Request to '/api/conversations/Diego' matches CORS resource '/*'. Using options: {'origins': ['.*'], 'methods': 'DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT', 'allow_headers': ['.*'], 'expose_headers': 'X-Total-Count', 'supports_credentials': False, 'max_age': 1800, 'send_wildcard': False, 'automatic_options': True, 'vary_header': True, 'resources': '/*', 'intercept_exceptions': True, 'always_send': True}
rasa-x_1           | [2019-12-12 19:05:52 +0000] - (sanic.access)[INFO][192.168.240.1:38274]: GET http://localhost:5002/api/conversations/Diego?since=1574941457.0959365  200 300
rasa-x_1           | [2019-12-12 19:05:56 +0000] [26] [DEBUG] CORS: Request to '/api/conversations/Diego' matches CORS resource '/*'. Using options: {'origins': ['.*'], 'methods': 'DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT', 'allow_headers': ['.*'], 'expose_headers': 'X-Total-Count', 'supports_credentials': False, 'max_age': 1800, 'send_wildcard': False, 'automatic_options': True, 'vary_header': True, 'resources': '/*', 'intercept_exceptions': True, 'always_send': True}
rasa-x_1           | [2019-12-12 19:05:56 +0000] - (sanic.access)[INFO][192.168.240.1:38274]: GET http://localhost:5002/api/conversations/Diego?since=1574941457.0959365  200 300
rasa-x_1           | [2019-12-12 19:05:59 +0000] [26] [DEBUG] CORS: Request to '/api/conversations/Diego' matches CORS resource '/*'. Using options: {'origins': ['.*'], 'methods': 'DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT', 'allow_headers': ['.*'], 'expose_headers': 'X-Total-Count', 'supports_credentials': False, 'max_age': 1800, 'send_wildcard': False, 'automatic_options': True, 'vary_header': True, 'resources': '/*', 'intercept_exceptions': True, 'always_send': True}
rasa-x_1           | [2019-12-12 19:05:59 +0000] - (sanic.access)[INFO][192.168.240.1:38274]: GET http://localhost:5002/api/conversations/Diego?since=1574941457.0959365  200 300
rasa-x_1           | DEBUG:rasax.community.services.git_service:Running scheduled Git synchronization.
rasa-x_1           | DEBUG:rasax.community.services.git_service:Skip synchronizing with Git since no credentials were given.
rasa-production_1  | 2019-12-12 19:06:01 DEBUG    rasa.core.agent  - Requesting model from server http://rasa-x:5002/api/projects/default/models/tags/production...
rasa-x_1           | [2019-12-12 19:06:01 +0000] [26] [DEBUG] CORS: Request to '/api/projects/default/models/tags/production' matches CORS resource '/*'. Using options: {'origins': ['.*'], 'methods': 'DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT', 'allow_headers': ['.*'], 'expose_headers': 'X-Total-Count', 'supports_credentials': False, 'max_age': 1800, 'send_wildcard': False, 'automatic_options': True, 'vary_header': True, 'resources': '/*', 'intercept_exceptions': True, 'always_send': True}
rasa-x_1           | [2019-12-12 19:06:01 +0000] - (sanic.access)[INFO][192.168.240.4:39290]: GET http://rasa-x:5002/api/projects/default/models/tags/production?token=sPRlKyfBUtKO26tWf3ltpg%3D%3D  204 0
rasa-production_1  | 2019-12-12 19:06:01 DEBUG    rasa.core.agent  - Model server returned 204 status code, indicating that no new model is available. Current fingerprint: 0503dc4aef23e5771721142e93f901b6
rasa-production_1  | 2019-12-12 19:06:01 DEBUG    rasa.core.agent  - No new model found at URL http://rasa-x:5002/api/projects/default/models/tags/production
rasa-worker_1      | 2019-12-12 19:06:01 DEBUG    rasa.core.agent  - Requesting model from server http://rasa-x:5002/api/projects/default/models/tags/production...
rasa-x_1           | [2019-12-12 19:06:01 +0000] [27] [DEBUG] CORS: Request to '/api/projects/default/models/tags/production' matches CORS resource '/*'. Using options: {'origins': ['.*'], 'methods': 'DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT', 'allow_headers': ['.*'], 'expose_headers': 'X-Total-Count', 'supports_credentials': False, 'max_age': 1800, 'send_wildcard': False, 'automatic_options': True, 'vary_header': True, 'resources': '/*', 'intercept_exceptions': True, 'always_send': True}
rasa-x_1           | [2019-12-12 19:06:01 +0000] - (sanic.access)[INFO][192.168.240.5:37304]: GET http://rasa-x:5002/api/projects/default/models/tags/production?token=sPRlKyfBUtKO26tWf3ltpg%3D%3D  204 0
rasa-worker_1      | 2019-12-12 19:06:01 DEBUG    rasa.core.agent  - Model server returned 204 status code, indicating that no new model is available. Current fingerprint: 0503dc4aef23e5771721142e93f901b6
rasa-worker_1      | 2019-12-12 19:06:01 DEBUG    rasa.core.agent  - No new model found at URL http://rasa-x:5002/api/projects/default/models/tags/production
```
.env:
```
RASA_X_VERSION=0.23.3
RASA_VERSION=1.5.3
RASA_TOKEN=XWaODkhYaPHIJeZbYTvQHQ==
RASA_X_TOKEN=sPRlKyfBUtKO26tWf3ltpg==
RASA_WORKER_TOKEN=XWaODkhYaPHIJeZbYTvQHQ==
JWT_SECRET=0qhPKdeG5fN11ehhqGBm1A==
PASSWORD_SALT=b5hmedss2LIQrgzce9KVjg==
RABBITMQ_PASSWORD=teste
DB_PASSWORD=teste
REDIS_PASSWORD=teste
METRICS_CONSENT=false
```
docker-compose:
```
version: '3.4'

x-geral: &geral
  PROFILE: "dev"
  DEBUG_MODE: "true"

x-rasa-envs: &rasa-envs
  <<: *geral
  RASA_TOKEN: "${RASA_TOKEN}"
  RASA_X_TOKEN: "${RASA_X_TOKEN}"
  RASA_WORKER_TOKEN: "${RASA_WORKER_TOKEN}"
  JWT_SECRET: "${JWT_SECRET}"
  PASSWORD_SALT: "${PASSWORD_SALT}"
  RABBITMQ_HOST: "rabbit"
  RABBITMQ_USERNAME: "user"
  RABBITMQ_PASSWORD: "${RABBITMQ_PASSWORD}"
  DB_DIALECT: "postgresql"
  DB_HOST: "banco"
  DB_PORT: "5432"
  DB_USER: "admin"
  DB_PASSWORD: "${DB_PASSWORD}"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: "${REDIS_PASSWORD}"
  REDIS_DB: "1"

x-rasa_x-credentials: &rasa_x-credentials
  <<: *rasa-envs
  LOCAL_MODE: "false"
  RASA_MODEL_DIR: "/app/models"
  RASA_X_USER_ANALYTICS: "0"
  SANIC_RESPONSE_TIMEOUT: "3600"
  METRICS_CONSENT: "${METRICS_CONSENT}"
  SELF_PORT: "5002"
  UUID: "${UUID:-''}"
  RASA_PRODUCTION_HOST: "http://rasa-production:5005"
  RASA_WORKER_HOST: "http://rasa-worker:5005"

x-rasa-credentials: &rasa-credentials
  <<: *rasa-envs
  RASA_X_HOST: "http://rasa-x:5002"
  RASA_USER_APP: "http://app:5055"
  RASA_MODEL_SERVER: "http://rasa-x:5002/api/projects/default/models/tags/production"
  RASA_MODEL_PULL_INTERVAL: 10

x-rasa-services: &default-rasa-service
  restart: always
  extra_hosts:
    - banco:0.0.0.0
    - rabbit:0.0.0.0
  image: rasa/rasa:${RASA_VERSION}-full
  expose:
    - 5005
  volumes:
    - ./:/app
  command: >
    x
    --no-prompt
    --production
    --config-endpoint http://rasa-x:5002/api/config?token=${RASA_X_TOKEN}
    --port 5005
    --jwt-method HS256
    --jwt-secret ${JWT_SECRET}
    --auth-token '${RASA_TOKEN}'
    --enable-api
    --cors "*"
    --debug
  depends_on:
    - rasa-x
    - redis

services:
  rasa-x:
    restart: always
    extra_hosts:
      - banco:0.0.0.0
      - rabbit:0.0.0.0
    image: chatbot-rasa
    ports:
      - 5002:5002
    volumes:
      - ./models:/app/models
      - ./environments.yml:/app/environments.yml
      - ./credentials.yml:/app/credentials.yml
      - ./endpoints.yml:/app/endpoints.yml
      - ./logs:/logs
    environment:
      <<: *rasa_x-credentials
      RABBITMQ_QUEUE: "rasa-production-events"
      DB_DATABASE: "rasa"
  rasa-production:
    <<: *default-rasa-service
    environment:
      <<: *rasa-credentials
      RASA_ENVIRONMENT: "production"
      RABBITMQ_QUEUE: "rasa-production-events"
      DB_DATABASE: "tracker"
  rasa-worker:
    <<: *default-rasa-service
    environment:
      <<: *rasa-credentials
      RASA_ENVIRONMENT: "worker"
      RABBITMQ_QUEUE: "rasa-worker-events"
      DB_DATABASE: "worker_tracker"
  app:
    restart: always
    image: chatbot-app
    expose:
      - 5055
    volumes:
      - ./actions:/app/actions
      - ./services:/app/services
      - ./utils:/app/utils
    environment:
      <<: *geral
    command: >
      start
      --actions actions
      --cors "*"
      --debug
    depends_on:
      - rasa-production
  redis:
    restart: always
    image: "bitnami/redis:5.0.5"
    ports:
      - "6379:6379"
    environment:
      REDIS_PASSWORD: "${REDIS_PASSWORD}"
```

chatbot-rasa image:
```
FROM rasa/rasa:1.5.3-full

USER root

RUN pip install --upgrade pip && \
    pip install emoji==0.5.2 && \
    pip install psycopg2-binary==2.8.2 && \
    pip install unidecode==1.1.1 && \
    pip install websockets==8.1

USER 1001
```

chatbot-app image:
```
FROM rasa/rasa-sdk:1.5.2

USER root

RUN pip install --upgrade pip && \
    pip install SQLAlchemy~=1.3.3 && \
    pip install cx-Oracle==7.2.2

COPY ${PWD}/config.ini ./config.ini
COPY ${PWD}/dependencies.py ./dependencies.py
COPY ${PWD}/actions ./actions
COPY ${PWD}/services ./services
COPY ${PWD}/utils ./utils

USER 1001
```

I don't use nginx and logger images, I'm using the windows platform.

**Comment by DiegoProtec** [comment]
Hello @wochinge, something new?

**Comment by wochinge** [comment]
@DiegoProtec Sorry, I was on christmas vacation. I wish you a happy new year! 

@Saladdin Could it be that the frontend sends a request to `PUT /conversations/<conversation_id>/events` before `POST http://localhost/api/conversations` was completed?

**Comment by wochinge** [comment]
@DiegoProtec we revamped the backend logic for the interactive learning in 0.27. Can you please try if this works now?
