### ISSUE TITLE
unable to add ConverRT featurizer to config

### ISSUE THREAD

**Issue by DivyashaAgrawal** [RasaHQ/rasa#4858]
**Rasa version**: latest NLU

**Python version**: 3.7

**Operating system** (windows, osx, ...): Manjaro

**Issue**: When adding conveRT featurizer to config, throws ModuleNotFoundError

**Error (including full traceback)**:
```
Traceback (most recent call last):
  File "/home/rivi/miniconda3/envs/nlu-flair/lib/python3.7/site-packages/rasa/nlu/registry.py", line 146, in get_component_class
    return class_from_module_path(component_name)
  File "/home/rivi/miniconda3/envs/nlu-flair/lib/python3.7/site-packages/rasa/utils/common.py", line 193, in class_from_module_path
    raise ImportError(f"Cannot retrieve class from path {module_path}.")
ImportError: Cannot retrieve class from path ConveRTFeaturizer.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rivi/miniconda3/envs/nlu-flair/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/home/rivi/miniconda3/envs/nlu-flair/lib/python3.7/site-packages/rasa/__main__.py", line 76, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/home/rivi/miniconda3/envs/nlu-flair/lib/python3.7/site-packages/rasa/cli/train.py", line 138, in train_nlu
    persist_nlu_training_data=args.persist_nlu_data,
  File "/home/rivi/miniconda3/envs/nlu-flair/lib/python3.7/site-packages/rasa/train.py", line 399, in train_nlu
    persist_nlu_training_data,
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/home/rivi/miniconda3/envs/nlu-flair/lib/python3.7/site-packages/rasa/train.py", line 430, in _train_nlu_async
    persist_nlu_training_data=persist_nlu_training_data,
  File "/home/rivi/miniconda3/envs/nlu-flair/lib/python3.7/site-packages/rasa/train.py", line 459, in _train_nlu_with_validated_data
    persist_nlu_training_data=persist_nlu_training_data,
  File "/home/rivi/miniconda3/envs/nlu-flair/lib/python3.7/site-packages/rasa/nlu/train.py", line 68, in train
    trainer = Trainer(nlu_config, component_builder)
  File "/home/rivi/miniconda3/envs/nlu-flair/lib/python3.7/site-packages/rasa/nlu/model.py", line 148, in __init__
    components.validate_requirements(cfg.component_names)
  File "/home/rivi/miniconda3/envs/nlu-flair/lib/python3.7/site-packages/rasa/nlu/components.py", line 38, in validate_requirements
    component_class = registry.get_component_class(component_name)
  File "/home/rivi/miniconda3/envs/nlu-flair/lib/python3.7/site-packages/rasa/nlu/registry.py", line 175, in get_component_class
    raise ModuleNotFoundError(exception_message)
ModuleNotFoundError: Cannot find class 'ConveRTFeaturizer' from global namespace. Please check that there is no typo in the class name and that you have imported the class into the global namespace.
```

**Command or request that led to error**:
```
rasa train nlu
```

**Content of configuration file (config.yml)** (if relevant):
```yml
language: en

pipeline:
  - name: WhitespaceTokenizer
  - name: ConveRTFeaturizer
  - name: EmbeddingIntentClassifier
```

**Comment by MinaBeirami** [comment]
Does anybody else have this problem? I am still facing this error for  "EmbeddingIntentClassifier".

**Comment by Ishan100** [comment]
Did anybody got the solution for this issue, I am also facing the same issue ?

**Comment by urbanusm** [comment]
I got the same problem too and it's so unfortunate that it's 2021 and nobody got the solution @MinaBeirami
