### ISSUE TITLE
InvalidSignatureError

### ISSUE THREAD

**Issue by AlucardNosferatu** [RasaHQ/rasa#4881]
**Rasa version**:Rasa 1.5.1

**Rasa X version** (if used & relevant):I dont know

**Python version**:Python 3.6

**Operating system** (windows, osx, ...):Ubuntu 16.04

**Issue**:
rasa init --ok
rasa shell --ok
rasa x --failed

**Error (including full traceback)**:
```
scrooge@scrooge-X455LD:~/RASA$ rasa x
Traceback (most recent call last):
  File "/usr/local/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/rasa/__main__.py", line 76, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/usr/local/lib/python3.6/dist-packages/rasa/cli/x.py", line 291, in rasa_x
    run_locally(args)
  File "/usr/local/lib/python3.6/dist-packages/rasa/cli/x.py", line 379, in run_locally
    from rasax.community import local  # pytype: disable=import-error
  File "/usr/local/lib/python3.6/dist-packages/rasax/community/local.py", line 13, in <module>
    import rasax.community.jwt
  File "/usr/local/lib/python3.6/dist-packages/rasax/community/jwt.py", line 5, in <module>
    from jwt import InvalidSignatureError
ImportError: cannot import name 'InvalidSignatureError'

```

**Command or request that led to error**:
```
cd
mkdir RASA
rasa init --no-prompt
rasa shell
/stop
rasa x
```

**Content of configuration file (config.yml)** (if relevant):
```yml
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline: supervised_embeddings

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
```

**Content of domain file (domain.yml)** (if relevant):
```yml
intents:
  - greet
  - goodbye
  - affirm
  - deny
  - mood_great
  - mood_unhappy
  - bot_challenge

actions:
- utter_greet
- utter_cheer_up
- utter_did_that_help
- utter_happy
- utter_goodbye
- utter_iamabot

templates:
  utter_greet:
  - text: "Hey! How are you?"

  utter_cheer_up:
  - text: "Here is something to cheer you up:"
    image: "https://i.imgur.com/nGF1K8f.jpg"

  utter_did_that_help:
  - text: "Did that help you?"

  utter_happy:
  - text: "Great, carry on!"

  utter_goodbye:
  - text: "Bye"

  utter_iamabot:
  - text: "I am a bot, powered by Rasa."
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @rgstephens will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by 402210313** [comment]
i have same problem. is this solved?

**Comment by AlucardNosferatu** [comment]
> i have same problem. is this solved?

Nope
