### ISSUE TITLE
ImportError: cannot import name 'Deque'. when I type rasa init

### ISSUE THREAD

**Issue by Maadhav** [RasaHQ/rasa#4906]
```
**_C:\Users\Maadhav\rasa>_** rasa init
Traceback (most recent call last):
  File "C:\Users\Maadhav\AppData\Local\Programs\Python\Python36\Scripts\rasa-script.py", line 11, in <module>
    load_entry_point('rasa', 'console_scripts', 'rasa')()
  File "c:\users\maadhav\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\users\maadhav\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "c:\users\maadhav\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 2443, in load
    return self.resolve()
  File "c:\users\maadhav\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\maadhav\rasa\rasa\__init__.py", line 8, in <module>
    from rasa.run import run
  File "c:\users\maadhav\rasa\rasa\run.py", line 7, in <module>
    from rasa.core.lock_store import LockStore
  File "c:\users\maadhav\rasa\rasa\core\__init__.py", line 5, in <module>
    from rasa.core.train import train
  File "c:\users\maadhav\rasa\rasa\core\train.py", line 11, in <module>
    from rasa.core.domain import Domain
  File "c:\users\maadhav\rasa\rasa\core\domain.py", line 11, in <module>
    import rasa.utils.common as common_utils
  File "c:\users\maadhav\rasa\rasa\utils\common.py", line 7, in <module>
    import rasa.core.utils
  File "c:\users\maadhav\rasa\rasa\core\utils.py", line 27, in <module>
    from sanic import Sanic
  File "c:\users\maadhav\appdata\local\programs\python\python36\lib\site-packages\sanic\__init__.py", line 2, in <module>
    from sanic.app import Sanic
  File "c:\users\maadhav\appdata\local\programs\python\python36\lib\site-packages\sanic\app.py", line 18, in <module>
    from sanic.asgi import ASGIApp
  File "c:\users\maadhav\appdata\local\programs\python\python36\lib\site-packages\sanic\asgi.py", line 28, in <module>
    from sanic.websocket import WebSocketConnection
  File "c:\users\maadhav\appdata\local\programs\python\python36\lib\site-packages\sanic\websocket.py", line 12, in <module>
    from websockets import (  # type: ignore
  File "c:\users\maadhav\appdata\local\programs\python\python36\lib\site-packages\websockets\__init__.py", line 3, in <module>
    from .auth import *
  File "c:\users\maadhav\appdata\local\programs\python\python36\lib\site-packages\websockets\auth.py", line 15, in <module>
    from .server import HTTPResponse, WebSocketServerProtocol
  File "c:\users\maadhav\appdata\local\programs\python\python36\lib\site-packages\websockets\server.py", line 49, in <module>
    from .protocol import WebSocketCommonProtocol
  File "c:\users\maadhav\appdata\local\programs\python\python36\lib\site-packages\websockets\protocol.py", line 18, in <module>
    from typing import (
ImportError: cannot import name 'Deque'
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @tabergma will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by tabergma** [comment]
Sorry, for the late reply. 

Do you still face the issue? What Rasa version are you using?

**Comment by tmbo** [comment]
you need to update to python >= 3.6.1
