### ISSUE TITLE
schemas/config.yml missing from wheel distribution

### ISSUE THREAD

**Issue by eric-bonfadini** [RasaHQ/rasa#4914]
**Rasa version**: Rasa 1.5.1

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**: 3.6.7

**Operating system** (windows, osx, ...): osx

**Issue**: in the wheel version of rasa the file ```rasa/nlu/schemas/config.yml``` is missing, while it is available in the source tar.gz version.
For this reason, I cannot launch the rasa test nlu command below. It works correctly if I copy manually the missing folder inside the virtualenv.

**Error (including full traceback)**:
```
Traceback (most recent call last):
  File "~/envs/env_rasa/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "~/envs/env_rasa/lib/python3.6/site-packages/rasa/__main__.py", line 76, in main
    cmdline_arguments.func(cmdline_arguments)
  File "~/envs/env_rasa/lib/python3.6/site-packages/rasa/cli/test.py", line 122, in test_nlu
    show_validation_errors=False,
  File "~/envs/env_rasa/lib/python3.6/site-packages/rasa/utils/validation.py", line 57, in validate_yaml_schema
    c = Core(source_data=source_data, schema_files=[schema_file])
  File "~/envs/env_rasa/lib/python3.6/site-packages/pykwalify/core.py", line 84, in __init__
    raise CoreError(u"Provided source_file do not exists on disk : {0}".format(f))
pykwalify.errors.CoreError: <CoreError: error code 3: Provided source_file do not exists on disk : ~/envs/env_rasa/lib/python3.6/site-packages/rasa/nlu/schemas/config.yml: Path: '/'>
```

**Command or request that led to error**:
```
rasa test nlu --config pretrained_embeddings_spacy.yml supervised_embeddings.yml --nlu data/nlu.md --runs 3 --percentages 0 25 50 70 90 -vv
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @tmbo will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by igormis** [comment]
I have the same issue:
```
Traceback (most recent call last):
  File "/home/doit/anaconda3/envs/rasa2/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/home/doit/anaconda3/envs/rasa2/lib/python3.6/site-packages/rasa/__main__.py", line 76, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/home/doit/anaconda3/envs/rasa2/lib/python3.6/site-packages/rasa/cli/test.py", line 122, in test_nlu
    show_validation_errors=False,
  File "/home/doit/anaconda3/envs/rasa2/lib/python3.6/site-packages/rasa/utils/validation.py", line 57, in validate_yaml_schema
    c = Core(source_data=source_data, schema_files=[schema_file])
  File "/home/doit/anaconda3/envs/rasa2/lib/python3.6/site-packages/pykwalify/core.py", line 84, in __init__
    raise CoreError(u"Provided source_file do not exists on disk : {0}".format(f))
pykwalify.errors.CoreError: <CoreError: error code 3: Provided source_file do not exists on disk : /home/doit/anaconda3/envs/rasa2/lib/python3.6/site-packages/rasa/nlu/schemas/config.yml: Path: '/'>
```
when executing:
`rasa test nlu --config pretrained_embeddings_spacy.yml supervised_embeddings.yml --nlu CF_model/config_en.json --runs 3 --percentages 0 25 50 70 90`

where config_en.json is the file with the training data and the content of
`pretrained_embeddings_spacy.yml `is
```
language: "en"

pipeline: "pretrained_embeddings_spacy"
```

whereas the content of `supervised_embeddings.yml` is:
```
language: "en"

pipeline: "supervised_embeddings"
```
Any ideas?

**Comment by eric-bonfadini** [comment]
I think we just need to modify the Mainifest file in order to include also this (and maybe some other missing?) files.
I can make a PR if needed.

**Comment by tmbo** [comment]
Yes that would be perfect, can you please fork from `1.5.x` and also target the branch there?
