### ISSUE TITLE
AttributeError : 'NoneType' object has no attribute 'setdefault'

### ISSUE THREAD

**Issue by SouvikMondalD** [RasaHQ/rasa#4924]
**Rasa version**: 1.5.2

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**: 3.6.9

**Operating system** (windows, osx, ...): ubuntu

**Issue**:

When using 'rasa train' to train after modifying the data and domain, I get the following error :

**Error (including full traceback)**:
```
Traceback (most recent call last):
  File "/home/souvik/rasa_de/rasa_de_env/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/home/souvik/rasa_de/rasa_de_env/lib/python3.6/site-packages/rasa/__main__.py", line 76, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/home/souvik/rasa_de/rasa_de_env/lib/python3.6/site-packages/rasa/cli/train.py", line 76, in train
    kwargs=extract_additional_arguments(args),
  File "/home/souvik/rasa_de/rasa_de_env/lib/python3.6/site-packages/rasa/train.py", line 46, in train
    kwargs=kwargs,
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/home/souvik/rasa_de/rasa_de_env/lib/python3.6/site-packages/rasa/train.py", line 84, in train_async
    domain = await file_importer.get_domain()
  File "/home/souvik/rasa_de/rasa_de_env/lib/python3.6/site-packages/rasa/importers/importer.py", line 242, in get_domain
    domains = await asyncio.gather(*domains)
  File "/home/souvik/rasa_de/rasa_de_env/lib/python3.6/site-packages/rasa/importers/rasa.py", line 66, in get_domain
    domain = Domain.load(self._domain_path)
  File "/home/souvik/rasa_de/rasa_de_env/lib/python3.6/site-packages/rasa/core/domain.py", line 72, in load
    other = cls.from_path(path)
  File "/home/souvik/rasa_de/rasa_de_env/lib/python3.6/site-packages/rasa/core/domain.py", line 82, in from_path
    domain = cls.from_file(path)
  File "/home/souvik/rasa_de/rasa_de_env/lib/python3.6/site-packages/rasa/core/domain.py", line 95, in from_file
    return cls.from_yaml(rasa.utils.io.read_file(path))
  File "/home/souvik/rasa_de/rasa_de_env/lib/python3.6/site-packages/rasa/core/domain.py", line 105, in from_yaml
    return cls.from_dict(data)
  File "/home/souvik/rasa_de/rasa_de_env/lib/python3.6/site-packages/rasa/core/domain.py", line 121, in from_dict
    **additional_arguments,
  File "/home/souvik/rasa_de/rasa_de_env/lib/python3.6/site-packages/rasa/core/domain.py", line 283, in __init__
    self.intent_properties = self.collect_intent_properties(intents)
  File "/home/souvik/rasa_de/rasa_de_env/lib/python3.6/site-packages/rasa/core/domain.py", line 213, in collect_intent_properties
    properties.setdefault("use_entities", True)
AttributeError: 'NoneType' object has no attribute 'setdefault'
```

**Command or request that led to error**:
```
rasa train
```

**Content of configuration file (config.yml)** (if relevant):
```yml
language: de
pipeline: pretrained_embeddings_spacy
policies:
- name: MemoizationPolicy
- name: KerasPolicy
- name: MappingPolicy
- name: "FallbackPolicy"
  nlu_threshold: 0.1
  core_threshold: 0.1
  fallback_action_name: "action_default_fallback"

```

**Content of domain file (domain.yml)** (if relevant):
```yml
intents:
  - card_lost:
    use_entities: []
  - greet
  - goodbye
  - affirm
  - deny
  - mood_great
  - mood_unhappy
  - bot_challenge

entities:
  - cardtype
  - verfallsdatum
  - verlustart
  - ersatzkarte
  - anrufer_ist_auch_karteninhaber

actions:
- utter_greet
- utter_cheer_up
- utter_did_that_help
- utter_happy
- utter_goodbye
- utter_iamabot
- utter_which_cardtype
- utter_which_verfallsdatum
- utter_which_verlustart
- utter_ersatzkarte_required
- utter_anrufer_ist_auch_karteninhaber

templates:
  utter_greet:
  - text: 'Hallo! '
  - text: Servus!
  - text: Grüß Gott!
  - text: Guten Tag!

  utter_which_cardtype:
  - text: "Um welchen Kartentyp handelt es sich?"
    buttons:
    - title: "Bankomatkarte"
      payload: '/card_type{"cardtype": "bankomatkarte"}'
    - title: "Kreditkarte"
      payload: '/card_type{"cardtype": "kreditkarte"}'
    - title: "Andere karte"
      payload: '/card_type{"cardtype": "karte"}'

  utter_which_verfallsdatum:
  - text: "Wann war Ihre Karte verloren?"

  utter_which_verlustart:
  - text: "Um welchen Kartentyp handelt es sich?"
    buttons:
    - title: "Verlust"
      payload: '/card_lost{"cardtype": {cardtype}, "verlustart": "verlust"}'
    - title: "Diebstahl"
      payload: '/card_lost{"cardtype": {cardtype}, "verlustart": "diebstahl"}'
    - title: "Sonstiges"
      payload: '/card_lost{"cardtype": {cardtype}, "verlustart": "sonstiges"}'

  utter_ersatzkarte_required:
  - text: "Erfordern Sie eine ersatzkarte?"
    buttons:
    - title: "Ersatzkarte Ja"
      payload: '/ersatzkarte{"cardtype": {cardtype}, "ersatzkarte": "ja"}'
    - title: "Ersatzkarte Nein"
      payload: '/ersatzkarte{"cardtype": {cardtype}, "verlustart": "nein"}'

  utter_anrufer_ist_auch_karteninhaber:
  - text: "Sind Sie der karteninhaber?"
    buttons:
    - title: "Karteninhaber Ja"
      payload: '/anrufer_ist_auch_karteninhaber{"cardtype": {cardtype}, "ersatzkarte": "ja"}'
    - title: "Karteninhaber Nein"
      payload: '/anrufer_ist_auch_karteninhaber{"cardtype": {cardtype}, "verlustart": "nein"}'

  utter_cheer_up:
  - text: "Here is something to cheer you up:"
    image: "https://i.imgur.com/nGF1K8f.jpg"

  utter_did_that_help:
  - text: "Did that help you?"

  utter_happy:
  - text: "Great, carry on!"

  utter_goodbye:
  - text: "Bye"

  utter_iamabot:
  - text: "I am a bot, powered by Rasa."
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @dakshvar22 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by dakshvar22** [comment]
Hi @SouvikMondalD ,

> after modifying the data and domain

Did you have a previous working version of it? What did you change? That might be helpful in debugging.

**Comment by SouvikMondalD** [comment]
Thanks, there was an issue with the slots config

**Comment by venkattejaRaavi** [comment]
HI I am getting the same error what is the solution?
