### ISSUE TITLE
Getting error while running default rasa model

### ISSUE THREAD

**Issue by manish2869** [RasaHQ/rasa#4932]
$ rasa train

/home/times-67/rasa/rasa/core/training/dsl.py:416: UserWarning: Found unknown intent 'inform' on line 4. Please, make sure that all intents are listed in your domain yaml.
  f"Found unknown intent '{intent_name}' on line {line_num}. "
Traceback (most recent call last):
  File "/home/times-67/anaconda3/bin/rasa", line 11, in <module>
    load_entry_point('rasa', 'console_scripts', 'rasa')()
  File "/home/times-67/rasa/rasa/__main__.py", line 76, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/home/times-67/rasa/rasa/cli/train.py", line 76, in train
    kwargs=extract_additional_arguments(args),
  File "/home/times-67/rasa/rasa/train.py", line 46, in train
    kwargs=kwargs,
  File "uvloop/loop.pyx", line 1417, in uvloop.loop.Loop.run_until_complete
  File "/home/times-67/rasa/rasa/train.py", line 97, in train_async
    kwargs,
  File "/home/times-67/rasa/rasa/train.py", line 140, in _train_async_internal
    file_importer.get_stories(), file_importer.get_nlu_data()
  File "/home/times-67/rasa/rasa/importers/importer.py", line 269, in get_nlu_data
    nlu_data = await asyncio.gather(*nlu_data)
  File "/home/times-67/rasa/rasa/importers/rasa.py", line 61, in get_nlu_data
    return utils.training_data_from_paths(self._nlu_files, language)
  File "/home/times-67/rasa/rasa/importers/utils.py", line 9, in training_data_from_paths
    training_datas = [loading.load_data(nlu_file, language) for nlu_file in paths]
  File "/home/times-67/rasa/rasa/importers/utils.py", line 9, in <listcomp>
    training_datas = [loading.load_data(nlu_file, language) for nlu_file in paths]
  File "/home/times-67/rasa/rasa/nlu/training_data/loading.py", line 67, in load_data
    data_sets = [_load(f, language) for f in files]
  File "/home/times-67/rasa/rasa/nlu/training_data/loading.py", line 67, in <listcomp>
    data_sets = [_load(f, language) for f in files]
  File "/home/times-67/rasa/rasa/nlu/training_data/loading.py", line 138, in _load
    return reader.read(filename, language=language, fformat=fformat)
  File "/home/times-67/rasa/rasa/nlu/training_data/formats/readerwriter.py", line 15, in read
    return self.reads(rasa.utils.io.read_file(filename), **kwargs)
  File "/home/times-67/rasa/rasa/nlu/training_data/formats/markdown.py", line 76, in reads
    self._set_current_section(header[0], header[1])
  File "/home/times-67/rasa/rasa/nlu/training_data/formats/markdown.py", line 195, in _set_current_section
    "".format(section, "', '".join(available_sections))
ValueError: Found markdown section 'entity' which is not in the allowed sections 'intent', 'synonym', 'regex', 'lookup'.

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template.
