### ISSUE TITLE
All rasa commands show errors after successful installation

### ISSUE THREAD

**Issue by PilgrimViis** [RasaHQ/rasa#4940]
**Rasa version**:
1.5.2
**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):
0.23.3
**Python version**:
Python 3.6.9 :: Anaconda, Inc.
**Operating system** (windows, osx, ...):
Windows 10
**Issue**:
 After successful installation of Rasa on trying to iniitialize using rasa init an error is thrown. Rasa installed in anaconda virtual environment by using command from rasa installation guide
_pip install rasa-x --extra-index-url https://pypi.rasa.com/simple_
And looks like all rasa commands throws the same error. Even rasa --version

**Error (including full traceback)**:
```
(rasa) F:\Projects\Testing\rasa>rasa init
Traceback (most recent call last):
  File "c:\programdata\anaconda3\envs\rasa\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\envs\rasa\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\rasa\Scripts\rasa.exe\__main__.py", line 4, in <module>
  File "c:\programdata\anaconda3\envs\rasa\lib\site-packages\rasa\__init__.py", line 8, in <module>
    from rasa.run import run
  File "c:\programdata\anaconda3\envs\rasa\lib\site-packages\rasa\run.py", line 7, in <module>
    from rasa.core.lock_store import LockStore
  File "c:\programdata\anaconda3\envs\rasa\lib\site-packages\rasa\core\__init__.py", line 5, in <module>
    from rasa.core.train import train
  File "c:\programdata\anaconda3\envs\rasa\lib\site-packages\rasa\core\train.py", line 11, in <module>
    from rasa.core.domain import Domain
  File "c:\programdata\anaconda3\envs\rasa\lib\site-packages\rasa\core\domain.py", line 11, in <module>
    import rasa.utils.common as common_utils
  File "c:\programdata\anaconda3\envs\rasa\lib\site-packages\rasa\utils\common.py", line 7, in <module>
    import rasa.core.utils
  File "c:\programdata\anaconda3\envs\rasa\lib\site-packages\rasa\core\utils.py", line 27, in <module>
    from sanic import Sanic
  File "c:\programdata\anaconda3\envs\rasa\lib\site-packages\sanic\__init__.py", line 2, in <module>
    from sanic.app import Sanic
  File "c:\programdata\anaconda3\envs\rasa\lib\site-packages\sanic\app.py", line 18, in <module>
    from sanic.asgi import ASGIApp
  File "c:\programdata\anaconda3\envs\rasa\lib\site-packages\sanic\asgi.py", line 22, in <module>
    from sanic.compat import Header
  File "c:\programdata\anaconda3\envs\rasa\lib\site-packages\sanic\compat.py", line 4, in <module>
    class Header(CIMultiDict):
TypeError: type 'multidict._multidict.CIMultiDict' is not an acceptable base type
```

**Command or request that led to error**:
```
rasa init, rasa --version, rasa --help. Looks like all of them
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by bhavaniravi** [comment]
having the same issue MacOS, Python 3.7

**Comment by PilgrimViis** [comment]
@bhavaniravi thank you very much. It helps me as well.

**Comment by sara-tagger** [comment]
Thanks for the issue, @Ghostvv will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by mav1797** [comment]
> having the same issue MacOS, Python 3.7
> 
> Turns out it was an issue with sanic server's dependency `multidict` downgrading it helped me get rasa running
> 
> [huge-success/sanic#1729 (comment)](https://github.com/huge-success/sanic/issues/1729#issuecomment-564312966)

how can i do that?
