### ISSUE TITLE
Rasa x HTTP API /conversations/{conversation_id}/events ~/debug-dump.md ~/debug-dump.json throwing errors

### ISSUE THREAD

**Issue by testphys** [RasaHQ/rasa#5000]
**Rasa version**: 1.3.9

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant): 0.21.6

**Python version**:

**Operating system** (windows, osx, ...):

**Issue**:  I get a 405 error on /conversations/{conversation_id}/events and 404 errors on ~/debug-dump.md and ~/debug-dump.json. I used the helm chart to deploy rasa-x.

**Error (including full traceback)**:
```
[2019-12-19 14:39:58 +0000] [20] [ERROR] Exception occurred while handling uri: 'http://34.89.143.66/api/conversations/1049945993/events'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/sanic/app.py", line 893, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/usr/local/lib/python3.6/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/usr/local/lib/python3.6/site-packages/sanic/router.py", line 468, in _get
    raise method_not_supported
sanic.exceptions.MethodNotSupported: Method GET not allowed for URL /api/conversations/1049945993/events
```
```
[2019-12-19 14:41:05 +0000] - (sanic.access)[INFO][10.16.0.27:53658]: GET http://34.89.143.66/api/conversations/1049945993/debug-dump.md  404 10
```

```
[2019-12-19 14:41:45 +0000] - (sanic.access)[INFO][10.16.0.27:53854]: GET http://34.89.143.66/api/conversations/1049945993/debug-dump.json  404 10

```

**Command or request that led to error**:
```
headers = {"Authorization": "Bearer {}".format(access_token)}


# api-endpoint |
URL = "http://34.89.143.66:8000/api/conversations/{conversation_id}/debug-dump.json"
  
# sending get request and saving the response as response object 
r = requests.get(url = URL,headers=headers) 
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by ricwo** [comment]
Hi @testphys, thanks for raising this issue! Rasa X doesn't actually have the `GET /events` endpoint - this is a mistake in the API spec and we'll be sure to update it. The debug dumps are not accessible via dedicated endpoints anymore - you can get either of them from the `GET /conversations/id` endpoint by specifying the `Accept` header as either `application/json` (to get the NLU data json dump) or as `text/markdown` (to get the story markdown dump). Thanks for pointing this out - we'll be fixing the API docs soon
