### ISSUE TITLE
Error when using SSL

### ISSUE THREAD

**Issue by juanmariareina** [RasaHQ/rasa#5002]
I'm trying to start RASA with SSL, since our portal is accesed via https:

`rasa run -m models --ssl-certificate /home/jmreina/rasa_cert/rasa.crt --ssl-keyfile /home/jmreina/rasa_cert/rasa.key --enable-api --cors "*"&`

But there is an error:

`jmreina@rasa-chatbot:~/project$ 2019-12-19 17:08:53 INFO     engineio.server  - Server initialized for sanic.
Enter PEM pass phrase:
Traceback (most recent call last):
  File "/usr/local/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/rasa/__main__.py", line 76, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/usr/local/lib/python3.7/dist-packages/rasa/cli/run.py", line 83, in run
    rasa.run(**vars(args))
  File "/usr/local/lib/python3.7/dist-packages/rasa/run.py", line 56, in run
    **kwargs,
  File "/usr/local/lib/python3.7/dist-packages/rasa/core/run.py", line 177, in serve_application
    ssl_certificate, ssl_keyfile, ssl_ca_file, ssl_password
  File "/usr/local/lib/python3.7/dist-packages/rasa/server.py", line 255, in create_ssl_context
    ssl_certificate, keyfile=ssl_keyfile, password=ssl_password
OSError: [Errno 22] Invalid argument
`
Cheers!

**Comment by juanmariareina** [comment]
Well, I managed to fix this. The point is to use a no-password key. My apologies! 

Hope this experience helps the other users!

**Comment by erohmensing** [comment]
Thanks for posting the solution!
