### ISSUE TITLE
Rasa Convert - Permission Denied

### ISSUE THREAD

**Issue by DiegoProtec** [RasaHQ/rasa#5010]
**Rasa version**:1.5.3

**Python version**: 3.6.9

**Operating system**: Windows

**Issue**: Permission denied to access out path, on convert files to json.

**Error (including full traceback)**:
```
Traceback (most recent call last):
  File "C:\Program Files\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python36\lib\site-packages\rasa\__main__.py", line 87, in <module>
    main()
  File "C:\Program Files\Python36\lib\site-packages\rasa\__main__.py", line 76, in main
    cmdline_arguments.func(cmdline_arguments)
  File "C:\Program Files\Python36\lib\site-packages\rasa\nlu\convert.py", line 38, in main
    convert_training_data(args.data, args.out, args.format, args.language)
  File "C:\Program Files\Python36\lib\site-packages\rasa\nlu\convert.py", line 34, in convert_training_data
    write_to_file(out_file, output)
  File "C:\Program Files\Python36\lib\site-packages\rasa\nlu\utils\__init__.py", line 55, in write_to_file
    io_utils.write_text_file(str(text), filename)
  File "C:\Program Files\Python36\lib\site-packages\rasa\utils\io.py", line 233, in write_text_file
    with open(file_path, mode, encoding=encoding) as file:
PermissionError: [Errno 13] Permission denied: 'data'
```

**Command or request that led to error**:
```
python -m rasa data convert nlu --data data/intents --out data --format json
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @TyDunn will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by erohmensing** [comment]
@DiegoProtec what are the permissions on your data directory? Have you tried running the command as an administrator?
