### ISSUE TITLE
docker run fail:distutils.errors.DistutilsFileError: could not create './endpoints.yml': Permission denied

### ISSUE THREAD

**Issue by pingyuan2016** [RasaHQ/rasa#5015]
![image](https://user-images.githubusercontent.com/25808622/71428049-2b191e00-26f9-11ea-8464-c53c392b760b.png)

![image](https://user-images.githubusercontent.com/25808622/71427625-9f51c280-26f5-11ea-93fb-cf27ae117ef3.png)

**Comment by pingyuan2016** [comment]
`ubuntu@VM-0-6-ubuntu:~$ docker -v && docker-compose -v
Docker version 19.03.5, build 633a0ea838
docker-compose version 1.22.0, build f46880fe
`
`ubuntu@VM-0-6-ubuntu:/opt/project/rasa_test$ sudo docker run -v $(pwd):/app rasa/rasa init --no-prompt
Welcome to Rasa! 烙

To get started quickly, an initial project will be created.
If you need some help, check out the documentation at https://rasa.com/docs/rasa.

Warning: Output is not to a terminal (fd=1).
Warning: Input is not to a terminal (fd=0).
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/distutils/file_util.py", line 41, in _copy_file_contents
    fdst = open(dst, 'wb')
PermissionError: [Errno 13] Permission denied: './endpoints.yml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/build/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/build/lib/python3.6/site-packages/rasa/__main__.py", line 76, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/build/lib/python3.6/site-packages/rasa/cli/scaffold.py", line 197, in run
    init_project(args, path)
  File "/build/lib/python3.6/site-packages/rasa/cli/scaffold.py", line 113, in init_project
    create_initial_project(path)
  File "/build/lib/python3.6/site-packages/rasa/cli/scaffold.py", line 121, in create_initial_project
    copy_tree(scaffold_path(), path)
  File "/usr/local/lib/python3.6/distutils/dir_util.py", line 163, in copy_tree
    dry_run=dry_run)
  File "/usr/local/lib/python3.6/distutils/file_util.py", line 151, in copy_file
    _copy_file_contents(src, dst)
  File "/usr/local/lib/python3.6/distutils/file_util.py", line 44, in _copy_file_contents
    "could not create '%s': %s" % (dst, e.strerror))
distutils.errors.DistutilsFileError: could not create './endpoints.yml': Permission denied
`

**Comment by sara-tagger** [comment]
Thanks for the question, our Github issue board is for **bugs and feature requests only,** though 😕
Please ask this question in the [forum✨](https://forum.rasa.com/c/rasa)

###### If you were describing a bug, please create a [report](https://github.com/RasaHQ/rasa/issues/new?labels=bug&template=bug_report.md) and fill out the template.
