### ISSUE TITLE
docker run fail:distutils.errors.DistutilsFileError: could not create './endpoints.yml': Permission denied

### ISSUE THREAD

**Issue by pingyuan2016** [RasaHQ/rasa#5017]
![image](https://user-images.githubusercontent.com/25808622/71453422-1c4c6d00-27c6-11ea-9c6f-e4323756760a.png)
![image](https://user-images.githubusercontent.com/25808622/71453429-240c1180-27c6-11ea-9c86-7d76972bf568.png)
this is docker version:
`ubuntu@VM-0-6-ubuntu:~$ docker -v && docker-compose -v Docker version 19.03.5, build 633a0ea838 docker-compose version 1.22.0, build f46880fe`
I rasa init is complete,but  hint of trouble
`ubuntu@VM-0-6-ubuntu:/opt/project/rasa_test$ sudo docker run -v $(pwd):/app rasa/rasa init --no-prompt
Welcome to Rasa! 烙

To get started quickly, an initial project will be created.
If you need some help, check out the documentation at https://rasa.com/docs/rasa.

Warning: Output is not to a terminal (fd=1).
Warning: Input is not to a terminal (fd=0).
Traceback (most recent call last):
File "/usr/local/lib/python3.6/distutils/file_util.py", line 41, in _copy_file_contents
fdst = open(dst, 'wb')
PermissionError: [Errno 13] Permission denied: './endpoints.yml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/build/bin/rasa", line 8, in
sys.exit(main())
File "/build/lib/python3.6/site-packages/rasa/main.py", line 76, in main
cmdline_arguments.func(cmdline_arguments)
File "/build/lib/python3.6/site-packages/rasa/cli/scaffold.py", line 197, in run
init_project(args, path)
File "/build/lib/python3.6/site-packages/rasa/cli/scaffold.py", line 113, in init_project
create_initial_project(path)
File "/build/lib/python3.6/site-packages/rasa/cli/scaffold.py", line 121, in create_initial_project
copy_tree(scaffold_path(), path)
File "/usr/local/lib/python3.6/distutils/dir_util.py", line 163, in copy_tree
dry_run=dry_run)
File "/usr/local/lib/python3.6/distutils/file_util.py", line 151, in copy_file
_copy_file_contents(src, dst)
File "/usr/local/lib/python3.6/distutils/file_util.py", line 44, in _copy_file_contents
"could not create '%s': %s" % (dst, e.strerror))
distutils.errors.DistutilsFileError: could not create './endpoints.yml': Permission denied`

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @wochinge will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by wochinge** [comment]
Hi @pingyuan2016 ,

it seems like your mounted directory has the wrong file permissions. Note that rasa containers not run as `root`. You can either 
- change the owning user to `1001`
- make the files accessible to group `0` (aka `root`)
- use the `docker run --user` flag

Does that help you?

**Comment by jagdish176** [comment]
Give permission to write for that directory(your docker directory where this file is getting created)

**Comment by jagdish176** [comment]
you  can do it by this using : 
"sudo chmod +777 -R dir_path"
