### ISSUE TITLE
Rasa command returns error

### ISSUE THREAD

**Issue by MinuhaFire** [RasaHQ/rasa#5023]
**Rasa version**: *Cannot access 'rasa' command

**Rasa SDK version** (if used & relevant): 1.5.2

**Rasa X version**(if used & relevant):
0.23.5

**Python version**: v3.6.0

**Operating system** (windows, osx, ...): Windows

**Issue**: When I use the command 'rasa', it returns an error:
```
Traceback (most recent call last):
  File "c:\users\lamma\appdata\local\programs\python\python36\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\lamma\appdata\local\programs\python\python36\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\lamma\Desktop\testbot\env\Scripts\rasa.exe\__main__.py", line 4, in <module>
  File "c:\users\lamma\desktop\testbot\env\lib\site-packages\rasa\__init__.py", line 8, in <module>
    from rasa.run import run
  File "c:\users\lamma\desktop\testbot\env\lib\site-packages\rasa\run.py", line 7, in <module>
    from rasa.core.lock_store import LockStore
  File "c:\users\lamma\desktop\testbot\env\lib\site-packages\rasa\core\__init__.py", line 5, in <module>
    from rasa.core.train import train
  File "c:\users\lamma\desktop\testbot\env\lib\site-packages\rasa\core\train.py", line 11, in <module>
    from rasa.core.domain import Domain
  File "c:\users\lamma\desktop\testbot\env\lib\site-packages\rasa\core\domain.py", line 11, in <module>
    import rasa.utils.common as common_utils
  File "c:\users\lamma\desktop\testbot\env\lib\site-packages\rasa\utils\common.py", line 7, in <module>
    import rasa.core.utils
  File "c:\users\lamma\desktop\testbot\env\lib\site-packages\rasa\core\utils.py", line 27, in <module>
    from sanic import Sanic
  File "c:\users\lamma\desktop\testbot\env\lib\site-packages\sanic\__init__.py", line 2, in <module>
    from sanic.app import Sanic
  File "c:\users\lamma\desktop\testbot\env\lib\site-packages\sanic\app.py", line 18, in <module>
    from sanic.asgi import ASGIApp
  File "c:\users\lamma\desktop\testbot\env\lib\site-packages\sanic\asgi.py", line 26, in <module>
    from sanic.websocket import WebSocketConnection
  File "c:\users\lamma\desktop\testbot\env\lib\site-packages\sanic\websocket.py", line 12, in <module>
    from websockets import (  # type: ignore
  File "c:\users\lamma\desktop\testbot\env\lib\site-packages\websockets\__init__.py", line 3, in <module>
    from .auth import *
  File "c:\users\lamma\desktop\testbot\env\lib\site-packages\websockets\auth.py", line 15, in <module>
    from .server import HTTPResponse, WebSocketServerProtocol
  File "c:\users\lamma\desktop\testbot\env\lib\site-packages\websockets\server.py", line 49, in <module>
    from .protocol import WebSocketCommonProtocol
  File "c:\users\lamma\desktop\testbot\env\lib\site-packages\websockets\protocol.py", line 18, in <module>
    from typing import (
ImportError: cannot import name "Deque" 
```

**Command or request that led to error**:
`rasa`

**Comment by sara-tagger** [comment]
Thanks for the issue, @rgstephens will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by tmbo** [comment]
duplicates https://github.com/RasaHQ/rasa/issues/4906
