### ISSUE TITLE
rasa.nlu.featurizers packages missing in rasa-x

### ISSUE THREAD

**Issue by mehtajinesh** [RasaHQ/rasa#5025]
**Rasa version**: 1.5.3

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**:3.7

**Operating system** (windows, osx, ...): Windows

**Issue**:

Goal - I am trying to setup rasa x on my local system. 
Steps followed - 
1. First I installed rasa using $ pip3 install rasa which installed 1.6 version
2. I did the initial bot setup using rasa init
3. I was able to chat with bot. No issues.
4. Next, I wanted to setup rasa X. So I used pip install rasa-x --extra-index-url https://pypi.rasa.com/simple to install rasa X to deploy server on my local system. During this process, it uninstalled 1.6 version and installed 1.5.3 version.
5. Finally, i tried to run rasa shell again to check if i am able chat with the bot. But it doesnt work. 

**Error (including full traceback)**:
```
Traceback (most recent call last):
  File "C:\Users\H242848\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\H242848\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\work\Chatbot\rasa_e\Scripts\rasa.exe\__main__.py", line 9, in <module>
  File "c:\work\chatbot\rasa_e\lib\site-packages\rasa\__main__.py", line 76, in main
    cmdline_arguments.func(cmdline_arguments)
  File "c:\work\chatbot\rasa_e\lib\site-packages\rasa\cli\shell.py", line 101, in shell
    rasa.cli.run.run(args)
  File "c:\work\chatbot\rasa_e\lib\site-packages\rasa\cli\run.py", line 114, in run
    rasa.run(**vars(args))
  File "c:\work\chatbot\rasa_e\lib\site-packages\rasa\run.py", line 56, in run
    **kwargs,
  File "c:\work\chatbot\rasa_e\lib\site-packages\rasa\core\run.py", line 206, in serve_application
    endpoints.lock_store if endpoints else None
  File "c:\work\chatbot\rasa_e\lib\site-packages\sanic\app.py", line 1133, in run
    serve(**server_settings)
  File "c:\work\chatbot\rasa_e\lib\site-packages\sanic\server.py", line 857, in serve
    trigger_events(before_start, loop)
  File "c:\work\chatbot\rasa_e\lib\site-packages\sanic\server.py", line 634, in trigger_events
    loop.run_until_complete(result)
  File "C:\Users\H242848\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 583, in run_until_complete
    return future.result()
  File "c:\work\chatbot\rasa_e\lib\site-packages\rasa\core\run.py", line 250, in load_agent_on_start
    action_endpoint=endpoints.action,
  File "c:\work\chatbot\rasa_e\lib\site-packages\rasa\core\agent.py", line 272, in load_agent
    remote_storage=remote_storage,
  File "c:\work\chatbot\rasa_e\lib\site-packages\rasa\core\agent.py", line 932, in load_local_model
    path_to_model_archive=model_archive,
  File "c:\work\chatbot\rasa_e\lib\site-packages\rasa\core\agent.py", line 387, in load
    interpreter = NaturalLanguageInterpreter.create(nlu_model)
  File "c:\work\chatbot\rasa_e\lib\site-packages\rasa\core\interpreter.py", line 55, in create
    return RasaNLUInterpreter(model_directory=obj)
  File "c:\work\chatbot\rasa_e\lib\site-packages\rasa\core\interpreter.py", line 267, in __init__
    self._load_interpreter()
  File "c:\work\chatbot\rasa_e\lib\site-packages\rasa\core\interpreter.py", line 290, in _load_interpreter
    self.interpreter = Interpreter.load(self.model_directory)
  File "c:\work\chatbot\rasa_e\lib\site-packages\rasa\nlu\model.py", line 305, in load
    return Interpreter.create(model_metadata, component_builder, skip_validation)
  File "c:\work\chatbot\rasa_e\lib\site-packages\rasa\nlu\model.py", line 327, in create
    components.validate_requirements(model_metadata.component_classes)
  File "c:\work\chatbot\rasa_e\lib\site-packages\rasa\nlu\components.py", line 38, in validate_requirements
    component_class = registry.get_component_class(component_name)
  File "c:\work\chatbot\rasa_e\lib\site-packages\rasa\nlu\registry.py", line 180, in get_component_class
    raise ModuleNotFoundError(exception_message)
ModuleNotFoundError: Failed to find module 'rasa.nlu.featurizers.sparse_featurizer.regex_featurizer'.
No module named 'rasa.nlu.featurizers.sparse_featurizer'
```

**Command or request that led to error**:
```
rasa shell
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @tmbo will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by mehtajinesh** [comment]
sure. I am trying to figure out the issue. I think the constants.py file is to be updated.

**Comment by erohmensing** [comment]
@mehtajinesh thanks for pointing this out. 0.23.5 is compatible with rasa 1.6, it isn't reflected in the setup.py, however. I'll add that to the next patch (0.23.6), and in the meantime you should be safe to re-install `rasa==1.6.0`

**Comment by mehtajinesh** [comment]
sure. thanks 👍

**Comment by mehtajinesh** [comment]
@erohmensing please close this up once you deploy `rasax 0.23.5`
