### ISSUE TITLE
cuda_driver error while running command rasa run error on Ubuntu

### ISSUE THREAD

**Issue by abhishekborse** [RasaHQ/rasa#5039]
**Rasa version**: 1.5.3

**Rasa SDK version** (if used & relevant): 1.5.2

**Rasa X version** (if used & relevant):  0.23.5

**Python version**: 3.7.1

**Operating system** (windows, osx, ...): Ubuntu 18.04.1 LTS

**Error (including full traceback)**:

(ml-venv) abhishek@abhishek-laptop:~/Projects/python/rasa/chatbot$ rasa run -p 5008
2020-01-05 17:27:51 INFO     root  - Starting Rasa server on http://localhost:5008
2020-01-05 17:27:54 INFO     absl  - Entry Point [tensor2tensor.envs.tic_tac_toe_env:TicTacToeEnv] registered with id [T2TEnv-TicTacToeEnv-v0]
2020-01-05 17:27:54.706448: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: UNKNOWN ERROR (303)
Exception occurred while handling uri: 'http://localhost:5008/favicon.ico'
Traceback (most recent call last):
  File "/home/abhishek/python-venv/ml-venv/lib/python3.7/site-packages/sanic/app.py", line 918, in handle_request
    handler, args, kwargs, uri = self.router.get(request)
  File "/home/abhishek/python-venv/ml-venv/lib/python3.7/site-packages/sanic/router.py", line 407, in get
    return self._get(request.path, request.method, "")
  File "/home/abhishek/python-venv/ml-venv/lib/python3.7/site-packages/sanic/router.py", line 470, in _get
    raise NotFound("Requested URL {} not found".format(url))
sanic.exceptions.NotFound: Requested URL /favicon.ico not found

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @rgstephens will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by rgstephens** [comment]
Questions should be asked in the [forum](https://forum.rasa.com) and the case will be closed. There's a specific discussion on this issue [here](https://forum.rasa.com/t/tensorflow-driver-unknown-error-303/21661)
