### ISSUE TITLE
"ValueError: Sequence dimensions for sparse and dense features don't coincide" when training with return_sequence: true in Rasa 1.6.0

### ISSUE THREAD

**Issue by nbeuchat** [RasaHQ/rasa#5050]
**Rasa version**: 1.6.0

**Rasa SDK version** (if used & relevant): 1.6.1

**Rasa X version** (if used & relevant): N/A

**Python version**: 3.6

**Operating system** (windows, osx, ...): Ubuntu

**Issue**:
When training the NLU model in Rasa 1.6.0 using the `return_sequence: true` flag on the `SpacyFeaturizer`, I get a `ValueError: Sequence dimensions for sparse and dense features don't coincide in 'yes I am' for attribute 'text'` when training the `EmbeddingIntentClassifier`. 

However, if I do not include `return_sequence: true`, I get many warnings during the `CRFEntityExtractor` training:

```
/home/nicolas/anaconda3/envs/chatbot/lib/python3.6/site-packages/rasa/nlu/extractors/crf_entity_extractor.py:590: UserWarning: Number of features (1) for attribute 'text_dense_features' does not match number of tokens (55). Set 'return_sequence' to true in the corresponding featurizer in order to make use of the features in 'CRFEntityExtractor'.
  f"Number of features ({len(features)}) for attribute "
```

**Error (including full traceback)**:
```
2020-01-07 13:14:46 INFO     rasa.nlu.model  - Starting to train component EmbeddingIntentClassifier
Traceback (most recent call last):
  File "/home/nicolas/anaconda3/envs/chatbot/bin/rasa", line 10, in <module>
    sys.exit(main())
  File "/home/nicolas/anaconda3/envs/chatbot/lib/python3.6/site-packages/rasa/__main__.py", line 76, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/home/nicolas/anaconda3/envs/chatbot/lib/python3.6/site-packages/rasa/cli/train.py", line 138, in train_nlu
    persist_nlu_training_data=args.persist_nlu_data,
  File "/home/nicolas/anaconda3/envs/chatbot/lib/python3.6/site-packages/rasa/train.py", line 410, in train_nlu
    persist_nlu_training_data,
  File "uvloop/loop.pyx", line 1417, in uvloop.loop.Loop.run_until_complete
  File "/home/nicolas/anaconda3/envs/chatbot/lib/python3.6/site-packages/rasa/train.py", line 441, in _train_nlu_async
    persist_nlu_training_data=persist_nlu_training_data,
  File "/home/nicolas/anaconda3/envs/chatbot/lib/python3.6/site-packages/rasa/train.py", line 470, in _train_nlu_with_validated_data
    persist_nlu_training_data=persist_nlu_training_data,
  File "/home/nicolas/anaconda3/envs/chatbot/lib/python3.6/site-packages/rasa/nlu/train.py", line 86, in train
    interpreter = trainer.train(training_data, **kwargs)
  File "/home/nicolas/anaconda3/envs/chatbot/lib/python3.6/site-packages/rasa/nlu/model.py", line 191, in train
    updates = component.train(working_data, self.config, **context)
  File "/home/nicolas/anaconda3/envs/chatbot/lib/python3.6/site-packages/rasa/nlu/classifiers/embedding_intent_classifier.py", line 708, in train
    session_data = self.preprocess_train_data(training_data)
  File "/home/nicolas/anaconda3/envs/chatbot/lib/python3.6/site-packages/rasa/nlu/classifiers/embedding_intent_classifier.py", line 684, in preprocess_train_data
    label_attribute=INTENT_ATTRIBUTE,
  File "/home/nicolas/anaconda3/envs/chatbot/lib/python3.6/site-packages/rasa/nlu/classifiers/embedding_intent_classifier.py", line 411, in _create_session_data
    _sparse, _dense = self._extract_and_add_features(e, TEXT_ATTRIBUTE)
  File "/home/nicolas/anaconda3/envs/chatbot/lib/python3.6/site-packages/rasa/nlu/classifiers/embedding_intent_classifier.py", line 303, in _extract_and_add_features
    f"Sequence dimensions for sparse and dense features "
ValueError: Sequence dimensions for sparse and dense features don't coincide in 'yes I am' for attribute 'text'.
```

**Command or request that led to error**:
```
rasa train nlu
```

**Content of configuration file (config.yml)** (if relevant):
```yml
language: "en"
pipeline:
  - name: "SpacyNLP"
    case_sensitive: true
  - name: "SpacyTokenizer"
  - name: "SpacyEntityExtractor"
    dimensions: ["PERSON", "MONEY", "DATE"]
  - name: "DucklingHTTPExtractor"
    url: ...
    dimensions: ...
  - name: "RegexFeaturizer"
  - name: "SpacyFeaturizer"
    return_sequence: true
  - name: "CRFEntityExtractor"
    features: [
                ["low", "title", "upper", "digit"],
                [
                  "bias",
                  "low",
                  "prefix5",
                  "prefix2",
                  "suffix5",
                  "suffix3",
                  "suffix2",
                  "upper",
                  "title",
                  "digit",
                  "pattern",
                  "pos",
                  "pos2",
                ],
                ["low", "title", "upper", "digit"]
              ]
  ...
  - name: "EmbeddingIntentClassifier"
```

**Content of domain file (domain.yml)** (if relevant): irrelevant

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @ArjaanBuijk will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by tabergma** [comment]
@nbeuchat Can you please also set `return_sequence: True` in the `RegexFeaturizer`? That should fix the problem. If you use `return_sequence: True` on one featurizer you need to use it in all.

**Comment by nbeuchat** [comment]
Great, that works! Thanks @tabergma
