### ISSUE TITLE
Rasa x not run

### ISSUE THREAD

**Issue by ankitsinghmyself** [RasaHQ/rasa#5051]
**I installed rasa x on my anaconda now when I am trying to run `rasa x` for creating a new project it throwing an errror**<br>
 `Traceback (most recent call last):
  File "c:\anaconda3\envs\rasa\lib\site-packages\git\__init__.py", line 83, in <module>
    refresh()
  File "c:\anaconda3\envs\rasa\lib\site-packages\git\__init__.py", line 73, in refresh
    if not Git.refresh(path=path):
  File "c:\anaconda3\envs\rasa\lib\site-packages\git\cmd.py", line 287, in refresh
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\anaconda3\envs\rasa\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\envs\rasa\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\envs\rasa\Scripts\rasa.exe\__main__.py", line 7, in <module>
  File "c:\anaconda3\envs\rasa\lib\site-packages\rasa\__main__.py", line 76, in main
    cmdline_arguments.func(cmdline_arguments)
  File "c:\anaconda3\envs\rasa\lib\site-packages\rasa\cli\x.py", line 324, in rasa_x
    run_locally(args)
  File "c:\anaconda3\envs\rasa\lib\site-packages\rasa\cli\x.py", line 412, in run_locally
    from rasax.community import local  # pytype: disable=import-error
  File "c:\anaconda3\envs\rasa\lib\site-packages\rasax\community\local.py", line 27, in <module>
    import rasax.community.server as rasa_x_server
  File "c:\anaconda3\envs\rasa\lib\site-packages\rasax\community\server.py", line 5, in <module>
    from rasax.community.services.git_service import GitService
  File "c:\anaconda3\envs\rasa\lib\site-packages\rasax\community\services\git_service.py", line 11, in <module>
    from git import Repo, GitCommandError, Reference, PushInfo, RemoteReference
  File "c:\anaconda3\envs\rasa\lib\site-packages\git\__init__.py", line 85, in <module>
    raise ImportError('Failed to initialize: {0}'.format(exc))
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet`

**Comment by ankitsinghmyself** [comment]
I found the solution for that 
- [download git for that and 
add the path in which the git executable is located (in this case maybe C:\Programs\Git\bin) to the Path variable' ]

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @amn41 will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by chiragsingh1711** [comment]
> I found the solution for that
> 
> * [download git for that and
>   add the path in which the git executable is located (in this case maybe C:\Programs\Git\bin) to the Path variable' ]

Bro , How to download that git????
