### ISSUE TITLE
Error running example/knowledgebasebot 

### ISSUE THREAD

**Issue by Gurdershan** [RasaHQ/rasa#5115]
**Rasa version**:23.1.0

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**:3.6

**Operating system** (windows, osx, ...):windows

**Issue**: Unable to riun knowledgebasedbot

```
2020-01-23 12:26:15.197756: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_100.dll'; dlerror: cudart64_100.dll not found
2020-01-23 12:26:15.198264: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
c:\softwares\lib\site-packages\rasa\core\domain.py:154: FutureWarning: No tracker session configuration was found in the loaded domain. Domains without a session config will automatically receive a session expiration time of 60 minutes in Rasa version 2.0 if not configured otherwise.
  FutureWarning,
Training Core model...
2020-01-23 12:26:44 INFO     absl  - Entry Point [tensor2tensor.envs.tic_tac_toe_env:TicTacToeEnv] registered with id [T2TEnv-TicTacToeEnv-v0]
2020-01-23 12:26:45 INFO     rasa.core.policies.ensemble  - MappingPolicy not included in policy ensemble. Default intents 'restart and back will not trigger actions 'action_restart' and 'action_back'.
2020-01-23 12:26:45 WARNING  rasa.core.domain  - You are using an experiential feature: Action 'action_query_knowledge_base'!
c:\softwares\lib\site-packages\rasa\core\domain.py:154: FutureWarning: No tracker session configuration was found in the loaded domain. Domains without a session config will automatically receive a session expiration time of 60 minutes in Rasa version 2.0 if not configured otherwise.
  FutureWarning,
Processed Story Blocks:   0%|          | 0/6 [00:00<?, ?it/s, # trackers=1]c:\softwares\lib\site-packages\rasa\core\domain.py:604: UserWarning: Failed to use action 'utter_goodbye' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while.
  f"Failed to use action '{latest_action}' in history. "
Processed Story Blocks:   0%|          | 0/6 [00:00<?, ?it/s, # trackers=1]c:\softwares\lib\site-packages\rasa\core\domain.py:604: UserWarning: Failed to use action 'utter_greet' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while.
  f"Failed to use action '{latest_action}' in history. "
Processed Story Blocks:   0%|          | 0/6 [00:00<?, ?it/s, # trackers=1]c:\softwares\lib\site-packages\rasa\core\domain.py:604: UserWarning: Failed to use action 'utter_iamabot' in history. Please make sure all actions are listed in the domains action list. If you recently removed an action, don't worry about this warning. It should stop appearing after a while.
  f"Failed to use action '{latest_action}' in history. "
Processed Story Blocks: 100%|##########| 6/6 [00:00<00:00, 2028.19it/s, # trackers=1]
Processed Story Blocks: 100%|##########| 6/6 [00:00<00:00, 546.93it/s, # trackers=6]
Processed Story Blocks: 100%|##########| 6/6 [00:00<00:00, 107.37it/s, # trackers=26]
Processed Story Blocks: 100%|##########| 6/6 [00:00<00:00, 105.54it/s, # trackers=25]
Processed trackers: 100%|##########| 6/6 [00:00<00:00, 2005.56it/s, # actions=18]
Processed actions: 0it [00:00, ?it/s, # examples=1]Traceback (most recent call last):
  File "c:\softwares\lib\site-packages\rasa\core\domain.py", line 446, in index_for_action
    return self.action_names.index(action_name)
ValueError: 'utter_greet' is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\softwares\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\softwares\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Softwares\Scripts\rasa.exe\__main__.py", line 7, in <module>
  File "c:\softwares\lib\site-packages\rasa\__main__.py", line 76, in main
    cmdline_arguments.func(cmdline_arguments)
  File "c:\softwares\lib\site-packages\rasa\cli\train.py", line 76, in train
    kwargs=extract_additional_arguments(args),
  File "c:\softwares\lib\site-packages\rasa\train.py", line 46, in train
    kwargs=kwargs,
  File "c:\softwares\lib\asyncio\base_events.py", line 579, in run_until_complete
    return future.result()
  File "c:\softwares\lib\site-packages\rasa\train.py", line 97, in train_async
    kwargs,
  File "c:\softwares\lib\site-packages\rasa\train.py", line 184, in _train_async_internal
    kwargs=kwargs,
  File "c:\softwares\lib\site-packages\rasa\train.py", line 219, in _do_training
    kwargs=kwargs,
  File "c:\softwares\lib\site-packages\rasa\train.py", line 357, in _train_core_with_validated_data
    kwargs=kwargs,
  File "c:\softwares\lib\site-packages\rasa\core\train.py", line 67, in train
    agent.train(training_data, **kwargs)
  File "c:\softwares\lib\site-packages\rasa\core\agent.py", line 708, in train
    self.policy_ensemble.train(training_trackers, self.domain, **kwargs)
  File "c:\softwares\lib\site-packages\rasa\core\policies\ensemble.py", line 126, in train
    policy.train(training_trackers, domain, **kwargs)
  File "c:\softwares\lib\site-packages\rasa\core\policies\memoization.py", line 163, in train
    self._add_states_to_lookup(trackers_as_states, trackers_as_actions, domain)
  File "c:\softwares\lib\site-packages\rasa\core\policies\memoization.py", line 110, in _add_states_to_lookup
    feature_item = domain.index_for_action(action)
  File "c:\softwares\lib\site-packages\rasa\core\domain.py", line 448, in index_for_action
    self._raise_action_not_found_exception(action_name)
  File "c:\softwares\lib\site-packages\rasa\core\domain.py", line 453, in _raise_action_not_found_exception
    f"Cannot access action '{action_name}', "
NameError: Cannot access action 'utter_greet', as that name is not a registered action for this domain. Available actions are:
         - action_listen
         - action_restart
         - action_session_start
         - action_default_fallback
         - action_deactivate_form
         - action_revert_fallback_events
         - action_default_ask_affirmation
         - action_default_ask_rephrase
         - action_back
         - action_query_knowledge_base
Processed actions: 0it [00:00, ?it/s, # examples=1]
```

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @Ghostvv will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by tabergma** [comment]
@Gurdershan I assume you took the Knowledgebot example from the current master branch? The example on master was recently updated. With the next release it will not be needed anymore to add the templates to actions in your `domain.yml`. However, as the feature is not yet released, the current Rasa version will fail. 
Please update the `actions` sections in your `domain.yml` with
```
actions:
- action_query_knowledge_base
- utter_greet
- utter_goodbye
- utter_ask_rephrase
- utter_iamabot
```
