### ISSUE TITLE
rasa.core.agent  - Could not load model due to not a gzip file.

### ISSUE THREAD

**Issue by juanmariareina** [RasaHQ/rasa#5134]
**Rasa version**: 1.5.1

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**: 3.7

**Operating system** (windows, osx, ...): Ubuntu

**Issue**: Cannot start rasa server due to error shown above.
I'm trying to start rasa server with:  rasa run -m models --enable-api --cors *

When I launch the above  I'm sure that my current path contains a folder named "models". What I have in this folder is just my newly created model: "20200127-125346.tar.gz"

The model was created via "rasa train". Previous models are deleted cause they are not working well (that's why we create a new one)

The file type is:
file 20200127-125346.tar.gz
20200127-125346.tar.gz: gzip compressed data, was "20200127-125346.tar", last modified: Mon Jan 27 12:53:46 2020, max compression, original size modulo 2^32 3246080

**Error (including full traceback)**:
2020-01-27 13:25:54 INFO     engineio.server  - Server initialized for sanic.
2020-01-27 13:25:54 INFO     root  - Starting Rasa server on http://localhost:5005
2020-01-27 13:25:54 ERROR    rasa.core.agent  - Could not load model due to not a gzip file.
[2020-01-27 13:25:54 +0000] [13781] [ERROR] Experienced exception while trying to serve
Traceback (most recent call last):
  File "/usr/lib/python3.7/tarfile.py", line 1645, in gzopen
    t = cls.taropen(name, mode, fileobj, **kwargs)
  File "/usr/lib/python3.7/tarfile.py", line 1621, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/usr/lib/python3.7/tarfile.py", line 1484, in __init__
    self.firstmember = self.next()
  File "/usr/lib/python3.7/tarfile.py", line 2289, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/usr/lib/python3.7/tarfile.py", line 1094, in fromtarfile
    buf = tarfile.fileobj.read(BLOCKSIZE)
  File "/usr/lib/python3.7/gzip.py", line 276, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.7/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.7/gzip.py", line 463, in read
    if not self._read_gzip_header():
  File "/usr/lib/python3.7/gzip.py", line 411, in _read_gzip_header
    raise OSError('Not a gzipped file (%r)' % magic)
OSError: Not a gzipped file (b'di')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sanic/app.py", line 1133, in run
    serve(**server_settings)
  File "/usr/local/lib/python3.7/dist-packages/sanic/server.py", line 857, in serve
    trigger_events(before_start, loop)
  File "/usr/local/lib/python3.7/dist-packages/sanic/server.py", line 634, in trigger_events
    loop.run_until_complete(result)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.7/dist-packages/rasa/core/run.py", line 250, in load_agent_on_start
    action_endpoint=endpoints.action,
  File "/usr/local/lib/python3.7/dist-packages/rasa/core/agent.py", line 272, in load_agent
    remote_storage=remote_storage,
  File "/usr/local/lib/python3.7/dist-packages/rasa/core/agent.py", line 921, in load_local_model
    unpacked_model = unpack_model(model_archive, working_directory)
  File "/usr/local/lib/python3.7/dist-packages/rasa/model.py", line 190, in unpack_model
    with tarfile.open(model_file, mode="r:gz") as tar:
  File "/usr/lib/python3.7/tarfile.py", line 1591, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/usr/lib/python3.7/tarfile.py", line 1649, in gzopen
    raise ReadError("not a gzip file")
tarfile.ReadError: not a gzip file
Traceback (most recent call last):
  File "/usr/lib/python3.7/tarfile.py", line 1645, in gzopen
    t = cls.taropen(name, mode, fileobj, **kwargs)
  File "/usr/lib/python3.7/tarfile.py", line 1621, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/usr/lib/python3.7/tarfile.py", line 1484, in __init__
    self.firstmember = self.next()
  File "/usr/lib/python3.7/tarfile.py", line 2289, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/usr/lib/python3.7/tarfile.py", line 1094, in fromtarfile
    buf = tarfile.fileobj.read(BLOCKSIZE)
  File "/usr/lib/python3.7/gzip.py", line 276, in read
    return self._buffer.read(size)
  File "/usr/lib/python3.7/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/lib/python3.7/gzip.py", line 463, in read
    if not self._read_gzip_header():
  File "/usr/lib/python3.7/gzip.py", line 411, in _read_gzip_header
    raise OSError('Not a gzipped file (%r)' % magic)
OSError: Not a gzipped file (b'di')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/rasa/__main__.py", line 76, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/usr/local/lib/python3.7/dist-packages/rasa/cli/run.py", line 83, in run
    rasa.run(**vars(args))
  File "/usr/local/lib/python3.7/dist-packages/rasa/run.py", line 56, in run
    **kwargs,
  File "/usr/local/lib/python3.7/dist-packages/rasa/core/run.py", line 206, in serve_application
    endpoints.lock_store if endpoints else None
  File "/usr/local/lib/python3.7/dist-packages/sanic/app.py", line 1133, in run
    serve(**server_settings)
  File "/usr/local/lib/python3.7/dist-packages/sanic/server.py", line 857, in serve
    trigger_events(before_start, loop)
  File "/usr/local/lib/python3.7/dist-packages/sanic/server.py", line 634, in trigger_events
    loop.run_until_complete(result)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.7/dist-packages/rasa/core/run.py", line 250, in load_agent_on_start
    action_endpoint=endpoints.action,
  File "/usr/local/lib/python3.7/dist-packages/rasa/core/agent.py", line 272, in load_agent
    remote_storage=remote_storage,
  File "/usr/local/lib/python3.7/dist-packages/rasa/core/agent.py", line 921, in load_local_model
    unpacked_model = unpack_model(model_archive, working_directory)
  File "/usr/local/lib/python3.7/dist-packages/rasa/model.py", line 190, in unpack_model
    with tarfile.open(model_file, mode="r:gz") as tar:
  File "/usr/lib/python3.7/tarfile.py", line 1591, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/usr/lib/python3.7/tarfile.py", line 1649, in gzopen
    raise ReadError("not a gzip file")
tarfile.ReadError: not a gzip file
sys:1: RuntimeWarning: coroutine 'Loop.create_server' was never awaited

**Command or request that led to error**:
I've tried with rasa run -m models --enable-api --cors *

I had also tried the above including certificate an key path to get rasa accesible through https. Same error...

**Content of configuration file (config.yml)** (if relevant):
```yml
language: es
pipeline: supervised_embeddings
policies:
- name: MemoizationPolicy
- name: KerasPolicy
- name: MappingPolicy
:```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by juanmariareina** [comment]
Well, I've just seen what is happening. 

I have to use "*" instead of *... But, anyway the error shown is weird as it was addressing another issue. What enlighted me was the idea of the "*" character could be parsed and interpreted as if it is the wildcard character used to refer to "any file"

Perhaps, some fix could arise from this error. At least some warning about configuration parameter error...

**Comment by sara-tagger** [comment]
Thanks for the issue, @amn41 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by Vaidehi16-05** [comment]
I am also facing the same issue..
**Command that led to the error**: python -m rasa run --m ./models --endpoints endpoints.yml --port 5005 -vv --enable-api
**ERROR** :

2020-08-10 16:08:10 DEBUG    rasa.cli.utils  - Parameter 'credentials' not set. Using default location 'credentials.yml' instead.
2020-08-10 16:08:12 DEBUG    rasa.core.utils  - Available web server routes:
/conversations/<conversation_id>/messages          POST                           add_message
/conversations/<conversation_id>/tracker/events    POST                           append_events
/webhooks/rasa                                     GET                            custom_webhook_RasaChatInput.health
/webhooks/rasa/webhook                             POST                           custom_webhook_RasaChatInput.receive
/webhooks/rest                                     GET                            custom_webhook_RestInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_RestInput.receive
/model/test/intents                                POST                           evaluate_intents
/model/test/stories                                POST                           evaluate_stories
/conversations/<conversation_id>/execute           POST                           execute_action
/domain                                            GET                            get_domain
/                                                  GET                            hello
/model                                             PUT                            load_model
/model/parse                                       POST                           parse
/conversations/<conversation_id>/predict           POST                           predict
/conversations/<conversation_id>/tracker/events    PUT                            replace_events
/conversations/<conversation_id>/story             GET                            retrieve_story
/conversations/<conversation_id>/tracker           GET                            retrieve_tracker
/status                                            GET                            status
/model/predict                                     POST                           tracker_predict
/model/train                                       POST                           train
/conversations/<conversation_id>/trigger_intent    POST                           trigger_intent
/model                                             DELETE                         unload_model
/version                                           GET                            version
2020-08-10 16:08:12 INFO     root  - Starting Rasa server on http://localhost:5005
2020-08-10 16:08:12 DEBUG    rasa.core.utils  - Using the default number of Sanic workers (1).
2020-08-10 16:08:12 INFO     root  - Enabling coroutine debugging. Loop id 1470183925960.
2020-08-10 16:08:13 DEBUG    rasa.model  - Extracted model to 'C:\WINDOWS\TEMP\tmp96xo2m29'.
2020-08-10 16:08:14 DEBUG    rasa.utils.tensorflow.models  - Loading the model ...
2020-08-10 16:08:15.007532: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (303)
2020-08-10 16:08:16 DEBUG    rasa.utils.tensorflow.models  - Finished loading the model.
2020-08-10 16:08:16 DEBUG    rasa.utils.tensorflow.models  - Building tensorflow prediction graph...
2020-08-10 16:08:23 DEBUG    rasa.utils.tensorflow.models  - Finished building tensorflow prediction graph.
2020-08-10 16:08:23 DEBUG    rasa.nlu.classifiers.diet_classifier  - Failed to load model for 'ResponseSelector'. Maybe you did not provide enough training data and no model was trained or the path 'C:\WINDOWS\TEMP\tmp96xo2m29\nlu' doesn't exist?
2020-08-10 16:08:23 DEBUG    rasa.core.tracker_store  - Connected to InMemoryTrackerStore.
2020-08-10 16:08:23 DEBUG    rasa.core.lock_store  - Connected to lock store 'InMemoryLockStore'.
2020-08-10 16:08:23 DEBUG    rasa.core.nlg.generator  - Instantiated NLG to 'TemplatedNaturalLanguageGenerator'.
2020-08-10 16:08:23 DEBUG    rasa.core.agent  - Requesting model from server http://my-server.com/models/default_core@latest...
2020-08-10 16:08:25 ERROR    **rasa.core.agent  - Could not load model due to File is not a zip file.**
[2020-08-10 16:08:25 +0530] [620] [ERROR] Experienced exception while trying to serve
Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\lib\site-packages\rasa\utils\io.py", line 217, in unarchive
    tar = tarfile.open(fileobj=IOReader(byte_array))
  File "C:\Users\HP\anaconda3\lib\tarfile.py", line 1578, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully

Kindly help me

**Comment by shreyal18ss** [comment]
I am also facing the same issue...

**Comment by alexlana** [comment]
I had this error because the GZIP file saved after traning was corrupted. The cause was Dropbox. Paused it and the GZIP works, always. Maybe Google Drive and other apps like it cause the same result.
