### ISSUE TITLE
"Tutorial Tensorflow Pipeline" contains bugs - how to get it working

### ISSUE THREAD

**Issue by giladpn** [RasaHQ/rasa#5161]
**Rasa version**: 1.6.1
**Python version**: 3.7.6
**Operating system** (windows, osx, ...): Windows 10 with Powershell 5.x
**Issue**: "Tutorial Tensorflow Pipeline" contains bugs - how to get it working

Hi there

I am learning to use rasa. I read the blog post on how to handle multiple intents
https://blog.rasa.com/how-to-handle-multiple-intents-per-input-using-rasa-nlu-tensorflow-pipeline/

and - as guided - downloaded your tutorial with
```
git clone https://github.com/RasaHQ/tutorial-tf-pipeline
```

I then went into the tutorial directory and ran
```
rasa train
```

This did some training but then crashed with a message
```
2020-01-30 16:50:09 INFO     rasa.nlu.training_data.training_data  - Training data stats: 
        - intent examples: 76 (9 distinct intents)
        - Found intents: 'goodbye', 'ask_transport', 'thanks+goodbye', 'thanks', 'greet', 'meetup', 'deny', 'affirm+ask_transport', 'affirm'
        - Number of response examples: 0 (0 distinct response)
        - entity examples: 0 (0 distinct entities)
        - found entities:

Traceback (most recent call last):
  File "C:\Users\Gilad\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Gilad\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\py-workspace\.venv\Scripts\rasa.exe\__main__.py", line 7, in <module>
  File "c:\py-workspace\.venv\lib\site-packages\rasa\__main__.py", line 76, in main
    cmdline_arguments.func(cmdline_arguments)
  File "c:\py-workspace\.venv\lib\site-packages\rasa\cli\train.py", line 76, in train
    kwargs=extract_additional_arguments(args),
  File "c:\py-workspace\.venv\lib\site-packages\rasa\train.py", line 46, in train
    kwargs=kwargs,
  File "C:\Users\Gilad\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 583, in run_until_complete
    return future.result()
  File "c:\py-workspace\.venv\lib\site-packages\rasa\train.py", line 97, in train_async
    kwargs,
  File "c:\py-workspace\.venv\lib\site-packages\rasa\train.py", line 184, in _train_async_internal
    kwargs=kwargs,
  File "c:\py-workspace\.venv\lib\site-packages\rasa\train.py", line 241, in _do_training
    persist_nlu_training_data=persist_nlu_training_data,
  File "c:\py-workspace\.venv\lib\site-packages\rasa\train.py", line 470, in _train_nlu_with_validated_data
    persist_nlu_training_data=persist_nlu_training_data,
  File "c:\py-workspace\.venv\lib\site-packages\rasa\nlu\train.py", line 86, in train
    interpreter = trainer.train(training_data, **kwargs)
  File "c:\py-workspace\.venv\lib\site-packages\rasa\nlu\model.py", line 180, in train
    components.validate_arguments(self.pipeline, context)
  File "c:\py-workspace\.venv\lib\site-packages\rasa\nlu\components.py", line 81, in validate_arguments
    "".format(component.name, r)
Exception: Failed to validate at component 'CountVectorsFeaturizer'. Missing property: 'tokens'
```
You'll notice the above describes some successful training data stats but then fails saying "Failed to validate at component 'CountVectorsFeaturizer'. Missing property: 'tokens'".

I assume that I need to correct the **downloaded config.yml** which is
```yml
language: en
pipeline:
- name: CountVectorsFeaturizer
- intent_split_symbol: +
  intent_tokenization_flag: true
  name: EmbeddingIntentClassifier
policies:
- batch_size: 50
  epochs: 200
  max_training_samples: 300
  name: KerasPolicy
- fallback_action_name: action_default_fallback
  name: FallbackPolicy
- max_history: 5
  name: MemoizationPolicy
- name: FormPolicy
- name: MappingPolicy
```

**Content of domain file (domain.yml)** (just in case, if you need it):
```yml
intents:
  - greet
  - goodbye
  - affirm
  - thanks
  - thanks+goodbye
  - meetup
  - affirm+ask_transport
  - ask_transport
  - deny


templates:
  utter_greet:
    - text: "Hey, how can I help you?"
  utter_goodbye:
    - text: "Talk to you later!"
    - text: "Goodbye :("
    - text: "Bye!"
    - text: "Have a great day!"
  utter_confirm:
    - text: "Done - I have just booked you a spot at the Bots Berlin meetup."
    - text: "Great, just made an RSVP for you."
  utter_meetup:
    - text: "Rasa Bots Berlin meetup is definitely worth checking out! They are having an event today at Behrenstraße 42. Would you like to join?"
  utter_affirm_suggest_transport:
    - text: "Great, I have just booked a spot for you. The venue is close to the Berlin Friedrichstraße station, you can get there by catching U-Bahn U6."
  utter_suggest_transport:
    - text: "The venue is close to the Berlin Friedrichstraße station, so the best option is to catch a U-Bahn U6."
  utter_thanks:
    - text: "You are very welcome."
    - text: "Glad I could help!"
  utter_deny:
    - text: "That's a shame. Let me know if you change your mind."


actions:
  - utter_greet
  - utter_goodbye
  - utter_confirm
  - utter_meetup
  - utter_affirm_suggest_transport
  - utter_suggest_transport
  - utter_thanks
  - utter_deny
```
All of the above is your suggested configuration, I have not changed it. Please advise on how to solve. Thanks.

**Comment by sara-tagger** [comment]
Thanks for the issue, @tabergma will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by tabergma** [comment]
@giladpn Thanks for pointing this out! The pipeline in the `config.yml` is missing a tokenizer. Can you  change the config file to
```
language: en
pipeline:
- name: WhitespaceTokenizer
- name: CountVectorsFeaturizer
- intent_split_symbol: +
  intent_tokenization_flag: true
  name: EmbeddingIntentClassifier
policies:
- batch_size: 50
  epochs: 200
  max_training_samples: 300
  name: KerasPolicy
- fallback_action_name: action_default_fallback
  name: FallbackPolicy
- max_history: 5
  name: MemoizationPolicy
- name: FormPolicy
- name: MappingPolicy
```
and try again?

**Comment by giladpn** [comment]
Yup, adding the `WhitespaceTokenizer` was the answer. Thanks.
