### ISSUE TITLE
Rasa shell --debug RuntimeError 

### ISSUE THREAD

**Issue by mrcsilverfox** [RasaHQ/rasa#5169]
**Rasa version**: 1.7.0

**Python version**: 3.7.3

**Operating system** (windows, osx, ...): MacOS Catalina 10.15.3

**Issue**:
After updating to Rasa 1.7.0 whatever I run the command `rasa shell --debug` the console return this output

**Error (including full traceback)**:
```
2020-02-01 14:15:48 DEBUG    rasa.model  - Extracted model to '/var/folders/vr/r9cxzr112jz28wybywj5kx_r0000gn/T/tmptzfyn3s9'.
2020-02-01 14:15:48 DEBUG    rasa.cli.utils  - Parameter 'endpoints' not set. Using default location 'endpoints.yml' instead.
2020-02-01 14:15:48 DEBUG    rasa.cli.utils  - Parameter 'credentials' not set. Using default location 'credentials.yml' instead.
2020-02-01 14:15:49 DEBUG    rasa.model  - Extracted model to '/var/folders/vr/r9cxzr112jz28wybywj5kx_r0000gn/T/tmpyj3erf_8'.
2020-02-01 14:15:50 INFO     root  - Connecting to channel 'cmdline' which was specified by the '--connector' argument. Any other channels will be ignored. To connect to all given channels, omit the '--connector' argument.
2020-02-01 14:15:50 DEBUG    sanic.root  - CORS: Configuring CORS with resources: {'/*': {'origins': [''], 'methods': 'DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT', 'allow_headers': ['.*'], 'expose_headers': None, 'supports_credentials': True, 'max_age': None, 'send_wildcard': False, 'automatic_options': True, 'vary_header': True, 'resources': {'/*': {'origins': ''}}, 'intercept_exceptions': True, 'always_send': True}}
2020-02-01 14:15:50 DEBUG    rasa.core.utils  - Available web server routes: 
/webhooks/rest                                     GET                            custom_webhook_CmdlineInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_CmdlineInput.receive
/                                                  GET                            hello
2020-02-01 14:15:50 INFO     root  - Starting Rasa server on http://localhost:5005
2020-02-01 14:15:50 DEBUG    rasa.core.utils  - Using the default number of Sanic workers (1).
2020-02-01 14:15:50 INFO     root  - Enabling coroutine debugging. Loop id 5184118808.
--- Logging error ---
--- Logging error ---
Exception ignored in: <built-in method call_exception_handler of Loop object at 0x134ff6018>
Traceback (most recent call last):
  File "uvloop/loop.pyx", line 2359, in uvloop.loop.Loop.call_exception_handler
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1412, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1519, in _log
    self.handle(record)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1529, in handle
    self.callHandlers(record)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1591, in callHandlers
    hdlr.handle(record)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 905, in handle
    self.emit(record)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 1040, in emit
    self.handleError(record)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/logging/__init__.py", line 958, in handleError
    traceback.print_exception(t, v, tb, None, sys.stderr)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/traceback.py", line 104, in print_exception
    type(value), value, tb, limit=limit).format(chain=chain):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/traceback.py", line 508, in __init__
    capture_locals=capture_locals)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/traceback.py", line 363, in extract
    f.line
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/traceback.py", line 285, in line
    self._line = linecache.getline(self.filename, self.lineno).strip()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/linecache.py", line 16, in getline
    lines = getlines(filename, module_globals)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/linecache.py", line 48, in getlines
    for mod in sys.modules.values():
RuntimeError: dictionary changed size during iteration
2020-02-01 14:15:52 DEBUG    rasa.model  - Extracted model to '/var/folders/vr/r9cxzr112jz28wybywj5kx_r0000gn/T/tmpgwcc3vxo'.
2020-02-01 14:15:56 INFO     absl  - Entry Point [tensor2tensor.envs.tic_tac_toe_env:TicTacToeEnv] registered with id [T2TEnv-TicTacToeEnv-v0]
2020-02-01 14:15:57 DEBUG    rasa.core.tracker_store  - Connected to InMemoryTrackerStore.
2020-02-01 14:15:57 DEBUG    rasa.core.lock_store  - Connected to lock store 'InMemoryLockStore'.
2020-02-01 14:15:58 DEBUG    rasa.model  - Extracted model to '/var/folders/vr/r9cxzr112jz28wybywj5kx_r0000gn/T/tmpsl28r2sv'.
2020-02-01 14:15:58 DEBUG    pykwalify.compat  - Using yaml library: /Users/marco/programmazione/cxp/cxp-rasa-chatbot/venv/lib/python3.7/site-packages/ruamel/yaml/__init__.py
2020-02-01 14:16:00 DEBUG    rasa.core.nlg.generator  - Instantiated NLG to 'TemplatedNaturalLanguageGenerator'.
Unable to start server
Traceback (most recent call last):
  File "/Users/marco/programmazione/cxp/cxp-rasa-chatbot/venv/lib/python3.7/site-packages/sanic/server.py", line 860, in serve
    http_server = loop.run_until_complete(server_coroutine)
  File "uvloop/loop.pyx", line 1433, in uvloop.loop.Loop.run_until_complete
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/asyncio/tasks.py", line 581, in ensure_future
    task = loop.create_task(coro_or_future)
  File "uvloop/loop.pyx", line 1396, in uvloop.loop.Loop.create_task
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/traceback.py", line 211, in extract_stack
    stack = StackSummary.extract(walk_stack(f), limit=limit)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/traceback.py", line 363, in extract
    f.line
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/traceback.py", line 285, in line
    self._line = linecache.getline(self.filename, self.lineno).strip()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/linecache.py", line 16, in getline
    lines = getlines(filename, module_globals)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/linecache.py", line 48, in getlines
    for mod in sys.modules.values():
RuntimeError: dictionary changed size during iteration
/Users/marco/programmazione/cxp/cxp-rasa-chatbot/venv/lib/python3.7/site-packages/sanic/app.py:1133: RuntimeWarning: coroutine 'Loop.create_server' was never awaited
  serve(**server_settings)
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @TyDunn will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by TyDunn** [comment]
Hi @mrcsilverfox! I tried to reproduce this with a clean install on my own machine and did not run into this issue. Does it also happen if you run `rasa init --no-prompt` and then `rasa shell debug`.

There was [this issue](https://github.com/RasaHQ/rasa/issues/5111) reported last week that also had to do with `uvloop`, but it was fixed in `Rasa 1.6.2`

**Comment by mrcsilverfox** [comment]
Hi @TyDunn! I have some issue to install rasa from scratch. I executed this step 
```
mkdir rasa-chatbot
python3 -m vena --system-site-packages ./venv
source venv/bin/activate
python -m pip install rasa
```
Whenever I run `rasa --version` the console returns this error: 
```
Traceback (most recent call last):
  File "/Users/marco/programmazione/cxp/cxp-rasa-chatbot/venv/bin/rasa", line 5, in <module>
    from rasa.__main__ import main
ModuleNotFoundError: No module named 'rasa'
```

In relation to the initial problem, after updating rasa from version 1.4.3 to 1.7.0 I have this requirements: 
```
absl-py==0.9.0
aiofiles==0.4.0
aiohttp==3.6.2
APScheduler==3.6.3
astor==0.8.1
async-generator==1.10
async-timeout==3.0.1
attrs==19.3.0
boto3==1.11.5
botocore==1.14.5
bz2file==0.98
cachetools==4.0.0
certifi==2019.11.28
cffi==1.13.2
chardet==3.0.4
Click==7.0
cloudpickle==1.2.2
colorclass==2.2.0
coloredlogs==10.0
colorhash==1.0.2
ConfigArgParse==1.0
cryptography==2.8
cycler==0.10.0
decorator==4.4.1
dill==0.3.1.1
dnspython==1.16.0
docopt==0.6.2
docutils==0.15.2
dopamine-rl==3.0.1
fbmessenger==6.0.0
Flask==1.1.1
future==0.18.2
gast==0.2.2
gevent==1.4.0
gin-config==0.3.0
google-api-python-client==1.7.11
google-auth==1.10.1
google-auth-httplib2==0.0.3
google-pasta==0.1.8
googleapis-common-protos==1.51.0
greenlet==0.4.15
grpcio==1.26.0
gunicorn==20.0.4
gym==0.15.4
h11==0.8.1
h2==3.1.1
h5py==2.10.0
hpack==3.0.0
httpcore==0.3.0
httplib2==0.16.0
httptools==0.0.13
humanfriendly==4.18
hyperframe==5.2.0
idna==2.8
importlib-metadata==1.4.0
itsdangerous==1.1.0
Jinja2==2.10.3
jmespath==0.9.4
jsonpickle==1.2
jsonschema==3.2.0
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
kfac==0.2.0
kiwisolver==1.1.0
Markdown==3.1.1
MarkupSafe==1.1.1
matplotlib==3.1.2
mattermostwrapper==2.1
mesh-tensorflow==0.1.9
more-itertools==8.1.0
mpmath==1.1.0
multidict==4.6.1
networkx==2.4
nltk==3.4.5
numpy==1.18.1
oauth2client==4.1.3
opencv-python==4.1.2.30
opt-einsum==3.1.0
packaging==19.2
pika==1.0.1
Pillow==7.0.0
promise==2.3
prompt-toolkit==2.0.10
protobuf==3.11.2
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.19
pydot==1.4.1
pyglet==1.3.2
PyJWT==1.7.1
pykwalify==1.7.0
pymongo==3.10.1
pyparsing==2.4.6
pypng==0.0.20
pyrsistent==0.15.7
python-crfsuite==0.9.6
python-dateutil==2.8.1
python-dotenv==0.10.3
python-engineio==3.11.2
python-socketio==4.4.0
python-telegram-bot==11.1.0
pytz==2019.3
PyYAML==5.3
questionary==1.4.0
rasa==1.7.0
rasa-sdk==1.7.0
redis==3.3.11
requests==2.22.0
requests-async==0.5.0
requests-toolbelt==0.9.1
rfc3986==1.3.2
rocketchat-API==0.6.36
rsa==4.0
ruamel.yaml==0.15.100
s3transfer==0.3.1
sanic==19.9.0
Sanic-Cors==0.9.9.post1
sanic-jwt==1.4.0
Sanic-Plugins-Framework==0.8.2
scikit-learn==0.20.4
scipy==1.4.1
six==1.14.0
sklearn-crfsuite==0.3.6
slackclient==1.3.2
SQLAlchemy==1.3.12
sympy==1.5.1
tabulate==0.8.6
tensor2tensor==1.14.1
tensorboard==1.15.0
tensorflow==1.15.0
tensorflow-cpu==1.15.0
tensorflow-cpu-estimator==1.15.1
tensorflow-datasets==1.3.2
tensorflow-estimator==1.15.1
tensorflow-gan==2.0.0
tensorflow-hub==0.7.0
tensorflow-metadata==0.21.0
tensorflow-probability==0.7.0
termcolor==1.1.0
terminaltables==3.1.0
tqdm==4.41.1
twilio==6.35.2
tzlocal==2.0.0
ujson==1.35
uritemplate==3.0.1
urllib3==1.25.7
uvloop==0.14.0
wcwidth==0.1.8
webexteamssdk==1.2
websocket-client==0.54.0
websockets==8.1
Werkzeug==0.16.0
wrapt==1.11.2
yarl==1.4.2
zipp==1.0.0
```

**Comment by vaibhavgupta0786** [comment]
I have been facing the same issue when I run the command for rasa-demo bot Sarah

**Comment by TyDunn** [comment]
Hi @vaibhavgupta0786. Can you please create a new issue filling out the information like above?

**Comment by basvankuijck** [comment]
I got the same issue.
Upgrading python to 3.7.7 (at this time) fixed it for me
