### ISSUE TITLE
AttributeError: 'DIET' object has no attribute '_set_optimizer'

### ISSUE THREAD

**Issue by chiragsanghvi10** [RasaHQ/rasa#5360]
Hi, while running rasa NLU for intent classification, I am getting the following error.

# code: https://github.com/RasaHQ/rasa/blob/791a899809735991ada2bd76c0861fcf393c183e/rasa/nlu/classifiers/diet_classifier.py#L964

# Error:
`Traceback (most recent call last):
  File "/home/chirag/rasavenv/lib/python3.6/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/chirag/rasavenv/lib/python3.6/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/chirag/rasavenv/lib/python3.6/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/chirag/rasavenv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/chirag/rasavenv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/chirag/rasavenv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/chirag/rasavenv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/chirag/rasavenv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/chirag/rasavenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/chirag/rasavenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/chirag/Desktop/byjus_test_intro/test_byjus.py", line 111, in main_byjus
    rasa_output_file = rasa_model_output(df2, rasa_trained_model_directory)
  File "/home/chirag/Desktop/byjus_test_intro/test_byjus.py", line 81, in rasa_model_output
    interpreter = Interpreter.load(rasa_trained_model_directory)
  File "/home/chirag/rasavenv/lib/python3.6/site-packages/rasa/nlu/model.py", line 301, in load
    return Interpreter.create(model_metadata, component_builder, skip_validation)
  File "/home/chirag/rasavenv/lib/python3.6/site-packages/rasa/nlu/model.py", line 328, in create
    component_meta, model_metadata.model_dir, model_metadata, **context
  File "/home/chirag/rasavenv/lib/python3.6/site-packages/rasa/nlu/components.py", line 643, in load_component
    component_meta, model_dir, model_metadata, cached_component, **context
  File "/home/chirag/rasavenv/lib/python3.6/site-packages/rasa/nlu/registry.py", line 231, in load_component_by_meta
    component_meta, model_dir, metadata, cached_component, **kwargs
  File "/home/chirag/rasavenv/lib/python3.6/site-packages/rasa/nlu/classifiers/diet_classifier.py", line 845, in load
    index_tag_id_mapping, label_data, meta, data_example, model_dir
  File "/home/chirag/rasavenv/lib/python3.6/site-packages/rasa/nlu/classifiers/diet_classifier.py", line 908, in _load_model
    config=meta,
  File "/home/chirag/rasavenv/lib/python3.6/site-packages/rasa/utils/tensorflow/models.py", line 161, in load
    model = cls(*args, **kwargs)
  File "/home/chirag/rasavenv/lib/python3.6/site-packages/rasa/nlu/classifiers/diet_classifier.py", line 964, in __init__
    self._set_optimizer(tf.keras.optimizers.Adam(config[LEARNING_RATE]))
AttributeError: 'DIET' object has no attribute '_set_optimizer'
`

Any updates on this?

Best,
Chirag Sanghvi

**Comment by Ghostvv** [comment]
what version of tensorflow are you using?

**Comment by chiragsanghvi10** [comment]
@Ghostvv 

`tf.__version__`
'2.1.0'

**Comment by Ghostvv** [comment]
that's strange, it works for me

**Comment by chiragsanghvi10** [comment]
Hi @Ghostvv,
It works now, I reinstalled tensorflow and I'm able to run this.

**Comment by vulauet** [comment]
I'm having this same issue. Rasa runs into this problem when I try to build tensorflow from source following this guide https://www.tensorflow.org/install/source#docker_linux_builds 
I've digged through the diet_classifier.py and indeed can't find the definition for _set_optimizer() method. I'm using rasa 1.9.4 and tensorflow 2.1.0. I'd really appreciate any help.

**Comment by vulauet** [comment]
I've managed to run rasa by commenting out the line `self._set_optimizer(tf.keras.optimizers.Adam(config[LEARNING_RATE]))` and replace it with `self.optimizer = tf.keras.optimizers.Adam(config[LEARNING_RATE])` in diet_classifier.py (and in ted_policy.py). Does rasa depend on additional libraries to auto generate setters?

**Comment by Ghostvv** [comment]
`_set_optimizer()` is present in tensorflow 2.1, maybe they removed it in latest master
