### ISSUE TITLE
ascii error 

### ISSUE THREAD

**Issue by oldmonkABA** [RasaHQ/rasa#5379]
**Rasa version**: 1.8.0

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**: 3.6.8

**Operating system** (windows, osx, ...): ubuntu

**Issue**:

I created a virtual environment and then installed rasa using

1. pip install rasa
2. pip install rasa[transformers]

After that when i did 

rasa init --no-prompt

i get the following error:

**Error (including full traceback)**:
```
Traceback (most recent call last):
  File "/home/rasa_1_8_0/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/home/rasa_1_8_0/lib/python3.6/site-packages/rasa/__main__.py", line 91, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/home/rasa_1_8_0/lib/python3.6/site-packages/rasa/cli/scaffold.py", line 167, in run
    print_success("Welcome to Rasa! \U0001f916\n")
  File "/home/rasa_1_8_0/lib/python3.6/site-packages/rasa/cli/utils.py", line 222, in print_success
    print_color(*args, color=bcolors.OKGREEN)
  File "/home/rasa_1_8_0/lib/python3.6/site-packages/rasa/cli/utils.py", line 218, in print_color
    print(wrap_with_color(*args, color=color))
UnicodeEncodeError: 'ascii' codec can't encode character '\U0001f916' in position 22: ordinal not in range(128)
```

**Command or request that led to error**:
```
rasa init --no-prompt
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by oldmonkABA** [comment]
Gets fixed if you do

```
export PYTHONIOENCODING='utf8'
```
