### ISSUE TITLE
ddl error during the command : rasa init

### ISSUE THREAD

**Issue by jnanavik99** [RasaHQ/rasa#5407]
**Rasa version**:1.8.1

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**:3.6

**Operating system** (windows, osx, ...):Microsoft Windows [Version 10.0.18362.657]

**Issue**:rasa init command not working

**Error (including full traceback)**:(rasabot) C:\Users\Janu\Documents>rasa init
Traceback (most recent call last):
  File "c:\users\janu\miniconda3\envs\rasabot\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "c:\users\janu\miniconda3\envs\rasabot\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "c:\users\janu\miniconda3\envs\rasabot\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "c:\users\janu\miniconda3\envs\rasabot\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "c:\users\janu\miniconda3\envs\rasabot\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\janu\miniconda3\envs\rasabot\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\janu\miniconda3\envs\rasabot\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Janu\Miniconda3\envs\rasabot\Scripts\rasa.exe\__main__.py", line 7, in <module>
  File "c:\users\janu\miniconda3\envs\rasabot\lib\site-packages\rasa\__main__.py", line 82, in main
    set_log_level(log_level)
  File "c:\users\janu\miniconda3\envs\rasabot\lib\site-packages\rasa\utils\common.py", line 71, in set_log_level
    update_tensorflow_log_level()
  File "c:\users\janu\miniconda3\envs\rasabot\lib\site-packages\rasa\utils\common.py", line 107, in update_tensorflow_log_level
    import tensorflow as tf
  File "c:\users\janu\miniconda3\envs\rasabot\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "c:\users\janu\miniconda3\envs\rasabot\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "c:\users\janu\miniconda3\envs\rasabot\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "c:\users\janu\miniconda3\envs\rasabot\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "c:\users\janu\miniconda3\envs\rasabot\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "c:\users\janu\miniconda3\envs\rasabot\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "c:\users\janu\miniconda3\envs\rasabot\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "c:\users\janu\miniconda3\envs\rasabot\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "c:\users\janu\miniconda3\envs\rasabot\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "c:\users\janu\miniconda3\envs\rasabot\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "c:\users\janu\miniconda3\envs\rasabot\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "c:\users\janu\miniconda3\envs\rasabot\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

```

**Command or request that led to error**:rasa init
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @wochinge will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by akelad** [comment]
Hey @jnanavik99 have you tried the suggestion here? https://github.com/tensorflow/tensorflow/issues/35749#issuecomment-573313402

You may need to update your visual c++ tools

**Comment by jnanavik99** [comment]
@akelad I have tried downgrading tensorflow also I tried visual studio c++. None of them worked

**Comment by akelad** [comment]
hm, could you raise an issue with tensorflow then? I'm not sure there's much we can do about that

**Comment by jnanavik99** [comment]
Respected RasaHQ/rasa

As I tried my best to resolve the issue and failed to do so I've decided
not to work on it further. Thank you for the reply
