### ISSUE TITLE
nlu test with cross validation throwing KeyError: 'start'

### ISSUE THREAD

**Issue by RubenAMtz** [RasaHQ/rasa#5427]
**Rasa version**:
1.8.1
**Rasa SDK version** (if used & relevant):
1.8.1
**Rasa X version** (if used & relevant):

**Python version**:
3.6.7
**Operating system** (windows, osx, ...):
Windows 10
**Issue**:
When calling: 
docker-compose run rasa test nlu --cross-validation --verbose -f 2

**Error (including full traceback)**:
```
Traceback (most recent call last):
  File "/opt/venv/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/opt/venv/lib/python3.6/site-packages/rasa/__main__.py", line 91, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/opt/venv/lib/python3.6/site-packages/rasa/cli/test.py", line 143, in test_nlu
    perform_nlu_cross_validation(config, nlu_data, output, vars(args))
  File "/opt/venv/lib/python3.6/site-packages/rasa/test.py", line 243, in perform_nlu_cross_validation
    data, folds, nlu_config, output, **kwargs
  File "/opt/venv/lib/python3.6/site-packages/rasa/nlu/test.py", line 1292, in cross_validate
    train,
  File "/opt/venv/lib/python3.6/site-packages/rasa/nlu/test.py", line 1197, in combine_result
    ) = compute_metrics(interpreter, data)
  File "/opt/venv/lib/python3.6/site-packages/rasa/nlu/test.py", line 1395, in compute_metrics
    entity_metrics = _compute_entity_metrics(entity_results, interpreter)
  File "/opt/venv/lib/python3.6/site-packages/rasa/nlu/test.py", line 1534, in _compute_entity_metrics
    aligned_predictions = align_all_entity_predictions(entity_results, extractors)
  File "/opt/venv/lib/python3.6/site-packages/rasa/nlu/test.py", line 910, in align_all_entity_predictions
    aligned_predictions.append(align_entity_predictions(result, extractors))
  File "/opt/venv/lib/python3.6/site-packages/rasa/nlu/test.py", line 889, in align_entity_predictions
    extracted = determine_token_labels(t, entities, {extractor})
  File "/opt/venv/lib/python3.6/site-packages/rasa/nlu/test.py", line 852, in determine_token_labels
    candidates = find_intersecting_entites(token, entities)
  File "/opt/venv/lib/python3.6/site-packages/rasa/nlu/test.py", line 807, in find_intersecting_entites
    if is_token_within_entity(token, e):
  File "/opt/venv/lib/python3.6/site-packages/rasa/nlu/test.py", line 759, in is_token_within_entity
    return determine_intersection(token, entity) == len(token.text)
  File "/opt/venv/lib/python3.6/site-packages/rasa/nlu/test.py", line 773, in determine_intersection
    pos_entity = set(range(entity["start"], entity["end"]))
KeyError: 'start'
```

**Command or request that led to error**:
```
docker-compose run rasa test nlu --cross-validation --verbose -f 2
```

**Content of configuration file (config.yml)** (if relevant):
```yml

language: es
pipeline:
  - name: WhitespaceTokenizer
    case_sensitive: true
    intent_tokenization_flag: true
    intent_split_symbol: "+"
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
    features: [
      ["low", "title", "upper"],
      [
        "BOS",
        "EOS",
        "prefix5",
        "prefix2",
        "suffix5",
        "suffix3",
        "suffix2",
        "upper",
        "title",
        "digit",
      ],
      ["low", "title", "upper"],
    ]
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 3
  - name: DIETClassifier
    epochs: 10
  - name: components.fuzzy_query.FuzzyQuery
    score_cutoff: 0.7

policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 20
  - name: MappingPolicy
  - name: TwoStageFallbackPolicy
    nlu_threshold: 0.7
    core_threshold: 0.3
    fallback_core_action_name: "action_default_ask_affirmation"
    fallback_nlu_action_name: "action_handoff_to_human"
    deny_suggestion_intent_name: "out_of_scope"
```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by RubenAMtz** [comment]
I found the issue, my custom component which returns entities was the issue. Apparently it is now required for it to return an object with these two extra keys: 'start' and 'end', which correspond to the position of the returned entity within the user input. I found this by going through the code of the Duckling component.
