### ISSUE TITLE
Environment Variables in *.yml files are not resolved

### ISSUE THREAD

**Issue by wederer** [RasaHQ/rasa#5522]
**Rasa version**:
1.9.3

**Python version**:
3.6.9

**Operating system** (windows, osx, ...):
Ubuntu 18.04

**Issue**:
When using an environment variable in any .yml file it will not be resolved/used.
e.g. 
```
# endpoints.yml
action_endpoint:
  url: "http://localhost:${ACTION_PORT}/webhook"
```

This is especially needed for the credentials.yml file.

**Error (including full traceback)**:
```
Failed to run custom action 'action_example'. Action server responded with a non 200 status code of None. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: http://localhost:${ACTION_PORT}/webhook

```

**Command or request that led to error**:
```
python3 -m rasa shell
```

Relates to #2571

**Comment by sara-tagger** [comment]
Thanks for the issue, @tabergma will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by tabergma** [comment]
Can you please do `python3 -m rasa shell --debug` and past the log output here? Thanks.

**Comment by wederer** [comment]
```
2020-03-31 13:19:36 DEBUG    rasa.model  - Extracted model to '/tmp/tmp_mc1mx6v'.
2020-03-31 13:19:36 DEBUG    rasa.cli.utils  - Parameter 'endpoints' not set. Using default location 'endpoints.yml' instead.
2020-03-31 13:19:36 DEBUG    rasa.cli.utils  - Parameter 'credentials' not set. Using default location 'credentials.yml' instead.
2020-03-31 13:19:36 DEBUG    rasa.model  - Extracted model to '/tmp/tmpolezrnrm'.
2020-03-31 13:19:37 INFO     root  - Connecting to channel 'cmdline' which was specified by the '--connector' argument. Any other channels will be ignored. To connect to all given channels, omit the '--connector' argument.
2020-03-31 13:19:37 DEBUG    sanic.root  - CORS: Configuring CORS with resources: {'/*': {'origins': [''], 'methods': 'DELETE, GET, HEAD, OPTIONS, PATCH, POST, PUT', 'allow_headers': ['.*'], 'expose_headers': None, 'supports_credentials': True, 'max_age': None, 'send_wildcard': False, 'automatic_options': True, 'vary_header': True, 'resources': {'/*': {'origins': ''}}, 'intercept_exceptions': True, 'always_send': True}}
2020-03-31 13:19:37 DEBUG    rasa.core.utils  - Available web server routes: 
/webhooks/rest                                     GET                            custom_webhook_CmdlineInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_CmdlineInput.receive
/                                                  GET                            hello
2020-03-31 13:19:37 INFO     root  - Starting Rasa server on http://localhost:5005
2020-03-31 13:19:37 DEBUG    rasa.core.utils  - Using the default number of Sanic workers (1).
2020-03-31 13:19:37 INFO     root  - Enabling coroutine debugging. Loop id 91536296.
2020-03-31 13:19:37 DEBUG    rasa.model  - Extracted model to '/tmp/tmpmd10mxll'.
2020-03-31 13:19:38 DEBUG    rasa.utils.tensorflow.models  - Loading the model ...
2020-03-31 13:19:38.500231: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (303)
2020-03-31 13:19:39 DEBUG    rasa.utils.tensorflow.models  - Finished loading the model.
2020-03-31 13:19:39 DEBUG    rasa.utils.tensorflow.models  - Building tensorflow prediction graph...
2020-03-31 13:19:45 DEBUG    rasa.utils.tensorflow.models  - Finished building tensorflow prediction graph.
2020-03-31 13:19:45 DEBUG    rasa.nlu.classifiers.diet_classifier  - Failed to load model. Maybe the path '/tmp/tmpmd10mxll/nlu' doesn't exist?
2020-03-31 13:19:45 DEBUG    rasa.core.tracker_store  - Connected to InMemoryTrackerStore.
2020-03-31 13:19:45 DEBUG    rasa.core.lock_store  - Connected to lock store 'InMemoryLockStore'.
2020-03-31 13:19:45 DEBUG    rasa.model  - Extracted model to '/tmp/tmpjfrctg1_'.
2020-03-31 13:19:45 DEBUG    pykwalify.compat  - Using yaml library: /home/wederer/.local/lib/python3.6/site-packages/ruamel/yaml/__init__.py
2020-03-31 13:19:45 DEBUG    rasa.utils.tensorflow.models  - Loading the model ...
2020-03-31 13:19:45 DEBUG    rasa.utils.tensorflow.models  - Finished loading the model.
2020-03-31 13:19:45 DEBUG    rasa.utils.tensorflow.models  - Building tensorflow prediction graph...
2020-03-31 13:19:47 DEBUG    rasa.utils.tensorflow.models  - Finished building tensorflow prediction graph.
2020-03-31 13:19:47 DEBUG    rasa.core.nlg.generator  - Instantiated NLG to 'TemplatedNaturalLanguageGenerator'.
Bot loaded. Type a message and press enter (use '/stop' to exit): 
Your input ->  was ist corona?                                                                                                                                                                                     
2020-03-31 13:19:50 DEBUG    rasa.core.tracker_store  - Creating a new tracker for id 'cdbfb123db124d4385fd9347dcc26649'.
2020-03-31 13:19:50 DEBUG    rasa.core.processor  - Starting a new session for conversation ID 'cdbfb123db124d4385fd9347dcc26649'.
2020-03-31 13:19:50 DEBUG    rasa.core.processor  - Action 'action_session_start' ended with events '[<rasa.core.events.SessionStarted object at 0x7f1fd9307a90>, <rasa.core.events.ActionExecuted object at 0x7f1fd9307a58>]'.
2020-03-31 13:19:50 DEBUG    rasa.core.processor  - Current slot values: 
	location: None
	metric: None
	topic: None
2020-03-31 13:19:51 DEBUG    rasa.nlu.classifiers.diet_classifier  - There is no trained model: component is either not trained or didn't receive enough training data.
2020-03-31 13:19:51 DEBUG    rasa.nlu.selectors.response_selector  - Adding following selector key to message property: default
2020-03-31 13:19:51 DEBUG    rasa.core.processor  - Received user message 'was ist corona?' with intent '{'name': 'what_is', 'confidence': 0.9256802797317505}' and entities '[]'
2020-03-31 13:19:51 DEBUG    rasa.core.processor  - Logged UserUtterance - tracker now has 4 events.
2020-03-31 13:19:51 DEBUG    rasa.core.policies.memoization  - Current tracker state [None, None, None, {}, {'prev_action_listen': 1.0, 'intent_what_is': 1.0}]
2020-03-31 13:19:51 DEBUG    rasa.core.policies.memoization  - There is no memorised next action
2020-03-31 13:19:51 DEBUG    rasa.core.policies.fallback  - NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2020-03-31 13:19:51 DEBUG    rasa.core.policies.ensemble  - Predicted next action using policy_1_TEDPolicy
2020-03-31 13:19:51 DEBUG    rasa.core.processor  - Predicted next action 'action_what_is' with confidence 0.88.
2020-03-31 13:19:51 DEBUG    rasa.core.actions.action  - Calling action endpoint to run action 'action_what_is'.
2020-03-31 13:19:51 ERROR    rasa.core.actions.action  - Failed to run custom action 'action_what_is'. Action server responded with a non 200 status code of None. Make sure your action server properly runs actions and returns a 200 once the action is executed. Error: http://localhost:${RASA_ACTION_PORT}/webhook
2020-03-31 13:19:51 ERROR    rasa.core.processor  - Encountered an exception while running action 'action_what_is'. Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
2020-03-31 13:19:51 DEBUG    rasa.core.processor  - Failed to execute custom action.
Traceback (most recent call last):
  File "/home/wederer/.local/lib/python3.6/site-packages/yarl/__init__.py", line 161, in __new__
    port = val.port
  File "/usr/lib/python3.6/urllib/parse.py", line 169, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10: '${RASA_ACTION_PORT}'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/wederer/.local/lib/python3.6/site-packages/aiohttp/client.py", line 380, in _request
    url = URL(str_or_url)
  File "/home/wederer/.local/lib/python3.6/site-packages/yarl/__init__.py", line 165, in __new__
    ) from e
ValueError: Invalid URL: port can't be converted to integer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wederer/.local/lib/python3.6/site-packages/rasa/core/actions/action.py", line 549, in run
    json=json_body, method="post", timeout=DEFAULT_REQUEST_TIMEOUT
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/home/wederer/.local/lib/python3.6/site-packages/rasa/utils/endpoints.py", line 146, in request
    **kwargs,
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/home/wederer/.local/lib/python3.6/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/home/wederer/.local/lib/python3.6/site-packages/aiohttp/client.py", line 382, in _request
    raise InvalidURL(str_or_url)
aiohttp.client_exceptions.InvalidURL: http://localhost:${RASA_ACTION_PORT}/webhook

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/wederer/.local/lib/python3.6/site-packages/rasa/core/processor.py", line 616, in _run_action
    events = await action.run(output_channel, nlg, tracker, self.domain)
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/home/wederer/.local/lib/python3.6/site-packages/rasa/core/actions/action.py", line 595, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
2020-03-31 13:19:51 DEBUG    rasa.core.processor  - Action 'action_what_is' ended with events '[]'.
2020-03-31 13:19:51 DEBUG    rasa.core.processor  - Current slot values: 
	location: None
	metric: None
	topic: None
2020-03-31 13:19:51 DEBUG    rasa.core.policies.memoization  - Current tracker state [None, None, {}, {'prev_action_listen': 1.0, 'intent_what_is': 1.0}, {'prev_action_what_is': 1.0, 'intent_what_is': 1.0}]
2020-03-31 13:19:51 DEBUG    rasa.core.policies.memoization  - There is no memorised next action
2020-03-31 13:19:51 DEBUG    rasa.core.policies.mapping_policy  - There is no mapped action for the predicted intent, 'what_is'.
2020-03-31 13:19:51 DEBUG    rasa.core.policies.fallback  - NLU confidence threshold met, confidence of fallback action set to core threshold (0.3).
2020-03-31 13:19:51 DEBUG    rasa.core.policies.ensemble  - Predicted next action using policy_1_TEDPolicy
2020-03-31 13:19:51 DEBUG    rasa.core.processor  - Predicted next action 'action_listen' with confidence 0.98.
2020-03-31 13:19:51 DEBUG    rasa.core.processor  - Action 'action_listen' ended with events '[]'.
2020-03-31 13:19:51 DEBUG    rasa.core.lock_store  - Deleted lock for conversation 'cdbfb123db124d4385fd9347dcc26649'.
```

**Comment by tabergma** [comment]
Can you try to remove the quotes around the url? 
```
# endpoints.yml
action_endpoint:
  url: http://localhost:${ACTION_PORT}/webhook
```

**Comment by wederer** [comment]
Oh boy. To think that I debugged rasa code for like an hour to find a bug 🙈

Thanks!
