### ISSUE TITLE
rasa Interactive throws up ruamel.yaml scanner error

### ISSUE THREAD

**Issue by Wing-e7** [RasaHQ/rasa#5551]
**Rasa version**: 1.9.4

**Rasa SDK version** (if used & relevant): 0.14.0

**Rasa X version** (if used & relevant):

**Python version**: 3.7

**Operating system** (windows, osx, ...): Windows 10

**Issue**: ruamel.yaml scanner error while running rasa interactive. The model trains propoerly without any errors or warnings

**Error (including full traceback)**:
``` Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\rasa\utils\io.py", line 118, in read_yaml
    return yaml_parser.load(content) or {}
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\ruamel\yaml\main.py", line 331, in load
    return constructor.get_single_data()
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\ruamel\yaml\constructor.py", line 109, in get_single_data
    node = self.composer.get_single_node()
  File "_ruamel_yaml.pyx", line 706, in _ruamel_yaml.CParser.get_single_node
  File "_ruamel_yaml.pyx", line 724, in _ruamel_yaml.CParser._compose_document
  File "_ruamel_yaml.pyx", line 775, in _ruamel_yaml.CParser._compose_node
  File "_ruamel_yaml.pyx", line 889, in _ruamel_yaml.CParser._compose_mapping_node
  File "_ruamel_yaml.pyx", line 731, in _ruamel_yaml.CParser._compose_node
  File "_ruamel_yaml.pyx", line 904, in _ruamel_yaml.CParser._parse_next_event
ruamel.yaml.scanner.ScannerError: while scanning for the next token
found character that cannot start any token
  in "<unicode string>", line 14, column 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\Scripts\rasa.exe\__main__.py", line 7, in <module>
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\rasa\__main__.py", line 91, in main
    cmdline_arguments.func(cmdline_arguments)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\rasa\cli\interactive.py", line 79, in interactive
    perform_interactive_learning(args, zipped_model, file_importer)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\rasa\cli\interactive.py", line 105, in perform_interactive_learning
    do_interactive_learning(args, file_importer)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\rasa\core\train.py", line 180, in do_interactive_learning
    server_args=args.__dict__,
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\rasa\core\training\interactive.py", line 1628, in run_interactive_learning
    endpoints = AvailableEndpoints.read_endpoints(server_args.get("endpoints"))
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\rasa\core\utils.py", line 400, in read_endpoints
    nlg = read_endpoint_config(endpoint_file, endpoint_type="nlg")
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\rasa\utils\endpoints.py", line 26, in read_endpoint_config
    content = rasa.utils.io.read_config_file(filename)
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\rasa\utils\io.py", line 190, in read_config_file
    content = read_yaml(read_file(filename))
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\rasa\utils\io.py", line 130, in read_yaml
    return yaml_parser.load(content) or {}
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\ruamel\yaml\main.py", line 331, in load
    return constructor.get_single_data()
  File "C:\Users\Administrator\AppData\Roaming\Python\Python37\site-packages\ruamel\yaml\constructor.py", line 109, in get_single_data
    node = self.composer.get_single_node()
  File "_ruamel_yaml.pyx", line 706, in _ruamel_yaml.CParser.get_single_node
  File "_ruamel_yaml.pyx", line 724, in _ruamel_yaml.CParser._compose_document
  File "_ruamel_yaml.pyx", line 775, in _ruamel_yaml.CParser._compose_node
  File "_ruamel_yaml.pyx", line 889, in _ruamel_yaml.CParser._compose_mapping_node
  File "_ruamel_yaml.pyx", line 731, in _ruamel_yaml.CParser._compose_node
  File "_ruamel_yaml.pyx", line 904, in _ruamel_yaml.CParser._parse_next_event
ruamel.yaml.scanner.ScannerError: while scanning for the next token
found character that cannot start any token
  in "<unicode string>", line 14, column 1

```

**Command or request that led to error**:
```
rasa interactive
```

**Content of configuration file (config.yml)** (if relevant):
```yml
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    retrieval_intent: faq
    epochs: 100

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 6
    epochs: 100
  - name: MappingPolicy
  - name: FormPolicy
```

**Content of domain file (domain.yml)** (if relevant):
```yml
actions:
- utter_ask_info
- utter_ask_price
- utter_bargain
- utter_bye
- utter_comeback
- utter_contact
- utter_deny
- utter_followup
- utter_giveinfo
- utter_greet
- utter_nod
- utter_purchase
- utter_welcome_context
- respond_faq

entities:
- company
- person_name
- purchase
- products


intents:
- greet
- affirm
- deny
- inform
- get_info
- get_challenges
- faq
- get_price
- get_bargain
- get_followup
- get_contact
- get_nod
- get_intro
- get_bye
- purchase  
- purchase_followup

responses:
  utter_ask_info:
  - text: What was your performance last year ?
  - text: How many admissions can you provide?
  - text: How do you help in branding?
  - text: How can you help us?
 utter_ask_price:
  - text: How much does it cost?
  - text: How much do you charge for branding?
  - text: How much does each admission cost?
  - text: How much do you charge?
 utter_bargain:
  - text: That is way beyond our budget
  - text: It is very costly
  - text: How about you give me 100 admissions at 6% each
  - text: I can work with the proposed amount but i need 6 guaranteed admissions
  - text: I have to discuss with management to finalise on the pricing
 utter_bye:
  - text: See you
  - text: Bye
  - text: Thank you and bye bye
 utter_comeback:
  - text: Come back later
  - text: Why dont you meet the Secretary
  - text: You should talk to the management
  - text: Please come back again
 utter_contact:
  - text: Sure. Take my card
  - text: Please note down principal@vbce.co.in
 utter_deny:
  - text: I am busy now. Come back later
  - text: Dont need what you are selling
  - text: Get out
  - text: No need for this
 utter_followup:
  - text: I am available next week
  - text: I dont see a point in doing this again
  - text: Would love to meet again
 utter_giveinfo:
  - text: We have 100 seats
  - text: Ours is an old college and we dont advewrtise anywhere
  - text: We spend around 20 Lakhs in marketing
  - text: We have an intake of 100 students in UG courses and 200 students in PG courses
  - text: We regularly advertise in newspapers and on hoarding
 utter_greet:
  - text: Hello! How are you doing today?
  - text: I am fine; how about you?
  - text: Hello
  - text: Hi
 utter_nod:
  - text: I agree
  - text: Thank you
  - text: Agreed
  - text: My pleasure
  - text: Hmm
 utter_purchase:
  - text: Yes I like your package offerings
  - text: I dont understand how you can get me admissions
  - text: I am not clear on your branding part
  - text: No. I am not interested
  - text: Yes. But the price seems high
  - text: I dont see a need for what you are offering
 utter_welcome_context:
  - text: You are sitting with the Management of a prestigious engineering college in Hyderabad. 
  session_expiration_time: 60
  carry_over_slots_to_new_session: true

forms:
- Info_Form

slots:
   person_name:
      type: unfeaturized
   company:
      type: unfeaturized
   purchase:
      type: bool
   products:
      type: unfeaturized

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @chkoss will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by Wing-e7** [comment]
Also, verified all my files with the online yaml tool. All the files check out fine.

**Comment by Wing-e7** [comment]
@sara-tagger Any update on this ?

**Comment by chkoss** [comment]
Hi @Wing-e7, sorry for the late reply. Can you post the content of your `endpoints.yml` file please? This seems to be the file that cannot be parsed properly.

**Comment by Wing-e7** [comment]
action_endpoint:
  url: "http://localhost:5805/webhook"

Everything else commented out

**Comment by Wing-e7** [comment]
@chkoss Help now..!!

**Comment by chkoss** [comment]
Is this the exact way it is written in your file? Looks like you are missing the indentation, it should be (note the two spaces in front of the url bit):
```
action_endpoint:
  url: "http://localhost:5805/webhook"
```
If you have indentation in your file and just didn't post it formatted here, make sure you are using spaces to indent and not tabs as YAML does not support tab indentation. Online yaml validation tools don't always pick up on such indentation mistakes, so you have to check that manually.

**Comment by Wing-e7** [comment]
Thanks. Got it.
