### ISSUE TITLE
Getting TypeError: 'NoneType' object is not iterable on training model

### ISSUE THREAD

**Issue by Prskriti** [RasaHQ/rasa#5552]
**Rasa version**: Rasa 1.7.2
**Python version**: Python 3.6.8

**Operating system**:  OSX

**Issue**: Type error on the training rasa model

**Error (including full traceback)**:
```
2020-04-01 17:13:56 DEBUG    rasa.nlu.training_data.loading  - Training data format of 'data/nlu.md' is 'md'.
2020-04-01 17:13:56 DEBUG    rasa.nlu.training_data.loading  - Training data format of 'data/responses.md' is 'nlg.md'.
2020-04-01 17:13:56 DEBUG    rasa.nlu.training_data.loading  - Training data format of 'data/stories.md' is 'unk'.
2020-04-01 17:13:56 DEBUG    pykwalify.compat  - Using yaml library: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/ruamel/yaml/__init__.py
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa/core/domain.py:148: FutureWarning: No tracker session configuration was found in the loaded domain. Domains without a session config will automatically receive a session expiration time of 60 minutes in Rasa version 2.0 if not configured otherwise.
  session_config = cls._get_session_config(data.get(SESSION_CONFIG_KEY, {}))
2020-04-01 17:13:56 DEBUG    rasa.nlu.training_data.loading  - Training data format of 'data/responses.md' is 'nlg.md'.
2020-04-01 17:13:56 DEBUG    rasa.nlu.training_data.loading  - Training data format of 'data/nlu.md' is 'md'.
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/rasa", line 11, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa/__main__.py", line 76, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa/cli/train.py", line 76, in train
    additional_arguments=extract_additional_arguments(args),
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa/train.py", line 50, in train
    additional_arguments=additional_arguments,
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa/train.py", line 101, in train_async
    additional_arguments,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa/train.py", line 144, in _train_async_internal
    file_importer.get_stories(), file_importer.get_nlu_data()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa/importers/importer.py", line 269, in get_nlu_data
    nlu_data = await asyncio.gather(*nlu_data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa/importers/rasa.py", line 61, in get_nlu_data
    return utils.training_data_from_paths(self._nlu_files, language)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa/importers/utils.py", line 9, in training_data_from_paths
    training_datas = [loading.load_data(nlu_file, language) for nlu_file in paths]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa/importers/utils.py", line 9, in <listcomp>
    training_datas = [loading.load_data(nlu_file, language) for nlu_file in paths]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa/nlu/training_data/loading.py", line 67, in load_data
    data_sets = [_load(f, language) for f in files]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa/nlu/training_data/loading.py", line 67, in <listcomp>
    data_sets = [_load(f, language) for f in files]
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa/nlu/training_data/loading.py", line 138, in _load
    return reader.read(filename, language=language, fformat=fformat)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa/nlu/training_data/formats/readerwriter.py", line 15, in read
    return self.reads(rasa.utils.io.read_file(filename), **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa/nlu/training_data/formats/markdown.py", line 75, in reads
    self._parse_item(line)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa/nlu/training_data/formats/markdown.py", line 116, in _parse_item
    parsed = self.parse_training_example(item)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa/nlu/training_data/formats/markdown.py", line 180, in parse_training_example
    message = Message.build(plain_text, self.current_title)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasa/nlu/training_data/message.py", line 75, in build
    split_intent, response_key = cls.separate_intent_response_key(intent)
TypeError: 'NoneType' object is not iterable
```

**Command or request that led to error**: 
```rasa train -c ./config.yml --debug```

**Content of configuration file (config.yml)** :
```
language: en
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
policies:
  - name: MemoizationPolicy
    max_history: 1
  - name: MappingPolicy

```

**Content of domain file (domain.yml)** :
```
intents:
- greet
- bye
- thank
- faq
responses:
  utter_noworries:
  - text: No worries!
  utter_greet:
  - text: Hi
  utter_bye:
  - text: Bye!
actions:
- respond_faq

```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @alwx will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
