### ISSUE TITLE
Rasa fails to load model from aws s3

### ISSUE THREAD

**Issue by Ben-Mark** [RasaHQ/rasa#5564]
**Rasa version**: Rasa 1.7.0. (running from docker image rasa/rasa)

**Rasa SDK version** (if used & relevant): not relevant

**Rasa X version** (if used & relevant): not relevant

**Python version**: docker image rasa/rasa (what ever python version in it)

**Operating system** (windows, osx, ...):  docker image rasa/rasa...

**Issue**:  error on fetching aws s3 model

**Error (including full traceback)**:
```
2020-04-02 12:08:37 INFO     root  - Starting Rasa server on http://localhost:5005
2020-04-02 12:08:39 ERROR    rasa.core.agent  - Could not load model due to expected string or bytes-like object.
[2020-04-02 12:08:39 +0000] [1] [ERROR] Experienced exception while trying to serve
Traceback (most recent call last):
  File "/build/lib/python3.6/site-packages/sanic/app.py", line 1133, in run
    serve(**server_settings)
  File "/build/lib/python3.6/site-packages/sanic/server.py", line 857, in serve
    trigger_events(before_start, loop)
  File "/build/lib/python3.6/site-packages/sanic/server.py", line 634, in trigger_events
    loop.run_until_complete(result)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/build/lib/python3.6/site-packages/rasa/core/run.py", line 247, in load_agent_on_start
    action_endpoint=endpoints.action,
  File "/build/lib/python3.6/site-packages/rasa/core/agent.py", line 259, in load_agent
    model_server=model_server,
  File "/build/lib/python3.6/site-packages/rasa/core/agent.py", line 976, in load_from_remote_storage
    persistor = get_persistor(remote_storage)
  File "/build/lib/python3.6/site-packages/rasa/nlu/persistor.py", line 19, in get_persistor
    os.environ.get("BUCKET_NAME"), os.environ.get("AWS_ENDPOINT_URL")
  File "/build/lib/python3.6/site-packages/rasa/nlu/persistor.py", line 121, in __init__
    self._ensure_bucket_exists(bucket_name)
  File "/build/lib/python3.6/site-packages/rasa/nlu/persistor.py", line 143, in _ensure_bucket_exists
    Bucket=bucket_name, CreateBucketConfiguration=bucket_config
  File "/build/lib/python3.6/site-packages/boto3/resources/factory.py", line 520, in do_action
    response = action(self, *args, **kwargs)
  File "/build/lib/python3.6/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/build/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/build/lib/python3.6/site-packages/botocore/client.py", line 634, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/build/lib/python3.6/site-packages/botocore/client.py", line 680, in _convert_to_request_dict
    api_params, operation_model, context)
  File "/build/lib/python3.6/site-packages/botocore/client.py", line 712, in _emit_api_params
    params=api_params, model=operation_model, context=context)
  File "/build/lib/python3.6/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/build/lib/python3.6/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/build/lib/python3.6/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/build/lib/python3.6/site-packages/botocore/handlers.py", line 219, in validate_bucket_name
    if VALID_BUCKET.search(bucket) is None:
TypeError: expected string or bytes-like object
No chat connector configured, falling back to the REST input channel. To connect your bot to another channel, read the docs here: https://rasa.com/docs/rasa/user-guide/messaging-and-voice-channels
Traceback (most recent call last):

```

**Command or request that led to error**:
```
my envs:

export AWS_DEFAULT_REGION=“eu-central-1”

export AWS_SECRET_ACCESS_KEY=“secret…”

export AWS_ACCESS_KEY_ID=“secret…”

export BUCKET_NAME=“nlp.models”

export AWS_ENDPOINT_URL=“https://s3.eu-central-1.amazonaws.com”

docker run -p 5005:5005 rasa/rasa run -m latest-model.tar.gz --enable-api --log-file out.log --remote-storage aws
```

**Content of configuration file (config.yml)** (if relevant):
```yml
language: en
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: CRFEntityExtractor
    features:
      - - low
        - upper
      - - low
        - prefix5
        - prefix2
        - suffix5
        - suffix3
        - suffix2
        - digit
        - pattern
      - - low
        - upper
  - name: EntitySynonymMapper
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 1
    max_ngram: 4
  - name: EmbeddingIntentClassifier
  - name: DucklingHTTPExtractor
    url: 'http://duckling-server:8000'
    dimensions:
      - time
      - number
      - distance
    timezone: Asia/Jerusalem
    locale: en-US
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy

```

**Content of domain file (domain.yml)** (if relevant):
```yml
session_config:
  session_expiration_time: 60
  carry_over_slots_to_new_session: true
intents:
  - greet
  - goodbye
  - affirm
  - deny
  - mood_great
  - mood_unhappy
  - bot_challenge
  - offend
  - compliment
  - whatsup
  - dont_know
  - agent_name
  - bye
  - come_again
  - something_else
  - explain_question
  - later
  - hello
  - hold_on
  - stop
  - thanks
  - None
  - provideYearMakeModel
  - live_agent
  - are_you_bot
  - flow_length
entities:
  - make
  - wh_question
  - coverage
  - province
  - bool
actions:
  - utter_greet
  - utter_cheer_up
  - utter_did_that_help
  - utter_happy
  - utter_goodbye
  - utter_iamabot
```

Hi, After running over every possible post related to running a rasa rest service with a model from aws s3 I came to a dead end. It simply isn’t working and the documentation for it is too broad.

The s3 file structure is plain simple:

s3 bucket called nlp.models (in frankfurt , eu-central-1) inside that bucket there’s 1 file: latest-model.tar.gz

My aws IAM permissions are set and verified with 10 other applications fetching from s3 from that machine.

This is not working guys, is the AWS_ENDPOINT_URL wrong? I tried with setting it to https://s3.amazonaws.com/ , with and with an ending slash. tried also with https://s3.eu-central-1.amazonaws.com/nlp.models with no success.

You must give a proper usage example, this isn’t the first feature that isn’t working.

Please advise , Thank you

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @tmbo will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by KarthiAru** [comment]
@Ben-Mark Can you try again after removing the .(dot) from the bucket name?

Also, try this code locally to see if you're able to interact with s3.

```
import boto3
from botocore.client import Config

AWS_DEFAULT_REGION="eu-central-1"
AWS_SECRET_ACCESS_KEY="secret…"
AWS_ACCESS_KEY_ID="secret…"
BUCKET_NAME="nlpmodels"
AWS_ENDPOINT_URL="https://s3.eu-central-1.amazonaws.com"

session = boto3.session.Session()
client = session.client('s3',
                        region_name=AWS_DEFAULT_REGION,
                        endpoint_url=AWS_ENDPOINT_URL,
                        aws_access_key_id=AWS_ACCESS_KEY_ID,
                        aws_secret_access_key=AWS_SECRET_ACCESS_KEY)

def ListFiles(client):
    """List files in specific S3 URL"""
    response = client.list_objects(Bucket=BUCKET_NAME)
    for content in response.get('Contents', []):
        yield content.get('Key')

file_list = ListFiles(client)
for file in file_list:
    print('File found: %s' % file)
```

**Comment by Ben-Mark** [comment]
Didn't work, 
posted the log in pastebin:
[](https://pastebin.com/B52Aiuiq)

Also tried to run a rasa/rasa dockerfile extension with injecting the env variables to the container itself
it also failed..

Maybe the issue is with boto3 in regards to my aws credentials which contain uppercase letters?

**Comment by KarthiAru** [comment]
@Ben-Mark The issue isn't with rasa. It is working for me. To troubleshoot further, can you paste the output of the code that I shared above?
Also, share the output of `rasa run --enable-api --remote-storage aws -vv`
Please ensure there is a model file in the bucket with the default name models.tar.gz.

**Comment by Ben-Mark** [comment]
@KarthiAru 

Have you used the rasa/rasa official image version?
or are you working with a different version.

because clearly in the 1.7.0 version its not working 

if you're working with a newer version, please upgrade the rasa/rasa image version so other can enjoy that super important feature.

**Comment by tangochris** [comment]
@Ben-Mark Agreed, our experience is that S3 storage does not work. We have to use EFS, which isn't ideal.

**Comment by ortsaCniveK** [comment]
@Ben-Mark I spun up a basic rasa project on rasa `1.7.0` as well as an S3 bucket with the initial model trained and was able to pull from the S3 bucket and load the model as expected (however without using Docker). What jumps out as a potential issue is adding the environment variables and expecting them in the docker container;  in order for the docker container to see those environment variables you have to pass them [as parameters when running the container](https://stackoverflow.com/questions/30494050/how-do-i-pass-environment-variables-to-docker-containers).  If the issue persists even when doing this, there might be some networking issues with the docker container connecting to the internet.

However, I have some additional feedback, because I went through a heck of a time trying to figure out what was happening even after finding this, but I ran into similar issues with setting remote storage up.  The issue here I think is lack of sufficient documentation and lack of some functionality on Rasa's end when interfacing with an S3 bucket.

1. The [remote storage docs](https://rasa.com/docs/rasa/user-guide/cloud-storage/#cloud-storage) don't cover the fact that **if you specify `--remote-storage aws` you still have to specify the model name**.  If you don't specify the model name, it will use the default `models` name which works **only when running in local**.  I even tried uploading my `models/` directory to see if it would be able to unzip the whole thing and find the latest model from there, but it treated `models.tar.gz` as the model itself (it errored out with a traceback provided below).  I think that if we allow users to use remote storage, specifying the model name should be optional and the logic to find the latest model in an S3 bucket should work out-of-the-box.
2. The `s3transfer` module pollutes the debug logs (`-vv`) with hundreds of messages like below:
    ```log
    2020-05-04 22:17:11 DEBUG    s3transfer.futures  - Submitting task IOWriteTask(transfer_id=0, {'offset': 29622272}) to executor <s3transfer.futures.BoundedExecutor object at 0x7f7b61ff9090> for transfer request: 0.
    2020-05-04 22:17:11 DEBUG    s3transfer.utils  - Acquiring 0
    2020-05-04 22:17:11 DEBUG    s3transfer.tasks  - IOWriteTask(transfer_id=0, {'offset': 29622272}) about to wait for the following futures []
    2020-05-04 22:17:11 DEBUG    s3transfer.tasks  - IOWriteTask(transfer_id=0, {'offset': 29622272}) done waiting for dependent futures
    2020-05-04 22:17:11 DEBUG    s3transfer.tasks  - Executing task IOWriteTask(transfer_id=0, {'offset': 29622272}) with kwargs {'fileobj': <_io.BufferedWriter name='20200504-182256.tar.gz'>, 'offset': 29622272}
    2020-05-04 22:17:11 DEBUG    s3transfer.utils  - Releasing acquire 0/None
    ```
3. There are unclosed SSL connections that `agent.py` complains about (again with below provided traceback)

<details>
<summary>traceback for attempting to load <code>models.tar.gz</code></summary>

```log
Traceback (most recent call last):
  File "/home/kevin/.cache/pypoetry/virtualenvs/venus-jw1ULBKI-py3.7/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/home/kevin/.cache/pypoetry/virtualenvs/venus-jw1ULBKI-py3.7/lib/python3.7/site-packages/rasa/__main__.py", line 91, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/home/kevin/.cache/pypoetry/virtualenvs/venus-jw1ULBKI-py3.7/lib/python3.7/site-packages/rasa/cli/run.py", line 95, in run
    rasa.run(**vars(args))
  File "/home/kevin/.cache/pypoetry/virtualenvs/venus-jw1ULBKI-py3.7/lib/python3.7/site-packages/rasa/run.py", line 56, in run
    **kwargs,
  File "/home/kevin/.cache/pypoetry/virtualenvs/venus-jw1ULBKI-py3.7/lib/python3.7/site-packages/rasa/core/run.py", line 217, in serve_application
    endpoints.lock_store if endpoints else None
  File "/home/kevin/.cache/pypoetry/virtualenvs/venus-jw1ULBKI-py3.7/lib/python3.7/site-packages/sanic/app.py", line 1167, in run
    serve(**server_settings)
  File "/home/kevin/.cache/pypoetry/virtualenvs/venus-jw1ULBKI-py3.7/lib/python3.7/site-packages/sanic/server.py", line 892, in serve
    trigger_events(before_start, loop)
  File "/home/kevin/.cache/pypoetry/virtualenvs/venus-jw1ULBKI-py3.7/lib/python3.7/site-packages/sanic/server.py", line 668, in trigger_events
    loop.run_until_complete(result)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/home/kevin/.cache/pypoetry/virtualenvs/venus-jw1ULBKI-py3.7/lib/python3.7/site-packages/rasa/core/run.py", line 258, in load_agent_on_start
    action_endpoint=endpoints.action,
  File "/home/kevin/.cache/pypoetry/virtualenvs/venus-jw1ULBKI-py3.7/lib/python3.7/site-packages/rasa/core/agent.py", line 259, in load_agent
    model_server=model_server,
  File "/home/kevin/.cache/pypoetry/virtualenvs/venus-jw1ULBKI-py3.7/lib/python3.7/site-packages/rasa/core/agent.py", line 968, in load_from_remote_storage
    remote_storage=remote_storage,
  File "/home/kevin/.cache/pypoetry/virtualenvs/venus-jw1ULBKI-py3.7/lib/python3.7/site-packages/rasa/core/agent.py", line 384, in load
    core_model, nlu_model = get_model_subdirectories(model_path)
  File "/home/kevin/.cache/pypoetry/virtualenvs/venus-jw1ULBKI-py3.7/lib/python3.7/site-packages/rasa/model.py", line 227, in get_model_subdirectories
    unpacked_model_path
rasa.exceptions.ModelNotFound: No NLU or Core data for unpacked model at: '/tmp/tmpre3xn48m'.
```
</details>

<details>
<summary>traceback for unclosed SSL connection</summary>


```log
/home/kevin/.cache/pypoetry/virtualenvs/venus-jw1ULBKI-py3.7/lib/python3.7/site-packages/rasa/core/agent.py:259: ResourceWarning: unclosed <ssl.SSLSocket fd=30, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.0.133', 40356), raddr=('54.231.113.240', 443)>
  model_server=model_server,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/home/kevin/.cache/pypoetry/virtualenvs/venus-jw1ULBKI-py3.7/lib/python3.7/site-packages/rasa/core/agent.py:259: ResourceWarning: unclosed <ssl.SSLSocket fd=24, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.0.133', 40344), raddr=('54.231.113.240', 443)>
  model_server=model_server,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/home/kevin/.cache/pypoetry/virtualenvs/venus-jw1ULBKI-py3.7/lib/python3.7/site-packages/rasa/core/agent.py:259: ResourceWarning: unclosed <ssl.SSLSocket fd=34, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.0.133', 40362), raddr=('54.231.113.240', 443)>
  model_server=model_server,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/home/kevin/.cache/pypoetry/virtualenvs/venus-jw1ULBKI-py3.7/lib/python3.7/site-packages/rasa/core/agent.py:259: ResourceWarning: unclosed <ssl.SSLSocket fd=26, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.0.133', 40348), raddr=('54.231.113.240', 443)>
  model_server=model_server,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/home/kevin/.cache/pypoetry/virtualenvs/venus-jw1ULBKI-py3.7/lib/python3.7/site-packages/rasa/core/agent.py:259: ResourceWarning: unclosed <ssl.SSLSocket fd=25, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.0.133', 40346), raddr=('54.231.113.240', 443)>
  model_server=model_server,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/home/kevin/.cache/pypoetry/virtualenvs/venus-jw1ULBKI-py3.7/lib/python3.7/site-packages/rasa/core/agent.py:259: ResourceWarning: unclosed <ssl.SSLSocket fd=32, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.0.133', 40358), raddr=('54.231.113.240', 443)>
  model_server=model_server,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/home/kevin/.cache/pypoetry/virtualenvs/venus-jw1ULBKI-py3.7/lib/python3.7/site-packages/rasa/core/agent.py:259: ResourceWarning: unclosed <ssl.SSLSocket fd=33, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.0.133', 40360), raddr=('54.231.113.240', 443)>
  model_server=model_server,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/home/kevin/.cache/pypoetry/virtualenvs/venus-jw1ULBKI-py3.7/lib/python3.7/site-packages/rasa/core/agent.py:259: ResourceWarning: unclosed <ssl.SSLSocket fd=29, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.0.133', 40354), raddr=('54.231.113.240', 443)>
  model_server=model_server,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/home/kevin/.cache/pypoetry/virtualenvs/venus-jw1ULBKI-py3.7/lib/python3.7/site-packages/rasa/core/agent.py:259: ResourceWarning: unclosed <ssl.SSLSocket fd=28, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.0.133', 40352), raddr=('54.231.113.240', 443)>
  model_server=model_server,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/home/kevin/.cache/pypoetry/virtualenvs/venus-jw1ULBKI-py3.7/lib/python3.7/site-packages/rasa/core/agent.py:259: ResourceWarning: unclosed <ssl.SSLSocket fd=27, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.0.133', 40350), raddr=('54.231.113.240', 443)>
  model_server=model_server,
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```
</details>
