### ISSUE TITLE
Event Service crashes when message is sent using Interactive Learning page

### ISSUE THREAD

**Issue by Naktibalda** [RasaHQ/rasa#5577]
**Rasa version**: 1.9.4

**Rasa X version** : 0.27.4

**Python version**: 3.6

**Operating system**: Linux (Kubernetes cluster running on minikube v1.9.1 on Microsoft Windows 10 Pro)

**Issue**:
Interactive learning page doesn't work.
I noticed errors happening in event service when Interactive learning page is opened and when each message is sent.

This issues does not affect shared chat window, it works fine until interactive learning breaks event services.

**Error (including full traceback)**:
```
ERROR:__main__:Caught an exception while consuming events. Will retry in 5 s.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/rasax/community/services/event_service.py", line 1391, in continuously_consume
    consumer.consume()
  File "/usr/local/lib/python3.6/site-packages/rasax/community/services/event_consumers/pika_consumer.py", line 123, in consume
    self.channel.start_consuming()
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 1866, in start_consuming
    self._process_data_events(time_limit=None)
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 2027, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 834, in process_data_events
    self._dispatch_channel_events()
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 566, in _dispatch_channel_events
    impl_channel._get_cookie()._dispatch_events()
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 1494, in _dispatch_events
    evt.properties, evt.body)
  File "/usr/local/lib/python3.6/site-packages/rasax/community/services/event_consumers/pika_consumer.py", line 116, in _callback
    properties
  File "/usr/local/lib/python3.6/site-packages/rasax/community/services/event_consumers/event_consumer.py", line 148, in log_event
    on_save=lambda event: self._on_event_saved(data, event),
  File "/usr/local/lib/python3.6/site-packages/rasax/community/services/event_service.py", line 199, in save_event
    self._update_conversation_metadata(event)
  File "/usr/local/lib/python3.6/site-packages/rasax/community/services/event_service.py", line 359, in _update_conversation_metadata
    event_confidence, conversation.minimum_action_confidence
TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

**Command or request that led to error**:
```
POST http://192.168.1.78:30984/api/conversations/b3073910b110414797222eeaab9243c7/messages?environment=production

{"message":"test"}
```

Endpoint used by chat window doesn't cause crash and responds correctly:
```
POST http://192.168.1.78:30984/api/conversations/me/messages?environment=production

http://192.168.1.78:30984/api/conversations/me/messages?environment=production
```

**Content of configuration file (config.yml)** (if relevant):
```yml
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: "lt"  # your two-letter language code

pipeline:
  - name: SpacyNLP
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
    max_history: 1
  - name: MappingPolicy

```

**Content of domain file (domain.yml)** (if relevant):
I don't think that it is relevant, but you can find it at
https://github.com/Naktibalda/rasa-koronavirusas/blob/8a5278f9d499fb7769dbc3a8b949011d8e7f88ed/domain.yml

I use a custom docker image with Spacy and LT language model, based on 1.9.4 space-de docker file.
I changed Docker file to install Spacy using Pip, because LT model is only available in Spacy 2.2
Dockerfile and config.yml:
https://github.com/Naktibalda/rasa/commit/491555f08b618ba531f1aa0087e30327c7b7b6ee

**Comment by Naktibalda** [comment]
I noticed that in Interactive Learning Mode I get correct classification and correct response action, but no response.
Event Service error happens on request to http://192.168.1.78:30984/api/conversations/e3e6aacab74c4fccb0f99779b0c5ec18/execute

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @chkoss will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by sara-tagger** [comment]
Thanks for the issue, @rctatman will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by degiz** [comment]
Hey @Naktibalda,

> Error (including full traceback):
 File "/usr/local/lib/python3.6/site-packages/rasax/community/services/event_service.py", line 359, in _update_conversation_metadata


The stack trace belongs to 0.26.x release of Rasa X. Are you sure you have 0.27? You can check that with `/api/version` endpoint.

If no, please try to upgrade to 0.27, the mentioned error shouldn't exist there. If that still doesn't work, I'll be happy to help you!

**Comment by Naktibalda** [comment]
Response of `/api/version`:
```js
{
  "rasa": {
    "production": "1.9.4",
    "worker": "1.9.4"
  },
  "rasa-x": "0.27.4",
  "keys": [
    {
      "alg": "RS256",
      "key": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmUFvCj8RMCAQvgkppOYw\n\/VWoRuoXXzNbwRo8EZqp5yfBDHke5BeqgMy3Z9RIJRjV08\/Ljwp6vgy\/Xiqd6lEM\npKMi1hFeSuF87h8RxbWGgASuTvurFBGjvVu9boCgHEYpdPgBy89rKDZPWkNST4xC\nFPFsO3ATD7Ze\/wZb653ZdjU+CilxnpC\/DSFfhS88wMoQstyfWMEcafhZ1clwiHby\n964aqe83BENlnAnZs98+F9\/0USFa61p4y7h2AcdQD1qAMAKILLhNKHl4LzbHZHzz\neBXFdLBf5X+JFUAM8\/YZomjUKKxHDmS0t5Z9DzqkBwDAT0MnfjOQXIMm+tyMtyNc\nAQIDAQAB\n-----END PUBLIC KEY-----\n"
    }
  ]
}
```

Fresh stacktraces:
```
[2020-04-06 10:02:44 +0000] [13] [INFO] Starting worker [13]
ERROR:__main__:Caught an exception while consuming events. Will retry in 5 s.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/rasax/community/services/event_service.py", line 1391, in continuously_consume
    consumer.consume()
  File "/usr/local/lib/python3.6/site-packages/rasax/community/services/event_consumers/pika_consumer.py", line 123, in consume
    self.channel.start_consuming()
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 1866, in start_consuming
    self._process_data_events(time_limit=None)
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 2027, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 834, in process_data_events
    self._dispatch_channel_events()
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 566, in _dispatch_channel_events
    impl_channel._get_cookie()._dispatch_events()
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 1494, in _dispatch_events
    evt.properties, evt.body)
  File "/usr/local/lib/python3.6/site-packages/rasax/community/services/event_consumers/pika_consumer.py", line 116, in _callback
    properties
  File "/usr/local/lib/python3.6/site-packages/rasax/community/services/event_consumers/event_consumer.py", line 148, in log_event
    on_save=lambda event: self._on_event_saved(data, event),
  File "/usr/local/lib/python3.6/site-packages/rasax/community/services/event_service.py", line 199, in save_event
    self._update_conversation_metadata(event)
  File "/usr/local/lib/python3.6/site-packages/rasax/community/services/event_service.py", line 359, in _update_conversation_metadata
    event_confidence, conversation.minimum_action_confidence
TypeError: '<' not supported between instances of 'NoneType' and 'int'
INFO:rasax.community.services.event_consumers.event_consumer:Terminated event consumer liveness endpoint process with PID '13'.
[2020-04-06 10:07:41 +0000] [13] [INFO] Stopping worker [13]
[2020-04-06 10:07:41 +0000] [13] [INFO] Server Stopped
INFO:rasax.community.services.event_consumers.event_consumer:Started Sanic liveness endpoint at port '5673'.
[2020-04-06 10:07:41 +0000] [19] [INFO] Goin' Fast @ http://0.0.0.0:5673
INFO:rasax.community.services.event_consumers.pika_consumer:Start consuming queue 'rasa_production_events' on pika host 'rasa-x-1585756598-rabbit'.
[2020-04-06 10:07:41 +0000] [19] [INFO] Starting worker [19]
ERROR:__main__:Caught an exception while consuming events. Will retry in 5 s.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/rasax/community/services/event_service.py", line 1391, in continuously_consume
    consumer.consume()
  File "/usr/local/lib/python3.6/site-packages/rasax/community/services/event_consumers/pika_consumer.py", line 123, in consume
    self.channel.start_consuming()
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 1866, in start_consuming
    self._process_data_events(time_limit=None)
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 2027, in _process_data_events
    self.connection.process_data_events(time_limit=time_limit)
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 834, in process_data_events
    self._dispatch_channel_events()
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 566, in _dispatch_channel_events
    impl_channel._get_cookie()._dispatch_events()
  File "/usr/local/lib/python3.6/site-packages/pika/adapters/blocking_connection.py", line 1494, in _dispatch_events
    evt.properties, evt.body)
  File "/usr/local/lib/python3.6/site-packages/rasax/community/services/event_consumers/pika_consumer.py", line 116, in _callback
    properties
  File "/usr/local/lib/python3.6/site-packages/rasax/community/services/event_consumers/event_consumer.py", line 148, in log_event
    on_save=lambda event: self._on_event_saved(data, event),
  File "/usr/local/lib/python3.6/site-packages/rasax/community/services/event_service.py", line 199, in save_event
    self._update_conversation_metadata(event)
  File "/usr/local/lib/python3.6/site-packages/rasax/community/services/event_service.py", line 359, in _update_conversation_metadata
    event_confidence, conversation.minimum_action_confidence
TypeError: '<' not supported between instances of 'NoneType' and 'float'
[2020-04-06 10:07:49 +0000] [19] [INFO] Stopping worker [19]
```

I used `0.27.3` initially, but I upgraded to `0.27.4` on Friday, 3rd of April by setting `tag: "0.27.4"` in values.yml and running `helm upgrade rasa-x-1585756598 rasa-x/rasa-x --namespace rasa-koronavirusas --values values.yml`

Before raising this issue, I asked in the forum and there is a record about upgrade: https://forum.rasa.com/t/rasa-x-doesnt-respond-to-messages/26927

P.S. Please ignore any references to coronavirus, this is just a learning project at the moment.

**Comment by degiz** [comment]
hey @Naktibalda 

ok, thanks for the logs! I see the issue now.

The error come from `event-service` app from `values.yaml`. It should have the same tag `0.27.4` as the `rasax`. 
Actually, that should have happened automatically after you've updated tag for `rasax`, but we'll fix that later.

Also, to be on the safe side, please update the tag for `nginx` as well, it should be `0.27.4`.

**Comment by Naktibalda** [comment]
Thank you, upgrading eventService fixed the issue.

I added these lines to values.yaml:
```yaml
eventService:
    tag: "0.27.4"
nginx:
    tag: "0.27.4"
```
