### ISSUE TITLE
Rasa can't recover an old model version and have to ignore it

### ISSUE THREAD

**Issue by zucher** [RasaHQ/rasa#5585]
**Rasa version**:
1.9.5

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**:
3.6
**Operating system** (windows, osx, ...):
rasa docker image

**Issue**:
With an older install model version created with 1.7.4, Rasa 1.9.5 try to load model already present into the existing volume and failed definitively, instead of ignoring the incompatible model on volume in order to start from idle state.

**Error (including full traceback)**:
```
...
2020-04-06 21:17:52 INFO     root  - Starting Rasa server on http://localhost:5005
2020-04-06 21:17:52 DEBUG    rasa.core.utils  - Using the default number of Sanic workers (1).
2020-04-06 21:17:52 INFO     root  - Enabling coroutine debugging. Loop id 94235516381864.
2020-04-06 21:17:52 DEBUG    rasa.model  - Extracted model to '/tmp/tmpulx46fbn'.
2020-04-06 21:17:52 DEBUG    root  - Could not load interpreter from 'models'.
2020-04-06 21:17:52 DEBUG    rasa.core.tracker_store  - Connected to InMemoryTrackerStore.
2020-04-06 21:17:52 DEBUG    rasa.core.lock_store  - Connected to lock store 'RedisLockStore'.
2020-04-06 21:17:52 DEBUG    rasa.model  - Extracted model to '/tmp/tmpo2xo9uyb'.
2020-04-06 21:17:52 ERROR    rasa.core.agent  - Could not load model due to The model version is too old to be loaded by this Rasa NLU instance. Either retrain the model, or run with an older version. Model version: 1.7.4 Instance version: 1.9.5.
[2020-04-06 21:17:52 +0000] [7] [ERROR] Experienced exception while trying to serve
Traceback (most recent call last):
  File "/opt/venv/lib/python3.6/site-packages/sanic/app.py", line 1096, in run
    serve(**server_settings)
  File "/opt/venv/lib/python3.6/site-packages/sanic/server.py", line 742, in serve
    trigger_events(before_start, loop)
  File "/opt/venv/lib/python3.6/site-packages/sanic/server.py", line 604, in trigger_events
    loop.run_until_complete(result)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/opt/venv/lib/python3.6/site-packages/rasa/core/run.py", line 258, in load_agent_on_start
    action_endpoint=endpoints.action,
  File "/opt/venv/lib/python3.6/site-packages/rasa/core/agent.py", line 271, in load_agent
    remote_storage=remote_storage,
  File "/opt/venv/lib/python3.6/site-packages/rasa/core/agent.py", line 938, in load_local_model
    path_to_model_archive=model_archive,
  File "/opt/venv/lib/python3.6/site-packages/rasa/core/agent.py", line 387, in load
    interpreter = NaturalLanguageInterpreter.create(nlu_model)
  File "/opt/venv/lib/python3.6/site-packages/rasa/core/interpreter.py", line 54, in create
    return RasaNLUInterpreter(model_directory=obj)
  File "/opt/venv/lib/python3.6/site-packages/rasa/core/interpreter.py", line 274, in __init__
    self._load_interpreter()
  File "/opt/venv/lib/python3.6/site-packages/rasa/core/interpreter.py", line 297, in _load_interpreter
    self.interpreter = Interpreter.load(self.model_directory)
  File "/opt/venv/lib/python3.6/site-packages/rasa/nlu/model.py", line 300, in load
    Interpreter.ensure_model_compatibility(model_metadata)
  File "/opt/venv/lib/python3.6/site-packages/rasa/nlu/model.py", line 275, in ensure_model_compatibility
    "".format(model_version, rasa.__version__)
rasa.nlu.model.UnsupportedModelError: The model version is too old to be loaded by this Rasa NLU instance. Either retrain the model, or run with an older version. Model version: 1.7.4 Instance version: 1.9.5
Traceback (most recent call last):
  File "/opt/venv/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/opt/venv/lib/python3.6/site-packages/rasa/__main__.py", line 91, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/opt/venv/lib/python3.6/site-packages/rasa/cli/run.py", line 83, in run
    rasa.run(**vars(args))
  File "/opt/venv/lib/python3.6/site-packages/rasa/run.py", line 56, in run
    **kwargs,
  File "/opt/venv/lib/python3.6/site-packages/rasa/core/run.py", line 217, in serve_application
    endpoints.lock_store if endpoints else None
  File "/opt/venv/lib/python3.6/site-packages/sanic/app.py", line 1096, in run
    serve(**server_settings)
  File "/opt/venv/lib/python3.6/site-packages/sanic/server.py", line 742, in serve
    trigger_events(before_start, loop)
  File "/opt/venv/lib/python3.6/site-packages/sanic/server.py", line 604, in trigger_events
    loop.run_until_complete(result)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/opt/venv/lib/python3.6/site-packages/rasa/core/run.py", line 258, in load_agent_on_start
    action_endpoint=endpoints.action,
  File "/opt/venv/lib/python3.6/site-packages/rasa/core/agent.py", line 271, in load_agent
    remote_storage=remote_storage,
  File "/opt/venv/lib/python3.6/site-packages/rasa/core/agent.py", line 938, in load_local_model
    path_to_model_archive=model_archive,
  File "/opt/venv/lib/python3.6/site-packages/rasa/core/agent.py", line 387, in load
    interpreter = NaturalLanguageInterpreter.create(nlu_model)
  File "/opt/venv/lib/python3.6/site-packages/rasa/core/interpreter.py", line 54, in create
    return RasaNLUInterpreter(model_directory=obj)
  File "/opt/venv/lib/python3.6/site-packages/rasa/core/interpreter.py", line 274, in __init__
    self._load_interpreter()
  File "/opt/venv/lib/python3.6/site-packages/rasa/core/interpreter.py", line 297, in _load_interpreter
    self.interpreter = Interpreter.load(self.model_directory)
  File "/opt/venv/lib/python3.6/site-packages/rasa/nlu/model.py", line 300, in load
    Interpreter.ensure_model_compatibility(model_metadata)
  File "/opt/venv/lib/python3.6/site-packages/rasa/nlu/model.py", line 275, in ensure_model_compatibility
    "".format(model_version, rasa.__version__)
rasa.nlu.model.UnsupportedModelError: The model version is too old to be loaded by this Rasa NLU instance. Either retrain the model, or run with an older version. Model version: 1.7.4 Instance version: 1.9.5
```

**Command or request that led to error**:
```
rasa run
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @tmbo will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by zucher** [comment]
Any progress ? Thank you
