### ISSUE TITLE
Cannot train DIET classifier with Bert '

### ISSUE THREAD

**Issue by 3NFBAGDU** [RasaHQ/rasa#5618]
**Rasa version**: 1.9.1

**Rasa SDK version**  not used

**Rasa X version** not used

**Python version**: 3.6.9

**Operating system** ubuntu 18.04

**Issue**: I followed this instruction (link: https://rasa.com/docs/rasa/master/nlu/components/#hftransformersnlp) to fed rasa's DIET classifier with BERT features and i got  the following error.

**Error (including full traceback)**:
```
Traceback (most recent call last):                                                                                    File "/home/optio/rasaprojects/rasaenv/bin/rasa", line 8, in <module>                                                 sys.exit(main())                                                                                                  File "/home/optio/rasaprojects/rasaenv/lib/python3.6/site-packages/rasa/__main__.py", line 91, in main                cmdline_arguments.func(cmdline_arguments)                                                                         File "/home/optio/rasaprojects/rasaenv/lib/python3.6/site-packages/rasa/cli/train.py", line 76, in train              additional_arguments=extract_additional_arguments(args),                                                          File "/home/optio/rasaprojects/rasaenv/lib/python3.6/site-packages/rasa/train.py", line 50, in train                  additional_arguments=additional_arguments,                                                                        File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete                                           File "/home/optio/rasaprojects/rasaenv/lib/python3.6/site-packages/rasa/train.py", line 101, in train_async           additional_arguments,                                                                                             File "/home/optio/rasaprojects/rasaenv/lib/python3.6/site-packages/rasa/train.py", line 188, in _train_async_internal                                                                                                                     additional_arguments=additional_arguments,                                                                        File "/home/optio/rasaprojects/rasaenv/lib/python3.6/site-packages/rasa/train.py", line 245, in _do_training          persist_nlu_training_data=persist_nlu_training_data,                                                              File "/home/optio/rasaprojects/rasaenv/lib/python3.6/site-packages/rasa/train.py", line 474, in _train_nlu_with_validated_data                                                                                                            persist_nlu_training_data=persist_nlu_training_data,                                                              File "/home/optio/rasaprojects/rasaenv/lib/python3.6/site-packages/rasa/nlu/train.py", line 86, in train              interpreter = trainer.train(training_data, **kwargs)                                                              File "/home/optio/rasaprojects/rasaenv/lib/python3.6/site-packages/rasa/nlu/model.py", line 191, in train             updates = component.train(working_data, self.config, **context)                                                   File "/home/optio/rasaprojects/rasaenv/lib/python3.6/site-packages/rasa/nlu/utils/hugging_face/hf_transformers.py", line 472, in train                                                                                                    batch_docs = self._get_docs_for_batch(batch_messages, attribute)                                                  File "/home/optio/rasaprojects/rasaenv/lib/python3.6/site-packages/rasa/nlu/utils/hugging_face/hf_transformers.py", line 417, in _get_docs_for_batch                                                                                      batch_examples, attribute                                                                                         File "/home/optio/rasaprojects/rasaenv/lib/python3.6/site-packages/rasa/nlu/utils/hugging_face/hf_transformers.py", line 249, in _get_token_ids_for_batch                                                                                 example, attribute                                                                                                File "/home/optio/rasaprojects/rasaenv/lib/python3.6/site-packages/rasa/nlu/utils/hugging_face/hf_transformers.py", line 219, in _tokenize_example                                                                                        split_token_ids, split_token_strings File "/home/optio/rasaprojects/rasaenv/lib/python3.6/site-packages/rasa/nlu/utils/hugging_face/hf_transformers.py", line 154, in _lm_specific_token_cleanup                                                                               return model_tokens_cleaners[self.model_name](split_token_ids, token_strings)                                     File "/home/optio/rasaprojects/rasaenv/lib/python3.6/site-packages/rasa/nlu/utils/hugging_face/transformers_pre_post_processors.py", line 234, in bert_tokens_cleaner                                                                     return cleanup_tokens(list(zip(token_ids, token_strings)), "##")                                                  File "/home/optio/rasaprojects/rasaenv/lib/python3.6/site-packages/rasa/nlu/utils/hugging_face/transformers_pre_post_processors.py", line 26, in cleanup_tokens  token_ids, token_strings = zip(*token_ids_string)                                                               ValueError: not enough values to unpack (expected 2, got 0) 
```

**Command or request that led to error**:
```
rasa train
```

**Content of configuration file (config.yml)** (if relevant):
```yml
language: en
pipeline:
- name: HFTransformersNLP
  model_weights: "bert-base-uncased"
  model_name: "bert"
- name: LanguageModelTokenizer
- name: LanguageModelFeaturizer
- name: DIETClassifier
epochs: 50

policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: MappingPolicy

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @tmbo will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by giorgobiani** [comment]
Any update on this? I'm also interested
