### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'event_broker'

### ISSUE THREAD

**Issue by azizHakim** [RasaHQ/rasa#5625]
**Rasa version**: 1.9.5, 1.8.1

**Python version**:3.7.6

**Operating system** : windows 10

**Issue**:I am trying to run my bot on cmdline but getting this error:

`AttributeError: 'NoneType' object has no attribute 'event_broker'`

I tried both rasa 1.9.5 and 1.8.1, same error occured 

**Error (including full traceback)**:
```
2020-04-14 10:48:54.432403: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-04-14 10:48:54.436767: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-04-14 10:48:57.160293: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2020-04-14 10:48:57.852489: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1555] Found device 0 with properties:
pciBusID: 0000:01:00.0 name: GeForce GTX 850M computeCapability: 5.0
coreClock: 0.9015GHz coreCount: 5 deviceMemorySize: 2.00GiB deviceMemoryBandwidth: 29.83GiB/s
2020-04-14 10:48:57.863760: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-04-14 10:48:57.868972: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cublas64_10.dll'; dlerror: cublas64_10.dll not found
2020-04-14 10:48:57.877842: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cufft64_10.dll'; dlerror: cufft64_10.dll not found
2020-04-14 10:48:57.901995: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'curand64_10.dll'; dlerror: curand64_10.dll not found
2020-04-14 10:48:57.923159: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cusolver64_10.dll'; dlerror: cusolver64_10.dll not found
2020-04-14 10:48:57.945602: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cusparse64_10.dll'; dlerror: cusparse64_10.dll not found
2020-04-14 10:48:57.967191: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudnn64_7.dll'; dlerror: cudnn64_7.dll not found
2020-04-14 10:48:57.980543: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1592] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2020-04-14 10:48:58.007757: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-04-14 10:48:58.026652: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1096] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-04-14 10:48:58.038063: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1102]
WARNING:tensorflow:From C:\Users\Raihan\Anaconda3\envs\rsx\lib\site-packages\tensorflow_core\python\ops\array_grad.py:563: _EagerTensorBase.cpu (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.identity instead.
2020-04-14 10:48:59.390469: W tensorflow/core/kernels/data/generator_dataset_op.cc:103] Error occurred when finalizing GeneratorDataset iterator: Cancelled: Operation was cancelled
C:\Users\Raihan\Anaconda3\envs\rsx\lib\site-packages\rasa\core\policies\keras_policy.py:265: FutureWarning: 'KerasPolicy' is deprecated and will be removed in version 2.0. Use 'TEDPolicy' instead.
  current_epoch=meta["epochs"],
[2020-04-14 10:49:04 +0600] [6920] [ERROR] Experienced exception while trying to serve
Traceback (most recent call last):
  File "C:\Users\Raihan\Anaconda3\envs\rsx\lib\site-packages\sanic\app.py", line 1167, in run
    serve(**server_settings)
  File "C:\Users\Raihan\Anaconda3\envs\rsx\lib\site-packages\sanic\server.py", line 892, in serve
    trigger_events(before_start, loop)
  File "C:\Users\Raihan\Anaconda3\envs\rsx\lib\site-packages\sanic\server.py", line 668, in trigger_events
    loop.run_until_complete(result)
  File "C:\Users\Raihan\Anaconda3\envs\rsx\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\Users\Raihan\Anaconda3\envs\rsx\lib\site-packages\rasa\core\run.py", line 244, in load_agent_on_start
    _broker = EventBroker.create(endpoints.event_broker)
AttributeError: 'NoneType' object has no attribute 'event_broker'
Traceback (most recent call last):
  File "r.py", line 58, in <module>
    run()
  File "r.py", line 55, in run
    rasa.core.run.serve_application(agent,channel='rest')
  File "C:\Users\Raihan\Anaconda3\envs\rsx\lib\site-packages\rasa\core\run.py", line 217, in serve_application
    endpoints.lock_store if endpoints else None
  File "C:\Users\Raihan\Anaconda3\envs\rsx\lib\site-packages\sanic\app.py", line 1167, in run
    serve(**server_settings)
  File "C:\Users\Raihan\Anaconda3\envs\rsx\lib\site-packages\sanic\server.py", line 892, in serve
    trigger_events(before_start, loop)
  File "C:\Users\Raihan\Anaconda3\envs\rsx\lib\site-packages\sanic\server.py", line 668, in trigger_events
    loop.run_until_complete(result)
  File "C:\Users\Raihan\Anaconda3\envs\rsx\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "C:\Users\Raihan\Anaconda3\envs\rsx\lib\site-packages\rasa\core\run.py", line 244, in load_agent_on_start
    _broker = EventBroker.create(endpoints.event_broker)
AttributeError: 'NoneType' object has no attribute 'event_broker'
sys:1: RuntimeWarning: coroutine 'BaseEventLoop.create_server' was never awaited
```

**Command or request that led to error**:
```
def run(dbug=False):
    if dbug:
        init_debug_logging()
    interpreter = RasaNLUInterpreter('./model_save/final/nlu')
    action_endpoint = EndpointConfig(url="http://localhost:5056/webhook")
    agent = Agent.load("model_save/final", interpreter=interpreter,action_endpoint=action_endpoint)
    rasa.core.run.serve_application(agent,channel='rest')

if __name__== "__main__":
    run()
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @dakshvar22 will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by degiz** [comment]
Hey @azizHakim 

> I am trying to run my bot on cmdline

Few questions:
- What command are you using?
- Are you using clean venv to run Rasa?

**Comment by azizHakim** [comment]
I am trying `python run.py`
I have created a clean conda environment to run rasa and rasa x.

**Comment by degiz** [comment]
Hey @azizHakim 

Is there a reason you want to use `run()` directly? 
According to the log you don't have the configuration files in place. 

Could you try to first run:
`rasa init --no-prompt`
This will make sure you have proper configs to start working with the bot.
