### ISSUE TITLE
rasa x command error

### ISSUE THREAD

**Issue by sheggamharshith** [RasaHQ/rasa#5795]
**Rasa version**:

1.10.0
**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):
0.22
**Python version**:
3.6

**Operating system** (windows, osx, ...):
Mac OS

**Issue**:
2020-05-08 19:30:27 ERROR    sanic.root  - Unable to start server
Traceback (most recent call last):
  File "/opt/anaconda3/envs/rasa/lib/python3.6/site-packages/sanic/server.py", line 860, in serve
    http_server = loop.run_until_complete(server_coroutine)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1727, in create_server
OSError: [Errno 48] error while attempting to bind on address ('0.0.0.0', 5002): address already in use
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/anaconda3/envs/rasa/lib/python3.6/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/opt/anaconda3/envs/rasa/lib/python3.6/multiprocessing/spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
  File "/opt/anaconda3/envs/rasa/lib/python3.6/multiprocessing/synchronize.py", line 110, in __setstate__
    self._semlock = _multiprocessing.SemLock._rebuild(*state)
FileNotFoundError: [Errno 2] No such file or directory

**Error (including full traceback)**:
```

```

**Command or request that led to error**:
```
rasa x
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sheggamharshith** [comment]
if I restarted  and run  the command 
> rasa x 
and train a model the error pops up
Training Core model...
2020-05-08 19:39:09 ERROR    rasax.community.api.blueprints.models  - 500, message='Internal Server Error', url=URL('http://localhost:5005/model/train')

is that. a port problem or should I change any code

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @erohmensing will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by erohmensing** [comment]
Hey there @sheggamharshith, Rasa 1.10 is incompatible with Rasa X 0.22. Please see the compatiblity matrix here: https://rasa.com/docs/rasa-x/changelog/compatibility-matrix/

Can I ask why you decided to install Rasa X locally instead of via one of our [recommended deployment methods](https://rasa.com/docs/rasa/user-guide/how-to-deploy/#recommended-deployment-methods)?

**Comment by sheggamharshith** [comment]
@erohmensing  thanks for the compatibility matrix i have resolved the issue  mam i was just checking it
