### ISSUE TITLE
 ConveRTTokenizer and ConveRTFeaturizer not able to train

### ISSUE THREAD

**Issue by robotmentor88** [RasaHQ/rasa#5858]
**Rasa version**:
1.10.1 

**Rasa SDK version** (if used & relevant):
 1.10.1   

**Rasa X version** (if used & relevant):

**Python version**:
3.7.3

**Operating system** (windows, osx, ...):
OSX
**Issue**:
Not able to train ConveRTTokenizer and ConveRTFeaturizer recommended pipeline.
It first said that tensorflow_text was missing. Installed tensorflow_text using command:
pip install --no-deps tensorflow_text
Now the error is different.

**Error (including full traceback)**:
```
2020-05-19 17:16:48 INFO     rasa.model  - Data (version) for Core model section changed.
2020-05-19 17:16:48 INFO     rasa.model  - Data (nlu-config) for NLU model section changed.
Training Core model...
Processed Story Blocks: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 35/35 [00:00<00:00, 1407.93it/s, # trackers=1]
Processed Story Blocks: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 35/35 [00:00<00:00, 47.36it/s, # trackers=35]
Processed Story Blocks: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 35/35 [00:01<00:00, 30.91it/s, # trackers=45]
Processed Story Blocks: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 35/35 [00:01<00:00, 19.45it/s, # trackers=47]
Processed trackers: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 35/35 [00:00<00:00, 1012.82it/s, # actions=110]
Processed actions: 110it [00:00, 7830.24it/s, # examples=110]
Processed trackers: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 535/535 [00:01<00:00, 512.92it/s, # actions=1556]
Epochs: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [02:10<00:00,  1.31s/it, t_loss=0.156, loss=0.008, acc=1.000]
2020-05-19 17:19:10 INFO     rasa.utils.tensorflow.models  - Finished training.
Processed trackers: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 35/35 [00:00<00:00, 1613.42it/s, # actions=107]
2020-05-19 17:19:11 INFO     rasa.core.agent  - Persisted model to '/var/folders/dq/c4dxqx0n523496rd2zvw3fkm0000gn/T/tmponuikurs/core'
Core model training completed.
Training NLU model...
Traceback (most recent call last):
  File "/Users/.virtualenvs/rasa_test_v1/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/Users/.virtualenvs/rasa_test_v1/lib/python3.7/site-packages/rasa/__main__.py", line 91, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/Users/.virtualenvs/rasa_test_v1/lib/python3.7/site-packages/rasa/cli/train.py", line 76, in train
    additional_arguments=extract_additional_arguments(args),
  File "/Users/.virtualenvs/rasa_test_v1/lib/python3.7/site-packages/rasa/train.py", line 50, in train
    additional_arguments=additional_arguments,
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/Users/.virtualenvs/rasa_test_v1/lib/python3.7/site-packages/rasa/train.py", line 101, in train_async
    additional_arguments,
  File "/Users/.virtualenvs/rasa_test_v1/lib/python3.7/site-packages/rasa/train.py", line 188, in _train_async_internal
    additional_arguments=additional_arguments,
  File "/Users/.virtualenvs/rasa_test_v1/lib/python3.7/site-packages/rasa/train.py", line 245, in _do_training
    persist_nlu_training_data=persist_nlu_training_data,
  File "/Users/.virtualenvs/rasa_test_v1/lib/python3.7/site-packages/rasa/train.py", line 482, in _train_nlu_with_validated_data
    persist_nlu_training_data=persist_nlu_training_data,
  File "/Users/.virtualenvs/rasa_test_v1/lib/python3.7/site-packages/rasa/nlu/train.py", line 75, in train
    trainer = Trainer(nlu_config, component_builder)
  File "/Users/.virtualenvs/rasa_test_v1/lib/python3.7/site-packages/rasa/nlu/model.py", line 142, in __init__
    components.validate_requirements(cfg.component_names)
  File "/Users/.virtualenvs/rasa_test_v1/lib/python3.7/site-packages/rasa/nlu/components.py", line 53, in validate_requirements
    find_unavailable_packages(component_class.required_packages())
  File "/Users/.virtualenvs/rasa_test_v1/lib/python3.7/site-packages/rasa/nlu/components.py", line 33, in find_unavailable_packages
    importlib.import_module(package)
  File "/usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/.virtualenvs/rasa_test_v1/lib/python3.7/site-packages/tensorflow_text/__init__.py", line 21, in <module>
    from tensorflow_text.python import metrics
  File "/Users/.virtualenvs/rasa_test_v1/lib/python3.7/site-packages/tensorflow_text/python/metrics/__init__.py", line 20, in <module>
    from tensorflow_text.python.metrics.text_similarity_metric_ops import *
  File "/Users/.virtualenvs/rasa_test_v1/lib/python3.7/site-packages/tensorflow_text/python/metrics/text_similarity_metric_ops.py", line 28, in <module>
    gen_text_similarity_metric_ops = load_library.load_op_library(resource_loader.get_path_to_datafile('_text_similarity_metric_ops.dylib'))
  File "/Users/.virtualenvs/rasa_test_v1/lib/python3.7/site-packages/tensorflow_core/python/framework/load_library.py", line 57, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: dlopen(/Users/.virtualenvs/rasa_test_v1/lib/python3.7/site-packages/tensorflow_text/python/metrics/_text_similarity_metric_ops.dylib, 6): Symbol not found: __ZN10tensorflow8OpKernel11TraceStringEPNS_15OpKernelContextEb
  Referenced from: /Users/.virtualenvs/rasa_test_v1/lib/python3.7/site-packages/tensorflow_text/python/metrics/_text_similarity_metric_ops.dylib (which was built for Mac OS X 10.15)
  Expected in: /Users/.virtualenvs/rasa_test_v1/lib/python3.7/site-packages/tensorflow_core/python/../libtensorflow_framework.2.dylib
 in /Users/.virtualenvs/rasa_test_v1/lib/python3.7/site-packages/tensorflow_text/python/metrics/_text_similarity_metric_ops.dylib

```

**Command or request that led to error**:
```
rasa train
```

**Content of configuration file (config.yml)** (if relevant):
```yml
language: en
pipeline:
  - name: ConveRTTokenizer
  - name: ConveRTFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DucklingHTTPExtractor
    url: http://localhost:8000
    dimensions:
    - number
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by robotmentor88** [comment]
It was a Mac upgrade issue. Upgraded to latest OS version and it is fine now.
