### ISSUE TITLE
Problem with Telegram channel

### ISSUE THREAD

**Issue by petasis** [RasaHQ/rasa#5864]
**Rasa version**:
Rasa 1.10.0
**Rasa SDK version** (if used & relevant):
rasa-sdk:1.10.0
**Rasa X version** (if used & relevant):

**Python version**:
Python 3.7.7
**Operating system** (windows, osx, ...):
Linux
**Issue**:

I am getting multiple errors like below, and I notice unstable behaviour in the telegram client. Most of the times I get responses, but other times I get no responses, or mixed responses from previous questions.

**Error (including full traceback)**:
```
Exception occurred while handling uri: 'http://localhost:5005/webhooks/telegram/webhook'
Traceback (most recent call last):
  File "/opt/venv/lib/python3.7/site-packages/sanic/app.py", line 976, in handle_request
    response = await response
  File "/opt/venv/lib/python3.7/site-packages/rasa/core/channels/telegram.py", line 215, in message
    if self._is_user_message(msg):
  File "/opt/venv/lib/python3.7/site-packages/rasa/core/channels/telegram.py", line 175, in _is_user_message
    return message.text is not None
AttributeError: 'NoneType' object has no attribute 'text'
Exception occurred while handling uri: 'http://localhost:5005/webhooks/telegram/webhook'
Traceback (most recent call last):
  File "/opt/venv/lib/python3.7/site-packages/sanic/app.py", line 976, in handle_request
    response = await response
  File "/opt/venv/lib/python3.7/site-packages/rasa/core/channels/telegram.py", line 215, in message
    if self._is_user_message(msg):
  File "/opt/venv/lib/python3.7/site-packages/rasa/core/channels/telegram.py", line 175, in _is_user_message
    return message.text is not None
AttributeError: 'NoneType' object has no attribute 'text'
```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @dakshvar22 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by petasis** [comment]
I have upgraded t rasa 1.10.1 and now telegram channel does not work at all :-(

**Comment by beliboba** [comment]
same

**Comment by beliboba** [comment]
In my case bot is answering to message only if it starts witgh "/start" in groups
