### ISSUE TITLE
rasa 1.10.1 - telegram in loop after upgrade rasa  - telegram.error.BadRequest: Message must be non-empty

### ISSUE THREAD

**Issue by snpr25** [RasaHQ/rasa#5870]
**Rasa version**:1.10.1

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**:3.6

**Operating system** (windows, osx, ...):linux ubuntu

**Issue**: 
I was so happy with rasa , then boom after upgrade to 1.10.1
my channel telegram start to behave in a loop fashion , my clients just freak out.
the web channel is normal.
please help

after update telegram loop messages
telegram.error.BadRequest: Message must be non-empty

**Error (including full traceback)**:
```
2020-05-21 05:24:43 ERROR    rasa.core.channels.telegram  - Exception when trying to handle message.Message must be non-empty
2020-05-21 05:24:43 DEBUG    rasa.core.channels.telegram  - Message must be non-empty
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/rasa/core/channels/telegram.py", line 252, in message
    metadata=metadata,
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/rasa/core/channels/channel.py", line 83, in handler
    await app.agent.handle_message(*args, **kwargs)
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/rasa/core/agent.py", line 486, in handle_message
    return await processor.handle_message(message)
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/rasa/core/processor.py", line 108, in handle_message
    await self._predict_and_execute_next_action(message.output_channel, tracker)
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/rasa/core/processor.py", line 552, in _predict_and_execute_next_action
    action, tracker, output_channel, self.nlg, policy, confidence
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/rasa/core/processor.py", line 665, in _run_action
    await self._send_bot_messages(events, tracker, output_channel)
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/rasa/core/processor.py", line 594, in _send_bot_messages
    await output_channel.send_response(tracker.sender_id, e.message())
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/rasa/core/channels/channel.py", line 183, in send_response
    recipient_id, message.pop("text"), message.pop("buttons"), **message
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/rasa/core/channels/telegram.py", line 94, in send_text_with_buttons
    self.send_message(recipient_id, text, reply_markup=reply_markup)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/telegram/bot.py", line 65, in decorator
    result = func(self, *args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/telegram/bot.py", line 90, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/telegram/utils/request.py", line 309, in post
    headers={'Content-Type': 'application/json'})
  File "/home/ubuntu/.local/lib/python3.6/site-packages/telegram/utils/request.py", line 223, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Message must be non-empty

```

**Command or request that led to error**:
```
chat in channel telegram

```

**Content of configuration file (config.yml)** (if relevant):
```

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by petasis** [comment]
I have started facing problems in the telegram channel a couple of days ago. Upgrading to 10.0.1 stopped working completely. I have opened a bug in #5864, although the messages I see in the log are different.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @erohmensing will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by benos** [comment]
I think it is a duplicate of https://github.com/RasaHQ/rasa/issues/5654
