### ISSUE TITLE
Python 3.5 Issue

### ISSUE THREAD

**Issue by shotamakino** [RasaHQ/rasa#5883]
**Rasa version**: 1.3.10

**Python version**: 3.5.6

**Operating system** (windows, osx, ...): OSX 10.15.4

**Issue**: Running rasa shell / rasa train (only tested these 2 cli commands, may include more) causes syntax errors.

My installation steps:
1. ```conda create -n py35 python=3.5```
1. ```conda activate py35```
1. ```export MACOSX_DEPLOYMENT_TARGET=10.9```
1. ```pip install rasa```

When installing on OSX 10.15.4, I had to set a variable before running `pip install rasa` in order for the build to run against libc++ as referenced here: https://stackoverflow.com/questions/56083725/macos-build-issues-lstdc-not-found-while-building-python-package

The variable set was ```export MACOSX_DEPLOYMENT_TARGET=10.9```

**Error (including full traceback)**:

rasa shell: 
```
Traceback (most recent call last):
  File "/Users/shota/anaconda3/envs/py35/bin/rasa", line 11, in <module>
    sys.exit(main())
  File "/Users/shota/anaconda3/envs/py35/lib/python3.5/site-packages/rasa/__main__.py", line 76, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/Users/shota/anaconda3/envs/py35/lib/python3.5/site-packages/rasa/cli/shell.py", line 101, in shell
    rasa.cli.run.run(args)
  File "/Users/shota/anaconda3/envs/py35/lib/python3.5/site-packages/rasa/cli/run.py", line 116, in run
    rasa.run(**vars(args))
  File "/Users/shota/anaconda3/envs/py35/lib/python3.5/site-packages/rasa/run.py", line 34, in run
    import rasa.core.run
  File "/Users/shota/anaconda3/envs/py35/lib/python3.5/site-packages/rasa/core/run.py", line 15, in <module>
    from rasa import server
  File "/Users/shota/anaconda3/envs/py35/lib/python3.5/site-packages/rasa/server.py", line 14, in <module>
    from sanic_jwt import Initialize, exceptions
  File "/Users/shota/anaconda3/envs/py35/lib/python3.5/site-packages/sanic_jwt/__init__.py", line 7, in <module>
    from .authentication import Authentication
  File "/Users/shota/anaconda3/envs/py35/lib/python3.5/site-packages/sanic_jwt/authentication.py", line 117
    **kwargs,
            ^
SyntaxError: invalid syntax
```
rasa train:

```
Traceback (most recent call last):
  File "/Users/shota/anaconda3/envs/py35/bin/rasa", line 11, in <module>
    sys.exit(main())
  File "/Users/shota/anaconda3/envs/py35/lib/python3.5/site-packages/rasa/__main__.py", line 76, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/Users/shota/anaconda3/envs/py35/lib/python3.5/site-packages/rasa/cli/train.py", line 75, in train
    kwargs=extract_additional_arguments(args),
  File "/Users/shota/anaconda3/envs/py35/lib/python3.5/site-packages/rasa/train.py", line 40, in train
    kwargs=kwargs,
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/Users/shota/anaconda3/envs/py35/lib/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception
  File "/Users/shota/anaconda3/envs/py35/lib/python3.5/asyncio/tasks.py", line 240, in _step
    result = coro.send(None)
  File "/Users/shota/anaconda3/envs/py35/lib/python3.5/site-packages/rasa/train.py", line 91, in train_async
    kwargs,
  File "/Users/shota/anaconda3/envs/py35/lib/python3.5/site-packages/rasa/train.py", line 175, in _train_async_internal
    kwargs=kwargs,
  File "/Users/shota/anaconda3/envs/py35/lib/python3.5/site-packages/rasa/train.py", line 210, in _do_training
    kwargs=kwargs,
  File "/Users/shota/anaconda3/envs/py35/lib/python3.5/site-packages/rasa/train.py", line 339, in _train_core_with_validated_data
    kwargs=kwargs,
  File "/Users/shota/anaconda3/envs/py35/lib/python3.5/site-packages/rasa/core/train.py", line 33, in train
    from rasa.core.agent import Agent
  File "/Users/shota/anaconda3/envs/py35/lib/python3.5/site-packages/rasa/core/agent.py", line 16, in <module>
    from rasa.core.channels.channel import InputChannel, OutputChannel, UserMessage
  File "/Users/shota/anaconda3/envs/py35/lib/python3.5/site-packages/rasa/core/channels/__init__.py", line 21, in <module>
    from rasa.core.channels.mattermost import MattermostInput  # nopep8
  File "/Users/shota/anaconda3/envs/py35/lib/python3.5/site-packages/rasa/core/channels/mattermost.py", line 2, in <module>
    from mattermostwrapper import MattermostAPI
  File "/Users/shota/anaconda3/envs/py35/lib/python3.5/site-packages/mattermostwrapper/__init__.py", line 1, in <module>
    from .wrapper import MattermostAPI
  File "/Users/shota/anaconda3/envs/py35/lib/python3.5/site-packages/mattermostwrapper/wrapper.py", line 89
    print(f"The post channel token is: {self.token}")
                                                   ^
SyntaxError: invalid syntax
```

**Command or request that led to error**:
```
rasa shell
rasa train
```

**Content of configuration file (config.yml)** (if relevant):
```yml
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline: supervised_embeddings

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy
```

**Content of domain file (domain.yml)** (if relevant):
```yml
intents:
  - greet
  - goodbye
  - affirm
  - deny
  - mood_great
  - mood_unhappy

actions:
- utter_greet
- utter_cheer_up
- utter_did_that_help
- utter_happy
- utter_goodbye

templates:
  utter_greet:
  - text: "Hey {name}! How are you?"

  utter_cheer_up:
  - text: "Here is something to cheer you up:"
    image: "https://i.imgur.com/nGF1K8f.jpg"

  utter_did_that_help:
  - text: "Did that help you?"

  utter_happy:
  - text: "Great carry on!"

  utter_goodbye:
  - text: "Bye"

```

**Comment by shotamakino** [comment]
Attempted a fresh install in a new conda environment again and this time I was successfully installed rasa without the ```export MACOSX_DEPLOYMENT_TARGET=10.9```. Not sure what the issue was with that. The issue above with `rasa shell` and `rasa train` is still present.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @wochinge will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by wochinge** [comment]
@shotamakino Rasa Open Source is not compatible with Python 3.5. Please use Python 3.6 or Python 3.7.
