### ISSUE TITLE
"AttributeError: 'list' object has no attribute 'get'" in rasa/nlu/training_data/loading.py l39

### ISSUE THREAD

**Issue by meelie** [RasaHQ/rasa#5896]
**Rasa version**: Rasa 1.10.1

**Python version**: Python 3.7.0

**Operating system** (windows, osx, ...): Ubuntu

**Issue**:  "AttributeError: 'list' object has no attribute 'get'" in rasa/nlu/training_data/loading.py l39 when running `rasa train nlu`. When i comment this line, the training works as expected

Previous steps
```
pip install --update pip
python3 -m venv ./venv
source ./venv/bin/activate
pip install -U spacy
python3 -c "import spacy"
python -m spacy download fr_core_news_md
python -m spacy link fr_core_news_md fr
pip install rasa
rasa init
rm -r data/*
mv unzippedDFFolder data/
rasa data convert nlu --data data/unzippedDFFolder --out data/nlu.md --format md -l fr-fr
rasa train nlu
```
unzippedDFFolder is an export from a multilocale (en, en-us, fr, fr-fr, fr-ca) DialogFlow agent

**Error (including full traceback)**:
```
Traceback (most recent call last):
  File "/var/www/yelda_staging/venv/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/var/www/yelda_staging/venv/lib/python3.7/site-packages/rasa/__main__.py", line 91, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/var/www/yelda_staging/venv/lib/python3.7/site-packages/rasa/cli/train.py", line 140, in train_nlu
    persist_nlu_training_data=args.persist_nlu_data,
  File "/var/www/yelda_staging/venv/lib/python3.7/site-packages/rasa/train.py", line 414, in train_nlu
    persist_nlu_training_data,
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/var/www/yelda_staging/venv/lib/python3.7/site-packages/rasa/train.py", line 436, in _train_nlu_async
    config, training_data_paths=[nlu_data]
  File "/var/www/yelda_staging/venv/lib/python3.7/site-packages/rasa/importers/importer.py", line 111, in load_nlu_importer_from_config
    config_path, domain_path, training_data_paths
  File "/var/www/yelda_staging/venv/lib/python3.7/site-packages/rasa/importers/importer.py", line 81, in load_from_config
    config, config_path, domain_path, training_data_paths
  File "/var/www/yelda_staging/venv/lib/python3.7/site-packages/rasa/importers/importer.py", line 139, in load_from_dict
    RasaFileImporter(config_path, domain_path, training_data_paths)
  File "/var/www/yelda_staging/venv/lib/python3.7/site-packages/rasa/importers/rasa.py", line 36, in __init__
    training_data_paths
  File "/var/www/yelda_staging/venv/lib/python3.7/site-packages/rasa/data.py", line 92, in get_core_nlu_files
    path
  File "/var/www/yelda_staging/venv/lib/python3.7/site-packages/rasa/data.py", line 113, in _find_core_nlu_files_in_directory
    if is_nlu_file(full_path):
  File "/var/www/yelda_staging/venv/lib/python3.7/site-packages/rasa/data.py", line 137, in is_nlu_file
    return loading.guess_format(file_path) != loading.UNK
  File "/var/www/yelda_staging/venv/lib/python3.7/site-packages/rasa/nlu/training_data/loading.py", line 172, in guess_format
    if format_heuristic(js, filename):
  File "/var/www/yelda_staging/venv/lib/python3.7/site-packages/rasa/nlu/training_data/loading.py", line 39, in <lambda>
    WIT: lambda js, fn: "data" in js and isinstance(js.get("data"), list),
AttributeError: 'list' object has no attribute 'get'
```

**Command or request that led to error**:
```
rasa train nlu
```

**Content of configuration file (config.yml)** (if relevant):
```yml
language: "fr"  # your two-letter language code

pipeline:
  - name: SpacyNLP
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @rctatman will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by rasadeveloper** [comment]
@meelie Did you find any solution to this?
I am also having the same issue.!

**Comment by meelie** [comment]
Hi @rasadeveloper,
As said in the issue description, when i comment this line (rasa/nlu/training_data/loading.py l39)  the training works as expected.
But that's just a local workaround. Unfortunately I am not a python developer so I did not dig more.
