### ISSUE TITLE
Rasa x Interactive Learning Broken  - ConversationCreationFailed 

### ISSUE THREAD

**Issue by chris-aeviator** [RasaHQ/rasa#5919]
**Rasa version**: latest

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):
latest
**Python version**:
supplied by provided Docker Image
**Operating system** (windows, osx, ...):
Ubuntu
**Issue**:

When setting up or working with Rasa X I encountered this issue on multiple systems (all Linux based though) and on different occasions of a projects maturity.

It seems as when not everything is correctly setup between the various tabs for setting a model (Stories, Domain, Config, ...), even though there might not be an error displayed by the rasa x UI, rasa-x is not working as expected. Whenever the environment is in the state where rasa x sucessfully builds and let me activate a model, but the currently unknown error state is present, the "Interactive Learning" page is missing it's chat window. Also stories cannot be added via 'Add new' or as described 'Add via interactive' learning, but I am able to upload them as a markdown file

![image](https://user-images.githubusercontent.com/11522213/83318990-584b9880-a264-11ea-9b74-f665adbc8752.png)

**Error (including full traceback)**:

No Errors in Rasa X UI, No errors on `rasa-production` (via provided docker-compose file)
Browser Network tab shows for `/api/conversations` but no error is logged in rasa-production
```
{"JSON":{"version":"0.28.1","status":"failure","message":"Error while trying to create conversation.","reason":"ConversationCreationFailed","details":"500, message='Internal Server Error', url=URL('http://rasa-production:5005/conversations/27c0330712fd4d7ea182b0b17745f8ad/tracker/events?token={I replaced this}%3D%3D')","help":null,"code":422}}
```

Doing a `curl rasa-production:5005
Hello from Rasa: 1.10.0` from the rasa-x container show's that it is accessible. How can I debug 
**Command or request that led to error**:
Post to `/api/conversations` done by rasa-x when visiting rasa-x `/interactive` page

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

1. How can I debug rasa-x (production), since an 500 error is thrown but not displayed by rasa-production (rasa-x docker)
2. how can I find out my config is in an instable state withouth having to rely on a UI part working or not 

EDIT: I'm running the same project flawlessly on a dev machine, when uploading the stories.md, domain., .... to a freshly setup production environment (both are running the same prod config) just the newly deployed behaves like this, also an update to 0.28.5 does not yield in any other behav.

**Comment by chris-aeviator** [comment]
I have found out (by adding a `--debug` flag to defaulf-rasa-service) that redis seems to be the issue, since it complains about `redis.exceptions.AuthenticationError: Client sent AUTH, but no password is set` - rasa is part of a bigger docker network, I will check if another redis instance is competing.

**Comment by yellybeans** [comment]
Hey, I am facing a similar problem. How did you fix it?

**Comment by chris-aeviator** [comment]
setting `--debug` as a CLI parameter will print what's going wrong. Verbosity here is high, so you'll need to carefully scroll through many lines of logs for a single event. Everytime interactive learning is broken it turned out to be a rasa error that will show up with the debug flag. Nontheless I think rasa-x performs very poorly here in not showing any error and it's an issue that should be adressed.

**Comment by yellybeans** [comment]
okay, so I am working on an aws ec2 instance and left out the -d flag when starting docker-compose to get the logs (right?). There are coming lots of warnings and errors :( ... In the startup process comes:
```
rasa-x_1           | Starting Rasa X server... 🚀
rasa-x_1           | /usr/local/lib/python3.7/site-packages/rasax/community/services/test_service.py:43: UserWarning: Unable to get tests from tests/conversation_tests.md:
rasa-x_1           | File 'tests/conversation_tests.md' does not exist. Please, make sure you have end-to-end tests added to your assistant. See https://rasa.com/docs/rasa/user-guide/testing-your-assistant/ for more information.
rasa-x_1           |   UserWarning,
rabbit_1           | Waiting for erlang distribution on node 'rabbit@localhost' while OS process '45' is running
rasa-worker_1      | /opt/venv/lib/python3.7/site-packages/rasa/core/brokers/pika.py:294: FutureWarning: Your Pika event broker config contains the deprecated `queue` key. Please use the `queues` key instead.
rasa-worker_1      |   self.queues = self._get_queues_from_args(queues, kwargs)
rasa-worker_1      | 2020-06-19 11:56:40 ERROR    pika.adapters.utils.io_services_utils  - Socket failed to connect: <socket.socket fd=21, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.20.0.8', 48176)>; error=111 (Connection refused)
rasa-worker_1      | 2020-06-19 11:56:40 ERROR    pika.adapters.utils.connection_workflow  - TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection refused'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('172.20.0.2', 5672))
rasa-worker_1      | 2020-06-19 11:56:40 ERROR    pika.adapters.utils.connection_workflow  - AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')
db_1               | 2020-06-19 11:56:40.881 GMT [174] WARNING:  there is no transaction in progress
rabbit_1           | Waiting for applications 'rabbit_and_plugins' to start on node 'rabbit@localhost'
rasa-production_1  | /opt/venv/lib/python3.7/site-packages/rasa/core/brokers/pika.py:294: FutureWarning: Your Pika event broker config contains the deprecated `queue` key. Please use the `queues` key instead.
rasa-production_1  |   self.queues = self._get_queues_from_args(queues, kwargs)
rasa-production_1  | 2020-06-19 11:56:41 ERROR    pika.adapters.utils.io_services_utils  - Socket failed to connect: <socket.socket fd=21, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.20.0.7', 59878)>; error=111 (Connection refused)
rasa-production_1  | 2020-06-19 11:56:41 ERROR    pika.adapters.utils.connection_workflow  - TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection refused'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('172.20.0.2', 5672))
rasa-production_1  | 2020-06-19 11:56:41 ERROR    pika.adapters.utils.connection_workflow  - AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')
db_1               | 2020-06-19 11:56:41.821 GMT [176] WARNING:  there is no transaction in progress
rabbit_1           | Applications 'rabbit_and_plugins' are running on node 'rabbit@localhost'
rasa-worker_1      | 2020-06-19 11:56:45 ERROR    pika.connection  - Connection closed while authenticating indicating a probable authentication error
rasa-worker_1      | 2020-06-19 11:56:45 WARNING  rasa.core.brokers.pika  - Connecting to 'rabbit' failed with error 'ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.''. Trying again.
rasa-worker_1      | 2020-06-19 11:56:45 ERROR    pika.adapters.utils.connection_workflow  - AMQPConnector - reporting failure: AMQPConnectorAMQPHandshakeError: ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",)
rasa-worker_1      | 2020-06-19 11:56:45 ERROR    pika.adapters.utils.connection_workflow  - AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 2 exceptions in all; last exception - AMQPConnectorAMQPHandshakeError: ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",); first exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')
rasa-worker_1      | 2020-06-19 11:56:45 ERROR    pika.adapters.base_connection  - Full-stack connection workflow failed: AMQPConnectionWorkflowFailed: 2 exceptions in all; last exception - AMQPConnectorAMQPHandshakeError: ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",); first exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')
rasa-worker_1      | 2020-06-19 11:56:45 ERROR    pika.adapters.base_connection  - Self-initiated stack bring-up failed: AMQPConnectionWorkflowFailed: 2 exceptions in all; last exception - AMQPConnectorAMQPHandshakeError: ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",); first exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')
rabbit_1           |  11:56:46.68 ERROR ==> Couldn't change password for user 'user'.
rabbit_1           |  11:56:46.69 INFO  ==> Stopping RabbitMQ...
rasa-production_1  | 2020-06-19 11:56:46 ERROR    pika.connection  - Connection closed while authenticating indicating a probable authentication error
rasa-production_1  | 2020-06-19 11:56:46 WARNING  rasa.core.brokers.pika  - Connecting to 'rabbit' failed with error 'ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.''. Trying again.
rasa-production_1  | 2020-06-19 11:56:46 ERROR    pika.adapters.utils.connection_workflow  - AMQPConnector - reporting failure: AMQPConnectorAMQPHandshakeError: ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",)
rasa-production_1  | 2020-06-19 11:56:46 ERROR    pika.adapters.utils.connection_workflow  - AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFailed: 2 exceptions in all; last exception - AMQPConnectorAMQPHandshakeError: ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",); first exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')
rasa-production_1  | 2020-06-19 11:56:46 ERROR    pika.adapters.base_connection  - Full-stack connection workflow failed: AMQPConnectionWorkflowFailed: 2 exceptions in all; last exception - AMQPConnectorAMQPHandshakeError: ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",); first exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')
rasa-production_1  | 2020-06-19 11:56:46 ERROR    pika.adapters.base_connection  - Self-initiated stack bring-up failed: AMQPConnectionWorkflowFailed: 2 exceptions in all; last exception - AMQPConnectorAMQPHandshakeError: ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",); first exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')
```
After that from rasa-x is coming from time to time:
```
rasa-x_1           | ERROR:rasax.community.services.event_service:Caught an exception while consuming events. Will retry in 5 s.
rasa-x_1           | Traceback (most recent call last):
rasa-x_1           |   File "/usr/local/lib/python3.7/site-packages/rasax/community/services/event_service.py", line 1633, in continuously_consume
rasa-x_1           |     endpoint_config, should_run_liveness_endpoint
rasa-x_1           |   File "/usr/local/lib/python3.7/site-packages/rasax/community/services/event_consumers/utils.py", line 45, in from_endpoint_config
rasa-x_1           |     broker_config, should_run_liveness_endpoint
rasa-x_1           |   File "/usr/local/lib/python3.7/site-packages/rasax/community/services/event_consumers/pika_consumer.py", line 73, in from_endpoint_config
rasa-x_1           |     should_run_liveness_endpoint=should_run_liveness_endpoint,
rasa-x_1           |   File "/usr/local/lib/python3.7/site-packages/rasax/community/services/event_consumers/pika_consumer.py", line 54, in __init__
rasa-x_1           |     host, self.queue, username, password, port
rasa-x_1           |   File "/usr/local/lib/python3.7/site-packages/rasa/core/brokers/pika.py", line 195, in initialise_pika_channel
rasa-x_1           |     host, username, password, port, connection_attempts, retry_delay_in_seconds
rasa-x_1           |   File "/usr/local/lib/python3.7/site-packages/rasa/core/brokers/pika.py", line 72, in initialise_pika_connection
rasa-x_1           |     return pika.BlockingConnection(parameters)
rasa-x_1           |   File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 359, in __init__
rasa-x_1           |     self._impl = self._create_connection(parameters, _impl_class)
rasa-x_1           |   File "/usr/local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 450, in _create_connection
rasa-x_1           |     raise self._reap_last_connection_workflow_error(error)
rasa-x_1           | pika.exceptions.ProbableAuthenticationError: ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'
```
and lots of these:
```
rabbit_1           | 2020-06-19 12:00:29.618 [info] <0.971.0> closing AMQP connection <0.971.0> (172.20.0.6:47490 -> 172.20.0.2:5672)
rabbit_1           | 2020-06-19 12:00:34.621 [info] <0.979.0> accepting AMQP connection <0.979.0> (172.20.0.6:47496 -> 172.20.0.2:5672)
rabbit_1           | 2020-06-19 12:00:34.622 [error] <0.979.0> Error on AMQP connection <0.979.0> (172.20.0.6:47496 -> 172.20.0.2:5672, state: starting):
rabbit_1           | PLAIN login refused: user 'user' - invalid credentials
```

I am really confused about where to start right now. You got any idea?

**Comment by chris-aeviator** [comment]
can you re-check that you a) have an unmodified `docker-compose.yml` file (check the one provided by rasa for comparasion), all manual changes should go to `docker-compose.override.yml`and b) have an .env file present in your folder (might be hidden)

**Comment by chris-aeviator** [comment]
https://rasa.com/docs/rasa-x/installation-and-setup/docker-compose-manual/ is listing all steps necessary, the only difference I made in successfully installing it with (Arch) Linux was using different folder mounts (I don't like to mix dev stuff with system files so I wont install in /etc/ )

**Comment by yellybeans** [comment]
okay, I just found the problem :D So after I followed the instructions from the manual installation it worked. Then i looked in the differences between the two and in the ```.env``` file one password was set that ended up with a .(dot) . I changed this password and now it works fine.

**Comment by chris-aeviator** [comment]
@yellybeans great to hear that!

**Comment by KoomeKiriinya** [comment]
Facing a similar issue as well. This are the logs of the rasa-worker service. Training the model fails once I click on train. Integration with github is successful.
```
rasa-worker_1      |   self.queues = self._get_queues_from_args(queues, kwargs)
rasa-worker_1      | 2020-10-11 16:41:44 ERROR    pika.adapters.utils.io_services_utils  - Socket failed to connect: <socket.socket fd=21, family=AddressFamily.AF_I
NET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.23.0.7', 50690)>; error=111 (Connection refused)
rasa-worker_1      | 2020-10-11 16:41:44 ERROR    pika.adapters.utils.connection_workflow  - TCP Connection attempt failed: ConnectionRefusedError(111, 'Connection 
refused'); dest=(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('172.23.0.4', 5672))
rasa-worker_1      | 2020-10-11 16:41:44 ERROR    pika.adapters.utils.connection_workflow  - AMQPConnector - reporting failure: AMQPConnectorSocketConnectError: Con
nectionRefusedError(111, 'Connection refused')
rasa-worker_1      | 2020-10-11 16:41:49 ERROR    pika.connection  - Connection closed while authenticating indicating a probable authentication error
rasa-worker_1      | 2020-10-11 16:41:49 WARNING  rasa.core.brokers.pika  - Connecting to 'rabbit' failed with error 'ConnectionClosedByBroker: (403) 'ACCESS_REFUSE
D - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.''. Trying again.
rasa-worker_1      | 2020-10-11 16:41:49 ERROR    pika.adapters.utils.connection_workflow  - AMQPConnector - reporting failure: AMQPConnectorAMQPHandshakeError: Pro
bableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSE
D - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",)
rasa-worker_1      | 2020-10-11 16:41:49 ERROR    pika.adapters.utils.connection_workflow  - AMQPConnectionWorkflow - reporting failure: AMQPConnectionWorkflowFaile
d: 2 exceptions in all; last exception - AMQPConnectorAMQPHandshakeError: ProbableAuthenticationError: Client was disconnected at a connection stage indicating a pr
obable authentication error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker 
logfile.'",); first exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')
rasa-worker_1      | 2020-10-11 16:41:49 ERROR    pika.adapters.base_connection  - Full-stack connection workflow failed: AMQPConnectionWorkflowFailed: 2 exceptions
 in all; last exception - AMQPConnectorAMQPHandshakeError: ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authenti
cation error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",); f
irst exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')
rasa-worker_1      | 2020-10-11 16:41:49 ERROR    pika.adapters.base_connection  - Self-initiated stack bring-up failed: AMQPConnectionWorkflowFailed: 2 exceptions 
in all; last exception - AMQPConnectorAMQPHandshakeError: ProbableAuthenticationError: Client was disconnected at a connection stage indicating a probable authentic
ation error: ("ConnectionClosedByBroker: (403) 'ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.'",); fi
rst exception - AMQPConnectorSocketConnectError: ConnectionRefusedError(111, 'Connection refused')
```

**Comment by KoomeKiriinya** [comment]
.env file
```
RASA_X_VERSION=0.32.2
RASA_VERSION=1.10.14
RASA_TOKEN=suBP9KVhbTNEr9iEcsbzFw==
RASA_X_DEMO_VERSION=0.26.0
RASA_X_TOKEN=bAf7SswMXy2oZ92pY51/6w==
PASSWORD_SALT=+0GA46N8MiQuIv/hM+JMhQ==
JWT_SECRET=+RD22PJC6E20QQDkImRaiQ==
RABBITMQ_PASSWORD=HnqZ3v4vghA0TBQ2PtZV3g==
DB_PASSWORD=UqjQkNQUcG9YyU9vWwEkaw==
REDIS_PASSWORD=Ao/2DK5ic7OfrK0c/uc2aw==
```

**Comment by KoomeKiriinya** [comment]
environments.yml file
```
rasa:
   production:
      url: http://rasa-production:5005
      token: ${RASA_TOKEN}
   worker:
      url: http://rasa-worker:5005
      token: ${RASA_TOKEN}
```

**Comment by KoomeKiriinya** [comment]
Docker-compose.yml is unmodified and action server on docker-compose.override.yml

**Comment by chris-aeviator** [comment]
@KoomeKiriinya  I would check in your case if the containers can see (ping/ curl) each other (e.g. `docker-compose exec rasa-x curl http://rasa-production:5005`). Is it possible you have multiple instances of the environment running (`docker ps | grep rasa`)?

Check your docker networking config.

**Comment by KoomeKiriinya** [comment]
Ping from rabbit mq is successful
```
/etc/rasa$ sudo docker-compose exec -u root rasa-worker ping 172.24.0.2
PING 172.24.0.2 (172.24.0.2) 56(84) bytes of data.
64 bytes from 172.24.0.2: icmp_seq=1 ttl=64 time=0.089 ms
64 bytes from 172.24.0.2: icmp_seq=2 ttl=64 time=0.075 ms
64 bytes from 172.24.0.2: icmp_seq=3 ttl=64 time=0.074 ms
64 bytes from 172.24.0.2: icmp_seq=4 ttl=64 time=0.073 ms
64 bytes from 172.24.0.2: icmp_seq=5 ttl=64 time=0.115 ms
64 bytes from 172.24.0.2: icmp_seq=6 ttl=64 time=0.071 ms
64 bytes from 172.24.0.2: icmp_seq=7 ttl=64 time=0.072 ms
^X64 bytes from 172.24.0.2: icmp_seq=8 ttl=64 time=0.087 ms
64 bytes from 172.24.0.2: icmp_seq=9 ttl=64 time=0.064 ms
64 bytes from 172.24.0.2: icmp_seq=10 ttl=64 time=0.074 ms
64 bytes from 172.24.0.2: icmp_seq=11 ttl=64 time=0.068 ms
```
rasa-x can reach production
```
docker-compose exec rasa-x curl http://rasa-production:5005
Hello from Rasa: 1.10.14
```
rasa-x can reach rasa-worker too

```
docker-compose exec rasa-x curl http://rasa-worker:5005
Hello from Rasa:
```

**Comment by chris-aeviator** [comment]
In the case of yellybeans (the comment above yours) rabbitMQ container threw an error and quit before this error was raised inside rasa-worker. Is there something in your logs?
