### ISSUE TITLE
Encountered an exception while running action 'action_weather_api'. Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.

### ISSUE THREAD

**Issue by goldy1987** [RasaHQ/rasa#5935]
**Rasa version**:Rasa 1.10.1

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**:3.6

**Operating system** (windows, osx, ...):Windows 10

**Issue**: I am getting error when my bot is suppose to give me reply from custom code .

**Error (including full traceback)**:
```
Traceback (most recent call last):
  File "c:\users\goldy\anaconda3\envs\rasabot1\lib\site-packages\sanic\app.py", line 976, in handle_request
    response = await response
  File "c:\users\goldy\anaconda3\envs\rasabot1\lib\site-packages\rasa_sdk\endpoint.py", line 102, in webhook
    result = await executor.run(action_call)
  File "c:\users\goldy\anaconda3\envs\rasabot1\lib\site-packages\rasa_sdk\executor.py", line 387, in run
    events = action(dispatcher, tracker, domain)
  File "C:\Users\goldy\PycharmProjects\RasaBot\actions.py", line 24, in run
    city = tracker.latest_message('text')
TypeError: 'dict' object is not callable
```

**Command or request that led to error**:
```

```

**Content of python file (actions.py):
```
from typing import Any, Text, Dict, List

from rasa_sdk import Action, Tracker
from rasa_sdk.executor import CollectingDispatcher
from app import Weather

class ActionHelloWorld(Action):

    def name(self) -> Text:
        return "action_weather_api"

    def run(self, dispatcher: CollectingDispatcher,
            tracker: Tracker,
            domain: Dict[Text, Any]) -> List[Dict[Text, Any]]:
        city = tracker.latest_message('text')
        temp = int(Weather(city)['temp'])
        dispatcher.utter_template("utter_temp",tracker,temp = temp)

        return []

```

**Content of domain file (domain.yml)** (if relevant):
```session_config:
  session_expiration_time: 60
  carry_over_slots_to_new_session: true
intents:
- greet
- weather
- city
- goodbye
responses:
  utter_greet:
  - text: Hey! I am WeatherBot, How can I assist you?
  utter_city:
  - text: Tell me the city name, you want to know weather of?
  utter_temp:
  - text: Today's temperature is {temp} degree celsius
  utter_goodbye:
  - text: Bye
actions:
- utter_greet
- utter_city
- utter_goodbye
- utter_temp
- action_weather_api

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @akelad will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by akelad** [comment]
Hi @goldy1987, this is more of a usage question about how to write custom actions, please ask those kinds of questions in our community [forum](https://forum.rasa.com). 

I believe the issues is that it should be `tracker.latest_message.get('text')
