### ISSUE TITLE
Rasa shell command error

### ISSUE THREAD

**Issue by gangeleski** [RasaHQ/rasa#5954]
**Rasa version**:
 Rasa 1.10.2
**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**:
Python 3.7.6
**Operating system** (windows, osx, ...):
Ubuntu 20.04
**Issue**:
Getting following error when running rasa shell command.

**Error (including full traceback)**:
```
rasa shell
2020-06-03 23:56:13 INFO     root  - Connecting to channel 'cmdline' which was specified by the '--connector' argument. Any other channels will be ignored. To connect to all given channels, omit the '--connector' argument.
2020-06-03 23:56:13 INFO     root  - Starting Rasa server on http://localhost:5005
2020-06-03 23:56:14.719163: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (303)
2020-06-03 23:56:22 INFO     root  - Rasa server is up and running.
Bot loaded. Type a message and press enter (use '/stop' to exit): 
2020-06-03 23:56:23 ERROR    asyncio  - Task exception was never retrieved
future: <Task finished coro=<configure_app.<locals>.run_cmdline_io() done, defined at /home/gangjeleski/miniconda3/envs/rasa/lib/python3.7/site-packages/rasa/core/run.py:128> exception=RuntimeError('this event loop is already running.')>
Traceback (most recent call last):
  File "/home/gangjeleski/miniconda3/envs/rasa/lib/python3.7/site-packages/rasa/core/run.py", line 134, in run_cmdline_io
    sender_id=conversation_id,
  File "/home/gangjeleski/miniconda3/envs/rasa/lib/python3.7/site-packages/rasa/core/channels/console.py", line 142, in record_messages
    text = get_user_input(button_question)
  File "/home/gangjeleski/miniconda3/envs/rasa/lib/python3.7/site-packages/rasa/core/channels/console.py", line 78, in get_user_input
    style=Style([("qmark", "#b373d6"), ("", "#b373d6")]),
  File "/home/gangjeleski/miniconda3/envs/rasa/lib/python3.7/site-packages/questionary/question.py", line 45, in ask
    return self.unsafe_ask(patch_stdout)
  File "/home/gangjeleski/miniconda3/envs/rasa/lib/python3.7/site-packages/questionary/question.py", line 59, in unsafe_ask
    return self.application.run()
  File "/home/gangjeleski/miniconda3/envs/rasa/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 812, in run
    self.run_async(pre_run=pre_run, set_exception_handler=set_exception_handler)
  File "uvloop/loop.pyx", line 1450, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1443, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1351, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 480, in uvloop.loop.Loop._run
RuntimeError: this event loop is already running.

```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @tmbo will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by gangeleski** [comment]
Any help on the issue? Thanks
