### ISSUE TITLE
Error : Invalid story file format and Failed to decode parameters as a json object

### ISSUE THREAD

**Issue by Bharathi-A-7** [RasaHQ/rasa#5987]
**Rasa version**:  1.10.1

**Python version**: 3.6.

**Operating system** : Windows

**Issue**: Unable to train dialogue model using ' rasa train ' . When I run the command ' rasa train ' , I'm getting an error ' **Invalid story file format and failed to parse stories.md** ' . My stories.md seems to be in proper format. And , further along , I also get the error , '  **Invalid to parse arguments in line 'slot{"location:"London"}'. Failed to decode parametersas a json object. Make sure the eventname is followed by a proper json object. Error: Expecting ':' delimiter: line 1 column 13 (char 12)'**  I'm attaching both my stories.md and domain.yml files.

**Error (including full traceback)**:
```
2020-06-10 17:34:07 ERROR    pykwalify.core  - validation.invalid
2020-06-10 17:34:07 ERROR    pykwalify.core  -  --- All found errors ---
2020-06-10 17:34:07 ERROR    pykwalify.core  - ["Value 'b'-greet -goodbye -inform'' is not a list. Value path: '/intents'", "Value 'b'-location'' is not a list. Value path: '/entities'", "Value 'b'-action_weather'' is not a list. Value path: '/actions'"]
c:\users\91887\anaconda3\envs\myenv\lib\site-packages\rasa\utils\common.py:351: UserWarning: Loading domain from 'domain.yml' failed. Using empty domain. Error: 'Failed to validate yaml file. Please make sure the file is correct and all mandatory parameters are specified; to do so, take a look at the errors logged during validation previous to this exception.'
Training NLU model...
c:\users\91887\anaconda3\envs\myenv\lib\site-packages\rasa\nlu\config.py:50: FutureWarning: You are using a pipeline template. All pipelines templates are deprecated and will be removed in version 2.0. Please add the components you want to use directly to your configuration file.
  return RasaNLUModelConfig(config)
2020-06-10 17:34:07 INFO     rasa.nlu.utils.spacy_utils  - Trying to load spacy model with name 'en'
2020-06-10 17:34:24 INFO     rasa.nlu.components  - Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2020-06-10 17:34:24 INFO     rasa.nlu.training_data.training_data  - Training data stats:
2020-06-10 17:34:24 INFO     rasa.nlu.training_data.training_data  - Number of intent examples: 0 (0 distinct intents)
2020-06-10 17:34:24 INFO     rasa.nlu.training_data.training_data  - Number of response examples: 0 (0 distinct responses)
2020-06-10 17:34:24 INFO     rasa.nlu.training_data.training_data  - Number of entity examples: 0 (0 distinct entities)
2020-06-10 17:34:24 INFO     rasa.nlu.model  - Starting to train component SpacyNLP
2020-06-10 17:34:24 INFO     rasa.nlu.model  - Finished training component.
2020-06-10 17:34:24 INFO     rasa.nlu.model  - Starting to train component SpacyTokenizer
2020-06-10 17:34:24 INFO     rasa.nlu.model  - Finished training component.
2020-06-10 17:34:24 INFO     rasa.nlu.model  - Starting to train component SpacyFeaturizer
2020-06-10 17:34:24 INFO     rasa.nlu.model  - Finished training component.
2020-06-10 17:34:24 INFO     rasa.nlu.model  - Starting to train component RegexFeaturizer
2020-06-10 17:34:24 INFO     rasa.nlu.model  - Finished training component.
2020-06-10 17:34:24 INFO     rasa.nlu.model  - Starting to train component CRFEntityExtractor
2020-06-10 17:34:24 INFO     rasa.nlu.model  - Finished training component.
2020-06-10 17:34:24 INFO     rasa.nlu.model  - Starting to train component EntitySynonymMapper
2020-06-10 17:34:24 INFO     rasa.nlu.model  - Finished training component.
2020-06-10 17:34:24 INFO     rasa.nlu.model  - Starting to train component SklearnIntentClassifier
c:\users\91887\anaconda3\envs\myenv\lib\site-packages\rasa\utils\common.py:351: UserWarning: Can not train an intent classifier as there are not enough intents. Need at least 2 different intents. Skipping training of intent classifier.
  More info at https://rasa.com/docs/rasa/nlu/training-data-format/
2020-06-10 17:34:24 INFO     rasa.nlu.model  - Finished training component.
c:\users\91887\anaconda3\envs\myenv\lib\site-packages\sklearn\externals\joblib\__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)
2020-06-10 17:34:24 INFO     rasa.nlu.model  - Successfully saved model into 'C:\Users\91887\AppData\Local\Temp\tmp64y1taid\nlu'
NLU model training completed.
2020-06-10 17:34:24 ERROR    pykwalify.core  - validation.invalid
2020-06-10 17:34:24 ERROR    pykwalify.core  -  --- All found errors ---
2020-06-10 17:34:24 ERROR    pykwalify.core  - ["Value 'b'-greet -goodbye -inform'' is not a list. Value path: '/intents'", "Value 'b'-location'' is not a list. Value path: '/entities'", "Value 'b'-action_weather'' is not a list. Value path: '/actions'"]
c:\users\91887\anaconda3\envs\myenv\lib\site-packages\rasa\utils\common.py:351: UserWarning: Loading domain from 'domain.yml' failed. Using empty domain. Error: 'Failed to validate yaml file. Please make sure the file is correct and all mandatory parameters are specified; to do so, take a look at the errors logged during validation previous to this exception.'
2020-06-10 17:34:24 ERROR    pykwalify.core  - validation.invalid
2020-06-10 17:34:24 ERROR    pykwalify.core  -  --- All found errors ---
2020-06-10 17:34:24 ERROR    pykwalify.core  - ["Value 'b'-greet -goodbye -inform'' is not a list. Value path: '/intents'", "Value 'b'-location'' is not a list. Value path: '/entities'", "Value 'b'-action_weather'' is not a list. Value path: '/actions'"]
c:\users\91887\anaconda3\envs\myenv\lib\site-packages\rasa\core\training\dsl.py:431: UserWarning: Found unknown intent 'greet' on line 2. Please, make sure that all intents are listed in your domain yaml.
  docs=DOCS_URL_DOMAINS,
c:\users\91887\anaconda3\envs\myenv\lib\site-packages\rasa\core\training\dsl.py:431: UserWarning: Found unknown intent 'inform' on line 4. Please, make sure that all intents are listed in your domain yaml.
  docs=DOCS_URL_DOMAINS,
c:\users\91887\anaconda3\envs\myenv\lib\site-packages\rasa\utils\common.py:351: UserWarning: Failed to parse arguments in line 'inform{"location:"London"}'. Failed to decode parameters as a json object. Make sure the intent is followed by a proper json object. Error: Expecting ':' delimiter: line 1 column 13 (char 12)
  More info at https://rasa.com/docs/rasa/core/stories/
c:\users\91887\anaconda3\envs\myenv\lib\site-packages\rasa\core\training\dsl.py:431: UserWarning: Found unknown intent 'inform' on line 6. Please, make sure that all intents are listed in your domain yaml.
  docs=DOCS_URL_DOMAINS,
2020-06-10 17:34:24 ERROR    rasa.core.training.dsl  - Error in line 7: Invalid to parse arguments in line 'slot{"location:"London"}'. Failed to decode parametersas a json object. Make sure the eventname is followed by a proper json object. Error: Expecting ':' delimiter: line 1 column 13 (char 12)
Traceback (most recent call last):
  File "c:\users\91887\anaconda3\envs\myenv\lib\site-packages\rasa\core\training\dsl.py", line 283, in _parameters_from_json_string
    parsed_slots = json.loads(s)
  File "c:\users\91887\anaconda3\envs\myenv\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "c:\users\91887\anaconda3\envs\myenv\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\91887\anaconda3\envs\myenv\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 1 column 13 (char 12)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\91887\anaconda3\envs\myenv\lib\site-packages\rasa\core\training\dsl.py", line 352, in process_lines
    event_name, parameters = self._parse_event_line(line[1:])
  File "c:\users\91887\anaconda3\envs\myenv\lib\site-packages\rasa\core\training\dsl.py", line 310, in _parse_event_line
    parameters = StoryFileReader._parameters_from_json_string(slots_str, line)
  File "c:\users\91887\anaconda3\envs\myenv\lib\site-packages\rasa\core\training\dsl.py", line 298, in _parameters_from_json_string
    "object. Error: {}".format(line, e)
ValueError: Invalid to parse arguments in line 'slot{"location:"London"}'. Failed to decode parametersas a json object. Make sure the eventname is followed by a proper json object. Error: Expecting ':' delimiter: line 1 column 13 (char 12)
2020-06-10 17:34:24 ERROR    rasa.core.training.dsl  - Invalid story file format. Failed to parse 'D:\Data Mining\Mini Projects\WeatherBot\data\stories.md'
Traceback (most recent call last):
  File "c:\users\91887\anaconda3\envs\myenv\lib\site-packages\rasa\core\training\dsl.py", line 283, in _parameters_from_json_string
    parsed_slots = json.loads(s)
  File "c:\users\91887\anaconda3\envs\myenv\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "c:\users\91887\anaconda3\envs\myenv\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\91887\anaconda3\envs\myenv\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 1 column 13 (char 12)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\91887\anaconda3\envs\myenv\lib\site-packages\rasa\core\training\dsl.py", line 352, in process_lines
    event_name, parameters = self._parse_event_line(line[1:])
  File "c:\users\91887\anaconda3\envs\myenv\lib\site-packages\rasa\core\training\dsl.py", line 310, in _parse_event_line
    parameters = StoryFileReader._parameters_from_json_string(slots_str, line)
  File "c:\users\91887\anaconda3\envs\myenv\lib\site-packages\rasa\core\training\dsl.py", line 298, in _parameters_from_json_string
    "object. Error: {}".format(line, e)
ValueError: Invalid to parse arguments in line 'slot{"location:"London"}'. Failed to decode parametersas a json object. Make sure the eventname is followed by a proper json object. Error: Expecting ':' delimiter: line 1 column 13 (char 12)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\91887\anaconda3\envs\myenv\lib\site-packages\rasa\core\training\dsl.py", line 263, in read_from_file
    return await reader.process_lines(lines)
  File "c:\users\91887\anaconda3\envs\myenv\lib\site-packages\rasa\core\training\dsl.py", line 371, in process_lines
    raise ValueError(msg)
ValueError: Error in line 7: Invalid to parse arguments in line 'slot{"location:"London"}'. Failed to decode parametersas a json object. Make sure the eventname is followed by a proper json object. Error: Expecting ':' delimiter: line 1 column 13 (char 12)
Traceback (most recent call last):
  File "c:\users\91887\anaconda3\envs\myenv\lib\site-packages\rasa\core\training\dsl.py", line 283, in _parameters_from_json_string
    parsed_slots = json.loads(s)
  File "c:\users\91887\anaconda3\envs\myenv\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "c:\users\91887\anaconda3\envs\myenv\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\91887\anaconda3\envs\myenv\lib\json\decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ':' delimiter: line 1 column 13 (char 12)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\91887\anaconda3\envs\myenv\lib\site-packages\rasa\core\training\dsl.py", line 352, in process_lines
    event_name, parameters = self._parse_event_line(line[1:])
  File "c:\users\91887\anaconda3\envs\myenv\lib\site-packages\rasa\core\training\dsl.py", line 310, in _parse_event_line
    parameters = StoryFileReader._parameters_from_json_string(slots_str, line)
  File "c:\users\91887\anaconda3\envs\myenv\lib\site-packages\rasa\core\training\dsl.py", line 298, in _parameters_from_json_string
    "object. Error: {}".format(line, e)
ValueError: Invalid to parse arguments in line 'slot{"location:"London"}'. Failed to decode parametersas a json object. Make sure the eventname is followed by a proper json object. Error: Expecting ':' delimiter: line 1 column 13 (char 12)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\91887\anaconda3\envs\myenv\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\91887\anaconda3\envs\myenv\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\91887\Anaconda3\envs\myenv\Scripts\rasa.exe\__main__.py", line 7, in <module>
  File "c:\users\91887\anaconda3\envs\myenv\lib\site-packages\rasa\__main__.py", line 91, in main
    cmdline_arguments.func(cmdline_arguments)
  File "c:\users\91887\anaconda3\envs\myenv\lib\site-packages\rasa\cli\train.py", line 76, in train
    additional_arguments=extract_additional_arguments(args),
  File "c:\users\91887\anaconda3\envs\myenv\lib\site-packages\rasa\train.py", line 50, in train
    additional_arguments=additional_arguments,
  File "c:\users\91887\anaconda3\envs\myenv\lib\asyncio\base_events.py", line 488, in run_until_complete
    return future.result()
  File "c:\users\91887\anaconda3\envs\myenv\lib\site-packages\rasa\train.py", line 91, in train_async
    file_importer, output_path, fixed_model_name
  File "c:\users\91887\anaconda3\envs\myenv\lib\site-packages\rasa\train.py", line 109, in handle_domain_if_not_exists
    file_importer, output=output_path, fixed_model_name=fixed_model_name
  File "c:\users\91887\anaconda3\envs\myenv\lib\site-packages\rasa\train.py", line 488, in _train_nlu_with_validated_data
    new_fingerprint = await model.model_fingerprint(file_importer)
  File "c:\users\91887\anaconda3\envs\myenv\lib\site-packages\rasa\model.py", line 285, in model_fingerprint
    stories = await file_importer.get_stories()
  File "c:\users\91887\anaconda3\envs\myenv\lib\site-packages\rasa\importers\importer.py", line 261, in get_stories
    stories = await asyncio.gather(*stories)
  File "c:\users\91887\anaconda3\envs\myenv\lib\site-packages\rasa\importers\rasa.py", line 56, in get_stories
    exclusion_percentage,
  File "c:\users\91887\anaconda3\envs\myenv\lib\site-packages\rasa\core\training\dsl.py", line 233, in read_from_files
    f, domain, interpreter, template_variables, use_e2e
  File "c:\users\91887\anaconda3\envs\myenv\lib\site-packages\rasa\core\training\dsl.py", line 263, in read_from_file
    return await reader.process_lines(lines)
  File "c:\users\91887\anaconda3\envs\myenv\lib\site-packages\rasa\core\training\dsl.py", line 371, in process_lines
    raise ValueError(msg)
ValueError: ('Error in line 7: Invalid to parse arguments in line \'slot{"location:"London"}\'. Failed to decode parametersas a json object. Make sure the eventname is followed by a proper json object. Error: Expecting \':\' delimiter: line 1 column 13 (char 12)', "Invalid story file format. Failed to parse 'D:\\Data Mining\\Mini Projects\\WeatherBot\\data\\stories.md'")

(myenv) D:\Data Mining\Mini Projects\WeatherBot>

```

**Command or request that led to error**:
```
'rasa train'    after running ' rasa run actions'
```

**Content of configuration file (config.yml)** (if relevant):
```yml
language: "en"
pipeline: "pretrained_embeddings_spacy"

policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
    epochs: 200

```

**Content of domain file (domain.yml)** (if relevant):
```yml
slots:
    location:
        type: text

intents:
    -greet
    -goodbye
    -inform

entities:
    -location

responses:
  utter_greet:
    - text: 'Hello! How can I help?'
  utter_goodbye:
    - text: 'Bye. Talk to you later.'
    - text: 'Bubye! See ya!'
    - text: 'Au revoir'
  utter_ask_location:
    - text: 'In what location?'


actions:
    -action_weather


```
**Content of stories.md :**  
```
##story_001
* greet
	-utter_greet
* inform 
	-utter_ask_location
* inform{"location:"London"}
	-slot{"location:"London"}
	-action_weather
* goodbye
	-utter_goodbye
	
##story_002
*greet
	-utter_greet
* inform{"location":"Paris"}
	-slot{"location":"Paris"}
	-action_weather
* goodbye
	-utter_goodbye
		
##story_003
* greet
	-utter_greet
* inform 
	-utter_ask_location
* inform{"location":"Vilnius"}
	-slot{"location":"Vilnius"}
	-action_weather
* goodbye
	-utter_goodbye
	
##story_004
* greet
	-utter_greet
* inform{"location":"Italy"}
	-slot{"location":"Italy"}
	-action_weather
* goodbye
	-utter_goodbye
	
##story_005
* greet
	-utter_greet
* inform
	-utter_ask_location
* inform{"location":"Lithuania"}
	-slot{"location":"Lithuania"}
	-action_weather
* goodbye
	-utter_goodbye

```
My action is present in the domain.yml file as well . I don't know where I'm going wrong . Please help me get rid of this error . Thanks

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @dakshvar22 will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
