### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow_core'

### ISSUE THREAD

**Issue by sainimohit23** [RasaHQ/rasa#5990]
**Rasa version**: 1.9.6

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**: 3.6

**Operating system** (windows, osx, ...): ubuntu 16.04

**Issue**: I am getting following error while running the command `rasa train nlu` 
ModuleNotFoundError: No module named 'tensorflow_core'

I created a conda environment.

installed rasa and its dependencies using-
```
pip install rasa rasa[spacy]
```

Pipeline that I am using

```
pipeline:
  - name: ConveRTTokenizer
  - name: ConveRTFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
```

**Error (including full traceback)**:
```
(rasaenv) YATRAONLINE\v-mohit.saini@lap0002044:~/personal/rasa/rasabot$ rasa train nlu
Training NLU model...
Traceback (most recent call last):
  File "/home/v-mohit.saini/anaconda3/envs/rasaenv/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/home/v-mohit.saini/anaconda3/envs/rasaenv/lib/python3.6/site-packages/rasa/__main__.py", line 91, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/home/v-mohit.saini/anaconda3/envs/rasaenv/lib/python3.6/site-packages/rasa/cli/train.py", line 140, in train_nlu
    persist_nlu_training_data=args.persist_nlu_data,
  File "/home/v-mohit.saini/anaconda3/envs/rasaenv/lib/python3.6/site-packages/rasa/train.py", line 414, in train_nlu
    persist_nlu_training_data,
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/home/v-mohit.saini/anaconda3/envs/rasaenv/lib/python3.6/site-packages/rasa/train.py", line 445, in _train_nlu_async
    persist_nlu_training_data=persist_nlu_training_data,
  File "/home/v-mohit.saini/anaconda3/envs/rasaenv/lib/python3.6/site-packages/rasa/train.py", line 474, in _train_nlu_with_validated_data
    persist_nlu_training_data=persist_nlu_training_data,
  File "/home/v-mohit.saini/anaconda3/envs/rasaenv/lib/python3.6/site-packages/rasa/nlu/train.py", line 74, in train
    trainer = Trainer(nlu_config, component_builder)
  File "/home/v-mohit.saini/anaconda3/envs/rasaenv/lib/python3.6/site-packages/rasa/nlu/model.py", line 142, in __init__
    components.validate_requirements(cfg.component_names)
  File "/home/v-mohit.saini/anaconda3/envs/rasaenv/lib/python3.6/site-packages/rasa/nlu/components.py", line 46, in validate_requirements
    from rasa.nlu import registry
  File "/home/v-mohit.saini/anaconda3/envs/rasaenv/lib/python3.6/site-packages/rasa/nlu/registry.py", line 13, in <module>
    from rasa.nlu.classifiers.diet_classifier import DIETClassifier
  File "/home/v-mohit.saini/anaconda3/envs/rasaenv/lib/python3.6/site-packages/rasa/nlu/classifiers/diet_classifier.py", line 25, in <module>
    from rasa.utils.tensorflow.models import RasaModel
  File "/home/v-mohit.saini/anaconda3/envs/rasaenv/lib/python3.6/site-packages/rasa/utils/tensorflow/models.py", line 9, in <module>
    from tensorflow_core.python.ops.summary_ops_v2 import ResourceSummaryWriter
ModuleNotFoundError: No module named 'tensorflow_core'
```

**Command or request that led to error**:
```
rasa train nlu
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @chkoss will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by dakshvar22** [comment]
Hi @sainimohit23, that error looks like there is a problem with your virtual environment. Can you please try pip installing rasa in a fresh environment and check. Also, since you want to use ConveRT in your pipeline, you should install rasa with `pip install rasa[convert]`

**Comment by sainimohit23** [comment]
@dakshvar22 thanks it worked. I have a question unrelated to this issue. I have asked this question 3 times in forums and I never got an answer.

As my dataset is going to have a lot of dates and times. So, how to make the intent classifier aware of dates as entities. The queries are going to have a lot of examples like:
- book flight from Delhi to Mumbai on 18 august.
- show flight options for 20-7-2020.
- 25 dec flight options for Bangalore.

So, if I prepare training data as given below, will it work? Or is there any better way to define date entities? Does adding the "DucklingHTTPExtractor" in the pipeline would help(as it is just an entity extractor)?

- book flight from Delhi to Mumbai on \[18 august\](date).
- show flight options for \[20-7-2020\](date).
- \[25 dec\](date) flight options for Bangalore.

**Comment by geetanjaligg** [comment]
Hi, 

I am still getting this error when I run `rasa train nlu`. I tried creating a fresh venv and reinstalled TensorFlow and rasa. Still couldn't get rid of this. 

pip libraries:

```
absl-py==0.9.0
aiofiles==0.5.0
aiohttp==3.6.2
appnope==0.1.0
APScheduler==3.6.3
astor==0.8.1
astroid==2.3.3
astropy==4.0
astunparse==1.6.3
async-generator==1.10
async-timeout==3.0.1
attrs==19.3.0
Automat==0.8.0
autopep8==1.5.2
backcall==0.1.0
beautifulsoup4==4.8.2
bleach==3.1.0
blis==0.2.4
boto==2.49.0
boto3==1.14.8
botocore==1.17.8
bs4==0.0.1
cachetools==4.0.0
catalogue==1.0.0
catboost==0.23.2
certifi==2019.11.28
cffi==1.13.2
chardet==3.0.4
click==7.1.2
cloudpickle==1.3.0
cltk==0.1.113
colorclass==2.2.0
coloredlogs==10.0
colorhash==1.0.2
colour==0.1.5
ConfigArgParse==0.13.0
confuse==1.0.0
constantly==15.1.0
cryptography==2.8
cssselect==1.1.0
cycler==0.10.0
cymem==2.0.3
decorator==4.4.0
defusedxml==0.6.0
dill==0.3.1.1
dnspython==1.16.0
docopt==0.6.2
docutils==0.15.2
en-core-web-md @ https://github.com/explosion/spacy-models/releases/download/en_core_web_md-2.1.0/en_core_web_md-2.1.0.tar.gz
entrypoints==0.3
fakeredis==0.10.3
fbmessenger==6.0.0
Flask==1.1.2
Flask-Cors==3.0.8
Flask-JWT-Simple==0.0.3
future==0.18.2
gast==0.2.2
gensim==3.8.3
geojson==2.5.0
gevent==1.5.0
gitdb2==2.0.6
GitPython==3.0.5
google-auth==1.10.1
google-auth-oauthlib==0.4.1
google-pasta==0.1.8
googleapis-common-protos==1.51.0
graphviz==0.13.2
greenlet==0.4.16
grpcio==1.26.0
gunicorn==20.0.4
h11==0.8.1
h2==3.2.0
h5py==2.10.0
hpack==3.0.0
hstspreload==2020.6.30
htmlmin==0.1.12
httplib2==0.18.1
httptools==0.1.1
httpx==0.9.3
humanfriendly==8.2
hyperframe==5.2.0
hyperlink==19.0.0
idna==2.8
imbalanced-learn==0.6.2
imblearn==0.0
importlib-metadata==0.23
incremental==17.5.0
ipykernel==5.1.2
ipython==7.8.0
ipython-genutils==0.2.0
ipywidgets==7.5.1
isort==4.3.21
itsdangerous==1.1.0
jedi==0.15.1
Jinja2==2.10.3
jmespath==0.10.0
joblib==0.14.1
json5==0.8.5
jsonpickle==1.4.1
jsonschema==3.2.0
jupyter-client==5.3.4
jupyter-contrib-core==0.3.3
jupyter-contrib-nbextensions==0.5.1
jupyter-core==4.6.0
jupyter-highlight-selected-word==0.2.0
jupyter-latex-envs==1.4.6
jupyter-nbextensions-configurator==0.4.1
jupyterlab==1.1.4
jupyterlab-server==1.0.6
jupyterthemes==0.20.0
kafka-python==1.4.7
Keras==2.3.1
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
kiwisolver==1.1.0
klein==17.10.0
kmodes==0.10.2
lazy-object-proxy==1.4.3
lesscpy==0.14.0
lightgbm==2.3.1
llvmlite==0.31.0
lxml==4.5.0
Markdown==3.1.1
MarkupSafe==1.1.1
matplotlib==3.2.2
mattermostwrapper==2.2
mccabe==0.6.1
missingno==0.4.2
mistune==0.8.4
mock==4.0.2
more-itertools==7.2.0
mpld3==0.3
multidict==4.7.6
murmurhash==1.0.2
nbconvert==5.6.0
nbformat==4.4.0
networkx==2.4
nltk==3.4.5
notebook==6.0.1
numba==0.48.0
numpy==1.17.2
oauth2client==4.1.3
oauthlib==3.1.0
opt-einsum==3.1.0
packaging==20.4
pandas==0.25.3
pandas-profiling==2.4.0
pandocfilters==1.4.2
parsel==1.5.2
parso==0.5.1
patsy==0.5.1
pexpect==4.7.0
phik==0.9.9
pickleshare==0.7.5
pika==1.1.0
Pillow==7.1.2
pixiedust==1.1.18
plac==0.9.6
plotly==4.8.1
pluggy==0.13.1
ply==3.11
preshed==2.0.1
prometheus-client==0.7.1
promise==2.3
prompt-toolkit==2.0.9
Protego==0.1.16
protobuf==3.11.2
psycopg2-binary==2.8.5
ptyprocess==0.6.0
py==1.8.1
pyaml==20.4.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycodestyle==2.5.0
pycparser==2.19
PyDispatcher==2.0.5
pydot==1.4.1
pydotplus==2.0.2
Pygments==2.4.2
PyHamcrest==2.0.0
PyJWT==1.7.1
pykwalify==1.7.0
pylint==2.4.4
pymongo==3.8.0
PyMySQL==0.9.3
pyOpenSSL==19.1.0
pyparsing==2.4.2
pyrsistent==0.15.4
PySocks==1.7.1
pytest==5.3.5
pytest-pylint==0.14.1
python-crfsuite==0.9.6
python-dateutil==2.8.0
python-engineio==3.12.1
python-socketio==4.5.1
python-telegram-bot==11.1.0
pytz==2019.3
pyuca==1.2
PyYAML==5.3
pyzmq==18.1.0
questionary==1.5.2
queuelib==1.5.0
rasa==1.10.3
rasa-core==0.14.5
rasa-core-sdk==0.14.0
rasa-nlu==0.15.1
rasa-sdk==1.10.2
redis==3.5.3
regex==2020.1.8
requests==2.24.0
requests-oauthlib==1.3.0
requests-toolbelt==0.9.1
retrying==1.3.3
rfc3986==1.4.0
rocketchat-API==0.6.36
rsa==4.0
ruamel.yaml==0.16.10
ruamel.yaml.clib==0.2.0
s3transfer==0.3.3
sanic==19.12.2
Sanic-Cors==0.10.0.post3
sanic-jwt==1.4.1
Sanic-Plugins-Framework==0.9.2
scikit-learn==0.22.2.post1
scikit-optimize==0.7.4
scipy==1.4.1
Scrapy==1.8.0
seaborn==0.9.0
Send2Trash==1.5.0
service-identity==18.1.0
simplejson==3.17.0
six==1.12.0
sklearn-crfsuite==0.3.6
slackclient==2.7.2
smart-open==2.0.0
smmap2==2.0.5
sniffio==1.1.0
soupsieve==1.9.5
spacy==2.1.9
SQLAlchemy==1.3.18
srsly==1.0.2
statsmodels==0.11.0
tabulate==0.8.7
tensorboard==2.1.1
tensorflow==2.1.1
tensorflow-addons==0.7.1
tensorflow-datasets==3.0.0
tensorflow-estimator==2.1.0
tensorflow-hub==0.8.0
tensorflow-metadata==0.21.2
tensorflow-probability==0.9.0
termcolor==1.1.0
terminado==0.8.2
terminaltables==3.1.0
testpath==0.4.2
thinc==7.0.8
tornado==6.0.3
tqdm==4.45.0
traitlets==4.3.2
twilio==6.26.3
Twisted==19.10.0
typed-ast==1.4.1
typing==3.7.4.1
tzlocal==2.1
ujson==2.0.3
urllib3==1.25.7
uvloop==0.14.0
w3lib==1.21.0
wasabi==0.7.0
wcwidth==0.1.7
webencodings==0.5.1
webexteamssdk==1.3
websocket-client==0.54.0
websockets==8.1
Werkzeug==0.16.0
Whoosh==2.7.4
widgetsnbextension==3.5.1
wrapt==1.11.2
xgboost==0.90
xlrd==1.2.0
yarl==1.4.2
zipp==0.6.0
zope.interface==4.7.1
```

**Comment by sainimohit23** [comment]
@geetanjaligg can you show me your pipeline?

**Comment by geetanjaligg** [comment]
```pipeline:
  - name: ConveRTTokenizer
  - name: ConveRTFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
```

**Comment by sainimohit23** [comment]
@geetanjaligg as @dakshvar22 has mentioned. You have to install the following package- `pip install rasa[convert]`

**Comment by geetanjaligg** [comment]
Thanks. I changed the virtual env with the old version of python and reinstalled everything.
