### ISSUE TITLE
Lock store endpoint_config has no attribute 'type'

### ISSUE THREAD

**Issue by tatianafrank** [RasaHQ/rasa#6031]
Rasa version:1.9.5

Rasa SDK version (if used & relevant):

Rasa X version (if used & relevant): 0.27.4

Python version: rasa x docker image

Operating system (windows, osx, ...): rasa x docker image

Issue:
This line https://github.com/RasaHQ/rasa/blob/master/rasa/core/lock_store.py#L250 should be lock_store = _load_from_module_string(endpoint_config)
endpoint_config is a string so it has no attribute `type` and fails with this error:

Error (including full traceback):
```
2020-06-16 14:03:23 INFO     root  - Starting Rasa server on http://localhost:5005
2020-06-16 14:03:24.004532: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (303)
Experienced exception while trying to serve
Traceback (most recent call last):
  File "/opt/venv/lib/python3.7/site-packages/rasa/core/lock_store.py", line 261, in _load_from_module_string
    lock_store_class = common.class_from_module_path(endpoint_config.type)
AttributeError: 'str' object has no attribute 'type'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/venv/lib/python3.7/site-packages/sanic/app.py", line 1167, in run
    serve(**server_settings)
  File "/opt/venv/lib/python3.7/site-packages/sanic/server.py", line 892, in serve
    trigger_events(before_start, loop)
  File "/opt/venv/lib/python3.7/site-packages/sanic/server.py", line 668, in trigger_events
    loop.run_until_complete(result)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/opt/venv/lib/python3.7/site-packages/rasa/core/run.py", line 245, in load_agent_on_start
    _lock_store = LockStore.create(endpoints.lock_store)
  File "/opt/venv/lib/python3.7/site-packages/rasa/core/lock_store.py", line 38, in create
    return _create_from_endpoint_config(obj)
  File "/opt/venv/lib/python3.7/site-packages/rasa/core/lock_store.py", line 250, in _create_from_endpoint_config
    lock_store = _load_from_module_string(endpoint_config.type)
  File "/opt/venv/lib/python3.7/site-packages/rasa/core/lock_store.py", line 265, in _load_from_module_string
    f"Could not find a class based on the module path "
AttributeError: 'str' object has no attribute 'type'
Traceback (most recent call last):
  File "/opt/venv/lib/python3.7/site-packages/rasa/core/lock_store.py", line 261, in _load_from_module_string
    lock_store_class = common.class_from_module_path(endpoint_config.type)
AttributeError: 'str' object has no attribute 'type'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/opt/venv/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/opt/venv/lib/python3.7/site-packages/rasa/__main__.py", line 91, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/opt/venv/lib/python3.7/site-packages/rasa/cli/run.py", line 114, in run
    rasa.run(**vars(args))
  File "/opt/venv/lib/python3.7/site-packages/rasa/run.py", line 56, in run
    **kwargs,
  File "/opt/venv/lib/python3.7/site-packages/rasa/core/run.py", line 216, in serve_application
    endpoints.lock_store if endpoints else None
  File "/opt/venv/lib/python3.7/site-packages/sanic/app.py", line 1167, in run
    serve(**server_settings)
  File "/opt/venv/lib/python3.7/site-packages/sanic/server.py", line 892, in serve
    trigger_events(before_start, loop)
  File "/opt/venv/lib/python3.7/site-packages/sanic/server.py", line 668, in trigger_events
    loop.run_until_complete(result)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/opt/venv/lib/python3.7/site-packages/rasa/core/run.py", line 245, in load_agent_on_start
    _lock_store = LockStore.create(endpoints.lock_store)
  File "/opt/venv/lib/python3.7/site-packages/rasa/core/lock_store.py", line 38, in create
    return _create_from_endpoint_config(obj)
  File "/opt/venv/lib/python3.7/site-packages/rasa/core/lock_store.py", line 250, in _create_from_endpoint_config
    lock_store = _load_from_module_string(endpoint_config.type)
  File "/opt/venv/lib/python3.7/site-packages/rasa/core/lock_store.py", line 265, in _load_from_module_string
    f"Could not find a class based on the module path "
AttributeError: 'str' object has no attribute 'type'
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @erohmensing will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by tatianafrank** [comment]
Following up @erohmensing @sara-tagger

**Comment by tatianafrank** [comment]
ping

**Comment by chkoss** [comment]
@tatianafrank Thank you for spotting this! The bug will be fixed in the next release.

**Comment by tatianafrank** [comment]
Thanks @chkoss ! When is the next release scheduled for?
