### ISSUE TITLE
asyncio  - Task exception was never retrieved

### ISSUE THREAD

**Issue by li-x-q** [RasaHQ/rasa#6037]
**Rasa version**:
   Rasa 1.10.0
**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**:
   Python 3.6.10 :: Anaconda, Inc.
**Operating system** (windows, osx, ...):
   Ubuntu 16.04
**Issue**:
asyncio  - Task exception was never retrieved
future: <Task finished coro=<configure_app.<locals>.run_cmdline_io() done, defined at /home/xxx/anaconda3/envs/chatter/lib/python3.6/site-packages/rasa/core/run.py:128> exception=RuntimeError('this event loop is already running.',)>

**Error (including full traceback)**:
```
Traceback (most recent call last):
  File "/home/xxx/anaconda3/envs/chatter/lib/python3.6/site-packages/rasa/core/run.py", line 134, in run_cmdline_io
    sender_id=conversation_id,
  File "/home/xxx/anaconda3/envs/chatter/lib/python3.6/site-packages/rasa/core/channels/console.py", line 142, in record_messages
    text = get_user_input(button_question)
  File "/home/xxx/anaconda3/envs/chatter/lib/python3.6/site-packages/rasa/core/channels/console.py", line 78, in get_user_input
    style=Style([("qmark", "#b373d6"), ("", "#b373d6")]),
  File "/home/xxx/anaconda3/envs/chatter/lib/python3.6/site-packages/questionary/question.py", line 45, in ask
    return self.unsafe_ask(patch_stdout)
  File "/home/xxx/anaconda3/envs/chatter/lib/python3.6/site-packages/questionary/question.py", line 59, in unsafe_ask
    return self.application.run()
  File "/home/xxx/anaconda3/envs/chatter/lib/python3.6/site-packages/prompt_toolkit/application/application.py", line 812, in run
    self.run_async(pre_run=pre_run, set_exception_handler=set_exception_handler)
  File "uvloop/loop.pyx", line 1450, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1443, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1351, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 480, in uvloop.loop.Loop._run
RuntimeError: this event loop is already running.

```

**Command or request that led to error**:
```
rasa run actions & rasa shell
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```
Last time the issue was resolved by reinstalling Rasa, however, it happened again.

**update**
I find the same issue in the Rasa community ("https://forum.rasa.com/t/error-this-event-loop-is-already-running/24017"), the questionary package was downgraded to 1.4.0 as suggested and the error prompt is disappeared. It really works and to some extend the issue is resolved.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @erohmensing will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
