### ISSUE TITLE
Can't install Rasa core on mac OS due to incompatible packages

### ISSUE THREAD

**Issue by lfnovo** [RasaHQ/rasa#6162]
**Rasa version**: latest (can't see the version since the app breaks)

**Python version**: 3.7.3 

**Operating system** (windows, osx, ...): Mac OS 10.15.5

**Issue**:
Error happens when I try to install rasa on a clean virtual environment. 

**Error (including full traceback)**:
```
ERROR: tensorflow 2.1.1 has requirement gast==0.2.2, but you'll have gast 0.3.3 which is incompatible.
ERROR: tensorflow 2.1.1 has requirement scipy==1.4.1; python_version >= "3", but you'll have scipy 1.5.1 which is incompatible.
```

**Command or request that led to error**:
```
rasa init
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @melindaloubser1 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by melindaloubser1** [comment]
@lfnovo Just confirming you mean you ran `pip install rasa` not `rasa install` right?

**Comment by lfnovo** [comment]
Sorry, I meant `rasa init` 

It fails to run because of TensorFlow

```
Traceback (most recent call last):
  File "/System/Volumes/Data/Users/lfnovo/Library/Python/3.7/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/Users/lfnovo/Library/Python/3.7/lib/python/site-packages/rasa/__main__.py", line 82, in main
    set_log_level(log_level)
  File "/Users/lfnovo/Library/Python/3.7/lib/python/site-packages/rasa/utils/common.py", line 71, in set_log_level
    update_tensorflow_log_level()
  File "/Users/lfnovo/Library/Python/3.7/lib/python/site-packages/rasa/utils/common.py", line 112, in update_tensorflow_log_level
    import tensorflow as tf
  File "/Users/lfnovo/Library/Python/3.7/lib/python/site-packages/tensorflow/__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "/Users/lfnovo/Library/Python/3.7/lib/python/site-packages/tensorflow_core/__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 959, in _find_and_load_unlocked
  File "/Users/lfnovo/Library/Python/3.7/lib/python/site-packages/tensorflow/__init__.py", line 50, in __getattr__
    module = self._load()
  File "/Users/lfnovo/Library/Python/3.7/lib/python/site-packages/tensorflow/__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/Users/lfnovo/Library/Python/3.7/lib/python/site-packages/tensorflow_core/python/__init__.py", line 64, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/Users/lfnovo/Library/Python/3.7/lib/python/site-packages/tensorflow_core/core/framework/graph_pb2.py", line 7, in <module>
    from google.protobuf import descriptor as _descriptor
  File "/Library/Python/3.7/site-packages/google/protobuf/__init__.py", line 37, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
  File "/Library/Python/3.7/site-packages/pkg_resources/__init__.py", line 83, in <module>
    __import__('pkg_resources.extern.packaging.requirements')
  File "/Library/Python/3.7/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 9, in <module>
    from pkg_resources.extern.pyparsing import stringStart, stringEnd, originalTextFor, ParseException
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/Library/Python/3.7/site-packages/pkg_resources/extern/__init__.py", line 43, in load_module
    __import__(extant)
  File "/Library/Python/3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 4756, in <module>
    _escapedPunc = Word( _bslash, r"\[]-*.$+^?()~ ", exact=2 ).setParseAction(lambda s,l,t:t[0][1])
  File "/Library/Python/3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 1284, in setParseAction
    self.parseAction = list(map(_trim_arity, list(fns)))
  File "/Library/Python/3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 1066, in _trim_arity
    this_line = extract_stack(limit=2)[-1]
  File "/Library/Python/3.7/site-packages/pkg_resources/_vendor/pyparsing.py", line 1050, in extract_stack
    frame_summary = traceback.extract_stack(limit=-offset+limit-1)[offset]
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/traceback.py", line 211, in extract_stack
    stack = StackSummary.extract(walk_stack(f), limit=limit)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/traceback.py", line 363, in extract
    f.line
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/traceback.py", line 285, in line
    self._line = linecache.getline(self.filename, self.lineno).strip()
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/linecache.py", line 16, in getline
    lines = getlines(filename, module_globals)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.7/lib/python3.7/linecache.py", line 48, in getlines
    for mod in sys.modules.values():
RuntimeError: dictionary changed size during iteration
```

**Comment by melindaloubser1** [comment]
The other three issues here https://github.com/RasaHQ/rasa/search?q=dictionary+changed+size+during+iteration&type=Issues might help - One suggestion is a Python upgrade to 3.7.7; 
 This does seem to be mac specific, but on my mac (same version) with Python 3.7.4 I don't have this problem.

**Comment by lfnovo** [comment]
That fixed it. Thanks!
