### ISSUE TITLE
installed rasa but getting this message

### ISSUE THREAD

**Issue by sanjana-coder** [RasaHQ/rasa#6217]
installed rasa but gettin this message
can anyone help

C:\Users\Sanjiw Jha>rasa
Traceback (most recent call last):
  File "c:\users\sanjiw jha\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "c:\users\sanjiw jha\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "c:\users\sanjiw jha\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "c:\users\sanjiw jha\appdata\local\programs\python\python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "c:\users\sanjiw jha\appdata\local\programs\python\python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\sanjiw jha\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\sanjiw jha\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Sanjiw Jha\AppData\Local\Programs\Python\Python37\Scripts\rasa.exe\__main__.py", line 7, in <module>
  File "c:\users\sanjiw jha\appdata\local\programs\python\python37\lib\site-packages\rasa\__main__.py", line 82, in main
    set_log_level(log_level)
  File "c:\users\sanjiw jha\appdata\local\programs\python\python37\lib\site-packages\rasa\utils\common.py", line 71, in set_log_level
    update_tensorflow_log_level()
  File "c:\users\sanjiw jha\appdata\local\programs\python\python37\lib\site-packages\rasa\utils\common.py", line 112, in update_tensorflow_log_level
    import tensorflow as tf
  File "c:\users\sanjiw jha\appdata\local\programs\python\python37\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "c:\users\sanjiw jha\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "c:\users\sanjiw jha\appdata\local\programs\python\python37\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "c:\users\sanjiw jha\appdata\local\programs\python\python37\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "c:\users\sanjiw jha\appdata\local\programs\python\python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "c:\users\sanjiw jha\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "c:\users\sanjiw jha\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "c:\users\sanjiw jha\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "c:\users\sanjiw jha\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "c:\users\sanjiw jha\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "c:\users\sanjiw jha\appdata\local\programs\python\python37\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "c:\users\sanjiw jha\appdata\local\programs\python\python37\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

Failed to load the native TensorFlow runtime.

_Originally posted by @kramitjha in https://github.com/RasaHQ/rasa/issues/3852#issuecomment-658339543_

**Comment by sanjana-coder** [comment]
I've got the same issue
(base) D:\PYTHON>rasa --version
Traceback (most recent call last):
  File "d:\anaconda\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "d:\anaconda\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "d:\anaconda\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "d:\anaconda\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "d:\anaconda\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\anaconda\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\ANACONDA\Scripts\rasa.exe\__main__.py", line 7, in <module>
  File "d:\anaconda\lib\site-packages\rasa\__main__.py", line 82, in main
    set_log_level(log_level)
  File "d:\anaconda\lib\site-packages\rasa\utils\common.py", line 71, in set_log_level
    update_tensorflow_log_level()
  File "d:\anaconda\lib\site-packages\rasa\utils\common.py", line 112, in update_tensorflow_log_level
    import tensorflow as tf
  File "d:\anaconda\lib\site-packages\tensorflow\__init__.py", line 101, in <module>
    from tensorflow_core import *
  File "d:\anaconda\lib\site-packages\tensorflow_core\__init__.py", line 40, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "d:\anaconda\lib\site-packages\tensorflow\__init__.py", line 50, in __getattr__
    module = self._load()
  File "d:\anaconda\lib\site-packages\tensorflow\__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "d:\anaconda\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "d:\anaconda\lib\site-packages\tensorflow_core\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "d:\anaconda\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "d:\anaconda\lib\site-packages\tensorflow_core\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "d:\anaconda\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "d:\anaconda\lib\site-packages\tensorflow_core\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "d:\anaconda\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "d:\anaconda\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @koaning will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by sanjana-coder** [comment]
I even tried installing ujson 
Then when i reinstalled rasa it gave me this error

ERROR: Command errored out with exit status 1:
   command: 'D:\ANACONDA\envs\insrasa\python.exe' 'D:\ANACONDA\envs\insrasa\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\Sanjana\AppData\Local\Temp\tmpu7jig9ss'
       cwd: C:\Users\Sanjana\AppData\Local\Temp\pip-install-lptg15wd\ujson
  Complete output (5 lines):
  running bdist_wheel
  running build
  running build_ext
  building 'ujson' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Build Tools for Visual Studio": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for ujson
Failed to build ujson
ERROR: Could not build wheels for ujson which use PEP 517 and cannot be installed directly

I even downloaded the build tools..could you please help out

**Comment by koaning** [comment]
Have you tried following the steps in [this video](https://www.youtube.com/watch?v=4ewIABo0OkU)?

**Comment by sanjana-coder** [comment]
Yeah I did
