### ISSUE TITLE
FORMBOT example - testing errors

### ISSUE THREAD

**Issue by stefanveliki** [RasaHQ/rasa#6224]
**Rasa version**: 1.10.8

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**: 3.7.2

**Operating system** (windows, osx, ...): Docker - Debian 9

**Issue**:

Number of errors when following the FORMBOT example - Part 2:
**Unable to test: could not find a Core model. Use 'rasa train' to train a Rasa model and provide it via the '--model' argument.**

**Error (including full traceback)**:
```
**Unable to test: could not find a Core model. Use 'rasa train' to train a Rasa model and provide it via the '--model' argument.**
- AND -
**'NoneType' object has no attribute 'probabilities_using_best_policy'**

root@5e4d19d195a3:/src/first_form# rasa test --model models
Unable to test: could not find a Core model. Use 'rasa train' to train a Rasa model and provide it via the '--model' argument.
2020-07-15 19:27:38.675687: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (303)
/usr/local/lib/python3.7/site-packages/rasa/core/training/dsl.py:431: UserWarning: Found unknown intent 'greet' on line 2. Please, make sure that all intents are listed in your domain yaml.
  docs=DOCS_URL_DOMAINS,
/usr/local/lib/python3.7/site-packages/rasa/core/training/dsl.py:431: UserWarning: Found unknown intent 'request_restaurant' on line 4. Please, make sure that all intents are listed in your domain yaml.
  docs=DOCS_URL_DOMAINS,
/usr/local/lib/python3.7/site-packages/rasa/core/training/dsl.py:431: UserWarning: Found unknown intent 'thankyou' on line 9. Please, make sure that all intents are listed in your domain yaml.
  docs=DOCS_URL_DOMAINS,
/usr/local/lib/python3.7/site-packages/rasa/core/training/dsl.py:431: UserWarning: Found unknown intent 'greet' on line 13. Please, make sure that all intents are listed in your domain yaml.
  docs=DOCS_URL_DOMAINS,
/usr/local/lib/python3.7/site-packages/rasa/core/training/dsl.py:431: UserWarning: Found unknown intent 'request_restaurant' on line 15. Please, make sure that all intents are listed in your domain yaml.
  docs=DOCS_URL_DOMAINS,
/usr/local/lib/python3.7/site-packages/rasa/core/training/dsl.py:431: UserWarning: Found unknown intent 'inform' on line 18. Please, make sure that all intents are listed in your domain yaml.
  docs=DOCS_URL_DOMAINS,
/usr/local/lib/python3.7/site-packages/rasa/core/training/dsl.py:431: UserWarning: Found unknown intent 'thankyou' on line 22. Please, make sure that all intents are listed in your domain yaml.
  docs=DOCS_URL_DOMAINS,
/usr/local/lib/python3.7/site-packages/rasa/core/training/dsl.py:431: UserWarning: Found unknown intent 'greet' on line 26. Please, make sure that all intents are listed in your domain yaml.
  docs=DOCS_URL_DOMAINS,
/usr/local/lib/python3.7/site-packages/rasa/core/training/dsl.py:431: UserWarning: Found unknown intent 'request_restaurant' on line 28. Please, make sure that all intents are listed in your domain yaml.
  docs=DOCS_URL_DOMAINS,
/usr/local/lib/python3.7/site-packages/rasa/core/training/dsl.py:431: UserWarning: Found unknown intent 'chitchat' on line 31. Please, make sure that all intents are listed in your domain yaml.
  docs=DOCS_URL_DOMAINS,
/usr/local/lib/python3.7/site-packages/rasa/core/training/dsl.py:431: UserWarning: Found unknown intent 'thankyou' on line 36. Please, make sure that all intents are listed in your domain yaml.
  docs=DOCS_URL_DOMAINS,
Processed Story Blocks: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 789.79it/s, # trackers=1]
2020-07-15 19:27:48 INFO     rasa.core.test  - Evaluating 3 stories
Progress:
  0%|                                                                                                                                                                               | 0/3 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/usr/local/bin/rasa", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/rasa/__main__.py", line 92, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/usr/local/lib/python3.7/site-packages/rasa/cli/test.py", line 159, in test
    run_core_test(args)
  File "/usr/local/lib/python3.7/site-packages/rasa/cli/test.py", line 91, in run_core_test
    additional_arguments=vars(args),
  File "/usr/local/lib/python3.7/site-packages/rasa/test.py", line 140, in test_core
    rasa.core.test(stories, _agent, out_directory=output, **kwargs)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.7/site-packages/rasa/core/test.py", line 546, in test
    completed_trackers, agent, fail_on_prediction_errors, e2e
  File "/usr/local/lib/python3.7/site-packages/rasa/core/test.py", line 469, in collect_story_predictions
    tracker, agent, fail_on_prediction_errors, use_e2e
  File "/usr/local/lib/python3.7/site-packages/rasa/core/test.py", line 403, in _predict_tracker_actions
    circuit_breaker_tripped,
  File "/usr/local/lib/python3.7/site-packages/rasa/core/test.py", line 327, in _collect_action_executed_predictions
    action, policy, confidence = processor.predict_next_action(partial_tracker)
  File "/usr/local/lib/python3.7/site-packages/rasa/core/processor.py", line 300, in predict_next_action
    action_confidences, policy = self._get_next_action_probabilities(tracker)
  File "/usr/local/lib/python3.7/site-packages/rasa/core/processor.py", line 802, in _get_next_action_probabilities
    return self.policy_ensemble.probabilities_using_best_policy(
AttributeError: 'NoneType' object has no attribute 'probabilities_using_best_policy'


```

**Command or request that led to error**:
```
rasa test --model models
```

**Content of configuration file (config.yml)** (if relevant):
```yml
[rasa example FORMBOT - no modifications]
```

**Content of domain file (domain.yml)** (if relevant):
```yml
[rasa example FORMBOT - no modifications]
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @melindaloubser1 will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by melindaloubser1** [comment]
Hi @stefanveliki, what command did you run to see this error? Had you trained a model?

**Comment by kougaga** [comment]
Not sure if this can help, but I had exactly the same error when I was trying the [building assistant tutorial](https://rasa.com/docs/rasa/user-guide/building-assistants/), and it turns out that I misplaced the domain.yml file inside the /data directory.

**Comment by melindaloubser1** [comment]
@stefanveliki does the above suggestion help you?
