### ISSUE TITLE
tickets error when using multi sanic workers

### ISSUE THREAD

**Issue by baudzhou** [RasaHQ/rasa#6290]
**Rasa version**:
1.6.0
**Rasa SDK version** (if used & relevant):
1.6.1
**Python version**:
3.6.8
**Operating system** (windows, osx, ...):
Ubuntu 16.04.4 LTS (GNU/Linux 4.4.0-117-generic x86_64)
**Issue**:
When using multi sanic workers, I can just send 1 message to rasa. The second one will get a ticket error, and rasa is blocked.
All the rasa start process looks good.
**Error (including full traceback)**:
```
2020-07-29 17:57:40 ERROR    rasa.core.channels.channel  - An exception occured while handling user message 'some text'.
Traceback (most recent call last):
  File "/usr/local/miniconda3/lib/python3.6/site-packages/rasa/core/channels/channel.py", line 487, in receive
    metadata=metadata,
  File "/usr/local/miniconda3/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/usr/local/miniconda3/lib/python3.6/site-packages/rasa/core/channels/channel.py", line 83, in handler
    await app.agent.handle_message(*args, **kwargs)
  File "/usr/local/miniconda3/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/usr/local/miniconda3/lib/python3.6/site-packages/rasa/core/agent.py", line 485, in handle_message
    async with self.lock_store.lock(message.sender_id):
  File "/usr/local/miniconda3/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/usr/local/miniconda3/lib/python3.6/site-packages/async_generator/_util.py", line 34, in __aenter__
    return await self._agen.asend(None)
  File "/usr/local/miniconda3/lib/python3.6/site-packages/rasa/core/lock_store.py", line 89, in lock
    ticket = self.issue_ticket(conversation_id, lock_lifetime)
  File "/usr/local/miniconda3/lib/python3.6/site-packages/rasa/core/lock_store.py", line 70, in issue_ticket
    lock = self.get_or_create_lock(conversation_id)
  File "/usr/local/miniconda3/lib/python3.6/site-packages/rasa/core/lock_store.py", line 140, in get_or_create_lock
    existing_lock = self.get_lock(conversation_id)
  File "/usr/local/miniconda3/lib/python3.6/site-packages/rasa/core/lock_store.py", line 204, in get_lock
    return TicketLock.from_dict(json.loads(serialised_lock))
  File "/usr/local/miniconda3/lib/python3.6/site-packages/rasa/core/lock.py", line 57, in from_dict
    tickets = [Ticket.from_dict(json.loads(d)) for d in data.get("tickets")]
TypeError: 'NoneType' object is not iterable
```

**content of endpoints.yml**:
```
tracker_store:
   type: redis
   url: 127.0.0.1
   port: 6379
   db: 9
   password: xxx

lock_store:
   type: "redis"
   url: 127.0.0.1
   port: 6379
   db: 9
   password: xxx
```

-------------------------------------------------------------------------------------
It looks like working when I changed lock_store db to 8.
lock_store:
   type: "redis"
   url: 127.0.0.1
   port: 6379
   db: **_8_**
   password: xxx

**Comment by sara-tagger** [comment]
Thanks for the issue, @akelad will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗
