### ISSUE TITLE
rasa.core.agent  - Could not load model due to File is not a zip file.

### ISSUE THREAD

**Issue by Vaidehi16-05** [RasaHQ/rasa#6364]
**Rasa version**:Rasa 1.10.8

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**: 3.6

**Operating system** (windows, osx, ...): Windows 10

**Issue**:rasa.core.agent  - Could not load model due to File is not a zip file.

**Error (including full traceback)**:
```2020-08-10 16:08:10 DEBUG    rasa.cli.utils  - Parameter 'credentials' not set. Using default location 'credentials.yml' instead.
2020-08-10 16:08:12 DEBUG    rasa.core.utils  - Available web server routes:
/conversations/<conversation_id>/messages          POST                           add_message
/conversations/<conversation_id>/tracker/events    POST                           append_events
/webhooks/rasa                                     GET                            custom_webhook_RasaChatInput.health
/webhooks/rasa/webhook                             POST                           custom_webhook_RasaChatInput.receive
/webhooks/rest                                     GET                            custom_webhook_RestInput.health
/webhooks/rest/webhook                             POST                           custom_webhook_RestInput.receive
/model/test/intents                                POST                           evaluate_intents
/model/test/stories                                POST                           evaluate_stories
/conversations/<conversation_id>/execute           POST                           execute_action
/domain                                            GET                            get_domain
/                                                  GET                            hello
/model                                             PUT                            load_model
/model/parse                                       POST                           parse
/conversations/<conversation_id>/predict           POST                           predict
/conversations/<conversation_id>/tracker/events    PUT                            replace_events
/conversations/<conversation_id>/story             GET                            retrieve_story
/conversations/<conversation_id>/tracker           GET                            retrieve_tracker
/status                                            GET                            status
/model/predict                                     POST                           tracker_predict
/model/train                                       POST                           train
/conversations/<conversation_id>/trigger_intent    POST                           trigger_intent
/model                                             DELETE                         unload_model
/version                                           GET                            version
2020-08-10 16:08:12 INFO     root  - Starting Rasa server on http://localhost:5005
2020-08-10 16:08:12 DEBUG    rasa.core.utils  - Using the default number of Sanic workers (1).
2020-08-10 16:08:12 INFO     root  - Enabling coroutine debugging. Loop id 1470183925960.
2020-08-10 16:08:13 DEBUG    rasa.model  - Extracted model to 'C:\WINDOWS\TEMP\tmp96xo2m29'.
2020-08-10 16:08:14 DEBUG    rasa.utils.tensorflow.models  - Loading the model ...
2020-08-10 16:08:15.007532: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (303)
2020-08-10 16:08:16 DEBUG    rasa.utils.tensorflow.models  - Finished loading the model.
2020-08-10 16:08:16 DEBUG    rasa.utils.tensorflow.models  - Building tensorflow prediction graph...
2020-08-10 16:08:23 DEBUG    rasa.utils.tensorflow.models  - Finished building tensorflow prediction graph.
2020-08-10 16:08:23 DEBUG    rasa.nlu.classifiers.diet_classifier  - Failed to load model for 'ResponseSelector'. Maybe you did not provide enough training data and no model was trained or the path 'C:\WINDOWS\TEMP\tmp96xo2m29\nlu' doesn't exist?
2020-08-10 16:08:23 DEBUG    rasa.core.tracker_store  - Connected to InMemoryTrackerStore.
2020-08-10 16:08:23 DEBUG    rasa.core.lock_store  - Connected to lock store 'InMemoryLockStore'.
2020-08-10 16:08:23 DEBUG    rasa.core.nlg.generator  - Instantiated NLG to 'TemplatedNaturalLanguageGenerator'.
2020-08-10 16:08:23 DEBUG    rasa.core.agent  - Requesting model from server http://my-server.com/models/default_core@latest...
2020-08-10 16:08:25 ERROR    rasa.core.agent  - Could not load model due to File is not a zip file.
[2020-08-10 16:08:25 +0530] [620] [ERROR] Experienced exception while trying to serve
Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\lib\site-packages\rasa\utils\io.py", line 217, in unarchive
    tar = tarfile.open(fileobj=IOReader(byte_array))
  File "C:\Users\HP\anaconda3\lib\tarfile.py", line 1578, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\lib\site-packages\sanic\app.py", line 1167, in run
    serve(**server_settings)
  File "C:\Users\HP\anaconda3\lib\site-packages\sanic\server.py", line 892, in serve
    trigger_events(before_start, loop)
  File "C:\Users\HP\anaconda3\lib\site-packages\sanic\server.py", line 668, in trigger_events
    loop.run_until_complete(result)
  File "C:\Users\HP\anaconda3\lib\asyncio\base_events.py", line 583, in run_until_complete
    return future.result()
  File "C:\Users\HP\anaconda3\lib\site-packages\rasa\core\run.py", line 257, in load_agent_on_start
    action_endpoint=endpoints.action,
  File "C:\Users\HP\anaconda3\lib\site-packages\rasa\core\agent.py", line 282, in load_agent
    model_server,
  File "C:\Users\HP\anaconda3\lib\site-packages\rasa\core\agent.py", line 63, in load_from_server
    await _update_model_from_server(model_server, agent)
  File "C:\Users\HP\anaconda3\lib\site-packages\rasa\core\agent.py", line 156, in _update_model_from_server
    model_server, agent.fingerprint
  File "C:\Users\HP\anaconda3\lib\site-packages\rasa\core\agent.py", line 214, in _pull_model_and_fingerprint
    rasa.utils.io.unarchive(await resp.read(), model_directory)
  File "C:\Users\HP\anaconda3\lib\site-packages\rasa\utils\io.py", line 222, in unarchive
    zip_ref = zipfile.ZipFile(IOReader(byte_array))
  File "C:\Users\HP\anaconda3\lib\zipfile.py", line 1258, in __init__
    self._RealGetContents()
  File "C:\Users\HP\anaconda3\lib\zipfile.py", line 1325, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\lib\site-packages\rasa\utils\io.py", line 217, in unarchive
    tar = tarfile.open(fileobj=IOReader(byte_array))
  File "C:\Users\HP\anaconda3\lib\tarfile.py", line 1578, in open
    raise ReadError("file could not be opened successfully")
tarfile.ReadError: file could not be opened successfully

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HP\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\HP\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\HP\anaconda3\lib\site-packages\rasa\__main__.py", line 103, in <module>
    main()
  File "C:\Users\HP\anaconda3\lib\site-packages\rasa\__main__.py", line 92, in main
    cmdline_arguments.func(cmdline_arguments)
  File "C:\Users\HP\anaconda3\lib\site-packages\rasa\cli\run.py", line 83, in run
    rasa.run(**vars(args))
  File "C:\Users\HP\anaconda3\lib\site-packages\rasa\run.py", line 56, in run
    **kwargs,
  File "C:\Users\HP\anaconda3\lib\site-packages\rasa\core\run.py", line 216, in serve_application
    endpoints.lock_store if endpoints else None
  File "C:\Users\HP\anaconda3\lib\site-packages\sanic\app.py", line 1167, in run
    serve(**server_settings)
  File "C:\Users\HP\anaconda3\lib\site-packages\sanic\server.py", line 892, in serve
    trigger_events(before_start, loop)
  File "C:\Users\HP\anaconda3\lib\site-packages\sanic\server.py", line 668, in trigger_events
    loop.run_until_complete(result)
  File "C:\Users\HP\anaconda3\lib\asyncio\base_events.py", line 583, in run_until_complete
    return future.result()
  File "C:\Users\HP\anaconda3\lib\site-packages\rasa\core\run.py", line 257, in load_agent_on_start
    action_endpoint=endpoints.action,
  File "C:\Users\HP\anaconda3\lib\site-packages\rasa\core\agent.py", line 282, in load_agent
    model_server,
  File "C:\Users\HP\anaconda3\lib\site-packages\rasa\core\agent.py", line 63, in load_from_server
    await _update_model_from_server(model_server, agent)
  File "C:\Users\HP\anaconda3\lib\site-packages\rasa\core\agent.py", line 156, in _update_model_from_server
    model_server, agent.fingerprint
  File "C:\Users\HP\anaconda3\lib\site-packages\rasa\core\agent.py", line 214, in _pull_model_and_fingerprint
    rasa.utils.io.unarchive(await resp.read(), model_directory)
  File "C:\Users\HP\anaconda3\lib\site-packages\rasa\utils\io.py", line 222, in unarchive
    zip_ref = zipfile.ZipFile(IOReader(byte_array))
  File "C:\Users\HP\anaconda3\lib\zipfile.py", line 1258, in __init__
    self._RealGetContents()
  File "C:\Users\HP\anaconda3\lib\zipfile.py", line 1325, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file
sys:1: RuntimeWarning: coroutine 'BaseEventLoop.create_server' was never awaited

```

**Command or request that led to error**:
python -m rasa run --m ./models --endpoints endpoints.yml --port 5005 -vv --enable-api

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @erohmensing will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by erohmensing** [comment]
Can you please post the contents of your models folder? Is there a zip file in there?

**Comment by Vaidehi16-05** [comment]
That file's quite big..
![image](https://user-images.githubusercontent.com/64906920/89785920-bdf7b300-db38-11ea-9aa6-1a04c56acaed.png)
so there's .gz file in there.. i also converted gz file to zip file. Still getting the error
