### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError : when trying to run rasa init --no-prompt 

### ISSUE THREAD

**Issue by garchaaman19** [RasaHQ/rasa#6376]
**Rasa version**:
1.10.10
**Rasa SDK version** (if used & relevant):
rasa-sdk<2.0.0,>=1.10.0
**Rasa X version** (if used & relevant):

**Python version**:
3.6.9
**Operating system** (windows, osx, ...):
	Ubuntu 18.04.4  64 bit

tensorflow-addons<0.8.0,>=0.7.1
tensorflow 2.3.0

**Issue**:
I am trying to run rasa init --no-prompt on my venv and I am getting the following issue, I even tried with --debug flag to get detail here and above is the result. 

I have tried installing rasa using above commands

**pip3 install rasa
pip3 install --upgrade tensorflow rasa
pip3 install --upgrade tensorflow-addons rasa
pip install --upgrade pip
pip3 install --upgrade tensorflow-addons rasa --use-feature=2020-resolver**

**Error (including full traceback)**:
```
Welcome to Rasa! 🤖

To get started quickly, an initial project will be created.
If you need some help, check out the documentation at https://rasa.com/docs/rasa.

Created project directory at '/home/aman/meraklis-pocs/RASA_POC'.
Finished creating project structure.
Training an initial model...
2020-08-11 14:22:26 DEBUG    rasa.nlu.training_data.loading  - Training data format of './data/nlu.md' is 'md'.
2020-08-11 14:22:26 DEBUG    rasa.nlu.training_data.loading  - Training data format of './data/stories.md' is 'unk'.
2020-08-11 14:22:26 DEBUG    pykwalify.compat  - Using yaml library: /home/aman/meraklis-pocs/RASA_POC/venv/lib/python3.6/site-packages/ruamel/yaml/__init__.py
2020-08-11 14:22:26 DEBUG    rasa.nlu.training_data.loading  - Training data format of './data/nlu.md' is 'md'.
Training Core model...
Traceback (most recent call last):
  File "/home/aman/meraklis-pocs/RASA_POC/venv/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/home/aman/meraklis-pocs/RASA_POC/venv/lib/python3.6/site-packages/rasa/__main__.py", line 92, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/home/aman/meraklis-pocs/RASA_POC/venv/lib/python3.6/site-packages/rasa/cli/scaffold.py", line 206, in run
    init_project(args, path)
  File "/home/aman/meraklis-pocs/RASA_POC/venv/lib/python3.6/site-packages/rasa/cli/scaffold.py", line 118, in init_project
    print_train_or_instructions(args, path)
  File "/home/aman/meraklis-pocs/RASA_POC/venv/lib/python3.6/site-packages/rasa/cli/scaffold.py", line 58, in print_train_or_instructions
    args.model = rasa.train(domain, config, training_files, output)
  File "/home/aman/meraklis-pocs/RASA_POC/venv/lib/python3.6/site-packages/rasa/train.py", line 50, in train
    additional_arguments=additional_arguments,
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/home/aman/meraklis-pocs/RASA_POC/venv/lib/python3.6/site-packages/rasa/train.py", line 101, in train_async
    additional_arguments,
  File "/home/aman/meraklis-pocs/RASA_POC/venv/lib/python3.6/site-packages/rasa/train.py", line 188, in _train_async_internal
    additional_arguments=additional_arguments,
  File "/home/aman/meraklis-pocs/RASA_POC/venv/lib/python3.6/site-packages/rasa/train.py", line 223, in _do_training
    additional_arguments=additional_arguments,
  File "/home/aman/meraklis-pocs/RASA_POC/venv/lib/python3.6/site-packages/rasa/train.py", line 361, in _train_core_with_validated_data
    additional_arguments=additional_arguments,
  File "/home/aman/meraklis-pocs/RASA_POC/venv/lib/python3.6/site-packages/rasa/core/train.py", line 43, in train
    policies = config.load(policy_config)
  File "/home/aman/meraklis-pocs/RASA_POC/venv/lib/python3.6/site-packages/rasa/core/config.py", line 28, in load
    return PolicyEnsemble.from_dict(config_data)
  File "/home/aman/meraklis-pocs/RASA_POC/venv/lib/python3.6/site-packages/rasa/core/policies/ensemble.py", line 308, in from_dict
    constr_func = registry.policy_from_module_path(policy_name)
  File "/home/aman/meraklis-pocs/RASA_POC/venv/lib/python3.6/site-packages/rasa/core/registry.py", line 21, in policy_from_module_path
    module_path, lookup_path="rasa.core.policies.registry"
  File "/home/aman/meraklis-pocs/RASA_POC/venv/lib/python3.6/site-packages/rasa/utils/common.py", line 220, in class_from_module_path
    m = importlib.import_module(lookup_path)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/aman/meraklis-pocs/RASA_POC/venv/lib/python3.6/site-packages/rasa/core/policies/registry.py", line 5, in <module>
    from rasa.core.policies.ted_policy import TEDPolicy
  File "/home/aman/meraklis-pocs/RASA_POC/venv/lib/python3.6/site-packages/rasa/core/policies/ted_policy.py", line 8, in <module>
    import tensorflow_addons as tfa
  File "/home/aman/meraklis-pocs/RASA_POC/venv/lib/python3.6/site-packages/tensorflow_addons/__init__.py", line 21, in <module>
    from tensorflow_addons import activations
  File "/home/aman/meraklis-pocs/RASA_POC/venv/lib/python3.6/site-packages/tensorflow_addons/activations/__init__.py", line 21, in <module>
    from tensorflow_addons.activations.gelu import gelu
  File "/home/aman/meraklis-pocs/RASA_POC/venv/lib/python3.6/site-packages/tensorflow_addons/activations/gelu.py", line 24, in <module>
    get_path_to_datafile("custom_ops/activations/_activation_ops.so"))
  File "/home/aman/meraklis-pocs/RASA_POC/venv/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 58, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: /home/aman/meraklis-pocs/RASA_POC/venv/lib/python3.6/site-packages/tensorflow_addons/custom_ops/activations/_activation_ops.so: undefined symbol: _ZN10tensorflow14kernel_factory17OpKernelRegistrar12InitInternalEPKNS_9KernelDefEN4absl11string_viewESt10unique_ptrINS0_15OpKernelFactoryESt14default_deleteIS8_EE

```

**Command or request that led to error**:
```
rasa init --no-prompt 
rasa train
```

**Content of configuration file (config.yml)** (if relevant):
```yml
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: MappingPolicy
```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by garchaaman19** [comment]
@wochinge can you look into this please.

**Comment by sara-tagger** [comment]
Thanks for the issue, @akelad will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by dakshvar22** [comment]
@garchaaman19 Can you install these versions of the following packages and check again? - 
```
tensorflow = "~2.1"
tensorflow_hub = ">=0.7,<0.9"
tensorflow-addons = "^0.7.1"
```

**Comment by gibrano** [comment]
I solved it downgrading tensorflow_hub ---> pip install tensorflow_hub==0.8

**Comment by akelad** [comment]
@garchaaman19 did you end up resolving this?
