### ISSUE TITLE
rasa test seems to be broken in master

### ISSUE THREAD

**Issue by Ghostvv** [RasaHQ/rasa#6492]
when I call `rasa test` I got the following error:
```
Traceback (most recent call last):
  File "/Users/vova/Documents/rasa/venv/bin/rasa", line 11, in <module>
    load_entry_point('rasa', 'console_scripts', 'rasa')()
  File "/Users/vova/Documents/rasa/rasa/__main__.py", line 109, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/Users/vova/Documents/rasa/rasa/cli/test.py", line 160, in test
    run_core_test(args)
  File "/Users/vova/Documents/rasa/rasa/cli/test.py", line 92, in run_core_test
    additional_arguments=vars(args),
  File "/Users/vova/Documents/rasa/rasa/test.py", line 164, in test_core
    _test_core(stories, _agent, output, **kwargs)
  File "/Users/vova/Documents/rasa/rasa/test.py", line 174, in _test_core
    test(stories, agent, out_directory=output_directory, **kwargs)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/Users/vova/Documents/rasa/rasa/core/test.py", line 580, in test
    completed_trackers, agent, fail_on_prediction_errors, e2e
  File "/Users/vova/Documents/rasa/rasa/core/test.py", line 479, in _collect_story_predictions
    tracker, agent, fail_on_prediction_errors, use_e2e
  File "/Users/vova/Documents/rasa/rasa/core/test.py", line 430, in _predict_tracker_actions
    event, partial_tracker, fail_on_prediction_errors
  File "/Users/vova/Documents/rasa/rasa/core/test.py", line 274, in _collect_user_uttered_predictions
    WronglyClassifiedUserUtterance(event, user_uttered_eval_store)
  File "/Users/vova/Documents/rasa/rasa/core/test.py", line 174, in __init__
    intent = {"name": eval_store.intent_targets[0]}
IndexError: list index out of range
```

**Comment by Ghostvv** [comment]
it happens in `examples/rules` bot

**Comment by Ghostvv** [comment]
should be fixed in e2e
