### ISSUE TITLE
Error while adding a lookup table as text file in windows

### ISSUE THREAD

**Issue by venkatesh-chinni** [RasaHQ/rasa#6548]
**Rasa version**: 1.10.10

**Rasa SDK version** (if used & relevant): NA

**Rasa X version** (if used & relevant): NA

**Python version**: 3.7

**Operating system** (windows, osx, ...): Windows

**Issue**:
Error while training a nlu model when a look up table is  created as textfile in data file and its path is given in nlu.md

**Error (including full traceback)**:
```
Traceback (most recent call last):
  File "c:\users\1000277196\anaconda3\envs\py37\lib\site-packages\rasa\nlu\featurizers\sparse_featurizer\regex_featurizer.py", line 154, in _generate_lookup_regex
    f = open(lookup_elements, "r", encoding=rasa.utils.io.DEFAULT_ENCODING)
FileNotFoundError: [Errno 2] No such file or directory: 'data/location.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\1000277196\anaconda3\envs\py37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\1000277196\anaconda3\envs\py37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\1000277196\Anaconda3\envs\py37\Scripts\rasa.exe\__main__.py", line 7, in <module>
  File "c:\users\1000277196\anaconda3\envs\py37\lib\site-packages\rasa\__main__.py", line 92, in main
    cmdline_arguments.func(cmdline_arguments)
  File "c:\users\1000277196\anaconda3\envs\py37\lib\site-packages\rasa\cli\train.py", line 140, in train_nlu
    persist_nlu_training_data=args.persist_nlu_data,
  File "c:\users\1000277196\anaconda3\envs\py37\lib\site-packages\rasa\train.py", line 414, in train_nlu
    persist_nlu_training_data,
  File "c:\users\1000277196\anaconda3\envs\py37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "c:\users\1000277196\anaconda3\envs\py37\lib\site-packages\rasa\train.py", line 453, in _train_nlu_async
    persist_nlu_training_data=persist_nlu_training_data,
  File "c:\users\1000277196\anaconda3\envs\py37\lib\site-packages\rasa\train.py", line 482, in _train_nlu_with_validated_data
    persist_nlu_training_data=persist_nlu_training_data,
  File "c:\users\1000277196\anaconda3\envs\py37\lib\site-packages\rasa\nlu\train.py", line 90, in train
    interpreter = trainer.train(training_data, **kwargs)
  File "c:\users\1000277196\anaconda3\envs\py37\lib\site-packages\rasa\nlu\model.py", line 191, in train
    updates = component.train(working_data, self.config, **context)
  File "c:\users\1000277196\anaconda3\envs\py37\lib\site-packages\rasa\nlu\featurizers\sparse_featurizer\regex_featurizer.py", line 57, in train
    self._add_lookup_table_regexes(training_data.lookup_tables)
  File "c:\users\1000277196\anaconda3\envs\py37\lib\site-packages\rasa\nlu\featurizers\sparse_featurizer\regex_featurizer.py", line 79, in _add_lookup_table_regexes
    regex_pattern = self._generate_lookup_regex(table)
  File "c:\users\1000277196\anaconda3\envs\py37\lib\site-packages\rasa\nlu\featurizers\sparse_featurizer\regex_featurizer.py", line 157, in _generate_lookup_regex
    f"Could not load lookup table {lookup_elements}. "
ValueError: Could not load lookup table data/location.txt. Please make sure you've provided the correct path.
```

**Command or request that led to error**:
```
rasa train nlu
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @koaning will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by koaning** [comment]
Hi @venkatesh-chinni, could you add the command that let to this error? It might also help if you could list the file/folder structure of the relevant files as well as the `config.yml` file. It might just be a typo that went wrong here.

**Comment by venkatesh-chinni** [comment]
HI @koaning , already added the command.  It is when I try to train using `rasa train nlu`
`

**Comment by venkatesh-chinni** [comment]
My folder structure
![image](https://user-images.githubusercontent.com/23174924/91980529-09227180-ed45-11ea-8046-39fae60364a3.png)
![image](https://user-images.githubusercontent.com/23174924/91980651-3707b600-ed45-11ea-8308-60509ed48ab4.png)

**Comment by koaning** [comment]
This might be a windows path issue. 

I might be wrong, but I recall window paths being `"folder\folder\file.txt"` as opposed to `"folder/folder/file.txt"`. Could you try that?

**Comment by venkatesh-chinni** [comment]
I was also expecting it to be a path issue. I tried with 

- data/location.txt

- data\location.txt

- ChatBot/data/location.txt

- ChatBot\data\location.txt.

I get the same error for all the paths I tried
