### ISSUE TITLE
Call "Append events to a tracker" api before rest channel issue

### ISSUE THREAD

**Issue by tosim** [RasaHQ/rasa#6609]
when i call 
```
/conversations/{sessionId}/tracker/events 
```
before
```
/webhooks/rest/webhook
```
when the sessionId is new and the first time i call.
the response of rest channel will always be "[]"
and the next time i call rest channel will be normal. is this a bug or something? can any one help me.
my rasa version is 1.10.10 and i deploy with rasax on a docker-compose way.
```
2020-09-09T05:03:14.765572192Z [2020-09-09 05:03:14 +0000] [1] [ERROR] Exception occurred while handling uri: 'http://10.38.48.8:5005/webhooks/rest/webhook'
2020-09-09T05:03:14.765603686Z Traceback (most recent call last):
2020-09-09T05:03:14.765608171Z   File "/opt/venv/lib/python3.7/site-packages/sanic/request.py", line 173, in load_json
2020-09-09T05:03:14.765612207Z     self.parsed_json = loads(self.body)
2020-09-09T05:03:14.765615772Z ValueError: Expected object or value
2020-09-09T05:03:14.765619634Z 
2020-09-09T05:03:14.765623307Z During handling of the above exception, another exception occurred:
2020-09-09T05:03:14.765627495Z 
2020-09-09T05:03:14.765631259Z Traceback (most recent call last):
2020-09-09T05:03:14.765635368Z   File "/opt/venv/lib/python3.7/site-packages/sanic/app.py", line 976, in handle_request
2020-09-09T05:03:14.765639154Z     response = await response
2020-09-09T05:03:14.765642581Z   File "/opt/venv/lib/python3.7/site-packages/rasa/core/channels/channel.py", line 462, in receive
2020-09-09T05:03:14.765646139Z     sender_id = await self._extract_sender(request)
2020-09-09T05:03:14.765649221Z   File "/opt/venv/lib/python3.7/site-packages/rasa/core/channels/channel.py", line 412, in _extract_sender
2020-09-09T05:03:14.765652762Z     return req.json.get("sender", None)
2020-09-09T05:03:14.765656090Z   File "/opt/venv/lib/python3.7/site-packages/sanic/request.py", line 167, in json
2020-09-09T05:03:14.765659936Z     self.load_json()
2020-09-09T05:03:14.765663181Z   File "/opt/venv/lib/python3.7/site-packages/sanic/request.py", line 177, in load_json
2020-09-09T05:03:14.765666884Z     raise InvalidUsage("Failed when parsing body as json")
2020-09-09T05:03:14.765680082Z sanic.exceptions.InvalidUsage: Failed when parsing body as json
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @TyDunn will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by ricwo** [comment]
@tosim when you say
> when i call
/conversations/{sessionId}/tracker/events 

do you mean a GET on `/conversations/{sessionId}/tracker`? or a PUT to `/conversations/{sessionId}/tracker/events` that appends events to the tracker?

Also, can you share the exact cURL that led to the error message you posted?

**Comment by tosim** [comment]
@ricwo 
POST to /conversations/{sessionId}/tracker
```
[root@campanion-aipet-01 ~]# curl -X POST 10.38.48.8:5005/conversations/8qTqkdRw/tracker/events -H 'Content-Type: application/json' -d '[{"name":"lng","event":"slot","value":120.212408},{"name":"lat","event":"slot","value":30.251329}]'
{"sender_id":"8qTqkdRw","slots":{"city":null,"lat":30.251329,"lng":120.212408},"latest_message":{"intent":{},"entities":[],"text":null,"message_id":null,"metadata":{}},"latest_event_time":1599704100.3850856,"followup_action":"action_listen","paused":false,"events":[{"event":"slot","timestamp":1599704100.3850656,"name":"lng","value":120.212408},{"event":"slot","timestamp":1599704100.3850856,"name":"lat","value":30.251329}],"latest_input_channel":null,"active_form":{},"latest_action_name":null}

[root@campanion-aipet-01 ~]# curl -X POST 10.38.48.8:5005/webhooks/rest/webhook -H 'Content-Type: application/json' -d '{"sender": "8qTqkdRw", "message": "附近的停车场"}'
[]

[root@campanion-aipet-01 ~]# curl -X POST 10.38.48.8:5005/webhooks/rest/webhook -H 'Content-Type: application/json' -d '{"sender": "8qTqkdRw", "message": "附近的停车场"}'
[{"recipient_id":"8qTqkdRw","text":"{\"attached\":{\"actionList\":[\"\u53cc\u624b\u644a\u5f00\"],\"emotion\":\"\u4fe1\u4efb\",\"optional\":\"\u9ed8\u8ba4\u5973\"},\"domainRespData\":\"{\\\"resourceList\\\":[{\\\"address\\\":\\\"\u6c11\u5fc3\u8def280\u53f7\\\",\\\"distance\\\":\\\"66.0m\\\",\\\"distanceDesc\\\":\\\"\u9002\u4e2d\\\",\\\"location\\\":\\\"120.212497,30.220741\\\",\\\"name\\\":\\\"\u5e73\u5b89\u91d1\u878d\u4e2d\u5fc3\u505c\u8f66\u573a\\\",\\\"price\\\":\\\"2\u5143\/\u5c0f\u65f6\\\",\\\"priceDesc\\\":\\\"\u9ad8\\\",\\\"resourceType\\\":\\\"address\\\",\\\"status\\\":\\\"\u6ee1\u7684\\\",\\\"type\\\":\\\"\u5730\u4e0b\u7684\\\"},{\\\"address\\\":\\\"\u5bcc\u6625\u8def701\u53f7\u4e07\u8c61\u57ce\\\",\\\"distance\\\":\\\"219.0m\\\",\\\"distanceDesc\\\":\\\"\u8fd1\\\",\\\"location\\\":\\\"120.254500,30.232127\\\",\\\"name\\\":\\\"themixc\u4e07\u8c61\u57ce\u8d2d\u7269\u4e2d\u5fc3\u4e07\u8c61\u57ce2\u53f7\u505c\u8f66\u573a\\\",\\\"price\\\":\\\"4\u5143\/\u5c0f\u65f6\\\",\\\"priceDesc\\\":\\\"\u9ad8\\\",\\\"resourceType\\\":\\\"address\\\",\\\"status\\\":\\\"\u7d27\u5f20\\\",\\\"type\\\":\\\"\u5730\u4e0b\u7684\\\"},{\\\"address\\\":\\\"\u5e86\u6625\u4e1c\u8def\u4e0e\u94b1\u6c5f\u8def\u4ea4\u53c9\u53e3\u897f\u5357150\u7c73\\\",\\\"distance\\\":\\\"223.0m\\\",\\\"distanceDesc\\\":\\\"\u8fdc\\\",\\\"location\\\":\\\"120.174545,30.292126\\\",\\\"name\\\":\\\"\u5730\u4e0b\u81ea\u884c\u8f66\u5e93\\\",\\\"price\\\":\\\"0\u5143\/\u5c0f\u65f6\\\",\\\"priceDesc\\\":\\\"\u9ad8\\\",\\\"resourceType\\\":\\\"address\\\",\\\"status\\\":\\\"\u7d27\u5f20\\\",\\\"type\\\":\\\"\u5730\u4e0a\u7684\\\"}]}\",\"parseData\":{\"entities\":[{\"end\":2,\"entity\":\"radius\",\"start\":0,\"value\":\"\u9644\u8fd1\"}],\"intent\":{\"confidence\":0.9999342560768127,\"name\":\"navi_park_lot\"},\"intent_ranking\":[{\"confidence\":0.9999342560768127,\"name\":\"navi_park_lot\"},{\"confidence\":1.964335751836188E-5,\"name\":\"bot_challenge\"},{\"confidence\":1.923566378536634E-5,\"name\":\"goodbye\"},{\"confidence\":1.0968870810756925E-5,\"name\":\"mood_great\"},{\"confidence\":5.261025307845557E-6,\"name\":\"deny\"},{\"confidence\":5.080942628410412E-6,\"name\":\"mood_unhappy\"},{\"confidence\":4.5361093725659885E-6,\"name\":\"greet\"},{\"confidence\":1.0477659770913306E-6,\"name\":\"affirm\"}],\"response_selector\":{\"default\":{\"ranking\":[],\"response\":{\"confidence\":0.0}}},\"text\":\"\u9644\u8fd1\u7684\u505c\u8f66\u573a\"},\"respType\":1,\"slots\":{\"city\":\"hangzhou\",\"lat\":30.251329,\"lng\":120.212408},\"text\":\"\u53d1\u73b0\u9644\u8fd1\u7684\u505c\u8f66\u573a\u90fd\u662f\u6ee1\u7684\uff0c\u770b\u6765\u9700\u8981\u53bb\u7a0d\u8fdc\u7684\u5730\u65b9\u505c\u8f66\u4e86\"}"}]
```
first POST to /conversations/{sessionId}/tracker/events then POST to /webhooks/rest/webhook, it will response [], then POST to /webhooks/rest/webhook again, it will be normal response.
