### ISSUE TITLE
Spacy Pipeline on Raspberry failing with "[E018] Can't retrieve string for hash"

### ISSUE THREAD

**Issue by DanBmh** [RasaHQ/rasa#6633]
**Rasa version**: 1.10.12

**Python version**: 3.7.3

**Operating system**: Raspbian Buster

**Issue**:

I'm trying to run spacy pipeline on raspberry pi 4 in raspbian buster container image. My setup works for ubuntu based images on normal computers but on the raspi training the nlu model always fails with (hash number can change):

```
KeyError: "[E018] Can't retrieve string for hash '18446744073548548906'. This usually refers to an issue with the `Vocab` or `StringStore`."
```

I'm not sure this issue is related to spacy or to rasa's pipeline because spacy itself seems to work and the error occurs after successfully parsing some words.

**Error (including full traceback)**:
```
Training NLU model...
2020-09-10 11:49:05 INFO     rasa.nlu.utils.spacy_utils  - Trying to load spacy model with name 'en'
2020-09-10 11:50:12 INFO     rasa.nlu.components  - Added 'SpacyNLP' to component cache. Key 'SpacyNLP-en'.
2020-09-10 11:50:12 INFO     rasa.nlu.training_data.training_data  - Training data stats:
2020-09-10 11:50:12 INFO     rasa.nlu.training_data.training_data  - Number of intent examples: 116 (4 distinct intents)
2020-09-10 11:50:12 INFO     rasa.nlu.training_data.training_data  -   Found intents: 'skill_riddles_check_riddle', 'skill_riddles_get_riddle', 'skill_dialogs_confirm', 'skill_dialogs_refuse'
2020-09-10 11:50:12 INFO     rasa.nlu.training_data.training_data  - Number of response examples: 0 (0 distinct responses)
2020-09-10 11:50:12 INFO     rasa.nlu.training_data.training_data  - Number of entity examples: 95 (1 distinct entities)
2020-09-10 11:50:12 INFO     rasa.nlu.training_data.training_data  -   Found entity types: 'skill_riddles_riddle_answers'
2020-09-10 11:50:12 INFO     rasa.nlu.model  - Starting to train component SpacyNLP
2020-09-10 11:50:13 INFO     rasa.nlu.model  - Finished training component.
2020-09-10 11:50:13 INFO     rasa.nlu.model  - Starting to train component SpacyTokenizer
Traceback (most recent call last):
  File "/usr/local/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/rasa/__main__.py", line 92, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/usr/local/lib/python3.7/dist-packages/rasa/cli/train.py", line 140, in train_nlu
    persist_nlu_training_data=args.persist_nlu_data,
  File "/usr/local/lib/python3.7/dist-packages/rasa/train.py", line 414, in train_nlu
    persist_nlu_training_data,
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.7/dist-packages/rasa/train.py", line 453, in _train_nlu_async
    persist_nlu_training_data=persist_nlu_training_data,
  File "/usr/local/lib/python3.7/dist-packages/rasa/train.py", line 482, in _train_nlu_with_validated_data
    persist_nlu_training_data=persist_nlu_training_data,
  File "/usr/local/lib/python3.7/dist-packages/rasa/nlu/train.py", line 90, in train
    interpreter = trainer.train(training_data, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/rasa/nlu/model.py", line 191, in train
    updates = component.train(working_data, self.config, **context)
  File "/usr/local/lib/python3.7/dist-packages/rasa/nlu/tokenizers/tokenizer.py", line 95, in train
    tokens = self.tokenize(example, attribute)
  File "/usr/local/lib/python3.7/dist-packages/rasa/nlu/tokenizers/spacy_tokenizer.py", line 40, in tokenize
    for t in doc
  File "/usr/local/lib/python3.7/dist-packages/rasa/nlu/tokenizers/spacy_tokenizer.py", line 40, in <listcomp>
    for t in doc
  File "token.pyx", line 871, in spacy.tokens.token.Token.lemma_.__get__
  File "strings.pyx", line 136, in spacy.strings.StringStore.__getitem__
KeyError: "[E018] Can't retrieve string for hash '18446744073548548906'. This usually refers to an issue with the `Vocab` or `StringStore`."
```
<br>

I did add some debugging prints to `/usr/local/lib/python3.7/dist-packages/rasa/nlu/tokenizers/spacy_tokenizer.py` and it shows that some words work, some of them only once, some multiple times: 
```
# Replacing:
        return [
            Token(
                t.text, t.idx, lemma=t.lemma_, data={POS_TAG_KEY: self._tag_of_token(t)}
            )
            for t in doc
        ]

# With:
        tokens = []
        for t in doc:
            print(t.text)
            try:
                tag_key = self._tag_of_token(t)
                tok = Token(t.text, t.idx, lemma=t.lemma_, data={POS_TAG_KEY: tag_key})
                print(tok.lemma, tok.data, t.idx)
                tokens.append(tok)
            except:
                print("did not work\n")
        return tokens
```

Output:
```
2020-09-10 14:33:54 INFO     rasa.nlu.model  - Starting to train component SpacyTokenizer
tell
tell {'pos': 'VB'} 0
me
-PRON- {'pos': 'PRP'} 5
a
a {'pos': 'DT'} 8
new
new {'pos': 'JJ'} 10
riddle
riddle {'pos': 'NN'} 14
let
let {'pos': 'VB'} 0
me
-PRON- {'pos': 'PRP'} 4
guess
guess {'pos': 'VB'} 7
something
something {'pos': 'NN'} 13
give
give {'pos': 'VB'} 0
me
-PRON- {'pos': 'PRP'} 5
a
did not work

riddle
did not work

a
did not work

new
did not work

riddle
did not work

please
please {'pos': 'UH'} 13
new
did not work

riddle
riddle {'pos': 'NNP'} 4

```

<br>

I did install rasa and spacy with: 
(nlu model training does work using a different pipeline without spacy)
```
RUN pip3 install --no-cache-dir --upgrade rasa
RUN BLIS_ARCH="generic" pip3 install --no-cache-dir --upgrade "blis<0.5.0,>=0.4.0"
RUN BLIS_ARCH="generic" pip3 install --no-cache-dir --upgrade spacy --no-binary blis  # Installs version 2.3.2
RUN python3 -m spacy download en_core_web_md
RUN python3 -m spacy link en_core_web_md en
```

And my pipeline looks as follows:
```
# Configuration for Rasa NLU.

language: en

pipeline:
  - name: "SpacyNLP"
  - name: "SpacyTokenizer"
  - name: "SpacyFeaturizer"
  - name: "RegexFeaturizer"
  - name: "CRFEntityExtractor"
  - name: "EntitySynonymMapper"
  - name: DIETClassifier
    epochs: 30
    entity_recognition: False
```

<br>
Any ideas on this?

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @b-quachtran will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by DanBmh** [comment]
Still occurring with rasa=2.0.3 and spacy=2.3.2 on raspbian, again no problems with my ubuntu container.
Problem is existing in training, as well as when I test the model trained in the ubuntu container in the raspbian container.

Currently it has something to do with the caching of words, because I usually get the exception when I use a word a second time in a text input. The first time it works as expected.

**Comment by DanBmh** [comment]
Was a spacy issue, which is not supported for 32bit python. See linked issue for a workaround.
