### ISSUE TITLE
ValueError: '' is not in list

### ISSUE THREAD

**Issue by sids07** [RasaHQ/rasa#6655]
**Rasa version**: 1.10.12

**Rasa SDK version** (if used & relevant): 1.10.2

**Rasa X version** (if used & relevant):

**Python version**: 3.6.10

**Operating system** (windows, osx, ...): Linux(Ubuntu)

**Issue**:

I have been trying to resolve this error for a long time and tried all the available solution for this problem but still not able to solve it. Actually it is not cleared like exactly where my error is coming from. Please help me to resolve this error.

**Error (including full traceback)**:
```
Traceback (most recent call last):
  File "/home/sid/anaconda3/envs/rasa/lib/python3.6/site-packages/rasa/core/domain.py", line 546, in index_for_action
    return self.action_names.index(action_name)
ValueError: '' is not in list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sid/anaconda3/envs/rasa/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/home/sid/anaconda3/envs/rasa/lib/python3.6/site-packages/rasa/__main__.py", line 92, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/home/sid/anaconda3/envs/rasa/lib/python3.6/site-packages/rasa/cli/train.py", line 76, in train
    additional_arguments=extract_additional_arguments(args),
  File "/home/sid/anaconda3/envs/rasa/lib/python3.6/site-packages/rasa/train.py", line 50, in train
    additional_arguments=additional_arguments,
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/home/sid/anaconda3/envs/rasa/lib/python3.6/site-packages/rasa/train.py", line 101, in train_async
    additional_arguments,
  File "/home/sid/anaconda3/envs/rasa/lib/python3.6/site-packages/rasa/train.py", line 188, in _train_async_internal
    additional_arguments=additional_arguments,
  File "/home/sid/anaconda3/envs/rasa/lib/python3.6/site-packages/rasa/train.py", line 223, in _do_training
    additional_arguments=additional_arguments,
  File "/home/sid/anaconda3/envs/rasa/lib/python3.6/site-packages/rasa/train.py", line 361, in _train_core_with_validated_data
    additional_arguments=additional_arguments,
  File "/home/sid/anaconda3/envs/rasa/lib/python3.6/site-packages/rasa/core/train.py", line 66, in train
    agent.train(training_data, **additional_arguments)
  File "/home/sid/anaconda3/envs/rasa/lib/python3.6/site-packages/rasa/core/agent.py", line 742, in train
    self.policy_ensemble.train(training_trackers, self.domain, **kwargs)
  File "/home/sid/anaconda3/envs/rasa/lib/python3.6/site-packages/rasa/core/policies/ensemble.py", line 124, in train
    policy.train(training_trackers, domain, **kwargs)
  File "/home/sid/anaconda3/envs/rasa/lib/python3.6/site-packages/rasa/core/policies/memoization.py", line 163, in train
    self._add_states_to_lookup(trackers_as_states, trackers_as_actions, domain)
  File "/home/sid/anaconda3/envs/rasa/lib/python3.6/site-packages/rasa/core/policies/memoization.py", line 110, in _add_states_to_lookup
    feature_item = domain.index_for_action(action)
  File "/home/sid/anaconda3/envs/rasa/lib/python3.6/site-packages/rasa/core/domain.py", line 548, in index_for_action
    self._raise_action_not_found_exception(action_name)
  File "/home/sid/anaconda3/envs/rasa/lib/python3.6/site-packages/rasa/core/domain.py", line 553, in _raise_action_not_found_exception
    f"Cannot access action '{action_name}', "
NameError: Cannot access action '', as that name is not a registered action for this domain. Available actions are: 
	 - action_listen
	 - action_restart
	 - action_session_start
	 - action_default_fallback
	 - action_deactivate_form
	 - action_revert_fallback_events
	 - action_default_ask_affirmation
	 - action_default_ask_rephrase
	 - action_back
	 - action_room_search
	 - utter_ask_number_of_people
	 - utter_ask_room_type
	 - utter_cheer_up
	 - utter_did_that_help
	 - utter_goodbye
	 - utter_greet
	 - utter_happy
	 - utter_how_can_i_help
	 - utter_iamabot

```

**Command or request that led to error**:
```
rasa run
```
**Content of configuration file (nlu.md)** (if relevant):
```yml
## intent:greet
- hey
- hello
- hi
- good morning
- good evening
- hey there

## intent:goodbye
- bye
- goodbye
- see you around
- see you later

## intent:service_provider
- I need a [room](facility_type)
- I am searching for [room](facility_type)
- I am looking for a [room](facility_type)
- I was looking for [seminar hall](facility_type)
- I want to know if i could book [seminar hall](facility_type) 

## intent: info
- [deluxe](room_type)
- [simple](room_type)
- [attached bathroom](room_type)
- [with a/c](room_type)
- [without a/c](room_type)
- [with natural view](room_type)
- I am looking for [deluxe](room_type) room for [3 people](number_of_person)

## intent: inform
- [1 people](number_of_person)
- [2 people](number_of_person)
- [3 people](number_of_person)
- [4 people](number_of_person)
- [5 people](number_of_person)
- [6 people](number_of_person)


## intent:affirm
- yes
- indeed
- of course
- that sounds good
- correct

## intent:deny
- no
- never
- I don't think so
- don't like that
- no way
- not really

## intent:mood_great
- perfect
- very good
- great
- amazing
- wonderful
- I am feeling very good
- I am great
- I'm good

## intent:mood_unhappy
- sad
- very sad
- unhappy
- bad
- very bad
- awful
- terrible
- not very good
- extremely sad
- so sad

## intent:bot_challenge
- are you a bot?
- are you a human?
- am I talking to a bot?
- am I talking to a human?

```
**Content of configuration file (stories.md)** (if relevant):
```yml
## book room path
* greet
  - utter_how_can_i_help
* service_provider {"facility_type":"room"}
  - utter_ask_room_type
* info {"room_type":"deluxe","number_of_person":"3 person"}
  - action_room_search
  - {"message":"Yes we have the room available"}
* thanks
  - utter_goodbye

## book room + people 
* greet
  - utter_how_can_i_help
* service_provider {"facility_type":"room"}
  - utter_ask_room_type
* info {"room_type":"deluxe"}
  - utter_ask_number_of_people
* inform {"number_of_person":"3 person"}
  - action_room_search
  - {"message":"Yes we have the room available"}
* thanks
  - utter_goodbye
```

**Content of domain file (domain.yml)** (if relevant):
```yml
---

intents:
  - greet
  - goodbye
  - affirm
  - deny
  - mood_great
  - mood_unhappy
  - service_provider
  - bot_challenge
  - info
  - thanks
  - inform

entities:
  - facility_type
  - number_of_person
  - room_type

slots:
  facility_type:
    type: text
  message:
    type: unfeaturized
  number_of_person:
    type: text
  room_type:
    type: text

actions:
  - action_room_search

responses:
  utter_ask_number_of_people:
    - text: "Can you provide the number of person you are looking room for?"
    - text: "Please tell me how many person you are planning to visit with?"
    - text: "To search {room_type}, i must know how many people are there."

  utter_ask_room_type:
    - text: "Fine, Can you tell me what type of room you are searching for?"
    - text: "Okay that's great can you tell me what kind of room you want?"
    - text: "To search {facility_type}, tell me type of room you seek?"
  utter_cheer_up:
    - text: "Here is something to cheer you up:"
    - custom: "https://i.imgur.com/nGF1K8f.jpg"

  utter_did_that_help:
    - text: "Did that help you?"

  utter_goodbye:
    - text: Bye

  utter_greet:
    - text: "Hey! How are you?"

  utter_happy:
    - text: "Great, carry on!"

  utter_how_can_i_help:
    - text: " Hi, My name is Sid Bot for Yak and Yeti. How can i help you?"

  utter_iamabot:
    - text: "I am a bot, powered by Rasa."

session_config:
  carry_over_slots_to_new_session: true
  session_expiration_time: 60

```
**Content of domain file (action.py)** (if relevant):
```yml
from typing import Any, Text, Dict, List

from rasa_sdk import Action, Tracker
from rasa_sdk.executor import CollectingDispatcher
from rasa_sdk.events import SlotSet

class action_room_search(Action):

    def name(self) -> Text:
        return "action_room_search"

    def run(self, dispatcher: CollectingDispatcher,
            tracker: Tracker,
            domain: Dict[Text, Any]) -> List[Dict[Text, Any]]:
        facility= tracker.get_slot("facility_type")
        room = tracker.get_slot("room_type")
        people = tracker.get_slot("number_of_people")

        message = "Yes we have the room available"
        dispatcher.utter_message(text="Well you are looking for {} of type {} for {}, {}".format(facility,room,people,message))

        return [SlotSet("message",message)]

```

**Comment by sids07** [comment]
Here, i found my error. I was missing slot command on stories.md which was giving me this error.
i.e. 
slot{"message":"Yes we have the room available"} which I was writing just {"message":"Yes we have the room available"}
