### ISSUE TITLE
`rasa init` fails with `AttributeError: __aexit__`

### ISSUE THREAD

**Issue by JEM-Mosig** [RasaHQ/rasa#6672]
**Rasa version**:
Rasa Version     : 2.0.0a5
master: ecba3fafdedf11e874bb436b61105653a31d777d

**Rasa SDK version** (if used & relevant):
Rasa SDK Version : 2.0.0a5

**Rasa X version** (if used & relevant):

**Python version**:
Python Version   : 3.7.9 (default, Aug 31 2020, 07:22:35) 

**Operating system** (windows, osx, ...):
Operating System : Darwin-19.5.0-x86_64-i386-64bit

**Issue**:
It looks like master is broken :fire: rasa init gives AttributeError: __aexit__ when training the model. This is on Mac with a fresh install in a new conda environment from rasa master ecba3fafdedf11e874bb436b61105653a31d777d.

**Error (including full traceback)**:
```
Training an initial model...
The configuration for policies and pipeline was chosen automatically. It was written into the config file at './config.yml'.
Traceback (most recent call last):
  File "/Users/johannes/miniconda3/envs/rasa-master2/bin/rasa", line 33, in <module>
    sys.exit(load_entry_point('rasa', 'console_scripts', 'rasa')())
  File "/Users/johannes/rasa/rasa/rasa/__main__.py", line 113, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/Users/johannes/rasa/rasa/rasa/cli/scaffold.py", line 215, in run
    init_project(args, path)
  File "/Users/johannes/rasa/rasa/rasa/cli/scaffold.py", line 127, in init_project
    print_train_or_instructions(args, path)
  File "/Users/johannes/rasa/rasa/rasa/cli/scaffold.py", line 67, in print_train_or_instructions
    args.model = rasa.train(domain, config, training_files, output)
  File "/Users/johannes/rasa/rasa/rasa/train.py", line 55, in train
    loop,
  File "/Users/johannes/rasa/rasa/rasa/utils/common.py", line 293, in run_in_loop
    result = loop.run_until_complete(f)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/Users/johannes/rasa/rasa/rasa/train.py", line 110, in train_async
    nlu_additional_arguments=nlu_additional_arguments,
  File "/Users/johannes/rasa/rasa/rasa/train.py", line 197, in _train_async_internal
    async with telemetry.track_model_training(file_importer, model_type="rasa"):
AttributeError: __aexit__
```

**Command or request that led to error**:
```
rasa init
```

**Comment by tmbo** [comment]
fixed on master
