### ISSUE TITLE
Cannot initiate model

### ISSUE THREAD

**Issue by borijang** [RasaHQ/rasa#6710]
**Rasa version**:
2.0.0rc1

**Python version**:
3.8.5

**Operating system** (windows, osx, ...):
Windows 10

**Issue**:
I cannot initiate the base model using rasa init. Installed 2.0.0rc1 using a fresh conda environment, with CUDA 10.1 with CUDNN already installed. The 1.x version initialized and trained just fine.

**Error (including full traceback)**:
```
Finished creating project structure.
? Do you want to train an initial model? 💪🏽  Yes
Training an initial model...
The configuration for pipeline and policies was chosen automatically. It was written into the config file at '.\config.yml'.
2020-09-18 14:06:55 INFO     rasa.model  - Data (core-config) for Core model section changed.
2020-09-18 14:06:55 INFO     rasa.model  - Data (messages) for NLU model section changed.
Training NLU model...
2020-09-18 14:06:59 INFO     rasa.shared.nlu.training_data.training_data  - Training data stats:
2020-09-18 14:06:59 INFO     rasa.shared.nlu.training_data.training_data  - Number of intent examples: 76 (7 distinct intents)

2020-09-18 14:06:59 INFO     rasa.shared.nlu.training_data.training_data  -   Found intents: 'deny', 'affirm', 'greet', 'goodbye', 'mood_great', 'bot_challenge', 'mood_unhappy'
2020-09-18 14:06:59 INFO     rasa.shared.nlu.training_data.training_data  - Number of response examples: 0 (6 distinct responses)
2020-09-18 14:06:59 INFO     rasa.shared.nlu.training_data.training_data  - Number of entity examples: 0 (0 distinct entities)
2020-09-18 14:06:59 INFO     rasa.nlu.model  - Starting to train component WhitespaceTokenizer
2020-09-18 14:06:59 INFO     rasa.nlu.model  - Finished training component.
2020-09-18 14:06:59 INFO     rasa.nlu.model  - Starting to train component RegexFeaturizer
2020-09-18 14:06:59 INFO     rasa.nlu.model  - Finished training component.
2020-09-18 14:06:59 INFO     rasa.nlu.model  - Starting to train component LexicalSyntacticFeaturizer
2020-09-18 14:06:59 INFO     rasa.nlu.model  - Finished training component.
2020-09-18 14:06:59 INFO     rasa.nlu.model  - Starting to train component CountVectorsFeaturizer
2020-09-18 14:06:59 INFO     rasa.nlu.model  - Finished training component.
2020-09-18 14:06:59 INFO     rasa.nlu.model  - Starting to train component CountVectorsFeaturizer
c:\anaconda5.1\envs\chatbot\lib\site-packages\sklearn\feature_extraction\text.py:501: UserWarning: The parameter 'token_pattern' will not be used since 'analyzer' != 'word'
  warnings.warn("The parameter 'token_pattern' will not be used"
2020-09-18 14:06:59 INFO     rasa.nlu.model  - Finished training component.
2020-09-18 14:06:59 INFO     rasa.nlu.model  - Starting to train component DIETClassifier
Traceback (most recent call last):
  File "c:\anaconda5.1\envs\chatbot\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\anaconda5.1\envs\chatbot\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda5.1\envs\chatbot\Scripts\rasa.exe\__main__.py", line 7, in <module>
  File "c:\anaconda5.1\envs\chatbot\lib\site-packages\rasa\__main__.py", line 113, in main
    cmdline_arguments.func(cmdline_arguments)
  File "c:\anaconda5.1\envs\chatbot\lib\site-packages\rasa\cli\scaffold.py", line 218, in run
    init_project(args, path)
  File "c:\anaconda5.1\envs\chatbot\lib\site-packages\rasa\cli\scaffold.py", line 128, in init_project
    print_train_or_instructions(args, path)
  File "c:\anaconda5.1\envs\chatbot\lib\site-packages\rasa\cli\scaffold.py", line 68, in print_train_or_instructions
    args.model = rasa.train(domain, config, training_files, output)
  File "c:\anaconda5.1\envs\chatbot\lib\site-packages\rasa\train.py", line 43, in train
    return rasa.utils.common.run_in_loop(
  File "c:\anaconda5.1\envs\chatbot\lib\site-packages\rasa\utils\common.py", line 293, in run_in_loop
    result = loop.run_until_complete(f)
  File "c:\anaconda5.1\envs\chatbot\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "c:\anaconda5.1\envs\chatbot\lib\site-packages\rasa\train.py", line 102, in train_async
    return await _train_async_internal(
  File "c:\anaconda5.1\envs\chatbot\lib\site-packages\rasa\train.py", line 198, in _train_async_internal
    await _do_training(
  File "c:\anaconda5.1\envs\chatbot\lib\site-packages\rasa\train.py", line 240, in _do_training
    model_path = await _train_nlu_with_validated_data(
  File "c:\anaconda5.1\envs\chatbot\lib\site-packages\rasa\train.py", line 537, in _train_nlu_with_validated_data
    await rasa.nlu.train(
  File "c:\anaconda5.1\envs\chatbot\lib\site-packages\rasa\nlu\train.py", line 114, in train
    interpreter = trainer.train(training_data, **kwargs)
  File "c:\anaconda5.1\envs\chatbot\lib\site-packages\rasa\nlu\model.py", line 208, in train
    updates = component.train(working_data, self.config, **context)
  File "c:\anaconda5.1\envs\chatbot\lib\site-packages\rasa\nlu\classifiers\diet_classifier.py", line 761, in train
    self.model = self._instantiate_model_class(model_data)
  File "c:\anaconda5.1\envs\chatbot\lib\site-packages\rasa\nlu\classifiers\diet_classifier.py", line 1081, in _instantiate_model_class
    return self.model_class()(
  File "c:\anaconda5.1\envs\chatbot\lib\site-packages\rasa\nlu\classifiers\diet_classifier.py", line 1103, in __init__
    super().__init__("DIET", config, data_signature, label_data)
  File "c:\anaconda5.1\envs\chatbot\lib\site-packages\rasa\utils\tensorflow\models.py", line 649, in __init__
    super().__init__(
  File "c:\anaconda5.1\envs\chatbot\lib\site-packages\rasa\utils\tensorflow\models.py", line 83, in __init__
    super().__init__(**kwargs)
  File "c:\anaconda5.1\envs\chatbot\lib\site-packages\tensorflow\python\training\tracking\base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "c:\anaconda5.1\envs\chatbot\lib\site-packages\tensorflow\python\keras\engine\training.py", line 308, in __init__
    self._init_batch_counters()
  File "c:\anaconda5.1\envs\chatbot\lib\site-packages\tensorflow\python\training\tracking\base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "c:\anaconda5.1\envs\chatbot\lib\site-packages\tensorflow\python\keras\engine\training.py", line 317, in _init_batch_counters
    self._train_counter = variables.Variable(0, dtype='int64', aggregation=agg)
  File "c:\anaconda5.1\envs\chatbot\lib\site-packages\tensorflow\python\ops\variables.py", line 262, in __call__
    return cls._variable_v2_call(*args, **kwargs)
  File "c:\anaconda5.1\envs\chatbot\lib\site-packages\tensorflow\python\ops\variables.py", line 244, in _variable_v2_call
    return previous_getter(
  File "c:\anaconda5.1\envs\chatbot\lib\site-packages\tensorflow\python\ops\variables.py", line 237, in <lambda>
    previous_getter = lambda **kws: default_variable_creator_v2(None, **kws)
  File "c:\anaconda5.1\envs\chatbot\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 2633, in default_variable_creator_v2
    return resource_variable_ops.ResourceVariable(
  File "c:\anaconda5.1\envs\chatbot\lib\site-packages\tensorflow\python\ops\variables.py", line 264, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "c:\anaconda5.1\envs\chatbot\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 1507, in __init__
    self._init_from_args(
  File "c:\anaconda5.1\envs\chatbot\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 1661, in _init_from_args
    handle = eager_safe_variable_handle(
  File "c:\anaconda5.1\envs\chatbot\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 242, in eager_safe_variable_handle
    return _variable_handle_from_shape_and_dtype(
  File "c:\anaconda5.1\envs\chatbot\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 174, in _variable_handle_from_shape_and_dtype
    gen_logging_ops._assert(  # pylint: disable=protected-access
  File "c:\anaconda5.1\envs\chatbot\lib\site-packages\tensorflow\python\ops\gen_logging_ops.py", line 49, in _assert
    _ops.raise_from_not_ok_status(e, name)
  File "c:\anaconda5.1\envs\chatbot\lib\site-packages\tensorflow\python\framework\ops.py", line 6843, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: [0] [Op:Assert] name: EagerVariableNameReuse
```

**Command or request that led to error**:
```
rasa init
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @koaning will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by koaning** [comment]
Hi @borijang could you tell us what tensorflow version your got in your virtualenv at this point?

**Comment by borijang** [comment]
Hi @koaning,

Tensorflow version is 2.3.0, automatically installed with the command `pip install rasa[spacy]==2.0.0rc1`.

It is probably helpful to mention that after installing rasa like this, I get the following incompatibility message:

tensorflow-probability 0.10.1 requires cloudpickle==1.3, but you'll have cloudpickle 1.4.1 which is incompatible.
tensorflow 2.3.0 requires gast==0.3.3, but you'll have gast 0.4.0 which is incompatible.
tensorflow 2.3.0 requires numpy<1.19.0,>=1.16.0, but you'll have numpy 1.19.2 which is incompatible.
tensorflow 2.3.0 requires scipy==1.4.1, but you'll have scipy 1.5.2 which is incompatible.
