### ISSUE TITLE
http_timeout on slack when request takes more than 3 seconds

### ISSUE THREAD

**Issue by askushwah** [RasaHQ/rasa#6956]
**Rasa version**: 2.0.0rc2

**Rasa SDK version** (if used & relevant): 2.0.0rc1

**Rasa X version** (if used & relevant):

**Python version**: 3.7.9 (default, Sep 9 2020, 00:09:07)

**Operating system** (windows, osx, ...): Darwin-19.6.0-x86_64-i386-64bit

**Issue**:

Getting http_timeout while fetching the request. I am using action to fetch the data from the backend which takes more then 3 seconds to get the data back (~10-15 sec). I have tried following in credentials.yml file but issue still persists:

```
 X-Slack-Retry-Num: 3
 X-Slack-Retry-Reason: http_timeout
errors_ignore_retry: http_timeout
```

**Error (including full traceback)**:
```
 Received retry #1 request from slack due to http_timeout.
2020-10-07 06:43:00 ERROR    rasa.core.processor  - Encountered an exception while running action 'info'. Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
2020-10-07 06:43:00 DEBUG    rasa.core.processor  - 
Traceback (most recent call last):
  File "/Users/adity/env/lib/python3.7/site-packages/rasa/core/processor.py", line 680, in _run_action
    events = await action.run(output_channel, nlg, tracker, self.domain)
  File "/Users/adity/env/lib/python3.7/site-packages/rasa/core/actions/action.py", line 612, in run
    json=json_body, method="post", timeout=DEFAULT_REQUEST_TIMEOUT
  File "/Users/adity/env/lib/python3.7/site-packages/rasa/utils/endpoints.py", line 151, in request
    **kwargs,
  File "/Users/adity/env/lib/python3.7/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/Users/adity/env/lib/python3.7/site-packages/aiohttp/client.py", line 483, in _request
    timeout=real_timeout
  File "/Users/adity/env/lib/python3.7/site-packages/aiohttp/connector.py", line 523, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/Users/adity/env/lib/python3.7/site-packages/aiohttp/connector.py", line 859, in _create_connection
    req, traces, timeout)
  File "/Users/adity/env/lib/python3.7/site-packages/aiohttp/connector.py", line 967, in _create_direct_connection
    traces=traces), loop=self._loop)
concurrent.futures._base.CancelledError
```

or 

```
2020-10-07 08:50:34 WARNING  connectors.slack_connector  - Received message on unsupported channel: None
2020-10-07 08:50:37 ERROR    rasa.core.processor  - Encountered an exception while running action 'valid_file'. Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
2020-10-07 08:50:37 DEBUG    rasa.core.processor  - 
Traceback (most recent call last):
  File "/Users/adity/env/lib/python3.7/site-packages/rasa/core/processor.py", line 680, in _run_action
    events = await action.run(output_channel, nlg, tracker, self.domain)
  File "/Users/adity/env/lib/python3.7/site-packages/rasa/core/actions/action.py", line 612, in run
    json=json_body, method="post", timeout=DEFAULT_REQUEST_TIMEOUT
  File "/Users/adity/env/lib/python3.7/site-packages/rasa/utils/endpoints.py", line 151, in request
    **kwargs,
  File "/Users/adity/env/lib/python3.7/site-packages/aiohttp/client.py", line 1012, in __aenter__
    self._resp = await self._coro
  File "/Users/adity/env/lib/python3.7/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/Users/adity/env/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 847, in start
    message, payload = await self._protocol.read()  # type: ignore  # noqa
  File "/Users/adity/env/lib/python3.7/site-packages/aiohttp/streams.py", line 591, in read
    await self._waiter
concurrent.futures._base.CancelledError
```

The logs seems to be different but causing the concurrent.futures._base.CancelledError to fail all the time.

**Comment by sara-tagger** [comment]
Thanks for the issue, @rgstephens will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by rgstephens** [comment]
This is not a bug and it's not related to the Slack channel. Let's continue the discussion on this in your [forum post](https://forum.rasa.com/t/http-timeout-in-slack/35450/2).

**Comment by Prostar12** [comment]
@askushwah hi, I had the same problem. How did you deal with it?

**Comment by webdev-rohit** [comment]
Hi @rgstephens @askushwah were you able to find any workaround or solution to the slack http_timeout issue?
