### ISSUE TITLE
Rasa Interactive doesn't work after rasa init -- no changes made

### ISSUE THREAD

**Issue by Aiodhan** [RasaHQ/rasa#6970]
**Rasa version**: 1.10.14

**Python version**:  3.7

**Operating system** (windows, osx, ...): windows 10

**Issue**:  Rasa Interactive doesn't work after rasa init -- no changes made

**Error (including full traceback)**:
```
(engtestv2) C:\Users\pruth\Downloads\engtestv2>rasa interactive
Nothing changed. You can use the old model stored at 'C:\Users\pruth\Downloads\engtestv2\models\20201008-190557.tar.gz'.
2020-10-08 19:13:15.765484: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (303)
2020-10-08 19:13:19 INFO     root  - Rasa server is up and running.
2020-10-08 19:13:21 ERROR    rasa.core.training.interactive  - Failed to connect to Rasa Core server at 'http://localhost:5005'. Is the server running?
Traceback (most recent call last):
  File "c:\users\pruth\anaconda3\lib\site-packages\rasa\core\training\interactive.py", line 1383, in record_messages
    domain = await retrieve_domain(endpoint)
  File "c:\users\pruth\anaconda3\lib\site-packages\rasa\core\training\interactive.py", line 159, in retrieve_domain
    method="get", subpath="/domain", headers={"Accept": "application/json"}
  File "c:\users\pruth\anaconda3\lib\site-packages\rasa\utils\endpoints.py", line 154, in request
    response.status, response.reason, await response.content.read()
rasa.utils.endpoints.ClientResponseError: 500, INTERNAL SERVER ERROR, body='b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"\n  "http://www.w3.org/TR/html4/loose.dtd">\n<html>\n  <head>\n    <title>NameError: name \'HTML_TEMPLATE\' is not defined // Werkzeug Debugger</title>\n    <link rel="stylesheet" href="?__debugger__=yes&amp;cmd=resource&amp;f=style.css"\n        type="text/css">\n    <!-- We need to make sure this has a favicon so that the debugger does\n         not by accident trigger a request to /favicon.ico which might\n         change the application state. -->\n    <link rel="shortcut icon"\n        href="?__debugger__=yes&amp;cmd=resource&amp;f=console.png">\n    <script src="?__debugger__=yes&amp;cmd=resource&amp;f=jquery.js"></script>\n    <script src="?__debugger__=yes&amp;cmd=resource&amp;f=debugger.js"></script>\n    <script type="text/javascript">\n      var TRACEBACK = 1155457427848,\n          CONSOLE_MODE = false,\n          EVALEX = true,\n          EVALEX_TRUSTED = false,\n          SECRET = "6tpuQCTvXfFylbVnZPA0";\n    </script>\n  </head>\n  <body style="background-color: #fff">\n    <div class="debugger">\n<h1>NameError</h1>\n<div class="detail">\n  <p class="errormsg">NameError: name \'HTML_TEMPLATE\' is not defined</p>\n</div>\n<h2 class="traceback">Traceback <em>(most recent call last)</em></h2>\n<div class="traceback">\n  \n  <ul><li><div class="frame" id="frame-1155457443912">\n  <h4>File <cite class="filename">"C:\\Users\\pruth\\anaconda3\\lib\\site-packages\\flask\\app.py"</cite>,\n      line <em class="line">2464</em>,\n      in <code class="function">__call__</code></h4>\n  <div class="source library"><pre class="line before"><span class="ws"></span> </pre>\n<pre class="line before"><span class="ws">    </span>def __call__(self, environ, start_response):</pre>\n<pre class="line before"><span class="ws">        </span>&quot;&quot;&quot;The WSGI server calls the Flask application object as the</pre>\n<pre class="line before"><span class="ws">        </span>WSGI application. This calls :meth:`wsgi_app` which can be</pre>\n<pre class="line before"><span class="ws">        </span>wrapped to applying middleware.&quot;&quot;&quot;</pre>\n<pre class="line current"><span class="ws">        </span>return self.wsgi_app(environ, start_response)</pre>\n<pre class="line after"><span class="ws"></span> </pre>\n<pre class="line after"><span class="ws">    </span>def __repr__(self):</pre>\n<pre class="line after"><span class="ws">        </span>return &quot;&lt;%s %r&gt;&quot; % (self.__class__.__name__, self.name)</pre></div>\n</div>\n\n<li><div class="frame" id="frame-1155457445384">\n  <h4>File <cite class="filename">"C:\\Users\\pruth\\anaconda3\\lib\\site-packages\\flask\\app.py"</cite>,\n      line <em class="line">2450</em>,\n      in <code class="function">wsgi_app</code></h4>\n  <div class="source library"><pre class="line before"><span class="ws">            </span>try:</pre>\n<pre class="line before"><span class="ws">                </span>ctx.push()</pre>\n<pre class="line before"><span class="ws">                </span>response = self.full_dispatch_request()</pre>\n<pre class="line before"><span class="ws">            </span>except Exception as e:</pre>\n<pre class="line before"><span class="ws">                </span>error = e</pre>\n<pre class="line current"><span class="ws">                </span>response = self.handle_exception(e)</pre>\n<pre class="line after"><span class="ws">            </span>except:  # noqa: B001</pre>\n<pre class="line after"><span class="ws">                </span>error = sys.exc_info()[1]</pre>\n<pre class="line after"><span class="ws">                </span>raise</pre>\n<pre class="line after"><span class="ws">            </span>return response(environ, start_response)</pre>\n<pre class="line after"><span class="ws">        </span>finally:</pre></div>\n</div>\n\n<li><div class="frame" id="frame-1155457442568">\n  <h4>File <cite class="filename">"C:\\Users\\pruth\\anaconda3\\lib\\site-packages\\flask\\app.py"</cite>,\n      line <em class="line">1867</em>,\n      in <code class="function">handle_exception</code></h4>\n  <div class="source library"><pre class="line before"><span class="ws">            </span># if we want to repropagate the exception, we can attempt to</pre>\n<pre class="line before"><span class="ws">            </span># raise it with the whole traceback in case we can do that</pre>\n<pre class="line before"><span class="ws">            </span># (the function was actually called from the except part)</pre>\n<pre class="line before"><span class="ws">            </span># otherwise, we just raise the error again</pre>\n<pre class="line before"><span class="ws">            </span>if exc_value is e:</pre>\n<pre class="line current"><span class="ws">                </span>reraise(exc_type, exc_value, tb)</pre>\n<pre class="line after"><span class="ws">            </span>else:</pre>\n<pre class="line after"><span class="ws">                </span>raise e</pre>\n<pre class="line after"><span class="ws"></span> </pre>\n<pre class="line after"><span class="ws">        </span>self.log_exception((exc_type, exc_value, tb))</pre>\n<pre class="line after"><span class="ws">        </span>server_error = InternalServerError()</pre></div>\n</div>\n\n<li><div class="frame" id="frame-1155457444360">\n  <h4>File <cite class="filename">"C:\\Users\\pruth\\anaconda3\\lib\\site-packages\\flask\\_compat.py"</cite>,\n      line <em class="line">39</em>,\n      in <code class="function">reraise</code></h4>\n  <div class="source library"><pre class="line before"><span class="ws">    </span>import collections.abc as collections_abc</pre>\n<pre class="line before"><span class="ws"></span> </pre>\n<pre class="line before"><span class="ws">    </span>def reraise(tp, value, tb=None):</pre>\n<pre class="line before"><span class="ws">        </span>if value.__traceback__ is not tb:</pre>\n<pre class="line before"><span class="ws">            </span>raise value.with_traceback(tb)</pre>\n<pre class="line current"><span class="ws">        </span>raise value</pre>\n<pre class="line after"><span class="ws"></span> </pre>\n<pre class="line after"><span class="ws">    </span>implements_to_string = _identity</pre>\n<pre class="line after"><span class="ws"></span> </pre>\n<pre class="line after"><span class="ws"></span>else:</pre>\n<pre class="line after"><span class="ws">    </span>iterkeys = lambda d: d.iterkeys()</pre></div>\n</div>\n\n<li><div class="frame" id="frame-1155457442824">\n  <h4>File <cite class="filename">"C:\\Users\\pruth\\anaconda3\\lib\\site-packages\\flask\\app.py"</cite>,\n      line <em class="line">2447</em>,\n      in <code class="function">wsgi_app</code></h4>\n  <div class="source library"><pre class="line before"><span class="ws">        </span>ctx = self.request_context(environ)</pre>\n<pre class="line before"><span class="ws">        </span>error = None</pre>\n<pre class="line before"><span class="ws">        </span>try:</pre>\n<pre class="line before"><span class="ws">            </span>try:</pre>\n<pre class="line before"><span class="ws">                </span>ctx.push()</pre>\n<pre class="line current"><span class="ws">                </span>response = self.full_dispatch_request()</pre>\n<pre class="line after"><span class="ws">            </span>except Exception as e:</pre>\n<pre class="line after"><span class="ws">                </span>error = e</pre>\n<pre class="line after"><span class="ws">                </span>response = self.handle_exception(e)</pre>\n<pre class="line after"><span class="ws">            </span>except:  # noqa: B001</pre>\n<pre class="line after"><span class="ws">                </span>error = sys.exc_info()[1]</pre></div>\n</div>\n\n<li><div class="frame" id="frame-1155457442888">\n  <h4>File <cite class="filename">"C:\\Users\\pruth\\anaconda3\\lib\\site-packages\\flask\\app.py"</cite>,\n      line <em class="line">1952</em>,\n      in <code class="function">full_dispatch_request</code></h4>\n  <div class="source library"><pre class="line before"><span class="ws">            </span>request_started.send(self)</pre>\n<pre class="line before"><span class="ws">            </span>rv = self.preprocess_request()</pre>\n<pre class="line before"><span class="ws">            </span>if rv is None:</pre>\n<pre class="line before"><span class="ws">                </span>rv = self.dispatch_request()</pre>\n<pre class="line before"><span class="ws">        </span>except Exception as e:</pre>\n<pre class="line current"><span class="ws">            </span>rv = self.handle_user_exception(e)</pre>\n<pre class="line after"><span class="ws">        </span>return self.finalize_request(rv)</pre>\n<pre class="line after"><span class="ws"></span> </pre>\n<pre class="line after"><span class="ws">    </span>def finalize_request(self, rv, from_error_handler=False):</pre>\n<pre class="line after"><span class="ws">        </span>&quot;&quot;&quot;Given the return value from a view function this finalizes</pre>\n<pre class="line after"><span class="ws">        </span>the request by converting it into a response and invoking the</pre></div>\n</div>\n\n<li><div class="frame" id="frame-1155457443848">\n  <h4>File <cite class="filename">"C:\\Users\\pruth\\anaconda3\\lib\\site-packages\\flask\\app.py"</cite>,\n      line <em class="line">1821</em>,\n      in <code class="function">handle_user_exception</code></h4>\n  <div class="source library"><pre class="line before"><span class="ws">            </span>return self.handle_http_exception(e)</pre>\n<pre class="line before"><span class="ws"></span> </pre>\n<pre class="line before"><span class="ws">        </span>handler = self._find_error_handler(e)</pre>\n<pre class="line before"><span class="ws"></span> </pre>\n<pre class="line before"><span class="ws">        </span>if handler is None:</pre>\n<pre class="line current"><span class="ws">            </span>reraise(exc_type, exc_value, tb)</pre>\n<pre class="line after"><span class="ws">        </span>return handler(e)</pre>\n<pre class="line after"><span class="ws"></span> </pre>\n<pre class="line after"><span class="ws">    </span>def handle_exception(self, e):</pre>\n<pre class="line after"><span class="ws">        </span>&quot;&quot;&quot;Handle an exception that did not have an error handler</pre>\n<pre class="line after"><span class="ws">        </span>associated with it, or that was raised from an error handler.</pre></div>\n</div>\n\n<li><div class="frame" id="frame-1155457444040">\n  <h4>File <cite class="filename">"C:\\Users\\pruth\\anaconda3\\lib\\site-packages\\flask\\_compat.py"</cite>,\n      line <em class="line">39</em>,\n      in <code class="function">reraise</code></h4>\n  <div class="source library"><pre class="line before"><span class="ws">    </span>import collections.abc as collections_abc</pre>\n<pre class="line before"><span class="ws"></span> </pre>\n<pre class="line before"><span class="ws">    </span>def reraise(tp, value, tb=None):</pre>\n<pre class="line before"><span class="ws">        </span>if value.__traceback__ is not tb:</pre>\n<pre class="line before"><span class="ws">            </span>raise value.with_traceback(tb)</pre>\n<pre class="line current"><span class="ws">        </span>raise value</pre>\n<pre class="line after"><span class="ws"></span> </pre>\n<pre class="line after"><span class="ws">    </span>implements_to_string = _identity</pre>\n<pre class="line after"><span class="ws"></span> </pre>\n<pre class="line after"><span class="ws"></span>else:</pre>\n<pre class="line after"><span class="ws">    </span>iterkeys = lambda d: d.iterkeys()</pre></div>\n</div>\n\n<li><div class="frame" id="frame-1155457441928">\n  <h4>File <cite class="filename">"C:\\Users\\pruth\\anaconda3\\lib\\site-packages\\flask\\app.py"</cite>,\n      line <em class="line">1950</em>,\n      in <code class="function">full_dispatch_request</code></h4>\n  <div class="source library"><pre class="line before"><span class="ws">        </span>self.try_trigger_before_first_request_functions()</pre>\n<pre class="line before"><span class="ws">        </span>try:</pre>\n<pre class="line before"><span class="ws">            </span>request_started.send(self)</pre>\n<pre class="line before"><span class="ws">            </span>rv = self.preprocess_request()</pre>\n<pre class="line before"><span class="ws">            </span>if rv is None:</pre>\n<pre class="line current"><span class="ws">                </span>rv = self.dispatch_request()</pre>\n<pre class="line after"><span class="ws">        </span>except Exception as e:</pre>\n<pre class="line after"><span class="ws">            </span>rv = self.handle_user_exception(e)</pre>\n<pre class="line after"><span class="ws">        </span>return self.finalize_request(rv)</pre>\n<pre class="line after"><span class="ws"></span> </pre>\n<pre class="line after"><span class="ws">    </span>def finalize_request(self, rv, from_error_handler=False):</pre></div>\n</div>\n\n<li><div class="frame" id="frame-1155457442056">\n  <h4>File <cite class="filename">"C:\\Users\\pruth\\anaconda3\\lib\\site-packages\\flask\\app.py"</cite>,\n      line <em class="line">1936</em>,\n      in <code class="function">dispatch_request</code></h4>\n  <div class="source library"><pre class="line before"><span class="ws">            </span>getattr(rule, &quot;provide_automatic_options&quot;, False)</pre>\n<pre class="line before"><span class="ws">            </span>and req.method == &quot;OPTIONS&quot;</pre>\n<pre class="line before"><span class="ws">        </span>):</pre>\n<pre class="line before"><span class="ws">            </span>return self.make_default_options_response()</pre>\n<pre class="line before"><span class="ws">        </span># otherwise dispatch to the handler for that endpoint</pre>\n<pre class="line current"><span class="ws">        </span>return self.view_functions[rule.endpoint](**req.view_args)</pre>\n<pre class="line after"><span class="ws"></span> </pre>\n<pre class="line after"><span class="ws">    </span>def full_dispatch_request(self):</pre>\n<pre class="line after"><span class="ws">        </span>&quot;&quot;&quot;Dispatches the request and on top of that performs request</pre>\n<pre class="line after"><span class="ws">        </span>pre and postprocessing as well as HTTP exception catching and</pre>\n<pre class="line after"><span class="ws">        </span>error handling.</pre></div>\n</div>\n\n<li><div class="frame" id="frame-1155457445448">\n  <h4>File <cite class="filename">"C:\\Users\\pruth\\Downloads\\laptop\\psychsurvey\\psych\\views.py"</cite>,\n      line <em class="line">90</em>,\n      in <code class="function">some_place_page</code></h4>\n  <div class="source "><pre class="line before"><span class="ws"></span> </pre>\n<pre class="line before"><span class="ws"></span> </pre>\n<pre class="line before"><span class="ws"></span> </pre>\n<pre class="line before"><span class="ws"></span>@app.route(\'/&lt;cand_id&gt;\')</pre>\n<pre class="line before"><span class="ws"></span>def some_place_page(cand_id):</pre>\n<pre class="line current"><span class="ws">    </span>return(HTML_TEMPLATE.substitute(place_name=some_place))</pre></div>\n</div>\n</ul>\n  <blockquote>NameError: name \'HTML_TEMPLATE\' is not defined</blockquote>\n</div>\n\n<div class="plain">\n  <form action="/?__debugger__=yes&amp;cmd=paste" method="post">\n    <p>\n      <input type="hidden" name="language" value="pytb">\n      This is the Copy/Paste friendly version of the traceback.  <span\n      class="pastemessage">You can also paste this traceback into\n      a <a href="https://gist.github.com/">gist</a>:\n      <input type="submit" value="create paste"></span>\n    </p>\n    <textarea cols="50" rows="10" name="code" readonly>Traceback (most recent call last):\n  File &quot;C:\\Users\\pruth\\anaconda3\\lib\\site-packages\\flask\\app.py&quot;, line 2464, in __call__\n    return self.wsgi_app(environ, start_response)\n  File &quot;C:\\Users\\pruth\\anaconda3\\lib\\site-packages\\flask\\app.py&quot;, line 2450, in wsgi_app\n    response = self.handle_exception(e)\n  File &quot;C:\\Users\\pruth\\anaconda3\\lib\\site-packages\\flask\\app.py&quot;, line 1867, in handle_exception\n    reraise(exc_type, exc_value, tb)\n  File &quot;C:\\Users\\pruth\\anaconda3\\lib\\site-packages\\flask\\_compat.py&quot;, line 39, in reraise\n    raise value\n  File &quot;C:\\Users\\pruth\\anaconda3\\lib\\site-packages\\flask\\app.py&quot;, line 2447, in wsgi_app\n    response = self.full_dispatch_request()\n  File &quot;C:\\Users\\pruth\\anaconda3\\lib\\site-packages\\flask\\app.py&quot;, line 1952, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File &quot;C:\\Users\\pruth\\anaconda3\\lib\\site-packages\\flask\\app.py&quot;, line 1821, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File &quot;C:\\Users\\pruth\\anaconda3\\lib\\site-packages\\flask\\_compat.py&quot;, line 39, in reraise\n    raise value\n  File &quot;C:\\Users\\pruth\\anaconda3\\lib\\site-packages\\flask\\app.py&quot;, line 1950, in full_dispatch_request\n    rv = self.dispatch_request()\n  File &quot;C:\\Users\\pruth\\anaconda3\\lib\\site-packages\\flask\\app.py&quot;, line 1936, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File &quot;C:\\Users\\pruth\\Downloads\\laptop\\psychsurvey\\psych\\views.py&quot;, line 90, in some_place_page\n    return(HTML_TEMPLATE.substitute(place_name=some_place))\nNameError: name \'HTML_TEMPLATE\' is not defined</textarea>\n  </form>\n</div>\n<div class="explanation">\n  The debugger caught an exception in your WSGI application.  You can now\n  look at the traceback which led to the error.  <span class="nojavascript">\n  If you enable JavaScript you can also use additional features such as code\n  execution (if the evalex feature is enabled), automatic pasting of the\n  exceptions and much more.</span>\n</div>\n      <div class="footer">\n        Brought to you by <strong class="arthur">DON\'T PANIC</strong>, your\n        friendly Werkzeug powered traceback interpreter.\n      </div>\n    </div>\n\n    <div class="pin-prompt">\n      <div class="inner">\n        <h3>Console Locked</h3>\n        <p>\n          The console is locked and needs to be unlocked by entering the PIN.\n          You can find the PIN printed out on the standard output of your\n          shell that runs the server.\n        <form>\n          <p>PIN:\n            <input type=text name=pin size=14>\n            <input type=submit name=btn value="Confirm Pin">\n        </form>\n      </div>\n    </div>\n  </body>\n</html>\n\n<!--\n\nTraceback (most recent call last):\n  File "C:\\Users\\pruth\\anaconda3\\lib\\site-packages\\flask\\app.py", line 2464, in __call__\n    return self.wsgi_app(environ, start_response)\n  File "C:\\Users\\pruth\\anaconda3\\lib\\site-packages\\flask\\app.py", line 2450, in wsgi_app\n    response = self.handle_exception(e)\n  File "C:\\Users\\pruth\\anaconda3\\lib\\site-packages\\flask\\app.py", line 1867, in handle_exception\n    reraise(exc_type, exc_value, tb)\n  File "C:\\Users\\pruth\\anaconda3\\lib\\site-packages\\flask\\_compat.py", line 39, in reraise\n    raise value\n  File "C:\\Users\\pruth\\anaconda3\\lib\\site-packages\\flask\\app.py", line 2447, in wsgi_app\n    response = self.full_dispatch_request()\n  File "C:\\Users\\pruth\\anaconda3\\lib\\site-packages\\flask\\app.py", line 1952, in full_dispatch_request\n    rv = self.handle_user_exception(e)\n  File "C:\\Users\\pruth\\anaconda3\\lib\\site-packages\\flask\\app.py", line 1821, in handle_user_exception\n    reraise(exc_type, exc_value, tb)\n  File "C:\\Users\\pruth\\anaconda3\\lib\\site-packages\\flask\\_compat.py", line 39, in reraise\n    raise value\n  File "C:\\Users\\pruth\\anaconda3\\lib\\site-packages\\flask\\app.py", line 1950, in full_dispatch_request\n    rv = self.dispatch_request()\n  File "C:\\Users\\pruth\\anaconda3\\lib\\site-packages\\flask\\app.py", line 1936, in dispatch_request\n    return self.view_functions[rule.endpoint](**req.view_args)\n  File "C:\\Users\\pruth\\Downloads\\laptop\\psychsurvey\\psych\\views.py", line 90, in some_place_page\n    return(HTML_TEMPLATE.substitute(place_name=some_place))\nNameError: name \'HTML_TEMPLATE\' is not defined\n\n-->\n''
2020-10-08 19:13:21 INFO     rasa.core.training.interactive  - Killing Sanic server now.
```

**Command or request that led to error**:
```
1. pip install rasa=1.10.14
2. rasa init
3. rasa run actions
4. rasa interactive
```
No file has been edited.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @TyDunn will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by TyDunn** [comment]
@Aiodhan Did you [install in a clean virtual environment](https://www.youtube.com/watch?v=4ewIABo0OkU)? Do you see the same issues with [Rasa Open Source 2.0](https://forum.rasa.com/t/rasa-open-source-2-0-is-out-now/35577)?

**Comment by wochinge** [comment]
If this is still a problem, please re-open.
