### ISSUE TITLE
Improve logging messages for file format recognition during training 

### ISSUE THREAD

**Issue by melindaloubser1** [RasaHQ/rasa#7000]
**Description of Problem**:
`rasa train --debug` will show the following output for legitimate NLU, stories, and rules files:

```
2020-10-13 10:56:27 DEBUG    rasa.shared.nlu.training_data.loading  - Training data format of 'data/nlu.yml' is 'rasa_yml'.
2020-10-13 10:56:27 DEBUG    rasa.shared.nlu.training_data.loading  - Training data format of 'data/rules.yml' is 'unk'.
2020-10-13 10:56:27 DEBUG    rasa.shared.nlu.training_data.loading  - Training data format of 'data/stories.yml' is 'unk'
```

This makes it sound like rules.yml and stories.yml are not correctly formatted. 

**Overview of the Solution**:
For NLU data loading the log message could say e.g. `Training data format of `data/rules.yml` is not NLU` or something that makes it clearer 

**Definition of Done**:
- [ ] Log message changed

**Comment by petasis** [comment]
In some cases, you may also get an error:

2020-10-13 12:31:19 DEBUG    rasa.shared.nlu.training_data.loading  - Training data format of 'data/nlu.yml' is 'rasa_yml'.
2020-10-13 12:31:23 DEBUG    rasa.shared.nlu.training_data.loading  - Training data format of 'data/responses.yml' is 'rasa_yml'.
2020-10-13 12:31:23 DEBUG    rasa.shared.nlu.training_data.loading  - Training data format of 'data/rules.yml' is 'unk'.
2020-10-13 12:31:23 DEBUG    rasa.shared.nlu.training_data.loading  - Training data format of 'data/stories.yml' is 'rasa_yml'.
2020-10-13 12:31:23 DEBUG    rasa.shared.nlu.training_data.loading  - Training data format of 'data/lookup/airline.el.yml' is 'rasa_yml'.
2020-10-13 12:31:23 DEBUG    rasa.shared.nlu.training_data.loading  - Training data format of 'data/lookup/airline.yml' is 'rasa_yml'.
2020-10-13 12:31:23 DEBUG    rasa.shared.nlu.training_data.loading  - Training data format of 'data/lookup/city.yml' is 'rasa_yml'.
2020-10-13 12:31:23 DEBUG    rasa.shared.nlu.training_data.loading  - Training data format of 'data/lookup/flight_statuses.json' is 'unk'.
2020-10-13 12:31:23 DEBUG    rasa.shared.nlu.training_data.loading  - Training data format of 'data/lookup/flying.yml' is 'rasa_yml'.
2020-10-13 12:31:23 DEBUG    rasa.shared.nlu.training_data.loading  - Training data format of 'data/lookup/time.yml' is 'rasa_yml'.
2020-10-13 12:31:30 DEBUG    rasa.shared.nlu.training_data.loading  - Training data format of 'data/lookup/airline.el.yml' is 'rasa_yml'.
2020-10-13 12:31:30 DEBUG    rasa.shared.nlu.training_data.loading  - Training data format of 'data/lookup/airline.yml' is 'rasa_yml'.
2020-10-13 12:31:30 DEBUG    rasa.shared.nlu.training_data.loading  - Training data format of 'data/lookup/city.yml' is 'rasa_yml'.
2020-10-13 12:31:30 DEBUG    rasa.shared.nlu.training_data.loading  - Training data format of 'data/lookup/flying.yml' is 'rasa_yml'.
2020-10-13 12:31:30 DEBUG    rasa.shared.nlu.training_data.loading  - Training data format of 'data/lookup/time.yml' is 'rasa_yml'.
2020-10-13 12:31:30 DEBUG    rasa.shared.nlu.training_data.loading  - Training data format of 'data/nlu.yml' is 'rasa_yml'.
2020-10-13 12:31:43 DEBUG    rasa.shared.nlu.training_data.loading  - Training data format of 'data/responses.yml' is 'rasa_yml'.
2020-10-13 12:32:06 DEBUG    rasa.shared.nlu.training_data.loading  - Training data format of 'data/stories.yml' is 'unk'.
Traceback (most recent call last):
  File "/home/pepper/.local/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/home/pepper/.local/lib/python3.8/site-packages/rasa/__main__.py", line 116, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/home/pepper/.local/lib/python3.8/site-packages/rasa/cli/train.py", line 81, in train
    return rasa.train(
  File "/home/pepper/.local/lib/python3.8/site-packages/rasa/train.py", line 43, in train
    return rasa.utils.common.run_in_loop(
  File "/home/pepper/.local/lib/python3.8/site-packages/rasa/utils/common.py", line 308, in run_in_loop
    result = loop.run_until_complete(f)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/home/pepper/.local/lib/python3.8/site-packages/rasa/train.py", line 95, in train_async
    domain = await file_importer.get_domain()
  File "/home/pepper/.local/lib/python3.8/site-packages/rasa/shared/utils/common.py", line 119, in decorated
    return await cache.cached_result()
  File "/home/pepper/.local/lib/python3.8/site-packages/rasa/shared/importers/importer.py", line 440, in get_domain
    original, e2e_domain = await asyncio.gather(
  File "/home/pepper/.local/lib/python3.8/site-packages/rasa/shared/utils/common.py", line 119, in decorated
    return await cache.cached_result()
  File "/home/pepper/.local/lib/python3.8/site-packages/rasa/shared/importers/importer.py", line 315, in get_domain
    existing_nlu_data = await self._importer.get_nlu_data()
  File "/home/pepper/.local/lib/python3.8/site-packages/rasa/shared/utils/common.py", line 119, in decorated
    return await cache.cached_result()
  File "/home/pepper/.local/lib/python3.8/site-packages/rasa/shared/importers/importer.py", line 289, in get_nlu_data
    nlu_data = await asyncio.gather(*nlu_data)
  File "/home/pepper/.local/lib/python3.8/site-packages/rasa/shared/importers/rasa.py", line 58, in get_nlu_data
    return utils.training_data_from_paths(self._nlu_files, language)
  File "/home/pepper/.local/lib/python3.8/site-packages/rasa/shared/importers/utils.py", line 11, in training_data_from_paths
    training_data_sets = [loading.load_data(nlu_file, language) for nlu_file in paths]
  File "/home/pepper/.local/lib/python3.8/site-packages/rasa/shared/importers/utils.py", line 11, in <listcomp>
    training_data_sets = [loading.load_data(nlu_file, language) for nlu_file in paths]
  File "/home/pepper/.local/lib/python3.8/site-packages/rasa/shared/nlu/training_data/loading.py", line 60, in load_data
    data_sets = [_load(f, language) for f in files]
  File "/home/pepper/.local/lib/python3.8/site-packages/rasa/shared/nlu/training_data/loading.py", line 60, in <listcomp>
    data_sets = [_load(f, language) for f in files]
  File "/home/pepper/.local/lib/python3.8/site-packages/rasa/shared/nlu/training_data/loading.py", line 107, in _load
    raise ValueError(f"Unknown data format for file '{filename}'.")
ValueError: Unknown data format for file 'data/stories.yml'.

**Comment by nikopetr** [comment]
Hello, is this still open can I contribute for this?

**Comment by petasis** [comment]
Yes, it is open.

**Comment by mbslet** [comment]
Hey @melindaloubser1 , just to make it clear, the expected output message for stories.yml and rules.yml lines is for example: Training data format of 'data/stories.yml' is not NLU?

**Comment by melindaloubser1** [comment]
I believe @degiz is working on this  - the log message is just an example. It could say anything that indicated that the file format was not valid **for NLU** vs. invalid in general (which is how it sounds at the moment)

**Comment by wochinge** [comment]
@degiz What's the state of this issue?

**Comment by BornaGajic** [comment]
Hi, I'm getting 'unk' for my `stories.yml` file even though the indentations and new lines are correct. In the end `rasa train` does train the model without errors. Could it pose a problem in the future? If so what should I do?
