### ISSUE TITLE
Training with Multiproject Importer gives UnicodeDecodeError in Rasa 2.0

### ISSUE THREAD

**Issue by tomgun132** [RasaHQ/rasa#7003]
**Rasa version**: 2.0

**Python version**: 3.7

**Operating system** (windows, osx, ...): Windows

**Issue**: When using multiproject importer and there is any non-text file such as compressed `tar.gz` file under the directories in `config.yml`, it gives `UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte` .

It seems like compared to previous version, Rasa 2.0 does another file read process after `ValueError` exception under `guess_format` function while on the previous version it doesn't.

**Error (including full traceback)**:

 Traceback (most recent call last):
 File "c:\users\anaconda3\lib\site-packages\rasa\shared\nlu\training_data\loading.py", line 134, in guess_format
 content = rasa.shared.utils.io.read_file(filename)
 File "c:\users\anaconda3\lib\site-packages\rasa\shared\utils\io.py", line 118, in read_file
 return f.read()
 File "c:\users\anaconda3\lib\codecs.py", line 322, in decode
 (result, consumed) = self._buffer_decode(data, self.errors, final)
 UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
 File "c:\users\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
 "__main__", mod_spec)
 File "c:\users\anaconda3\lib\runpy.py", line 85, in _run_code
 exec(code, run_globals)
 File "C:\Users\anaconda3\Scripts\rasa.exe__main__.py", line 7, in <module>
 File "c:\users\anaconda3\lib\site-packages\rasa__main__.py", line 116, in main
 cmdline_arguments.func(cmdline_arguments)
 File "c:\users\anaconda3\lib\site-packages\rasa\cli\train.py", line 90, in train
 nlu_additional_arguments=extract_nlu_additional_arguments(args),
 File "c:\users\anaconda3\lib\site-packages\rasa\train.py", line 55, in train
 loop,
 File "c:\users\anaconda3\lib\site-packages\rasa\utils\common.py", line 308, in run_in_loop
 result = loop.run_until_complete(f)
 File "c:\users\anaconda3\lib\asyncio\base_events.py", line 583, in run_until_complete
 return future.result()
 File "c:\users\anaconda3\lib\site-packages\rasa\train.py", line 90, in train_async
 config, domain, training_files
 File "c:\users\anaconda3\lib\site-packages\rasa\shared\importers\importer.py", line 86, in load_from_config
 config, config_path, domain_path, training_data_paths, training_type
 File "c:\users\anaconda3\lib\site-packages\rasa\shared\importers\importer.py", line 146, in load_from_dict
 for importer in importers
 File "c:\users\anaconda3\lib\site-packages\rasa\shared\importers\importer.py", line 146, in <listcomp>
 for importer in importers
 File "c:\users\anaconda3\lib\site-packages\rasa\shared\importers\importer.py", line 190, in _importer_from_dict
 config_path, domain_path, training_data_paths, **constructor_arguments
 File "c:\users\anaconda3\lib\site-packages\rasa\shared\importers\multi_project.py", line 38, in __init__
 self._init_from_dict(self.config, self._project_directory)
 File "c:\users\anaconda3\lib\site-packages\rasa\shared\importers\multi_project.py", line 89, in _init_from_dict
 self._init_from_path(p)
 File "c:\users\anaconda3\lib\site-packages\rasa\shared\importers\multi_project.py", line 59, in _init_from_path
 self._init_from_directory(path)
 File "c:\users\anaconda3\lib\site-packages\rasa\shared\importers\multi_project.py", line 106, in _init_from_directory
 elif rasa.shared.data.is_nlu_file(full_path):
 File "c:\users\anaconda3\lib\site-packages\rasa\shared\data.py", line 201, in is_nlu_file
 return nlu_loading.guess_format(file_path) != nlu_loading.UNK
 File "c:\users\anaconda3\lib\site-packages\rasa\shared\nlu\training_data\loading.py", line 137, in guess_format
 if MarkdownReader.is_markdown_nlu_file(filename):
 File "c:\users\anaconda3\lib\site-packages\rasa\shared\nlu\training_data\formats\markdown.py", line 177, in is_markdown_nlu_file
 content = rasa.shared.utils.io.read_file(filename)
 File "c:\users\anaconda3\lib\site-packages\rasa\shared\utils\io.py", line 118, in read_file
 return f.read()
 File "c:\users\anaconda3\lib\codecs.py", line 322, in decode
 (result, consumed) = self._buffer_decode(data, self.errors, final)
 UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte

**Command or request that led to error**:

 rasa train

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @tmbo will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
