### ISSUE TITLE
Rasa interactive cannot write non-ascii character due to the encoing

### ISSUE THREAD

**Issue by matthewkos** [RasaHQ/rasa#7005]
**Rasa version**: 1.10, 2.*

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**: 3.7.6

**Operating system** (windows, osx, ...): Windows

**Issue**:
The rasa interactive write file write with the default encoding, for windows python, it may cause error if the user type utf-8 character.

**Error (including full traceback)**:
```
Traceback (most recent call last):
  File "e:\env\anaconda\envs\rasa\lib\site-packages\rasa\core\training\interactive.py", line 1465, in record_messages
    plot_file,
  File "e:\env\anaconda\envs\rasa\lib\site-packages\rasa\core\training\interactive.py", line 949, in _predict_till_next_listen
    unconfirmed=[ActionExecuted(action_name)],
  File "e:\env\anaconda\envs\rasa\lib\site-packages\rasa\core\training\interactive.py", line 1394, in _plot_trackers
    write_dot(graph, output_file)
  File "<decorator-gen-781>", line 2, in write_dot
  File "e:\env\anaconda\envs\rasa\lib\site-packages\networkx\utils\decorators.py", line 240, in _open_file
    result = func_to_be_decorated(*new_args, **kwargs)
  File "e:\env\anaconda\envs\rasa\lib\site-packages\networkx\drawing\nx_pydot.py", line 47, in write_dot
    path.write(P.to_string())
UnicodeEncodeError: 'cp950' codec can't encode character '\u5605' in position 505: illegal multibyte sequence
```

**Command or request that led to error**:
```

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Solution**:
change rasa/core/training/interactive.py : 1394
```
   write_dot(graph, output_file)
```
to
```
    output_file = open(output_file, 'w', encoding='utf-8')
    write_dot(graph, output_file)
    output_file.close()
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @rgstephens will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
