### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte when using MultiProjectImporter with Rasa2.0

### ISSUE THREAD

**Issue by theresazobel** [RasaHQ/rasa#7025]
**Rasa version**:

 Rasa Version : 2.0.0
 Rasa SDK Version : 2.0.0
 Rasa X Version : None
 Python Version : 3.7.6 (default, Mar 3 2020, 09:56:13)
 Operating System : Darwin-19.6.0-x86_64-i386-64bit
 Python Path : /usr/local/opt/python/bin/python3.7

**Issue** I am using the "experimental" feature _MultiProjectImporter_ . I recently updated to Rasa 2.0.0\. Since then, whenever I want to start the training in the main folder, I get the following error:

**Error**

 Traceback (most recent call last):
 File "/usr/local/lib/python3.7/site-packages/rasa/shared/nlu/training_data/loading.py", line 134, in guess_format
 content = rasa.shared.utils.io.read_file(filename)
 File "/usr/local/lib/python3.7/site-packages/rasa/shared/utils/io.py", line 118, in read_file
 return f.read()
 File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/codecs.py", line 322, in decode
 (result, consumed) = self._buffer_decode(data, self.errors, final)
 UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 576: invalid start byte

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
 File "/usr/local/bin/rasa", line 8, in <module>
 sys.exit(main())
 File "/usr/local/lib/python3.7/site-packages/rasa/__main__.py", line 116, in main
 cmdline_arguments.func(cmdline_arguments)
 File "/usr/local/lib/python3.7/site-packages/rasa/cli/train.py", line 90, in train
 nlu_additional_arguments=extract_nlu_additional_arguments(args),
 File "/usr/local/lib/python3.7/site-packages/rasa/train.py", line 55, in train
 loop,
 File "/usr/local/lib/python3.7/site-packages/rasa/utils/common.py", line 308, in run_in_loop
 result = loop.run_until_complete(f)
 File "uvloop/loop.pyx", line 1451, in uvloop.loop.Loop.run_until_complete
 File "/usr/local/lib/python3.7/site-packages/rasa/train.py", line 90, in train_async
 config, domain, training_files
 File "/usr/local/lib/python3.7/site-packages/rasa/shared/importers/importer.py", line 86, in load_from_config
 config, config_path, domain_path, training_data_paths, training_type
 File "/usr/local/lib/python3.7/site-packages/rasa/shared/importers/importer.py", line 146, in load_from_dict
 for importer in importers
 File "/usr/local/lib/python3.7/site-packages/rasa/shared/importers/importer.py", line 146, in <listcomp>
 for importer in importers
 File "/usr/local/lib/python3.7/site-packages/rasa/shared/importers/importer.py", line 190, in _importer_from_dict
 config_path, domain_path, training_data_paths, **constructor_arguments
 File "/usr/local/lib/python3.7/site-packages/rasa/shared/importers/multi_project.py", line 38, in __init__
 self._init_from_dict(self.config, self._project_directory)
 File "/usr/local/lib/python3.7/site-packages/rasa/shared/importers/multi_project.py", line 89, in _init_from_dict
 self._init_from_path(p)
 File "/usr/local/lib/python3.7/site-packages/rasa/shared/importers/multi_project.py", line 59, in _init_from_path
 self._init_from_directory(path)
 File "/usr/local/lib/python3.7/site-packages/rasa/shared/importers/multi_project.py", line 106, in _init_from_directory
 elif rasa.shared.data.is_nlu_file(full_path):
 File "/usr/local/lib/python3.7/site-packages/rasa/shared/data.py", line 201, in is_nlu_file
 return nlu_loading.guess_format(file_path) != nlu_loading.UNK
 File "/usr/local/lib/python3.7/site-packages/rasa/shared/nlu/training_data/loading.py", line 137, in guess_format
 if MarkdownReader.is_markdown_nlu_file(filename):
 File "/usr/local/lib/python3.7/site-packages/rasa/shared/nlu/training_data/formats/markdown.py", line 177, in is_markdown_nlu_file
 content = rasa.shared.utils.io.read_file(filename)
 File "/usr/local/lib/python3.7/site-packages/rasa/shared/utils/io.py", line 118, in read_file
 return f.read()
 File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/codecs.py", line 322, in decode
 (result, consumed) = self._buffer_decode(data, self.errors, final)
 UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 576: invalid start byte

**Command or request that led to error**:

 rasa train --out models

**Config.yml**

 language: en

 pipeline:

*   name: WhitespaceTokenizer
*   name: RegexFeaturizer
*   name: LexicalSyntacticFeaturizer
*   name: CountVectorsFeaturizer
*   name: CountVectorsFeaturizer
     analyzer: char_wb
     min_ngram: 1
     max_ngram: 4
*   name: DIETClassifier
     epochs: 100
*   name: EntitySynonymMapper
*   name: ResponseSelector
     epochs: 100

 policies:

*   name: MemoizationPolicy
*   name: TEDPolicy
     max_history: 5
     epochs: 10
*   name: MappingPolicy

 importers:

*   name: MultiProjectImporter

 imports:

*   projects/faq-bot

Training the faq-bot only without importing another project (Greet-Bot) with the same config, everything works fine. Training the Greeting Bot alone works fine as well. This error first occurred when updating to Rasa 2.0\. Before that, _MultiProjectImporter_ worked perfectly fine.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @rgstephens will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by theresazobel** [comment]
I update my Rasa to this version:

```
Rasa Version     : 2.0.1
Rasa SDK Version : 2.0.0
Rasa X Version   : None
Python Version   : 3.8.6 (default, Oct  8 2020, 14:06:32)
Operating System : macOS-10.15.7-x86_64-i386-64bit
Python Path      : /usr/local/opt/python@3.8/bin/python3.8
```

The issue seems to be resolved now. Closing this issue now

**Comment by theresazobel** [comment]
Reopening because the issue occurred again. Config/commands as above.

`Rasa --version`

```
Rasa Version     : 2.0.1
Rasa SDK Version : 2.0.0
Rasa X Version   : None
Python Version   : 3.8.6 (default, Oct  8 2020, 14:06:32)
Operating System : macOS-10.15.7-x86_64-i386-64bit
Python Path      : /usr/local/opt/python@3.8/bin/python3.8
```
