### ISSUE TITLE
Error when executing " rasa x" command 

### ISSUE THREAD

**Issue by bessem1992** [RasaHQ/rasa#7029]
**Rasa version**:
Rasa 1.10.16
**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):
 0.32.x
**Python version**:
3.7.8
**Operating system** (windows, osx, ...):
windows 10
**Issue**:
hi guys, i built an end-to-end Conversational bot with UI, so i install dependencies for spacy and Rasa X without error.. after that i use the command "rasa init --no-prompt" to building the chatbot but when i use the command " rasa x" in order to starting chatting it failed with Error  

**Error (including full traceback)**:
```
(venv) C:\Users\Toumia Bessem\PycharmProjects\Chatbot-rasa>rasa x
Starting Rasa X in local mode... �

The server is running at http://localhost:5002/login?username=me&password=WrhGOPQb3Zhp

2020-10-15 17:18:55 WARNING  sanic.root  - Sanic tried to use loop.add_signal_handler but it is not implemented on this platform.
2020-10-15 17:18:55 WARNING  sanic.root  - Sanic tried to use loop.add_signal_handler but it is not implemented on this platform.
2020-10-15 17:18:58 ERROR    concurrent.futures  - exception calling callback for <Future at 0x20030ead508 state=finished raised gaierror>
Traceback (most recent call last):
  File "C:\Users\Toumia Bessem\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "C:\Users\Toumia Bessem\AppData\Local\Programs\Python\Python37\lib\socket.py", line 752, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Toumia Bessem\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "C:\Users\Toumia Bessem\AppData\Local\Programs\Python\Python37\lib\asyncio\futures.py", line 365, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "C:\Users\Toumia Bessem\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 736, in call_soon_threadsafe
    self._check_closed()
  File "C:\Users\Toumia Bessem\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 479, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2020-10-15 17:18:58 ERROR    concurrent.futures  - exception calling callback for <Future at 0x20030ea46c8 state=finished returned list>
Traceback (most recent call last):
  File "C:\Users\Toumia Bessem\AppData\Local\Programs\Python\Python37\lib\concurrent\futures\_base.py", line 324, in _invoke_callbacks
    callback(self)
  File "C:\Users\Toumia Bessem\AppData\Local\Programs\Python\Python37\lib\asyncio\futures.py", line 365, in _call_set_state
    dest_loop.call_soon_threadsafe(_set_state, destination, source)
  File "C:\Users\Toumia Bessem\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 736, in call_soon_threadsafe
    self._check_closed()
  File "C:\Users\Toumia Bessem\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 479, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
2020-10-15 17:19:56 ERROR    sanic.root  - Exception occurred while handling uri: unknown
NoneType: None
2020-10-15 17:23:32 ERROR    asyncio  - Task was destroyed but it is pending!
task: <Task pending coro=<TCPConnector._resolve_host() running at c:\users\toumia bessem\pycharmprojects\chatbot-rasa\venv\lib\site-packages\aiohttp\connector
.py:830> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at C:\Users\Toumia Bessem\AppData\Local\Programs\Python\Python37\lib\asyncio
\futures.py:351, <TaskWakeupMethWrapper object at 0x0000020030ED9A98>()]>>
2020-10-15 17:23:32 ERROR    asyncio  - Task was destroyed but it is pending!
task: <Task pending coro=<TCPConnector._resolve_host() running at c:\users\toumia bessem\pycharmprojects\chatbot-rasa\venv\lib\site-packages\aiohttp\connector
.py:830> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at C:\Users\Toumia Bessem\AppData\Local\Programs\Python\Python37\lib\asyncio
\futures.py:351, <TaskWakeupMethWrapper object at 0x0000020030ED9D98>()]>>
Stopping event service.
[2020-10-15 17:33:44 +0100] [10732] [ERROR] Experienced exception while trying to serve
Traceback (most recent call last):
  File "c:\users\toumia bessem\pycharmprojects\chatbot-rasa\venv\lib\site-packages\sanic\app.py", line 1167, in run
    serve(**server_settings)
  File "c:\users\toumia bessem\pycharmprojects\chatbot-rasa\venv\lib\site-packages\sanic\server.py", line 920, in serve
    loop.run_forever()
  File "C:\Users\Toumia Bessem\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 541, in run_forever
    self._run_once()
  File "C:\Users\Toumia Bessem\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 1750, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\Users\Toumia Bessem\AppData\Local\Programs\Python\Python37\lib\selectors.py", line 323, in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "C:\Users\Toumia Bessem\AppData\Local\Programs\Python\Python37\lib\selectors.py", line 314, in _select
    r, w, x = select.select(r, w, w, timeout)
KeyboardInterrupt

**Command or request that led to error**:
```rasa x

```

**Content of configuration file (config.yml)** (if relevant):
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: MemoizationPolicy
  - name: TEDPolicy
    max_history: 5
    epochs: 100
  - name: MappingPolicy

```

**Content of domain file (domain.yml)** (if relevant):
session_config:
  session_expiration_time: 60
  carry_over_slots_to_new_session: true
intents:
- greet
- goodbye
- affirm
- deny
- mood_great
- mood_unhappy
- bot_challenge
responses:
  utter_greet:
  - text: Hey! How are you?
  utter_cheer_up:
  - image: https://i.imgur.com/nGF1K8f.jpg
    text: 'Here is something to cheer you up:'
  utter_did_that_help:
  - text: Did that help you?
  utter_happy:
  - text: Great, carry on!
  utter_goodbye:
  - text: Bye
  utter_iamabot:
  - text: I am a bot, powered by Rasa.


```

**Comment by sara-tagger** [comment]
Thanks for the issue, @b-quachtran will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by rasaworkshop** [comment]
Looks like host issue .Please set enviroment variable for http_proxy and https_proxy it might solve the problem

**Comment by sidorowicz-aleksandra** [comment]
worked for me

**Comment by m-vdb** [comment]
@bessem1992 are you still experiencing the issue? Did the suggestion above help you? Can we close this ticket?

**Comment by m-vdb** [comment]
Closing this one for now 😄  Please reach out on the forum if you're encountering this issue again!

**Comment by dx111ge** [comment]
same issue in windows 10

**Comment by simonm3** [comment]
I also have this issue. Is there a solution? Why is it closed?

**Comment by m-vdb** [comment]
it looks like this is an environment issue rather than a rasa issue (cf. [this comment](https://github.com/RasaHQ/rasa/issues/7029#issuecomment-711789915)). Can you post on the forum with as much details on your setup as possible so that someone can help if you're still stuck? Thanks!

**Comment by simonm3** [comment]
thanks I posted on the forum. 
https://forum.rasa.com/t/rasa-x-task-was-destroyed/49408/9

"Note: You will see the Event Loop Close error in the terminal, you can ignore that, its an persistent issue with Rasa X and team is working on it."
