### ISSUE TITLE
Docker getting started instructions dont work

### ISSUE THREAD

**Issue by elyase** [RasaHQ/rasa#7065]
**Rasa version**:
2.0.0

**Python version**:
docker

**Operating system** (windows, osx, ...):
osx

**Issue**:
Docker getting started instructions fail

**Error (including full traceback)**:
```
❯ docker run -v (pwd):/app rasa/rasa:2.0.0-full init --no-prompt

...
To get started quickly, an initial project will be created.
If you need some help, check out the documentation at https://rasa.com/docs/rasa.

Created project directory at '/app'.
Finished creating project structure.
Training an initial model...
The configuration for policies and pipeline was chosen automatically. It was written into the config file at './config.yml'.
Training NLU model...
NLU model training completed.
Training Core model...
Core model training completed.
Your Rasa model is trained and saved at '/app/models/20201019-164657.tar.gz'.
If you want to speak to the assistant, run 'rasa shell' at any time inside the project directory.


❯ docker run -it -v (pwd):/app rasa/rasa:2.0.0-full shell           
Failed to write global config. Error: [Errno 13] Permission denied: '/.config'. Skipping.
Failed to write global config. Error: [Errno 13] Permission denied: '/.config'. Skipping.
Failed to write global config. Error: [Errno 13] Permission denied: '/.config'. Skipping.
Failed to write global config. Error: [Errno 13] Permission denied: '/.config'. Skipping.
Failed to write global config. Error: [Errno 13] Permission denied: '/.config'. Skipping.
Failed to write global config. Error: [Errno 13] Permission denied: '/.config'. Skipping.
Failed to write global config. Error: [Errno 13] Permission denied: '/.config'. Skipping.
Failed to write global config. Error: [Errno 13] Permission denied: '/.config'. Skipping.
Failed to write global config. Error: [Errno 13] Permission denied: '/.config'. Skipping.
Failed to write global config. Error: [Errno 13] Permission denied: '/.config'. Skipping.
Failed to write global config. Error: [Errno 13] Permission denied: '/.config'. Skipping.
Failed to write global config. Error: [Errno 13] Permission denied: '/.config'. Skipping.
Failed to write global config. Error: [Errno 13] Permission denied: '/.config'. Skipping.
Failed to write global config. Error: [Errno 13] Permission denied: '/.config'. Skipping.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-tw6kwmga because the default path (/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
2020-10-19 16:48:25 ERROR    rasa.model  - Failed to extract model at models/20201019-164657.tar.gz. Error: not a gzip file
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/tarfile.py", line 1646, in gzopen
    t = cls.taropen(name, mode, fileobj, **kwargs)
  File "/usr/local/lib/python3.7/tarfile.py", line 1623, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/usr/local/lib/python3.7/tarfile.py", line 1486, in __init__
    self.firstmember = self.next()
  File "/usr/local/lib/python3.7/tarfile.py", line 2289, in next
    tarinfo = self.tarinfo.fromtarfile(self)
  File "/usr/local/lib/python3.7/tarfile.py", line 1094, in fromtarfile
    buf = tarfile.fileobj.read(BLOCKSIZE)
  File "/usr/local/lib/python3.7/gzip.py", line 287, in read
    return self._buffer.read(size)
  File "/usr/local/lib/python3.7/_compression.py", line 68, in readinto
    data = self.read(len(byte_view))
  File "/usr/local/lib/python3.7/gzip.py", line 474, in read
    if not self._read_gzip_header():
  File "/usr/local/lib/python3.7/gzip.py", line 422, in _read_gzip_header
    raise OSError('Not a gzipped file (%r)' % magic)
OSError: Not a gzipped file (b'\x00\x00')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/venv/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/opt/venv/lib/python3.7/site-packages/rasa/__main__.py", line 116, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/opt/venv/lib/python3.7/site-packages/rasa/cli/shell.py", line 102, in shell
    model_path = get_model(model)
  File "/opt/venv/lib/python3.7/site-packages/rasa/model.py", line 153, in get_model
    return unpack_model(model_path)
  File "/opt/venv/lib/python3.7/site-packages/rasa/model.py", line 198, in unpack_model
    with tarfile.open(model_file, mode="r:gz") as tar:
  File "/usr/local/lib/python3.7/tarfile.py", line 1593, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/usr/local/lib/python3.7/tarfile.py", line 1650, in gzopen
    raise ReadError("not a gzip file")
tarfile.ReadError: not a gzip file
```

**Command or request that led to error**:
```
docker run -v (pwd):/app rasa/rasa:2.0.0-full init --no-prompt
docker run -it -v (pwd):/app rasa/rasa:2.0.0-full shell 
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @erohmensing will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by erohmensing** [comment]
Hm, I just tried the same commands and although I saw a lot of the same misleading logs regarding `'/.config'.` (we're working on those), mine successfuly loaded up the model. Which OS are you running this on, and which version of docker? What does the `models/20201019-164657.tar.gz` model look like in your local -- is it a zipped file, or for some reason an uncompressed dir?

**Comment by elyase** [comment]
it is the latest docker (19.03.13) running on OSX 10.13.6. The problem seems to be indeed the created model file. I can not uncompress it by any means but it is also not a directory. I cleaned up and did another rasa train and the model trains correctly but for some reason the output model.tar.gz looks corrupted.
Any idea how to debug further?

**Comment by elyase** [comment]
I downgraded docker and now it works so it seems to be an issue with the latest docker and 10.13.

**Comment by erohmensing** [comment]
Very strange, I'll try that out. Thanks for pointing this out!

**Comment by elyase** [comment]
Yep I read somewhere that the latest docker is unsupported en 10.13. Too old, it seems it might be time to upgrade.

**Comment by alexlana** [comment]
I have the same problem, previously using Rasa 1.9 and now 2.0, latest Docker and latest Mac OS. The error is on save the model as a corrupted GZIP file. Sometimes the model works fine, but when it is corrupted one time I want to restart the Mac OS to get train back to work...

With this pipeline it behave as above:

```
  - name: "WhitespaceTokenizer"
  - name: "RegexFeaturizer"
  - name: "LexicalSyntacticFeaturizer"
  - name: "CountVectorsFeaturizer"
  - name: "CountVectorsFeaturizer"
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: "DIETClassifier"
    epochs: 100
  - name: FallbackClassifier
    threshold: 0.4
    ambiguity_threshold: 0.1
  - name: "EntitySynonymMapper"
```

With this pipeline I always have a corrupted GZIP:
```
  - name: SpacyNLP
  - name: SpacyTokenizer
  - name: SpacyFeaturizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: DIETClassifier
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 100
```

**Comment by alexlana** [comment]
I'm testing and maybe it has influence of filesize. When I uncomment DIETClassifier and filesize increases from 2MB to 25MB and problem start

**Comment by erohmensing** [comment]
@alexlana would you mind making a new issue with regards to the file size problem? Seems like a different one than the outdated OS version...

**Comment by benjenis** [comment]
Was the new issue created to address this issue?
