### ISSUE TITLE
Rest, SocketIO channel inconsistencies regarding buttons

### ISSUE THREAD

**Issue by Dobatymo** [RasaHQ/rasa#7083]
**Rasa version**: 1.10.15 (but the relevant source code didn't change for the current 2.0.1/master) **Python version**: 3.6 **Operating system** (windows, osx, ...): Ubuntu

**Issue**:

The SocketIO channel requires the `payload` key to be defined for buttons, while the REST channel does not. For example the REST channel will happily send buttons where only the `title` is set (which is convenient if the payload should be the same value as the title. the frontend can handle this accordingly.)

I suggest to make `title` required and `payload` either optional, or fill missing ones with the `title` value to keep compatibility with existing socketio frontends.

**Error (including full traceback)**:

 2020-10-22 03:03:41,484 <span class="error">[ERROR]</span> Task exception was never retrieved
 future: <Task finished coro=<AsyncServer._handle_event_internal() done, defined at /usr/local/lib/python3.6/dist-packages/socketio/asyncio_server.py:469> exception=KeyError('payload',)>
 Traceback (most recent call last):
 File "/usr/local/lib/python3.6/dist-packages/socketio/asyncio_server.py", line 470, in _handle_event_internal
 r = await server._trigger_event(data<span class="error">[0]</span>, namespace, sid, *data<span class="error">[1:]</span>)
 File "/usr/local/lib/python3.6/dist-packages/socketio/asyncio_server.py", line 498, in _trigger_event
 ret = await self.handlers<span class="error">[namespace]</span><span class="error">[event]</span>(*args)
 File "/usr/local/lib/python3.6/dist-packages/rasa/core/channels/socketio.py", line 217, in handle_message
 await on_new_message(message)
 File "/usr/local/lib/python3.6/dist-packages/rasa/core/channels/channel.py", line 83, in handler
 await app.agent.handle_message(*args, **kwargs)
 File "/usr/local/lib/python3.6/dist-packages/rasa/core/agent.py", line 531, in handle_message
 return await processor.handle_message(message)
 File "/usr/local/lib/python3.6/dist-packages/rasa/core/processor.py", line 108, in handle_message
 await self._predict_and_execute_next_action(message.output_channel, tracker)
 File "/usr/local/lib/python3.6/dist-packages/rasa/core/processor.py", line 558, in _predict_and_execute_next_action
 action, tracker, output_channel, self.nlg, policy, confidence
 File "/usr/local/lib/python3.6/dist-packages/rasa/core/processor.py", line 671, in _run_action
 await self._send_bot_messages(events, tracker, output_channel)
 File "/usr/local/lib/python3.6/dist-packages/rasa/core/processor.py", line 600, in _send_bot_messages
 await output_channel.send_response(tracker.sender_id, e.message())
 File "/usr/local/lib/python3.6/dist-packages/rasa/core/channels/channel.py", line 183, in send_response
 recipient_id, message.pop("text"), message.pop("buttons"), **message
 File "/usr/local/lib/python3.6/dist-packages/rasa/core/channels/socketio.py", line 77, in send_text_with_buttons
 "payload": button<span class="error">["payload"]</span>,
 KeyError: 'payload'

These are the relevant lines: [https://github.com/RasaHQ/rasa/blob/ba0d89022c3a4cb269afe44627506cbd68d9c9a6/rasa/core/channels/socketio.py#L73-L79](https://github.com/RasaHQ/rasa/blob/ba0d89022c3a4cb269afe44627506cbd68d9c9a6/rasa/core/channels/socketio.py#L73-L79)

**Command or request that led to error**: Any response which uses an utterance from `domain.yml` which doesn't have the `payload` key defined.

EDIT: I found more inconsistencies and/or undocumented issues.

REST channel uses the `button` key, SocketIO uses `quick_replies`. REST wrappes the `json_message` in `custom`, SocketIO requires the `json_message` (from `utter_messsage`) to have a `data` key...

**Comment by sara-tagger** [comment]
Thanks for the issue, @amn41 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗
