### ISSUE TITLE
Migrating Rasa 1.x assistant to Rasa 2.0 - AttributeError: module 'sip' has no attribute 'setapi'

### ISSUE THREAD

**Issue by satishavhad** [RasaHQ/rasa#7144]
**Rasa version**:  2.0.3

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**: 3.8.3

**Operating system** (windows, osx, ...): Windows

**Issue**:
Getting "AttributeError: module 'sip' has no attribute 'setapi'" when running commands to convert NLU, Core and config files.

**Error (including full traceback)**:
```
(venv) (base) C:\Users\avhadsa\Documents\GitHub\Conversational_Intelligence>rasa data convert core -f yaml --data=./data/core --out=./data/core
Traceback (most recent call last):
  File "C:\Users\avhadsa\Anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\avhadsa\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\avhadsa\Documents\GitHub\Conversational_Intelligence\venv\Scripts\rasa.exe\__main__.py", line 5, in <module>
  File "c:\users\avhadsa\documents\github\conversational_intelligence\venv\lib\site-packages\rasa\__init__.py", line 9, in <module>
    from rasa.train import train
  File "c:\users\avhadsa\documents\github\conversational_intelligence\venv\lib\site-packages\rasa\train.py", line 13, in <module>
    from rasa.nlu.model import Interpreter
  File "c:\users\avhadsa\documents\github\conversational_intelligence\venv\lib\site-packages\rasa\nlu\__init__.py", line 5, in <module>
    from rasa.nlu.test import run_evaluation as test
  File "c:\users\avhadsa\documents\github\conversational_intelligence\venv\lib\site-packages\rasa\nlu\test.py", line 22, in <module>
    import rasa.utils.plotting as plot_utils
  File "c:\users\avhadsa\documents\github\conversational_intelligence\venv\lib\site-packages\rasa\utils\plotting.py", line 42, in <module>
    _fix_matplotlib_backend()
  File "c:\users\avhadsa\documents\github\conversational_intelligence\venv\lib\site-packages\rasa\utils\plotting.py", line 19, in _fix_matplotlib_backend
    if matplotlib.get_backend() == "TkAgg":
  File "c:\users\avhadsa\documents\github\conversational_intelligence\venv\lib\site-packages\matplotlib\__init__.py", line 1188, in get_backend
    return rcParams['backend']
  File "c:\users\avhadsa\documents\github\conversational_intelligence\venv\lib\site-packages\matplotlib\__init__.py", line 702, in __getitem__
    from matplotlib import pyplot as plt
  File "c:\users\avhadsa\documents\github\conversational_intelligence\venv\lib\site-packages\matplotlib\pyplot.py", line 2336, in <module>
    switch_backend(rcParams["backend"])
  File "c:\users\avhadsa\documents\github\conversational_intelligence\venv\lib\site-packages\matplotlib\__init__.py", line 703, in __getitem__
    plt.switch_backend(rcsetup._auto_backend_sentinel)
  File "c:\users\avhadsa\documents\github\conversational_intelligence\venv\lib\site-packages\matplotlib\pyplot.py", line 256, in switch_backend
    switch_backend(candidate)
  File "c:\users\avhadsa\documents\github\conversational_intelligence\venv\lib\site-packages\matplotlib\pyplot.py", line 276, in switch_backend
    class backend_mod(matplotlib.backend_bases._Backend):
  File "c:\users\avhadsa\documents\github\conversational_intelligence\venv\lib\site-packages\matplotlib\pyplot.py", line 277, in backend_mod
    locals().update(vars(importlib.import_module(backend_name)))
  File "C:\Users\avhadsa\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "c:\users\avhadsa\documents\github\conversational_intelligence\venv\lib\site-packages\matplotlib\backends\backend_qt5agg.py", line 11, in <module>
    from .backend_qt5 import (
  File "c:\users\avhadsa\documents\github\conversational_intelligence\venv\lib\site-packages\matplotlib\backends\backend_qt5.py", line 16, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "c:\users\avhadsa\documents\github\conversational_intelligence\venv\lib\site-packages\matplotlib\backends\qt_editor\figureoptions.py", line 11, in <module>
    from matplotlib.backends.qt_compat import QtGui
  File "c:\users\avhadsa\documents\github\conversational_intelligence\venv\lib\site-packages\matplotlib\backends\qt_compat.py", line 170, in <module>
    _setup()
  File "c:\users\avhadsa\documents\github\conversational_intelligence\venv\lib\site-packages\matplotlib\backends\qt_compat.py", line 130, in _setup_pyqt4
    _setup_pyqt4_internal(api=2)
  File "c:\users\avhadsa\documents\github\conversational_intelligence\venv\lib\site-packages\matplotlib\backends\qt_compat.py", line 113, in _setup_pyqt4_internal
    sip.setapi(_sip_api, api)
AttributeError: module 'sip' has no attribute 'setapi'
```

**Command or request that led to error**:
```
rasa data convert core -f yaml --data=./data/core --out=./data/core

Same error encountered when I used:
rasa data convert nlu   and
rasa data convert config

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @tabergma will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by degiz** [comment]
Hey @satishavhad 

Did you use a clean virtual environment for the rasa installation?

Seems like matplotlib cannot be initialized on your windows system. Could you take a look at [this](https://matplotlib.org/3.3.2/users/installing.html) page for troubleshooting?

**Comment by satishavhad** [comment]
> Hey @satishavhad
> 
> Did you use a clean virtual environment for the rasa installation?
> 
> Seems like matplotlib cannot be initialized on your windows system. Could you take a look at [this](https://matplotlib.org/3.3.2/users/installing.html) page for troubleshooting?

Hi,
Yes, I used clean virtual environment for the rasa installation. I double checked matplotlib. All the requirements are correctly installed. I am still getting the same error. I tried reinstalling rasa as well. But no luck!

**Comment by degiz** [comment]
Hmm, what about just launching `python` in interactive mode and try to `import matplotlib`?

**Comment by satishavhad** [comment]
I tried that. Import matplotlib was successful. Error happens only on rasa command. See the log below:


(venv) (base) C:\Users\avhadsa\Documents\GitHub\Conversational_Intelligence>python
Python 3.8.3 (default, Jul  2 2020, 17:30:36) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib
>>> exit()

(venv) (base) C:\Users\avhadsa\Documents\GitHub\Conversational_Intelligence>rasa data convert config
Traceback (most recent call last):
  File "C:\Users\avhadsa\Anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\avhadsa\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\avhadsa\Documents\GitHub\Conversational_Intelligence\venv\Scripts\rasa.exe\__main__.py", line 4, in <module>
  File "c:\users\avhadsa\documents\github\conversational_intelligence\venv\lib\site-packages\rasa\__init__.py", line 9, in <module>
    from rasa.train import train
  File "c:\users\avhadsa\documents\github\conversational_intelligence\venv\lib\site-packages\rasa\train.py", line 13, in <module>
    from rasa.nlu.model import Interpreter
  File "c:\users\avhadsa\documents\github\conversational_intelligence\venv\lib\site-packages\rasa\nlu\__init__.py", line 5, in <module>
    from rasa.nlu.test import run_evaluation as test
  File "c:\users\avhadsa\documents\github\conversational_intelligence\venv\lib\site-packages\rasa\nlu\test.py", line 22, in <module>
    import rasa.utils.plotting as plot_utils
  File "c:\users\avhadsa\documents\github\conversational_intelligence\venv\lib\site-packages\rasa\utils\plotting.py", line 42, in <module>
    _fix_matplotlib_backend()
  File "c:\users\avhadsa\documents\github\conversational_intelligence\venv\lib\site-packages\rasa\utils\plotting.py", line 19, in _fix_matplotlib_backend
    if matplotlib.get_backend() == "TkAgg":
  File "c:\users\avhadsa\documents\github\conversational_intelligence\venv\lib\site-packages\matplotlib\__init__.py", line 1188, in get_backend
    return rcParams['backend']
  File "c:\users\avhadsa\documents\github\conversational_intelligence\venv\lib\site-packages\matplotlib\__init__.py", line 702, in __getitem__
    from matplotlib import pyplot as plt
  File "c:\users\avhadsa\documents\github\conversational_intelligence\venv\lib\site-packages\matplotlib\pyplot.py", line 2336, in <module>
    switch_backend(rcParams["backend"])
  File "c:\users\avhadsa\documents\github\conversational_intelligence\venv\lib\site-packages\matplotlib\__init__.py", line 703, in __getitem__
    plt.switch_backend(rcsetup._auto_backend_sentinel)
  File "c:\users\avhadsa\documents\github\conversational_intelligence\venv\lib\site-packages\matplotlib\pyplot.py", line 256, in switch_backend
    switch_backend(candidate)
  File "c:\users\avhadsa\documents\github\conversational_intelligence\venv\lib\site-packages\matplotlib\pyplot.py", line 276, in switch_backend
    class backend_mod(matplotlib.backend_bases._Backend):
  File "c:\users\avhadsa\documents\github\conversational_intelligence\venv\lib\site-packages\matplotlib\pyplot.py", line 277, in backend_mod
    locals().update(vars(importlib.import_module(backend_name)))
  File "C:\Users\avhadsa\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "c:\users\avhadsa\documents\github\conversational_intelligence\venv\lib\site-packages\matplotlib\backends\backend_qt5agg.py", line 11, in <module>
    from .backend_qt5 import (
  File "c:\users\avhadsa\documents\github\conversational_intelligence\venv\lib\site-packages\matplotlib\backends\backend_qt5.py", line 16, in <module>
    import matplotlib.backends.qt_editor.figureoptions as figureoptions
  File "c:\users\avhadsa\documents\github\conversational_intelligence\venv\lib\site-packages\matplotlib\backends\qt_editor\figureoptions.py", line 11, in <module>
    from matplotlib.backends.qt_compat import QtGui
  File "c:\users\avhadsa\documents\github\conversational_intelligence\venv\lib\site-packages\matplotlib\backends\qt_compat.py", line 170, in <module>
    _setup()
  File "c:\users\avhadsa\documents\github\conversational_intelligence\venv\lib\site-packages\matplotlib\backends\qt_compat.py", line 130, in _setup_pyqt4
    _setup_pyqt4_internal(api=2)
  File "c:\users\avhadsa\documents\github\conversational_intelligence\venv\lib\site-packages\matplotlib\backends\qt_compat.py", line 113, in _setup_pyqt4_internal
    sip.setapi(_sip_api, api)
AttributeError: module 'sip' has no attribute 'setapi'

**Comment by alwx** [comment]
Hey @satishavhad!
Could you please try running `poetry run pip install matplotlib==3.2`? Might be that matplotlib 3.3 does not properly work on Windows.

**Comment by satishavhad** [comment]
After downgrading to Matplotlib 3.2, i am getting below error. It seems Rasa 2.0 require matplotlib 3.3. But with that I am getting above error.

Successfully installed matplotlib-3.2.0

(venv) (base) C:\Users\avhadsa\Documents\GitHub\Conversational_Intelligence>rasa data convert config
Traceback (most recent call last):
  File "c:\users\avhadsa\documents\github\conversational_intelligence\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\avhadsa\Anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\avhadsa\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\avhadsa\Documents\GitHub\Conversational_Intelligence\venv\Scripts\rasa.exe\__main__.py", line 7, in <module>
  File "c:\users\avhadsa\documents\github\conversational_intelligence\venv\lib\site-packages\rasa\__main__.py", line 103, in main
    set_log_level(log_level)
  File "c:\users\avhadsa\documents\github\conversational_intelligence\venv\lib\site-packages\rasa\utils\common.py", line 66, in set_log_level
    update_tensorflow_log_level()
  File "c:\users\avhadsa\documents\github\conversational_intelligence\venv\lib\site-packages\rasa\utils\common.py", line 108, in update_tensorflow_log_level
    import tensorflow as tf
  File "c:\users\avhadsa\documents\github\conversational_intelligence\venv\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "c:\users\avhadsa\documents\github\conversational_intelligence\venv\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "c:\users\avhadsa\documents\github\conversational_intelligence\venv\lib\site-packages\tensorflow\python\eager\context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe
  File "c:\users\avhadsa\documents\github\conversational_intelligence\venv\lib\site-packages\tensorflow\python\pywrap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "c:\users\avhadsa\documents\github\conversational_intelligence\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "c:\users\avhadsa\documents\github\conversational_intelligence\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by wochinge** [comment]
Closing this as it's a usage question. If this is still an issue, please ask this in the [forum](https://forum.rasa.com)
