### ISSUE TITLE
Yamlvalidation error with domain while migrating to version 2.0.x

### ISSUE THREAD

**Issue by akshay-gupta11** [RasaHQ/rasa#7163]
**Rasa version**: 2.0.3

**Rasa SDK version** (if used & relevant): NA

**Rasa X version** (if used & relevant): NA

**Python version**: 3.6.9

**Operating system** (windows, osx, ...): Linux-4.4.0-18362-Microsoft-x86_64-with-Ubuntu-18.04-bionic

**Issue**:  While executing the command '''rasa data convert config --debug''' to migrate domain and config files to support version 2.0.x, i get a YamlValidationException. I already checked with a yaml validator and there is no problem with config.yml or domain.yml. Also the YamlValidationException shows no errors after the "Failed to Validate" message.

**Error (including full traceback)**:
```
2020-11-03 10:43:00 DEBUG    rasa.__main__  - Failed to run CLI command due to an exception.
Traceback (most recent call last):
  File "/home/akshay/.virtualenvs/convai/lib/python3.6/site-packages/rasa/shared/utils/validation.py", line 160, in validate_yaml_schema
    c.validate(raise_exception=True)
  File "/home/akshay/.virtualenvs/convai/lib/python3.6/site-packages/pykwalify/core.py", line 155, in validate
    self._start_validate(self.source)
  File "/home/akshay/.virtualenvs/convai/lib/python3.6/site-packages/pykwalify/core.py", line 202, in _start_validate
    self._validate(value, root_rule, path, done)
  File "/home/akshay/.virtualenvs/convai/lib/python3.6/site-packages/pykwalify/core.py", line 236, in _validate
    self._validate_mapping(value, rule, path, done=None)
  File "/home/akshay/.virtualenvs/convai/lib/python3.6/site-packages/pykwalify/core.py", line 570, in _validate_mapping
    self._validate(v, r, u"{0}/{1}".format(path, k), done)
  File "/home/akshay/.virtualenvs/convai/lib/python3.6/site-packages/pykwalify/core.py", line 232, in _validate
    self._validate_include(value, rule, path, done=None)
  File "/home/akshay/.virtualenvs/convai/lib/python3.6/site-packages/pykwalify/core.py", line 293, in _validate_include
    self._validate(value, partial_schema_rule, path, done)
  File "/home/akshay/.virtualenvs/convai/lib/python3.6/site-packages/pykwalify/core.py", line 236, in _validate
    self._validate_mapping(value, rule, path, done=None)
  File "/home/akshay/.virtualenvs/convai/lib/python3.6/site-packages/pykwalify/core.py", line 578, in _validate_mapping
    self._validate(v, mm[0], "{0}/{1}".format(path, k), done)
  File "/home/akshay/.virtualenvs/convai/lib/python3.6/site-packages/pykwalify/core.py", line 234, in _validate
    self._validate_sequence(value, rule, path, done=None)
  File "/home/akshay/.virtualenvs/convai/lib/python3.6/site-packages/pykwalify/core.py", line 324, in _validate_sequence
    self._handle_func(value, rule, path, done)
  File "/home/akshay/.virtualenvs/convai/lib/python3.6/site-packages/pykwalify/core.py", line 259, in _handle_func
    ret = method(value, rule, path)
  File "/home/akshay/.virtualenvs/convai/lib/python3.6/site-packages/rasa/shared/utils/pykwalify_extensions.py", line 24, in require_response_keys
    raise SchemaError("Missing 'text' or 'custom' key in response.")
pykwalify.errors.SchemaError: <SchemaError: error code 2: Missing 'text' or 'custom' key in response.: Path: '/'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/akshay/.virtualenvs/convai/lib/python3.6/site-packages/rasa/__main__.py", line 115, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/home/akshay/.virtualenvs/convai/lib/python3.6/site-packages/rasa/cli/data.py", line 417, in _migrate_model_config
    domain = _get_domain(domain_file)
  File "/home/akshay/.virtualenvs/convai/lib/python3.6/site-packages/rasa/cli/data.py", line 561, in _get_domain
    return Domain.from_path(path)
  File "/home/akshay/.virtualenvs/convai/lib/python3.6/site-packages/rasa/shared/core/domain.py", line 131, in from_path
    domain = cls.from_file(path)
  File "/home/akshay/.virtualenvs/convai/lib/python3.6/site-packages/rasa/shared/core/domain.py", line 144, in from_file
    return cls.from_yaml(rasa.shared.utils.io.read_file(path), path)
  File "/home/akshay/.virtualenvs/convai/lib/python3.6/site-packages/rasa/shared/core/domain.py", line 162, in from_yaml
    raise e
  File "/home/akshay/.virtualenvs/convai/lib/python3.6/site-packages/rasa/shared/core/domain.py", line 150, in from_yaml
    yaml, rasa.shared.constants.DOMAIN_SCHEMA_FILE
  File "/home/akshay/.virtualenvs/convai/lib/python3.6/site-packages/rasa/shared/utils/validation.py", line 167, in validate_yaml_schema
    content=source_data,
rasa.shared.utils.validation.YamlValidationException: Failed to validate '/home/akshay/.virtualenvs/convai/rasa/domain.yml'. Please make sure the file is correct and all mandatory parameters are specified. Here are the errors found during validation
YamlValidationException: Failed to validate '/home/akshay/.virtualenvs/convai/rasa/domain.yml'. Please make sure the file is correct and all mandatory parameters are specified. Here are the errors found during validation
```

**Command or request that led to error**:
```
(convai) akshay@Lit:~/.virtualenvs/convai/rasa$ rasa data convert config --debug
```

**Content of configuration file (config.yml)** (if relevant):
```
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline:
  - name: "WhitespaceTokenizer"
  - name: "RegexFeaturizer"
  - name: "LexicalSyntacticFeaturizer"
  - name: "CountVectorsFeaturizer"
  - name: "CountVectorsFeaturizer"
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4
  - name: "DIETClassifier"
    epochs: 25
  - name: "EntitySynonymMapper"
  - name: "ResponseSelector"
    epochs: 100

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
  - name: "MemoizationPolicy"
    max_history: 1
  - name: "TEDPolicy"
    epochs: 40
  - name: "MappingPolicy"
  - name: "TwoStageFallbackPolicy"
    nlu_threshold: 0.3
    ambiguity_threshold: 0.2
    core_threshold: 0.3
    fallback_core_action_name: "action_default_fallback"
    fallback_nlu_action_name: "action_default_fallback"
    deny_suggestion_intent_name: "out_of_scope"
    

```

**Content of domain file (domain.yml)** (if relevant):
```
actions:
- action_chat_restart
- ca_dev_testing
- action_default_ask_affirmation
- action_default_fallback
- respond_faq
- utter_ask_rephrase
- utter_cheer_up
- utter_did_that_help
- utter_goodbye
- utter_graph
- utter_greet
- utter_happy
- utter_iamabot
- utter_interesting_replies
- utter_pause_statements
- utter_sad
- utter_thanks
- utter_walkthrough

entities:
- category
- description
- criteria
- day
- kpi
- kpi_adj
- quantity
- time
- weather
- zone
- comp_one
- comp_two
- comp_three
- sub_kpi
intents:
- dev_testing:
    triggers: ca_dev_testing
- faq
- interesting
- peak_time
- mood_great
- thanks
- mood_unhappy
- comparison
- walkthrough
- overview
- greet
- zone_comparison
- goodbye
- affirm
- deny
- one_more_question
- bot_challenge
- out_of_scope
- restart:
    triggers: action_chat_restart
- no_to_anything
- smile
- laugh
- oneup
- onedown
slots:
  avdt_flag:
    type: text
responses:
  utter_ask_rephrase:
  - text: Could you please rephrase your statement. 🤔
  utter_cheer_up:
  - text: Why so Serious!
  utter_did_that_help:
  - text: Did that help you?
  utter_goodbye:
  - text: Bye
  utter_graph:
  - image: https://media.giphy.com/media/blK6842DVLtfO/giphy.gif
    text: Here you go.
  utter_greet:
  - image: https://media.giphy.com/media/l0FF56cexcW2JAXCJj/giphy.gif
    text: Hi again. 👋👋
  - image: https://media.giphy.com/media/VeyKFkeLLW8h2/giphy.gif
    text: Hola. 🙋
  utter_happy:
  - text: 😊
  - text: Nice
  - text: Great!
  utter_iamabot:
  - text: I am a bot.
  - text: This is 21st century. Ofcourse I am a bot.
  utter_interesting_replies:
  - text: uh huh!
  - text: indeed
  utter_pause_statements:
  - text: Sit tight.
  - image: https://media.giphy.com/media/820QjxfKziUsU/giphy.gif
    text: Information coming right up.
  - text: Hang on.
  - image: https://media.giphy.com/media/DfSXiR60W9MVq/giphy.gif
    text: Pulling the numbers for you.
  - image: https://media.giphy.com/media/dPWFfe3tykssE/giphy.gif
    text: Fetching information.
  - image: https://media.giphy.com/media/dPWFfe3tykssE/giphy.gif
    text: Sure. Hang on...
  utter_sad:
  - image: https://media.giphy.com/media/5t9wJjyHAOxvnxcPNk/giphy.gif
    text: null
  utter_thanks:
  - text: :)
  - text: You're most welcome!
  - text: ¡de nada!
  utter_walkthrough:
  - buttons:
    - payload: /overview
      title: 👍
    - payload: /no_to_anything
      title: 👎
    text: Would you like me to give you an overview.?
session_config:
  carry_over_slots_to_new_session: true
  session_expiration_time: 60


```

**Comment by sara-tagger** [comment]
Thanks for the issue, @rgstephens will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by chandhana2910** [comment]
Any update on this? I am facing same issue

**Comment by rgstephens** [comment]
The 1.x version did not validate the domain file.

@akshay-gupta11 The issue with your domain is the `text: null`. Change that to `text: ""` and you should have no problem.

@chandhana2910 There is a syntax issue with your domain file. Could be similar to the above or [the user in this forum post](https://forum.rasa.com/t/yamlvalidationexception-while-migrating-domain-from-rasa-1-x-to-rasa-2-0-0/36038/7?u=stephens). If you run a `rasa data validate` it may provide a pointer to the issue. If you can't figure out the issue, please post the domain file in the forum.
