### ISSUE TITLE
Api call at /conversation/{conv-id}/tracker fails when custom action_session_start generates some messages

### ISSUE THREAD

**Issue by pbuszka** [RasaHQ/rasa#7248]
**Rasa version**: 2.0.6

**Rasa SDK version** (if used & relevant): not used

**Rasa X version** (if used & relevant): not used

**Python version**: 3.6

**Operating system** (windows, osx, ...): linux (ubuntu 18.04)

**Issue**: failed call for conversations/

 {conv-id} 

/tracker endpoint ([http://localhost:5005/conversations/test/tracker](http://localhost:5005/conversations/test/tracker)) happens when all of the following conditions are met:

*   it is a new conversation (probably this is related to the next condition)
*   action_session_start is triggered
*   there is a custom action handler for action_session_start (I have an external java based server but probably same problem would be with python based action server)
*   the custom action server handler returns some messages to be sent in response to action_session_start

having looked into the code, I suppose, the root cause is from the fact that there is no output_channel in this request and down the processing it breaks down when output_channel is None and some message should be sent at the same time

 fetch_tracker_with_initial_session(..., output_channel: Optional<span class="error">[OutputChannel]</span> = None...)
 _update_tracker_session(..., ***output_channel: OutputChannel***, ...)
 _run_action(..., output_channel: OutputChannel
 execute_side_effects(..., output_channel: OutputChannel

1.  and fails when output_channel is None on when there are some message to be sent
     await output_channel.send_response(tracker.sender_id, e.message())

Probably a quick fix would be to test if output_channel is available and ignore send_response call in such a case but I'm not sure if it is the right way to fix. Proper way seems to change sigantures of _update_tracker_session, _run_action, execute_side_effects so that it is clear that output_channel can be None. Alternatively provide some dummy output_channel for api calls that do not have output_channel. I can do a pull request for the quick workaround but probably not something more complicated (I haven't done anything substantial in python)

**Error (including full traceback)**:

 Traceback (most recent call last):
 File "/usr/local/lib/python3.6/dist-packages/sanic/app.py", line 938, in handle_request
 response = await response
 File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
 return self.gen.send(None)
 File "/usr/local/lib/python3.6/dist-packages/rasa/server.py", line 194, in decorated
 result = await result
 File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
 return self.gen.send(None)
 File "/usr/local/lib/python3.6/dist-packages/rasa/server.py", line 477, in retrieve_tracker
 tracker = await get_tracker(app.agent.create_processor(), conversation_id)
 File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
 return self.gen.send(None)
 File "/usr/local/lib/python3.6/dist-packages/rasa/server.py", line 234, in get_tracker
 tracker = await processor.get_tracker_with_session_start(conversation_id)
 File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
 return self.gen.send(None)
 File "/usr/local/lib/python3.6/dist-packages/rasa/core/processor.py", line 196, in get_tracker_with_session_start
 await self._update_tracker_session(tracker, output_channel, metadata)
 File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
 return self.gen.send(None)
 File "/usr/local/lib/python3.6/dist-packages/rasa/core/processor.py", line 170, in _update_tracker_session
 metadata=metadata,
 File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
 return self.gen.send(None)
 File "/usr/local/lib/python3.6/dist-packages/rasa/core/processor.py", line 701, in _run_action
 await self.execute_side_effects(events, tracker, output_channel)
 File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
 return self.gen.send(None)
 File "/usr/local/lib/python3.6/dist-packages/rasa/core/processor.py", line 605, in execute_side_effects
 await self._send_bot_messages(events, tracker, output_channel)
 File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
 return self.gen.send(None)
 File "/usr/local/lib/python3.6/dist-packages/rasa/core/processor.py", line 621, in _send_bot_messages
 await output_channel.send_response(tracker.sender_id, e.message())
 AttributeError: 'NoneType' object has no attribute 'send_response'

**Command or request that led to error**:

 api call 
 [http://localhost:5005/conversations/test/tracker](http://localhost:5005/conversations/test/tracker)

**Content of configuration file (config.yml)** (if relevant):

<pre>...
 actions:

*   action_ChangeProfile
*   action_EndConversation
*   action_NextProfileQuestion
*   action_NextStructuredProfileQuestion
*   action_UpdateProfile
*   action_default_fallback
*   action_explain_offer
*   action_human_handover
*   action_options_FaqInteraction
*   action_options_FindBestProductInteraction
*   action_options_GlobalInteraction
*   action_session_start
     ...</pre>

**Content of domain file (domain.yml)** (if relevant):

**Comment by sara-tagger** [comment]
Thanks for the issue, @tabergma will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by JEM-Mosig** [comment]
A forum user encountered this (or a related) issue: https://forum.rasa.com/t/how-to-set-a-response-as-first-message/41617/3

**Comment by boisdecerf** [comment]
thank you @pbuszka
I just had the same bug with a different context, here's my logs

**Rasa version:** 2.8.0
**Rasa SDK version (if used & relevant):** 2.8.0
**Rasa X version (if used & relevant):** 0.42.0
**Python version:** 3.7
**Operating system (windows, osx, ...):** linux (ubuntu 18.04)

**Issue**
output_channel is at None when sending a message to the bot after restarting the session

**Error (including full traceback):**
```Traceback (most recent call last):
  File "/chat-bot/venvNoAvx3.7/lib/python3.7/site-packages/sanic/app.py", line 938, in handle_request
    response = await response
  File "/chat-bot/venvNoAvx3.7/lib/python3.7/site-packages/rasa/server.py", line 263, in decorated
    result = await result
  File "/chat-bot/venvNoAvx3.7/lib/python3.7/site-packages/rasa/server.py", line 740, in retrieve_tracker
    conversation_id
  File "/chat-bot/venvNoAvx3.7/lib/python3.7/site-packages/rasa/core/processor.py", line 266, in fetch_tracker_with_initial_session
    await self._update_tracker_session(tracker, output_channel, metadata)
  File "/chat-bot/venvNoAvx3.7/lib/python3.7/site-packages/rasa/core/processor.py", line 217, in _update_tracker_session
    self.domain, ACTION_SESSION_START_NAME
  File "/chat-bot/venvNoAvx3.7/lib/python3.7/site-packages/rasa/core/processor.py", line 798, in _run_action
    await self.execute_side_effects(events, tracker, output_channel)
  File "/chat-bot/venvNoAvx3.7/lib/python3.7/site-packages/rasa/core/processor.py", line 699, in execute_side_effects
    await self._send_bot_messages(events, tracker, output_channel)
  File "/chat-bot/venvNoAvx3.7/lib/python3.7/site-packages/rasa/core/processor.py", line 715, in _send_bot_messages
    await output_channel.send_response(tracker.sender_id, e.message())
AttributeError: 'NoneType' object has no attribute 'send_response'
```

**Command or request that led to error:**
Sending a message to the bot after restarting

**Content of configuration file (config.yml)** (if relevant):

**Content of domain file (domain.yml)** (if relevant):

**Comment by rnarv009** [comment]
I'm also getting the same error
[2021-11-10 07:37:15 +0530] [281683] [ERROR] Exception occurred while handling uri: 'http://localhost:5005/conversations/336f85e4-2ded-4d45-8ab2-40164bcee52a/tracker/?{%22msg%22:%22message%22}'
Traceback (most recent call last):
  File "/home/rahul/project/unoBot/.env/lib/python3.6/site-packages/sanic/app.py", line 1001, in handle_request
    response = await response
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/home/rahul/project/unoBot/.env/lib/python3.6/site-packages/rasa/server.py", line 178, in decorated
    result = await result
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/home/rahul/project/unoBot/.env/lib/python3.6/site-packages/rasa/server.py", line 445, in retrieve_tracker
    tracker = await get_tracker(app.agent.create_processor(), conversation_id)
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/home/rahul/project/unoBot/.env/lib/python3.6/site-packages/rasa/server.py", line 216, in get_tracker
    tracker = await processor.get_tracker_with_session_start(conversation_id)
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/home/rahul/project/unoBot/.env/lib/python3.6/site-packages/rasa/core/processor.py", line 196, in get_tracker_with_session_start
    await self._update_tracker_session(tracker, output_channel)
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/home/rahul/project/unoBot/.env/lib/python3.6/site-packages/rasa/core/processor.py", line 174, in _update_tracker_session
    nlg=self.nlg,
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/home/rahul/project/unoBot/.env/lib/python3.6/site-packages/rasa/core/processor.py", line 617, in _run_action
    await self._send_bot_messages(events, tracker, output_channel)
  File "/usr/lib/python3.6/asyncio/coroutines.py", line 110, in __next__
    return self.gen.send(None)
  File "/home/rahul/project/unoBot/.env/lib/python3.6/site-packages/rasa/core/processor.py", line 546, in _send_bot_messages
    await output_channel.send_response(tracker.sender_id, e.message())
AttributeError: 'NoneType' object has no attribute 'send_response'
