### ISSUE TITLE
Failed to find component class

### ISSUE THREAD

**Issue by anandhperumal** [RasaHQ/rasa#7321]
**Rasa version**:
rasa                    2.0.0
rasa-nlu                0.15.0
rasa-sdk                2.1.2

**Python version**: 3.6.12

**Operating system** (windows, osx, ...): osx

**Issue**:

Failed to find a component class even though it is present in the latest code.

When I was looking at the site-packages the class components are missing from the one which is present in the latest [code](https://github.com/RasaHQ/rasa/blob/b40a022e0870c2c21efb47f114e35357b1aeaed2/rasa/nlu/registry.py#L64) 
![image](https://user-images.githubusercontent.com/12907396/99785592-953d6d00-2ada-11eb-9582-41b0c766aa51.png)

I tried updating the rasa in a clean env and also tried installing from the source but still, I see the code is the old version 

**Error (including full traceback)**:
```
/Users/anandhperumal/opt/anaconda3/envs/tmp2/bin/python3 /Users/anandhperumal/Github/TMP/TMP.py
Traceback (most recent call last):
  File "/Users/anandhperumal/opt/anaconda3/envs/tmp2/lib/python3.6/site-packages/rasa_nlu/registry.py", line 135, in get_component_class
    return utils.class_from_module_path(component_name)
  File "/Users/anandhperumal/opt/anaconda3/envs/tmp2/lib/python3.6/site-packages/rasa_nlu/utils/__init__.py", line 165, in class_from_module_path
    return globals()[module_path]
KeyError: 'LexicalSyntacticFeaturizer'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/anandhperumal/Github/TMP/TMP.py", line 3, in <module>
    trainer = Trainer(config.load("config.yml"))
  File "/Users/anandhperumal/opt/anaconda3/envs/tmp2/lib/python3.6/site-packages/rasa_nlu/model.py", line 147, in __init__
    components.validate_requirements(cfg.component_names)
  File "/Users/anandhperumal/opt/anaconda3/envs/tmp2/lib/python3.6/site-packages/rasa_nlu/components.py", line 37, in validate_requirements
    component_class = registry.get_component_class(component_name)
  File "/Users/anandhperumal/opt/anaconda3/envs/tmp2/lib/python3.6/site-packages/rasa_nlu/registry.py", line 144, in get_component_class
    "in a module.".format(component_name))
Exception: Failed to find component class for 'LexicalSyntacticFeaturizer'. Unknown component name. Check your configured pipeline and make sure the mentioned component is not misspelled. If you are creating your own component, make sure it is either listed as part of the `component_classes` in `rasa_nlu.registry.py` or is a proper name of a class in a module.

```

**Command or request that led to error**:
```
from rasa_nlu.model import Trainer
from rasa_nlu import config
trainer = Trainer(config.load("config.yml"))
```

**Content of configuration file (config.yml)** (if relevant):
```yml
language: en
pipeline:
- name: WhitespaceTokenizer
- name: RegexFeaturizer
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  OOV_token: oov
  token_pattern: (?u)\b\w+\b
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 200
  ranking_length: 5
- name: DucklingEntityExtractor
  url: http://localhost:8000
  dimensions:
  - email
  - number
  - amount-of-money
- name: EntitySynonymMapper
- name: ResponseSelector
  retrieval_intent: out_of_scope
  scale_loss: false
  epochs: 100
- name: ResponseSelector
  retrieval_intent: faq
  scale_loss: false
  epochs: 100
- name: ResponseSelector
  retrieval_intent: chitchat
  scale_loss: false
  epochs: 100
- name: FallbackClassifier
  threshold: 0.7
policies:
- name: TEDPolicy
  max_history: 10
  epochs: 20
  batch_size:
  - 32
  - 64
- max_history: 6
  name: AugmentedMemoizationPolicy
- name: RulePolicy
  core_fallback_threshold: 0.3
  core_fallback_action_name: "action_default_fallback"
  enable_fallback_prediction: True


```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @erohmensing will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by anandhperumal** [comment]
Also, it works fine when I run cmi using the following command rasa train

**Comment by anandhperumal** [comment]
Closing this issue, the module is working as expected. I was comparing the wrong files.
