### ISSUE TITLE
Rasa x domain section tab and space bug

### ISSUE THREAD

**Issue by Horizon733** [RasaHQ/rasa#7416]
***Also like to tag along @koaning he was the one to whom I showed this when we where in workshop for Rasa chatbot organized by Me in India. *Rasa version**: 2.0.2

**Rasa SDK version** (if used & relevant): 2.1.2

**Rasa X version** (if used & relevant): 0.33.2

**Python version**: 3.8.5

**Operating system** (windows, osx, ...): Windows

**Issue**: When used spaces in domain section rasa x recognizes the indentation but when used tab for adding spaces it gives Error 500 Here is screenshot of that error: With tabs [<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/57827233/100634144-ed833300-3354-11eb-9eee-cd743f57f990.png)</span>](https://user-images.githubusercontent.com/57827233/100634144-ed833300-3354-11eb-9eee-cd743f57f990.png) with spaces [<span class="image-wrap" style="">![](https://user-images.githubusercontent.com/57827233/100634193-fc69e580-3354-11eb-8c1d-429dcbc9858b.png)</span>](https://user-images.githubusercontent.com/57827233/100634193-fc69e580-3354-11eb-8c1d-429dcbc9858b.png)

**Error (including full traceback)**:

 Traceback (most recent call last):
 File "e:\anaconda3\envs\rasa-workshop\lib\site-packages\sanic\app.py", line 939, in handle_request
 response = await response
 File "e:\anaconda3\envs\rasa-workshop\lib\site-packages\rasax\community\api\decorators.py", line 213, in decorated_function
 return await await_and_return_response(args, kwargs, request)
 File "e:\anaconda3\envs\rasa-workshop\lib\site-packages\rasax\community\api\decorators.py", line 143, in await_and_return_response 
 response = await response
 File "e:\anaconda3\envs\rasa-workshop\lib\site-packages\rasax\community\api\decorators.py", line 50, in decorated_function
 return await f(request, user=user, *args, **kwargs)
 File "e:\anaconda3\envs\rasa-workshop\lib\site-packages\rasax\community\api\blueprints\project.py", line 384, in update_domain 
 updated_domain = DomainService(
 File "e:\anaconda3\envs\rasa-workshop\lib\site-packages\rasax\community\services\domain_service.py", line 140, in validate_and_store_domain_yaml
 domain = RasaDomain.from_yaml(domain_yaml)
 File "e:\anaconda3\envs\rasa-workshop\lib\site-packages\rasa\shared\core\domain.py", line 162, in from_yaml
 raise e
 File "e:\anaconda3\envs\rasa-workshop\lib\site-packages\rasa\shared\core\domain.py", line 149, in from_yaml
 rasa.shared.utils.validation.validate_yaml_schema(
 File "e:\anaconda3\envs\rasa-workshop\lib\site-packages\rasa\shared\utils\validation.py", line 143, in validate_yaml_schema
 raise YamlSyntaxException(underlying_yaml_exception=e)
 rasa.shared.exceptions.YamlSyntaxException: Failed to read YAML. while scanning for the next token
 found character '\t' that cannot start any token
 in "<unicode string>", line 23, column 1:
 type: float
 ^ (line: 23)

**Command or request that led to error**: rasa x <- to start rasax and save changes button

**Content of configuration file (config.yml)** (if relevant):

**Content of domain file (domain.yml)** (if relevant):

 session_config:
 session_expiration_time: 60
 carry_over_slots_to_new_session: true
 intents:

*   greet
*   goodbye
*   affirm
*   deny
*   mood_great
*   mood_unhappy
*   bot_challenge
*   ask_timings
*   ask_menu
*   take_order
*   ask_details
*   chitchat
     entities:
*   name
*   email
*   order
     slots:
     age:
     type: float
     influence_conversation: false
     max_value: 1
     min_value: 0
     email:
     type: text
     influence_conversation: true
     name:
     type: text
     influence_conversation: true
     order:
     type: list
     influence_conversation: true
     responses:
     utter_greet:
*   text: Hey! How are you?
     utter_cheer_up:
*   image: 'https://i.imgur.com/nGF1K8f.jpg'
     text: 'Here is something to cheer you up:'
     utter_did_that_help:
*   text: Did that help you?
     utter_happy:
*   text: 'Great, carry on!'
     utter_goodbye:
*   text: Bye
     utter_iamabot:
*   text: 'I am a bot, powered by Rasa.'
     utter_timings:
*   text: Our restaurant is opened from Morning 10am till 12am Midnight
     utter_menu:
*   text: |-
     1\. Panner Butter Masala
     2\. Pizza
     3\. Burger
     4\. Roti
     utter_ask_details:
*   text: Please provide us with your details(name and email id)
     utter_confirm:
*   buttons:
*   payload: /affirm
     title: 'Yes'
*   payload: /deny
     title: 'No'
     text: Should I confirm your order?
     utter_thank_you:
*   text: Thank you!
     actions:
*   action_menu
*   action_send_mail

 ```

**Comment by sara-tagger** [comment]
Thanks for the issue, @joejuzl will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by joejuzl** [comment]
Hi @Horizon733 technically tabs are actually forbidden in yaml, see: https://yaml.org/faq.html.

**Comment by Horizon733** [comment]
> Hi @Horizon733 technically tabs are actually forbidden in yaml, see: https://yaml.org/faq.html.

But in Domain file it doesn't so that's why. If we keep just spaces or both(tabs and spaces) in both places then there won't be this error.

**Comment by joejuzl** [comment]
> But in Domain file it doesn't so that's why. If we keep just spaces or both(tabs and spaces) in both places then there won't be this error.

Are you sure that your tabs are not being converted to spaces by your editor?

I get this error when I run `rasa train` with a domain file containing tabs:
```
YamlSyntaxException: Failed to read '/Users/josephjuzl/code/myrasa/domain.yml'. while scanning for the next token
found character '\t' that cannot start any token
  in "/Users/josephjuzl/code/myrasa/domain.yml", line 5, column 1:
        - greet
    ^ (line: 5)

You can use https://yamlchecker.com/ to validate the YAML syntax of your file.
```

**Comment by joejuzl** [comment]
Although I do agree that it's a bit weird that the yaml editor in rasa x allows tabs but then fails like that.

**Comment by Horizon733** [comment]
> > But in Domain file it doesn't so that's why. If we keep just spaces or both(tabs and spaces) in both places then there won't be this error.
> 
> Are you sure that your tabs are not being converted to spaces by your editor?
> 
> I get this error when I run `rasa train` with a domain file containing tabs:
> 
> ```
> YamlSyntaxException: Failed to read '/Users/josephjuzl/code/myrasa/domain.yml'. while scanning for the next token
> found character '\t' that cannot start any token
>   in "/Users/josephjuzl/code/myrasa/domain.yml", line 5, column 1:
>         - greet
>     ^ (line: 5)
> 
> You can use https://yamlchecker.com/ to validate the YAML syntax of your file.
> ```

Yes Because when I and Vincent Checked the editor showed us Tabs and not spaces

**Comment by joejuzl** [comment]
Try with this:
```
intents:
	- greet
	- goodbye
responses:
	utter_greet:
	- text: Hey! How are you?
```

**Comment by Horizon733** [comment]
> Try with this:
> 
> ```
> intents:
> 	- greet
> 	- goodbye
> responses:
> 	utter_greet:
> 	- text: Hey! How are you?
> ```

This provides more than 2 spaces

**Comment by joejuzl** [comment]
Try loading it in python and see what characters you can find.

**Comment by Horizon733** [comment]
> Try loading it in python and see what characters you can find.

2 tabs thats equal to 4 spaces in python 3.7 IDE

**Comment by joejuzl** [comment]
```
In [1]: text = open('domain.yml', 'r').read()

In [2]: text
Out[2]: 'intents:\n\t- greet\n\t- goodbye\nresponses:\n\tutter_greet:\n\t- text: Hey! How are you?\n'

```

The `\t` character represents a tab. It is a special character, different from a space. See how I can use `expandtabs` to replace it with any number of spaces?

```
In [3]: text.expandtabs(0)
Out[3]: 'intents:\n- greet\n- goodbye\nresponses:\nutter_greet:\n- text: Hey! How are you?\n'

In [4]: text.expandtabs(10)
Out[4]: 'intents:\n          - greet\n          - goodbye\nresponses:\n          utter_greet:\n          - text: Hey! How are you?\n'
```

And if I try to parse it using yaml:
```
import yaml
list(yaml.parse(text))


ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "<unicode string>", line 2, column 1:
        - greet
    ^

```

I get an error.

**Comment by Horizon733** [comment]
oh I see so what if we remove the tab option everywhere so, this issue won't arrive

**Comment by Horizon733** [comment]
Whenever the domain orany yml is ran it needs to be checked for tabs. For example, when running rasa train

**Comment by joejuzl** [comment]
> oh I see so what if we remove the tab option everywhere so, this issue won't arrive

Yeah I think what makes it confusing is that it lets you input tabs in the rasa x UI. And then it doesn't highlight it as an error until you save it.

Do you think it would be clearer if it showed a warning as soon as you entered a tab character?

**Comment by Horizon733** [comment]
Yep that too is great idea. This will work, also some might say like tab works with Rasa and not in Rasa x GUI. So, tab checking needs to be there in Rasa.
What do you think?

**Comment by joejuzl** [comment]
I think that the reason the tabs seem to work for you with rasa is that your IDE is converting them to spaces when you save. And if you were to load the raw text you would see that it actually contains spaces.

**Comment by Horizon733** [comment]
Yeah that might be the case. So, better idea just to show up warning in Rasa x GUI.
