### ISSUE TITLE
can't install rasa-nlu on ubuntu 20.04

### ISSUE THREAD

**Issue by kishanmaharaj** [RasaHQ/rasa#7431]
**Rasa version**: 2.0.6

**Rasa SDK version** (if used & relevant): 2.0.0

**Rasa X version** (if used & relevant):None

**Python version**:3.8.5

**Operating system** : Ubuntu 20.04

**Issue**:
I can't install rasa-nlu 

**Error (including full traceback)**:
```
 ERROR: Command errored out with exit status 1:
     command: /home/kishan/Documents/Projects/Chat_Bots/RASA/rasa/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fcvns88g/matplotlib_d2081837d52140a88bd37d7f25475210/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fcvns88g/matplotlib_d2081837d52140a88bd37d7f25475210/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-y7ofa828
         cwd: /tmp/pip-install-fcvns88g/matplotlib_d2081837d52140a88bd37d7f25475210/
    Complete output (62 lines):
    ============================================================================
    Edit setup.cfg to change the build options
    
    BUILDING MATPLOTLIB
                matplotlib: yes [2.2.5]
                    python: yes [3.8.5 (default, Jul 28 2020, 12:59:40)  [GCC
                            9.3.0]]
                  platform: yes [linux]
    
    REQUIRED DEPENDENCIES AND EXTENSIONS
                     numpy: yes [version 1.19.1]
          install_requires: yes [handled by setuptools]
                    libagg: yes [pkg-config information for 'libagg' could not
                            be found. Using local copy.]
                  freetype: no  [The C/C++ header for freetype2 (ft2build.h)
                            could not be found.  You may need to install the
                            development package.]
                       png: no  [pkg-config information for 'libpng' could not
                            be found.]
                     qhull: yes [pkg-config information for 'libqhull' could not
                            be found. Using local copy.]
    
    OPTIONAL SUBPACKAGES
               sample_data: yes [installing]
                  toolkits: yes [installing]
                     tests: no  [skipping due to configuration]
            toolkits_tests: no  [skipping due to configuration]
    
    OPTIONAL BACKEND EXTENSIONS
                    macosx: no  [Mac OS-X only]
                    qt5agg: no  [PySide2 not found; PyQt5 not found]
                    qt4agg: no  [PySide not found; PyQt4 not found]
                   gtk3agg: no  [Requires pygobject to be installed.]
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-fcvns88g/matplotlib_d2081837d52140a88bd37d7f25475210/setup.py", line 252, in <module>
        msg = pkg.install_help_msg()
      File "/tmp/pip-install-fcvns88g/matplotlib_d2081837d52140a88bd37d7f25475210/setupext.py", line 718, in install_help_msg
        release = platform.linux_distribution()[0].lower()
    AttributeError: module 'platform' has no attribute 'linux_distribution'
                 gtk3cairo: no  [Requires cairocffi or pycairo to be installed.]
                    gtkagg: no  [Requires pygtk]
                     tkagg: yes [installing; run-time loading from Python Tcl /
                            Tk]
                     wxagg: no  [requires wxPython]
                       gtk: no  [Requires pygtk]
                       agg: yes [installing]
                     cairo: no  [cairocffi or pycairo not found]
                 windowing: no  [Microsoft Windows only]
    
    OPTIONAL LATEX DEPENDENCIES
                    dvipng: no
               ghostscript: yes [version 9.50]
                     latex: no
                   pdftops: yes [version 0.86.1]
    
    OPTIONAL PACKAGE DATA
                      dlls: no  [skipping due to configuration]
    
    ============================================================================
                            * The following required packages can not be built:
                            * freetype, png
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Command or request that led to error**:
```
pip3 install rasa-nlu
```
**Already attempted**:
```
$ pip3 install pypng
$ pip3 install freetype-py
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @koaning will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by tmbo** [comment]
@tczekajlo you were looking into ubuntu 20 the other day, any chance it was due to this error?

**Comment by tczekajlo** [comment]
It looks like `matplotlib` in the 2.2.5 version uses the `platform.linux_distribution` function, Python 3.7 onwards have no longer `platform.linux_distribution()` (https://bugs.python.org/issue1322). The `matplotlib` removed the `platform.linux_distribution` function.

The only solution here that I see is to use python 3.6 if you wanna run the rasa-nlu on Ubuntu 20.

**Comment by tczekajlo** [comment]
I'll close the issue. Due to the dependencies, the rasa-nlu doesn't work on Ubuntu 20.04.

@tmbo is it something that we wanna change?

**Comment by virtualroot** [comment]
This issue doesn't seem relevant anymore. So I'm closing it for now. Please reopen if I'm mistaken. 🙏 

```
rasa λ grep matplotlib pyproject.toml
matplotlib = ">=3.1,<3.4"
```
