### ISSUE TITLE
Default action leads to error

### ISSUE THREAD

**Issue by kaiogu** [RasaHQ/rasa#7444]
**Rasa version**:
```
❯ rasa --version
Rasa Version     : 2.1.2
Rasa SDK Version : 2.1.2
Rasa X Version   : 0.34.0
Python Version   : 3.8.0
Operating System : Linux-4.15.0-124-generic-x86_64-with-glibc2.10
```

**Issue**:
I'm trying to implement Two-Stage-Fallback on rasa x local mode. I followed the [instructions in the docs](https://rasa.com/docs/rasa/fallback-handoff#two-stage-fallback) but they are not enough to get the two stage fallback to work.

I get the following error on the actions server
```
2020-12-03 13:59:46 ERROR    rasa_sdk.endpoint  - No registered action found for name 'action_default_ask_affirmation'.
```

And the next one in rasa x:
```
2020-12-03 15:12:19 ERROR    rasa.core.processor  - Encountered an exception while running action 'action_two_stage_fallback'.Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
Traceback (most recent call last):
  File "/home/kutsch/miniconda3/envs/rasa/lib/python3.8/site-packages/rasa/core/actions/action.py", line 611, in run
    response = await self.action_endpoint.request(
  File "/home/kutsch/miniconda3/envs/rasa/lib/python3.8/site-packages/rasa/utils/endpoints.py", line 154, in request
    raise ClientResponseError(
rasa.utils.endpoints.ClientResponseError: 404, Not Found, body='b'{"error":"No registered action found for name \'action_default_ask_affirmation\'.","action_name":"action_default_ask_affirmation"}''

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/kutsch/miniconda3/envs/rasa/lib/python3.8/site-packages/rasa/core/processor.py", line 749, in _run_action
    events = await action.run(
  File "/home/kutsch/miniconda3/envs/rasa/lib/python3.8/site-packages/rasa/core/actions/loops.py", line 29, in run
    events += await self.do(output_channel, nlg, tracker, domain, events)
  File "/home/kutsch/miniconda3/envs/rasa/lib/python3.8/site-packages/rasa/core/actions/two_stage_fallback.py", line 46, in do
    return await self._ask_affirm(output_channel, nlg, tracker, domain)
  File "/home/kutsch/miniconda3/envs/rasa/lib/python3.8/site-packages/rasa/core/actions/two_stage_fallback.py", line 61, in _ask_affirm
    return await affirm_action.run(output_channel, nlg, tracker, domain)
  File "/home/kutsch/miniconda3/envs/rasa/lib/python3.8/site-packages/rasa/core/actions/action.py", line 635, in run
    raise RasaException("Failed to execute custom action.") from e
rasa.shared.exceptions.RasaException: Failed to execute custom action.
```

**Command or request that led to error**:
Nonsense text while chatting with bot on rasa x to trigger fallback.

**Content of configuration file (config.yml)** (if relevant):
Left it at the recommended default, only changed the Fallback Settings:
```
- name: FallbackClassifier
  threshold: 0.8
  ambiguity_threshold: 0.1   
```

---
EDIT:
Language is also changed to german in config.yml.

**Definition of Done**
- [ ]  clarify with user and see whether there are possible next steps to improve documentation

**Comment by sara-tagger** [comment]
Thanks for the issue, @amn41 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by kaiogu** [comment]
I tried it on a fresh init and I think I found the culprit: Two-Stage-Fallback seems to only be available in English.

I might have a go at fixing this after the weekend.

**Comment by amn41** [comment]
thanks for the heads up! would be an awesome contribution :)

**Comment by ancalita** [comment]
Hi @kaiogu, double-checking if you managed to get to the bottom of this issue?
If so, could you please post the solution to this thread? Let us know either way.

**Comment by TyDunn** [comment]
@kaiogu Please reopen this if you still have problems / questions
