### ISSUE TITLE
docs build error

### ISSUE THREAD

**Issue by chenwei182729** [RasaHQ/rasa#7538]
**Rasa version**: 2.1.3
when i build docs in docs directory,some error happen

```basj
yarn run v1.22.10
$ docusaurus build --out-dir build/docs/rasa
Creating an optimized production build...
no versions.json file found
Error: Cannot find module './docs/reference/sidebar.json'
Require stack:
- D:\gitstore\rasa-2.1.3\docs\sidebars.js
- D:\gitstore\rasa-2.1.3\docs\node_modules\@docusaurus\plugin-content-docs\lib\sidebars.js
- D:\gitstore\rasa-2.1.3\docs\node_modules\@docusaurus\plugin-content-docs\lib\index.js
- D:\gitstore\rasa-2.1.3\docs\node_modules\@docusaurus\core\lib\server\plugins\init.js
- D:\gitstore\rasa-2.1.3\docs\node_modules\@docusaurus\core\lib\server\plugins\index.js
- D:\gitstore\rasa-2.1.3\docs\node_modules\@docusaurus\core\lib\server\index.js
- D:\gitstore\rasa-2.1.3\docs\node_modules\@docusaurus\core\lib\commands\build.js
- D:\gitstore\rasa-2.1.3\docs\node_modules\@docusaurus\core\lib\index.js
- D:\gitstore\rasa-2.1.3\docs\node_modules\@docusaurus\core\bin\docusaurus.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (D:\gitstore\rasa-2.1.3\docs\sidebars.js:136:9)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at Object.module.exports [as default] (D:\gitstore\rasa-2.1.3\docs\node_modules\import-fresh\index.js:31:59)
    at Object.loadSidebars (D:\gitstore\rasa-2.1.3\docs\node_modules\@docusaurus\plugin-content-docs\lib\sidebars.js:131:47)
    at loadVersion (D:\gitstore\rasa-2.1.3\docs\node_modules\@docusaurus\plugin-content-docs\lib\index.js:95:45)
    at Array.map (<anonymous>)
    at Object.loadContent (D:\gitstore\rasa-2.1.3\docs\node_modules\@docusaurus\plugin-content-docs\lib\index.js:147:68)
    at D:\gitstore\rasa-2.1.3\docs\node_modules\@docusaurus\core\lib\server\plugins\index.js:54:59
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by chenwei182729** [comment]
sidebars.js not exits in rasa 2.1.3 ,and pydoc-markdown poetry command not install
