### ISSUE TITLE
Problems starting Rasa X on Windows 10 when using special characters

### ISSUE THREAD

**Issue by JBrettas** [RasaHQ/rasa#7561]
**Rasa version**: 2.1.3

**Rasa SDK version** (if used & relevant): 2.1.2

**Rasa X version** (if used & relevant): 0.34.0

**Python version**: 3.8.5

**Operating system** (windows, osx, ...): Windows 10

**Issue**: Can't start rasa x from Windows while using the upgraded rasa stack, even after just starting a dummy project with `rasa init` (it seems that this issue was already been reported). But before arriving at this, I had another issue: it might be the case that special characters such as 'ç', 'é' or 'á' when present on the 'nlu.yml' (raw in sentence or as normalized value/synonym for an entity) or the 'stories.yml' file implies the error below when calling `rasa x`. Seems like Linux also doesn't have the encoding issues presented here: [https://github.com/RasaHQ/rasa/issues/7541](https://github.com/RasaHQ/rasa/issues/7541)

`rasa shell` and `rasa shell nlu` works just fine using the same data.

**Error (including full traceback)**:

 Starting Rasa X in local mode... 🚀
 Traceback (most recent call last):
 File "c:\users\my_user\appdata\local\continuum\anaconda3\envs\rasa213\lib\site-packages\rasa\shared\utils\io.py", line 122, in read_file
 return f.read()
 File "c:\users\my_user\appdata\local\continuum\anaconda3\envs\rasa213\lib\codecs.py", line 322, in decode
 (result, consumed) = self._buffer_decode(data, self.errors, final)
 UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe1 in position 44: invalid continuation byte

 During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
 File "c:\users\my_user\appdata\local\continuum\anaconda3\envs\rasa213\lib\site-packages\rasa\cli\x.py", line 472, in run_locally
 local.main(
 File "C:\Users\my_user\AppData\Roaming\Python\Python38\site-packages\rasax\community\local.py", line 224, in main
 _initialize_with_local_data(
 File "C:\Users\my_user\AppData\Roaming\Python\Python38\site-packages\rasax\community\local.py", line 160, in _initialize_with_local_data
 loop.run_until_complete(
 File "c:\users\my_user\appdata\local\continuum\anaconda3\envs\rasa213\lib\asyncio\base_events.py", line 616, in run_until_complete
 return future.result()
 File "C:\Users\my_user\AppData\Roaming\Python\Python38\site-packages\rasax\community\initialise.py", line 336, in inject_files_from_disk
 await inject_stories(
 File "C:\Users\my_user\AppData\Roaming\Python\Python38\site-packages\rasax\community\initialise.py", line 130, in inject_stories
 story_blocks = await story_service.save_stories_from_files(
 File "C:\Users\my_user\AppData\Roaming\Python\Python38\site-packages\rasax\community\services\story_service.py", line 545, in save_stories_from_files
 additional_blocks = await self.save_stories(
 File "C:\Users\my_user\AppData\Roaming\Python\Python38\site-packages\rasax\community\services\story_service.py", line 437, in save_stories
 processed_stories = await self._extract_stories_yaml(
 File "C:\Users\my_user\AppData\Roaming\Python\Python38\site-packages\rasax\community\services\story_service.py", line 365, in _extract_stories_yaml
 steps_list = self.get_story_steps(
 File "C:\Users\my_user\AppData\Roaming\Python\Python38\site-packages\rasax\community\services\story_service.py", line 212, in get_story_steps
 return StoryService._reader_read_from_string(reader, story_string)
 File "C:\Users\my_user\AppData\Roaming\Python\Python38\site-packages\rasax\community\services\story_service.py", line 133, in _reader_read_from_string
 return reader.read_from_file(temp_path)
 File "c:\users\my_user\appdata\local\continuum\anaconda3\envs\rasa213\lib\site-packages\rasa\shared\core\training_data\story_reader\yaml_story_reader.py", line 95, in read_from_file
 rasa.shared.utils.io.read_file(
 File "c:\users\my_user\appdata\local\continuum\anaconda3\envs\rasa213\lib\site-packages\rasa\shared\utils\io.py", line 128, in read_file
 raise FileIOException(
 rasa.shared.exceptions.FileIOException: Failed to read file 'C:\Users\my_user\AppData\Local\Temp\tmpe3z8ap10', could not read the file using utf-8 to decode it. Please make sure the file is stored with this encoding.

 Sorry, something went wrong (see error above). Make sure to start Rasa X with valid data and valid domain and config files. Please, also check any warnings that popped up.
 If you need help fixing the issue visit our forum: [https://forum.rasa.com/](https://forum.rasa.com/).

**Command or request that led to error**:

 rasa x

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @rctatman will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by yilaguan** [comment]
I have the same error when I run rasa x in windows10

**Comment by Belentxuga** [comment]
I have the same issue. rasa x won´t work if I have any special character as 'á' or 'ñ' in the stories.yml file. I have this characters in the responses of my domain file and in the examples of my nlu file and it works correctly, but if I add it in the stories it doesn't let me run rasa x.
Version details:
```
Rasa Version: 2.6.2
Rasa SDK Version: 2.6.0
Rasa X Version: 0.40.0
Python Version: 3.8.11
```
