### ISSUE TITLE
Rasa X v0.34 not loading

### ISSUE THREAD

**Issue by sujee** [RasaHQ/rasa#7602]
**Rasa version**: 2.2.1

**Rasa SDK version** (if used & relevant): 2.2.0

**Rasa X version** (if used & relevant):  0.34.0

**Python version**: 3.8.5

**Operating system** (windows, osx, ...):Linux-5.4.0-58-generic-x86_64-with-glibc2.10

**Issue**: Rasa X v0.34 not loading

I have been using rasaX 0.32.2 and just tried updating no 0.34. I got the following error 

**Error (including full traceback)**:
```
Traceback (most recent call last):
  File "/home/sujee/anaconda3/envs/rasa2/lib/python3.8/site-packages/rasa/cli/x.py", line 493, in run_locally
    local.main(
TypeError: main() got an unexpected keyword argument 'domain_path'

```

**Command or request that led to error**:

```bash
# Here are my steps to reproduce

$  conda create -n rasa2  python=3.8

$  conda activate rasa2

$  pip3 install rasa-x --extra-index-url https://pypi.rasa.com/simple

$  conda list | grep -i rasa
rasa                      2.2.1                    pypi_0    pypi
rasa-sdk                  2.2.0                    pypi_0    pypi
rasa-x                    0.34.0                   pypi_0    pypi

# started a default project
$  rasa init

$  rasa train

$  rasa shell
# works fine on CLI

 # tried to launch rasa x
 $  rasa x

 # error
2020-12-18 11:06:09 DEBUG    git.cmd  - Popen(['git', 'version'], cwd=/home/sujee/tmp/test, universal_newlines=False, shell=None, istream=None)
2020-12-18 11:06:09 DEBUG    rasa.cli.utils  - Parameter 'endpoints' not set. Using default location 'endpoints.yml' instead.
Traceback (most recent call last):
  File "/home/sujee/anaconda3/envs/rasa2/lib/python3.8/site-packages/rasa/cli/x.py", line 493, in run_locally
local.main(
TypeError: main() got an unexpected keyword argument 'domain_path'
```

**Content of configuration file (config.yml)** (if relevant):
```yml
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.
#   - name: WhitespaceTokenizer
#   - name: RegexFeaturizer
#   - name: LexicalSyntacticFeaturizer
#   - name: CountVectorsFeaturizer
#   - name: CountVectorsFeaturizer
#     analyzer: char_wb
#     min_ngram: 1
#     max_ngram: 4
#   - name: DIETClassifier
#     epochs: 100
#   - name: EntitySynonymMapper
#   - name: ResponseSelector
#     epochs: 100
#   - name: FallbackClassifier
#     threshold: 0.3
#     ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#   - name: RulePolicy


```

**Content of domain file (domain.yml)** (if relevant):
```yml
version: "2.0"

intents:
  - greet
  - goodbye
  - affirm
  - deny
  - mood_great
  - mood_unhappy
  - bot_challenge

responses:
  utter_greet:
  - text: "Hey! How are you?"

  utter_cheer_up:
  - text: "Here is something to cheer you up:"
    image: "https://i.imgur.com/nGF1K8f.jpg"

  utter_did_that_help:
  - text: "Did that help you?"

  utter_happy:
  - text: "Great, carry on!"

  utter_goodbye:
  - text: "Bye"

  utter_iamabot:
  - text: "I am a bot, powered by Rasa."

session_config:
  session_expiration_time: 60
  carry_over_slots_to_new_session: true

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @rctatman will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by amn41** [comment]
closing, looks like a duplicate of https://github.com/RasaHQ/rasa/issues/7592

**Comment by sujee** [comment]
Thanks for responding.  
Hope to see a fix soon.  Because installing rasax 0.34 is actually pulling down rasa 2.2.1 as a dependency and installing it... only they seem not be compatible :-)
