### ISSUE TITLE
e2e learning story syntax error

### ISSUE THREAD

**Issue by desmarchris** [RasaHQ/rasa#7631]
**Rasa version**: 2.2.2

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**: 3.8.6

**Operating system** (windows, osx, ...): osx

**Issue**: I'm trying to capture a name using an e2e story. When I start the user statement in the training data with an entity, the model fails to train citing a yaml error. Here's the story:

*   story: capture name
     steps:
*   user: hi.
*   bot: what's your name?
*   user: <span class="error">[chris]</span>(name)
*   action: utter_name

**Error (including full traceback)**:

 (e2e) chris@ChristophersMBP e2e % rasa train; rasa shell
 YamlSyntaxException: Failed to read 'data/stories.yml'. while parsing a block mapping
 in "data/stories.yml", line 58, column 5
 did not find expected key
 in "data/stories.yml", line 58, column 18

 You can use [https://yamlchecker.com/](https://yamlchecker.com/) to validate the YAML syntax of your file.
 ^CTraceback (most recent call last):
 File "/Users/chris/.pyenv/versions/e2e/bin/rasa", line 5, in <module>
 from rasa.__main__ import main
 File "/Users/chris/.pyenv/versions/3.8.6/envs/e2e/lib/python3.8/site-packages/rasa/__init__.py", line 9, in <module>
 from rasa.train import train
 File "/Users/chris/.pyenv/versions/3.8.6/envs/e2e/lib/python3.8/site-packages/rasa/train.py", line 39, in <module>
 from rasa.core.agent import Agent
 File "/Users/chris/.pyenv/versions/3.8.6/envs/e2e/lib/python3.8/site-packages/rasa/core/agent.py", line 29, in <module>
 from rasa.core.policies.ensemble import PolicyEnsemble, SimplePolicyEnsemble
 File "/Users/chris/.pyenv/versions/3.8.6/envs/e2e/lib/python3.8/site-packages/rasa/core/policies/__init__.py", line 2, in <module>
 from rasa.core.policies.policy import Policy
 File "/Users/chris/.pyenv/versions/3.8.6/envs/e2e/lib/python3.8/site-packages/rasa/core/policies/policy.py", line 27, in <module>
 from rasa.core.featurizers.single_state_featurizer import SingleStateFeaturizer
 File "/Users/chris/.pyenv/versions/3.8.6/envs/e2e/lib/python3.8/site-packages/rasa/core/featurizers/single_state_featurizer.py", line 27, in <module>
 from rasa.utils.tensorflow.model_data_utils import TAG_ID_ORIGIN
 File "/Users/chris/.pyenv/versions/3.8.6/envs/e2e/lib/python3.8/site-packages/rasa/utils/tensorflow/model_data_utils.py", line 9, in <module>
 from rasa.utils.tensorflow.model_data import Data, FeatureArray
 File "/Users/chris/.pyenv/versions/3.8.6/envs/e2e/lib/python3.8/site-packages/rasa/utils/tensorflow/model_data.py", line 5, in <module>
 import tensorflow as tf
 File "/Users/chris/.pyenv/versions/3.8.6/envs/e2e/lib/python3.8/site-packages/tensorflow/__init__.py", line 41, in <module>
 from tensorflow.python.tools import module_util as _module_util
 File "/Users/chris/.pyenv/versions/3.8.6/envs/e2e/lib/python3.8/site-packages/tensorflow/python/__init__.py", line 40, in <module>
 from tensorflow.python.eager import context
 File "/Users/chris/.pyenv/versions/3.8.6/envs/e2e/lib/python3.8/site-packages/tensorflow/python/eager/context.py", line 35, in <module>
 from tensorflow.python import pywrap_tfe
 File "/Users/chris/.pyenv/versions/3.8.6/envs/e2e/lib/python3.8/site-packages/tensorflow/python/pywrap_tfe.py", line 28, in <module>
 from tensorflow.python import pywrap_tensorflow
 File "/Users/chris/.pyenv/versions/3.8.6/envs/e2e/lib/python3.8/site-packages/tensorflow/python/pywrap_tensorflow.py", line 64, in <module>
 from tensorflow.python._pywrap_tensorflow_internal import *

**Command or request that led to error**:

 rasa train

**Content of configuration file (config.yml)** (if relevant):

<pre># Configuration for Rasa NLU.

1.  [https://rasa.com/docs/rasa/nlu/components/](https://rasa.com/docs/rasa/nlu/components/)
     language: en

pipeline:

1.  # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
2.  # If you'd like to customize it, uncomment and adjust the pipeline.
3.  # See [https://rasa.com/docs/rasa/tuning-your-model](https://rasa.com/docs/rasa/tuning-your-model) for more information.
4.  - name: WhitespaceTokenizer
5.  - name: RegexFeaturizer
6.  - name: LexicalSyntacticFeaturizer
7.  - name: CountVectorsFeaturizer
8.  - name: CountVectorsFeaturizer
9.  analyzer: char_wb
10.  min_ngram: 1
11.  max_ngram: 4
12.  - name: DIETClassifier
13.  epochs: 100
14.  - name: EntitySynonymMapper
15.  - name: ResponseSelector
16.  epochs: 100
17.  - name: FallbackClassifier
18.  threshold: 0.3
19.  ambiguity_threshold: 0.1

1.  Configuration for Rasa Core.
2.  [https://rasa.com/docs/rasa/core/policies/](https://rasa.com/docs/rasa/core/policies/)
     policies:
3.  # No configuration for policies was provided. The following default policies were used to train your model.
4.  # If you'd like to customize them, uncomment and adjust the policies.
5.  # See [https://rasa.com/docs/rasa/policies](https://rasa.com/docs/rasa/policies) for more information.

*   name: MemoizationPolicy
*   name: TEDPolicy
     max_history: 10
     epochs: 100
*   name: RulePolicy
     </pre>

**Content of domain file (domain.yml)** (if relevant):

<pre>version: "2.0"

intents:

*   greet
*   goodbye
*   affirm
*   deny
*   mood_great
*   mood_unhappy
*   bot_challenge
*   joke

responses:
 utter_greet:

*   text: "Hey! How are you?"

 utter_cheer_up:

*   text: "Here is something to cheer you up:"
     image: "https://i.imgur.com/nGF1K8f.jpg"

 utter_did_that_help:

*   text: "Did that help you?"

 utter_happy:

*   text: "Great, carry on!"

 utter_goodbye:

*   text: "Bye"

 utter_iamabot:

*   text: "I am a bot, powered by Rasa."

 utter_name:

*   text: "nice ta meet ya {name} 

    "

session_config:
 session_expiration_time: 60
 carry_over_slots_to_new_session: true
 </pre>

**Comment by twerkmeister** [comment]
Hi @desmarchris, I think the problem is that yaml thinks that keys starting with `[` constitute a list. Maybe we can fix that somehow. For now, a workaround is to wrap sentences that start with an entity in double quotes indicating that it is a string.

This will work: 
```yaml
- story: capture name
  steps:
  - user: hi.
  - bot: what's your name?
  - user: "[chris](name)"
  - action: utter_name
```
