### ISSUE TITLE
Training from wit.ai data causes exception in extractor.py

### ISSUE THREAD

**Issue by sciguy14** [RasaHQ/rasa#7676]
**Rasa version**: 2.2.2

**Rasa SDK version** (if used & relevant): 2.2.0

**Rasa X version** (if used & relevant): None

**Python version**: 3.8.5

**Operating system** (windows, osx, ...): WSL (Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.29)

**Issue**:
Following the instructions to convert my wit.ai data to Rasa training data results in a Python exception. I followed these instructions: https://rasa.com/docs/rasa/migrate-from/facebook-wit-ai-to-rasa/

My `utterances-1.json` file is present in the `data/` folder as noted in the migration instructions.

**Error (including full traceback)**:
```
(venv) jeremy@PHOENIX:/mnt/c/wit.ai to Rasa$ rasa train nlu
2021-01-03 21:14:05.237561: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2021-01-03 21:14:05.238107: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-01-03 21:14:07.937718: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-01-03 21:14:07.938268: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2021-01-03 21:14:07.938525: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (PHOENIX): /proc/driver/nvidia/version does not exist
The configuration for pipeline was chosen automatically. It was written into the config file at 'config.yml'.
Training NLU model...
2021-01-03 21:14:08 INFO     rasa.shared.nlu.training_data.training_data  - Training data stats:
2021-01-03 21:14:08 INFO     rasa.shared.nlu.training_data.training_data  - Number of intent examples: 1066 (20 distinct intents)

2021-01-03 21:14:08 INFO     rasa.shared.nlu.training_data.training_data  -   Found intents: 'introductions', 'date', 'snooze', 'play_news', 'prev_track', 'weather', 'play_music', 'out_of_scope', 'choose_music', 'curtains', 'stop_audio', 'goodnight', 'greetings', 'pause_audio', 'alarm', 'volume', 'lighting', 'time', 'next_track', 'wikipedia'
2021-01-03 21:14:08 INFO     rasa.shared.nlu.training_data.training_data  - Number of response examples: 0 (0 distinct responses)
2021-01-03 21:14:08 INFO     rasa.shared.nlu.training_data.training_data  - Number of entity examples: 706 (10 distinct entities)
2021-01-03 21:14:08 INFO     rasa.shared.nlu.training_data.training_data  -   Found entity types: 'relative_adjustment', 'wit$location', 'location_1', 'wit$wikipedia_search_query', 'wit$datetime', 'wit$number', 'artist', 'light_type_entity', 'mood', 'song'
2021-01-03 21:14:08 INFO     rasa.shared.nlu.training_data.training_data  -   Found entity roles: 'wikipedia_search_query', 'relative_adjustment', 'number', 'location', 'location_1', 'datetime', 'artist', 'light_type_entity', 'mood', 'song'
2021-01-03 21:14:08 WARNING  rasa.shared.utils.common  - The Entity Roles and Groups feature is currently experimental and might change or be removed in the future 🔬 Please share your feedback on it in the forum (https://forum.rasa.com) to help us make this feature ready for production.
/mnt/c/wit.ai to Rasa/venv/lib/python3.8/site-packages/rasa/shared/utils/io.py:93: UserWarning: Intent 'out_of_scope' has only 1 training examples! Minimum is 2, training may fail.
2021-01-03 21:14:08 INFO     rasa.nlu.model  - Starting to train component WhitespaceTokenizer
2021-01-03 21:14:08 INFO     rasa.nlu.model  - Finished training component.
2021-01-03 21:14:08 INFO     rasa.nlu.model  - Starting to train component RegexFeaturizer
2021-01-03 21:14:08 INFO     rasa.nlu.model  - Finished training component.
2021-01-03 21:14:08 INFO     rasa.nlu.model  - Starting to train component LexicalSyntacticFeaturizer
2021-01-03 21:14:09 INFO     rasa.nlu.model  - Finished training component.
2021-01-03 21:14:09 INFO     rasa.nlu.model  - Starting to train component CountVectorsFeaturizer
2021-01-03 21:14:09 INFO     rasa.nlu.featurizers.sparse_featurizer.count_vectors_featurizer  - 578 vocabulary slots consumed out of 1578 slots configured for text attribute.
2021-01-03 21:14:09 INFO     rasa.nlu.model  - Finished training component.
2021-01-03 21:14:09 INFO     rasa.nlu.model  - Starting to train component CountVectorsFeaturizer
2021-01-03 21:14:09 INFO     rasa.nlu.featurizers.sparse_featurizer.count_vectors_featurizer  - 3866 vocabulary slots consumed out of 5799 slots configured for text attribute.
2021-01-03 21:14:09 INFO     rasa.nlu.model  - Finished training component.
2021-01-03 21:14:09 INFO     rasa.nlu.model  - Starting to train component DIETClassifier
Traceback (most recent call last):
  File "/mnt/c/wit.ai to Rasa/venv/bin/rasa", line 10, in <module>
    sys.exit(main())
  File "/mnt/c/wit.ai to Rasa/venv/lib/python3.8/site-packages/rasa/__main__.py", line 116, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/mnt/c/wit.ai to Rasa/venv/lib/python3.8/site-packages/rasa/cli/train.py", line 195, in train_nlu
    return train_nlu(
  File "/mnt/c/wit.ai to Rasa/venv/lib/python3.8/site-packages/rasa/train.py", line 700, in train_nlu
    return rasa.utils.common.run_in_loop(
  File "/mnt/c/wit.ai to Rasa/venv/lib/python3.8/site-packages/rasa/utils/common.py", line 308, in run_in_loop
    result = loop.run_until_complete(f)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/mnt/c/wit.ai to Rasa/venv/lib/python3.8/site-packages/rasa/train.py", line 749, in _train_nlu_async
    return await _train_nlu_with_validated_data(
  File "/mnt/c/wit.ai to Rasa/venv/lib/python3.8/site-packages/rasa/train.py", line 811, in _train_nlu_with_validated_data
    await rasa.nlu.train(
  File "/mnt/c/wit.ai to Rasa/venv/lib/python3.8/site-packages/rasa/nlu/train.py", line 116, in train
    interpreter = trainer.train(training_data, **kwargs)
  File "/mnt/c/wit.ai to Rasa/venv/lib/python3.8/site-packages/rasa/nlu/model.py", line 209, in train
    updates = component.train(working_data, self.config, **context)
  File "/mnt/c/wit.ai to Rasa/venv/lib/python3.8/site-packages/rasa/nlu/classifiers/diet_classifier.py", line 803, in train
    self.check_correct_entity_annotations(training_data)
  File "/mnt/c/wit.ai to Rasa/venv/lib/python3.8/site-packages/rasa/nlu/extractors/extractor.py", line 418, in check_correct_entity_annotations
    entities_repr = [
  File "/mnt/c/wit.ai to Rasa/venv/lib/python3.8/site-packages/rasa/nlu/extractors/extractor.py", line 422, in <listcomp>
    entity[ENTITY_ATTRIBUTE_VALUE],
KeyError: 'value'
```

**Command or request that led to error**:
```
rasa train nlu
```

**Content of configuration file (config.yml)** (if relevant): N/A

**Content of domain file (domain.yml)** (if relevant): N/A

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @degiz will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by degiz** [comment]
cc @RasaHQ/enable-squad

**Comment by wochinge** [comment]
@degiz Can you please add it our inbox in the future? 

@sciguy14 Seems there is some issue with converting the entities correctly. Do you want to have a go solving it (I'd be happy to support you with the PR) or should we handle it?

**Comment by roots-ai** [comment]
> @degiz Can you please add it our inbox in the future?
> 
> @sciguy14 Seems there is some issue with converting the entities correctly. Do you want to have a go solving it (I'd be happy to support you with the PR) or should we handle it?

Facing the same issue. Please help.

**Comment by wochinge** [comment]
@roots-ai Would you mind creating a PR with the necessary fixes? Unfortunately the team is currently very busy with 3.0 so I don't think we can tackle this one soon ourselves

**Comment by roots-ai** [comment]
> @roots-ai Would you mind creating a PR with the necessary fixes? Unfortunately the team is currently very busy with 3.0 so I don't think we can tackle this one soon ourselves
@wochinge 
Can you please guide me; any ideas or suggestions on what are the possible reasons and how can I go about finding a fix?

**Comment by roots-ai** [comment]
@wochinge ?

**Comment by wochinge** [comment]
@roots-ai Sorry, as I said in my previous comment it's currently very busy and I can't provide a reliable timeline
