### ISSUE TITLE
Cannot initiate model with GPU support, RASA 2.2.3, CUDA 10.1

### ISSUE THREAD

**Issue by Ooiyenchun** [RasaHQ/rasa#7696]
**Rasa version**: 2.2.3

**Rasa SDK version**: 2.2.0

**Python version**: 3.8.5

**Tensorflow version**: 2.3.0

**Operating system**: Windows Server 2019

**Issue**: Cannot initiate model with GPU support, RASA 2.2.3, CUDA 10.1

**Error (including full traceback)**:

 Traceback (most recent call last):
 File "c:\programdata\anaconda3\envs\newenv\lib\runpy.py", line 194, in _run_module_as_main
 return _run_code(code, main_globals, None,
 File "c:\programdata\anaconda3\envs\newenv\lib\runpy.py", line 87, in _run_code
 exec(code, run_globals)
 File "C:\ProgramData\Anaconda3\envs\newEnv\Scripts\rasa.exe__main__.py", line 7, in <module>
 File "c:\programdata\anaconda3\envs\newenv\lib\site-packages\rasa__main__.py", line 116, in main
 cmdline_arguments.func(cmdline_arguments)
 File "c:\programdata\anaconda3\envs\newenv\lib\site-packages\rasa\cli\scaffold.py", line 234, in run
 init_project(args, path)
 File "c:\programdata\anaconda3\envs\newenv\lib\site-packages\rasa\cli\scaffold.py", line 129, in init_project
 print_train_or_instructions(args, path)
 File "c:\programdata\anaconda3\envs\newenv\lib\site-packages\rasa\cli\scaffold.py", line 68, in print_train_or_instructions
 training_result = rasa.train(domain, config, training_files, output)
 File "c:\programdata\anaconda3\envs\newenv\lib\site-packages\rasa\train.py", line 94, in train
 return rasa.utils.common.run_in_loop(
 File "c:\programdata\anaconda3\envs\newenv\lib\site-packages\rasa\utils\common.py", line 308, in run_in_loop
 result = loop.run_until_complete(f)
 File "c:\programdata\anaconda3\envs\newenv\lib\asyncio\base_events.py", line 616, in run_until_complete
 return future.result()
 File "c:\programdata\anaconda3\envs\newenv\lib\site-packages\rasa\train.py", line 163, in train_async
 return await _train_async_internal(
 File "c:\programdata\anaconda3\envs\newenv\lib\site-packages\rasa\train.py", line 342, in _train_async_internal
 await _do_training(
 File "c:\programdata\anaconda3\envs\newenv\lib\site-packages\rasa\train.py", line 388, in _do_training
 model_path = await _train_nlu_with_validated_data(
 File "c:\programdata\anaconda3\envs\newenv\lib\site-packages\rasa\train.py", line 811, in _train_nlu_with_validated_data
 await rasa.nlu.train(
 File "c:\programdata\anaconda3\envs\newenv\lib\site-packages\rasa\nlu\train.py", line 116, in train
 interpreter = trainer.train(training_data, **kwargs)
 File "c:\programdata\anaconda3\envs\newenv\lib\site-packages\rasa\nlu\model.py", line 209, in train
 updates = component.train(working_data, self.config, **context)
 File "c:\programdata\anaconda3\envs\newenv\lib\site-packages\rasa\nlu\classifiers\diet_classifier.py", line 810, in train
 self.model = self._instantiate_model_class(model_data)
 File "c:\programdata\anaconda3\envs\newenv\lib\site-packages\rasa\nlu\classifiers\diet_classifier.py", line 1128, in _instantiate_model_class
 return self.model_class()(
 File "c:\programdata\anaconda3\envs\newenv\lib\site-packages\rasa\nlu\classifiers\diet_classifier.py", line 1146, in __init__
 super().__init__("DIET", config, data_signature, label_data)
 File "c:\programdata\anaconda3\envs\newenv\lib\site-packages\rasa\utils\tensorflow\models.py", line 700, in __init__
 super().__init__(
 File "c:\programdata\anaconda3\envs\newenv\lib\site-packages\rasa\utils\tensorflow\models.py", line 91, in __init__
 super().__init__(**kwargs)
 File "c:\programdata\anaconda3\envs\newenv\lib\site-packages\tensorflow\python\training\tracking\base.py", line 457, in _method_wrapper
 result = method(self, *args, **kwargs)
 File "c:\programdata\anaconda3\envs\newenv\lib\site-packages\tensorflow\python\keras\engine\training.py", line 308, in __init__
 self._init_batch_counters()
 File "c:\programdata\anaconda3\envs\newenv\lib\site-packages\tensorflow\python\training\tracking\base.py", line 457, in _method_wrapper
 result = method(self, *args, **kwargs)
 File "c:\programdata\anaconda3\envs\newenv\lib\site-packages\tensorflow\python\keras\engine\training.py", line 317, in _init_batch_counters
 self._train_counter = variables.Variable(0, dtype='int64', aggregation=agg)
 File "c:\programdata\anaconda3\envs\newenv\lib\site-packages\tensorflow\python\ops\variables.py", line 262, in __call__
 return cls._variable_v2_call(*args, **kwargs)
 File "c:\programdata\anaconda3\envs\newenv\lib\site-packages\tensorflow\python\ops\variables.py", line 244, in _variable_v2_call
 return previous_getter(
 File "c:\programdata\anaconda3\envs\newenv\lib\site-packages\tensorflow\python\ops\variables.py", line 237, in <lambda>
 previous_getter = lambda **kws: default_variable_creator_v2(None, **kws)
 File "c:\programdata\anaconda3\envs\newenv\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 2633, in default_variable_creator_v2
 return resource_variable_ops.ResourceVariable(
 File "c:\programdata\anaconda3\envs\newenv\lib\site-packages\tensorflow\python\ops\variables.py", line 264, in __call__
 return super(VariableMetaclass, cls).__call__(*args, **kwargs)
 File "c:\programdata\anaconda3\envs\newenv\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 1507, in __init__
 self._init_from_args(
 File "c:\programdata\anaconda3\envs\newenv\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 1661, in _init_from_args
 handle = eager_safe_variable_handle(
 File "c:\programdata\anaconda3\envs\newenv\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 242, in eager_safe_variable_handle
 return _variable_handle_from_shape_and_dtype(
 File "c:\programdata\anaconda3\envs\newenv\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 174, in _variable_handle_from_shape_and_dtype
 gen_logging_ops._assert( # pylint: disable=protected-access
 File "c:\programdata\anaconda3\envs\newenv\lib\site-packages\tensorflow\python\ops\gen_logging_ops.py", line 49, in _assert
 _ops.raise_from_not_ok_status(e, name)
 File "c:\programdata\anaconda3\envs\newenv\lib\site-packages\tensorflow\python\framework\ops.py", line 6843, in raise_from_not_ok_status
 six.raise_from(core._status_to_exception(e.code, message), None)
 File "<string>", line 3, in raise_from
 tensorflow.python.framework.errors_impl.InvalidArgumentError: assertion failed: <span class="error">[0]</span> <span class="error">[Op:Assert]</span> name: EagerVariableNameReuse

**Command or request that led to error**:

 Created project directory at 'C:\Users\Administrator\rasa\shoesRecommender'.
 Finished creating project structure.
 ? Do you want to train an initial model? 💪🏽 Yes

**Steps to replicate error**

1.  Create a model by "rasa init"
2.  State path(create path for new project)
3.  "yes" on "Do you want to train an initial model?"

**Message shown on "rasa init"**

 2021-01-08 12:32:28.479585: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
 2021-01-08 12:32:32.243406: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library nvcuda.dll
 2021-01-08 12:32:32.701538: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties:
 pciBusID: 0000:01:00.0 name: GeForce 930M computeCapability: 5.0
 coreClock: 0.941GHz coreCount: 3 deviceMemorySize: 2.00GiB deviceMemoryBandwidth: 13.41GiB/s
 2021-01-08 12:32:32.709264: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudart64_101.dll
 2021-01-08 12:32:32.723489: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cublas64_10.dll
 2021-01-08 12:32:32.733891: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cufft64_10.dll
 2021-01-08 12:32:32.742644: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library curand64_10.dll
 2021-01-08 12:32:32.755053: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusolver64_10.dll
 2021-01-08 12:32:32.764156: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cusparse64_10.dll
 2021-01-08 12:32:32.783373: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library cudnn64_7.dll
 2021-01-08 12:32:32.787887: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
 Welcome to Rasa! 🤖

**Comment by Ooiyenchun** [comment]
Seems like downgrading to Tensorflow 2.2 will solve the "InvalidArgumentError: assertion failed: [0] [Op:Assert] name: EagerVariableNameReuse" error, but RASA require version between 2.4 and 2.3 so it will not work.
Related github post:
https://github.com/tensorflow/tensorflow/issues/38518

**Comment by sara-tagger** [comment]
Thanks for the issue, @wochinge will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by Ooiyenchun** [comment]
w

> Thanks for the issue, @wochinge will get back to you about it soon!
> 
> ###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

Sure! no problem Ms. Sara

**Comment by wochinge** [comment]
> Seems like downgrading to Tensorflow 2.2 
@dakshvar22 Do you think we could safely open up the range of supported `TensorFlow` versions?
Maybe also updating to 2.4 could help as some users reported that this problem doesn't appear in nightlies 🙈 

[This comment](https://github.com/tensorflow/tensorflow/issues/38518#issuecomment-619538236) seems interesting as well 🤔 Anything which comes to mind?

**Comment by wochinge** [comment]
@dakshvar22 What do you think of my above comment?
