### ISSUE TITLE
concurrent.futures._base.CancelledError

### ISSUE THREAD

**Issue by Prostar12** [RasaHQ/rasa#7719]
**Rasa version**:1.7.4

**Rasa SDK version** (if used & relevant):1.7.0

**Rasa X version** (if used & relevant):

**Python version**:3.6

**Operating system** (windows, osx, ...):

**Issue**: I use it occasionally concurrent.futures . base.CancelledError Problem, it appears randomly. I use restchannel and custom action. I can't locate the cause of the problem.

**Error (including full traceback)**:

 Traceback (most recent call last):
 File "/rasa/rasa/core/processor.py", line 834, in _run_action
 events = await action.run(output_channel, nlg, tracker, self.domain)
 File "/rasa/rasa/core/actions/action.py", line 549, in run
 json=json_body, method="post", timeout=DEFAULT_REQUEST_TIMEOUT
 File "/rasa/rasa/utils/endpoints.py", line 148, in request
 **kwargs,
 File "/build/lib/python3.6/site-packages/aiohttp/client.py", line 1012, in __aenter__
 self._resp = await self._coro
 File "/build/lib/python3.6/site-packages/aiohttp/client.py", line 483, in _request
 timeout=real_timeout
 File "/build/lib/python3.6/site-packages/aiohttp/connector.py", line 523, in connect
 proto = await self._create_connection(req, traces, timeout)
 File "/build/lib/python3.6/site-packages/aiohttp/connector.py", line 859, in _create_connection
 req, traces, timeout)
 File "/build/lib/python3.6/site-packages/aiohttp/connector.py", line 967, in _create_direct_connection
 traces=traces), loop=self._loop)
 concurrent.futures._base.CancelledError

**Command or request that led to error**:

**Content of configuration file (config.yml)** (if relevant):

**Content of domain file (domain.yml)** (if relevant):

**Comment by sara-tagger** [comment]
Thanks for the issue, @koaning will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by erohmensing** [comment]
@Prostar12 does this happen when your custom action takes more than 60 seconds to respond?

**Comment by Prostar12** [comment]
@erohmensing No, my custom action just searches value by giving key from Redis, and it won't takes more than 60 seconds.
