### ISSUE TITLE
md to yaml conversion crashes if there's a `\t` character inside the sentence

### ISSUE THREAD

**Issue by koernerfelicia** [RasaHQ/rasa#7727]
**Rasa version**:
2.2.4
**Python version**:
3.7.2
**Operating system** (windows, osx, ...):
OSX

**Issue**:
md to yaml conversion crashes if there's a `\t` character inside the sentence like so:

this will`\t`crash

Trailing or leading `\t` characters seem fine.

**Error (including full traceback)**:
```
Traceback (most recent call last):
  File ".pyenv/versions/rasa-env-3.7.2/bin/rasa", line 5, in <module>
    main()
  File "rasa/rasa/__main__.py", line 116, in main
    cmdline_arguments.func(cmdline_arguments)
  File "rasa/rasa/cli/data.py", line 313, in _convert_nlu_data
    _convert_to_yaml(args.out, args.data, NLUMarkdownToYamlConverter())
  File "rasa/rasa/utils/common.py", line 308, in run_in_loop
    result = loop.run_until_complete(f)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "rasa/rasa/cli/data.py", line 397, in _convert_to_yaml
    if await _convert_file_to_yaml(training_data, output, converter):
  File "rasa/rasa/cli/data.py", line 434, in _convert_file_to_yaml
    await converter.convert_and_write(source_file, target_dir)
  File "rasa/rasa/nlu/training_data/converters/nlu_markdown_to_yaml_converter.py", line 39, in convert_and_write
    source_path
  File "rasa/rasa/shared/nlu/training_data/formats/readerwriter.py", line 33, in read
    return self.reads(rasa.shared.utils.io.read_file(filename), **kwargs)
  File "rasa/rasa/shared/nlu/training_data/formats/markdown.py", line 66, in reads
    line = decode_string(line.strip())
  File "rasa/rasa/shared/nlu/training_data/util.py", line 163, in decode_string
    return UNESCAPE.sub(replace, s)
  File "rasa/rasa/shared/nlu/training_data/util.py", line 161, in replace
    return UNESCAPE_DCT[match.group(GROUP_COMPLETE_MATCH)]
KeyError: '\t'
```

**Command or request that led to error**:
```
rasa data convert nlu -f yaml --data=./data/nlu --out=./data/nlu
```

**Comment by koernerfelicia** [comment]
User question here: https://forum.rasa.com/t/unable-to-convert-data-to-2-x-format-using-convertor/38899/3

**Comment by twerkmeister** [comment]
This is fixed in the current main branch. I think we can close this issue

**Comment by koernerfelicia** [comment]
@twerkmeister I thought @desmarchris was looking at this a while back?

**Comment by twerkmeister** [comment]
@koernerfelicia I don't know ^^. I was just going through issues the other day and this here seems to be already fixed. And both you and @desmarchris gave thumbs up for closing - so I'll close it.
