### ISSUE TITLE
Tensorboard command fails in Docker

### ISSUE THREAD

**Issue by Mazyod** [RasaHQ/rasa#7744]
**Rasa version**: Docker image, rasa/rasa:2.2.5-full

**Issue**:

Very similar to #5336, trying to run tensorboard command seems to fail due to missing packages.

```
docker run --rm -it --entrypoint "tensorboard" rasa/rasa:2.2.5-full
2021-01-17 09:31:52.353959: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2021-01-17 09:31:52.354114: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "/opt/venv/bin/tensorboard", line 8, in <module>
    sys.exit(run_main())
  File "/opt/venv/lib/python3.7/site-packages/tensorboard/main.py", line 65, in run_main
    default.get_plugins(),
  File "/opt/venv/lib/python3.7/site-packages/tensorboard/default.py", line 108, in get_plugins
    return get_static_plugins() + get_dynamic_plugins()
  File "/opt/venv/lib/python3.7/site-packages/tensorboard/default.py", line 146, in get_dynamic_plugins
    "tensorboard_plugins"
  File "/opt/venv/lib/python3.7/site-packages/tensorboard/default.py", line 145, in <listcomp>
    for entry_point in pkg_resources.iter_entry_points(
  File "/opt/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2461, in load
    self.require(*args, **kwargs)
  File "/opt/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2484, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/opt/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 787, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'wheel>=0.26; python_version >= "3"' distribution was not found and is required by the application
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @rctatman will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by wochinge** [comment]
@Mazyod Closing this as this is currently not supported out of the box by the Rasa CLI. Please consider opening up an enhancement request for out-of-the-box tensorboard support (cc @koaning ).

**Comment by Mazyod** [comment]
Probably less trouble if the tags were simply changed, but sure :) unless I misunderstood something
