### ISSUE TITLE
RasaX write a file with nothing encoding，but rasa read the file with utf-8 encoding ,   BOOM!

### ISSUE THREAD

**Issue by RumRaisins** [RasaHQ/rasa#7765]
**Rasa version**:
2.2.2
**Rasa SDK version** (if used & relevant):
2.2.0
**Rasa X version** (if used & relevant):
0.34.0
**Python version**:
 3.7.9
**Operating system** (windows, osx, ...):
Windows-10-10.0.18362-SP0
**Issue**:
The error occurred when using Chinese stories.
rasaX write a file with nothing encoding， but rasa read the file with utf-8 ， 
source code of rasaX at rasax/community/services/story_service.py  line 128 
```
 // no encoding
with tempfile.NamedTemporaryFile(mode="w", delete=False) as f:  
    temp_path = f.name
    f.write(story_string)
```
source code of rasa at rasa/shared/utils/io.py", line 129
```
def read_file(filename: Union[Text, Path], encoding: Text = DEFAULT_ENCODING) -> Any:
    """Read text from a file."""
    try:
        with open(filename, encoding=encoding) as f:    // Wrong happen !!!
            return f.read()
    except FileNotFoundError:
        raise FileNotFoundException(
            f"Failed to read file, " f"'{os.path.abspath(filename)}' does not exist."
        )
```

**Error (including full traceback)**:
```
Starting Rasa X in local mode... 🚀
Traceback (most recent call last):
  File "d:\soft\anaconda\envs\rasa\lib\site-packages\rasa\cli\x.py", line 500, in run_locally
    domain_path=domain_path,
TypeError: main() got an unexpected keyword argument 'domain_path'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\soft\anaconda\envs\rasa\lib\site-packages\rasa\cli\x.py", line 511, in run_locally
    config_path=config_path,
  File "d:\soft\anaconda\envs\rasa\lib\site-packages\rasax\community\local.py", line 225, in main
    project_path, data_path, session, args.port, config_path
  File "d:\soft\anaconda\envs\rasa\lib\site-packages\rasax\community\local.py", line 162, in _initialize_with_local_data
    project_path, data_path, session, config_path=config_path
  File "d:\soft\anaconda\envs\rasa\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "d:\soft\anaconda\envs\rasa\lib\site-packages\rasax\community\initialise.py", line 342, in inject_files_from_disk
    username,
  File "d:\soft\anaconda\envs\rasa\lib\site-packages\rasax\community\initialise.py", line 131, in inject_stories
    story_files, team, project_id, username
  File "d:\soft\anaconda\envs\rasa\lib\site-packages\rasax\community\services\story_service.py", line 553, in save_stories_from_files
    is_test=is_test,
  File "d:\soft\anaconda\envs\rasa\lib\site-packages\rasax\community\services\story_service.py", line 438, in save_stories
    story_string, filename, domain, is_test
  File "d:\soft\anaconda\envs\rasa\lib\site-packages\rasax\community\services\story_service.py", line 366, in _extract_stories_yaml
    story_string, data.FileFormat.YAML, domain, filename, test_stories=is_test
  File "d:\soft\anaconda\envs\rasa\lib\site-packages\rasax\community\services\story_service.py", line 212, in get_story_steps
    return StoryService._reader_read_from_string(reader, story_string)
  File "d:\soft\anaconda\envs\rasa\lib\site-packages\rasax\community\services\story_service.py", line 133, in _reader_read_from_string
    return reader.read_from_file(temp_path)
  File "d:\soft\anaconda\envs\rasa\lib\site-packages\rasa\shared\core\training_data\story_reader\yaml_story_reader.py", line 98, in read_from_file
    filename, rasa.shared.utils.io.DEFAULT_ENCODING
  File "d:\soft\anaconda\envs\rasa\lib\site-packages\rasa\shared\utils\io.py", line 129, in read_file
    f"Failed to read file '{os.path.abspath(filename)}', "
rasa.shared.exceptions.FileIOException: Failed to read file 'C:\Users\87312\AppData\Local\Temp\tmpexrq8zye', could not read the file using utf-8 to decode it. Please make sure the file is stored with this encoding.

Sorry, something went wrong (see error above). Make sure to start Rasa X with valid data and valid domain and config files. Please, also check any warnings that popped up.
If you need help fixing the issue visit our forum: https://forum.rasa.com/.

**Comment by sara-tagger** [comment]
Thanks for the issue, @yennycheung will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by gausie** [comment]
Could you upload the training data file in question?

**Comment by wochinge** [comment]
please re-open if this is still an issue

**Comment by Gray430** [comment]
Hi, I still encountered the same problem.
rasa version:

rasa 2.8.25
rasa_sdk 2.8.4
rasa x 1.0.1
python 3.8.12
system  windows-10-10.0.19043-SP0

my training data nlu.yaml is chinese

**Comment by Gray430** [comment]
traceback:
```
(rasa3) D:\1Python_Project\rasa_first_bot>rasa x
Preparing the local database...
Starting Rasa X in local mode... 🚀
Traceback (most recent call last):
  File "d:\1python\anaconda\anaconda\envs\rasa3\lib\site-packages\rasa\shared\utils\io.py", line 126, in read_file
    return f.read()
  File "d:\1python\anaconda\anaconda\envs\rasa3\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 2522: invalid start byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\1python\anaconda\anaconda\envs\rasa3\lib\site-packages\rasa\cli\x.py", line 494, in run_locally
    local.main(
  File "d:\1python\anaconda\anaconda\envs\rasa3\lib\site-packages\rasax\community\local.py", line 213, in main
    _initialize_with_local_data(
  File "d:\1python\anaconda\anaconda\envs\rasa3\lib\site-packages\rasax\community\local.py", line 127, in _initialize_with_local_data
    loop.run_until_complete(
  File "d:\1python\anaconda\anaconda\envs\rasa3\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "d:\1python\anaconda\anaconda\envs\rasa3\lib\site-packages\rasax\initialise.py", line 454, in inject_files_from_disk
    await inject_stories(
  File "d:\1python\anaconda\anaconda\envs\rasa3\lib\site-packages\rasax\initialise.py", line 268, in inject_stories
    story_blocks = await story_service.save_stories_from_files(
  File "d:\1python\anaconda\anaconda\envs\rasa3\lib\site-packages\rasax\community\services\story_service.py", line 559, in save_stories_from_files 
    additional_blocks = await self.save_stories(
  File "d:\1python\anaconda\anaconda\envs\rasa3\lib\site-packages\rasax\community\services\story_service.py", line 452, in save_stories
    processed_stories = await self._extract_stories_yaml(
  File "d:\1python\anaconda\anaconda\envs\rasa3\lib\site-packages\rasax\community\services\story_service.py", line 375, in _extract_stories_yaml   
    steps_list = self.get_story_steps(
  File "d:\1python\anaconda\anaconda\envs\rasa3\lib\site-packages\rasax\community\services\story_service.py", line 217, in get_story_steps
    return StoryService._reader_read_from_string(
  File "d:\1python\anaconda\anaconda\envs\rasa3\lib\site-packages\rasax\community\services\story_service.py", line 135, in _reader_read_from_string
    return reader.read_from_file(temp_path, skip_validation=skip_validation)
  File "d:\1python\anaconda\anaconda\envs\rasa3\lib\site-packages\rasa\shared\core\training_data\story_reader\yaml_story_reader.py", line 100, in r
ead_from_file
    rasa.shared.utils.io.read_file(
  File "d:\1python\anaconda\anaconda\envs\rasa3\lib\site-packages\rasa\shared\utils\io.py", line 132, in read_file
    raise FileIOException(
rasa.shared.exceptions.FileIOException: Failed to read file 'C:\Users\19789\AppData\Local\Temp\tmp1he_7fzl', could not read the file using utf-8 to
 decode it. Please make sure the file is stored with this encoding.

Sorry, something went wrong (see error above). Make sure to start Rasa X with valid data and valid domain and config files. Please, also check any 
warnings that popped up.
If you need help fixing the issue visit our forum: https://forum.rasa.com/.

```
