### ISSUE TITLE
Failing to start rasa-docs server

### ISSUE THREAD

**Issue by lightmagic1** [RasaHQ/rasa#7792]
**Rasa version**: Main

**Rasa SDK version** (if used & relevant): -

**Rasa X version** (if used & relevant): -

**Python version**: 3.8.3

**Operating system** (windows, osx, ...): Ubuntu 20.04

**Issue**:

I forked rasa repo (at main branch), cloned the project into my computer, cd to docs folder and run:

yarn
yarn start

It returned me the following exception:

**Error (including full traceback)**:
```
lmagic in rasa/docs on  main 
> yarn                      
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "linux" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "linux" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning "@docusaurus/plugin-ideal-image > @docusaurus/lqip-loader@2.0.0-alpha.63" has unmet peer dependency "file-loader@*".
warning "@docusaurus/plugin-ideal-image > @endiliey/react-ideal-image@0.0.11" has unmet peer dependency "prop-types@>=15".
warning " > @lunelson/sass-maps-next@1.0.0" has incorrect peer dependency "@lunelson/sass-throw@2.0.0-rc.4".
warning " > @rasahq/docusaurus-theme-tabula@0.8.3" has incorrect peer dependency "@docusaurus/core@^2.0.0".
warning " > @rasahq/docusaurus-theme-tabula@0.8.3" has unmet peer dependency "postcss@^7.0.32".
warning "redoc > @redocly/react-dropdown-aria@2.0.11" has incorrect peer dependency "styled-components@^5.1.1".
warning "redoc > swagger2openapi > better-ajv-errors@0.6.7" has unmet peer dependency "ajv@4.11.8 - 6".
warning " > sass-loader@9.0.3" has unmet peer dependency "webpack@^4.36.0 || ^5.0.0".
[4/4] Building fresh packages...
Done in 25.49s.
lmagic in rasa/docs on  main took 26s 
> yarn start                
yarn run v1.22.4
$ yarn pre-build && yarn develop
$ yarn copy-md-files && yarn variables && yarn program-outputs && yarn included-sources && yarn autodoc && yarn telemetry
$ node scripts/copy_md_files.js
Copying markdown files
$ node scripts/compile_variables.js
Computing docs variables and writing to ./docs/variables.json
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'rasa_sdk'
child_process.js:669
    throw err;
    ^

Error: Command failed: python -c "from rasa_sdk import __version__ as rasa_sdk_version; print(rasa_sdk_version)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'rasa_sdk'

    at checkExecSyncError (child_process.js:630:11)
    at execSync (child_process.js:666:15)
    at getRasaSdkVersion (/home/lmagic/development/rasa/docs/scripts/compile_variables.js:18:33)
    at writeVariablesFile (/home/lmagic/development/rasa/docs/scripts/compile_variables.js:24:25)
    at Object.<anonymous> (/home/lmagic/development/rasa/docs/scripts/compile_variables.js:33:1)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  status: 1,
  signal: null,
  output: [
    null,
    <Buffer >,
    <Buffer 54 72 61 63 65 62 61 63 6b 20 28 6d 6f 73 74 20 72 65 63 65 6e 74 20 63 61 6c 6c 20 6c 61 73 74 29 3a 0a 20 20 46 69 6c 65 20 22 3c 73 74 72 69 6e 67 ... 72 more bytes>
  ],
  pid: 72841,
  stdout: <Buffer >,
  stderr: <Buffer 54 72 61 63 65 62 61 63 6b 20 28 6d 6f 73 74 20 72 65 63 65 6e 74 20 63 61 6c 6c 20 6c 61 73 74 29 3a 0a 20 20 46 69 6c 65 20 22 3c 73 74 72 69 6e 67 ... 72 more bytes>
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Command or request that led to error**:
```
yarn start

```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @erohmensing will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by erohmensing** [comment]
Hi @lightmagic1, instead of using `yarn` and `yarn start`, can you try, as the [README](https://github.com/RasaHQ/rasa#running-and-changing-the-documentation) explains, to use 
```
make install install-docs
make livedocs
```
