### ISSUE TITLE
asyncio  - Task exception was never retrieved when using `rasa shell`

### ISSUE THREAD

**Issue by alwx** [RasaHQ/rasa#7828]
**Rasa version**: 2.x (tried to reproduce it with 2.2.7)

**Rasa SDK version** (if used & relevant): irrelevant

**Rasa X version** (if used & relevant): irrelevant

**Python version**: 3.6, 3.8

**Operating system** (windows, osx, ...): Ubuntu was used in this particular case. There are also reports that it's the same on Windows.

**Issue**: After training a model and running `rasa shell` some people are unable to communicate with the bot. For example, here is what was posted on forum: [https://forum.rasa.com/t/concert-bot-in-2-1x-problem-with-intents/37523](https://forum.rasa.com/t/concert-bot-in-2-1x-problem-with-intents/37523) I tried to reproduce this issue locally but failed — with Python 3.8 and Python 3.7 (on Mac OS) everything works just fine. Also seems like this user uses Tensorflow 2.3.2 which is a bit outdated but I tried installing it and also got no problems at all in this particular scenario. Some people also report that the issue can be solved by downgrading `questionary` — which makes me think that the fix is quite simple and the problem might be gone if we update `rasa/core/channels/console.py` to use `.ask_async()` (+ more async operations) instead of `ask()` in questionary calls, but I cannot validate it because I cannot reproduce this issue.

**More information** [https://forum.rasa.com/t/concert-bot-in-2-1x-problem-with-intents/37523](https://forum.rasa.com/t/concert-bot-in-2-1x-problem-with-intents/37523) [https://forum.rasa.com/t/error-asyncio-task-exception-was-never-retrieve/15511](https://forum.rasa.com/t/error-asyncio-task-exception-was-never-retrieve/15511) [https://forum.rasa.com/t/error-this-event-loop-is-already-running/24017](https://forum.rasa.com/t/error-this-event-loop-is-already-running/24017)

**Error (including full traceback)**: from [https://forum.rasa.com/t/error-asyncio-task-exception-was-never-retrieve/15511](https://forum.rasa.com/t/error-asyncio-task-exception-was-never-retrieve/15511)

 > ok let me see what I can find
 2019-09-11 11:53:44 ERROR asyncio - Task exception was never retrieved
 future: <Task finished coro=<configure_app.<locals>.run_cmdline_io() done, defined at /home/powerop/work/project/rasa-master/rasa/core/run.py:122> exception=TimeoutError()>
 Traceback (most recent call last):
 File "/home/powerop/work/project/rasa-master/rasa/core/run.py", line 126, in run_cmdline_io
 server_url=constants.DEFAULT_SERVER_FORMAT.format(port)
 File "/home/powerop/work/project/rasa-master/rasa/core/channels/console.py", line 137, in record_messages
 async for response in bot_responses:
 File "/home/powerop/.local/lib/python3.6/site-packages/async_generator/_impl.py", line 366, in step
 return await ANextIter(self._it, start_fn, *args)
 File "/home/powerop/.local/lib/python3.6/site-packages/async_generator/_impl.py", line 205, in throw
 return self._invoke(self._it.throw, type, value, traceback)
 File "/home/powerop/.local/lib/python3.6/site-packages/async_generator/_impl.py", line 209, in _invoke
 result = fn(*args)
 File "/home/powerop/work/project/rasa-master/rasa/core/channels/console.py", line 102, in send_message_receive_stream
 async for line in resp.content:
 File "/home/powerop/.local/lib/python3.6/site-packages/aiohttp/streams.py", line 40, in __anext__
 rv = await self.read_func()
 File "/home/powerop/.local/lib/python3.6/site-packages/aiohttp/streams.py", line 329, in readline
 await self._wait('readline')
 File "/home/powerop/.local/lib/python3.6/site-packages/aiohttp/streams.py", line 297, in _wait
 await waiter
 File "/home/powerop/.local/lib/python3.6/site-packages/aiohttp/helpers.py", line 585, in __exit__
 raise asyncio.TimeoutError from None
 concurrent.futures._base.TimeoutError
 2019-09-11 11:58:34 ERROR rasa.core.processor - Encountered an exception while running action 'action_search_restaurants'. Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
 2019-09-11 12:03:35 ERROR rasa.core.processor - Encountered an exception while running action 'action_suggest'. Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.

**Comment by r1cummings** [comment]
I am currently experiencing this issue. Has there been any updates?

**Comment by doguaraci** [comment]
Also having the same issue.

**Comment by nbala2k2** [comment]
Same here

**Comment by Ra0k** [comment]
Same here...

**Comment by JotFe** [comment]
Same here

**Comment by wirayuda23** [comment]
how to fix this tho.. i need this to work for my final project
