### ISSUE TITLE
UnicodeEncodeError: 'charmap' codec can't encode character '\u010d' 

### ISSUE THREAD

**Issue by vid9** [RasaHQ/rasa#7945]
**Rasa version**: 2.3.0

**Rasa SDK version** (if used & relevant):2.3.1

**Rasa X version** (if used & relevant): 0.35.1

**Python version**: 3.7.9

**Operating system** (windows, osx, ...): Windows 10

**Issue**:
I am using rasa to train a model in Slovene. This language includes letters (č, š, ž) that can cause problems with encodings. I am able to run rasa model using _rasa shell_, but _rasa x_ command is crashing.

I was able to run rasa x by adding ˝encoding="utf-8"˝ as a parameter for method _NamedTemporaryFile_ in _rasax\community\services\story_service.py", line 212._ 

Could you include this parameter by default so this doesn't have to be done after each update or fresh install of rasa, or do you suggest another solution for this problem?

**Error (including full traceback)**:
```
Traceback (most recent call last):
  File "\venv\lib\site-packages\rasax\community\services\story_service.py", line 212, in get_story_steps
    return StoryService._reader_read_from_string(reader, story_string)
  File "\venv\lib\site-packages\rasax\community\services\story_service.py", line 130, in _reader_read_from_string
    f.write(story_string)
  File "C:\Users\vc6478\AppData\Local\Programs\Python\Python37\lib\tempfile.py", line 481, in func_wrapper
    return func(*args, **kwargs)
  File "C:\Users\vc6478\AppData\Local\Programs\Python\Python37\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u010d' in position 1144: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "\venv\lib\site-packages\rasa\cli\x.py", line 500, in run_locally
    domain_path=domain_path,
  File "\venv\lib\site-packages\rasax\community\local.py", line 235, in main
    project_path, data_path, session, args.port, config_path, domain_path
  File "\venv\lib\site-packages\rasax\community\local.py", line 167, in _initialize_with_local_data
    domain_path=domain_path,
  File "C:\Users\vc6478\AppData\Local\Programs\Python\Python37\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "\venv\lib\site-packages\rasax\community\initialise.py", line 373, in inject_files_from_disk
    username,
  File "\venv\lib\site-packages\rasax\community\initialise.py", line 135, in inject_stories
    story_files, team, project_id, username
  File "\venv\lib\site-packages\rasax\community\services\story_service.py", line 553, in save_stories_from_files
    is_test=is_test,
  File "\venv\lib\site-packages\rasax\community\services\story_service.py", line 438, in save_stories
    story_string, filename, domain, is_test
  File "\venv\lib\site-packages\rasax\community\services\story_service.py", line 366, in _extract_stories_yaml
    story_string, data.FileFormat.YAML, domain, filename, test_stories=is_test
  File "\venv\lib\site-packages\rasax\community\services\story_service.py", line 216, in get_story_steps
    "'{}'\nError: {}".format(story_string, e)
rasa.shared.core.training_data.story_reader.story_reader.StoryParseError

```

**Command or request that led to error**:
```
rasa x
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @degiz will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by vid9** [comment]
This error can be fixed by forcing "utf-8" encoding in **\rasax\community\services\story_service.py**
 
Change the line 130 to:
`        with tempfile.NamedTemporaryFile(mode="w", delete=False, encoding="utf-8") as f:`
