### ISSUE TITLE
rasa train --augmentation 0 gives error

### ISSUE THREAD

**Issue by dnabanita7** [RasaHQ/rasa#7948]
**Rasa version**: 2.3.0

**Rasa SDK version** (if used & relevant): 2.3.1

**Rasa X version** (if used & relevant): None

**Python version**: 3.8.5

**Operating system** (windows, osx, ...): Linux-5.8.0-41-generic-x86_64-with-glibc2.10

**Issue**: couldn't understand the error. I have tried all stackoverflow answers. 

**Error (including full traceback)**:
```
Training NLU model...
Traceback (most recent call last):
  File "/home/nabanita07/anaconda3/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/home/nabanita07/anaconda3/lib/python3.8/site-packages/rasa/__main__.py", line 116, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/home/nabanita07/anaconda3/lib/python3.8/site-packages/rasa/cli/train.py", line 58, in <lambda>
    train_parser.set_defaults(func=lambda args: train(args, can_exit=True))
  File "/home/nabanita07/anaconda3/lib/python3.8/site-packages/rasa/cli/train.py", line 90, in train
    training_result = rasa.train(
  File "/home/nabanita07/anaconda3/lib/python3.8/site-packages/rasa/train.py", line 94, in train
    return rasa.utils.common.run_in_loop(
  File "/home/nabanita07/anaconda3/lib/python3.8/site-packages/rasa/utils/common.py", line 308, in run_in_loop
    result = loop.run_until_complete(f)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/home/nabanita07/anaconda3/lib/python3.8/site-packages/rasa/train.py", line 163, in train_async
    return await _train_async_internal(
  File "/home/nabanita07/anaconda3/lib/python3.8/site-packages/rasa/train.py", line 342, in _train_async_internal
    await _do_training(
  File "/home/nabanita07/anaconda3/lib/python3.8/site-packages/rasa/train.py", line 388, in _do_training
    model_path = await _train_nlu_with_validated_data(
  File "/home/nabanita07/anaconda3/lib/python3.8/site-packages/rasa/train.py", line 812, in _train_nlu_with_validated_data
    await rasa.nlu.train(
  File "/home/nabanita07/anaconda3/lib/python3.8/site-packages/rasa/nlu/train.py", line 97, in train
    trainer = Trainer(
  File "/home/nabanita07/anaconda3/lib/python3.8/site-packages/rasa/nlu/model.py", line 158, in __init__
    components.validate_requirements(cfg.component_names)
  File "/home/nabanita07/anaconda3/lib/python3.8/site-packages/rasa/nlu/components.py", line 57, in validate_requirements
    from rasa.nlu import registry
  File "/home/nabanita07/anaconda3/lib/python3.8/site-packages/rasa/nlu/registry.py", line 29, in <module>
    from rasa.nlu.featurizers.sparse_featurizer.count_vectors_featurizer import (
  File "/home/nabanita07/anaconda3/lib/python3.8/site-packages/rasa/nlu/featurizers/sparse_featurizer/count_vectors_featurizer.py", line 10, in <module>
    from sklearn.feature_extraction.text import CountVectorizer
  File "/home/nabanita07/anaconda3/lib/python3.8/site-packages/sklearn/feature_extraction/__init__.py", line 8, in <module>
    from ._hashing import FeatureHasher
ImportError: cannot import name 'FeatureHasher' from 'sklearn.feature_extraction._hashing' (/home/nabanita07/anaconda3/lib/python3.8/site-packages/sklearn/feature_extraction/_hashing.cpython-38-x86_64-linux-gnu.so)

```

**Command or request that led to error**:
```
rasa train --augmentation 0
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @desmarchris will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by desmarchris** [comment]
hey @dnabanita7 - can you post the output of `pip freeze` here? I just tried to reproduce this locally with your versions but it worked for me, so I'm thinking perhaps some of the dependencies are behind versions

**Comment by dnabanita7** [comment]
Hey!! Yes, I figured that and now its working fine. Thanks! Here is the trace of ``pip freeze``

```
(base) nabanita07@nabanita07:~$ pip freeze
absl-py==0.11.0
aio-pika==6.7.1
aiofiles==0.6.0
aiohttp==3.6.3
aioice==0.7.3
aiormq==3.3.1
aiortc==1.1.1
alabaster==0.7.12
algoliasearch==2.4.0
anaconda-client==1.7.2
anaconda-navigator==1.10.0
anaconda-project==0.8.3
appdirs==1.4.4
APScheduler==3.7.0
argh==0.26.2
argon2-cffi @ file:///tmp/build/80754af9/argon2-cffi_1596828493937/work
asn1crypto @ file:///tmp/build/80754af9/asn1crypto_1596577642040/work
astroid @ file:///tmp/build/80754af9/astroid_1592495912941/work
astropy==4.0.2
astunparse==1.6.3
async-generator==1.10
async-timeout==3.0.1
atomicwrites==1.4.0
attrs==20.3.0
Automat==20.2.0
autopep8 @ file:///tmp/build/80754af9/autopep8_1596578164842/work
av==8.0.3
Babel @ file:///tmp/build/80754af9/babel_1605108370292/work
backcall==0.2.0
backports.functools-lru-cache==1.6.1
backports.shutil-get-terminal-size==1.0.0
backports.tempfile==1.0
backports.weakref==1.0.post1
beautifulsoup4==4.6.3
bidict==0.21.2
bitarray @ file:///tmp/build/80754af9/bitarray_1605065113847/work
bkcharts==0.2
bleach==3.2.3
blis @ file:///home/conda/feedstock_root/build_artifacts/cython-blis_1606130919153/work
bokeh @ file:///tmp/build/80754af9/bokeh_1603297833684/work
boto==2.49.0
boto3==1.17.6
botocore==1.20.6
Bottleneck==1.3.2
brotlipy==0.7.0
cachetools==4.2.1
catalogue @ file:///home/conda/feedstock_root/build_artifacts/catalogue_1610454478459/work
certifi==2020.12.5
cffi==1.14.5
chardet==3.0.4
click==7.1.2
cloudpickle==0.6.1
clyent==1.2.2
colorama @ file:///tmp/build/80754af9/colorama_1603211150991/work
colorclass==2.2.0
coloredlogs==10.0
colorhash==1.0.3
conda==4.9.2
conda-build==3.20.5
conda-package-handling @ file:///tmp/build/80754af9/conda-package-handling_1603018141399/work
conda-verify==3.4.2
constantly==15.1.0
contextlib2==0.6.0.post1
crc32c==2.2
cryptography==3.4.4
cycler==0.10.0
cymem @ file:///home/conda/feedstock_root/build_artifacts/cymem_1604919356432/work
Cython @ file:///tmp/build/80754af9/cython_1594831566883/work
cytoolz==0.11.0
dask @ file:///tmp/build/80754af9/dask-core_1602083700509/work
dataclasses==0.6
decorator==4.4.2
defusedxml==0.6.0
diff-match-patch @ file:///tmp/build/80754af9/diff-match-patch_1594828741838/work
distlib==0.3.1
distributed @ file:///tmp/build/80754af9/distributed_1605066520644/work
dm-tree==0.1.5
dnspython==1.16.0
docopt==0.6.2
docutils==0.16
dpcontracts==0.6.0
e==1.4.5
en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.3.1/en_core_web_sm-2.3.1.tar.gz
entrypoints==0.3
et-xmlfile==1.0.1
fastcache==1.1.0
fbmessenger==6.0.0
filelock==3.0.12
flake8 @ file:///tmp/build/80754af9/flake8_1601911421857/work
Flask==1.1.2
forbiddenfruit==0.1.4
fsspec @ file:///tmp/build/80754af9/fsspec_1602684995936/work
future==0.17.1
gast==0.4.0
geographiclib==1.50
geopy==1.18.1
gevent==1.5.0
glob2==0.7
gmpy2==2.0.8
google-auth==1.26.1
google-auth-oauthlib==0.4.2
google-pasta==0.2.0
greenlet @ file:///tmp/build/80754af9/greenlet_1600874013538/work
grpcio==1.35.0
gspread==3.0.1
h11==0.9.0
h5py==2.10.0
HeapDict==1.0.1
helpdev==0.7.1
html5lib @ file:///tmp/build/80754af9/html5lib_1593446221756/work
httpcore==0.11.1
httplib2==0.19.0
httptools==0.1.1
httpx==0.15.4
humanfriendly==9.1
hyperlink==21.0.0
idna @ file:///tmp/build/80754af9/idna_1593446292537/work
imageio @ file:///tmp/build/80754af9/imageio_1594161405741/work
imagesize==1.2.0
importlib-metadata @ file:///tmp/build/80754af9/importlib-metadata_1602276842396/work
incremental==17.5.0
iniconfig @ file:///tmp/build/80754af9/iniconfig_1602780191262/work
intervaltree @ file:///tmp/build/80754af9/intervaltree_1598376443606/work
ipykernel @ file:///tmp/build/80754af9/ipykernel_1596207638929/work/dist/ipykernel-5.3.4-py3-none-any.whl
ipython @ file:///tmp/build/80754af9/ipython_1604101197014/work
ipython-genutils==0.2.0
ipywidgets @ file:///tmp/build/80754af9/ipywidgets_1601490159889/work
isort @ file:///tmp/build/80754af9/isort_1602603989581/work
itsdangerous==1.1.0
jdcal==1.4.1
jedi @ file:///tmp/build/80754af9/jedi_1592841866100/work
jeepney @ file:///tmp/build/80754af9/jeepney_1605069705079/work
Jinja2==2.11.2
jmespath==0.10.0
joblib==0.15.1
json5==0.9.5
jsonpickle==1.5.2
jsonschema @ file:///tmp/build/80754af9/jsonschema_1602607155483/work
jupyter==1.0.0
jupyter-client==6.1.11
jupyter-console @ file:///tmp/build/80754af9/jupyter_console_1598884538475/work
jupyter-core==4.7.0
jupyterlab==2.2.6
jupyterlab-pygments==0.1.2
jupyterlab-server @ file:///tmp/build/80754af9/jupyterlab_server_1594164409481/work
kafka-python==2.0.2
Keras-Preprocessing==1.1.2
keyring @ file:///tmp/build/80754af9/keyring_1601490835422/work
kiwisolver==1.3.1
klein==17.10.0
lazy-object-proxy==1.4.3
libarchive-c==2.9
llvmlite==0.34.0
locket==0.2.0
loguru==0.5.3
lxml @ file:///tmp/build/80754af9/lxml_1603216285000/work
mailchimp3==3.0.14
Markdown==3.3.3
MarkupSafe==1.1.1
matplotlib @ file:///tmp/build/80754af9/matplotlib-base_1603378225747/work
mattermostwrapper==2.2
mccabe==0.6.1
mistune==0.8.4
mkl-fft==1.2.0
mkl-random==1.1.1
mkl-service==2.3.0
mock==4.0.2
more-itertools @ file:///tmp/build/80754af9/more-itertools_1605111547926/work
mpmath==1.1.0
msgpack==1.0.0
multidict==4.7.6
multipledispatch==0.6.0
murmurhash==1.0.4
navigator-updater==0.2.1
nbclient==0.5.1
nbconvert==6.0.7
nbformat==5.1.2
nest-asyncio==1.5.1
netifaces==0.10.9
networkx @ file:///tmp/build/80754af9/networkx_1598376031484/work
nltk @ file:///tmp/build/80754af9/nltk_1592496090529/work
nose==1.3.7
notebook @ file:///tmp/build/80754af9/notebook_1601501575118/work
numba @ file:///tmp/build/80754af9/numba_1600100669015/work
numexpr==2.7.1
numpy==1.16.6
numpydoc @ file:///tmp/build/80754af9/numpydoc_1605117425582/work
oauth2client==4.1.3
oauthlib==3.1.0
olefile==0.46
openpyxl @ file:///tmp/build/80754af9/openpyxl_1598113097404/work
opt-einsum==3.3.0
packaging==20.4
pamqp==2.3.0
pandas==0.24.2
pandocfilters==1.4.3
parso==0.7.0
partd==1.1.0
path @ file:///tmp/build/80754af9/path_1598376507494/work
pathlib2==2.3.5
pathtools==0.1.2
patsy==0.5.1
pbr==5.5.1
pep8==1.7.1
pexpect==4.8.0
pickleshare==0.7.5
Pillow==8.1.0
pkginfo==1.6.1
plac==0.9.6
pluggy==0.13.1
ply==3.11
preshed @ file:///home/conda/feedstock_root/build_artifacts/preshed_1605166129992/work
prometheus-client==0.8.0
prompt-toolkit==2.0.10
protobuf==3.14.0
psutil @ file:///tmp/build/80754af9/psutil_1598370257551/work
psycopg2-binary==2.8.6
ptyprocess==0.6.0
py @ file:///tmp/build/80754af9/py_1593446248552/work
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycodestyle==2.6.0
pycosat==0.6.3
pycparser @ file:///tmp/build/80754af9/pycparser_1594388511720/work
pycurl==7.43.0.6
pydocstyle @ file:///tmp/build/80754af9/pydocstyle_1598885001695/work
pydot==1.4.1
pyee==8.1.0
pyflakes==2.2.0
Pygments==2.7.4
PyHamcrest==2.0.2
PyJWT==2.0.1
pykwalify==1.8.0
pylibsrtp==0.6.7
pylint @ file:///tmp/build/80754af9/pylint_1598623985952/work
pymongo==3.10.1
PyNaCl==1.4.0
pyodbc===4.0.0-unsupported
pyOpenSSL @ file:///tmp/build/80754af9/pyopenssl_1594392929924/work
pyparsing==2.4.7
PyQt5==5.12
PyQt5-sip==4.19.19
PyQtWebEngine==5.12
pyrsistent==0.17.3
PySocks==1.7.1
pyTelegramBotAPI==3.7.6
pytest==0.0.0
python-crfsuite==0.9.7
python-dateutil==2.8.1
python-engineio==3.13.2
python-jsonrpc-server @ file:///tmp/build/80754af9/python-jsonrpc-server_1600278539111/work
python-language-server @ file:///tmp/build/80754af9/python-language-server_1600454544709/work
python-socketio==5.0.4
pytz==2020.5
PyWavelets @ file:///tmp/build/80754af9/pywavelets_1601658317819/work
pyxdg @ file:///tmp/build/80754af9/pyxdg_1603822279816/work
PyYAML==5.4.1
pyzmq==22.0.0
QDarkStyle==2.8.1
QtAwesome @ file:///tmp/build/80754af9/qtawesome_1602272867890/work
qtconsole @ file:///tmp/build/80754af9/qtconsole_1600870028330/work
QtPy==1.9.0
questionary==1.5.2
rasa==2.2.10
-e git+https://github.com/RasaHQ/rasa-demo.git@bc6c7c8adced3339b53af7e72c54fd1e02819cc4#egg=rasa_demo
rasa-nlu==0.15.1
rasa-sdk==2.2.0
redis==3.5.3
regex==2020.9.27
requests @ file:///tmp/build/80754af9/requests_1592841827918/work
requests-oauthlib==1.3.0
requests-toolbelt==0.9.1
rfc3986==1.4.0
rocketchat-API==1.9.1
rope @ file:///tmp/build/80754af9/rope_1602264064449/work
rsa==4.7
Rtree==0.9.4
ruamel-yaml==0.15.87
ruamel.yaml.clib==0.2.2
s3transfer==0.3.4
sanic==20.12.1
Sanic-Cors==0.10.0.post3
sanic-jwt==1.6.0
Sanic-Plugins-Framework==0.9.5
scikit-image==0.17.2
scikit-learn @ file:///tmp/build/80754af9/scikit-learn_1598376899566/work
scipy==1.6.0
seaborn @ file:///tmp/build/80754af9/seaborn_1600553570093/work
SecretStorage==3.1.2
Send2Trash==1.5.0
sentry-sdk==0.19.5
simplegeneric==0.8.1
simplejson==3.17.2
singledispatch @ file:///tmp/build/80754af9/singledispatch_1602523705405/work
sip==4.19.13
six @ file:///tmp/build/80754af9/six_1605205327372/work
sklearn-crfsuite==0.3.6
slackclient==2.9.3
sniffio==1.2.0
snowballstemmer==2.0.0
sortedcollections==1.2.1
sortedcontainers==2.2.2
soupsieve==2.0.1
spacy @ file:///home/conda/feedstock_root/build_artifacts/spacy_1606374753274/work
Sphinx @ file:///tmp/build/80754af9/sphinx_1597428793432/work
sphinxcontrib-applehelp==1.0.2
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==1.0.3
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.4
sphinxcontrib-websupport @ file:///tmp/build/80754af9/sphinxcontrib-websupport_1597081412696/work
spyder @ file:///tmp/build/80754af9/spyder_1599056981321/work
spyder-kernels @ file:///tmp/build/80754af9/spyder-kernels_1599056754858/work
SQLAlchemy==1.3.23
sqlitedict==1.7.0
srsly @ file:///home/conda/feedstock_root/build_artifacts/srsly_1605085673973/work
statsmodels @ file:///tmp/build/80754af9/statsmodels_1602280205159/work
stevedore==3.3.0
syft==0.3.0
sympy @ file:///tmp/build/80754af9/sympy_1605119542615/work
tables==3.6.1
tabulate==0.8.7
tblib @ file:///tmp/build/80754af9/tblib_1597928476713/work
tensorboard==2.4.1
tensorboard-plugin-wit==1.8.0
tensorflow==2.3.2
tensorflow-addons==0.12.0
tensorflow-estimator==2.3.0
tensorflow-hub==0.10.0
tensorflow-probability==0.11.1
tensorflow-text==2.3.0
termcolor==1.1.0
terminado==0.9.1
terminaltables==3.1.0
testpath==0.4.4
thinc @ file:///home/conda/feedstock_root/build_artifacts/thinc_1606141555073/work
threadpoolctl @ file:///tmp/tmp9twdgx9k/threadpoolctl-2.1.0-py3-none-any.whl
tifffile==2020.10.1
toml @ file:///tmp/build/80754af9/toml_1592853716807/work
toolz @ file:///tmp/build/80754af9/toolz_1601054250827/work
torch==1.7.1
torchvision==0.8.2
tornado==6.1
tqdm==4.56.2
traitlets==5.0.5
twilio==6.50.1
Twisted==20.3.0
typeguard==2.10.0
typing==3.6.1
typing-extensions @ file:///tmp/build/80754af9/typing_extensions_1598376058250/work
tzlocal==2.1
ujson==4.0.2
unicodecsv==0.14.1
urllib3 @ file:///tmp/build/80754af9/urllib3_1603305693037/work
uvloop==0.15.0
virtualenv==20.4.2
virtualenv-clone==0.5.4
virtualenvwrapper==4.8.4
wasabi @ file:///home/conda/feedstock_root/build_artifacts/wasabi_1612156086016/work
watchdog @ file:///tmp/build/80754af9/watchdog_1593447344699/work
wcwidth @ file:///tmp/build/80754af9/wcwidth_1593447189090/work
webencodings==0.5.1
webexteamssdk==1.6
websockets==8.1
Werkzeug==1.0.1
widgetsnbextension==3.5.1
wrapt==1.12.1
wurlitzer @ file:///tmp/build/80754af9/wurlitzer_1594753850195/work
xlrd==1.2.0
XlsxWriter @ file:///tmp/build/80754af9/xlsxwriter_1602692860603/work
xlwt==1.3.0
xmltodict==0.12.0
yapf @ file:///tmp/build/80754af9/yapf_1593528177422/work
yarl==1.6.3
zict==2.0.0
zipp @ file:///tmp/build/80754af9/zipp_1604001098328/work
zope.event==4.5.0
zope.interface @ file:///tmp/build/80754af9/zope.interface_1602002420968/work
```
