### ISSUE TITLE
Rasa Core Training Fails when using Convert and E2E Training

### ISSUE THREAD

**Issue by 0roboros** [RasaHQ/rasa#7991]
**Rasa version**: 2.3.0

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**: 3.7.3

**Operating system** (windows, osx, ...): linux

**Issue**:

When training for end-to-end learning using ConvertTokenizer and ConvertFeaturizer, rasa core is unable to train. Changing ConvertTokenizer to WhitespaceTokenizer and ConvertFeaturizer to CountTokenFeaturizer, rasa core is able to train again (while keeping all other settings).

**Error (including full traceback)**:

Training Core model... /home/jamesjiang/.local/lib/python3.7/site-packages/rasa/shared/utils/io.py:93: UserWarning: Neither 'RulePolicy' nor 'MappingPolicy' (deprecated) are included in the model's policy configuration. Default intents such as 'rest art' and 'back' will not trigger actions 'action_restart' and 'action_back'. More info at [https://rasa.com/docs/rasa/default-actions](https://rasa.com/docs/rasa/default-actions) Processed story blocks: 100%|██████████████████████████████████████| 3/3 [00:00<00:00, 2839.75it/s, # trackers=1](#trackers=1) Processed story blocks: 100%|██████████████████████████████████████| 3/3 [00:00<00:00, 1452.66it/s, # trackers=3](#trackers=3) Processed story blocks: 100%|██████████████████████████████████████| 3/3 [00:00<00:00, 1217.98it/s, # trackers=3](#trackers=3) Processed story blocks: 100%|███████████████████████████████████████| 3/3 [00:00<00:00, 883.76it/s, # trackers=3](#trackers=3) Processed trackers: 100%|█████████████████████████████████████████| 42/42 [00:00<00:00, 729.81it/s, # actions=55](#actions=55) Traceback (most recent call last): File "/home/jamesjiang/.local/bin/rasa", line 8, in sys.exit(main()) File "/home/jamesjiang/.local/lib/python3.7/site-packages/rasa/**main**.py", line 116, in main cmdline_arguments.func(cmdline_arguments) File "/home/jamesjiang/.local/lib/python3.7/site-packages/rasa/cli/train.py", line 58, in train_parser.set_defaults(func=lambda args: train(args, can_exit=True)) File "/home/jamesjiang/.local/lib/python3.7/site-packages/rasa/cli/train.py", line 102, in train finetuning_epoch_fraction=args.epoch_fraction, File "/home/jamesjiang/.local/lib/python3.7/site-packages/rasa/train.py", line 109, in train loop, File "/home/jamesjiang/.local/lib/python3.7/site-packages/rasa/utils/common.py", line 308, in run_in_loop result = loop.run_until_complete(f) File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete File "/home/jamesjiang/.local/lib/python3.7/site-packages/rasa/train.py", line 174, in train_async finetuning_epoch_fraction=finetuning_epoch_fraction, File "/home/jamesjiang/.local/lib/python3.7/site-packages/rasa/train.py", line 353, in _train_async_internal finetuning_epoch_fraction=finetuning_epoch_fraction, File "/home/jamesjiang/.local/lib/python3.7/site-packages/rasa/train.py", line 415, in _do_training

**Command or request that led to error**:

rasa train

**Content of configuration file (config.yml)** (if relevant):

<pre>language: en
 pipeline:

*   name: ConveRTTokenizer

1\. model_url: "https://github.com/connorbrinton/polyai-models/releases/download/v1.0/model.tar.gz" 

*   name: WhitespaceTokenizer
     #intent_tokenization_flag: True
     #intent_split_symbol: "+"

*   name: ConveRTFeaturizer
     model_url: "https://github.com/connorbrinton/polyai-models/releases/download/v1.0/model.tar.gz"
*   name: RegexFeaturizer
*   name: LexicalSyntacticFeaturizer
*   name: CountVectorsFeaturizer
*   name: CountVectorsFeaturizer
     analyzer: char_wb
     min_ngram: 1
     max_ngram: 4
*   name: CountVectorsFeaturizer

1\. analyzer: "char_wb"
 2\. min_ngram: 1
 3\. max_ngram: 5

*   name: DIETClassifier
     #use_masked_language_model: True
     epochs: 400
     #entity_recognition: false
     #intent_recognition: true
     dense_dimension:
     text: 512
     label: 20
     weight_sparsity: 0
     number_of_transformer_layers: 4
     embedding_dimension: 30
     constrain_similarities: true
     model_confidence: cosine

*   name: MemoizationPolicy
*   name: TEDPolicy
     max_history: 5
     epochs: 100
     constrain_similarities: true
     model_confidence: cosine

</pre>

**Content of domain file (domain.yml)** (if relevant):

<pre>version: "2.0"

responses:
 utter_greet:

*   text: "Hey! How are you?"
     utter_cheer_up:
*   text: "Here is something to cheer you up:"
     image: "https://i.imgur.com/nGF1K8f.jpg"
     utter_did_that_help:
*   text: "Did that help you?"
     utter_happy:
*   text: "Great, carry on!"
     utter_goodbye:
*   text: "Bye"
     utter_iamabot:
*   text: "I am a bot, powered by Rasa."
     session_config:
     session_expiration_time: 60
     carry_over_slots_to_new_session: true
     </pre>

**Comment by sara-tagger** [comment]
Thanks for the issue, @yennycheung will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by TyDunn** [comment]
@Ghostvv Are you aware of this? Any thoughts?

**Comment by Ghostvv** [comment]
@TyDunn I didn't know, looks like a bug

**Comment by 0roboros** [comment]
@Ghostvv @yennycheung @TyDunn Any thoughts/updates on this? Seems like a really critical bug as its not even able to train, and is keeping us from using the new end-to-end features.

**Comment by twerkmeister** [comment]
Hey @0roboros! Thanks for reporting this issue. Would you mind sharing the training data or part of it as well? Asking as your domain yaml seems like just a test project and it would make replicating the issue easier.

**Comment by twerkmeister** [comment]
Also @0roboros, it seems to me the stack trace isn't complete. The specific error message is missing - maybe you just copied one console window worth of stack trace?
