### ISSUE TITLE
rasa test breaks when failed test story contains retrieval intent without user text

### ISSUE THREAD

**Issue by samsucik** [RasaHQ/rasa#8097]
**Rasa version**: 2.3.4 (`main`)

**Python version**: 3.8.5

**Operating system** (windows, osx, ...): osx

**Issue**: `rasa test` breaks while creating the failed stories file. This happens when a failed test story (a story on which the current model made some mistakes) contains a user turn with only `intent` information and no `user` info. Additionally, it only happens when that one intent is a retrieval intent. See a minimalistic example below.

From what I've discovered so far, the error happens because user text is `None` but `re` tries to find entities in it.

If it's the case that we require user text to be present everywhere in test stories, we should make it explicit and throw a more meaningful error. If we don't require user text everywhere (which is the option that makes more sense to me), then we need to fix this bug somehow.

**Error (including full traceback)**:

Traceback (most recent call last): File "/Users/sams/.miniconda/envs/rasa1/bin/rasa", line 5, in main() File "/Users/sams/rasa1/rasa/**main**.py", line 116, in main cmdline_arguments.func(cmdline_arguments) File "/Users/sams/rasa1/rasa/cli/test.py", line 222, in test run_core_test(args) File "/Users/sams/rasa1/rasa/cli/test.py", line 104, in run_core_test test_core( File "/Users/sams/rasa1/rasa/test.py", line 157, in test_core rasa.utils.common.run_in_loop(test(stories, _agent, out_directory=output, **kwargs)) File "/Users/sams/rasa1/rasa/utils/common.py", line 308, in run_in_loop result = loop.run_until_complete(f) File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete File "/Users/sams/rasa1/rasa/core/test.py", line 832, in test _log_stories( File "/Users/sams/rasa1/rasa/core/test.py", line 748, in _log_stories f.write(YAMLStoryWriter().dumps(steps)) File "/Users/sams/rasa1/rasa/shared/core/training_data/story_writer/yaml_story_writer.py", line 73, in dumps self.dump(stream, story_steps, is_appendable, is_test_story) File "/Users/sams/rasa1/rasa/shared/core/training_data/story_writer/yaml_story_writer.py", line 94, in dump result = self.stories_to_yaml(story_steps, is_test_story) File "/Users/sams/rasa1/rasa/shared/core/training_data/story_writer/yaml_story_writer.py", line 119, in stories_to_yaml stories.append(self.process_story_step(story_step)) File "/Users/sams/rasa1/rasa/shared/core/training_data/story_writer/yaml_story_writer.py", line 149, in process_story_step processed = self.process_event(event) File "/Users/sams/rasa1/rasa/shared/core/training_data/story_writer/yaml_story_writer.py", line 163, in process_event return self.process_user_utterance(event, self._is_test_story) File "/Users/sams/rasa1/rasa/shared/core/training_data/story_writer/yaml_story_writer.py", line 210, in process_user_utterance user_utterance.inline_comment(), KEY_USER_INTENT File "/Users/sams/rasa1/rasa/core/test.py", line 314, in inline_comment predicted_message = format_message( File "/Users/sams/rasa1/rasa/shared/core/events.py", line 96, in format_message message_from_md = entities_parser.parse_training_example(text, intent) File "/Users/sams/rasa1/rasa/shared/nlu/training_data/entities_parser.py", line 174, in parse_training_example entities = find_entities_in_training_example(example) File "/Users/sams/rasa1/rasa/shared/nlu/training_data/entities_parser.py", line 52, in find_entities_in_training_example for match in re.finditer(ENTITY_REGEX, example): File "/Users/sams/.miniconda/envs/rasa1/lib/python3.8/re.py", line 248, in finditer return _compile(pattern, flags).finditer(string) TypeError: expected string or bytes-like object

**Command or request that led to error**:

rasa test

**Content of configuration file (config.yml)** (if relevant):

<pre>language: en
 pipeline:

*   name: WhitespaceTokenizer
*   name: CountVectorsFeaturizer
*   name: CountVectorsFeaturizer
     analyzer: char_wb
     min_ngram: 1
     max_ngram: 4
*   name: DIETClassifier
     epochs: 100
*   name: ResponseSelector
     epochs: 100
     policies:
*   name: RulePolicy</pre>

**Content of domain file (domain.yml)** (if relevant):

<pre>version: "2.0"
 intents:

*   greet
*   goodbye
     responses:
     utter_greet:
*   text: "Hey! How are you?"
     utter_goodbye:
*   text: "Bye"</pre>

**Training data**:

<pre>version: "2.0"
 nlu:

*   intent: greet
     examples: |
*   hey
*   hello
*   intent: goodbye/formal
     examples: |
*   good afternoon
*   goodbye
*   intent: goodbye/informal
     examples: |
*   cu
*   bye
     rules:
*   rule:
     steps:
*   intent: goodbye
*   action: utter_goodbye </pre>

**Test story:**

<pre>stories:

*   story:
     steps:
*   intent: goodbye/formal
*   action: utter_goodbye</pre>

**Comment by tolgayayci** [comment]
I think there is a problem with retrieval intent logic, you shouldn't use in way of goodbye/formal (goodbye is correct form) in stories and need to add action for response like (response_goodbye), ResponseSelector selects the correct intent and answer for you. (I can't see seperate answer file for relevant intents, you need to create that also) . 

These are some problems from my perception, retrieval intent is hard to understand, you need to be sure you've applied all steps at the link.

[Rasa Blog - Response Retrieval Models](https://blog.rasa.com/response-retrieval-models/)
