### ISSUE TITLE
Error in actions while running on server

### ISSUE THREAD

**Issue by annaakhil** [RasaHQ/rasa#8101]
**Rasa version**:2.1.0

**Rasa SDK version** (if used & relevant):2.3.1

**Rasa X version** (if used & relevant):

**Python version**:3.8.5

**Operating system** (windows, osx, linux):

**Issue**:
i am getting an error on actions while running on cloud server. but when i am running on locally its working prefect. may i know the reason

**Error (including full traceback)**:
```
2021-03-03 15:35:43 INFO     rasa_sdk.endpoint  - Starting action endpoint server...
2021-03-03 15:35:43 INFO     rasa_sdk.executor  - Registered function for 'action_basicinfo'.
2021-03-03 15:35:43 INFO     rasa_sdk.endpoint  - Action endpoint is up and running on http://localhost:5055
/home/akhila/nrasa/lib/python3.8/site-packages/rasa_sdk/utils.py:193: UserWarning: Your versions of rasa and rasa_sdk might not be compatible. You are currently running rasa version 2.1.0 and rasa
_sdk version 2.3.1.
To ensure compatibility use the same version for both, modulo the last number, i.e. using version A.B.x the numbers A and B should be identical for both rasa and rasa_sdk.
  warnings.warn(
search_text:: types of H-1b classification
Exception occurred while handling uri: 'http://localhost:5055/webhook'
Traceback (most recent call last):
  File "/home/akhila/nrasa/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/akhila/nrasa/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/akhila/nrasa/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/akhila/nrasa/lib/python3.8/site-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/home/akhila/nrasa/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 428, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/akhila/nrasa/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/akhila/nrasa/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/home/akhila/nrasa/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/home/akhila/nrasa/lib/python3.8/site-packages/urllib3/util/retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
File "/home/akhila/nrasa/lib/python3.8/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/home/akhila/nrasa/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/home/akhila/nrasa/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/home/akhila/nrasa/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/home/akhila/nrasa/lib/python3.8/site-packages/urllib3/connection.py", line 411, in connect
    self.sock = ssl_wrap_socket(
  File "/home/akhila/nrasa/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 428, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/home/akhila/nrasa/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 472, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', OSError(0, 'Error'))
During handling of the above exception, another exception occurred:



```

**Command or request that led to error**:
```
when rasa trying to run actions.py
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by kaustuk** [comment]
>/home/akhila/nrasa/lib/python3.8/site-packages/rasa_sdk/utils.py:193: UserWarning: Your versions of rasa and rasa_sdk might not be compatible. You are currently running rasa version 2.1.0 and rasa
_sdk version 2.3.1.
To ensure compatibility use the same version for both, modulo the last number, i.e. using version A.B.x the numbers A and B should be identical for both rasa and rasa_sdk.

Hi @annaakhil, As you can see in logs the issue here is there is mismatch in Rasa version and Rasa SDK version.

**Solution**:

1. Can you try decreasing rasa-sdk version to 2.1.x. Latest version of rasa-sdk with `2.1.x` is `2.1.2`. You can install it via `pip3 install rasa-sdk==2.1.2` . 
2. Another solution is you increase you rasa version to `2.3.x`.  Latest version of rasa with `2.3.x` is `2.3.4`. You  can install it via `pip3 install rasa==2.3.4`


I would prefer first solution. since rasa 2.3.x have many new NLU feature which required to revisit your bot config and all.

**Comment by sara-tagger** [comment]
Thanks for the issue, @degiz will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by degiz** [comment]
Hey @annaakhil 

That doesn't look like a bug, we usually encourage to use forum for the questions.
What's the current status with the issue now?

**Comment by TyDunn** [comment]
If you still have questions, please ask the Rasa forum
