### ISSUE TITLE
Telegram receive message has no text Exception

### ISSUE THREAD

**Issue by mingchi21** [RasaHQ/rasa#8166]
**Rasa version**: 2.3.1

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**: 3.8

**Operating system** (windows, osx, ...): Ubuntu

**Issue**: Telegram receive message Exception. It seems like some telegram update has no message attribute.

**Error (including full traceback)**:

Traceback (most recent call last): File "/opt/venv/lib/python3.8/site-packages/sanic/app.py", line 973, in handle_request response = await response File "/opt/venv/lib/python3.8/site-packages/rasa/core/channels/telegram.py", line 218, in message if self._is_user_message(msg): File "/opt/venv/lib/python3.8/site-packages/rasa/core/channels/telegram.py", line 177, in _is_user_message return message.text is not None AttributeError: 'NoneType' object has no attribute 'text'

In File "/opt/venv/lib/python3.8/site-packages/rasa/core/channels/telegram.py",

if self._is_button(update): msg = update.callback_query.message text = update.callback_query.data else: msg = update.message

 _In some case the msg could be None, in this case there will trigger the exception_ 

**Command or request that led to error**:

When receive the some message from telegram.

**Content of configuration file (config.yml)** (if relevant):

**Content of domain file (domain.yml)** (if relevant):

**Comment by sara-tagger** [comment]
Thanks for the issue, @amn41 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗
