### ISSUE TITLE
NLU Training fails with --persist-nlu-data enabled

### ISSUE THREAD

**Issue by ortsaCniveK** [RasaHQ/rasa#8227]
**Rasa version**: 2.4.0

**Rasa SDK version** (if used & relevant): 2.4.0

**Rasa X version** (if used & relevant): N/A

**Python version**: I believe it was Python 3.6, I was using the `tensorflow/tensorflow:2.3.2-gpu` image to run the training

**Operating system** (windows, osx, ...): Linux

**Issue**:
Running a training with --persist-nlu-data prevents NLU training from completing successfully.  Running training without this parameter works fine.  Additionally, no NLU training data validation errors for entities appear when running `rasa data validate`.

**Error (including full traceback)**:
```
Traceback (most recent call last):
  File "/usr/local/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/rasa/__main__.py", line 116, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/usr/local/lib/python3.6/dist-packages/rasa/cli/train.py", line 58, in <lambda>
    train_parser.set_defaults(func=lambda args: train(args, can_exit=True))
  File "/usr/local/lib/python3.6/dist-packages/rasa/cli/train.py", line 102, in train
    finetuning_epoch_fraction=args.epoch_fraction,
  File "/usr/local/lib/python3.6/dist-packages/rasa/train.py", line 109, in train
    loop,
  File "/usr/local/lib/python3.6/dist-packages/rasa/utils/common.py", line 307, in run_in_loop
    result = loop.run_until_complete(f)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.6/dist-packages/rasa/train.py", line 174, in train_async
    finetuning_epoch_fraction=finetuning_epoch_fraction,
  File "/usr/local/lib/python3.6/dist-packages/rasa/train.py", line 353, in _train_async_internal
    finetuning_epoch_fraction=finetuning_epoch_fraction,
  File "/usr/local/lib/python3.6/dist-packages/rasa/train.py", line 396, in _do_training
    finetuning_epoch_fraction=finetuning_epoch_fraction,
  File "/usr/local/lib/python3.6/dist-packages/rasa/train.py", line 819, in _train_nlu_with_validated_data
    **additional_arguments,
  File "/usr/local/lib/python3.6/dist-packages/rasa/nlu/train.py", line 119, in train
    path, persistor, fixed_model_name, persist_nlu_training_data
  File "/usr/local/lib/python3.6/dist-packages/rasa/nlu/model.py", line 245, in persist
    metadata.update(self.training_data.persist(dir_name))
  File "/usr/local/lib/python3.6/dist-packages/rasa/shared/nlu/training_data/training_data.py", line 453, in persist
    self.persist_nlu(nlu_data_file)
  File "/usr/local/lib/python3.6/dist-packages/rasa/shared/nlu/training_data/training_data.py", line 405, in persist_nlu
    rasa.shared.utils.io.write_text_file(self.nlu_as_yaml(), filename)
  File "/usr/local/lib/python3.6/dist-packages/rasa/shared/nlu/training_data/training_data.py", line 397, in nlu_as_yaml
    return RasaYAMLWriter().dumps(no_responses_training_data)
  File "/usr/local/lib/python3.6/dist-packages/rasa/shared/nlu/training_data/formats/rasa_yaml.py", line 365, in dumps
    self.dump(stream, training_data)
  File "/usr/local/lib/python3.6/dist-packages/rasa/shared/nlu/training_data/formats/rasa_yaml.py", line 377, in dump
    result = self.training_data_to_dict(training_data)
  File "/usr/local/lib/python3.6/dist-packages/rasa/shared/nlu/training_data/formats/rasa_yaml.py", line 399, in training_data_to_dict
    nlu_items.extend(cls.process_intents(training_data))
  File "/usr/local/lib/python3.6/dist-packages/rasa/shared/nlu/training_data/formats/rasa_yaml.py", line 429, in process_intents
    TrainingDataWriter.generate_message,
  File "/usr/local/lib/python3.6/dist-packages/rasa/shared/nlu/training_data/formats/rasa_yaml.py", line 480, in process_training_examples_by_key
    examples, example_extraction_predicate
  File "/usr/local/lib/python3.6/dist-packages/rasa/shared/nlu/training_data/formats/rasa_yaml.py", line 519, in _convert_training_examples
    KEY_INTENT_TEXT: example_extraction_predicate(example).strip(
  File "/usr/local/lib/python3.6/dist-packages/rasa/shared/nlu/training_data/formats/readerwriter.py", line 88, in generate_message
    entities = sorted(message.get("entities", []), key=lambda k: k["start"])
  File "/usr/local/lib/python3.6/dist-packages/rasa/shared/nlu/training_data/formats/readerwriter.py", line 88, in <lambda>
    entities = sorted(message.get("entities", []), key=lambda k: k["start"])
KeyError: 'start'
```

**Command or request that led to error**:
```
rasa venus-train train --augmentation 30 --persist-nlu-data -vv
```

**Content of configuration file (config.yml)** (if relevant):
```yml
N/A
```

**Content of domain file (domain.yml)** (if relevant):
```yml
N/A
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @samsucik will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by samsucik** [comment]
Hi @ortsaCniveK, can you provide the concrete domain and config files (+ in this case also some NLU data) that led to this error? These are definitely relevant, not `N/A` 😉   It's hard to reproduce the bug unless we know the setup that led to it.

Additionally, what's the `venus-train` in the training command? 🤔

**Comment by ortsaCniveK** [comment]
@samsucik Sorry, thought I had taken the `venus-train` command out -- that's just the name of the docker-compose service I use to run the training, so the offending command being sent over to Rasa that caused the issue is:

`rasa train --augmentation 30 --persist-nlu-data -vv`

I'm using the `MultiProjectImporter` in my config and had converted the config from 1.10.20 to 2.4.0 using the `rasa data convert config` command:

```yml
language: en

importers:
  - name: MultiProjectImporter

imports:
  - projects/REDACTED
  - ... more projects

pipeline:
  - name: WhitespaceTokenizer
  - name: RegexFeaturizer
  - name: LexicalSyntacticFeaturizer
  - name: CountVectorsFeaturizer
  - name: CountVectorsFeaturizer
    analyzer: char_wb
    min_ngram: 2
    max_ngram: 5
  - name: DIETClassifier
    epochs: 125
    BILOU_flag: true
    evaluate_every_number_of_epochs: 10
    evaluate_on_number_of_examples: 100
    use_masked_language_model: true
    number_of_transformer_layers: 4
    embedding_dimension: 50
    tensorboard_log_directory: logs
    tensorboard_log_level: epoch
  - name: EntitySynonymMapper
  - name: DucklingEntityExtractor
    url: http://duckling:8000
    dimensions:
      - distance
      - number
      - time
    locale: en_US
    timezone: America/New_York
  - name: FallbackClassifier
    threshold: 0.7
    ambiguity_threshold: 0.01

policies:
  - name: AugmentedMemoizationPolicy
    max_history: 5
  - name: FormPolicy
  - name: TEDPolicy
    epochs: 50
    max_history: 5
    batch_size:
      - 64
      - 128
    tensorboard_log_directory: logs
    tensorboard_log_level: epoch
  - name: RulePolicy
    core_fallback_threshold: 0.1
    core_fallback_action_name: action_default_fallback
```

Let me know if there's anything else you needed!

**Comment by samsucik** [comment]
Thanks @ortsaCniveK! I can't see anything wrong with the config. Since you use multiple projects, it'd make sense to try to narrow down the issue so we can meaningfully isolate and/or reproduce it. For the start, could you run `rasa train nlu` instead of the full `rasa train`, and could you try removing individual projects from the config so that you identify a minimal combination of projects which cause the error?

Another thing I'd do if I had access to your data (and which I encourage you to do) is [installing Rasa 2.4.0 from source](https://github.com/RasaHQ/rasa#building-from-source) and adding some logging statements to the relevant bits of `rasa/shared/nlu/training_data/formats/readerwriter.py` in order to learn more about the particular troublesome entity. My hunch is that this is about some entity-related edge case, so the best bet may be to find out which entity is causing it and then looking at the training data for that entity.

**Comment by TyDunn** [comment]
Please reopen if there are further questions
