### ISSUE TITLE
Failed file saving in interactive mode does not fail gracefully

### ISSUE THREAD

**Issue by ortsaCniveK** [RasaHQ/rasa#8365]
**Rasa version**: 2.4.3

**Rasa SDK version** (if used & relevant): 2.4.1

**Rasa X version** (if used & relevant): N/A

**Python version**: 3.8

**Operating system** (windows, osx, ...): Linux

**Issue**:
When exporting and quitting from an interactive session, if the process doesn't have proper read/write permissions (e.g. in a docker container) the CLI will report that a failed save occurred and offered to retry.  If you deny a retry, the CLI will fail with below provided traceback and hang indefinitely (until a CTRL+C command is sent).

There should be additional error handling to prevent this from hanging :)

**Error (including full traceback)**:
```log
? Failed to export 'new_domain.yml': [Errno 13] Permission denied: 'new_domain.yml'. Please make sure 'rasa' has read and write ac
cess to this file. Would you like to retry?  No                                                                                   
2021-04-05 19:01:23 ERROR    rasa.core.training.interactive  - An exception occurred while recording messages.
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/rasa/core/training/interactive.py", line 1476, in record_messages
    await _enter_user_message(conversation_id, endpoint)
  File "/opt/venv/lib/python3.8/site-packages/rasa/core/training/interactive.py", line 1315, in _enter_user_message
    message = await _ask_questions(question, conversation_id, endpoint, lambda a: not a)
  File "/opt/venv/lib/python3.8/site-packages/rasa/core/training/interactive.py", line 319, in _ask_questions
    should_retry = await _ask_if_quit(conversation_id, endpoint)
  File "/opt/venv/lib/python3.8/site-packages/rasa/core/training/interactive.py", line 634, in _ask_if_quit
    await _write_data_to_file(conversation_id, endpoint)
  File "/opt/venv/lib/python3.8/site-packages/rasa/core/training/interactive.py", line 611, in _write_data_to_file
    _retry_on_error(_write_domain_to_file, domain_path, events, domain)
  File "/opt/venv/lib/python3.8/site-packages/rasa/core/training/interactive.py", line 595, in _retry_on_error
    raise e
  File "/opt/venv/lib/python3.8/site-packages/rasa/core/training/interactive.py", line 588, in _retry_on_error
    return func(export_path, *args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/rasa/core/training/interactive.py", line 943, in _write_domain_to_file
    old_domain.merge(new_domain).persist_clean(dom  ain_path)
  File "/opt/venv/lib/python3.8/site-packages/rasa/shared/core/domain.py", line 1350, in persist_clean
    rasa.shared.utils.io.write_text_file(as_yaml, filename)
  File "/opt/venv/lib/python3.8/site-packages/rasa/shared/utils/io.py", line 116, in write_text_file
    with open(file_path, mode, encoding=encoding) as file:
PermissionError: [Errno 13] Permission denied: 'new_domain.yml'
2021-04-05 19:01:23 ERROR    asyncio  - Task exception was never retrieved
future: <Task finished name='Task-3' coro=<_serve_application.<locals>.run_interactive_io() done, defined at /opt/venv/lib/python3.8/site-packages/rasa/core/training/interactive.py:1569> exception=PermissionError(13, 'Permission denied')>
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/rasa/core/training/interactive.py", line 1572, in run_interactive_io
    await record_messages(
  File "/opt/venv/lib/python3.8/site-packages/rasa/core/training/interactive.py", line 1476, in record_messages
    await _enter_user_message(conversation_id, endpoint)
  File "/opt/venv/lib/python3.8/site-packages/rasa/core/training/interactive.py", line 1315, in _enter_user_message
    message = await _ask_questions(question, conversation_id, endpoint, lambda a: not a)
  File "/opt/venv/lib/python3.8/site-packages/rasa/core/training/interactive.py", line 319, in _ask_questions
    should_retry = await _ask_if_quit(conversation_id, endpoint)
  File "/opt/venv/lib/python3.8/site-packages/rasa/core/training/interactive.py", line 634, in _ask_if_quit
    await _write_data_to_file(conversation_id, endpoint)
  File "/opt/venv/lib/python3.8/site-packages/rasa/core/training/interactive.py", line 611, in _write_data_to_file
    _retry_on_error(_write_domain_to_file, domain_path, events, domain)
  File "/opt/venv/lib/python3.8/site-packages/rasa/core/training/interactive.py", line 595, in _retry_on_error
    raise e
  File "/opt/venv/lib/python3.8/site-packages/rasa/core/training/interactive.py", line 588, in _retry_on_error
    return func(export_path, *args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/rasa/core/training/interactive.py", line 943, in _write_domain_to_file
    old_domain.merge(new_domain).persist_clean(domain_path)
  File "/opt/venv/lib/python3.8/site-packages/rasa/shared/core/domain.py", line 1350, in persist_clean
    rasa.shared.utils.io.write_text_file(as_yaml, filename)
  File "/opt/venv/lib/python3.8/site-packages/rasa/shared/utils/io.py", line 116, in write_text_file
    with open(file_path, mode, encoding=encoding) as file:
PermissionError: [Errno 13] Permission denied: 'new_domain.yml'
```

**Command or request that led to error**:
```
rasa interactive
```

**Content of configuration file (config.yml)** (if relevant):
Not relevant.

**Content of domain file (domain.yml)** (if relevant):
Not relevant.

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @koernerfelicia will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by koernerfelicia** [comment]
@ortsaCniveK thank you for raising this, this does indeed look like a bug!
