### ISSUE TITLE
Unable to evaluate stories when stories contain slot_was_set

### ISSUE THREAD

**Issue by billtrn** [RasaHQ/rasa#8379]
**Rasa version**: 2.4.3

**Rasa SDK version** (if used & relevant): 2.4.1

**Rasa X version** (if used & relevant): None

**Python version**: 3.7.3

**Operating system** (windows, osx, ...):  Darwin-20.2.0-x86_64-i386-64bit

**Issue**:
As the title has indicated, I tried evaluating stories by sending a POST request to `/model/test/stories` per the [official docs](https://rasa.com/docs/rasa/pages/http-api#operation/testModelStories) but could not due to an InternalServerError. However, when removing all the `slot_was_set` in the request body, the request was executed successfully.

**Error (including full traceback)**:
```
Traceback (most recent call last):
  File "/Users/rasa/venv/lib/python3.7/site-packages/rasa/shared/core/training_data/loading.py", line 114, in load_data_from_files
    steps = reader.read_from_file(story_file)
  File "/Users/rasa/venv/lib/python3.7/site-packages/rasa/shared/core/training_data/story_reader/yaml_story_reader.py", line 99, in read_from_file
    filename, rasa.shared.utils.io.DEFAULT_ENCODING
  File "/Users/rasa/venv/lib/python3.7/site-packages/rasa/shared/core/training_data/story_reader/yaml_story_reader.py", line 118, in read_from_string
    return self.read_from_parsed_yaml(yaml_content)
  File "/Users/rasa/venv/lib/python3.7/site-packages/rasa/shared/core/training_data/story_reader/yaml_story_reader.py", line 143, in read_from_parsed_yaml
    parser.parse_data(data)
  File "/Users/rasa/venv/lib/python3.7/site-packages/rasa/shared/core/training_data/story_reader/yaml_story_reader.py", line 239, in parse_data
    self._parse_plain_item(item)
  File "/Users/rasa/venv/lib/python3.7/site-packages/rasa/shared/core/training_data/story_reader/yaml_story_reader.py", line 269, in _parse_plain_item
    self._parse_step(step)
  File "/Users/rasa/venv/lib/python3.7/site-packages/rasa/shared/core/training_data/story_reader/yaml_story_reader.py", line 302, in _parse_step
    self._parse_slot(step)
  File "/Users/rasa/venv/lib/python3.7/site-packages/rasa/shared/core/training_data/story_reader/yaml_story_reader.py", line 489, in _parse_slot
    SlotSet.type_name, {slot: self._slot_default_value(slot)}
  File "/Users/rasa/venv/lib/python3.7/site-packages/rasa/shared/core/training_data/story_reader/yaml_story_reader.py", line 510, in _slot_default_value
    slot = next(slot for slot in self.domain.slots if slot.name == slot_name)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/rasa/venv/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/Users/rasa/venv/lib/python3.7/site-packages/rasa/__main__.py", line 116, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/Users/rasa/venv/lib/python3.7/site-packages/rasa/cli/test.py", line 222, in test
    run_core_test(args)
  File "/Users/rasa/venv/lib/python3.7/site-packages/rasa/cli/test.py", line 108, in run_core_test
    additional_arguments=vars(args),
  File "/Users/rasa/venv/lib/python3.7/site-packages/rasa/test.py", line 157, in test_core
    rasa.utils.common.run_in_loop(test(stories, _agent, out_directory=output, **kwargs))
  File "/Users/rasa/venv/lib/python3.7/site-packages/rasa/utils/common.py", line 307, in run_in_loop
    result = loop.run_until_complete(f)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/Users/rasa/venv/lib/python3.7/site-packages/rasa/core/test.py", line 833, in test
    generator = await _create_data_generator(stories, agent, max_stories, e2e)
  File "/Users/rasa/venv/lib/python3.7/site-packages/rasa/core/test.py", line 351, in _create_data_generator
    story_graph = await test_data_importer.get_stories(use_e2e=use_e2e)
  File "/Users/rasa/venv/lib/python3.7/site-packages/rasa/shared/importers/importer.py", line 456, in get_stories
    template_variables, use_e2e, exclusion_percentage
  File "/Users/rasa/venv/lib/python3.7/site-packages/rasa/shared/importers/importer.py", line 370, in get_stories
    template_variables, use_e2e, exclusion_percentage
  File "/Users/rasa/venv/lib/python3.7/site-packages/rasa/shared/utils/common.py", line 141, in decorated
    return await cache.cached_result()
  File "/Users/rasa/venv/lib/python3.7/site-packages/rasa/shared/importers/importer.py", line 254, in get_stories
    stories = await asyncio.gather(*stories)
  File "/Users/rasa/venv/lib/python3.7/site-packages/rasa/shared/importers/rasa.py", line 54, in get_stories
    exclusion_percentage,
  File "/Users/rasa/venv/lib/python3.7/site-packages/rasa/shared/importers/utils.py", line 26, in story_graph_from_paths
    files, domain, template_variables, use_e2e, exclusion_percentage
RuntimeError: coroutine raised StopIteration
```

**Command or request that led to error**:
POST `model/test/stories`
Request body:
```yaml
stories:
  - story: "Cancel Order, Order Cancelled"
    steps:
      - intent: cancel_order_request
      - action: utter_welcome_message
      - action: utter_order_number_request
      - intent: order_number_provided
      - slot_was_set:
          - order_id
      - action: utter_cancellation_reason_request
      - intent: issue_reason_provided
      - action: utter_gratitude
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @amn41 will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by melindaloubser1** [comment]
@billtrn Were you using `slot_was_set` steps with slots without values? e.g. like this:
```
- story: something
   steps: 
   - intent: anything
   - slot_was_set:
      - some_text_slot
```
I see this on 2.6.0 as well, but only under the circumstance above. If I provide a value, which for a text slot is a dummy value to indicate "this slot is set", it works fine:

```
- story: something
   steps: 
   - intent: anything
   - slot_was_set:
      - some_text_slot: "some_dummy_value"
 ```

Using the first format no longer causes this error in `rasa>=2.7.1`.
