### ISSUE TITLE
Could not submit coverage report (HTTP timeout issue)

### ISSUE THREAD

**Issue by alwx** [RasaHQ/rasa#8399]
**Rasa version**: 2.4.2

**Python version**: 3.7 & 3.8

**Operating system** (windows, osx, ...): Linux 

**Issue**:
Not sure if anything can be done about that but sometimes test suite fails only because of coveralls HTTP timeout issue.

```
Run poetry run coveralls
Submitting coverage to coveralls.io...
Could not submit coverage: 504 Server Error: Gateway Time-out for url: https://coveralls.io/api/v1/jobs
Traceback (most recent call last):
  File "/home/runner/work/rasa/rasa/.venv/lib/python3.6/site-packages/coveralls/api.py", line 257, in wear
    response.raise_for_status()
  File "/home/runner/work/rasa/rasa/.venv/lib/python3.6/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Time-out for url: https://coveralls.io/api/v1/jobs

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/runner/work/rasa/rasa/.venv/lib/python3.6/site-packages/coveralls/cli.py", line 85, in main
    result = coverallz.wear()
  File "/home/runner/work/rasa/rasa/.venv/lib/python3.6/site-packages/coveralls/api.py", line 261, in wear
    'Could not submit coverage: {}'.format(e)) from e
coveralls.exception.CoverallsException: Could not submit coverage: 504 Server Error: Gateway Time-out for url: https://coveralls.io/api/v1/jobs
Error: Process completed with exit code 1.
```
(https://github.com/RasaHQ/rasa/pull/8334/checks?check_run_id=2227954239)

**Comment by HotThoughts** [comment]
This error is a [global issue](https://github.com/lemurheavy/coveralls-public/issues/1543) from the Coveralls side. 

Fixed https://github.com/RasaHQ/rasa/pull/8549, so close this one.
