### ISSUE TITLE
policy_name = policy.pop("name") KeyError: 'name'

### ISSUE THREAD

**Issue by Gourav-infobiz** [RasaHQ/rasa#8426]
**Rasa version**: 2.4.x

**Python version**: 3.7.0

**Operating system** (windows, osx, ...):

**Issue**:

**Error (including full traceback)**: 
```
Traceback (most recent call last):
  File "c:\users\dell.desktop-c18n4a6\anaconda3\envs\env\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\dell.desktop-c18n4a6\anaconda3\envs\env\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\DELL.DESKTOP-C18N4A6\anaconda3\envs\env\Scripts\rasa.exe\__main__.py", line 7, in <module>
  File "c:\users\dell.desktop-c18n4a6\anaconda3\envs\env\lib\site-packages\rasa\__main__.py", line 116, in main
    cmdline_arguments.func(cmdline_arguments)
  File "c:\users\dell.desktop-c18n4a6\anaconda3\envs\env\lib\site-packages\rasa\cli\train.py", line 58, in <lambda>
    train_parser.set_defaults(func=lambda args: train(args, can_exit=True))
  File "c:\users\dell.desktop-c18n4a6\anaconda3\envs\env\lib\site-packages\rasa\cli\train.py", line 102, in train
    finetuning_epoch_fraction=args.epoch_fraction,
  File "c:\users\dell.desktop-c18n4a6\anaconda3\envs\env\lib\site-packages\rasa\train.py", line 109, in train
    loop,
  File "c:\users\dell.desktop-c18n4a6\anaconda3\envs\env\lib\site-packages\rasa\utils\common.py", line 307, in run_in_loop
    result = loop.run_until_complete(f)
  File "c:\users\dell.desktop-c18n4a6\anaconda3\envs\env\lib\asyncio\base_events.py", line 568, in run_until_complete
    return future.result()
  File "c:\users\dell.desktop-c18n4a6\anaconda3\envs\env\lib\site-packages\rasa\train.py", line 174, in train_async
    finetuning_epoch_fraction=finetuning_epoch_fraction,
  File "c:\users\dell.desktop-c18n4a6\anaconda3\envs\env\lib\site-packages\rasa\train.py", line 353, in _train_async_internal
    finetuning_epoch_fraction=finetuning_epoch_fraction,
  File "c:\users\dell.desktop-c18n4a6\anaconda3\envs\env\lib\site-packages\rasa\train.py", line 415, in _do_training
    finetuning_epoch_fraction=finetuning_epoch_fraction,
  File "c:\users\dell.desktop-c18n4a6\anaconda3\envs\env\lib\site-packages\rasa\train.py", line 610, in _train_core_with_validated_data
    model_to_finetune=model_to_finetune,
  File "c:\users\dell.desktop-c18n4a6\anaconda3\envs\env\lib\site-packages\rasa\core\train.py", line 45, in train
    policies = config.load(policy_config)
  File "c:\users\dell.desktop-c18n4a6\anaconda3\envs\env\lib\site-packages\rasa\core\config.py", line 56, in load
    return PolicyEnsemble.from_dict(config_data)
  File "c:\users\dell.desktop-c18n4a6\anaconda3\envs\env\lib\site-packages\rasa\core\policies\ensemble.py", line 427, in from_dict
    policy_name = policy.pop("name")
KeyError: 'name'
```

**Command or request that led to error**: 
```
rasa train 
```

**Content of configuration file (config.yml)** (if relevant):
```# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.
   - name: WhitespaceTokenizer
   - name: RegexFeaturizer
   - name: CountVectorsFeaturizer
   - name: DIETClassifier
     epochs: 100
   - name: EntitySynonymMapper
   - name: FallbackClassifier
     threshold: 0.3
     ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
   - name: MemoizationPolicy
   - name: RulePolicy
   - name: TEDPolicy
     max_history: 5
     epochs: 100
   - fallback_action_name : "action_Custom_fallback"


```

**Comment by Gourav-infobiz** [comment]
@JiteshGaikwad

**Comment by sara-tagger** [comment]
Thanks for the issue, @amn41 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by Gourav-infobiz** [comment]
@amn41 please help

**Comment by erohmensing** [comment]
This is happening due to the ` - fallback_action_name : "action_Custom_fallback"` entry in your policies list, as it's being registered. There is no more fallback parameter in the policies configuration; you should delete that line and instead [add a fallback rule](https://rasa.com/docs/rasa/fallback-handoff#3-creating-an-nlu-fallback-rule) to be predicted when the intent is `nlu_fallback`.
