### ISSUE TITLE
rasa fresh installation say error 500 when try to use rest endpoint

### ISSUE THREAD

**Issue by LionelBino** [RasaHQ/rasa#8481]
Hi everyone! I tried to start with Rasa. I need to create a integration using webhooks and always find the error 500 when tried to use the following curl command:

```
curl -X POST http://localhost:5005/webhooks/rest/webhook -H "Content-Type: application/json" -d '[{"text": "hi"}]'
```

The error that rasa server say is the next one:

```
Exception occurred while handling uri: 'http://localhost:5005/webhooks/rest/webhook'
Traceback (most recent call last):
  File "/PATH_TO_MY_DEV_FOLDER/rasas/generalista-es/venv/lib/python3.8/site-packages/sanic/app.py", line 938, in handle_request
    response = await response
  File "/PATH_TO_MY_DEV_FOLDERs/rasas/generalista-es/venv/lib/python3.8/site-packages/rasa/core/channels/rest.py", line 101, in receive
    sender_id = await self._extract_sender(request)
  File "/PATH_TO_MY_DEV_FOLDER/rasas/generalista-es/venv/lib/python3.8/site-packages/rasa/core/channels/rest.py", line 52, in _extract_sender
    return req.json.get("sender", None)
AttributeError: 'list' object has no attribute 'get'
```

The `rasa --version` output is the following:

```
Rasa Version      :         2.5.0
Minimum Compatible Version: 2.2.0a1
Rasa SDK Version  :         2.5.0
Rasa X Version    :         None
Python Version    :         3.8.9+
Operating System  :         Linux-5.4.0-70-generic-x86_64-with-glibc2.29
Python Path       :         /PATH_TO_MY_DEV_FOLDER/rasas/generalista-es/venv/bin/python3
```

The installation is a fresh installation. I tried this using python 3.7 and 3.8.

**Comment by Dustyposa** [comment]
the post body format is wrong. Try this one:
```bash
curl -X POST http://localhost:5005/webhooks/rest/webhook -H "Content-Type: application/json" -d '{"message": "hi"}'
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @yennycheung will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
