### ISSUE TITLE
AttributeError: module 'tensorflow.python.keras.engine.training' has no attribute 'enable_multi_worker'

### ISSUE THREAD

**Issue by jaykeerti** [RasaHQ/rasa#8561]
**Rasa version**:
Rasa Version      :         2.5.0
Minimum Compatible Version: 2.2.0a1
Rasa X Version    :         None
**Rasa SDK version** (if used & relevant):
Rasa SDK Version  :         2.5.0
**Rasa X version** (if used & relevant):
None
**Python version**:
Python Version    :         3.6.8
**Operating system** (windows, osx, ...):
Operating System  :         Windows-10-10.0.17763-SP0

**Issue**:

rasa train causes this error

The configuration for pipeline and policies was chosen automatically. It was written into the config file at 'config.yml'.
Training NLU model...

**Error (including full traceback)**:
```
The configuration for pipeline and policies was chosen automatically. It was written into the config file at 'config.yml'.
Training NLU model...
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\user\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\AppData\Local\Programs\Python\Python36\Scripts\rasa.exe\__main__.py", line 7, in <module>
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\rasa\__main__.py", line 117, in main
    cmdline_arguments.func(cmdline_arguments)
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\rasa\cli\train.py", line 59, in <lambda>
    train_parser.set_defaults(func=lambda args: run_training(args, can_exit=True))
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\rasa\cli\train.py", line 103, in run_training
    finetuning_epoch_fraction=args.epoch_fraction,
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\rasa\api.py", line 124, in train
    loop,
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\rasa\utils\common.py", line 310, in run_in_loop
    result = loop.run_until_complete(f)
  File "c:\users\user\appdata\local\programs\python\python36\lib\asyncio\base_events.py", line 484, in run_until_complete
    return future.result()
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\rasa\model_training.py", line 119, in train_async
    finetuning_epoch_fraction=finetuning_epoch_fraction,
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\rasa\model_training.py", line 300, in _train_async_internal
    finetuning_epoch_fraction=finetuning_epoch_fraction,
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\rasa\model_training.py", line 343, in _do_training
    finetuning_epoch_fraction=finetuning_epoch_fraction,
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\rasa\model_training.py", line 766, in _train_nlu_with_validated_data
    **additional_arguments,
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\rasa\nlu\train.py", line 98, in train
    nlu_config, component_builder, model_to_finetune=model_to_finetune
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\rasa\nlu\model.py", line 161, in __init__
    components.validate_requirements(cfg.component_names)
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\rasa\nlu\components.py", line 57, in validate_requirements
    from rasa.nlu import registry
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\rasa\nlu\registry.py", line 12, in <module>
    from rasa.nlu.classifiers.diet_classifier import DIETClassifier
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\rasa\nlu\classifiers\diet_classifier.py", line 24, in <module>
    from rasa.utils.tensorflow.models import RasaModel, TransformerRasaModel
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\rasa\utils\tensorflow\models.py", line 51, in <module>
    from rasa.utils.tensorflow.temp_keras_modules import TmpKerasModel
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\rasa\utils\tensorflow\temp_keras_modules.py", line 26, in <module>
    class TmpKerasModel(tf.keras.models.Model):
  File "c:\users\user\appdata\local\programs\python\python36\lib\site-packages\rasa\utils\tensorflow\temp_keras_modules.py", line 37, in TmpKerasModel
    @training.enable_multi_worker
AttributeError: module 'tensorflow.python.keras.engine.training' has no attribute 'enable_multi_worker'
```

**Command or request that led to error**:
```
rasa train
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml

```

**Comment by sara-tagger** [comment]
Thanks for the issue, @Imod7 will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by gmftbyGMFTBY** [comment]
Any progress about this bug?

**Comment by jaykeerti** [comment]
@gmftbyGMFTBY The open source one `[](https://rasa.com/docs/rasa/installation/)`

**Comment by chiranshu14** [comment]
Has anyone figured this out?  @gmftbyGMFTBY  @jaykeerti ?
Why does it work with conda but not with normal Python?

How do we deploy this with our normal python versions? I already have django running, was planning on integrating rasa model inside that. But it won't work.
