### ISSUE TITLE
Rasa shell crashes if form with only custom slot mappings is defined

### ISSUE THREAD

**Issue by koernerfelicia** [RasaHQ/rasa#8590]
**Rasa version**:
2.5.1
**Python version**:
3.8.7
**Operating system** (windows, osx, ...):
OSX

**Issue**:

If a user wants to define a form with only custom slot mappings, then `required_slots` for that form in the domain is empty. This results in a crash when we try to access `REQUIRED_SLOTS` for that form. We need to either force at least one slot with a pre-defined mapping for a form defined in a domain, or deal with this case more gracefully in `domain.slot_mapping_for_form`:
```
    def slot_mapping_for_form(self, form_name: Text) -> Dict[Text, Any]:
        """...
        """
        form = self.forms.get(form_name, {})
        if REQUIRED_SLOTS_KEY in form:
            return form[REQUIRED_SLOTS_KEY]
        else:
            return {}
```
**Error (including full traceback)**:
```
21-04-30 19:13:55 ERROR    rasa.core.processor  - Encountered an exception while running action 'contract_form'.Bot will continue, but the actions events are lost. Please check the logs of your action server for more information.
Traceback (most recent call last):
  File "/home/jsv/Documents/CARRERA/tfg4/resources/rasa-chatbot/.env/lib/python3.6/site-packages/rasa/core/processor.py", line 773, in _run_action
    output_channel, nlg, temporary_tracker, self.domain
  File "/home/jsv/Documents/CARRERA/tfg4/resources/rasa-chatbot/.env/lib/python3.6/site-packages/rasa/core/actions/loops.py", line 26, in run
    events += await self.activate(output_channel, nlg, tracker, domain)
  File "/home/jsv/Documents/CARRERA/tfg4/resources/rasa-chatbot/.env/lib/python3.6/site-packages/rasa/core/actions/forms.py", line 706, in activate
    for slot_name in self.required_slots(domain):
  File "/home/jsv/Documents/CARRERA/tfg4/resources/rasa-chatbot/.env/lib/python3.6/site-packages/rasa/core/actions/forms.py", line 58, in required_slots
    return list(domain.slot_mapping_for_form(self.name()).keys())
AttributeError: 'NoneType' object has no attribute 'key
```

**Command or request that led to error**:
```
rasa shell
```

**Content of configuration file (config.yml)** (if relevant):
```yml

```

**Content of domain file (domain.yml)** (if relevant):
```yml
forms:
    contract_form:
```

```
forms:
  tobi_form:
    required_slots:
```

**Comment by joejuzl** [comment]
Hi @koernerfelicia does this only happen when the user adds `required_slots:` with no value, or also when it is not there at all?

**Comment by koernerfelicia** [comment]
@joejuzl I just tested it on formbot and was able to reproduce without `required_slots`, like so:

```
forms:
  restaurant_form:
```
