### ISSUE TITLE
Error when starting Rasa X

### ISSUE THREAD

**Issue by joancipria** [RasaHQ/rasa#8605]
**Rasa version**: 2.4.3

**Rasa SDK version**: 2.4.1

**Rasa X version**: 0.38.1

**Python version**: 3.6

**Operating system**: Linux-5.10.30-1-MANJARO-x86_64-with-arch-Manjaro-Linux

**Issue**:  When I try to init Rasa x in my project it throws the following error: `Sorry, something went wrong (see error above). Make sure to start Rasa X with valid data and valid domain and config files. Please, also check any warnings that popped up`

I think my data is valid, rasa data validate goes perfect and the Rasa shell & train are working perfectly so I don’t know what’s going on. I’ve tried upgrading Rasa and Rasa X following the compatibility matrix without success, getting the same error. Does somebody know how can solve this problem?

**Error (including full traceback)**:
```
2021-05-04 17:32:30.558375: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2021-05-04 17:32:30.558443: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2021-05-04 17:32:37.033904: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2021-05-04 17:32:37.033942: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2021-05-04 17:32:37.033968: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (joan-13z990gaa52b): /proc/driver/nvidia/version does not exist
Starting Rasa X in local mode... 🚀
Traceback (most recent call last):
  File "/home/joan/Desktop/VihrtualApp_Chatbot/venv/lib/python3.6/site-packages/rasa/cli/x.py", line 500, in run_locally
    domain_path=domain_path,
  File "/home/joan/Desktop/VihrtualApp_Chatbot/venv/lib/python3.6/site-packages/rasax/community/local.py", line 242, in main
    project_path, data_path, session, args.port, config_path, domain_path
  File "/home/joan/Desktop/VihrtualApp_Chatbot/venv/lib/python3.6/site-packages/rasax/community/local.py", line 169, in _initialize_with_local_data
    domain_path=domain_path,
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/home/joan/Desktop/VihrtualApp_Chatbot/venv/lib/python3.6/site-packages/rasax/community/initialise.py", line 381, in inject_files_from_disk
    nlu_files, constants.COMMUNITY_PROJECT_NAME, username, data_service, nlg_service
  File "/home/joan/Desktop/VihrtualApp_Chatbot/venv/lib/python3.6/site-packages/rasax/community/initialise.py", line 101, in inject_nlu_data
    nlu_files, project_id, username
  File "/home/joan/Desktop/VihrtualApp_Chatbot/venv/lib/python3.6/site-packages/rasax/community/services/data_service.py", line 1763, in save_bulk_data_from_files
    add_data_items_to_domain=False,
  File "/home/joan/Desktop/VihrtualApp_Chatbot/venv/lib/python3.6/site-packages/rasax/community/services/data_service.py", line 1903, in save_bulk_data
    self.save_additional_training_features(project_id, training_data, filename)
  File "/home/joan/Desktop/VihrtualApp_Chatbot/venv/lib/python3.6/site-packages/rasax/community/services/data_service.py", line 716, in save_additional_training_features
    project_id, training_data.entity_synonyms, filename
  File "/home/joan/Desktop/VihrtualApp_Chatbot/venv/lib/python3.6/site-packages/rasax/community/services/data_service.py", line 655, in _bulk_save_entity_synonyms
    project_id, synonym_name, mapped_values, filename
  File "/home/joan/Desktop/VihrtualApp_Chatbot/venv/lib/python3.6/site-packages/rasax/community/services/data_service.py", line 1037, in create_entity_synonym
    project_id, entity_synonym.id, mapped_values
  File "/home/joan/Desktop/VihrtualApp_Chatbot/venv/lib/python3.6/site-packages/rasax/community/services/data_service.py", line 1289, in add_entity_synonym_mapped_values
    f"Value to map '{entity_synonym.name}' is equal to the entity "
  File "/home/joan/Desktop/VihrtualApp_Chatbot/venv/lib/python3.6/site-packages/rasax/community/utils/cli.py", line 84, in raise_warning
    warnings.warn(message, category=category, **kwargs)
  File "/usr/lib/python3.6/warnings.py", line 101, in _showwarnmsg
    _showwarnmsg_impl(msg)
  File "/usr/lib/python3.6/warnings.py", line 28, in _showwarnmsg_impla
    text = _formatwarnmsg(msg)
  File "/usr/lib/python3.6/warnings.py", line 116, in _formatwarnmsg
    msg.filename, msg.lineno, line=msg.line)
TypeError: formatwarning() got an unexpected keyword argument 'line'

Sorry, something went wrong (see error above). Make sure to start Rasa X with valid data and valid domain and config files. Please, also check any warnings that popped up.
If you need help fixing the issue visit our forum: https://forum.rasa.com/.
```

**Command or request that led to error**:
```
rasa x
```

**Content of configuration file (config.yml)**: 

https://github.com/joancipria/VihrtualApp/blob/develop/config.yml

**Content of domain file (domain.yml)**: 
https://github.com/joancipria/VihrtualApp/blob/develop/domain.yml

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @hsm207 will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by hsm207** [comment]
hi @joancipria 

This error is specific to Python 3.6. See this [bug report ](https://bugs.python.org/issue35178) for details.

The solution is to upgrade the Python installation to 3.7 or above.

I've cloned the [VihrtualApp](https://github.com/joancipria/VihrtualApp/tree/develop) project and set up the following environment:

```bash
Rasa Version     : 2.4.3
Rasa SDK Version : 2.4.1
Rasa X Version   : 0.38.1
Python Version   : 3.7.10
```

Running `rasa x` does not throw that error anymore.
