### ISSUE TITLE
Flakey CI test: Post Job Cleanup

### ISSUE THREAD

**Issue by ancalita** [RasaHQ/rasa#8663]
**Error Information**:
```
Post job cleanup.
/usr/bin/tar --posix --use-compress-program zstd -T0 -cf cache.tzst -P -C /home/runner/work/rasa/rasa --files-from manifest.txt
Warning: Cache service responded with 429 during upload chunk.
/home/runner/work/_actions/actions/cache/v2/dist/save/index.js:4043
                        throw new Error(`Cache upload failed because file read failed with ${error.message}`);
                        ^

Error: Cache upload failed because file read failed with EBADF: bad file descriptor, read
    at ReadStream.<anonymous> (/home/runner/work/_actions/actions/cache/v2/dist/save/index.js:4043:31)
    at ReadStream.emit (events.js:210:5)
    at internal/fs/streams.js:167:12
    at FSReqCallback.wrapper [as oncomplete] (fs.js:470:5)
```

**Job Run URL examples**:
https://github.com/RasaHQ/rasa/runs/2526705587

**Definition of Done**:
- [ ] apply fix so that tests run deterministic

**Comment by tczekajlo** [comment]
It was an error caused by GH itself, there is nothing to do/fix.
