### ISSUE TITLE
Getting Timeout error in Rasa 2.6.0

### ISSUE THREAD

**Issue by sudhir512kj** [RasaHQ/rasa#8667]
**Rasa version**:
2.6.0
**Rasa SDK version**:
2.6.0

**Python version**:
Python 3.8
**Operating system** (windows, osx, ...):
Windows 10

**Error (including full traceback)**:
I am getting this error with rasa 2.6.0 version and Python 3.8
```
2021-05-12 08:10:12 ERROR    asyncio  - Task exception was never retrieved
future: <Task finished name='Task-2' coro=<configure_app.<locals>.run_cmdline_io() done, defined at c:\users\sures\rasa-for-beginners\env\lib\site-packages\rasa\core\run.py:131> exception=TimeoutError()>
Traceback (most recent call last):
  File "c:\users\sures\rasa-for-beginners\env\lib\site-packages\rasa\core\run.py", line 135, in run_cmdline_io
    await console.record_messages(
  File "c:\users\sures\rasa-for-beginners\env\lib\site-packages\rasa\core\channels\console.py", line 182, in record_messages
    async for response in bot_responses:
  File "c:\users\sures\rasa-for-beginners\env\lib\site-packages\rasa\core\channels\console.py", line 137, in send_message_receive_stream
    async for line in resp.content:
  File "c:\users\sures\rasa-for-beginners\env\lib\site-packages\aiohttp\streams.py", line 39, in __anext__
    rv = await self.read_func()
  File "c:\users\sures\rasa-for-beginners\env\lib\site-packages\aiohttp\streams.py", line 338, in readline
    await self._wait("readline")
  File "c:\users\sures\rasa-for-beginners\env\lib\site-packages\aiohttp\streams.py", line 306, in _wait
    await waiter
  File "c:\users\sures\rasa-for-beginners\env\lib\site-packages\aiohttp\helpers.py", line 656, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
```

**Command or request that led to error**:
when i do sent a message to bot like "hi"
```
rasa shell
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @samsucik will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by sudhir512kj** [comment]
@samsucik  @sara-tagger  I have solved the error thank you.

**Comment by ailungoal** [comment]
how to solve this problem?https://github.com/sudhir512kj

**Comment by samsucik** [comment]
@ailungoal could you, please, create a new issue where you precisely describe your situation? Thanks a lot!
