### ISSUE TITLE
ResponseSelector training fails with `use_text_as_label` and no transformer due to inconsistent data pre-processing

### ISSUE THREAD

**Issue by samsucik** [RasaHQ/rasa#8705]
_Rasa version_ : 2.6.1

 _Python version_ : 3.7.9

 _Operating system_ (windows, osx, ...): OSX

 _Issue_ : As previously reported in #8046, ResponseSelector training fails with `use_text_as_label` when no further specification of the selector's transformer is given in the config.

This bug report is about a particularly deep issue that results in an error only when the transformer has no layers (i.e. the default), but not when the transformer has some layers and just `transformer_size` is missing in the config (this case has been addressed over in #8046).

The issue lies within the ResponseSelector & DIET codebase where, during training, two versions of model data are created for the label attribute – one version with the token-level features removed if no transformer is present, the other version with all those features preserved. Subsequently, model layers for processing labels are created based on the label's data signature derived from the second version of the data. Meaning that these model layers assume the future presence of token-level features. However, for the actual training, the version of the data without token-level features is used. Which ultimately leads to the observed error. More details [here| [https://rasa-hq.slack.com/archives/C8LEHMTAM/p1620991628244100?thread_ts=1620810229.176200&cid=C8LEHMTAM](https://rasa-hq.slack.com/archives/C8LEHMTAM/p1620991628244100?thread_ts=1620810229.176200&cid=C8LEHMTAM)].

 _Error (including full traceback)_ :

Traceback (most recent call last): File "/Users/sams/.miniconda/envs/rasaenv/bin/rasa", line 5, in main() File "/Users/sams/rasa/rasa/**main**.py", line 117, in main cmdline_arguments.func(cmdline_arguments) File "/Users/sams/rasa/rasa/cli/train.py", line 206, in run_nlu_training finetuning_epoch_fraction=args.epoch_fraction, File "/Users/sams/rasa/rasa/model_training.py", line 658, in train_nlu finetuning_epoch_fraction=finetuning_epoch_fraction, File "/Users/sams/rasa/rasa/utils/common.py", line 296, in run_in_loop result = loop.run_until_complete(f) File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete File "/Users/sams/rasa/rasa/model_training.py", line 705, in train_nlu_async finetuning_epoch_fraction=finetuning_epoch_fraction, File "/Users/sams/rasa/rasa/model_training.py", line 766, in _train_nlu_with_validated_data ***additional_arguments, File "/Users/sams/rasa/rasa/nlu/train.py", line 116, in train interpreter = trainer.train(training_data, **kwargs) File "/Users/sams/rasa/rasa/nlu/model.py", line 219, in train component.train(working_data, self.config, **context) File "/Users/sams/rasa/rasa/nlu/classifiers/diet_classifier.py", line 867, in train shuffle=False, # we use custom shuffle inside data generator File "/Users/sams/.miniconda/envs/rasaenv/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 108, in _method_wrapper return method(self, *args, **kwargs) File "/Users/sams/rasa/rasa/utils/tensorflow/temp_keras_modules.py", line 191, in fit tmp_logs = train_function(iterator) File "/Users/sams/.miniconda/envs/rasaenv/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 780, in *call** result = self._call(**args, **kwds) File "/Users/sams/.miniconda/envs/rasaenv/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 823, in _call self._initialize(args, kwds, add_initializers_to=initializers) File "/Users/sams/.miniconda/envs/rasaenv/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 697, in _initialize *args, **kwds)) File "/Users/sams/.miniconda/envs/rasaenv/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2855, in _get_concrete_function_internal_garbage_collected graph_function, _, _ = self._maybe_define_function(args, kwargs) File "/Users/sams/.miniconda/envs/rasaenv/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3213, in _maybe_define_function graph_function = self._create_graph_function(args, kwargs) File "/Users/sams/.miniconda/envs/rasaenv/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 3075, in _create_graph_function capture_by_value=self._capture_by_value), File "/Users/sams/.miniconda/envs/rasaenv/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 986, in func_graph_from_py_func func_outputs = python_func(*func_args, **func_kwargs) File "/Users/sams/.miniconda/envs/rasaenv/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 600, in wrapped_fn return weak_wrapped_fn().*wrapped**(*args, **kwds) File "/Users/sams/.miniconda/envs/rasaenv/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py", line 973, in wrapper raise e.ag_error_metadata.to_exception(e) ValueError: in user code:

/Users/sams/.miniconda/envs/rasaenv/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:806 train_function * return step_function(self, iterator) /Users/sams/rasa/rasa/utils/tensorflow/rasa_layers.py:856 call * seq_sent_features, mask_combined_sequence_sentence = self._tf_layers[ /Users/sams/rasa/rasa/utils/tensorflow/rasa_layers.py:509 call * sequence_features_combined = self._combine_sequence_level_features( /Users/sams/rasa/rasa/utils/tensorflow/rasa_layers.py:434 _combine_sequence_level_features * sequence_features_combined = self._tf_layers[f"sparse_dense.

 {SEQUENCE} 

"]( /Users/sams/rasa/rasa/utils/tensorflow/rasa_layers.py:202 call * return tf.concat(dense_features, axis=-1) /Users/sams/.miniconda/envs/rasaenv/lib/python3.7/site-packages/tensorflow/python/util/dispatch.py:201 wrapper ** return target(*args, **kwargs) /Users/sams/.miniconda/envs/rasaenv/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py:1654 concat return gen_array_ops.concat_v2(values=values, axis=axis, name=name) /Users/sams/.miniconda/envs/rasaenv/lib/python3.7/site-packages/tensorflow/python/ops/gen_array_ops.py:1222 concat_v2 "ConcatV2", values=values, axis=axis, name=name) /Users/sams/.miniconda/envs/rasaenv/lib/python3.7/site-packages/tensorflow/python/framework/op_def_library.py:530 _apply_op_helper (input_name, op_type_name, len(values), num_attr.minimum))

ValueError: List argument 'values' to 'ConcatV2' Op with length 0 shorter than minimum length 2.

 _Command or request that led to error_ :

rasa train nlu

 _Content of configuration file (config.yml)_ (if relevant):

<pre>language: en

pipeline:

*   name: WhitespaceTokenizer
*   name: CountVectorsFeaturizer
*   name: ResponseSelector
     epochs: 1
     use_text_as_label: true
     number_of_transformer_layers: 0</pre>

 _Content of domain file (domain.yml)_ (if relevant):

<pre>version: "2.0"
 intents:

*   greet
*   goodbye</pre>

 _NLU data_ :

<pre>version: "2.0"
 nlu:

*   intent: greet/hi
     examples: |
*   hey
*   hello

*   intent: greet/bye
     examples: |
*   bye
*   ciao

*   intent: goodbye
     examples: |
*   see you
*   good night

responses:
 utter_goodbye:

*   text: "Bye"

 utter_greet/hi:

*   text: hey there

 utter_greet/bye:

*   text: bye</pre>

 _Proposed definition of done_ :

*   [ ] Understand if the different versions of the data are needed or can be made consistent
*   [ ] Take a decision and either make the data versions consistent, or, if that's not desirable, create an issue that proposes a suitable fix. Consult PM.

**Comment by samsucik** [comment]
@alopez what's the meaning of/reasoning behind the `rasa-3.0-planning` label for this issue? I think this bug has nothing to do with 3.0, but maybe "planning" is the key word here? 🤔

**Comment by samsucik** [comment]
@TyDunn I'd like to lobby this one. We're currently [not testing the `use_text_as_label` variant of `ResponseSelector` at all (in the model regression tests)](https://github.com/RasaHQ/training-data/pull/13) because of this bug.

I don't know how many users set `use_text_as_label: true` but if they currently do this (and don't tweak the rest of the `ResponseSelector` config), then training will fail for them...

**Comment by alopez** [comment]
@ka-bu primary assignee
@JEM-Mosig reviewer

**Comment by rgstephens** [comment]
> and don't tweak the rest of the ResponseSelector config

@samsucik I just ran into this.  Is there a workaround?

**Comment by samsucik** [comment]
@rgstephens only if one is willing to use a slightly different config for ResponseSelector. The issue is quite deep as far as I know (from @ka-bu who's working on a fix [here](https://github.com/RasaHQ/rasa/pull/9010)). So, to make things work, I personally would either:
1. for now, use a transformer in ResponseSelector (i.e. set `number_of_transformer_layers` to something greater than 0, perhaps just 1 for simplicity), or
2. for now, use ResponseSelector without `use_text_as_label` (as far as I know, this bug occurs only with `use_text_as_label: true`)

**Comment by samsucik** [comment]
@ka-bu just to confirm, your work around the more complex refactoring that would also address this issue got paused in October and hasn't resumed yet? In any case, do you think we can close this particular issue because those other issues/PRs cover it?

**Comment by ka-bu** [comment]
> @ka-bu just to confirm, your work around the more complex refactoring that would also address this issue got paused in October and hasn't resumed yet? In any case, do you think we can close this particular issue because those other issues/PRs cover it?

yep, that work has been paused -- I'm not aware of any other issue/PR that covers this bug
