### ISSUE TITLE
InvalidArgumentError:  reshape cannot infer the missing input size for an empty tensor

### ISSUE THREAD

**Issue by asmaier** [RasaHQ/rasa#8729]
```
# rasa --version
Rasa Version      :         2.6.2
Minimum Compatible Version: 2.6.0
Rasa SDK Version  :         2.6.0
Rasa X Version    :         None
Python Version    :         3.7.9
Operating System  :         Linux-5.10.25-linuxkit-x86_64-with-debian-10.8
Python Path       :         /usr/local/bin/python
```

**Issue**:
I updated Rasa from 1.10.20 to the newest version 2.6.2 . I converted the training data to yaml format as suggested in the migration guide. To make sure I'm doing no mistakes I'm simply using a default config.yml (see below). But when I start training using the training command described below, the training crashes with the error

```
tensorflow.python.framework.errors_impl.InvalidArgumentError:  reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
```

I have no idea what might be the reason for this, but it is a blocker for me. I cannot train my bot with 2.6.2. 
Could it be an issue with my training data? Should I downgrade to an older version of Rasa? 

**Error (including full traceback)**:
```
Training Core model...
Processed story blocks: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 226/226 [00:03<00:00, 68.22it/s, # trackers=1]
Processed story blocks: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 226/226 [01:09<00:00,  3.25it/s, # trackers=50]
Processed story blocks: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 226/226 [01:35<00:00,  2.37it/s, # trackers=50]
Processed story blocks: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 226/226 [02:02<00:00,  1.85it/s, # trackers=50]
/usr/local/lib/python3.7/site-packages/rasa/shared/utils/io.py:97: UserWarning: Found a rule-based policy in your pipeline but no rule-based training data. Please add rule-based stories to your training data or remove the rule-based policy (`RulePolicy`) from your your pipeline.
  More info at https://rasa.com/docs/rasa/rules
Processed trackers: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 206/206 [00:05<00:00, 39.43it/s, # actions=1461]
Processed actions: 1461it [00:01, 1213.42it/s, # examples=1446]
Processed trackers: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 706/706 [00:34<00:00, 20.17it/s, # actions=5694]
Epochs:   0%|                                                                                                                                                                               | 0/100 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.7/site-packages/rasa/__main__.py", line 135, in <module>
    main()
  File "/usr/local/lib/python3.7/site-packages/rasa/__main__.py", line 117, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/usr/local/lib/python3.7/site-packages/rasa/cli/train.py", line 59, in <lambda>
    train_parser.set_defaults(func=lambda args: run_training(args, can_exit=True))
  File "/usr/local/lib/python3.7/site-packages/rasa/cli/train.py", line 103, in run_training
    finetuning_epoch_fraction=args.epoch_fraction,
  File "/usr/local/lib/python3.7/site-packages/rasa/api.py", line 124, in train
    loop,
  File "/usr/local/lib/python3.7/site-packages/rasa/utils/common.py", line 296, in run_in_loop
    result = loop.run_until_complete(f)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/lib/python3.7/site-packages/rasa/model_training.py", line 119, in train_async
    finetuning_epoch_fraction=finetuning_epoch_fraction,
  File "/usr/local/lib/python3.7/site-packages/rasa/model_training.py", line 300, in _train_async_internal
    finetuning_epoch_fraction=finetuning_epoch_fraction,
  File "/usr/local/lib/python3.7/site-packages/rasa/model_training.py", line 362, in _do_training
    finetuning_epoch_fraction=finetuning_epoch_fraction,
  File "/usr/local/lib/python3.7/site-packages/rasa/model_training.py", line 557, in _train_core_with_validated_data
    model_to_finetune=model_to_finetune,
  File "/usr/local/lib/python3.7/site-packages/rasa/core/train.py", line 70, in train
    agent.train(training_data, **additional_arguments)
  File "/usr/local/lib/python3.7/site-packages/rasa/core/agent.py", line 753, in train
    training_trackers, self.domain, interpreter=self.interpreter, **kwargs
  File "/usr/local/lib/python3.7/site-packages/rasa/core/policies/ensemble.py", line 212, in train
    trackers_to_train, domain, interpreter=interpreter, **kwargs
  File "/usr/local/lib/python3.7/site-packages/rasa/core/policies/ted_policy.py", line 590, in train
    shuffle=False,  # we use custom shuffle inside data generator
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 108, in _method_wrapper
    return method(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/rasa/utils/tensorflow/temp_keras_modules.py", line 191, in fit
    tmp_logs = train_function(iterator)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 780, in __call__
    result = self._call(*args, **kwds)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py", line 840, in _call
    return self._stateless_fn(*args, **kwds)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 2829, in __call__
    return graph_function._filtered_call(args, kwargs)  # pylint: disable=protected-access
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1848, in _filtered_call
    cancellation_manager=cancellation_manager)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 1924, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager))
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/function.py", line 550, in call
    ctx=ctx)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/eager/execute.py", line 60, in quick_execute
    inputs, attrs, num_outputs)
tensorflow.python.framework.errors_impl.InvalidArgumentError:  reshape cannot infer the missing input size for an empty tensor unless all specified input sizes are non-zero
	 [[{{node cond_1/then/_82/cond_1/concatenate_sparse_dense_features_active_loop_sentence/sparse_to_dense.active_loop_sentence/SparseReshape}}]] [Op:__inference_train_function_46182]

Function call stack:
train_function
```

**Command or request that led to error**:
```
python3 -m rasa train --fixed-model-name model --verbose --force
```

**Content of configuration file (config.yml)** (if relevant):
```yml
language: en

pipeline:
# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.
#   - name: WhitespaceTokenizer
#   - name: RegexFeaturizer
#   - name: LexicalSyntacticFeaturizer
#   - name: CountVectorsFeaturizer
#   - name: CountVectorsFeaturizer
#     analyzer: char_wb
#     min_ngram: 1
#     max_ngram: 4
#   - name: DIETClassifier
#     epochs: 100
#     constrain_similarities: true
#   - name: EntitySynonymMapper
#   - name: ResponseSelector
#     epochs: 100
#     constrain_similarities: true
#   - name: FallbackClassifier
#     threshold: 0.3
#     ambiguity_threshold: 0.1
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#     constrain_similarities: true
#   - name: RulePolicy
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @akelad will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by asmaier** [comment]
I tested and I have the same issue with rasa 2.5

```
rasa --version
Rasa Version      :         2.5.1
Minimum Compatible Version: 2.2.0a1
Rasa SDK Version  :         2.5.0
Rasa X Version    :         None
Python Version    :         3.7.9
Operating System  :         Linux-5.10.25-linuxkit-x86_64-with-debian-10.8
Python Path       :         /usr/local/bin/python
```
So maybe this problem is caused by my training data? Or could it be related to the fact that I'm training on CPU not GPU?

**Comment by akelad** [comment]
@asmaier could you also share the tensorflow version you have installed?

**Comment by asmaier** [comment]
My version of tensorflow:
```
# pip3 list | grep tensorflow
tensorflow                2.3.2
tensorflow-addons         0.12.0
tensorflow-estimator      2.3.0
tensorflow-hub            0.10.0
tensorflow-probability    0.11.1
tensorflow-text           2.3.0
```

**Comment by asmaier** [comment]
After many bisections I believe I found a minimal example which triggers the problem:

domain.yml
```
version: "2.0"
actions:
- send_sample_form

intents:
- send_sample

session_config:
  carry_over_slots_to_new_session: true
  session_expiration_time: 0
```
nlu.yml:
```
version: "2.0"
nlu:
- intent: send_sample
  examples: |
    - please send a product sample to me
    - please send me a sample of the product
    - send a sample to me
    - please send a sample to me
    - send a product sample please
    - I need a product sample
    - I want a product sample
    - send me a sample
    - ok thank you please send me also a sample of this product
    - great please also send a sample of this product to me
    - could you please also deliver a sample of this product to me
    - can you please dispatch a sample of this product to my registered address
    - please send a sample
```
stories.yml:
```
version: "2.0"
stories:
- story: Generated Story -7654687130300487132
  steps:
  - intent: send_sample
  - action: send_sample_form
  - active_loop: send_sample_form
```
The last line seems to be the culprit. When I delete the line `  - active_loop: send_sample_form` the tensorflow error disappears. 
 I have no clue why that is the case but I could reproduce the issue several times on my machine.

**Comment by asmaier** [comment]
So I think I figured the problem out. The problem is with the `domain.yml` file. It is missing the `forms` section. To fix the minimal example change `domain.yml` to:
```
version: "2.0"
actions:
- send_sample_form

intents:
- send_sample

session_config:
  carry_over_slots_to_new_session: true
  session_expiration_time: 0

forms:
  send_sample_form:
```
This is described at the end of https://rasa.com/docs/rasa/migration-guide#forms-1 :

> To continue to use the deprecated Rasa SDK FormActions, add a custom action with the name of your form to your domain. 

Unfortunately the error message above isn't really helpful to figure out what is going on. Also running 
```
rasa data validate
```
did not find this problem. 

So it would be nice to at least improve the error message or extend the validate command to also check for missing `forms` section.

**Comment by akelad** [comment]
wow this is a strange one 🤔  let me ask our research team why this would cause a tensorflow error to be thrown.

**Comment by koernerfelicia** [comment]
It seems if `active_loop: some_form` is specified in a story but `some_form` is not defined in the domain, `TEDPolicy` crashes due to an empty tensor. We should handle this more gracefully (see first linked issue above).

The second issue above is to warn the user if they have not defined the form but included `active_loop: some_form` in their stories.

@asmaier thanks for the detailed info. It looks like you've already figured out that you need to define the form. I'll close this issue, but feel free to re-open and continue the conversation if the problem persists despite a defined form in the domain.
