### ISSUE TITLE
rasa on google colab your terminal doesn't support cursor position requests

### ISSUE THREAD

**Issue by pleabargain** [RasaHQ/rasa#8777]
**Rasa version**:
Rasa Version      :         2.6.3
Minimum Compatible Version: 2.6.0
Rasa SDK Version  :         2.6.0
Rasa X Version    :         None
Python Version    :         3.7.10
Operating System  :         Linux-5.4.109+-x86_64-with-Ubuntu-18.04-bionic
Python Path       :         /usr/bin/python3

**Issue**:
connected to https://rasa.com/docs/rasa/jupyter-notebooks#train-a-model
trying to follow the instructions to install on google colab

Here's the code
https://colab.research.google.com/drive/1ui5UdkqMI_ft8lTgLTQ56UWVFyJnSiBX?usp=sharing
here's the github repo
https://github.com/pleabargain/ipynb/blob/master/installing_rasa_on_Colab_from_the_instructions.ipynb

**Error (including full traceback)**:
```
Welcome to Rasa! 🤖

To get started quickly, an initial project will be created.
If you need some help, check out the documentation at https://rasa.com/docs/rasa.
Now let's start! 👇🏽

t
WARNING: your terminal doesn't support cursor position requests (CPR).
```

**Command or request that led to error**:
after starting Rasa

```init rasa
```

```
config yml
# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: en

pipeline:
# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.
#   - name: WhitespaceTokenizer
#   - name: RegexFeaturizer
#   - name: LexicalSyntacticFeaturizer
#   - name: CountVectorsFeaturizer
#   - name: CountVectorsFeaturizer
#     analyzer: char_wb
#     min_ngram: 1
#     max_ngram: 4
#   - name: DIETClassifier
#     epochs: 100
#   - name: EntitySynonymMapper
#   - name: ResponseSelector
#     epochs: 100
#   - name: FallbackClassifier
#     threshold: 0.3
#     ambiguity_threshold: 0.1

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
#   - name: MemoizationPolicy
#   - name: TEDPolicy
#     max_history: 5
#     epochs: 100
#   - name: RulePolicy
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @joejuzl will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by joejuzl** [comment]
Hi @pleabargain 
Are you running a rasa command when you get this error? e.g. `rasa init`.
Or is it happening after a certain line of code is executed? e.g. `create_initial_project(project)`?

**Comment by pleabargain** [comment]
I get the error after rasa -init 

but
I'm seeing slightly different output now!
```(0lqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqk(B
(0x(B Rasa Open Source reports anonymous usage telemetry to help improve the product (0x(B
(0x(B for all its users.                                                             (0x(B
(0x(B                                                                                (0x(B
(0x(B If you'd like to opt-out, you can use `rasa telemetry disable`.                (0x(B
(0x(B To learn more, check out https://rasa.com/docs/rasa/telemetry/telemetry.       (0x(B
(0mqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqj(B
Welcome to Rasa! 🤖

To get started quickly, an initial project will be created.
If you need some help, check out the documentation at https://rasa.com/docs/rasa.
Now let's start! 👇🏽

t
WARNING: your terminal doesn't support cursor position requests (CPR).
t

Cancelled by user

Ok. You can continue setting up by running 'rasa init' 🙋🏽‍♀️
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/sentry_sdk/integrations/atexit.py", line 62, in _shutdown
    client.close(callback=integration.callback)
  File "/usr/local/lib/python3.7/dist-packages/sentry_sdk/client.py", line 375, in close
    self.flush(timeout=timeout, callback=callback)
  File "/usr/local/lib/python3.7/dist-packages/sentry_sdk/client.py", line 397, in flush
    self.transport.flush(timeout=timeout, callback=callback)
  File "/usr/local/lib/python3.7/dist-packages/sentry_sdk/transport.py", line 352, in flush
    self._worker.flush(timeout, callback)
  File "/usr/local/lib/python3.7/dist-packages/sentry_sdk/worker.py", line 96, in flush
    logger.debug("background worker flushed")
  File "/usr/lib/python3.7/logging/__init__.py", line 1366, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/usr/lib/python3.7/logging/__init__.py", line 1514, in _log
    self.handle(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 1523, in handle
    if (not self.disabled) and self.filter(record):
KeyboardInterrupt```

Maybe rasa and google colab just won't play nice with each other.



These errors are new since I last ran the noteook.

`ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
nbclient 0.5.3 requires jupyter-client>=6.1.5, but you have jupyter-client 5.3.5 which is incompatible.
jupyter-console 5.2.0 requires prompt-toolkit<2.0.0,>=1.0.0, but you have prompt-toolkit 2.0.10 which is incompatible.
google-colab 1.0.0 requires ipython~=5.5.0, but you have ipython 7.24.1 which is incompatible.
datascience 0.10.6 requires folium==0.2.1, but you have folium 0.8.3 which is incompatible.
albumentations 0.1.12 requires imgaug<0.2.7,>=0.2.5, but you have imgaug 0.2.9 which is incompatible.
Successfully installed PyJWT-2.1.0 SQLAlchemy-1.3.24 aio-pika-6.8.0 aiofiles-0.7.0 aiohttp-3.7.4 aiormq-3.3.1 apscheduler-3.7.0 async-timeout-3.0.1 attrs-20.3.0 bidict-0.21.2 boto3-1.17.90 botocore-1.20.90 colorclass-2.2.0 coloredlogs-15.0 colorhash-1.0.3 cryptography-3.4.7 dnspython-1.16.0 fbmessenger-6.0.0 gast-0.3.3 h11-0.9.0 h5py-2.10.0 httpcore-0.11.1 httptools-0.2.0 httpx-0.15.4 humanfriendly-9.1 jmespath-0.10.0 jsonpickle-2.0.0 jsonschema-3.2.0 kafka-python-2.0.2 mattermostwrapper-2.2 multidict-5.1.0 numpy-1.18.5 pamqp-2.3.0 prompt-toolkit-2.0.10 psycopg2-binary-2.8.6 pyTelegramBotAPI-3.7.9 pydot-1.4.2 pykwalify-1.8.0 pymongo-3.10.1 python-crfsuite-0.9.7 python-engineio-4.2.0 python-socketio-5.3.0 pytz-2021.1 questionary-1.9.0 rasa-2.7.0 rasa-sdk-2.7.0 redis-3.5.3 regex-2020.9.27 requests-toolbelt-0.9.1 rfc3986-1.5.0 rocketchat-API-1.15.0 ruamel.yaml-0.16.13 ruamel.yaml.clib-0.2.2 s3transfer-0.4.2 sanic-20.12.3 sanic-cors-0.10.0.post3 sanic-jwt-1.5.0 sanic-plugins-framework-0.9.5 sentry-sdk-1.1.0 sklearn-crfsuite-0.3.6 slackclient-2.9.3 sniffio-1.2.0 tensorflow-2.3.2 tensorflow-addons-0.12.1 tensorflow-estimator-2.3.0 tensorflow-hub-0.10.0 tensorflow-probability-0.11.1 tensorflow-text-2.3.0 terminaltables-3.1.0 twilio-6.50.1 tzlocal-2.1 ujson-4.0.2 urllib3-1.25.11 uvloop-0.14.0 webexteamssdk-1.6 websockets-8.1 yarl-1.6.3
WARNING: Running pip as root will break packages and permissions. You should install packages reliably by using venv: https://pip.pypa.io/warnings/venv
WARNING: Upgrading ipython, ipykernel, tornado, prompt-toolkit or pyzmq can
cause your runtime to repeatedly crash or behave in unexpected ways and is not
recommended. If your runtime won't connect or execute code, you can reset it
with "Factory reset runtime" from the "Runtime" menu.
WARNING: prompt-toolkit > 1.0.16 is incompatible with IPython < 7.0
WARNING: The following packages were previously imported in this runtime:
  [numpy,prompt_toolkit,pytz]
Run "pip install -U ipython" before restarting to avoid repeated crashes.`

**Comment by joejuzl** [comment]
I think you should be using the python rather than CLI commands to create the rasa project, as it describes here: https://rasa.com/docs/rasa/jupyter-notebooks#train-a-model

i.e. use `create_initial_project` in python code, not `rasa init` in the command line.

I assume google colab is not designed to work with interactive cli tools.

**Comment by pleabargain** [comment]
Re colab CLI
I have used and built real time CLI chats in Colab. So colab CLI is not
necessarily the issue.


I will check out your link.

 Thank you

**Comment by TyDunn** [comment]
There has not been any follow up in this issue, so I am going to close it. Please reopen if there is still an issue
