### ISSUE TITLE
`_extract_paired_histogram_specification` raises ValueError when no data is provided

### ISSUE THREAD

**Issue by JEM-Mosig** [RasaHQ/rasa#8812]
**Rasa version**:
```
Rasa Version      :         2.7.0
Minimum Compatible Version: 2.6.0
Rasa SDK Version  :         2.6.0
Rasa X Version    :         None
Python Version    :         3.8.0
Operating System  :         Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-glibc2.10
Python Path       :         /home/jem-mosig/miniconda3/envs/rasa-master/bin/python
```

**Issue**:
`_extract_paired_histogram_specification` raises ValueError when `[]` or `[[], [], ...]` is provided as data. This can cause regression tests to fail.

**Error (including full traceback)**:
```
...
/home/github/.cache/pypoetry/virtualenvs/rasa-ip_mm8IB-py3.8/lib/python3.8/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
2021-06-03 19:15:10 WARNING  rasa.model_testing  - No labels to evaluate. Skip evaluation.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/github/_work/rasa/rasa/rasa/__main__.py", line 117, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/home/github/_work/rasa/rasa/rasa/cli/test.py", line 219, in run_nlu_test
    rasa.utils.common.run_in_loop(
  File "/home/github/_work/rasa/rasa/rasa/utils/common.py", line 296, in run_in_loop
    result = loop.run_until_complete(f)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/home/github/_work/rasa/rasa/rasa/cli/test.py", line 210, in run_nlu_test_async
    await test_nlu(model_path, data_path, output, all_args)
  File "/home/github/_work/rasa/rasa/rasa/model_testing.py", line 220, in test_nlu
    await run_evaluation(
  File "/home/github/_work/rasa/rasa/rasa/nlu/test.py", line 1491, in run_evaluation
    result["entity_evaluation"] = evaluate_entities(
  File "/home/github/_work/rasa/rasa/rasa/nlu/test.py", line 923, in evaluate_entities
    plot_entity_confidences(
  File "/home/github/_work/rasa/rasa/rasa/nlu/test.py", line 376, in plot_entity_confidences
    plot_utils.plot_paired_histogram([pos_hist, neg_hist], title, hist_filename)
  File "/home/github/_work/rasa/rasa/rasa/utils/plotting.py", line 68, in inner
    return func(*args, **kwargs)
  File "/home/github/_work/rasa/rasa/rasa/utils/plotting.py", line 247, in plot_paired_histogram
    bins, tallies, x_ranges, y_range = _extract_paired_histogram_specification(
  File "/home/github/_work/rasa/rasa/rasa/utils/plotting.py", line 167, in _extract_paired_histogram_specification
    min_data_value = np.min(np.concatenate(histogram_data))
  File "<__array_function__ internals>", line 5, in amin
  File "/home/github/.cache/pypoetry/virtualenvs/rasa-ip_mm8IB-py3.8/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 2792, in amin
    return _wrapreduction(a, np.minimum, 'min', axis, None, out,
  File "/home/github/.cache/pypoetry/virtualenvs/rasa-ip_mm8IB-py3.8/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 90, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity
```
Not sure if this is related to [this issue](https://github.com/RasaHQ/rasa/issues/8147)

**Command or request that led to error**:
CI regression tests

**Comment by JEM-Mosig** [comment]
My bugfix #8813 fixed this.
