### ISSUE TITLE
Intermittent Sanic errors in deployed service

### ISSUE THREAD

**Issue by arunbg** [RasaHQ/rasa#8845]
**Rasa version**: 1.10.8

**Rasa SDK version** (if used & relevant): 1.10.2

**Rasa X version** (if used & relevant): N/A

**Python version**: 3.7

**Operating system** (windows, osx, ...): Linux (docker)

**Issue**: 

In a deployed chatbot, we're seeing the following errors intermittently from socket.io clients leading to 5xx errors. We are not able to reproduce the error locally and it is unclear if users are affected. The socket.io client widget is set to use only websockets for horizontal scaling.
After some searching, I've tried pinning the version of Sanic in the docker image to 19.9.0 but the errors remain. I am considering upgrading to Rasa 2.x soon which has Sanic > 20, which may or may not fix the issue.

**Error (including full traceback)**:
```
2021-06-07 13:06:23 Exception occurred in one of response middleware handlers
2021-06-07 13:06:23 Traceback (most recent call last):
2021-06-07 13:06:23 File "/opt/venv/lib/python3.7/site-packages/sanic/app.py", line 983, in handle_request
2021-06-07 13:06:23 request, response
2021-06-07 13:06:23 File "/opt/venv/lib/python3.7/site-packages/spf/framework.py", line 653, in _run_response_middleware_18_12
2021-06-07 13:06:23 _response = await _response
2021-06-07 13:06:23 File "/opt/venv/lib/python3.7/site-packages/sanic_cors/extension.py", line 301, in unapplied_cors_response_middleware
2021-06-07 13:06:23 set_cors_headers(req, resp, request_context, res_options)
2021-06-07 13:06:23 File "/opt/venv/lib/python3.7/site-packages/sanic_cors/core.py", line 250, in set_cors_headers
2021-06-07 13:06:23 if resp.headers is None:
2021-06-07 13:06:23 AttributeError: 'list' object has no attribute 'headers'
2021-06-07 13:06:23 Invalid response object for url b'/abc/chat/?EIO=3&transport=websocket', Expected Type: HTTPResponse, Actual Type: <class 'list'>
2021-06-07 13:06:23 Exception occurred while handling uri: 'http://example.com/abc/chat/?EIO=3&transport=websocket'
2021-06-07 13:06:23 2021-06-07 17:06:23 DEBUG rasa.core.channels.socketio - User 6856cc23708e469483de3953b9bcf707 connected to socketIO endpoint.
```

**Command or request that led to error**:
Unable to reproduce locally

**Content of configuration file (config.yml)** (if relevant):
n/a

**Content of domain file (domain.yml)** (if relevant):
n/a

**Comment by sara-tagger** [comment]
Thanks for the issue, @akelad will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by akelad** [comment]
Hi @arunbg I would indeed suggest upgrading to 2.x, we don't maintain 1.10 much anymore. Will close this issue, but feel free to re-open if you encounter the issue with 2.x as well
