### ISSUE TITLE
Cannot run nlu comparison mode with pipelines only geared towards entity extraction.

### ISSUE THREAD

**Issue by liaeh** [RasaHQ/rasa#8925]
**Rasa version**: 2.7.1

**Rasa SDK version** (if used & relevant):

**Rasa X version** (if used & relevant):

**Python version**: 3.8.8

**Operating system** (windows, osx, ...): windows

**Issue**: When running `rasa test nlu --config config1 config2` to compare performance of different pipelines on the same data, an error is raised if the configs do not have an intent classifier in the pipeline (i.e. rasa nlu model is just being used for entity extraction. I guess the same error will happen vice versa - in an NLU pipeline that only does intent classification.

Since there is no requirement to do both tasks when only using Rasa NLU, this comparison mode should work for single-task settings <span class="error">[!/images/icons/emoticons/smile.png!| /images/icons/emoticons/smile.png]</span>

**Error (including full traceback)**:

Traceback (most recent call last): File "c:\users\lhr\anaconda3\envs\rasa-py38\lib\runpy.py", line 194, in _run_module_as_main return _run_code(code, main_globals, None, File "c:\users\lhr\anaconda3\envs\rasa-py38\lib\runpy.py", line 87, in _run_code exec(code, run_globals) File "C:\Users\lhr\Anaconda3\envs\rasa-py38\Scripts\rasa.exe__main_ _ .py", line 7, in File "c:\users\lhr\anaconda3\envs\rasa-py38\lib\site-packages\rasa__main_ _.py", line 117, in main cmdline_arguments.func(cmdline_arguments) File "c:\users\lhr\anaconda3\envs\rasa-py38\lib\site-packages\rasa\cli\test.py", line 219, in run_nlu_test rasa.utils.common.run_in_loop( File "c:\users\lhr\anaconda3\envs\rasa-py38\lib\site-packages\rasa\utils\common.py", line 296, in run_in_loop result = loop.run_until_complete(f) File "c:\users\lhr\anaconda3\envs\rasa-py38\lib\asyncio\base_events.py", line 616, in run_until_complete return future.result() File "c:\users\lhr\anaconda3\envs\rasa-py38\lib\site-packages\rasa\cli\test.py", line 192, in run_nlu_test_async await compare_nlu_models( File "c:\users\lhr\anaconda3\envs\rasa-py38\lib\site-packages\rasa\model_testing.py", line 255, in compare_nlu_models training_examples_per_run = await compare_nlu( File "c:\users\lhr\anaconda3\envs\rasa-py38\lib\site-packages\rasa\nlu\test.py", line 1918, in compare_nlu f1 = result<span class="error">["intent_evaluation"]</span><span class="error">["f1_score"]</span> TypeError: 'NoneType' object is not subscriptable

**Command or request that led to error**:

rasa test nlu --config config1 config2

**Content of configuration file (config.yml)** (if relevant):

<pre># Configuration for Rasa NLU.

1\. [https://rasa.com/docs/rasa/nlu/components/](https://rasa.com/docs/rasa/nlu/components/)([https://rasa.com/docs/rasa/nlu/components/](https://rasa.com/docs/rasa/nlu/components/))
 language: en

pipeline:

1\. Flag to check whether to split intents

*   name: LanguageModelFeaturizer

1\. Name of the language model to use
 2\. choose from <span class="error">['bert', 'gpt', 'gpt2', 'xlnet', 'distilbert', 'roberta']</span>
 3\. or create a new class inheriting from this class to support your model.
 model_name: "bert"
 4\. Pre-Trained weights to be loaded
 model_weights: "bert-base-uncased"

*   name: LexicalSyntacticFeaturizer
     "features": [

1\. features for the word preceding the word being evaluated
 [ "suffix2", "prefix2", "pos2" ],
 2\. features for the word being evaluated
 [ "BOS", "EOS", "pos2" ],
 3\. features for the word following the word being evaluated
 [ "suffix2", "prefix2", "pos2" ]]

*   name: CRFEntityExtractor
     </pre>

**Content of domain file (domain.yml)** (if relevant):

**Comment by sara-tagger** [comment]
Thanks for the issue, @aeshky will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗
