### ISSUE TITLE
Finetuning a model twice in a row breaks.

### ISSUE THREAD

**Issue by koaning** [RasaHQ/rasa#8973]
I'm doing experiments with spelling errors. I have a model trained but I want to finetune against augmented data that contains spelling errors. Doing this the first time around works fine.

```
> rasa train nlu --nlu data/nlu-train-spelling.yml --finetune --epoch-fraction 0.1 --fixed-model-name spelling-epoch-1
Training NLU model...
```

When I now want to take this finetuned model and finetune it some more ... stuff breaks. 

```
> rasa train nlu --nlu data/nlu-train-spelling.yml --finetune --epoch-fraction 0.1 --fixed-model-name spelling-epoch-1
Training NLU model...
2021-06-28 13:32:29 WARNING  rasa.shared.utils.common  - The Incremental Training feature is currently experimental and might change or be removed in the future 🔬 Please share your feedback on it in the forum (https://forum.rasa.com) to help us make this feature ready for production.
Loading NLU model from models/spelling-epoch-1.tar.gz for finetuning...
2021-06-28 13:32:37 INFO     rasa.shared.nlu.training_data.training_data  - Training data stats:
2021-06-28 13:32:37 INFO     rasa.shared.nlu.training_data.training_data  - Number of intent examples: 15878 (151 distinct intents)

...

2021-06-28 13:32:37 INFO     rasa.shared.nlu.training_data.training_data  - Number of response examples: 0 (0 distinct responses)
2021-06-28 13:32:37 INFO     rasa.shared.nlu.training_data.training_data  - Number of entity examples: 0 (0 distinct entities)
2021-06-28 13:32:37 INFO     rasa.nlu.model  - Starting to train component WhitespaceTokenizer
2021-06-28 13:32:38 INFO     rasa.nlu.model  - Finished training component.
2021-06-28 13:32:38 INFO     rasa.nlu.model  - Starting to train component RegexFeaturizer
2021-06-28 13:32:38 INFO     rasa.nlu.model  - Finished training component.
2021-06-28 13:32:38 INFO     rasa.nlu.model  - Starting to train component LexicalSyntacticFeaturizer
2021-06-28 13:32:42 INFO     rasa.nlu.model  - Finished training component.
2021-06-28 13:32:42 INFO     rasa.nlu.model  - Starting to train component CountVectorsFeaturizer
/home/vincent/Development/taipo/venv/lib/python3.7/site-packages/rasa/shared/utils/io.py:97: UserWarning: New data contains vocabulary of size 21830 for attribute text which is larger than the maximum vocabulary size (8911) of the original model. Some tokens will have to be dropped in order to continue training. It is advised to re-train the model from scratch on the complete data.
Traceback (most recent call last):
  File "/home/vincent/Development/taipo/venv/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/home/vincent/Development/taipo/venv/lib/python3.7/site-packages/rasa/__main__.py", line 117, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/home/vincent/Development/taipo/venv/lib/python3.7/site-packages/rasa/cli/train.py", line 206, in run_nlu_training
    finetuning_epoch_fraction=args.epoch_fraction,
  File "/home/vincent/Development/taipo/venv/lib/python3.7/site-packages/rasa/model_training.py", line 658, in train_nlu
    finetuning_epoch_fraction=finetuning_epoch_fraction,
  File "/home/vincent/Development/taipo/venv/lib/python3.7/site-packages/rasa/utils/common.py", line 296, in run_in_loop
    result = loop.run_until_complete(f)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/home/vincent/Development/taipo/venv/lib/python3.7/site-packages/rasa/model_training.py", line 705, in train_nlu_async
    finetuning_epoch_fraction=finetuning_epoch_fraction,
  File "/home/vincent/Development/taipo/venv/lib/python3.7/site-packages/rasa/model_training.py", line 766, in _train_nlu_with_validated_data
    **additional_arguments,
  File "/home/vincent/Development/taipo/venv/lib/python3.7/site-packages/rasa/nlu/train.py", line 116, in train
    interpreter = trainer.train(training_data, **kwargs)
  File "/home/vincent/Development/taipo/venv/lib/python3.7/site-packages/rasa/nlu/model.py", line 219, in train
    component.train(working_data, self.config, **context)
  File "/home/vincent/Development/taipo/venv/lib/python3.7/site-packages/rasa/nlu/featurizers/sparse_featurizer/count_vectors_featurizer.py", line 735, in train
    self._train_with_independent_vocab(attribute_texts)
  File "/home/vincent/Development/taipo/venv/lib/python3.7/site-packages/rasa/nlu/featurizers/sparse_featurizer/count_vectors_featurizer.py", line 552, in _train_with_independent_vocab
    self._fit_loaded_vectorizer(attribute, attribute_texts[attribute])
  File "/home/vincent/Development/taipo/venv/lib/python3.7/site-packages/rasa/nlu/featurizers/sparse_featurizer/count_vectors_featurizer.py", line 593, in _fit_loaded_vectorizer
    self._update_vectorizer_vocabulary(attribute, new_vocabulary)
  File "/home/vincent/Development/taipo/venv/lib/python3.7/site-packages/rasa/nlu/featurizers/sparse_featurizer/count_vectors_featurizer.py", line 387, in _update_vectorizer_vocabulary
    self._merge_new_vocabulary_tokens(existing_vocabulary, new_vocabulary)
  File "/home/vincent/Development/taipo/venv/lib/python3.7/site-packages/rasa/nlu/featurizers/sparse_featurizer/count_vectors_featurizer.py", line 397, in _merge_new_vocabulary_tokens
    del existing_vocabulary[f"{BUFFER_SLOTS_PREFIX}{available_empty_index}"]
KeyError: 'buf_8911'
```

These are my Rasa versions. 

```
Rasa Version      :         2.6.0
Minimum Compatible Version: 2.6.0
Rasa SDK Version  :         2.7.0
Rasa X Version    :         None
Python Version    :         3.7.9
Operating System  :         Linux-5.11.0-7614-generic-x86_64-with-Pop-20.10-groovy
Python Path       :         /home/vincent/Development/taipo/venv/bin/python
```

**Comment by jupyterjazz** [comment]
It looks like the error is related to the extra buffers (`KeyError: 'buf_8911'`) that we were creating in order to account for new sparse features that appeared during fine-tuning. 
We have replaced extra buffers with [dynamic feature allocation](https://github.com/RasaHQ/rasa/pull/8985) since 2.8.0 which means this shouldn't be relevant anymore and we can close it
