### ISSUE TITLE
fix ubuntu e2e dataset problem involving special characters

### ISSUE THREAD

**Issue by twerkmeister** [RasaHQ/rasa#9024]
**Issue**:
Using the Ubuntu corpus seems not to work as it has a lot of unicode special characters in the form of `\uxxxx` in the text and the yaml parser complains about those. 

**Error (including full traceback)**:
```
2021-07-05 08:56:58 DEBUG    rasa.shared.nlu.training_data.loading  - Training data format of '../ubuntu/split/stories_block_00310.yml' is 'unk'.
2021-07-05 08:57:34 DEBUG    rasa.__main__  - Failed to run CLI command due to an exception.
Traceback (most recent call last):
  File "/home/thomas/rasa/rasa/shared/utils/validation.py", line 144, in validate_yaml_schema
    yaml_file_content, reader_type=["safe", "rt"]
  File "/home/thomas/rasa/rasa/shared/utils/io.py", line 356, in read_yaml
    return yaml_parser.load(content) or {}
  File "/home/thomas/.cache/pypoetry/virtualenvs/rasa-dSg-QxvX-py3.7/lib/python3.7/site-packages/ruamel/yaml/main.py", line 341, in load
    constructor, parser = self.get_constructor_parser(stream)
  File "/home/thomas/.cache/pypoetry/virtualenvs/rasa-dSg-QxvX-py3.7/lib/python3.7/site-packages/ruamel/yaml/main.py", line 397, in get_constructor_parser
    self.reader.stream = stream
  File "/home/thomas/.cache/pypoetry/virtualenvs/rasa-dSg-QxvX-py3.7/lib/python3.7/site-packages/ruamel/yaml/reader.py", line 117, in stream
    self.check_printable(val)
  File "/home/thomas/.cache/pypoetry/virtualenvs/rasa-dSg-QxvX-py3.7/lib/python3.7/site-packages/ruamel/yaml/reader.py", line 255, in check_printable
    'special characters are not allowed',
ruamel.yaml.reader.ReaderError: unacceptable character #xffff: special characters are not allowed
  in "<unicode string>", position 94498

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thomas/rasa/rasa/__main__.py", line 117, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/home/thomas/rasa/rasa/cli/train.py", line 59, in <lambda>
    train_parser.set_defaults(func=lambda args: run_training(args, can_exit=True))
  File "/home/thomas/rasa/rasa/cli/train.py", line 103, in run_training
    finetuning_epoch_fraction=args.epoch_fraction,
  File "/home/thomas/rasa/rasa/api.py", line 124, in train
    loop,
  File "/home/thomas/rasa/rasa/utils/common.py", line 296, in run_in_loop
    result = loop.run_until_complete(f)
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/home/thomas/rasa/rasa/model_training.py", line 100, in train_async
    domain = await file_importer.get_domain()
  File "/home/thomas/rasa/rasa/shared/utils/common.py", line 141, in decorated
    return await cache.cached_result()
  File "/home/thomas/rasa/rasa/shared/importers/importer.py", line 449, in get_domain
    self.importer.get_domain(), self._get_domain_with_e2e_actions()
  File "/home/thomas/rasa/rasa/shared/importers/importer.py", line 455, in _get_domain_with_e2e_actions
    stories = await self.get_stories()
  File "/home/thomas/rasa/rasa/shared/importers/importer.py", line 491, in get_stories
    template_variables, use_e2e, exclusion_percentage
  File "/home/thomas/rasa/rasa/shared/importers/importer.py", line 400, in get_stories
    template_variables, use_e2e, exclusion_percentage
  File "/home/thomas/rasa/rasa/shared/utils/common.py", line 141, in decorated
    return await cache.cached_result()
  File "/home/thomas/rasa/rasa/shared/importers/importer.py", line 272, in get_stories
    stories = await asyncio.gather(*stories)
  File "/home/thomas/rasa/rasa/shared/importers/rasa.py", line 58, in get_stories
    exclusion_percentage,
  File "/home/thomas/rasa/rasa/shared/importers/utils.py", line 26, in story_graph_from_paths
    files, domain, template_variables, use_e2e, exclusion_percentage
  File "/home/thomas/rasa/rasa/shared/core/training_data/loading.py", line 113, in load_data_from_files
    steps = reader.read_from_file(story_file)
  File "/home/thomas/rasa/rasa/shared/core/training_data/story_reader/yaml_story_reader.py", line 107, in read_from_file
    raise e
  File "/home/thomas/rasa/rasa/shared/core/training_data/story_reader/yaml_story_reader.py", line 103, in read_from_file
    skip_validation,
  File "/home/thomas/rasa/rasa/shared/core/training_data/story_reader/yaml_story_reader.py", line 123, in read_from_string
    rasa.shared.utils.validation.validate_yaml_schema(string, CORE_SCHEMA_FILE)
  File "/home/thomas/rasa/rasa/shared/utils/validation.py", line 147, in validate_yaml_schema
    raise YamlSyntaxException(underlying_yaml_exception=e)
rasa.shared.exceptions.YamlSyntaxException: Failed to read '../ubuntu/split/stories_block_00019.yml'. unacceptable character #xffff: special characters are not allowed
  in "../ubuntu/split/stories_block_00019.yml", position 94498

You can use https://yamlchecker.com/ to validate the YAML syntax of your file.
YamlSyntaxException: Failed to read '../ubuntu/split/stories_block_00019.yml'. unacceptable character #xffff: special characters are not allowed
  in "../ubuntu/split/stories_block_00019.yml", position 94498

You can use https://yamlchecker.com/ to validate the YAML syntax of your file.
```

**Command or request that led to error**:
```
rasa train --data ../ubuntu/split/ -c ../ubuntu/config.yml -d ../ubuntu/domain.yml --augmentation 0 --debug
```

**Potential solutions**
- [ ] make our yaml reader accept special characters
- [ ] get rid of those special characters during the dataset conversion into rasa format

**definition of done**
- [ ] the problem is fixed
- [ ] if we let our yaml reader accept special characters, tests are added
- [ ] if we change the dataset conversion, the dataset is updated in the data repo

**Comment by samsucik** [comment]
This doesn't sound like a research-owned issue to me 🤔

**Comment by dakshvar22** [comment]
+1 to Sam's opinion.

**Comment by twerkmeister** [comment]
I think this could be in research domain to prepare the experimental data properly. The data is in the rasa data repository (of whom researchers are the main users I suppose). Also the converter scripts (original dataset -> rasa format) that I have seen so far had been written by researchers

**Comment by twerkmeister** [comment]
I guess the question here is - is the yaml parser at fault or the data preparation ;)
