### ISSUE TITLE
DynamoTrackerStore integers are converted to floats

### ISSUE THREAD

**Issue by nmekionis** [RasaHQ/rasa#9044]
**Rasa version**: 2.5.0

**Rasa SDK version** (if used & relevant): 2.5.0

**Rasa X version** (if used & relevant): NA

**Python version**: Python 3.8.8

**Operating system** (windows, osx, ...): Ubuntu 18.04.5 LTS (Linux-5.4.0-1051-aws-x86_64-with-glibc2.27)

**Issue**:
When using `dynamodb` as tracker store it seems that all integers are converted to floats when tracker data is deserialized. One of the issues is that `entity` `start` and `end` indexes are converted to floats causing `/conversations/<conversation_id:path>/story` endpoint to fail.

**Error (including full traceback)**:
```
2021-07-06 09:13:30 DEBUG    rasa.server  - Traceback (most recent call last):
  File "/venv/lib/python3.8/site-packages/rasa/server.py", line 844, in retrieve_story
    stories = get_test_stories(
  File "/venv/lib/python3.8/site-packages/rasa/server.py", line 343, in get_test_stories
    return YAMLStoryWriter().dumps(story_steps, is_test_story=True)
  File "/venv/lib/python3.8/site-packages/rasa/shared/core/training_data/story_writer/yaml_story_writer.py", line 73, in dumps
    self.dump(stream, story_steps, is_appendable, is_test_story)
  File "/venv/lib/python3.8/site-packages/rasa/shared/core/training_data/story_writer/yaml_story_writer.py", line 94, in dump
    result = self.stories_to_yaml(story_steps, is_test_story)
  File "/venv/lib/python3.8/site-packages/rasa/shared/core/training_data/story_writer/yaml_story_writer.py", line 119, in stories_to_yaml
    stories.append(self.process_story_step(story_step))
  File "/venv/lib/python3.8/site-packages/rasa/shared/core/training_data/story_writer/yaml_story_writer.py", line 149, in process_story_step
    processed = self.process_event(event)
  File "/venv/lib/python3.8/site-packages/rasa/shared/core/training_data/story_writer/yaml_story_writer.py", line 163, in process_event
    return self.process_user_utterance(event, self._is_test_story)
  File "/venv/lib/python3.8/site-packages/rasa/shared/core/training_data/story_writer/yaml_story_writer.py", line 220, in process_user_utterance
    rasa.shared.core.events.format_message(
  File "/venv/lib/python3.8/site-packages/rasa/shared/core/events.py", line 109, in format_message
    return TrainingDataWriter.generate_message(
  File "/venv/lib/python3.8/site-packages/rasa/shared/nlu/training_data/formats/readerwriter.py", line 104, in generate_message
    md += text[pos : entity["start"]]
TypeError: slice indices must be integers or None or have an __index__ method

```

**Command or request that led to error**:
```
GET http://127.0.0.1:5005/conversations/test1/story
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @koaning will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗
