### ISSUE TITLE
Rasa X StoryService _reader_read_from_string should use rasa.shared.utils.io.DEFAULT_ENCODING to set tempfile

### ISSUE THREAD

**Issue by Goxiaoy** [RasaHQ/rasa#9241]
**Rasa version**: 2.8.1 **Rasa SDK version** (if used & relevant): 2.8.1 **Rasa X version** (if used & relevant): 0.42.0 **Python version**: 3.8.7 **Operating system** (windows, osx, ...): Windows-10-10.0.19041-SP0 **Issue**:

`rasax/community/services/store_service.py` Line 128-133

should be following to handle encoding

import tempfile import os import rasa.shared.utils.io with tempfile.NamedTemporaryFile(mode="w", delete=False,encoding=rasa.shared.utils.io.DEFAULT_ENCODING) as f: temp_path = f.name f.write(story_string)

**Error (including full traceback)**:

Traceback (most recent call last): File "f:\goxy\mh-chat\venv\lib\site-packages\rasa\shared\utils\io.py", line 126, in read_file return f.read() File "C:\Program Files\Python38\lib\codecs.py", line 322, in decode (result, consumed) = self._buffer_decode(data, self.errors, final) UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 705: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last): File "f:\goxy\mh-chat\venv\lib\site-packages\rasa\cli\x.py", line 496, in run_locally local.main( File "f:\goxy\mh-chat\venv\lib\site-packages\rasax\community\local.py", line 241, in main _initialize_with_local_data( File "f:\goxy\mh-chat\venv\lib\site-packages\rasax\community\local.py", line 163, in _initialize_with_local_data loop.run_until_complete( File "C:\Program Files\Python38\lib\asyncio\base_events.py", line 616, in run_until_complete return future.result() File "f:\goxy\mh-chat\venv\lib\site-packages\rasax\community\initialise.py", line 376, in inject_files_from_disk await inject_stories( File "f:\goxy\mh-chat\venv\lib\site-packages\rasax\community\initialise.py", line 134, in inject_stories story_blocks = await story_service.save_stories_from_files( File "f:\goxy\mh-chat\venv\lib\site-packages\rasax\community\services\story_service.py", line 560, in save_stories_from_files additional_blocks = await self.save_stories( File "f:\goxy\mh-chat\venv\lib\site-packages\rasax\community\services\story_service.py", line 452, in save_stories processed_stories = await self._extract_stories_yaml( File "f:\goxy\mh-chat\venv\lib\site-packages\rasax\community\services\story_service.py", line 375, in _extract_stories_yaml steps_list = self.get_story_steps( File "f:\goxy\mh-chat\venv\lib\site-packages\rasax\community\services\story_service.py", line 217, in get_story_steps return StoryService._reader_read_from_string( File "f:\goxy\mh-chat\venv\lib\site-packages\rasax\community\services\story_service.py", line 135, in _reader_read_from_string return reader.read_from_file(temp_path, skip_validation=skip_validation) File "f:\goxy\mh-chat\venv\lib\site-packages\rasa\shared\core\training_data\story_reader\yaml_story_reader.py", line 100, in read_from_file rasa.shared.utils.io.read_file( File "f:\goxy\mh-chat\venv\lib\site-packages\rasa\shared\utils\io.py", line 132, in read_file raise FileIOException( rasa.shared.exceptions.FileIOException: Failed to read file 'C:\Users\Goxy\AppData\Local\Temp\tmpfi0moy1l', could not read the file using utf-8 to decode it. Please make sure the file is stored with this encoding.

**Command or request that led to error**:

**Content of configuration file (config.yml)** (if relevant):

**Content of domain file (domain.yml)** (if relevant):

**Comment by sara-tagger** [comment]
Thanks for the issue, @rctatman will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by m-vdb** [comment]
Closing as stale
