### ISSUE TITLE
dlopen: cannot load any more object with static TLS

### ISSUE THREAD

**Issue by atptour2017** [RasaHQ/rasa#9397]
Rasa Version : 2.8.2 Minimum Compatible Version: 2.8.0 Rasa SDK Version : 2.8.1 Rasa X Version : None Python Version : 3.6.8 Operating System : Linux-3.10.0-1062.el7.x86_64-x86_64-with-centos-7.7.1908-Core Python Path : /root/.virtualenvs/rasa_all/bin/python

**Issue**: I run `pip3 install rasa` to install rasa firstly. I run `rasa init`, choose to train an initial model, then got a fatal error.

**Error (including full traceback)**:

(rasa_all) <span class="error">[root@localhost b]</span># rasa init Welcome to Rasa! [0m To get started quickly, an initial project will be created. If you need some help, check out the documentation at [https://rasa.com/docs/rasa](https://rasa.com/docs/rasa). Now let's start! ??

? Please enter a path where the project will be created <span class="error">[default: current directory]</span> Created project directory at '/root/code/prj_rasa/b'. Finished creating project structure. ? Do you want to train an initial model? ?? Yes Training an initial model...

Traceback (most recent call last): File "/root/.virtualenvs/rasa_all/lib/python3.6/site-packages/sklearn/__check_build/**init**.py", line 44, in from ._check_build import check_build # noqa ImportError: dlopen: cannot load any more object with static TLS

During handling of the above exception, another exception occurred:

Traceback (most recent call last): File "/root/.virtualenvs/rasa_all/bin/rasa", line 8, in sys.exit(main()) File "/root/.virtualenvs/rasa_all/lib/python3.6/site-packages/rasa/**main**.py", line 117, in main cmdline_arguments.func(cmdline_arguments) File "/root/.virtualenvs/rasa_all/lib/python3.6/site-packages/rasa/cli/scaffold.py", line 235, in run init_project(args, path) File "/root/.virtualenvs/rasa_all/lib/python3.6/site-packages/rasa/cli/scaffold.py", line 130, in init_project print_train_or_instructions(args, path) File "/root/.virtualenvs/rasa_all/lib/python3.6/site-packages/rasa/cli/scaffold.py", line 69, in print_train_or_instructions training_result = rasa.train(domain, config, training_files, output) File "/root/.virtualenvs/rasa_all/lib/python3.6/site-packages/rasa/api.py", line 106, in train from rasa.model_training import train_async File "/root/.virtualenvs/rasa_all/lib/python3.6/site-packages/rasa/model_training.py", line 22, in from rasa.nlu.model import Interpreter File "/root/.virtualenvs/rasa_all/lib/python3.6/site-packages/rasa/nlu/model.py", line 14, in from rasa.nlu import components, utils File "/root/.virtualenvs/rasa_all/lib/python3.6/site-packages/rasa/nlu/components.py", line 7, in import rasa.utils.train_utils File "/root/.virtualenvs/rasa_all/lib/python3.6/site-packages/rasa/utils/train_utils.py", line 40, in from rasa.utils.tensorflow.data_generator import RasaBatchDataGenerator File "/root/.virtualenvs/rasa_all/lib/python3.6/site-packages/rasa/utils/tensorflow/data_generator.py", line 9, in from rasa.utils.tensorflow.model_data import RasaModelData, Data, FeatureArray File "/root/.virtualenvs/rasa_all/lib/python3.6/site-packages/rasa/utils/tensorflow/model_data.py", line 6, in from sklearn.model_selection import train_test_split File "/root/.virtualenvs/rasa_all/lib/python3.6/site-packages/sklearn/**init**.py", line 81, in from . import __check_build # noqa: F401 File "/root/.virtualenvs/rasa_all/lib/python3.6/site-packages/sklearn/__check_build/**init**.py", line 46, in raise_build_error(e) File "/root/.virtualenvs/rasa_all/lib/python3.6/site-packages/sklearn/__check_build/**init**.py", line 41, in raise_build_error %s""" % (e, local_dir, ''.join(dir_content).strip(), msg)) ImportError: dlopen: cannot load any more object with static TLS

*   * *

Contents of /root/.virtualenvs/rasa_all/lib/python3.6/site-packages/sklearn/_ _check_build: setup.py _check_build.cpython-36m-x86_64-linux-gnu.so__init_ _ .py **pycache**

*   * *

It seems that scikit-learn has not been built correctly.

If you have installed scikit-learn from source, please do not forget to build the package before using it: run `python setup.py install` or `make` in the source directory.

If you have used an installer, please check that it is suited for your Python version, your operating system and your platform. Segmentation fault Exception ignored in: 'garbage collection' SystemError: Objects/unicodeobject.c:2373: bad argument to internal function Fatal Python error: unexpected exception during garbage collection

Thread 0x00007fd007623700 (most recent call first): File "/root/python36/lib/python3.6/threading.py", line 295 in wait File "/root/.virtualenvs/rasa_all/lib/python3.6/site-packages/sentry_sdk/_queue.py", line 180 in get File "/root/.virtualenvs/rasa_all/lib/python3.6/site-packages/sentry_sdk/worker.py", line 123 in _target File "/root/python36/lib/python3.6/threading.py", line 864 in run File "/root/python36/lib/python3.6/threading.py", line 916 in _bootstrap_inner File "/root/python36/lib/python3.6/threading.py", line 884 in _bootstrap

Current thread 0x00007fd018bbd700 (most recent call first): Aborted

**Command or request that led to error**:

rasa init

**Content of configuration file (config.yml)** (if relevant):

**Content of domain file (domain.yml)** (if relevant):

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @erohmensing will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗
