### ISSUE TITLE
Slack: TypeError: Bad body type. Expected str, got NoneType

### ISSUE THREAD

**Issue by BornaGajic** [RasaHQ/rasa#9480]
### Rasa Open Source version

2.8.1

### Rasa SDK version

2.8.1

### Rasa X version

 _No response_ 

### Python version

3.8

### What operating system are you using?

Windows

### What happened?

Everything is written [here](https://forum.rasa.com/t/getting-multiple-messages-on-slack/46865)

### Command / Request

 _No response_ 

### Relevant log output

<pre><span class="error">[1488]</span> <span class="error">[ERROR]</span> Exception occurred while handling uri: 'http://xxxxxxxxxxxx.ngrok.io/webhooks/slack/webhook'
 Traceback (most recent call last):
 File "e:\anaconda\envs\chatbot_env\lib\site-packages\sanic\app.py", line 931, in handle_request
 response = await response
 File "e:\anaconda\envs\chatbot_env\lib\site-packages\rasa\core\channels\slack.py", line 526, in webhook
 return await self.process_message(
 File "e:\anaconda\envs\chatbot_env\lib\site-packages\rasa\core\channels\slack.py", line 351, in process_message
 return response.text(
 File "e:\anaconda\envs\chatbot_env\lib\site-packages\sanic\response.py", line 224, in text
 raise TypeError(
 TypeError: Bad body type. Expected str, got NoneType)</pre>

**Comment by m-vdb** [comment]
Closing as stale
