### ISSUE TITLE
ValueError: “start” is not in list rasa

### ISSUE THREAD

**Issue by ankandrew** [RasaHQ/rasa#9486]
### Rasa Open Source version

2.8.3

### Rasa SDK version

2.8.1

### Rasa X version

`None`

### Python version

3.7

### What operating system are you using?

Linux

### What happened?

Similar to this user in [SO](https://stackoverflow.com/questions/68613192/rasa-encountering-error-with-telegram-start-is-not-in-list), I can't make Rasa to interact with telegram messages, as it gets stuck on this error. Instead of avoiding `/start` command message, it tries to analyze it.

### Command / Request

<pre>rasa run</pre>

### Relevant log output

<pre>Exception occurred while handling uri: 'http://XXXX-XX-XXX-XX-XXX.ngrok.io/webhooks/telegram/webhook'
 Traceback (most recent call last):
 File "/usr/local/lib/python3.7/dist-packages/sanic/app.py", line 931, in handle_request
 response = await response
 File "/usr/local/lib/python3.7/dist-packages/rasa/core/channels/telegram.py", line 265, in message
 metadata=metadata,
 File "/usr/local/lib/python3.7/dist-packages/rasa/core/channels/channel.py", line 89, in handler
 await app.agent.handle_message(message)
 File "/usr/local/lib/python3.7/dist-packages/rasa/core/agent.py", line 577, in handle_message
 return await processor.handle_message(message)
 File "/usr/local/lib/python3.7/dist-packages/rasa/core/processor.py", line 108, in handle_message
 await self._predict_and_execute_next_action(message.output_channel, tracker)
 File "/usr/local/lib/python3.7/dist-packages/rasa/core/processor.py", line 657, in _predict_and_execute_next_action
 action, prediction = self.predict_next_action(tracker)
 File "/usr/local/lib/python3.7/dist-packages/rasa/core/processor.py", line 379, in predict_next_action
 prediction = self._get_next_action_probabilities(tracker)
 File "/usr/local/lib/python3.7/dist-packages/rasa/core/processor.py", line 922, in _get_next_action_probabilities
 tracker, self.domain, self.interpreter
 File "/usr/local/lib/python3.7/dist-packages/rasa/core/policies/ensemble.py", line 817, in probabilities_using_best_policy
 winning_prediction = self._best_policy_prediction(tracker, domain, interpreter)
 File "/usr/local/lib/python3.7/dist-packages/rasa/core/policies/ensemble.py", line 698, in _best_policy_prediction
 for i, p in enumerate(self.policies)
 File "/usr/local/lib/python3.7/dist-packages/rasa/core/policies/ensemble.py", line 698, in 

 for i, p in enumerate(self.policies)
 File "/usr/local/lib/python3.7/dist-packages/rasa/core/policies/ensemble.py", line 730, in _get_prediction
 tracker, domain, interpreter
 File "/usr/local/lib/python3.7/dist-packages/rasa/core/policies/unexpected_intent_policy.py", line 577, in predict_action_probabilities
 domain, sequence_similarities, query_intent
 File "/usr/local/lib/python3.7/dist-packages/rasa/core/policies/unexpected_intent_policy.py", line 671, in _check_unlikely_intent
 if not self._should_check_for_intent(query_intent, domain):
 File "/usr/local/lib/python3.7/dist-packages/rasa/core/policies/unexpected_intent_policy.py", line 633, in _should_check_for_intent
 if domain.intents.index(intent) not in self.label_thresholds:
 ValueError: 'start' is not in list
 </pre>

### Extra Info

<pre>Python Version : 3.7.11
 Operating System : Linux-5.4.104+-x86_64-with-Ubuntu-18.04-bionic</pre>

**Comment by m-vdb** [comment]
Closing as stale
