### ISSUE TITLE
On window10, execute rasa x and report an error

### ISSUE THREAD

**Issue by Dei6** [RasaHQ/rasa#9556]
### Rasa Open Source version

2.8.0

### Rasa SDK version

2.8.1

### Rasa X version

0.42.0

### Python version

3.7

### What operating system are you using?

Windows

## target：
build Chinese question answering robot
## error：
rasa.shared.exceptions.FileIOException: Failed to read file 'C:\Users\cui\AppData\Local\Temp\tmpm7jti28x', could not read the file using utf-8 to decode it. Please make sure the file is stored with 
this encoding.

### Command / Request

```shell
rasa x
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "E:\pipenvs\.venv\my_robot-0BFV8NyQ\lib\site-packages\rasa\cli\x.py", line 502, in run_locally
    domain_path=domain_path,
  File "E:\pipenvs\.venv\my_robot-0BFV8NyQ\lib\site-packages\rasax\community\local.py", line 242, in main
    project_path, data_path, session, args.port, config_path, domain_path
  File "E:\pipenvs\.venv\my_robot-0BFV8NyQ\lib\site-packages\rasax\community\local.py", line 169, in _initialize_with_local_data    
    domain_path=domain_path,
  File "D:\Python3.7.7\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "E:\pipenvs\.venv\my_robot-0BFV8NyQ\lib\site-packages\rasax\community\initialise.py", line 382, in inject_files_from_disk    
    username,
  File "E:\pipenvs\.venv\my_robot-0BFV8NyQ\lib\site-packages\rasax\community\initialise.py", line 135, in inject_stories
    story_files, team, project_id, username
  File "E:\pipenvs\.venv\my_robot-0BFV8NyQ\lib\site-packages\rasax\community\services\story_service.py", line 568, in save_stories_from_files
    is_test=is_test,
  File "E:\pipenvs\.venv\my_robot-0BFV8NyQ\lib\site-packages\rasax\community\services\story_service.py", line 453, in save_stories  
    story_string, filename, domain, is_test
  File "E:\pipenvs\.venv\my_robot-0BFV8NyQ\lib\site-packages\rasax\community\services\story_service.py", line 381, in _extract_stories_yaml
    skip_validation=False,
  File "E:\pipenvs\.venv\my_robot-0BFV8NyQ\lib\site-packages\rasax\community\services\story_service.py", line 218, in get_story_steps
    reader, story_string, skip_validation=skip_validation
  File "E:\pipenvs\.venv\my_robot-0BFV8NyQ\lib\site-packages\rasax\community\services\story_service.py", line 135, in _reader_read_from_string
    return reader.read_from_file(temp_path, skip_validation=skip_validation)
  File "E:\pipenvs\.venv\my_robot-0BFV8NyQ\lib\site-packages\rasa\shared\core\training_data\story_reader\yaml_story_reader.py", line 101, in read_from_file
    filename, rasa.shared.utils.io.DEFAULT_ENCODING
  File "E:\pipenvs\.venv\my_robot-0BFV8NyQ\lib\site-packages\rasa\shared\utils\io.py", line 133, in read_file
    f"Failed to read file '{os.path.abspath(filename)}', "        
rasa.shared.exceptions.FileIOException: Failed to read file 'C:\Users\cui\AppData\Local\Temp\tmpm7jti28x', could not read the file using utf-8 to decode it. Please make sure the file is stored with 
this encoding.
```

**Comment by sara-tagger** [comment]
Thanks for the issue, @aeshky will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by Dei6** [comment]
@aeshky

**Comment by aeshky** [comment]
Thanks for raising the issue @Dei6. Can you please ask your question in the [community forum](https://forum.rasa.com/)?

**Comment by Vazerthon** [comment]
Hi @Dei6,
It looks like you're developing on Windows, I'm afraid Rasa X is not supported on that platform unless you're using WSL.
If you're able to use WSL, you should be fine. https://docs.microsoft.com/en-us/windows/wsl/about

I hope that helps!
