### ISSUE TITLE
Rasa ERROR asyncio - Task exception was never retrieved 

### ISSUE THREAD

**Issue by InnoOmnia** [RasaHQ/rasa#9582]
### Rasa Open Source version

2.2.0

### Rasa SDK version

2.2.0

### Rasa X version

 _No response_ 

### Python version

3.7

### What operating system are you using?

Linux

### What happened?

I have created a bot what uses action server. Bot works in **shell mode** but not when using botfront **webchat** client.

Full documentation can be find in this issue report [https://forum.rasa.com/t/rasa-error-asyncio-task-exception-was-never-retrieved/47583](https://forum.rasa.com/t/rasa-error-asyncio-task-exception-was-never-retrieved/47583)

### Command / Request

<pre>Action server up: 
 docker run -d -v $(pwd)/actions:/app/actions --net action-link --name action-server-prod rasa-sdk:2.2.0 

Chatbot with botfront webchat 
 docker run --name=pilleri --user 1003 -v $(pwd):/app -p "5013:5005" --net action-link rasa/rasa:2.2.0-full run -m models --enable-api --cors "*" --debug</pre>

### Relevant log output

<pre>2021-09-08 14:06:20 DEBUG rasa.core.lock_store - Deleted lock for conversation 'ccb46afa541447fda34f1f87b7954ca2'.
 2021-09-08 14:06:20 ERROR asyncio - Task exception was never retrieved
 future: 
 exception=AttributeError("'NoneType' object has no attribute 'strip'") created at /opt/venv/lib/python3.7/site-packages/engineio/asyncio_server.py:322>
 source_traceback: Object created at (most recent call last):
 File "/opt/venv/bin/rasa", line 8, in 

 sys.exit(main())
 File "/opt/venv/lib/python3.7/site-packages/rasa/__main__.py", line 116, in main
 cmdline_arguments.func(cmdline_arguments)
 File "/opt/venv/lib/python3.7/site-packages/rasa/cli/run.py", line 90, in run
 rasa.run(**vars(args))
 File "/opt/venv/lib/python3.7/site-packages/rasa/run.py", line 57, in run
 **kwargs,
 File "/opt/venv/lib/python3.7/site-packages/rasa/core/run.py", line 226, in serve_application
 workers=number_of_workers,
 File "/opt/venv/lib/python3.7/site-packages/sanic/app.py", line 1170, in run
 serve(**server_settings)
 File "/opt/venv/lib/python3.7/site-packages/sanic/server.py", line 856, in serve
 loop.run_forever()
 File "/opt/venv/lib/python3.7/site-packages/spf/framework.py", line 555, in _handle_request
 stream_callback)
 File "/opt/venv/lib/python3.7/site-packages/sanic/app.py", line 973, in handle_request
 response = await response
 File "/opt/venv/lib/python3.7/site-packages/engineio/asyncio_server.py", line 251, in handle_request
 packets = await socket.handle_get_request(environ)
 File "/opt/venv/lib/python3.7/site-packages/engineio/asyncio_socket.py", line 93, in handle_get_request
 return await getattr(self, '_upgrade_' + transport)(environ)
 File "/opt/venv/lib/python3.7/site-packages/engineio/asyncio_socket.py", line 136, in _upgrade_websocket
 return await ws(environ)
 File "/opt/venv/lib/python3.7/site-packages/engineio/async_drivers/sanic.py", line 122, in __call__
 await self.handler(self)
 File "/opt/venv/lib/python3.7/site-packages/engineio/asyncio_socket.py", line 228, in _websocket_handler
 await self.receive(pkt)
 File "/opt/venv/lib/python3.7/site-packages/engineio/asyncio_socket.py", line 47, in receive
 run_async=self.server.async_handlers)
 File "/opt/venv/lib/python3.7/site-packages/engineio/asyncio_server.py", line 423, in _trigger_event
 ret = await self.handlers<span class="error">[event]</span>(*args)
 File "/opt/venv/lib/python3.7/site-packages/socketio/asyncio_server.py", line 543, in _handle_eio_message
 await self._handle_event(sid, pkt.namespace, pkt.id, pkt.data)
 File "/opt/venv/lib/python3.7/site-packages/socketio/asyncio_server.py", line 471, in _handle_event
 data, namespace, id)
 File "/opt/venv/lib/python3.7/site-packages/socketio/asyncio_server.py", line 373, in start_background_task
 return self.eio.start_background_task(target, *args, **kwargs)
 File "/opt/venv/lib/python3.7/site-packages/engineio/asyncio_server.py", line 322, in start_background_task
 return asyncio.ensure_future(target(*args, **kwargs))
 Traceback (most recent call last):
 File "/opt/venv/lib/python3.7/site-packages/socketio/asyncio_server.py", line 476, in _handle_event_internal
 r = await server._trigger_event(data<span class="error">[0]</span>, namespace, sid, *data<span class="error">[1:]</span>)
 File "/opt/venv/lib/python3.7/site-packages/socketio/asyncio_server.py", line 504, in _trigger_event
 ret = await self.handlers<span class="error">[namespace]</span><span class="error">[event]</span>(*args)
 File "/opt/venv/lib/python3.7/site-packages/rasa/core/channels/socketio.py", line 217, in handle_message
 await on_new_message(message)
 File "/opt/venv/lib/python3.7/site-packages/rasa/core/channels/channel.py", line 85, in handler
 await app.agent.handle_message(*args, **kwargs)
 File "/opt/venv/lib/python3.7/site-packages/rasa/core/agent.py", line 528, in handle_message
 return await processor.handle_message(message)
 File "/opt/venv/lib/python3.7/site-packages/rasa/core/processor.py", line 99, in handle_message
 await self._predict_and_execute_next_action(message.output_channel, tracker)
 File "/opt/venv/lib/python3.7/site-packages/rasa/core/processor.py", line 632, in _predict_and_execute_next_action
 action, tracker, output_channel, self.nlg, prediction
 File "/opt/venv/lib/python3.7/site-packages/rasa/core/processor.py", line 776, in _run_action
 await self.execute_side_effects(events, tracker, output_channel)
 File "/opt/venv/lib/python3.7/site-packages/rasa/core/processor.py", line 671, in execute_side_effects
 await self._send_bot_messages(events, tracker, output_channel)
 File "/opt/venv/lib/python3.7/site-packages/rasa/core/processor.py", line 687, in _send_bot_messages
 await output_channel.send_response(tracker.sender_id, e.message())
 File "/opt/venv/lib/python3.7/site-packages/rasa/core/channels/channel.py", line 183, in send_response
 recipient_id, message.pop("text"), message.pop("buttons"), **message
 File "/opt/venv/lib/python3.7/site-packages/rasa/core/channels/socketio.py", line 68, in send_text_with_buttons
 message_parts = text.strip().split("\n\n") or <span class="error">[text]</span>
 AttributeError: 'NoneType' object has no attribute 'strip'

 </pre>

**Comment by sara-tagger** [comment]
Thanks for the issue, @kalkbrennerei will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by InnoOmnia** [comment]
> Thanks for the issue, @kalkbrennerei will get back to you about it soon!
> 
> ###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

Any news?

**Comment by m-vdb** [comment]
Closing as stale
