### ISSUE TITLE
phoBert is not works when training NLU

### ISSUE THREAD

**Issue by ptran1203** [RasaHQ/rasa#9650]
### Rasa Open Source version

2.8.4

### Transformers version

4.10.2

### Python version

3.8

### What operating system are you using?

Windows

### What happened?

I'm trying to config BERT model for training NLU. but when I set `model_weights=vinai/phobert-base`, it causes error

Error log
```
Traceback (most recent call last):
  File "c:\users\msi\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\msi\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\msi\AppData\Local\Programs\Python\Python38\Scripts\rasa.exe\__main__.py", line 7, in <module>
  File "c:\users\msi\appdata\local\programs\python\python38\lib\site-packages\rasa\__main__.py", line 117, in main
    cmdline_arguments.func(cmdline_arguments)
  File "c:\users\msi\appdata\local\programs\python\python38\lib\site-packages\rasa\cli\train.py", line 196, in run_nlu_training
    return train_nlu(
  File "c:\users\msi\appdata\local\programs\python\python38\lib\site-packages\rasa\model_training.py", line 646, in train_nlu
    return rasa.utils.common.run_in_loop(
  File "c:\users\msi\appdata\local\programs\python\python38\lib\site-packages\rasa\utils\common.py", line 296, in run_in_loop
    result = loop.run_until_complete(f)
  File "c:\users\msi\appdata\local\programs\python\python38\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "c:\users\msi\appdata\local\programs\python\python38\lib\site-packages\rasa\model_training.py", line 696, in train_nlu_async
    return await _train_nlu_with_validated_data(
  File "c:\users\msi\appdata\local\programs\python\python38\lib\site-packages\rasa\model_training.py", line 758, in _train_nlu_with_validated_data
    await rasa.nlu.train.train(
  File "c:\users\msi\appdata\local\programs\python\python38\lib\site-packages\rasa\nlu\train.py", line 111, in train
    interpreter = trainer.train(training_data, **kwargs)
  File "c:\users\msi\appdata\local\programs\python\python38\lib\site-packages\rasa\nlu\model.py", line 221, in train
    component.train(working_data, self.config, **context)
  File "c:\users\msi\appdata\local\programs\python\python38\lib\site-packages\rasa\nlu\utils\hugging_face\hf_transformers.py", line 732, in train
    batch_docs = self._get_docs_for_batch(batch_messages, attribute)
  File "c:\users\msi\appdata\local\programs\python\python38\lib\site-packages\rasa\nlu\utils\hugging_face\hf_transformers.py", line 675, in _get_docs_for_batch
    batch_tokens, batch_token_ids = self._get_token_ids_for_batch(
    example_tokens, example_token_ids = self._tokenize_example(
  File "c:\users\msi\appdata\local\programs\python\python38\lib\site-packages\rasa\nlu\utils\hugging_face\hf_transformers.py", line 285, in _tokenize_example
    split_token_ids, split_token_strings = self._lm_tokenize(token.text)
  File "c:\users\msi\appdata\local\programs\python\python38\lib\site-packages\rasa\nlu\utils\hugging_face\hf_transformers.py", line 172, in _lm_tokenize
    split_token_ids = self.tokenizer.encode(text, add_special_tokens=False)
  File "c:\users\msi\appdata\local\programs\python\python38\lib\site-packages\transformers\tokenization_utils_base.py", line 2153, in encode
    encoded_inputs = self.encode_plus(
  File "c:\users\msi\appdata\local\programs\python\python38\lib\site-packages\transformers\tokenization_utils_base.py", line 2472, in encode_plus
    return self._encode_plus(
  File "c:\users\msi\appdata\local\programs\python\python38\lib\site-packages\transformers\tokenization_utils.py", line 464, in _encode_plus
    return self.prepare_for_model(
  File "c:\users\msi\appdata\local\programs\python\python38\lib\site-packages\transformers\tokenization_utils_base.py", line 2922, in prepare_for_model
    encoded_inputs = self.pad(
  File "c:\users\msi\appdata\local\programs\python\python38\lib\site-packages\transformers\tokenization_utils_base.py", line 2725, in pad
    raise ValueError(
ValueError: type of None unknown: <class 'NoneType'>. Should be one of a python, numpy, pytorch or tensorflow object.
```
and I saw below message
```
The tokenizer class you load from this checkpoint is not the same type as the class this function is called from. It may result in unexpected tokenization. 
The tokenizer class you load from this checkpoint is 'PhobertTokenizer'.
The class this function is called from is 'BertTokenizer'.
```

After debugging, I changed `BertTokenizer` to `PhobertTokenizer` in `model_tokenizer_dict` [here](https://github.com/RasaHQ/rasa/blob/main/rasa/nlu/utils/hugging_face/registry.py#L50) and it works.

My config is

```yml
language: vi

pipeline:
  - name: HFTransformersNLP
    # model_weights: "bert-base-multilingual-cased"
    model_weights: "vinai/phobert-base"
    model_name: "bert"
  - name: LanguageModelTokenizer
  - name: LanguageModelFeaturizer
  - name: DIETClassifier
    epochs: 100
    constrain_similarities: true
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @yennycheung will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by ptran1203** [comment]
I will try to custom new class based on `HFTransformersNLP` to overcome this issue

**Comment by thongtruongAB** [comment]
> I tried to custom new class based on `HFTransformersNLP` and change model to `roberta` to overcome this issue
> 
> ```yaml
> language: vi
> 
> pipeline:
>   - name: components.featurizers.HFTransformersPhobert
>     # model_weights: "bert-base-multilingual-cased"
>     model_weights: "vinai/phobert-base"
>     model_name: "roberta"
>   - name: LanguageModelTokenizer
>   - name: LanguageModelFeaturizer
>   - name: DIETClassifier
>     epochs: 100
>     constrain_similarities: true
> ```

I got the same issue, can i see your "components.featurizers.HFTransformersPhobert"? Please!

**Comment by ptran1203** [comment]
I left the company :)
