### ISSUE TITLE
rasa train  报错

### ISSUE THREAD

**Issue by dengqiqi123** [RasaHQ/rasa#9702]
### Rasa Open Source version

1.10.18

### Rasa SDK version

1.10.3

### Python version

3.7

### What operating system are you using?

Windows

### What happened?

训练模型出错

### Command / Request

```shell
rasa train --domain domain.yml --data data --config config.yml --out models
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "D:\Anaconda3\envs\rasa\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Anaconda3\envs\rasa\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda3\envs\rasa\Scripts\rasa.exe\__main__.py", line 7, in <module>
  File "D:\Anaconda3\envs\rasa\lib\site-packages\rasa\__main__.py", line 92, in main
    cmdline_arguments.func(cmdline_arguments)
  File "D:\Anaconda3\envs\rasa\lib\site-packages\rasa\cli\train.py", line 76, in train
    additional_arguments=extract_additional_arguments(args),
  File "D:\Anaconda3\envs\rasa\lib\site-packages\rasa\train.py", line 50, in train
    additional_arguments=additional_arguments,
  File "D:\Anaconda3\envs\rasa\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "D:\Anaconda3\envs\rasa\lib\site-packages\rasa\train.py", line 101, in train_async
    additional_arguments,
  File "D:\Anaconda3\envs\rasa\lib\site-packages\rasa\train.py", line 188, in _train_async_internal
    additional_arguments=additional_arguments,
  File "D:\Anaconda3\envs\rasa\lib\site-packages\rasa\train.py", line 223, in _do_training
    additional_arguments=additional_arguments,
  File "D:\Anaconda3\envs\rasa\lib\site-packages\rasa\train.py", line 361, in _train_core_with_validated_data
    additional_arguments=additional_arguments,
  File "D:\Anaconda3\envs\rasa\lib\site-packages\rasa\core\train.py", line 43, in train
    policies = config.load(policy_config)
  File "D:\Anaconda3\envs\rasa\lib\site-packages\rasa\core\config.py", line 28, in load
    return PolicyEnsemble.from_dict(config_data)
  File "D:\Anaconda3\envs\rasa\lib\site-packages\rasa\core\policies\ensemble.py", line 308, in from_dict
    constr_func = registry.policy_from_module_path(policy_name)
  File "D:\Anaconda3\envs\rasa\lib\site-packages\rasa\core\registry.py", line 21, in policy_from_module_path
    module_path, lookup_path="rasa.core.policies.registry"
  File "D:\Anaconda3\envs\rasa\lib\site-packages\rasa\utils\common.py", line 231, in class_from_module_path
    m = importlib.import_module(lookup_path)
  File "D:\Anaconda3\envs\rasa\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Anaconda3\envs\rasa\lib\site-packages\rasa\core\policies\registry.py", line 5, in <module>
    from rasa.core.policies.ted_policy import TEDPolicy
  File "D:\Anaconda3\envs\rasa\lib\site-packages\rasa\core\policies\ted_policy.py", line 8, in <module>
    import tensorflow_addons as tfa
  File "D:\Anaconda3\envs\rasa\lib\site-packages\tensorflow_addons\__init__.py", line 21, in <module>
    from tensorflow_addons import activations
  File "D:\Anaconda3\envs\rasa\lib\site-packages\tensorflow_addons\activations\__init__.py", line 21, in <module>
    from tensorflow_addons.activations.gelu import gelu
  File "D:\Anaconda3\envs\rasa\lib\site-packages\tensorflow_addons\activations\gelu.py", line 24, in <module>
    get_path_to_datafile("custom_ops/activations/_activation_ops.so"))
  File "D:\Anaconda3\envs\rasa\lib\site-packages\tensorflow\python\framework\load_library.py", line 61, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Invalid name: Addons>Gelu (Did you use CamelCase?); in OpDef: name: "Addons>Gelu" input_arg { name: "features" type_attr: "T" } output_arg { name: "activations" type_attr: "T" } attr { name: "T" type: "type" allowed_values { list { type: DT_HALF type: DT_FLOAT type: DT_DOUBLE } } } attr { name: "approximate" type: "bool" default_value { b: true } }
```

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @aeshky will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by aeshky** [comment]
Hi @dengqiqi123. Try this: https://stackoverflow.com/a/62755910/5190279

**Comment by aeshky** [comment]
Closing this issue which has been marked as stale.
