### ISSUE TITLE
Running Rasa X locally throws an InvalidDomain for a duplicated session_started_metadata slot

### ISSUE THREAD

**Issue by nbeuchat** [RasaHQ/rasa#9715]
### Rasa Open Source version

2.8.7

### Rasa SDK version

2.8.2

### Rasa X version

0.42.2

### Python version

3.8

### What operating system are you using?

Linux

### What happened?

I am trying to run Rasa X locally. When running Rasa X, I get an `InvalidDomain` error stating that the `session_started_metadata` slot is duplicated. However, this is not a slot I defined in the domain and must be a rasa-defined one.

### Command / Request

<pre>`rasa x --debug --enable-api --endpoint endpoints-local.yml --cors "*"`</pre>

### Relevant log output

<pre>2021-09-24 14:18:29 DEBUG rasax.community.services.story_service - Injecting stories from file 'tests/test_rules.yml' to database (test stories: True).
 /home/nicolas/anaconda3/envs/rasax2.1/lib/python3.8/site-packages/rasa/shared/core/slots.py:311: FutureWarning: UnfeaturizedSlot is deprecated and will be removed in Rasa Open Source 3.0\. Please change the type and configure the 'influence_conversation' flag for slot 'session_started_metadata' instead.
 rasa.shared.utils.io.raise_warning(
 Traceback (most recent call last):
 File "/home/nicolas/anaconda3/envs/rasax2.1/lib/python3.8/site-packages/rasa/cli/x.py", line 496, in run_locally
 local.main(
 File "/home/nicolas/anaconda3/envs/rasax2.1/lib/python3.8/site-packages/rasax/community/local.py", line 241, in main
 _initialize_with_local_data(
 File "/home/nicolas/anaconda3/envs/rasax2.1/lib/python3.8/site-packages/rasax/community/local.py", line 163, in _initialize_with_local_data
 loop.run_until_complete(
 File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
 File "/home/nicolas/anaconda3/envs/rasax2.1/lib/python3.8/site-packages/rasax/community/initialise.py", line 376, in inject_files_from_disk
 await inject_stories(
 File "/home/nicolas/anaconda3/envs/rasax2.1/lib/python3.8/site-packages/rasax/community/initialise.py", line 143, in inject_stories
 test_story_blocks = await story_service.save_stories_from_files(
 File "/home/nicolas/anaconda3/envs/rasax2.1/lib/python3.8/site-packages/rasax/community/services/story_service.py", line 560, in save_stories_from_files
 additional_blocks = await self.save_stories(
 File "/home/nicolas/anaconda3/envs/rasax2.1/lib/python3.8/site-packages/rasax/community/services/story_service.py", line 438, in save_stories
 domain = domain_service.get_merged_domain(project_id)
 File "/home/nicolas/anaconda3/envs/rasax2.1/lib/python3.8/site-packages/rasax/community/services/domain_service.py", line 377, in get_merged_domain
 merged_domain = merged_domain.merge(CoreDomain.from_dict(domain.as_dict()))
 File "/home/nicolas/anaconda3/envs/rasax2.1/lib/python3.8/site-packages/rasa/shared/core/domain.py", line 212, in from_dict
 return cls(
 File "/home/nicolas/anaconda3/envs/rasax2.1/lib/python3.8/site-packages/rasa/shared/core/domain.py", line 637, in __init__
 self._check_domain_sanity()
 File "/home/nicolas/anaconda3/envs/rasax2.1/lib/python3.8/site-packages/rasa/shared/core/domain.py", line 1810, in _check_domain_sanity
 raise InvalidDomain(
 rasa.shared.core.domain.InvalidDomain: Duplicate slots in domain. These slots occur more than once in the domain: 'session_started_metadata'.

Sorry, something went wrong (see error above). Make sure to start Rasa X with valid data and valid domain and config files. Please, also check any warnings that popped up.
 If you need help fixing the issue visit our forum: [https://forum.rasa.com/](https://forum.rasa.com/)([https://forum.rasa.com/](https://forum.rasa.com/)).</pre>

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @b-quachtran will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by nbeuchat** [comment]
Hi @b-quachtran, do you have any update on this specific issue? I'm unable to use Rasa X at all because of it. Thanks!

**Comment by m-vdb** [comment]
Closing as stale
