### ISSUE TITLE
The following components require a SpacyPreprocessorGraphComponent: run_SpacyTokenizer1.

### ISSUE THREAD

**Issue by koaning** [RasaHQ/rasa#9919]
I just tried to run `rasa train` on the `moodbot` example that I have [here](https://github.com/RasaHQ/rasa-examples/tree/main/moodbot). It gave me this error:

```
> rasa train
┌────────────────────────────────────────────────────────────────────────────────┐
│ Rasa Open Source reports anonymous usage telemetry to help improve the product │
│ for all its users.                                                             │
│                                                                                │
│ If you'd like to opt-out, you can use `rasa telemetry disable`.                │
│ To learn more, check out https://rasa.com/docs/rasa/telemetry/telemetry.       │
└────────────────────────────────────────────────────────────────────────────────┘
/workspace/.pip-modules/lib/python3.7/site-packages/rasa/engine/recipes/recipe.py:35: FutureWarning: From Rasa Open Source 4.0.0 onwards it will be required to specify a recipe in your model configuration. Defaulting to recipe 'default.v1'. (will be removed in 3.0.0)
  "From Rasa Open Source 4.0.0 onwards it will be required to specify "
Traceback (most recent call last):
  File "/workspace/.pip-modules/bin/rasa", line 8, in <module>
    sys.exit(main())
  File "/workspace/.pip-modules/lib/python3.7/site-packages/rasa/__main__.py", line 117, in main
    cmdline_arguments.func(cmdline_arguments)
  File "/workspace/.pip-modules/lib/python3.7/site-packages/rasa/cli/train.py", line 59, in <lambda>
    train_parser.set_defaults(func=lambda args: run_training(args, can_exit=True))
  File "/workspace/.pip-modules/lib/python3.7/site-packages/rasa/cli/train.py", line 103, in run_training
    finetuning_epoch_fraction=args.epoch_fraction,
  File "/workspace/.pip-modules/lib/python3.7/site-packages/rasa/api.py", line 117, in train
    finetuning_epoch_fraction=finetuning_epoch_fraction,
  File "/workspace/.pip-modules/lib/python3.7/site-packages/rasa/model_training.py", line 179, in train
    **(nlu_additional_arguments or {}),
  File "/workspace/.pip-modules/lib/python3.7/site-packages/rasa/model_training.py", line 214, in _train_graph
    rasa.engine.validation.validate(model_configuration)
  File "/workspace/.pip-modules/lib/python3.7/site-packages/rasa/engine/validation.py", line 73, in validate
    _validate(model_configuration.train_schema, True, model_configuration.language)
  File "/workspace/.pip-modules/lib/python3.7/site-packages/rasa/engine/validation.py", line 109, in _validate
    _validate_required_components(schema)
  File "/workspace/.pip-modules/lib/python3.7/site-packages/rasa/engine/validation.py", line 499, in _validate_required_components
    f"{num_nodes} nodes are missing required components:\n"
rasa.engine.exceptions.GraphSchemaValidationException: 1 nodes are missing required components:
The following components require a SpacyPreprocessorGraphComponent: run_SpacyTokenizer1. Please add the required components to the graph.
```

It seems like we may still have some `<ComponentName>1` or `<ComponentName>2` around.

**Comment by koaning** [comment]
Ah yeah, now I see from the logs. Do the numbers indicate the order in the config?
