### ISSUE TITLE
rasa interactive breaks on main

### ISSUE THREAD

**Issue by koaning** [RasaHQ/rasa#9949]
These are the results from running `rasa interactive` on `main` on the `rasa init` project. When introducing a new entity, it seems to break. 

```
gitpod /workspace/rasa-examples/rasa-ini $ rasa interactive
2021-10-21 11:37:50 INFO     rasa.engine.training.hooks  - Starting to train component 'CountVectorsFeaturizerGraphComponent'.
2021-10-21 11:37:50 INFO     rasa.engine.training.hooks  - Finished training component 'CountVectorsFeaturizerGraphComponent'.
2021-10-21 11:37:50 INFO     rasa.engine.training.hooks  - Starting to train component 'CountVectorsFeaturizerGraphComponent'.
2021-10-21 11:37:50 INFO     rasa.engine.training.hooks  - Finished training component 'CountVectorsFeaturizerGraphComponent'.
2021-10-21 11:37:50 INFO     rasa.engine.training.hooks  - Starting to train component 'DIETClassifierGraphComponent'.
2021-10-21 11:37:50 INFO     rasa.engine.training.hooks  - Finished training component 'DIETClassifierGraphComponent'.
2021-10-21 11:37:50 INFO     rasa.engine.training.hooks  - Starting to train component 'EntitySynonymMapperGraphComponent'.
2021-10-21 11:37:50 INFO     rasa.engine.training.hooks  - Finished training component 'EntitySynonymMapperGraphComponent'.
2021-10-21 11:37:50 INFO     rasa.engine.training.hooks  - Starting to train component 'LexicalSyntacticFeaturizerGraphComponent'.
2021-10-21 11:37:50 INFO     rasa.engine.training.hooks  - Finished training component 'LexicalSyntacticFeaturizerGraphComponent'.
2021-10-21 11:37:50 INFO     rasa.engine.training.hooks  - Starting to train component 'MemoizationPolicyGraphComponent'.
2021-10-21 11:37:50 INFO     rasa.engine.training.hooks  - Finished training component 'MemoizationPolicyGraphComponent'.
2021-10-21 11:37:50 INFO     rasa.engine.training.hooks  - Starting to train component 'RegexFeaturizerGraphComponent'.
2021-10-21 11:37:50 INFO     rasa.engine.training.hooks  - Finished training component 'RegexFeaturizerGraphComponent'.
2021-10-21 11:37:50 INFO     rasa.engine.training.hooks  - Starting to train component 'ResponseSelectorGraphComponent'.
2021-10-21 11:37:50 INFO     rasa.engine.training.hooks  - Finished training component 'ResponseSelectorGraphComponent'.
2021-10-21 11:37:50 INFO     rasa.engine.training.hooks  - Starting to train component 'RulePolicyGraphComponent'.
2021-10-21 11:37:50 INFO     rasa.engine.training.hooks  - Finished training component 'RulePolicyGraphComponent'.
2021-10-21 11:37:50 INFO     rasa.engine.training.hooks  - Starting to train component 'TEDPolicyGraphComponent'.
2021-10-21 11:37:50 INFO     rasa.engine.training.hooks  - Finished training component 'TEDPolicyGraphComponent'.
2021-10-21 11:37:50 INFO     rasa.engine.training.hooks  - Starting to train component 'UnexpecTEDIntentPolicyGraphComponent'.
2021-10-21 11:37:50 INFO     rasa.engine.training.hooks  - Finished training component 'UnexpecTEDIntentPolicyGraphComponent'.
Your Rasa model is trained and saved at 'models/20211021-113748-feldspar-valley.tar.gz'.
2021-10-21 11:38:22 WARNING  rasa.shared.utils.common  - The UnexpecTED Intent Policy is currently experimental and might change or be removed in the future 🔬 Please share your feedback on it in the forum (https://forum.rasa.com) to help us make this feature ready for production.
2021-10-21 11:38:33 INFO     root  - Rasa server is up and running.
Processed story blocks: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 1316.48it/s, # trackers=1]
Processed rules: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00, 2418.16it/s, # trackers=1]
Bot loaded. Visualisation at http://localhost:5006/visualization.html .
Type a message and press enter (press 'Ctrl-c' to exit).
? Your input -> what is the price for tesla stock today                                                                                                                      
? Your NLU model classified 'what is the price for tesla stock today' with intent 'goodbye' and there are no entities, is this correct? No                                   
? What intent is it? <create_new_intent>                                                                                                                                     
? Please type the intent name: ask_stock                                                                                                                                     
? Please mark the entities using [value](type) notation what is the price for [tesla](ticker) stock today                                                                    
2021-10-21 11:40:18 ERROR    rasa.server  - An unexpected error occurred. Error: Error running graph component for node run_UnexpecTEDIntentPolicy2.
2021-10-21 11:40:18 ERROR    rasa.core.training.interactive  - An exception occurred while recording messages.
Traceback (most recent call last):
  File "/workspace/.pip-modules/lib/python3.7/site-packages/rasa/core/training/interactive.py", line 1505, in record_messages
    plot_file,
  File "/workspace/.pip-modules/lib/python3.7/site-packages/rasa/core/training/interactive.py", line 954, in _predict_till_next_listen
    result = await request_prediction(endpoint, conversation_id)
  File "/workspace/.pip-modules/lib/python3.7/site-packages/rasa/core/training/interactive.py", line 173, in request_prediction
    method="post", subpath=f"/conversations/{conversation_id}/predict"
  File "/workspace/.pip-modules/lib/python3.7/site-packages/rasa/utils/endpoints.py", line 174, in request
    response.status, response.reason, await response.content.read()
rasa.utils.endpoints.ClientResponseError: 500, Internal Server Error, body='b'{"version":"2.8.8","status":"failure","message":"An unexpected error occurred. Error: Error running graph component for node run_UnexpecTEDIntentPolicy2.","reason":"ConversationError","details":{},"help":null,"code":500}''
2021-10-21 11:40:18 ERROR    asyncio  - Task exception was never retrieved
future: <Task finished coro=<_serve_application.<locals>.run_interactive_io() done, defined at /workspace/.pip-modules/lib/python3.7/site-packages/rasa/core/training/interactive.py:1591> exception=ClientResponseError('500, Internal Server Error, body=\'b\'{"version":"2.8.8","status":"failure","message":"An unexpected error occurred. Error: Error running graph component for node run_UnexpecTEDIntentPolicy2.","reason":"ConversationError","details":{},"help":null,"code":500}\'\'')>
Traceback (most recent call last):
  File "/workspace/.pip-modules/lib/python3.7/site-packages/rasa/core/training/interactive.py", line 1598, in run_interactive_io
    conversation_id=conversation_id,
  File "/workspace/.pip-modules/lib/python3.7/site-packages/rasa/core/training/interactive.py", line 1505, in record_messages
    plot_file,
  File "/workspace/.pip-modules/lib/python3.7/site-packages/rasa/core/training/interactive.py", line 954, in _predict_till_next_listen
    result = await request_prediction(endpoint, conversation_id)
  File "/workspace/.pip-modules/lib/python3.7/site-packages/rasa/core/training/interactive.py", line 173, in request_prediction
    method="post", subpath=f"/conversations/{conversation_id}/predict"
  File "/workspace/.pip-modules/lib/python3.7/site-packages/rasa/utils/endpoints.py", line 174, in request
    response.status, response.reason, await response.content.read()
rasa.utils.endpoints.ClientResponseError: 500, Internal Server Error, body='b'{"version":"2.8.8","status":"failure","message":"An unexpected error occurred. Error: Error running graph component for node run_UnexpecTEDIntentPolicy2.","reason":"ConversationError","details":{},"help":null,"code":500}'
```

**Comment by melindaloubser1** [comment]
@tayfun This issue persists in 3.0.0rc2
