### ISSUE TITLE
Callback channel throws AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by hsm207** [RasaHQ/rasa#9951]
### Rasa Open Source version

2.8.11

### Rasa SDK version

2.8.2

### Python version

3.8

### What operating system are you using?

Linux

### What happened?

Sending a request to `webhooks/callback/webhook` throws the following exception in the rasa server logs:

```
2021-10-21 14:51:17 ERROR    rasa.core.channels.rest  - An exception occured while handling user message 'None'.
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/rasa/core/channels/rest.py", line 120, in receive
    await on_new_message(
  File "/opt/venv/lib/python3.8/site-packages/rasa/core/channels/channel.py", line 89, in handler
    await app.agent.handle_message(message)
  File "/opt/venv/lib/python3.8/site-packages/rasa/core/agent.py", line 577, in handle_message
    return await processor.handle_message(message)
  File "/opt/venv/lib/python3.8/site-packages/rasa/core/processor.py", line 96, in handle_message
    tracker = await self.log_message(message, should_save_tracker=False)
  File "/opt/venv/lib/python3.8/site-packages/rasa/core/processor.py", line 327, in log_message
    await self._handle_message_with_tracker(message, tracker)
  File "/opt/venv/lib/python3.8/site-packages/rasa/core/processor.py", line 594, in _handle_message_with_tracker
    parse_data = await self.parse_message(message, tracker)
  File "/opt/venv/lib/python3.8/site-packages/rasa/core/processor.py", line 567, in parse_message
    if text.startswith(INTENT_MESSAGE_PREFIX):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

### Command / Request

```shell
1. Run rasa init
2. Enable the rest and callback channel in credentials.yml. Set the config for the callback channel to:
callback:
  url: http://localhost:5005/webhooks/rest/webhook
3. Run rasa train
4. Run rasa run --enable-api -vv
5. Run:
curl -X POST \
     -H "Content-Type: application/json" \
     -d '{"sender":"test_user", "message":"/greet"}' \
     http://localhost:5005/webhooks/callback/webhook
```

### Relevant log output

```shell
2021-10-21 14:51:16 DEBUG    rasa.core.processor  - Received user message 'hello world' with intent '{'id': -9191520425337906859, 'name': 'greet', 'confidence': 0.8585400581359863}' and entities '[]'
2021-10-21 14:51:16 DEBUG    rasa.core.processor  - Logged UserUtterance - tracker now has 14 events.
2021-10-21 14:51:16 DEBUG    rasa.core.policies.memoization  - Current tracker state:
[state 0] user intent: greet | previous action name: action_listen
[state 1] user intent: greet | previous action name: utter_greet
[state 2] user intent: greet | previous action name: action_listen
[state 3] user intent: greet | previous action name: utter_greet
[state 4] user intent: greet | previous action name: action_listen
2021-10-21 14:51:16 DEBUG    rasa.core.policies.memoization  - There is no memorised next action
2021-10-21 14:51:17 DEBUG    rasa.core.policies.ted_policy  - TED predicted 'utter_greet' based on user intent.
2021-10-21 14:51:17 DEBUG    rasa.core.policies.rule_policy  - Current tracker state:
[state 1] user intent: greet | previous action name: action_listen
[state 2] user intent: greet | previous action name: utter_greet
[state 3] user intent: greet | previous action name: action_listen
[state 4] user intent: greet | previous action name: utter_greet
[state 5] user text: hello world | previous action name: action_listen
2021-10-21 14:51:17 DEBUG    rasa.core.policies.rule_policy  - There is no applicable rule.
2021-10-21 14:51:17 DEBUG    rasa.core.policies.rule_policy  - Current tracker state:
[state 1] user intent: greet | previous action name: action_listen
[state 2] user intent: greet | previous action name: utter_greet
[state 3] user intent: greet | previous action name: action_listen
[state 4] user intent: greet | previous action name: utter_greet
[state 5] user intent: greet | previous action name: action_listen
2021-10-21 14:51:17 DEBUG    rasa.core.policies.rule_policy  - There is a rule for the next action 'utter_greet'.
2021-10-21 14:51:17 DEBUG    rasa.core.policies.ensemble  - Made prediction using user intent.
2021-10-21 14:51:17 DEBUG    rasa.core.policies.ensemble  - Added `DefinePrevUserUtteredFeaturization(False)` event.
2021-10-21 14:51:17 DEBUG    rasa.core.policies.ensemble  - Predicted next action using policy_2_RulePolicy.
2021-10-21 14:51:17 DEBUG    rasa.core.processor  - Predicted next action 'utter_greet' with confidence 1.00.
2021-10-21 14:51:17 DEBUG    rasa.core.processor  - Policy prediction ended with events '[<rasa.shared.core.events.DefinePrevUserUtteredFeaturization object at 0x7f77f458c8e0>]'.
2021-10-21 14:51:17 DEBUG    rasa.core.processor  - Action 'utter_greet' ended with events '[BotUttered('Hey! How are you?', {"elements": null, "quick_replies": null, "buttons": null, "attachment": null, "image": null, "custom": null}, {"utter_action": "utter_greet"}, 1634827877.2163692)]'.
2021-10-21 14:51:17 DEBUG    rasa.core.lock_store  - Issuing ticket for conversation 'default'.
2021-10-21 14:51:17 DEBUG    rasa.core.lock_store  - Acquiring lock for conversation 'default'.
2021-10-21 14:51:17 DEBUG    rasa.core.lock_store  - Acquired lock for conversation 'default'.
2021-10-21 14:51:17 DEBUG    rasa.core.tracker_store  - Recreating tracker for id 'default'
2021-10-21 14:51:17 DEBUG    rasa.core.processor  - Starting a new session for conversation ID 'default'.
2021-10-21 14:51:17 DEBUG    rasa.core.processor  - Policy prediction ended with events '[]'.
2021-10-21 14:51:17 DEBUG    rasa.core.processor  - Action 'action_session_start' ended with events '[<rasa.shared.core.events.SessionStarted object at 0x7f76f7e63760>, ActionExecuted(action: action_listen, policy: None, confidence: None)]'.
2021-10-21 14:51:17 DEBUG    rasa.core.processor  - Current slot values: 
        session_started_metadata: None
2021-10-21 14:51:17 DEBUG    rasa.core.lock_store  - Deleted lock for conversation 'default'.
2021-10-21 14:51:17 ERROR    rasa.core.channels.rest  - An exception occured while handling user message 'None'.
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/rasa/core/channels/rest.py", line 120, in receive
    await on_new_message(
  File "/opt/venv/lib/python3.8/site-packages/rasa/core/channels/channel.py", line 89, in handler
    await app.agent.handle_message(message)
  File "/opt/venv/lib/python3.8/site-packages/rasa/core/agent.py", line 577, in handle_message
    return await processor.handle_message(message)
  File "/opt/venv/lib/python3.8/site-packages/rasa/core/processor.py", line 96, in handle_message
    tracker = await self.log_message(message, should_save_tracker=False)
  File "/opt/venv/lib/python3.8/site-packages/rasa/core/processor.py", line 327, in log_message
    await self._handle_message_with_tracker(message, tracker)
  File "/opt/venv/lib/python3.8/site-packages/rasa/core/processor.py", line 594, in _handle_message_with_tracker
    parse_data = await self.parse_message(message, tracker)
  File "/opt/venv/lib/python3.8/site-packages/rasa/core/processor.py", line 567, in parse_message
    if text.startswith(INTENT_MESSAGE_PREFIX):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Definition of done**
- [ ] Investigate issue
- [ ] Fix bug if straightforward
- [ ] Otherwise: Create issue for problem if it is too complicated

**Comment by tayfun** [comment]
Could be related to https://github.com/RasaHQ/rasa/issues/10504 ?

**Comment by carlad** [comment]
@hsm207 I was looking into this with @joejuzl and we think this may be a usage error on your part.

The `callback` section of the `credentials.yml` is configured with the URL of an external callback server. This is when the user wants to forward the _response_ of the http request to the rasa `rest` channel, to a custom server.

What you've done in the `credentials.yml` is configure this callback server as the rasa `rest` server.
Then, in your POST request you've sent a request to the `/webhooks/callback/webhook` endpoint, which then forwards the response to the rasa `rest` channel, which is unable to extract a `message` from the request, as it doesn't exist (because it receives the response of the initial request):
`{'recipient_id': 'test_user', 'text': 'Hey! How are you?'}`

Which then throws an error as `message` is set to `None`.

The correct usage would be to POST to the `rest` channel on the `webhook` endpoint:
`/webhooks/rest/webhook`:

```
curl -X POST \                                                                                                               ─╯
     -H "Content-Type: application/json" \
     -d '{"sender":"test_user", "message":"/greet"}' \
     http://localhost:5005/webhooks/rest/webhook
```

And the response, `[{"recipient_id":"test_user","text":"Hey! How are you?"}]`, would then be sent to external callback server URL configured in the `credentials.yml`

So I just wanted to double-check with you that this was a usage error on your part, or if there's a special case where the `callback` channel would need to use the rasa server...

**Comment by hsm207** [comment]
@carlad 

> The correct usage would be to POST to the rest channel on the webhook endpoint:

I was trying to make  a simplified version of [reminder bot](https://github.com/RasaHQ/rasa/tree/main/examples/reminderbot).  The bot's README said to make a POST to the callback channel:

```
 curl -XPOST http://localhost:5005/webhooks/callback/webhook \
    -d '{"sender": "tester", "message": "hello"}' \
    -H "Content-type: application/json"
```

Our [docs](https://rasa.com/docs/rasa/connectors/your-own-website/#callbackinput) on the callback channel also mention we can POST to it.

The use case I wanted to simulate was a smart device talking to the rasa server which then notifies the user. So, I thought the smart device will POST a notification to the callback channel which will then get forwarded to the user, in this case through the REST channel. This is similar to the [External Events](https://rasa.com/docs/rasa/reaching-out-to-user/#external-events) example in the docs, except in the docs,  it did not POST to a channel:

```
curl -H "Content-Type: application/json" -X POST \
  -d '{"name": "EXTERNAL_dry_plant", "entities": {"plant": "Orchid"}}' \
  "http://localhost:5005/conversations/user123/trigger_intent?output_channel=latest"
```

**Comment by joejuzl** [comment]
You're right you can POST to the callback channel.
The callback channel is essentially the same as the rest channel - the only different being it POSTs the bot response to a callback url instead of returning it to the user message request. 

Bot responses are a different format to the format to POST a new message to the rest channel. But even if they weren't using the rest channel input as the callback url it would mean that the bot responds to itself, which would be strange. i.e. the bot response going into an input channel.

I think external events are the way to go for your use case. Have you tried specifying the output_channel explicitly?

**Comment by hsm207** [comment]
@joejuzl 

> Have you tried specifying the output_channel explicitly?

Yes.

I have an implementation assuming the user uses the REST channel to interact with the user [here](https://github.com/hsm207/rasa_moodbot/tree/proactive). It works as expected i.e. the user gets notified despite the except being thrown.

Then, a customer extended the example by replacing the REST channel with Telegram and WhatsApp. Bot cases did not work. In the end, they found that having the device POST to the channel directly also works.

The REST channel example working despite the exception thrown made me think that it could be an unintended behaviour so I thought I'd make an issue to raise awareness.

**Comment by carlad** [comment]
> a customer extended the example by replacing the REST channel with Telegram and WhatsApp. 

@hsm207 Here do you mean the Telegram and WhatsApp/Twilio channels are configured and the Callback channel _isn't_ configured, or do you mean the Callback channel is configured with Telegram and WhatsApp URLs only? 

 I'm really curious by what the customer is wanting to achieve. They want to use Telegram and Twilio/WhatsApp as output channels, but also have a (eg) rasa-x user receive a notification in the rasa-x UI? Would that not be achieved, as @joejuzl says, by including `?output_channel=latest` in the original POST url?

**Comment by hsm207** [comment]
@carlad and I had a call and agreed that setting:

```
callback:
  url: http://localhost:5005/webhooks/rest/webhook
```

is a usage error.

The smart device should send the notification directly to the input/output channel.
