### ISSUE TITLE
importing `DefaultV1Recipe` leads to AttributeError: module 'pyparsing' has no attribute 'downcaseTokens'

### ISSUE THREAD

**Issue by koaning** [RasaHQ/rasa#9998]
On the main branch, importing this line of code in a `try_this.py` script file causes an error. 

```python
from rasa.engine.recipes.default_recipe import DefaultV1Recipe
```

This is the traceback. 

```
Traceback (most recent call last):
  File "components/test_nlu_tok.py", line 7, in <module>
    from rasa.engine.recipes.default_recipe import DefaultV1Recipe
  File "/Users/vincent/Development/rasa-examples/venv/lib/python3.7/site-packages/rasa/engine/recipes/default_recipe.py", line 24, in <module>
    from rasa.engine.constants import (
  File "/Users/vincent/Development/rasa-examples/venv/lib/python3.7/site-packages/rasa/engine/constants.py", line 3, in <module>
    from rasa.core.channels import UserMessage
  File "/Users/vincent/Development/rasa-examples/venv/lib/python3.7/site-packages/rasa/core/channels/__init__.py", line 26, in <module>
    from rasa.core.channels.hangouts import HangoutsInput  # noqa: F401
  File "/Users/vincent/Development/rasa-examples/venv/lib/python3.7/site-packages/rasa/core/channels/hangouts.py", line 9, in <module>
    from oauth2client import client
  File "/Users/vincent/Development/rasa-examples/venv/lib/python3.7/site-packages/oauth2client/client.py", line 39, in <module>
    from oauth2client import transport
  File "/Users/vincent/Development/rasa-examples/venv/lib/python3.7/site-packages/oauth2client/transport.py", line 17, in <module>
    import httplib2
  File "/Users/vincent/Development/rasa-examples/venv/lib/python3.7/site-packages/httplib2/__init__.py", line 52, in <module>
    from . import auth
  File "/Users/vincent/Development/rasa-examples/venv/lib/python3.7/site-packages/httplib2/auth.py", line 20, in <module>
    auth_param_name = token.copy().setName("auth-param-name").addParseAction(pp.downcaseTokens)
AttributeError: module 'pyparsing' has no attribute 'downcaseTokens'
```

Here's the version info. 

```
Rasa Version      :         2.8.12
Minimum Compatible Version: 2.8.9
Rasa SDK Version  :         2.8.2
Rasa X Version    :         None
Python Version    :         3.7.7
Operating System  :         Darwin-19.3.0-x86_64-i386-64bit
Python Path       :         /Users/vincent/Development/rasa-examples/venv/bin/python
```

**Comment by marisbeautypalace** [comment]
> limit the pyparsing version to 2.4.7

Hi Jean, could you be so kind and write how to limit pyparsing to version 2.4.7? Thanks in advance!

**Comment by koaning** [comment]
This issue no longer persists in Rasa 3.0rc1. Closing.
